### PR TITLE
Initial cellGameThemeInstall and cellGameThemeInstallFromBuffer

### PR DESCRIPTION
**Pull request by Megamouse**
- Probably allows a theme installation through the game
- Files are copied to /dev_hdd0/theme with cellGameThemeInstall
- Files are written to /dev_hdd0/theme with cellGameThemeInstallFromBuffer
- The files should be moved, but I don't wanna break stuff (yet)

### CODE REVIEW

**Comment by Darkhost1999** [comment]
Screenshot 2022-06-06 152733
Screenshot 2022-06-06 152926
Screenshot 2022-06-06 152946

**Comment by Gael2433** [comment]
Allows installing extra themes from Final Fantasy XIII.
Games with multiple themes only allow one to be installed, it overwrites the currently installed one from the same titleID.
Log contains the install of 4 themes.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8847879/RPCS3.log)

**Comment by Gael2433** [comment]
image

**Comment by Gael2433** [comment]
It seems that installing another theme from the same game wont overwrite the one already installed.

**Comment by Megamouse** [comment]
Please try again

**Comment by Darkhost1999** [comment]
image
image

> // Use hash to get a hopefully unique filename

Just took 3 hours to confirm they're unique filenames. We can fix real name later

**Comment by Konrad444** [comment]
DUALSENSE don"t work in MGS4 (BLES 00246) ???  :(  :(  :(

**Pull request merged**
