### PR TITLE
Restructuring repository

### PR DESCRIPTION
**Pull request by feliwir**
Hello,

i wanted to clean the entire repository up a bit by removing visual studio files and updating the cmake files. Here is a short list of things that have been done:
- Remove most submodules in favor for cmake scripts that locate the dependency
- Create the build project with cmake on every OS for every compiler
- Allow deployment -> The project can be build anywhere and the bin folder will be copied in the right place
- Don't link libraries with #pragma comment inside the code, instead link libraries with the buildsystem (cmake)
- Removed unused files (e.g. qtgui) 
- Updated to cmake 3.1 and have much cleaner project files now

I know that this commit will probably break every buildbot and will cause a lot of discussion, but please give your opinions on this everyone, so we can work on this. The reason why this is required in my opinion is that the current repository is a mess and scares beginners of in my opinion 

What still needs to be done:
- Fix build bots
- Consider changing the rsx_program_decompiler submodule aswell
- Allow optional usage of submodules for certain dependencies
- Update ReadME

### CODE REVIEW

**Comment by Bigpet** [comment]
Build instructions for Windows are now wrong in the Readme.

Keep building under Windows simple. Don't add 3 additional steps to it.

**Comment by feliwir** [comment]
Okay, i added it to the TODO list

**Comment by vlj** [comment]
I don't think we need gcm anymore. 
Otoh I prefer to keep sln system since it splits solution in several project. Cmake build is a big monolithic build which is OK for build, less for dev. 

Also I would rather have wix used for Windows deployment. It feels more "native"

**Comment by vlj** [comment]
Sorry glm not gcm

**Comment by feliwir** [comment]
If you want i can split in multiple projects that is no problem

**Comment by tambry** [comment]
So now it tries to find dependencies. What if the dependencies aren't found? Will it build them? I'm not sure if this makes much sense to have.

**Comment by feliwir** [comment]
if dependencies aren't found it will complain about missing dependencies and ask the user to add them right now. In theory cmake could fallback to submodules in that case

**Comment by Nekotekina** [comment]
I see you removed warning about 64-bit platform only. We decided to drop 32-bit support because it makes virtual memory management extremely hard, plus other reasons. You cannot alloc 4 GB virtual memory at once with VirtualAlloc/mmap on 32-bit platforms.

Also I sincerely ask to rename "src" back to "rpcs3" for now. It doesn't make big difference but will cause a lot of problems for me.

**Comment by feliwir** [comment]
I don't think this PR will get accepted anyways since it breaks all the buildbot stuff. And most people seem to be happy with the current structuring and mess

**Comment by Bigpet** [comment]
I don't think it's about being "happy with the current structuring and mess"

If your original goal was "the current repository is a mess and scares beginners of in my opinion".  
Then I personally do not think improved the situation much by having people hunt down dependencies on plaforms without package manager like Windows.

You could maybe do this in a more incremental way. I think there's some fairly uncontroversial stuff here.

* Removing the unused qt stuff
* improving the cmake scripts
* add basic deployment/packaging preparation scripts (so that I don't have to use this silly stuff: https://github.com/Bigpet/rpcs3-buildbot-tools/blob/master/Windows/package.bat )

You could get started with having those as seperate pull-requests before completely re-structuring the whole repository (sidenote: you should be able to empathize with a certain adversarial stance by people to a first-time committer who breaks all their stuff in the name of aesthetics, not to excuse that, just to explain it)

**Comment by vlj** [comment]
I agree with Bigpet here. Part of your PR are very welcomed like removing unused libs/files, removing the pragma lib and move them to vcproj/cmake ; but ditching manual visual studio build is a bit ambitious atm. In theory having a single build system is better, in practice everyone is using the visual studio version now and fix cmake way if it breaks buildbots.

**Comment by MyaniPT** [comment]
@vlj glm is still needed in Emu\RSX\GL\gl_helpers.h
It would be nice if this or a restructuring PR was made to clean up the repo a bit

**Comment by raven02** [comment]
From the above comments from different parties , i'm closing it at this moment and feel free to open another one with agreed items .

**Pull request closed without merging**
