### PR TITLE
vulkan: Enable window resizing

### PR DESCRIPTION
**Pull request by kd-11**
I had already done most of the work with the original vulkan PR, but I wasn't getting any VK_OUT_OF_DATE_KHR errors to flag a resize. I've simply added a size check to trigger the resize and it works ok. I'll need nvidia testers to check for any resource usage conflicts.

### CODE REVIEW

**Comment by raven02** [comment]
Not too sure if it is nvidia specific issue , when enlarge , it crashes the emulator . If shrink , the viewport seems not able to catch up with the resize

**Comment by raven02** [comment]
OpenGL also with similar issue when resizing . Only DX12 works prefectly at this moment.

**Comment by kd-11** [comment]
The vulkan crash I kinda expected. I'll have to sync properly before messing with the swapchain. As for opengl, most games work fine but others dont. I'll check it as well.

**Comment by kd-11** [comment]
@raven02 The crashes should be resolved now

**Comment by raven02** [comment]
Just retested . Shrink window is ok but crash instantly when enlarge window.

**Comment by kd-11** [comment]
Any messages with debug output during shrink? Might give a clue as to what is happening on NV.

**Comment by raven02** [comment]
It breaks at this one when run debug mode in vs2015

CHECK_RESULT(m_swap_chain->queuePresentKHR(m_swap_chain->get_present_queue(), &present));

**Comment by kd-11** [comment]
Probably requires that the KHR surface be recreated as well. I'll refactor some swapchain init code to make it more manageable.

**Comment by kd-11** [comment]
I'll resubmit a better solution

**Comment by kd-11** [comment]
@raven02 You can try my vulkan-wip branch. Appveyor build: https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.134

**Comment by raven02** [comment]
Nice . Let me try it out tonight.

**Comment by raven02** [comment]
@kd-11 , it still crashed when resize and click it to full screen. Do you able to click it to full screen without crash?

**Comment by kd-11** [comment]
@raven02 Does it resize okay if you dont switch to fullscreen?

**Comment by raven02** [comment]
@kd-11 no , it crashed when i resize the windows

**Comment by kd-11** [comment]
@raven02 https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.138
On amd all resizing works including fullscreen. If this still crashes i'll write a debugging build so we can dump information to the log and analyze from there.

**Comment by raven02** [comment]
Humm still the same .When you have the debug build , let me know .

**Comment by kd-11** [comment]
@raven02 Could you check the crashing function? It may not be during queuePresentKHR anymore. It'll help narrow it down.

**Comment by kd-11** [comment]
@raven02 Test https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.141 when its done building. If it crashes, attach log here. Leave debug output on if you have the sdk as well. First just try resizing, not maximizing. I'm trying to keep the official issue tracker free from too much testing clutter

**Pull request closed without merging**
