### PR TITLE
vk: Center final on-screen image

### PR DESCRIPTION
**Pull request by kd-11**
A cosmetic fix for vulkan; centers the frame output when blitting to the swapchain surface.

### CODE REVIEW

**Comment by kd-11** [comment]
Appveyor crash with no compilation error. Probably needs to be restarted.
@raven02

**Comment by raven02** [comment]
@Nekotekina , i don't have privs to restart it .Can you help ?

**Comment by raven02** [comment]
It is okay now and tested few titles look ok

**Comment by zminhquanz** [comment]
Will it help fix on NVIDIA card ?

**Pull request merged**
