### PR TITLE
Map and update pugixml with the upstream repository instead of the one from RPCS3

### PR DESCRIPTION
**Pull request by scribam**
Changelog: https://github.com/zeux/pugixml/compare/f205aaf6e1c90f1dda943edd4f82922118a85648...257fbb4e1b09b0f1a6b2020ae2db190b87c8f9c7

### CODE REVIEW

**Comment by AniLeo** [comment]
Notice fork was done to remove unnecessary files to save space, maybe this change is unwanted

**Comment by scribam** [comment]
Thank you for your feedback, I agree with you about the fact unnecessary files were removed but why specifically for the submodule `pugixml` and not the others like `cereal` for example?
The difference in size between the repository `zeux` and the one from `rpcs3` is about 3 MB, do you think it is important?

**Comment by danilaml** [comment]
Wouldn't the files still be kept in git history?

**Comment by scribam** [comment]
Yes, the files would still be kept in the git history. To switch to the `zeux` repository, you can either do a fresh `git clone` or run the following commands (for Linux):
```
git submodule deinit -f -- 3rdparty/pugixml
rm -rf .git/modules/3rdparty/pugixml
git submodule update --init
```

**Comment by Nekotekina** [comment]
Don't rebase out of sudden, takes a lot to wait for checks.

**Comment by scribam** [comment]
For some reason, AppVeyor failed (https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-6899) after the merge from master. I decided to do a rebase in order to trigger it again.

**Comment by joaozin23** [comment]
esboco

**Comment by joaozin23** [comment]
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-6901

**Comment by scribam** [comment]
@joaozin23 Logs?

**Comment by joaozin23** [comment]
esboco 3
esboco 2

**Comment by joaozin23** [comment]
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-6902

**Comment by Asinin3** [comment]
That crash at that house in Ni No Kuni has been there for quite some time AFAIK it's nothing new. Did you test before & after?

**Pull request merged**
