### PR TITLE
rsx: Epic fixes

### PR DESCRIPTION
**Pull request by kd-11**
Partially fixes the common unreal engine 3 bugs https://github.com/RPCS3/rpcs3/issues/4025
- Support for srgb (gamma corrected) texture data. Only DXT and ARGB8 are supported right now
- Support for shadowmaps when used in wierd ways. Unreal reads all the components of a shadow comparison which is interesting
- Crude support for arbitrary component shuffling on rendertarget resources. Very likely to be unused by any games and needs further polishing
- A fix for AMD polaris and newer when using strict mode. Fixes exploding vertices

Extended commits
- Reimplement TEX class of opcodes in FP
- Implement SRGB framebuffer output
- Reimplement framebuffer sampling and correctly implement color shuffling
- Implement video-out calibration (ogl only)

The extended set fixes regressions introduced by the first set of patches

### CODE REVIEW

**Comment by kd-11** [comment]
There are some regressions here, due to incorrect colorspace detection for some games (skate3 for example). I'm working on that and will push a fix before merging this.

**Comment by Asinin3** [comment]
Before/After Comparisons (Click to Expand)
<details>
 <summary>Dollar Dash Trial - Fixed Lighting</summary>

before

after
</details>

**Comment by Xcedf** [comment]
The most pleasant part Issue 3031 is affected

**Comment by Asinin3** [comment]
@Xcedf Actually Dante's Inferno kinda regressed: https://cdn.discordapp.com/attachments/345204501831221249/426056393527787526/unknown.png
https://cdn.discordapp.com/attachments/272035812277878785/426038632009302031/unknown.png
https://cdn.discordapp.com/attachments/345204501831221249/426064101526077450/2018-03-22_03-35-45.mp4

**Comment by Xcedf** [comment]
@Asinin3 yeah, but i think it regressed by somr other pr not this one, i remember someone wrote a few days ago that game became darker

**Comment by Asinin3** [comment]
@Xcedf The first screenshot in my post above is from current master. And you can see colors are fine there, they were possibly fixed by the recent typo fix. Because I know that they were broken a few weeks ago.

**Comment by Xcedf** [comment]
@Asinin3 will try to buildcombined version later

**Comment by jjsat** [comment]
Dead Space Dismemberment Demo has a regression: it fails to compile a shader. Easy to reproduce because it happens right at startup.

```
E {rsx::thread} RSX: Failed to compile shader: Fragment shader failed to compile with the following errors:
ERROR: 0:56: error(#202) No matching overloaded function found: textureProj
ERROR: 0:56: error(#216) Vector field selection out of range "xyz"
ERROR: error(#273) 2 compilation errors.  No code generated


F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
```

The shader: [FragmentProgram80.zip](https://github.com/RPCS3/rpcs3/files/1834649/FragmentProgram80.zip)

**Comment by MarioSonic2987** [comment]
GTA V is improved (Trevor's outfit is no longer red in this camera position) and regressed at the same time (water can is brown and lighting is dark).

**Before**:
image

**After**:
image

**Comment by Xcedf** [comment]
Yakuza 3 now with shadows

**Comment by Psycho-A** [comment]
This fixed Silent Hill: Downpour, but bump maps on the characters seems still to be rendered weird, and dynamic shadows are glitchy if any resolution scaling different from 720p is chosen.

**Comment by Dreadmoth** [comment]
<details>
<summary>Red Dead Redemption regression</summary>
<br>
<b>Master:</b>
</img>
<br>
<b>PR:</b>
</img>
</details>
<br>
Guess this is due to the known incorrect colorspace detection issue? Occurs with Strict Rendering Mode enabled too.

**Comment by Asinin3** [comment]
Yeah, regressions with Uncharted, Dante's Inferno, Skate 3 and RDR are all known at this point just waiting for more commits to continue testing.

**Comment by Zangetsu38** [comment]
also problem on VK format, him is broken again on X16 and 2 other 
[DX12](https://cdn.discordapp.com/attachments/306945493764669440/426150139468709910/unknown.png)
[VK](https://cdn.discordapp.com/attachments/306945493764669440/426150286999027722/unknown.png)
[OGL](https://cdn.discordapp.com/attachments/306945493764669440/426150435490103308/unknown.png)

**Comment by Xcedf** [comment]
Dante's Inferno regressed with very first commit c33f095e
removing lines from VKTextureCache.h fixes this for me
```
if (colorspace != rsx::texture_colorspace::rgb_linear)
	vk_format = get_compatible_srgb_format(vk_format);
```
same for OGL
As for RDR it regressed from a420e2e6

**Comment by kd-11** [comment]
The scope of this has grown significantly following further investigation. Relegated to WIP statud until the supporting patches are ready.

**Comment by Psycho-A** [comment]
What about this issue - https://github.com/RPCS3/rpcs3/issues/3656
Is this a typical Unreal 3 games bug too?

**Comment by MSuih** [comment]
Dante's Inferno now crashes with following error:

>E {rsx::thread} RSX: ERROR: 0:149: 'macro expansion' : Too many args in macro TEX2D_PROJ
ERROR: 0:149: 'assign' :  cannot convert from ' global highp 4-component vector of float' to ' temp highp 3-component vector of float'
ERROR: 0:149: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
>E {rsx::thread} RSX: 
>F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file Emu\RSX\VK\VKFragmentProgram.cpp:391)

Clearing the shader cache doesn't help.

**Comment by Zangetsu38** [comment]
same for MS PR

**Comment by Kravickas** [comment]
ye GT HD regression too

```
E {rsx::thread} RSX: ERROR: 0:124: 'macro expansion' : Too many args in macro TEX2D_PROJ
ERROR: 0:124: 'assign' :  cannot convert from ' global highp 4-component vector of float' to ' temp highp float'
ERROR: 0:124: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.


E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file Emu\RSX\VK\VKFragmentProgram.cpp:391)
```

**Comment by Anty0** [comment]
You've got typo in includes. In commit "video out: Set up video configuration options in fxm".
It isn't "Emu/idManager.h" but Emu/IdManager.h". (I vs i)

Can't build on Linux without this fix, as Linux is case sensitive...

**Comment by Psycho-A** [comment]
After Extended commits, some interface elements of SH: Downpour got abnormally dark.

Before:
bandicam 2018-03-24 03-52-38-976
After:
bandicam 2018-03-24 03-54-57-394
Before:
bandicam 2018-03-24 03-53-07-775
After:
bandicam 2018-03-24 03-55-32-923

**Comment by slashiee** [comment]
Supersonic Acrobatic Battle-Cars' lighting has become more accurate with the latest changes.

**Comment by guofuchou** [comment]
how to download it

**Comment by woj1993** [comment]
@guofuchou Go to Commits. Click on tick on the last one. Chose Appveyor details, artifact and chose file.

**Comment by Psycho-A** [comment]
> gl: Implement video-out calibration for gamma and dynamic range 

Where can I find it? It's an user-defined feature, or just something internal?

**Comment by whjhs1010203** [comment]
@Psycho-A 
From System.h see that.
It's default I guess, so do NOT something.

**Comment by kd-11** [comment]
Its enabled for gamma correction, but that doesnt seem to have much effect. Limited RGB does have a big effect but it simulates the washed out visuals you get on standard TV display and isnt visually pleasing imo It does add some implicit brightness to the games though - can be edited in config.yml
As for downpour getting darker menus, that will have to be investigated separately as the detection code was scrapped and now the game's texture settings are just blindly implemented in the fragment shaders with no special code or hacks. Probably caused by one setting implicitly overriding another.

**Comment by Yuuyatails** [comment]
This pull request has caused a potentially game-breaking graphical regression on **Kamen Rider: Battride War Genesis**, as after the game publishers logo screens and the loading screen, all the game shows most of the time were black screens with music running.

**Pull request merged**
