### PR TITLE
Vulkan: Avoid extra sync

### PR DESCRIPTION
**Pull request by vlj**
This PR removes the need for command buffer submission after each draw call by using per draw call descriptor set. It also removes the submission outside of the flip call.

This means a command buffer will record all clear_surface and end command until a flip command is met by RSX. When flipping an extra blitting command is emitted and then the command buffer is submitted. The thread wait for the command buffer to be executed before resuming execution.

Since there is only a sync per frame this increase performance. On my machine FPS doubled in Hitman 2.

### CODE REVIEW

**Comment by Ekaseo** [comment]
after trying the build, some games show kernel problems and crashes, im not sure if this pr causes it or the one before, Castle Crashers, DBZ Burst limit, Tales of Xillia are some examples where it happens, some games like Dragon Quest builders dont show main menu (Black screen) and The Fancy Pants adventures shows black squares that cover everything except the UI when standing still, when moving you can see some textures for some frames+

**Comment by tambry** [comment]
@Ekaseo Kernel problems? What? Could you provide a log? It'd be interesting if this caused HLE problems to show up, but it's probably something with incorrect syncing. What GPU and drivers do you have?

**Comment by kd-11** [comment]
From earlier testing, i did notice that there was some kind of limit to how much I could record before random crashes happened. The renderer has come a long way since then though, so whatever issues I had may have already been resolved.

**Comment by Ekaseo** [comment]
@tambry here is a screenshot when i try to go ingame:
castlecrasherskernelproblem
and here is the log:
https://www.sendspace.com/file/vpeglx

**Comment by SakataGintokiYT** [comment]
Fotoszok.pl

**Comment by kd-11** [comment]
@SakataGintokiYT Does your display hang during the error? It usually is only for about 2 seconds when a driver crashes and has to recover. I encountered something similar due to faulty logic letting the commandbuffer grow too large (> 1000 draw calls) earlier in the development of the vulkan backend. Let me test with AMD and see what happens.

**Comment by vlj** [comment]
Does it work better with this PR ?

**Comment by vlj** [comment]
Looks like I have the same, it looks like a driver bug from nv side

**Comment by tambry** [comment]
Should probably check if it works on AMD and if so try reporting it to Nvidia with as small of a sample as possible.

**Comment by kd-11** [comment]
Crashes on AMD as well. Its actually almost exactly the same as the case I described earlier. The GPU driver crashes and the OS has to recover the device.

**Comment by vlj** [comment]
I don't see what other resources is accessed in a concurrent maneer.

**Comment by kd-11** [comment]
The issue usually occurs if a commandbuffer is written to while executing, but i dont think thats the case here. Does vkResetCommandPool implicitly reset all command buffers? as in like vkResetCommandBuffer ?

**Comment by vlj** [comment]
Yes https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#commandbuffers-pools

I removed the VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT  on the allocator

**Comment by vlj** [comment]
Ho maybe it's because of texture cache removing texture

**Comment by kd-11** [comment]
Aren't the textures only removed after flip has finished and a new frame is starting? I havent checked the code recently though.

**Comment by vlj** [comment]
there is a 			if (num_dirty_textures > 32) purge_dirty_textures();

**Comment by kd-11** [comment]
hmm. ok. should be changed to purge after flip then. used to heppen during the merge_dirty_textures call, but that has been superseded by the new texture stuff.

**Comment by kd-11** [comment]
@vlj its not the textures. simple triangle crashes as well

**Comment by kd-11** [comment]
I dont think the command reset is working fine. Simple triangle only has one draw call, so if everything went as planned, there would be no difference between this and the old method.

**Comment by vlj** [comment]
BTW on my hd 7750 the backend fails to create swap chain because of image Usage (supported image usage bits are 0x9c)

**Comment by kd-11** [comment]
Thats a bug in the validation layer or radeon driver. It always says that. Thats because we create a swapchain with blt_dst bit set. also happens on my 270x since day 1

**Comment by vlj** [comment]
Does it work better with the 3 new commits ?

**Comment by kd-11** [comment]
Still crashes.

**Comment by vlj** [comment]
I'm a bit clueless I don't know what can be destroyed while still used by gpu.

**Comment by Ekaseo** [comment]
there are still crashes, but Dragon Quest Builders displays the main menu now, but it still crashes when trying to enter into the game and the fancy pants adventures is a bit better now, it displays some textures now even when standing still, here is a screenshot:
tfpa

**Comment by Ekaseo** [comment]
@vlj ok, i tested the newest commit and it does not crash now, almost every game works now (except Tales of xillia which crashes when trying to enter the main menu), its a bit slower and castle crashers dont work for me like it works for others, it still crashes, but because of some fragment shaders or something

**Comment by vlj** [comment]
Fullscreen is not supported ATM.

**Comment by Ekaseo** [comment]
i know, i just mention it in case its related to this, since it displays the same error, i will give you all the possible log files from a games as i can, if it helps (i will enable rsx logging too)

**Comment by raven02** [comment]
Vulkan is even faster than dx12 for DBZ burst limit. However in-game quite broken.

**Comment by kd-11** [comment]
At least its ok-ish with NV. It completely trashes the amd driver. Doesn't even do a single flip before it all goes bad. Even the triangle test crashes at startup. I'll see if I can narrow it down.

**Comment by kd-11** [comment]
I found the problem. It was actually triggered by a change in the last PR. vk::default_image_subresource_range was altered to return 100 layers and textures instead of 1. This means for simple operations such as changing image layout for blitting or presenting, the driver expects to work on 99 non-existent layers for swapchain images or textures which leads to an epic crash. Obviously the  radeon driver expects the returned number of layers/levels to be accurate (capped). You could set this back to 1 and change it to number of mipmaps / actual layers available before using it. I'm guessing the nvidia driver is capping these figures before pushing them to the actual hardware.

**Comment by vlj** [comment]
Does https://github.com/RPCS3/rpcs3/pull/1625 fix Vulkan on AMD ? I explicitly set VkImageSubresourceRange there.

**Comment by Ekaseo** [comment]
it does not crash with a kernel problem anymore, at least the games i tested that crashed before #1925

**Comment by kd-11** [comment]
I cant test https://github.com/RPCS3/rpcs3/pull/1625 right now, but I think that and this PR can be merged as soon as we have confirmation that AMD isn't crashing anymore. From my earlier testing however, fixing the subresource range should resolve the issues.

**Comment by SakataGintokiYT** [comment]
@AniLeo can you test this pr 1620 +1625.

**Comment by AniLeo** [comment]
@SakataGintokiYT Which are the games that triggered the issue? I'll test with The Fancy Pants Adventures

**Comment by SakataGintokiYT** [comment]
@AniLeo Castle Crashers , DBZ burst limit , A-men 2 ,

**Comment by AniLeo** [comment]
@SakataGintokiYT OpenGL outputs no video, only the audio (black screen). Vulkan works just fine, passed the first level without any issues (apart from the low ~20fps)

screenshot_11

OpenGL spams the log with
```
{rsx::thread} RSX: Texture params are invalid for block starting 0xC1CF3480!
{rsx::thread} RSX: Params passed w=512, h=128, mip=1, found w=128, h=512, mip=1
{rsx::thread} RSX: Texture params are invalid for block starting 0xC1C8F480!
{rsx::thread} RSX: Params passed w=512, h=128, mip=1, found w=256, h=256, mip=1
```

**Comment by SakataGintokiYT** [comment]
@AniLeo AMD isn't crashing anymore ?

**Comment by AniLeo** [comment]
@SakataGintokiYT Yes, can confirm, just tested it.
Running with an older build (the same you ran the game with on the screenshot above: 74affbb) crashes the driver, while running with the latest master (PR #1625) does not crash it. 
Using Radeon Crimson 16.3.1.

**Comment by SakataGintokiYT** [comment]
@vlj can you merged.

**Comment by kd-11** [comment]
@AniLeo Could you open an issue for the OpenGL renderer? That way it wont be forgotten

**Pull request closed without merging**
