### PR TITLE
Fixups

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Ypu can maybe rebase llvm 6 on last version here
https://github.com/llvm-mirror/llvm/commits/release_60, last commited 11 days ago

**Comment by Nekotekina** [comment]
I won't rebase release_60

**Comment by Zangetsu38** [comment]
ah, why ? it is 6.01 now, so normamly is better with few probleme fixed

**Comment by kerojin180** [comment]
Does this fix my issue with spu llvm on persona5 ? #4798

**Comment by cokabisco** [comment]
@Nekotekina  skate 3 'free skate' mode is not working can you please fix it and i will be reviewing other games too and try to keep you up to date.

**Pull request merged**
