### PR TITLE
Update TravisCI to build+upload AppImage for Linux

### PR DESCRIPTION
**Pull request by AniLeo**
Solves #2744 by @probonopd

### CODE REVIEW

**Comment by probonopd** [comment]
Did you know https://lint.travis-ci.org/?

**Comment by AniLeo** [comment]
I used it and http://www.yamllint.com/, the last one wasn't YAML syntax error, should work now

**Comment by AniLeo** [comment]
Any idea why script failed? https://travis-ci.org/RPCS3/rpcs3/jobs/239363892#L2509

**Comment by probonopd** [comment]
Missing `;`s

**Comment by AniLeo** [comment]
Derp, thanks

**Pull request merged**
