### PR TITLE
PPU LLVM: Re-add multi-threaded (multi-files) overlay module compilation

### PR DESCRIPTION
**Pull request by elad335**
Fixes https://github.com/RPCS3/rpcs3/issues/9694

Should improve MGS4 compilation time.

Fixed a regression from #14622.

### CODE REVIEW

**Comment by Ordinary205** [comment]
Demon's Souls crashes while loading PPU Modules.
PPU thread bug
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12565785/RPCS3.log.gz)

**Comment by Ordinary205** [comment]
Same error, nothing changes.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12565925/RPCS3.log.gz)

**Comment by elad335** [comment]
Maybe fixed now.

**Comment by Ordinary205** [comment]
@elad335 sorry to bother you, but can you upload the local build? Because I would like to test the build early, instead of waiting another 30 minutes.

**Comment by Ordinary205** [comment]
Demon's Souls now boots properly.
Demons Souls works
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12566109/RPCS3.log.gz)

**Comment by elad335** [comment]
Will merge, testers can test later MGS4 compilation time. For me it is 100% CPU usage. It also contains a hotfix.

**Pull request merged**
