### PR TITLE
vulkan: Add default component values in shader.

### PR DESCRIPTION
**Pull request by vlj**

### CODE REVIEW

**Comment by tambry** [comment]
Needs rebase. Also, is there anything specific that this fixes?

**Comment by kd-11** [comment]
Is there an issue with the component masks for the samplers? I know there's an issue on AMD, so is this a workaround?

**Comment by vlj** [comment]
@kd-11 As far as I know bufferView don't embed a swizzle mask in Vulkan. They do on DX12 but it looks like not all drivers follow it.
I intend to remove the swizzle mask for vertex buffer and fill missing component in shader in all backend so that it behaves the same. In case of Vulkan it should also allow to use more little vertex attribute like RGB16F (supported by AMD but likely after the next release driver or the one after) when available for instance and save some bandwitdh.

**Comment by kd-11** [comment]
@vlj The 3-component formats are unreliable for texel buffers from my earlier testing. Checking the format features for those formats shows missing texel buffer flags.
Adding the component masks in the shaders actually should help remove some of the messy workarounds we have for GL and Vulkan (using prepare_buffer_for_writing)

**Comment by raven02** [comment]
@kd-11 , do we still need this ?

**Comment by kd-11** [comment]
@raven02 Not really, there are some other somewhat "messy" workarounds on gl and vulkan concerning 3-component half-float attributes but they work just fine.

**Comment by raven02** [comment]
Alright .I'm then closing it .

**Pull request closed without merging**
