### PR TITLE
rsx: Minor fixes

### PR DESCRIPTION
**Pull request by kd-11**
Minor fixups

- gl/vk: Bump shader cache version
- gl/vk: Disable anisotropic override when strict mode enabled as it is proven to alter some games negatively
- gl: Clamp buffer view window sizes and add asserts on the same. https://github.com/RPCS3/rpcs3/issues/4284

### CODE REVIEW

**Comment by toccata10** [comment]
On the basic triangle, with Ogl, I still got a black screen with:
```
Mesa: User error: GL_INVALID_VALUE in glTextureBufferRange(offset=0 + size=2147483647 > buffer_size=268435456)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
```
On virtual fighter 5, it's just:
`Mesa: User error: GL_INVALID_VALUE in glTextureBufferRange(offset=0 + size=2147483647 > buffer_size=268435456)`

**Comment by kd-11** [comment]
Thanks. The buffer views allowed in mesa are huge! Lol. On windows amd has the largest allowed view at 256m, nvidia 128m but in mesa 2gb heaps are possible. Will push a fix soon

**Comment by kd-11** [comment]
@toccata10 Retest

**Comment by toccata10** [comment]
OGl is back to normal (=working). Thanks.

**Pull request merged**
