### PR TITLE
Add Envy and Skyline themes

### PR DESCRIPTION
**Pull request by drysalter**
Envy:

Skyline:

Skyline (Nightfall):

### CODE REVIEW

**Comment by hyperspeedgx** [comment]
Dat Skyline is gorgeous, can you add a Skyline Dark too something like the dark mode of the rpcs3 offcial page?

https://rpcs3.net/blog/

**Comment by 13xforever** [comment]
Shouldn't progress bar gradient be from 0 to 100% instead of from 0 to current position? So it will be revealed instead of stretching with the progress.

**Comment by drysalter** [comment]
> Shouldn't progress bar gradient be from 0 to 100% instead of from 0 to current position? So it will be revealed instead of stretching with the progress.

This sounds great, but I'm not sure how to accomplish it in Qt styling.

**Comment by Hopefullyidontgetbanned** [comment]
Envy looks great! Not sure about skyline tho. its mostly rpcs3's gui that makes skyline look a bit off to me.
Mostly because the mixed colors are better used in ios styled guis. But to each their own i guess

**Comment by drysalter** [comment]
Alright, themes are ready for review.

**Comment by Johndeep** [comment]
I somehow really like Envy, since the dark is not completely black (which is somehow really tiring for my eyes), but a gentle warm dark (maybe a little tad brighter, but the color palette is already top!)

It would be nice, if  anyone would revert or even fix the qt autoscaling pr #3185 to fix the crazy scaling in Linux though, then the theme might also looks nice in Linux..

**Comment by MSuih** [comment]
My complaint with Envy is the progress bar. It's fine at start, but after halfway point it turns into white text on light green background which is kind of hard to see at least on my monitor. Adding something like a dark shadow around the text would improve things, but I'm not sure if Qt supports that.

**Comment by drysalter** [comment]
> My complaint with Envy is the progress bar. It's fine at start, but after halfway point it turns into white text on light green background which is kind of hard to see at least on my monitor. Adding something like a dark shadow around the text would improve things, but I'm not sure if Qt supports that.

AFAIK there isn't a way to add shadows or outlines to text in Qt style sheets that doesn't involve some kind of hack. I've considered changing the color myself, but given the color palette it is difficult to find a color that is legible both on the gray and the green without looking conspicuous.

**Comment by HerrHulaHoop** [comment]
Sadly, this bug is not specific to Envy. Kuroi suffers from it as well. We need to figure out a way to outline text. That will solve all issues.

Progress_bar_bug

**Comment by AniLeo** [comment]
Looks good overall, just noticed something weird:
- Why is Logging level ERROR blue instead of red on Skyline themes?

**Comment by Megamouse** [comment]
You can just change the text color of the bar with
`QProgressBar {
	color: blue;
}`

**Comment by drysalter** [comment]
> You can just change the text color of the bar with
> `QProgressBar { color: blue; }`
> or the color of the filling bar with
> `QProgressBar::chunk { background: blue; }`

This is most certainly the case, but I don't see what you are trying to say. Do you mean one of those should be blue?

**Comment by Megamouse** [comment]
No, I was responding to HerrHulaHoop.
The color is irrelevant. I was merely pointing out what needs to be done to at least fix the color issue of the percentage in the bars

**Comment by JOHN30011887** [comment]
Dam, Skyline (Nightfall) looks so good :)

**Comment by AlexM71** [comment]
Really nice work, Skyline themes are gorgerous :):)

**Pull request merged**
