### PR TITLE
Restore experimental optimized operators &= |= ^= for se_t

### PR DESCRIPTION
**Pull request by Nekotekina**
They were removed approximately 3 years ago due to their rarity.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Woah 6666.

**Comment by marosis** [comment]
😈

**Comment by marosis** [comment]
Jéžiš tak se neposerte kvůli každé píčovině kokoti

**Comment by RainbowCookie32** [comment]
Please keep comments in English so everyone can understand and participate

**Pull request merged**
