### PR TITLE
Implement Real PS Move Handler

### LINKED ISSUE #2297: PS Move controller support/emulation
Today we got first working game, which needs it :P
http://www.emunewz.net/forum/showthread.php?tid=173914&pid=240811#pid240811

### PR DESCRIPTION
**Pull request by Megamouse**
### Changes
- Adds a **"Real" Move handler** to the IO tab in the settings (uses players 7,6,5 and 4, just like the "Fake" move).
- Adds real **PS Move camera tracking** (well, as good as I was able to for now).
Adds a tracker configuration dialog for setting up the correct LED colors and thresholds etc.
- Adds a "Real" PS Move emulated USB device config similar to the "Fake" PS Move device config.
This is needed because the real devices are basically also just virtual DS3s and can be mapped anyway you want.
- Adds a new **HID pad handler** for the **PS Move**.
You need to pair your PS Move on Windows first (see below).
It only works properly while the device is not connected via USB. I haven't had the patience to fix that.
- Adds support for the **PS Move CECH-ZCM1** (that's the PS3 version)
- Adds support for the **PS Move CECH-ZCM2** (that's the PS4 version)
- Adds support for the **PS Move Sharpshooter** (including remapping the buttons in the pad dialog if used as DS3)
- Adds support for the **PS Move Racing Wheel** (including remapping the buttons in the pad dialog if used as DS3)

### Pairing a PS Move on Windows
After searching for a while, I think the PS Move Api works best for pairing a PS Move on windows
- Download the latest PS Move Api release at https://github.com/thp/psmoveapi/releases
- For me this is: **psmoveapi-4.0.12-windows-msvc2017-x64.zip**
- Unzip the file into a new directory (for example into a subdirectory of your download folder)
- Connect your PS Move to the Windows PC via USB
- Open the windows command prompt (or powershell) as administrator
- Navigate to the `/bin` directory and Run `psmove.exe pair`
- Follow **all** the steps in the terminal until the tool prints `"Pairing of #1 succeeded!"` and terminates
- You should only have to pair the device with Windows once, unless you pair it with another device again.
- If you have any issues, try to follow the pairing guide: https://psmoveapi.readthedocs.io/en/latest/pairing.html

### PS EYE
The PS eye doesn't work on windows at the moment.
So you have to connect a different camera and select the PS EYE in the IO config tab.
You also have to select the Qt camera handler.

Fixes #2297

### CODE REVIEW

**Comment by legend800** [comment]
First, thanks for getting this implemented. I've been waiting for this day (as a big rail shooter fan). 

Hopefully, you can fix the compiling issues so testing can begin. I'm on Windows if you have a build available. 

For your PS Move write-up, two notes:
1. Run "./psmove.exe pair" gives me an error. "psmove.exe pair" works fine
2. You have to move the dll into the exe dir else you'll get this error:


I got both my moves paired and ready to go!


I'm not clear though what to do with the PS Eye. Do I just plug it in and then it'll work?

**Comment by Megamouse** [comment]
The PS eye doesn't work on windows at the moment.
So you have to connect a different camera and select the PS EYE in the IO config tab.
You also have to select the Qt camera handler.

**Comment by legend800** [comment]
Ok, got the build, followed all the instructions, rpcs3 sees the cam and move but the "PS Move Tracker" tool doesn't trigger the globe to illuminate. The game doesn't show the PS Move cali screen either like there's no move connected. If I switch Move Handler back to "Mouse", the cali screen shows up fine. Log and pics:

[RPCS3.log.gz](https://github.com/user-attachments/files/16319138/RPCS3.log.gz)
2024-07-19 23_49_45-Configure Emulated PS Move (Real)

2024-07-19 23_49_04-Settings_  NPUB30760  The House Of The Dead_ OVERKILL™ Extended Cut  US DL
2024-07-19 23_49_18-PS3

**Comment by Megamouse** [comment]
You have to configure the hue and the thresholds in the tracker config dialog first.

**Comment by Megamouse** [comment]
Also, it has to be player 7, as mentioned in the first sentence

**Comment by legend800** [comment]
Got it. Ok, it's working fine in the tracker config now. Really cool app. 

I saw that line but I wasn't sure what "uses players 7,6...." means. Seemed like it was more of a implementation comment vs a user step. I've used fake mouse for years and never selected anything in the "Gamepad Settings" before, so not sure what "just like the Fake move" note means. I would suggest a tweak like:

**_Adds a "Real" Move handler to the IO tab in the settings. You'll need to go to Gamepad Settings, select any player 4-7, select "PS Move" from the Handlers dropdown and confirm your PS Move is recognized in the Devices selector._**

I only have HOD Overkill right now and while I can get the Cali screen to show and btn input is recognized, the sphere never lights up and there's no tracking. This could just be an existing issue with this game, since even with Mouse, similar behavior - buttons work but no tracking like some lib isn't getting initialize on this one. Log attached.

[RPCS3.log.gz](https://github.com/user-attachments/files/16319271/RPCS3.log.gz)

**Comment by Megamouse** [comment]
I didn't change anything that actually improves games.
This will only work if the game already works with the other move handlers

**Comment by Darkhost1999** [comment]
This dialog goes off-screen for my TV. I'm using a 200% scale, 4k res on a 55" display
image
Save, close, apply do not show and I can't resize the dialog. I tried to resize and it does the Windows animation for minimum height already achieved

**Comment by hyperionxze** [comment]
hello im new to github. can u please tell me how i can download your build.

**Comment by thecatontheceiling** [comment]
> hello im new to github. can u please tell me how i can download your build.
> 

Actions tab, find the latest action which builds this pull request and scroll down to the Artifacts section to download the build

**Comment by hyperionxze** [comment]
> > hello im new to github. can u please tell me how i can download your build.
> 
> https://github.com/RPCS3/rpcs3/blob/master/.github%2FPR-BUILD.md

i followed the instructions until the last step where it tells to download the artifact. i dont see any artifact that i can download.

**Comment by hyperionxze** [comment]
> > hello im new to github. can u please tell me how i can download your build.
> 
> https://github.com/RPCS3/rpcs3/blob/master/.github%2FPR-BUILD.md

tysm ♥

**Comment by hyperionxze** [comment]
image
how do i get it so that the game detects my camera. also why does the light go out when i leave ps move tracker.

**Comment by Megamouse** [comment]
It's explained in the description above.
Also, the ps move needs to be actively updated every 4 seconds or the light goes out on its own.

**Comment by hyperionxze** [comment]
> It's explained in the description above. Also, the ps move needs to be actively updated every 4 seconds or the light goes out on its own.

the light goes out for me even though i give an inbput every 4 seconds

**Comment by hyperionxze** [comment]
> It's explained in the description above. Also, the ps move needs to be actively updated every 4 seconds or the light goes out on its own.

oh sorry about that. despite turning on the camera like mentioned it shows a green screen ingame, whereas the ps tracker works completely fine. do you know as to why?

**Comment by IAMASIGMite** [comment]
Does anyone still have this build of RPCS3?  If so, please send it to me via discord: mugny

**Comment by Darkhost1999** [comment]
BTHPS3 may interfere with PSMove API if you have used a DualShock 3 controller before using Nefarius Software Solutions.

Screenshot 2024-11-14 105559
If working correctly you'll see an unspecified device with the following

Screenshot 2024-11-14 115107

**Pull request merged**
