### PR TITLE
vk: Some shader improvements

### PR DESCRIPTION
**Pull request by kd-11**
- Properly match image_type->image_view_type for placeholder dummy textures.

Fixes https://github.com/RPCS3/rpcs3/issues/8674

### CODE REVIEW

**Comment by AniLeo** [comment]
Cube now works without asserting driver, but it floods this validation error

`E {RSX [0x000c774]} RSX: ERROR: [Validation] Code 0 : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdatedated ] Object 0: handle = 0x14700000001470, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x50363c8d | VkDescriptorSet 0x14700000001470[] encountered the following validation error at vkCmdDraw() time: Descriptor in binding #2 index 0 requires an image view of type VK_IMAGE_VIEW_TYPE_2D_ARRAY but got VK_IMAGE_VIEW_TYPE_2D.`

**Comment by AniLeo** [comment]
Working well now :+1:

**Comment by xddxd** [comment]
Still can reproduce #8159

**Comment by kd-11** [comment]
@xddxd How consistent does it fail for you? Does it crash ingame or only when pre-loading shaders? I need some more info before I can pass it on to AMD.

**Comment by xddxd** [comment]
The trick to get it to crash on GT5 is to make the interpreter initialize while there are tons of shaders not compiled yet. Like have a shader cache for the menus and loading screens, but no cache for the track and cars themselves. Then go to a race and it should crash, it's not very consistent, but it's there.

**Pull request merged**
