### PR TITLE
invalid arguments

### PR DESCRIPTION
**Pull request by kamer1337**
fix issue #3448

### CODE REVIEW

**Comment by Nekotekina** [comment]
This problem will be discussed in #3327

**Comment by MarioSonic2987** [comment]
Fixes GTA V regression (doesn't go ingame):

image

**Comment by Margen67** [comment]
Why was this closed?

**Comment by kamer1337** [comment]
latest nekoteka pr fixed the issue

**Comment by Asinin3** [comment]
Shouldn't issues only be closed after the PR gets merged? Not a huge problem though.

**Pull request closed without merging**
