### PR TITLE
Force order of initialization for utils::version

### PR DESCRIPTION
**Pull request by predator5047**
Because s_gui_listener depends on rpcs3::version it is possible for
s_gui_listener to be initialized before rpcs3::version causing a null
pointer dereference.
Replacing with a function call that has a local static
variable guarantees correct order of initialization.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Function doesn't make sense there. Version object has constexpr constructor, it means it should be constantly initialized.

**Comment by predator5047** [comment]
The problem is that the order of initialization is random. On my pc  s_gui_listener is initialized before witch causes a crash.

**Comment by Nekotekina** [comment]
It is not random.
https://stackoverflow.com/questions/31468247/should-constexpr-initialization-happen-before-other-initialization
Check your compiler version

**Comment by predator5047** [comment]
With MSVC++ 14.1  (visual studio 2017) s_gui_listener is initialized before.

**Comment by Nekotekina** [comment]
https://developercommunity.visualstudio.com/content/problem/1219/regression-in-compiler-for-constexpr-constructors.html
Try to update. Otherwise it cannot be helped,

**Comment by danilaml** [comment]
@Nekotekina btw, can't `version` here https://github.com/RPCS3/rpcs3/pull/2808/files#diff-30442376c18179781533b6456d6f894bL7 be explicetly declared `constexpr`?

**Comment by Nekotekina** [comment]
No, this won't compile.

**Comment by danilaml** [comment]
@Nekotekina yeah, I see now that it won't play nicely with multiple `extern`s.

**Pull request closed without merging**
