### PR TITLE
rsx: Enhancements

### PR DESCRIPTION
**Pull request by kd-11**
- Adds support for internal resolution scaling. Compatible with most applications out-of-the-box unless 'write color buffers' is required. Note that strict rendering mode disables this scaling.
- Enables forced anisotropic filtering upto 16x
- Implements vsync mode for vulkan

### CODE REVIEW

**Comment by Psycho-A** [comment]
"Note that strict rendering mode disables this scaling."

Is that always be this way?

**Comment by Renusek** [comment]
@Psycho-A Probably, "strict" means accurate and enabling resolution different than native might be not that accurate. But maybe wait for an answer from kd-11.

**Comment by kd-11** [comment]
Strict mode enforces accuracy over everything else, so it will always be that way. The alternative would be individual settings for accuracy level but that would require 20+ switches as is and I fear the bloat would be too much. I might eventually split the setting into separate switches and use the strict mode toggle to change all of them on or off allowing one to alter the state in the config file for finer grained control, but thats not a priority right now

**Comment by up201505472** [comment]
Hey kd-11 just want to say really outstanding work

**Comment by Psycho-A** [comment]
> I might eventually split the setting into separate switches and use the strict mode toggle to change all of them

Maybe it's good to do it, but separate into "advanced settings" or sort of, because some games miss interface elements without "strict rendering" enabled, so becomes totally unplayable with new resolution scaling feature. That'll be bad...

**Comment by Psycho-A** [comment]
Also, there are some glitches appears when we set various upscaling settings.

Here is 150% resize (1080p):
http://i1.imageban.ru/out/2017/10/09/2e0f2065f137b68d5856182d40e95063.png

Here is 200% resize (1440p):
http://i3.imageban.ru/out/2017/10/09/abc61bbbfd63275f8a018d5c0a874394.png

And here's native 720p rendering:
http://i1.imageban.ru/out/2017/10/09/21ca7645a2aceb3b9f4cffc19edbe4dd.png

**Comment by Lardian** [comment]
Outstanding work ! 
I'm getting error when toggling fullscreen (alt+enter) in Demon's Souls (BLUS30443) tho.
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4653214h
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp:1593)

**Comment by kd-11** [comment]
@Psycho-A The only workaround for bugs like that is to try playing around with the threshold slider. Otherwise the correct way would be to ironically disable scaling. Alot of games have hardcoded values and even assets that dont play well with upscaling

**Comment by Morgawr** [comment]
I'm having the same issue as @Lardian , I toggle fullscreen or 1080p mode and the game freezes with that exact error message.

If I launch it at 720p then it's fine until I try to resize it (game tested: Ni No Kuni). I managed to get it to run at 1080p a couple of times but I was not able to replicate it successfully and I'm not sure exactly what's causing it.

**Comment by tkashkin** [comment]
I was also having same issue as @Lardian and @Morgawr on vulkan (old builds and 0.0.3-6390) when I tried to launch game (BLJM60223, NieR Replicant) in fullscreen or resize window manually.
It worked without error sometimes but I can't replicate it too.
I used windowed mode with 'resize game window on boot' option as workaround.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/3563 should fix the nvidia resize hang

**Comment by Psycho-A** [comment]
> The only workaround for bugs like that is to try playing around with the threshold slider. 
@kd-11 Maybe it's good solution too, where reverting back to native resolution will be one of last slider position (if I understand correctly the conception of the threshold slider)...

**Comment by tesla2105** [comment]
@kd-11 Portraits in Persona 5 are glitched in high resolution (I'm playing at 5k) and vsync still doesn't work in vulkan, otherwise amazing work!

**Comment by Asinin3** [comment]
@tesla2105 Known issue.

**Pull request merged**
