### PR TITLE
Insignificant fixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by stevphie** [comment]
just test this pr out of curriousity,.. stuck on startup with llvm + linux + tales of graces, amsjit was normal,
imastuckzzz

**Comment by Zangetsu38** [comment]
yes, spu llvm is more broken actually here, need wait i think ^^

**Comment by Zangetsu38** [comment]
If you can try rewrite instruction FMA/FNMS/FMS with code based oin asmjit, can fix render on Bleach and maybe dante Inferno and heavy rain and more

**Comment by greggameplayer** [comment]
@Nekotekina this PR make NPUA80706 (Jak and dexter the precursor legacy) crash because of 

> F {PPU[0x100000e] Thread (GOAL) [0x0001b498]} class std::runtime_error thrown: Unregistered PPU function

**Comment by stevphie** [comment]
Tested so many times always crashed if SPU thread = 2 others like 1,3,4 SPU thread are no problem.. consistent crashed duration betwee 5 - 6 seconds ingame Tales of Graces...

**Comment by SowingSadness** [comment]
RPCS3 Version: 0.0.8-9365-aeed349a Alpha

Ryzen 7 3700U + Vega 10 give me 5 fps XD
But Xeon 1240 E3 + Gtx 970 give 70 fps
Are somthing wrong with AMD products?

**Pull request merged**
