### PR TITLE
Enable PPU java mode handling by default

### PR DESCRIPTION
**Pull request by Megamouse**
I don't remember if we had decided to do this, so I'll just make a PR and Ani or Neko can merge if needed.

### CODE REVIEW

**Comment by elad335** [comment]
No, it has severe perf hit.

**Comment by MSuih** [comment]
Does it apply to specific games or something? We've not noticed any difference in testing.

**Comment by elad335** [comment]
I guess there are no PPU perf limited games, better to have accurate prebuilt cache because switching LLVm options is pain so OK.

**Comment by VelocityRa** [comment]
> Does it apply to specific games or something? We've not noticed any real-world difference in testing.

It affects the Sly cooper games. ie. https://github.com/RPCS3/rpcs3/issues/5289

**Comment by Megamouse** [comment]
> > Does it apply to specific games or something? We've not noticed any real-world difference in testing.
> 
> It affects the Sly cooper games. ie. #5289

he meant regarding performance loss

**Comment by YuriNator557** [comment]
> I guess there are very little PPU perf limited games, better to have accurate prebuilt cache because switching PPU LLVM options is pain so OK. Worse we can revert commit.

We tried some PPU limited games such as NieR and GTA San Andreas before and it doesn't seem to mess with them either

**Pull request merged**
