### PR TITLE
vk: Conform to current spec

### PR DESCRIPTION
**Pull request by kd-11**
While investigating the NV vulkan crashes, I realized we were violating spec in several ways. Some of these have been there since the beginning and others have crept in during refactoring efforts.

### CODE REVIEW

**Comment by kd-11** [comment]
NV Testers, please use bundled samples first before attempting to execute games with this.

**Comment by raven02** [comment]
Just grap this build and ran .It still crashed though with memoryTypeBits (0x102) 

·E {rsx::thread} RSX: ERROR: [MT] Code 14 : vkBindImageMemory(): MemoryRequirements->memoryTypeBits (0x102) for this object type are not compatible with the memory type (0x7) of this memory object 0xa1.

**Comment by kd-11** [comment]
@raven02 How about something more basic like basic triangle test (no textures)

**Comment by kd-11** [comment]
I think I know why this is happening. Unfortunately, it means we have to rewrite our memory properties search code. This certainly complicates things since AMD does not use NV's memory properties layout that is obviously created to better suit the memory search algorithm created for sdk samples. We'll have to reimplement this unfortunately.

**Comment by raven02** [comment]
No luck for gs_gcm_basic_triangle.elf as well

**Comment by kd-11** [comment]
According to spec
```
memoryTypeBits is a bitmask and contains one bit set for every supported memory type for the resource. Bit i is set if and only if the memory type i in the VkPhysicalDeviceMemoryProperties structure for the physical device is supported for the resource.
```

Unfortunately this goes against what we have been doing for image memory. We have been assuming that type bits will match memory type. NV approach to this is actually rather interesting. I'm pushing a fix for this. It seems the property flags in the table dont mean anything for images.

**Comment by kd-11** [comment]
NV issue should be resolved now.

**Comment by raven02** [comment]
Cool .It works perfectly .No more startup crash using latest NV driver now and scaling also fixed as well.

**Comment by kd-11** [comment]
That's good. Its ready to merge then.

**Pull request merged**
