### PR TITLE
rsx: Add duplicate sections detection

### PR DESCRIPTION
**Pull request by kd-11**
Tries to detect when there are too many sections in a given memory range and remove the duplicates if any.

Fixes https://github.com/RPCS3/rpcs3/issues/9624
Should also improve part of https://github.com/RPCS3/rpcs3/issues/8294

### CODE REVIEW

**Comment by jeremybris** [comment]
When I use the default settings of the emulator, SSX works great. However, when I increase the resolution, it will marginally tank the F.P.S., until is more severe. Past 350 %, the emulator crashes with this error and this log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5975922/RPCS3.zip)

Thank you for your hard work, and please tell me if I have misspoken.

Capture4

**Comment by jeremybris** [comment]
Ok, nevermind about my earlier comment, sorry. I tested my main branch, and that regression is present, so it is separate. I'll try to figure out the source of that regression.

**Comment by AphelionWasTaken** [comment]
Texture upload times no longer creep up in SSX, and performance no longer decreases over time. Unfortunately, this game still suffers from very high texture upload times in some levels as seen below.

Run 1:
run1

Run 15:
run15

Level with high texture upload times:
texture upload

Log for playthrough on this level:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5976090/RPCS3.zip)

**Comment by Lagahan** [comment]
No significant difference in texture upload times in Motorstorm 1 (issue is intermittent on certain parts of some tracks)
PR:
pr
Master:
master

**Comment by Shoegzer** [comment]
Not sure if this is expected, but I've tested same performance with SSX when comparing before and after these recent SSX-related PRs: both show between 6-7fps during intro cutscene and 15-20fps ingame with stuttering audio.  I've removed all caches before testing.  Test system is an i7-7820HK with GTX 1070 driver 460.32, linux 20.1 kernel 5.8.  Tested against build 76518d4c590051944ff978b594361c0a65059002.

**Comment by kd-11** [comment]
This PR solves a very specific engine issue with this game, if you're still having low performance, its likely caused by something else and is outside scope. Unless you can see your texture upload times increasing with each run, you'll need a separate investigation for why its so slow for you. FTR, it's 30fps on a R7 1700 and RX470/GTX1050Ti system so you should in theory have better performance if you use the right settings. That said, this is not the place to discuss tuning.

**Comment by Shoegzer** [comment]
Thanks @kd-11.   I wonder if I've encountered a linux-specific performance issue.  I've opened a new issue [here](https://github.com/RPCS3/rpcs3/issues/9786) for tracking.

**Pull request merged**
