### PR TITLE
VS: Fix zstd debug lib

### PR DESCRIPTION
**Pull request by Megamouse**
- The zstd lib was building a dll and I randomly had the .lib somewhere in the folder, so it worked before cleaning it properly.
- Update FAudio to [24.10](https://github.com/FNA-XNA/FAudio/releases/tag/24.10)
- Update SDL to [2.30.8](https://github.com/libsdl-org/SDL/releases/tag/release-2.30.8)

### CODE REVIEW

**Comment by Darkhost1999** [comment]
Debug build compiled successfully
image
Thank you

**Comment by digant73** [comment]
is it no longer needed to compile the projects under _BUILD_BEFORE (e.g. llvm_build)?

**Comment by Megamouse** [comment]
What makes you think that?

**Comment by digant73** [comment]
> What makes you think that?

becuase I didn't compile them. I simply built the solution and it compiled

**Comment by Megamouse** [comment]
It's possible that you had them built before at some point

**Comment by Megamouse** [comment]
The bin folder is not relevant for the build result and doesn't have to be cleaned

**Comment by digant73** [comment]
> The bin folder is not relevant for the build result and doesn't have to be cleaned



> It's possible that you had them built before at some point

yes possible. I will start from a clean repo

**Comment by digant73** [comment]
> The bin folder is not relevant for the build result and doesn't have to be cleaned

yes, I see

**Comment by digant73** [comment]
cloned your PR and compiled successfully also in Debug mode

**Comment by digant73** [comment]
If I can suggest, for a next PR, better organized target compilation folders for the MSVC `sln` project I would follow the same approach used by the `cmake` project (also handled by VS 2022). Cmake project provides all the compilation files (lib, obj etc.) inside the `build-msvc` main folder as shown in the following picture:

cmake_target_compile_folder

Currently, the MSVC `sln` project is creating folders directly on `3rdparty`'s source folder (source code mixed with .obj etc.) and also on different other folders in the rpcs3's main folder (e.g. `lib`,` Release`, `Debug`, `x64` etc.)

**Pull request merged**
