### PR TITLE
implement getSizeKB functions

### PR DESCRIPTION
**Pull request by Inviuz**
bugfix in sys_net. id 0 is acceptable socket id

ok. so while id 0 should be correct it often causes games to hang on recvfrom() since, it's blocking func.

### CODE REVIEW

**Comment by SakataGintokiYT** [comment]
@Inviuz 

**[NPEB01316]**

```
E {PPU[0x1000006] Thread (JoystickThread) [0x007accd0]} libnet: recvfrom(): error 35
W {PPU[0x1000006] Thread (JoystickThread) [0x007accd0]} libnet: recvfrom(s=0, buf=*0xd003bcb0, len=128, flags=0x0, addr=*0xd003bca0, paddrlen=*0xd003bc10)
```

```
Fatal error
Unhandled Win32 exception 0xC0000005.
Segfault writing location 00000000080fd040 at 00000000004d8d00.
Instruction address: 00000000004d8d00.
Function address: 00000000004d8cb9 (base+0x4c8cb9).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

```

**[Log:](https://gist.github.com/SakataGintokiYT/885a76d31fcae7b1ed6c21421e0a3257)**

**Comment by Inviuz** [comment]
[NPEB01316]
Crashes when reverted to commit 34c2b8a55e612a95995327b8dbc5cef89d3e14aa

**Comment by SakataGintokiYT** [comment]
@Inviuz 
This is a regression from rpcs3 v0.0.0.9

**Comment by Nekotekina** [comment]
Bytes to kibibytes?

**Pull request merged**
