### PR TITLE
Fix regressions caused by network code.

### PR DESCRIPTION
**Pull request by clienthax**

### CODE REVIEW

**Comment by digitaldude555** [comment]
Backbreaker is working now.

**Comment by Kojikun1** [comment]
Fixed Bomberman Ultra regression https://github.com/RPCS3/rpcs3/issues/3586

**Comment by Xcedf** [comment]
Maybe you could also take a look please on Beyond Two Souls which is also regressed from PR 3503

**Comment by Zangetsu38** [comment]
for beyond it is diference situtation regression

**Comment by Xcedf** [comment]
Actually commit e5f75620 caused this

**Comment by clienthax** [comment]
@Xcedf Doubtfull.

**Comment by legend800** [comment]
This PR allows NBA Jam OFE to finally get in game! Use to always hang on loading screen. Good stability fixes here!

**Comment by money123451** [comment]
this also fixes payday2s regression (where it would crash on restarting missions or ending them or going back to the main menu from the mission select screen)

**Comment by Asinin3** [comment]
Fixes NBA Jam: On Fire Edition

**Comment by elad335** [comment]
but not all regressions have been fixed , beyond still not working

**Comment by clienthax** [comment]
beyond is a different issue, i will have a look at it soon

**Pull request merged**
