### PR TITLE
Qt/Input: add color picker for DS4 Controller LEDs

### PR DESCRIPTION
**Pull request by Megamouse**

### CODE REVIEW

**Comment by z0z0z** [comment]
Fails to build for me on Linux

```[ 73%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Vulkan/glslang/glslang/MachineIndependent/InfoSink.cpp.o
[ 73%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Vulkan/glslang/glslang/MachineIndependent/Initialize.cpp.o
[ 73%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Vulkan/glslang/glslang/MachineIndependent/IntermTraverse.cpp.o
[ 73%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Vulkan/glslang/glslang/MachineIndependent/Intermediate.cpp.o
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:5204: rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/settings_dialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:201: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by drysalter** [comment]
No issues with building on Ubuntu 19.04 (gcc 8.3.0).

The controller image looks jagged on my HiDPI screen, however. I don't know how well you can tell from this picture:

controllerhidpi

I personally don't see an issue with the way it looks in master. Is it as big as in the picture above on standard definition?

**Comment by Megamouse** [comment]
It fills the space on 1080p screens but lately it is super small on highdpi screens. Idk if it looks jagged because of the scaling or if the source image is simply not good enough

**Comment by MSuih** [comment]
That's odd, it looks much smaller for me, same size as current master, but I'm on 1080p at 100% scaling. Some kind of scaling issue I guess, is it caused by the lack of setDevicePixelRatio or what?

image

As for it being jaggy, that could just be caused by the original artwork being stretched beyond it's limits. You can find the PNG file in `rpcs3/Icons/controller.png` of source. That artwork has multiple mistakes anyways, I'd say it's due to redrawing anyways.

**Comment by Megamouse** [comment]
Guess I'll have to investigate then

**Comment by drysalter** [comment]
> As for it being jaggy, that could just be caused by the original artwork being stretched beyond it's limits.

Yup, this is it. At the correct size it'll be decent.

**Comment by Megamouse** [comment]
this might need a checkbox or something to enable it similar to the vibration

**Comment by Megamouse** [comment]
Hmm I couldn't find a way to read the old LED state or to prevent it from being updated without disabling the Rumble as well. So for now we have to stick with LEDs being updated.

But I fixed a bug that kept the selected color even when you didn't save it.

I'll look into the controller background image problems next.

**Comment by Megamouse** [comment]
I removed the resizing of the icon for now.

**Comment by Kravickas** [comment]
just transfer everything to vector

**Pull request merged**
