### PR TITLE
link to libatomic

### PR DESCRIPTION
**Pull request by John-Gee**
Hello,

I tried building RPCS3 earlier but I was unable to.
This is my first time trying to build it on GCC7 so that could be the reason, but it could be a change in RPCS3 as well for all I know...

With the standard git, I get these errors:
/tmp/ccS4TsgI.ltrans9.ltrans.o: In function `RawSPUThread::write_reg(unsigned int, unsigned int)':
<artificial>:(.text+0x2806b): undefined reference to `__atomic_load_16'
<artificial>:(.text+0x28136): undefined reference to `__atomic_compare_exchange_16'
/tmp/ccS4TsgI.ltrans13.ltrans.o: In function `sys_spu_thread_write_spu_mb(unsigned int, unsigned int)':
<artificial>:(.text+0x24250): undefined reference to `__atomic_load_16'
<artificial>:(.text+0x24303): undefined reference to `__atomic_compare_exchange_16'
/tmp/ccS4TsgI.ltrans31.ltrans.o: In function `SPUThread::get_ch_value(unsigned int, unsigned int&) [clone .constprop.5202]':
<artificial>:(.text+0xe857): undefined reference to `__atomic_load_16'
<artificial>:(.text+0xe8f2): undefined reference to `__atomic_compare_exchange_16'
<artificial>:(.text+0xe96b): undefined reference to `__atomic_compare_exchange_16'
/tmp/ccS4TsgI.ltrans10.ltrans.o: In function `SPUThread::cpu_init()':
<artificial>:(.text+0x242f2): undefined reference to `__atomic_store_16'
/tmp/ccS4TsgI.ltrans10.ltrans.o: In function `SPUThread::get_ch_value(unsigned int, unsigned int&)':
<artificial>:(.text+0x2ec67): undefined reference to `__atomic_load_16'
<artificial>:(.text+0x2ed04): undefined reference to `__atomic_compare_exchange_16'
<artificial>:(.text+0x2ee7b): undefined reference to `__atomic_compare_exchange_16'
collect2: error: ld returned 1 exit status
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:10726: bin/rpcs3] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2

Looking into it a bit, it seemed like the makefile was simply missing "-latomic" and adding it gave me a good build.
For now I added it in the same place as "-ldl" but feel free to correct me about this.

Thanks!

### CODE REVIEW

**Comment by danilaml** [comment]
@John-Gee just for completeness sake, what OS/architecture are you using? GCC on travis doesn't seem to need explicit atomic linking.

**Comment by John-Gee** [comment]
Arch Linux on AMD64, Linux 4.11, glibc 2.25. Please ask if you'd like to know more.

Looking at the build logs, travis seems to use GCC 4.8.4, a fairly old build.
I wonder if it would make sense to have more travis runs with various GCC builds, kind of like there is already one for GCC and one for clang...

**Comment by danilaml** [comment]
@John-Gee it uses `g++-5 (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904`  https://github.com/RPCS3/rpcs3/blob/master/.travis.yml#L81
But yeah, I was asking just out of curiosity.

**Comment by John-Gee** [comment]
Hmmm, I don't get it then.

That's what I see in the log (https://travis-ci.org/RPCS3/rpcs3/jobs/235942440):

   gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Am I looking at the wrong page?

**Comment by hcorion** [comment]
This fixes issue #2770

**Comment by hcorion** [comment]
But yes, GCC 7 appears to require manually link libatomic now.

**Pull request merged**
