### PR TITLE
use clang 3.6 for travis

### PR DESCRIPTION
**Pull request by Bigpet**
rebase of #1057

### CODE REVIEW

**Comment by Syphurith** [comment]
OK, just wait for the Travis result.
However if you let it `apt-key add -` first.. well not a severe problem.

**Comment by Syphurith** [comment]
while linking: `clang: error: unable to execute command: Killed`.
It is said to be not enough swap, which maybe we can not deal simply.

**Comment by Bigpet** [comment]
Yeah, let's see what it actually complains about

**Comment by Syphurith** [comment]
That is a sometimes failure, so we would have to detect and catch those manually.
And Travis has sometimes locked memory out with no reason.
please add these somewhere (for example around line 71 of `.travis.yml`):
* `uname -a`: show kernel version
* `lsb_release --version` to show Linux Release version. thus with one above we know the host.
* `cat /proc/meminfo` to see total swap, and free swap (all linux)
* `cat /proc/swaps` to see which swap devices are being used (all linux)
* `free -m -t` to see how much free memory left.

See this file: https://github.com/dbsrgits/dbix-class/blob/current/blead/maint/travis-ci_scripts/10_before_install.bash, link 12. It can be stopped when the needs isn't met.

**Comment by Syphurith** [comment]
Also from https://github.com/tsuru/tsuru/blob/master/.travis.yml#L38:
```bash
after_failure:
  # check for OOM; see https://github.com/travis-ci/travis-ci/issues/3075#issuecomment-68629130
  - sudo dmesg
  - free
  - vmstat
  - ps aux --sort -rss | head -n 10
```

**Comment by Syphurith** [comment]
It is said that using too many template class in C++ may cause big memory footprint.
Unfortunately we can not stop using those. Also i saw Travis building LLVM.
BTW building rpcs3 on Windows is now slow already, take me around 20 minutes, without wx/LLVM.
I don't know should we split those into plugins thus may help building it faster. Also it would help someone testing the UI or implemented functions without fully linked them..

**Comment by Syphurith** [comment]
Well clang build passed. I've said that is a occasionally issue. Even some VM has no swap.
It seems it would need very much memory space while linking (around 1G for me with VS).
The linker log links too many objects that i scrolled several pages, dude. Orz.

**Comment by Syphurith** [comment]
@Hykem you can merge this pull instead of #1057. Bigpet improved it.
I don't know how much memory and swap exactly the linker would need to build the executable.
As mentioned above it may sometimes OOM and fail the travis build.
BTW I have a [Article in Markdown](https://gist.github.com/Syphurith/abbce0f38354218667cf) for starter devs. I can not commit to github wiki so just leave link here.

**Pull request merged**
