### PR TITLE
Update Qt to 5.9.3

### PR DESCRIPTION
**Pull request by scribam**
- Travis will now use Qt 5.9.3 when building
- AppVeyor will switch automatically on this release when available on their servers
- Update CMake comment to recommend the Qt 5.9.3 PPA 

For more information about Qt 5.9.3: https://blog.qt.io/blog/2017/11/22/qt-5-9-3-released/

### CODE REVIEW

**Comment by greentop** [comment]
I've been using Qt 5.9.3 for more than a few days now to build RPCS3 on Ubuntu 16.04. No issues observed.

**Comment by ps2player** [comment]
ps2 controller issue

untitled

**Comment by AniLeo** [comment]
@ps2player stop spamming unrelated PRs

**Comment by ps2player** [comment]
@AniLeo im not trying to spamming . where to post these thing ?

**Pull request merged**
