### PR TITLE
gl: Disable overlay if required extension is not supported

### PR DESCRIPTION
**Pull request by kd-11**
https://github.com/RPCS3/rpcs3/issues/2209
https://github.com/RPCS3/rpcs3/issues/2211

### CODE REVIEW

**Comment by kd-11** [comment]
Can anyone confirm that the affected GPUs are working with this fix?

**Comment by raven02** [comment]
thanks @kd-11 . i will test it shortly.

**Comment by sirdanielk** [comment]
It works for me. And thats without changing any settings. Great.

**Comment by raven02** [comment]
Just tested and works okay .

**Pull request merged**
