### PR TITLE
HLE cellHttpUtilParseUri, Also initalise networking with windows.

### PR DESCRIPTION
**Pull request by clienthax**
Fixs https://github.com/RPCS3/rpcs3/issues/2788

### CODE REVIEW

**Comment by hcorion** [comment]
For the sake of cross-platform-ness, could you also implement cellHttpUtilParseUri for Linux?
Wine has an implementation you can use:
https://github.com/wine-mirror/wine/blob/07cf14dc928a1a00baecbbc7ca5a6f3fe680238c/dlls/winhttp/url.c#L183-L322

**Comment by clienthax** [comment]
@hcorion As i wouldn't be able to test it easily il let someone else take care of that side of it,
I was originally using QUrl which has cross compat, but aparantly were not allowed to use QT in core.

**Comment by legend800** [comment]
This commit broke Scott Pilgrim (spams socket error now causing massive load times). 

http://www.emunewz.net/forum/showthread.php?tid=178174&pid=283631#pid283631

**Comment by clienthax** [comment]
@legend800 no, this commit Actually made networking able to work, broken libnet code caused the issue..

**Comment by clienthax** [comment]
@legend800 I am unable to reproduce that error even with the dlcs etc.
And since no one bothered to upload a log theres not much i can do..
Msg me on the rpcs3 discord if you want me to take a look

**Comment by Drive251** [comment]
@clienthax 
I uploaded this log so please check it
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1207211/RPCS3.zip)

**Pull request merged**
