### PR TITLE
moved build options to options.cmake

### PR DESCRIPTION
**Pull request by p01arst0rm**
Moved the CMake build options to a dedicated file. Makes
configuring build options easier when not using the CMake
GUI.

### CODE REVIEW

**Comment by JohnHolmesII** [comment]
If these were scattered throughout the file, I would support it, but given that the options are very prominent and right at the top, this seems silly. Plus the formatting is awful.

Not sure if its worth adding.

**Comment by Nekotekina** [comment]
Not to mention that separating them into another file, itself is a form of scattering. I think there is no need to do this.

**Comment by Megamouse** [comment]
maybe show the difference in cmake GUI...

**Comment by p01arst0rm** [comment]
putting the configurable options in a dedicated file is best practice, so is marking advanced options. This isnt personal preference, i dont mind either way.

**Comment by Nekotekina** [comment]
Well...

**Comment by hcorion** [comment]
Could've at least gotten the formatting fixed before merging... this is atrocious.

**Pull request merged**
