### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Compilation error With 2 last commit 
https://gist.github.com/Zangetsu38/99400027fdff24612456

**Comment by Nekotekina** [comment]
Sorry, this error shouldn't happen. You did something wrong with your merges.

**Comment by Zangetsu38** [comment]
@Nekotekina ok, it is my fault, line 137 >void sys_event_queue_attribute_initialize(vm::ptr<sys_event_queue_attr> attr);>

**Comment by Zangetsu38** [comment]
@Hykem It was enough to merge at once, it was not ready yet: /, rpcs3 is now slower and more error :(

**Pull request merged**
