### PR TITLE
Experimental: SPU reservations: Notify single SPU thread at a time

### PR DESCRIPTION
**Pull request by elad335**
Since most of reservations are just waiting for cellSpurs jobs and because if we awake all SPU threads at everytime theres a change in reservation state only 1 thread will win the job, awaking all at once will waste many resources and increase reservation contention.
So hey, let's try awaking only 1 thread at a time, this is very experimental as there may be other cellSpurs functoions which may regress by this change.

### CODE REVIEW

**Comment by dio-gh** [comment]
Tested with RDR, cleaned cache. Can't say I noticed a change to be honest. The game reliably crashes the emu on exit though.

**Comment by elad335** [comment]
I guess notify_one() is broken in some way if it crashes, closing for now.

**Comment by elad335** [comment]
Bug fixed I think.

**Comment by Nekotekina** [comment]
It's scary to merge, but let it remain for testing.

**Comment by Nekotekina** [comment]
Need (later) to rebase and do more testing for both regressions and performance. Notifying other threads is also expensive, and reducing it to notify_one() may directly help.

**Comment by elad335** [comment]
rebased.

**Comment by elad335** [comment]
If noone tests it I will close, its worth nothing without testing..

**Comment by Satan86** [comment]
Tested Uncharted 1, TLOU, RDR and Gran Turismo 5 and couldn't notice a difference in performance, all with fresh spu cache

**Comment by Yahfz** [comment]
> If noone tests it I will close, its worth nothing without testing..

Mind fixing conflicts and rebasing? I'm interested in testing this

**Comment by elad335** [comment]
Closing, this should be implemented within HLE cellSpurs I believe.

**Pull request closed without merging**
