### PR TITLE
Random improvements

### PR DESCRIPTION
**Pull request by DHrpcs3**

### CODE REVIEW

**Comment by SakataGintokiYT** [comment]
#1804  Can you check this please  :)

**Comment by raven02** [comment]
@DHrpcs3 , FYI. 

{rsx::thread} class gl::glsl::compilation_exception thrown: 
compilation failed: '0(69) : error C1008: undefined variable "tex0"
0(70) : error C1008: undefined variable "tex0"
0(71) : error C1008: undefined variable "tex0"
0(72) : error C1008: undefined variable "tex0"

**Comment by DHrpcs3** [comment]
@SakataGintokiYT, not now, sorry

@raven02,
about fogc - fog is unimplemented atm. I will implement it in near future (hopefully, today)
with tex0 mush harder. something corrupt memory with shaders and override last instruction with END flag. That problem in older build too, but it's stay invisible with old decompilers

**Comment by raven02** [comment]
I see. @DHrpcs3 . Take you time.

**Comment by raven02** [comment]
@DHrpcs3 , FYI.

- Alpha kill sample
{rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 'ERROR: 0:74: 'any' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:74: '' : boolean expression expected 

- Depth read sample
{rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 'ERROR: 0:16: 'r8' : syntax error syntax error

**Comment by DHrpcs3** [comment]
@raven02, yes, vertex textures not implemented atm

**Comment by raven02** [comment]
I see @DHrpcs3 .Thanks.

**Pull request merged**
