### PR TITLE
xxHash: Update to v0.8.0 xxHash (and XXH3 hash algorithm)

### PR DESCRIPTION
**Pull request by bevanweiss**
Removed build of XXHSUM test application for xxHash also.
~~Migrated existing XXH64 uses to XXH3_64bits (we were providing seeds of 0, so we don't need the third parameter).~~

### CODE REVIEW

**Comment by elad335** [comment]
Uhh, wait, I think this change will causeall previous rsx captures to fail booting.

**Comment by bevanweiss** [comment]
> Uhh, wait, I think this change will cause all previous rsx captures to fail booting.

Thanks for the heads-up.  Have pulled out those persistent RSX capture related items.

**Comment by AniLeo** [comment]
Windows build just failed randomly, when you rebase it should work, otherwise I'll issue a manual Re-Run again

**Comment by bevanweiss** [comment]
Thanks :)

**Pull request merged**
