### PR TITLE
LLVM Clang-cl support and ninja build

### PR DESCRIPTION
**Pull request by xddxd**
Adds support for building LLVM with Clang-cl + Ninja or MSVC + Ninja on Windows. This reduces the compile times quite a bit compared to using MSBuild for either of the compilers.
from CMake config to finish:
MSBuild + MSVC: 12:20
MSBuild + Clang-cl: about an hour (some bug, makes it start with 16 jobs but it later dwindles down to 1, lol)
Ninja + MSVC: 9:48
Ninja + Clang-cl: 9:14
~~One caveat for now: the rebuild and clean commands result in Ninja trying to clean the CMake generated files which fails with an error, but the compiled files themselves are removed. While it can be ignored, I'd like to resolve that, but I can't figure out how yet.~~
Also, the Azure side needs to be updated accordingly. Maybe @JohnHolmesII can handle that.
Do not merge before https://github.com/RPCS3/llvm-mirror/pull/6 is merged.

### CODE REVIEW

**Comment by ZeeWanderer** [comment]
I have a local ninja build version of llvm project, i use this for total cmake clean
```xml
```

**Comment by JohnHolmesII** [comment]
You only need to delete the CMakeCache file to force a regen

**Comment by xddxd** [comment]
Thanks ZeeWanderer, works exactly like I needed it to.

**Comment by xddxd** [comment]
PR ready for merge after the PR in LLVM is merged.

**Comment by Nekotekina** [comment]
What do you mean, you want to update commit of the submodule?

**Comment by xddxd** [comment]
Oops, done.

**Pull request merged**
