### PR TITLE
Fixes (LLVM)

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by hcorion** [comment]
Could we also get LLVM updated to 4.0? I know the upgrade to 3.9 requires the addition of 
```cpp
#include "llvm/Transforms/Scalar/GVN.h"
```
in rpcs3/Emu/Cell/PPUThread.cpp
but I haven't tried 4.0

**Comment by Luffykun007** [comment]
Demon's Souls and several other games do not work right now using LLVM 4.0
capturar

**Comment by Zangetsu38** [comment]
Look here https://github.com/Zangetsu38/rpcs3/commit/451c06152d90844104a56f65839851c87f76e491
you have set a wrong change, not works with this

**Comment by Luffykun007** [comment]
in https://ci.appveyor.com/api/buildjobs/yqgdcv7c31w6upwu/artifacts/rpcs3-v0.0.2-2017-03-21-8034017d_win64.zip 
worked 

capturar1

**Comment by Nekotekina** [comment]
Appveyor build with LLVM 4.0 now available, I removed possibly misleading comments.

**Comment by Zangetsu38** [comment]
Yes, now it's works, but why you have disable "createGVNPass" ?
Just need add include "#include "llvm/Transforms/Scalar/GVN.h"
for found function moved file.

**Comment by Luffykun007** [comment]
Corrected now
capturar

**Pull request merged**
