### PR TITLE
Various cleanup, nothing to see here

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by elhaya** [comment]
you should change the title, this PR brings huge fps gains!
tested so far with GOW 3 and RDR, both show huge improvement. especially with vulkan - alas it's crashing for me every few seconds.
great work!!

**Comment by Nekotekina** [comment]
Are you kidding or it's some sort of mistake?
Did you compare with latest master?

**Comment by elhaya** [comment]
Neko - I swear to G-d!
I've been testing every "stable" release for the past month - today with your build showed huge improvement.

**Comment by elhaya** [comment]
https://youtu.be/ud3F1TikC5o
https://youtu.be/K0zm8wV8Y00

**Comment by vietnam13231** [comment]
I just checked, but I don't see any kind of improvement. No regressions either from what I see, so at least it's not breaking anything.

**Comment by Zangetsu38** [comment]
last commit broken compile for me, get one error on ppumodule.cpp line 1695
>6>h:\git\rpcs3-dante\rpcs3\emu\cell\ppumodule.cpp(1695): error C2275: 'ppu_load_overlay_exec::process_param_t' : improper use of this type as an expression
6>h:\git\rpcs3-dante\rpcs3\emu\cell\ppumodule.cpp(1681): note: see the statement of 'ppu_load_overlay_exec::process_param_t'
6>h:\git\rpcs3-dante\rpcs3\emu\cell\ppumodule.cpp(1695): error C3861: 'SIZE_32' : identifier not found

**Comment by elad335** [comment]
@Zangetsu38 thats only because you are using pr #4679 in your branch as well.

**Pull request merged**
