### PR TITLE
Minor change

### PR DESCRIPTION
**Pull request by Zangetsu38**
Thx @kd-11 for help and approve this
d3d12: Fix typo, invalid no says Unknown it is a different and little clean up in D3D12Formats.
PPU: Fix two Warning compile.
Add info in BufferUtils for log.

### CODE REVIEW

**Comment by Nekotekina** [comment]
What a useless PR. Stop wasting my time or I'll have to ban you again.

**Comment by O1L** [comment]
Actually we use only D3D (part of DirectX). 
In truth, these changes do not do anything.

**Comment by Zangetsu38** [comment]
I have only restore Unknown and DirectX 12 name for same other GCM_ENUM etc.., and same before and GSframe indicate DirectX 12 while setting dialog indicate D3D12, just more clear, that all, 
And commit Allows Kung fuu Rider launch, just after this waiting kd-11 implement quad_strip.
And i have ask for sur before request PR, and  i am saying this little change it is interesting :/

**Comment by kd-11** [comment]
@Zangetsu38 As I mentioned earlier, its best to leave those cosmetic changes out and maybe submit only the stubbed cellMusic function and the BufferUtils improvement. Comsetic changes like that tend to be divisive and don't add new functionality.

**Comment by paulsapps** [comment]
Seems strange that cellMusicSetVolume2 takes no arguments? If it does have arguments won't this unbalance the stack?

**Comment by Zangetsu38** [comment]
@kd-11 Yes I know that, but the other 2 changes, are just the one for the useless code that had been forgotten, and make it all clearer, nothing else: /
And simply with a coherence between the settting dialog which says D3d12 and the window GSFRAME which indicates it DirectX 12.
It's just to be coherent, and it changes nothing.

**Comment by Nekotekina** [comment]
Then change GUI back to D3D12.
And single cellMusic line only.
And I'd merge it.

**Comment by Zangetsu38** [comment]
@Nekotekina One line only ? What do you mean ?
I do not understand, it takes 2 lines though, like any other function not implemented. 
And for Gui i have juste restored same before and also same in GSFrame, and also same Vk Named Vulkan and GL named OpenGL , It just seemed logical to me, it makes it a little strange with the other 2 that well their full name.
But if you want of but i don't really understung for one line celle music

**Comment by Zangetsu38** [comment]
I've done

**Comment by Nekotekina** [comment]
Oops. there is nothing to merge. Also I don't think that "Unknown" is better.

**Comment by Zangetsu38** [comment]
@Nekotekina Sorry but precisely if we need it, kd-11 said it himself, the change in BuferUtil was necessary, I found the missing value to fix a games like that, and kd-11 will implement it after , We need it to find other value and therefore why he said we should merge.

And for Unknow, I only handed it over as it was before and especially as is the case in the rest of the code, it's only to be consistent with all the code, see here:
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/gcm_enums.cpp#L16
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/VK/VKGSRender.cpp#L20

This is already written Unknown in all the rest of the code, precisely because that is what it means, unknown value (not known therefore), value invalid means nothing in this case.

And I had not just done that, there was also a small cleanup of old undeleted code that had been forgotten at the time, "break" and "unsupported" are not useful if all boxes return a value , It was precisely in order to save you time.

**Comment by kd-11** [comment]
There are some unimplemented exapansions in BufferUtils which is why I agreed that the change was useful in that case. The gramatical stuff I don't care for.
The other important bits were commited with https://github.com/RPCS3/rpcs3/pull/2343

**Comment by Zangetsu38** [comment]
@kd-11 Yes I know, I had to implement a single value in cell music, since I did not test the rest, otherwise I would have done too.
But I have not just renamed the "invalid", there is also some old useless code cleanup that has been forgotten.
But so I have to do what, remake a PR with only the change in buffertutil?

**Comment by kd-11** [comment]
That change alone would be too small to justify a PR by itself. While it would provide some useful information in case of a crash, it does not improve functionality, which is why I usually let my work stay in my private fork for a while until I have something bigger to provide.
I will include the improvement when I submit my buffer synchronization work.

**Comment by Zangetsu38** [comment]
ho ok, i see sorry :/

**Pull request closed without merging**
