### PR TITLE
vk/rsx: Bug fixes

### PR DESCRIPTION
**Pull request by kd-11**
1. https://github.com/RPCS3/rpcs3/issues/2085
2. https://github.com/RPCS3/rpcs3/issues/1935
3. Addendum to https://github.com/RPCS3/rpcs3/pull/2083

### CODE REVIEW

**Comment by raven02** [comment]
All the following games are re-tested and look good.

- 1942 Joint Strike
- Castle Crashers
- Marvel Vs Capcom 2 and
- Super Street Fighter II HD Remix
- Blade Arcus From Shining EX
- Saint Seiya Brave Soldiers
- Braid
- 4 Elements HD

**Comment by kd-11** [comment]
@raven02 Did you check awakened fate ultimatum?

**Comment by kd-11** [comment]
Added a fix for https://github.com/RPCS3/rpcs3/issues/2058

**Comment by kd-11** [comment]
@raven02 I've updated the commits. Retry awakened fate ultimatum now.
If it works then this is ready to merge

**Comment by raven02** [comment]
Yes it is working now . I think it is unimplemented lighting in Vulkan below on the character , isn;t?

untitled

**Pull request merged**
