### PR TITLE
Adding link library: rt

### PR DESCRIPTION
**Pull request by latot**
https://github.com/RPCS3/rpcs3/issues/1048

### CODE REVIEW

**Comment by Bigpet** [comment]
It's already here: https://github.com/RPCS3/rpcs3/blob/master/rpcs3/CMakeLists.txt#L47

What OS are you using that is not captured by that "if"?

**Comment by latot** [comment]
Linux gentoo 64, here the issue https://github.com/RPCS3/rpcs3/issues/1048

**Comment by Bigpet** [comment]
What you need to change is `set(ADDITIONAL_LIBS "X11")` to `set(ADDITIONAL_LIBS "${ADDITIONAL_LIBS} X11")`

**Comment by Syphurith** [comment]
@Bigpet Well that's really a typo.
@latot So you leave that simple complication fix for me?

**Comment by Bigpet** [comment]
Yeah, that's the same thing "${ADDITIONAL_LIBS}" is just "previous content of the variable".

**Comment by Syphurith** [comment]
@Bigpet but that is a little dumb when we can just keep those in one line.

**Comment by Bigpet** [comment]
superseded by #1053

**Pull request closed without merging**
