### PR TITLE
XAudio: allow Xaudio2 run in its own thread

### PR DESCRIPTION
**Pull request by raven02**
Tested with LLVM PPU which easily trigger the AddData() failed.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Probably won't work on 8.1 if it has neither 2.7 nor 2.9, need some information.

**Comment by raven02** [comment]
Ops . 8.1 even not come along with 2.7 dll

**Comment by danilaml** [comment]
@raven02 just change 28 to 28_plus or something (name could be worked on later), which tries to load 2.9 first and if it fails - 2.8. 2.8 and 2.9 have the same interface and work the same, so it should work.

**Comment by raven02** [comment]
Please test it again especially with PPU LLVM where easily trigger the AddData() failed.

**Pull request closed without merging**
