### PR TITLE
GUI: Modern app icon

### LINKED ISSUE #10024: [Feature Request] Modernize the application's icon
It's been bugging me for a while, but @DAGINATSUKO's website thumbnail looks infinitely better than the current RPCS3 app icon, or even the repo's logo.

This one, I mean:
image

What do you guys think, would it be okay if the current icon and repo logo was swapped out with this? She agreed to adjust it to different icon sizes. Looks plenty decent on the taskbar, imo:

new-icon

### PR DESCRIPTION
**Pull request by dio-gh**
Fixes #10024 

Hey all,

After some back and forth with @DAGINATSUKO, we settled on two possible new designs. One of them being my original proposal, a flat-shaded RPCS3 logo with tightly rounded corners, and the other being a gradient-shaded version, with curvier corners. This is how they'll look on your desktop (take note of the `gradient ver` and the `flat ver` shortcuts):

| **Small Icons** | **Medium Icons** |
|          :---:          |              :---:           |
|  small-ico | medium-ico |

And this is how they'll look on your taskbar (note that the  `flat ver` is on the left, and the `gradient ver` is on the right):

| **Small Taskbar** | **Normal Taskbar** |
|            :---:            |              :---:             |
| image | image |

Finally, a close-up juxtaposition:

image

~~**Please vote**, by putting either a ❤️ or a 🚀 emoji on this PR, depending on if you like the flat shaded (❤️), or the gradient (🚀) variant. I'll close the vote tomorrow (March 28), 8:00 PM, UTC time.~~

~~You may also add a 👎, if you don't like either one of the options. Would be cool if you left a comment on what would you rather want in that case, though. :)~~

The vote has concluded with 4 disapprovals, 5 votes on the `flat ver` and 22 votes on the `gradient ver`, making `gradient ver` the winner.

### CODE REVIEW

**Comment by hcorion** [comment]
I heavily prefer gradient with the curvier corners.
IMO the flat shaded version looks outdated, very Windows 8 Metro. The gradient really makes the RPCS3 logo pop for me and makes the icon easier on the eyes. We should be looking forward in icon trends, not looking backwards at icon design from 2013.

**Comment by xddxd** [comment]
I like the gradient style, but if the gradient was purple blue like on our discord logo.

**Comment by AphelionWasTaken** [comment]
Both look better than the current logo, but I prefer the gradient with rounder corners as well.

**Comment by Asinin3** [comment]
I don't like flat/metro design icons so having the corners more rounded is good. I also agree with gradients being good, but white on a light gradient might not show up very well especially when its small.

So in the example 2 is better, and definetely a lot better than what we have at the moment but i feel like it can "pop" more.

**Comment by Kravickas** [comment]
Left with discord color gradient

**Comment by Megamouse** [comment]
The margin could be smaller if you ask me.
The 3 looks a bit tiny tbh.
image

**Comment by lainiwaku** [comment]
i think rounded one will go well with new windows 10 icons design ! 
https://www.theverge.com/2021/3/24/22348639/microsoft-windows-10-file-explorer-new-icons-system-update

**Comment by dio-gh** [comment]
The vote has concluded with 4 disapprovals, 5 votes on the `flat ver` and 22 votes on the `gradient ver`, making `gradient ver` the winner. The final files will be hopefully pushed up tomorrow. Thank you all for voting!

There have been some recommendations and comments made on the designs, so I figured I should also address them while at it.

> We should be looking forward in icon trends, not looking backwards at icon design from 2013.

While the exact implementations change, the general trends tend to persist and cycle. Gradient shaded surfaces on GUIs have been with us since the mid to late 2000s at the very least, and the flat shaded styles are not at all attached to the Windows Metro style either.

It is true however, that Microsoft is now actively trying to use more gradients and more curves in their designs lately and is also planning to moving forward at this point in time, as seen in the article linked above this comment. It's worth noting though, that every one of those icons also feature differently shaded areas that make it so that it doesn't look like a single surface that is curved towards you, something which I'd claim is not the case here, nor is it realistically possible.

> I like the gradient style, but if the gradient was purple blue like on our discord logo.

> Left with discord color gradient

Discussed this with dag, and we agreed right away: multicolor gradients would absolutely not scale across sizes, and so these are sadly not feasible ideas.

> The margin could be smaller if you ask me. The 3 looks a bit tiny tbh.

We also discussed this one, and I even tested it days ago actually - the current margins are about the best you can get out of it, without making it look silly. I also think that it looks reasonably sized on your screenshot, but alas.

> I also agree with gradients being good, but white on a light gradient might not show up very well especially when its small.

I'm not exactly sure what you mean here, I reckon you want to make the gradient darker?

**Comment by dio-gh** [comment]
Ready to merge, I think. Replaced the following files:

- rpcs3.ico
- rpcs3.png
- rpcs3.icns
- rpcs3.svg

Do tell if anything else needs to be adjusted.

**Comment by Megamouse** [comment]
better run this through svgcleaner before someone else does it later

**Comment by hcorion** [comment]
In addition looks like the SVG is missing the gradient, and the 3 is transparent.
image

**Comment by dio-gh** [comment]
Done the svgcleaner pass, and it is missing the gradient. The icon was created in raster originally, and dag unsurprisingly couldn't find a converter that could properly turn that into a non-horrific looking svg.

**Comment by MSuih** [comment]
You can create gradients with svg, there's a syntax for it.

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients

**Comment by dio-gh** [comment]
I'm aware gradients are well possible in vector graphics, but it wasn't made in vector. I'll ask her if she's up to the task of making a vector version i suppose.

**Comment by Megamouse** [comment]
whats with the random llvm stuff

**Comment by dio-gh** [comment]
forgot to update submodule on the branch after jo poked around in it yesterday or so

**Comment by Megamouse** [comment]
and btw. there's also the "/rpcs3/Icons/insignia.png"

**Comment by hcorion** [comment]
Try this
```svg
<svg height="256pt" preserveAspectRatio="xMidYMid meet" viewBox="0 0 4096 4096" width="256pt" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="20622.121" x2="20622.121" y1="1442.7061" y2="38992.512"><stop offset="0" stop-color="#4f34c9"/><stop offset="1" stop-color="#7d69c6"/></linearGradient><path d="m327.11261 340.74228h3434.6821v3380.1636h-3434.6821z" fill="#fff" fill-rule="evenodd" stroke-width="14.0423"/><path d="m6993 39149c-501-26-1033-129-1513-294-889-305-1701-846-2330-1550-795-892-1263-1963-1387-3175-17-167-18-774-18-13680 0-12891 1-13513 18-13680 173-1702 1065-3180 2482-4115 747-493 1615-796 2535-887 198-19 27180-19 27375 0 618 61 1201 214 1749 459 477 213 903 479 1321 827 143 119 517 490 636 631 453 537 777 1093 1005 1729 164 455 268 931 309 1416 14 167 15 1504 12 13710-3 12668-4 13533-20 13655-47 358-105 657-182 925-261 921-751 1752-1430 2424-983 975-2252 1534-3645 1606-235 12-26683 11-26917-1zm20032-10189c983-11 1049-14 1610-96 778-113 1358-273 1934-536 531-242 955-526 1320-883 359-351 595-672 816-1110 245-485 388-972 480-1630 62-448 62-1295-1-1755-125-922-403-1640-878-2273-46-62-127-159-180-217s-96-107-96-110 44-52 96-110c163-179 333-416 479-670 332-576 547-1322 610-2122 20-250 20-900 0-1153-73-931-333-1731-778-2390-255-378-589-726-972-1010-615-458-1456-806-2365-979-482-92-952-150-1365-168-161-7-3390-12-9845-15l-9604-4-61 22c-88 31-167 82-222 143-56 61-115 176-132 254-8 37-11 405-11 1245 0 1313-2 1254 63 1386 65 134 219 247 367 270 44 7 3029 12 9230 16 5041 2 9316 9 9500 14 300 8 348 11 461 35 376 77 629 195 815 380 217 218 342 510 416 976 18 114 18 692 0 805-54 341-139 595-262 785-217 332-526 500-1095 594l-150 25-9455 3-9455 4-74 27c-182 64-316 219-350 402-8 40-11 430-11 1244 0 1251-1 1217 44 1339 35 95 154 220 253 267 28 14 80 31 115 39 54 12 1425 15 9458 20 5989 3 9439 9 9517 15 459 37 865 206 1084 451 202 225 317 510 380 935 19 124 19 687 1 810-68 452-194 746-412 965-209 210-487 335-910 406-86 15-468 17-3900 24-2093 4-6357 8-9477 9-4072 1-5687 4-5725 12-201 42-374 215-417 417-15 73-16 2393 0 2477 33 181 169 338 344 400l70 25 8940-1c4917 0 9327-4 9800-9z" fill="url(#a)" transform="matrix(.1 0 0 -.1 0 4096)"/></svg>
```

**Comment by dio-gh** [comment]
Nice! Works for me. Gonna do the insignia too and we're golden.

**Comment by Megamouse** [comment]
I still don't understand why there are llvm changes

**Comment by dio-gh** [comment]
I misinterpreted the git output. It claimed after I switched to the branch that there were changes made, and so I kept going in circles resetting submodules, syncing, and so on, over and over again. All I had to do is to just accept and commit the changes,  because they were the actual new commits made upstream.

All fixed, ready to go.

**Comment by Megamouse** [comment]
image
image
image
image
image
image

**Comment by Megamouse** [comment]
this dio and his locked branch...
REBASE

**Pull request merged**
