### PR TITLE
[Qt/OpenGL/AMD]: fix gamepad settings layout issue, add refresh button / fix amd openGL Emu stop bug

### PR DESCRIPTION
**Pull request by Megamouse**
should fix this:

image

It cuts off the last part though. I hope it is okay. (as in: DragonRise Inc. Gene...)

image

### CODE REVIEW

**Comment by Oky12** [comment]
Why the gamepad setting rpcs3 windows. different with the picture?

**Comment by Megamouse** [comment]
you might be on an outdated version xD

**Comment by Oky12** [comment]
thanks to tell me to update. but on mmjoystick. i cannot config that
screenshot 155

**Comment by Megamouse** [comment]
yeah thats normal
previously you could open it but everything should have been greyed out I think

**Comment by Oky12** [comment]
oh..... so in current build rpcs3. only config keyboard

**Comment by Megamouse** [comment]
are you actually able to configure buttons in older builds with mmjoystick?

**Comment by Oky12** [comment]
no

**Pull request merged**
