### PR TITLE
Fix Miku

### PR DESCRIPTION
**Pull request by Nekotekina**
_Credits to @RipleyTom and @Stewie10 for investigating the root of Diva F 2nd's issue_

### CODE REVIEW

**Comment by AniLeo** [comment]
This fixes Project Diva F 2nd. I completed the game.
Here's proof: https://www.youtube.com/watch?v=QnIe4WaEv_8

**Comment by Stewie10** [comment]
I also kind of helped with this. I found out wut was causing the songs not to load. I removed the motion names from the file pv_db.ppr in data.psarc so the characters wouldn't appear, and then the song loaded

**Comment by raveskirza** [comment]
The logs are getting spammed with the below messages for games like Soul calibur 4 and Tekken 6 after this commit. Also performance degradation in these games

E {PPU[0x1000001] Thread (mainThread) [0x006260b0]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM
E {PPU[0x1000001] Thread (mainThread) [0x005e376c]} 'sys_lwmutex_trylock' failed with 0x80010008 : CELL_EDEADLK

**Comment by Nekotekina** [comment]
Try to disable logs by configuring config.yml:
``
Log: {"": Fatal}
``

**Comment by redtankbai** [comment]
> I also kind of helped with this. I found out wut was causing the songs not to load. I removed the motion names from the file pv_db.ppr in data.psarc so the characters wouldn't appear, and then the song loaded

how could you edit pv_db.ppr? plz help

**Pull request merged**
