### PR TITLE
CMake refactor fixup (LLVM disabled in UI and Qt resources missing)

### PR DESCRIPTION
**Pull request by kukkamario**
- Fixes LLVM recompiler options being disabled in the UI and Qt resource files not being properly included in the build

### CODE REVIEW

**Comment by kukkamario** [comment]
@scribam Can you verify that this pull request fixes the issues?

**Comment by Josko** [comment]
Fixed the issues for me.

**Comment by greentop** [comment]
Ubuntu 18.04 - qt 5.11.1

```
F {Audio Thread} St13runtime_error thrown: Invalid audio renderer: PulseAudio
(in file /home/green/rpcs3/rpcs3/rpcs3_app.cpp:265)
```

**Comment by kukkamario** [comment]
@greentop I added a commit that probably fixes your issue. Could you verify the fix?

**Comment by greentop** [comment]
@kukkamario 55a206d fixes the pulseaudio problem. A new issue now seen is that evdev is missing from the gamepad settings.

**Comment by kukkamario** [comment]
@greentop Thanks for testing. Same issue with that also...

Squashed these fix up commits to one and included a couple lines that should fix libevdev being missing.

**Comment by greentop** [comment]
Evdev is working again as of 9ff2ca4.

**Comment by scribam** [comment]
@kukkamario I found an other regression: I can not build RPCS3 when I use `-DWITHOUT_LLVM=ON`. Can you please have a look at it?

**Comment by kukkamario** [comment]
@scribam I think I found the issue and opened new pull request https://github.com/RPCS3/rpcs3/pull/5149 

I think it isn't related to CMake refactoring and some other change broke it.

**Pull request merged**
