### PR TITLE
Implements sys_fs_disk_free

### PR DESCRIPTION
**Pull request by RipleyTom**
Might(?) help disgaea d2 and a few other games.

### CODE REVIEW

**Comment by ScorchEmber256** [comment]
Will this help the ratchet and clank series?

**Comment by JayC-03** [comment]
Why was this closed? It fixed the filesystem issue with GTA 4.

**Comment by AniLeo** [comment]
@RipleyTom Is reworking it and will reopen when ready.

**Comment by MarioSonic2987** [comment]
GTA IV still works without this PR.

**Pull request closed without merging**
