### PR TITLE
cellAudio: Implement cellAudioSet/RemoveNotifyEventQueueEx

### LINKED ISSUE #7272: Alien Isolation - unimplemented 6ch audio.
Some videos in USM format contains no audio and can be played by emulator, however several of them contains 6ch audio, maybe 2ch too.
Those can't be played and cause game to stuck.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4079003/RPCS3.log.gz)

### PR DESCRIPTION
**Pull request by elad335**
Thanks to @isJuhn who did debugging.
Fixes #7272.

### CODE REVIEW

**Comment by elad335** [comment]
hw test for when both CELL_AUDIO_EVENTFLAG_DECIMATE_4/2 flags are set:
https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellAudioSetNotifyEventQueueEx

**Comment by TigiHof** [comment]
The videos in Alien: Isolation finally work, I can hardly believe my eyes! Great job!

**Comment by isshininu** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4176837/RPCS3.log.gz)

Works.

**Comment by 13xforever** [comment]
This PR fixed sound in Zone of the Enders Collection launcher (disc version)

**Pull request merged**
