### PR TITLE
cellVdec: Do not decode next frame during end_sequence

### PR DESCRIPTION
**Pull request by GinkREAL**
Fixes issue #2930, only tested on the intro cutscene.

### CODE REVIEW

**Comment by fifazalata** [comment]
OH MY GOD FINALLY
Tested it & it's working as it should.
too bad I've already beaten the game.
But nevertheless, you did a good job. thank you so much for fixing that long lased issue.

**Comment by isshininu** [comment]
hmm.....
> If we watch a cutscenes until the end, the screen goes black and we cant play anymore..
Sounds familiar...


This PR also fixes #3382 ,
1) menu videoscene
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1885888/RPCS3.log.gz)

**Comment by greentop** [comment]
This PR fixes the hang in BLUS31535 that occurred if you allowed the intro video to play for longer than a second. (The bug appeared sometime around an month ago.)

**Comment by kdlz4161** [comment]
F {rsx::thread} class std::runtime_error thrown: Unknown wrap mode 0x0
(in file Emu\RSX\gcm_enums.cpp:588)

**Comment by Charmareian** [comment]
This fixes the issue with NPUB31241 (Project Diva F) freezing on the intro video.

**Comment by Dominosity** [comment]
I'm sorry I have to ask, but where is this cellVdec file placed?

**Comment by Megamouse** [comment]
rpcs3/Emu/Cell/Modules/cellVdec.cpp

**Comment by tlm-2501** [comment]
I'm assuming you're trying to test this PR. This is not done by replacing a file but rather by downloading the build. Head over to the commits tab, click the green check mark near the latest one, go to Appveyor details and, under Artifacts, find the version of RPCS3 that corresponds to this PR. Use that to test the changes.

**Comment by VelocityRa** [comment]
Protip: Go to the main repo and press "T". You can search any file.

**Pull request merged**
