### PR TITLE
Drop d3d12 backend

### PR DESCRIPTION
**Pull request by kd-11**
F

### CODE REVIEW

**Comment by MSuih** [comment]
Remember to remove dx12 from /rpcs3/Emu/CMakeLists.txt as well.

**Comment by hyperspeedgx** [comment]
Finally! Fuck Microsoft!!

**Comment by illusion98** [comment]
Direct3D12. 😿

**Comment by danilaml** [comment]
@hyperspeedgx it's not: https://devblogs.microsoft.com/directx/world-of-warcraft-uses-directx-12-running-on-windows-7/

**Comment by purifiedh2o** [comment]
> @hyperspeedgx it's not: https://devblogs.microsoft.com/directx/world-of-warcraft-uses-directx-12-running-on-windows-7/

You're wrong, only for that game.

**Pull request merged**
