### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by hcorion**
@probonopd
We've just ran into a weird issue with the AppImages finding the Qt5.9 libs, this fixes it, please see if this makes sense to you.

### CODE REVIEW

**Comment by probonopd** [comment]
Can you please elaborate "weird issue with the AppImages finding the Qt5.9 libs"? Can you point me to an error message?

**Comment by hcorion** [comment]
@probonopd It would fail on ldd with:
```
ERROR: ldd outputLine: "libQt5Widgets.so.5 => not found"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```
I have no idea why it would suddenly do that, no changes were made to the AppImages, or the Qt PPA.

**Comment by hcorion** [comment]
Here is the entire failing log: https://travis-ci.org/RPCS3/rpcs3/jobs/246174834

**Comment by probonopd** [comment]
Thanks @hcorion, so if it works with the suggested change then I'd say go with it.

**Pull request merged**
