### PR TITLE
[vk] Check for BGRA8 linear image to support blitting

### PR DESCRIPTION
**Pull request by kvark**
The result of `upload_image_simple` is used as a blit source, so we need to make sure it's possible.

### CODE REVIEW

**Comment by kvark** [comment]
@kd-11 thanks for the review! comments are addressed now.
Also renamed the variable to just `bgra8_linear` since the other ones also check for blit support and the don't reflect that with `_blit` suffix.

**Comment by kd-11** [comment]
Its ok now. Its quite strange to have a GPU with the BGRA8 format not usable as a blit source, I wonder how many other formats cannot be easily copied to the backbuffer via blitting.

**Comment by kvark** [comment]
@kd-11 
*Copying* is fine, it's the blitting that's not so easy. Blitting is different in that it [requires a graphics queue](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkCmdBlitImage.html), and can be implemented under the hood as a graphics operation.

Also, it's not BGRA8 that is problematic but the fact of placing it in HOST_VISIBLE memory (with linear tiling). Vulkan baseline requirements for HOST_VISIBLE images are super low, e.g. only 2D with a few formats, and they aren't required to support any graphics operations. Basically, they are glorified staging buffers, and that's how Metal portability backend implements them. Hence, they can only be used in transfers.

**Comment by kd-11** [comment]
> Also, it's not BGRA8 that is problematic but the fact of placing it in HOST_VISIBLE memory
Makes sense, otherwise it would have been strange as drivers often just implement blitting with a full-quad pass which would have made the user-side implementation of the same redundant. Thanks for that clearing up.

**Pull request merged**
