### PR TITLE
Remove mentionbot config

### PR DESCRIPTION
**Pull request by ibrakap**
This PR removes mentionbot config because mentionbot not used.

### CODE REVIEW

**Comment by AniLeo** [comment]
It hasn't been removed in order not to lose the blacklist, because the bot can eventually be re-added

**Comment by JohnHolmesII** [comment]
The bot *will never* be readded. Ever.

**Comment by elad335** [comment]
The file is saved in github history, if someone wants to readd the bot just readd the file.

**Comment by Nekotekina** [comment]
Fine, fine

**Pull request merged**
