### PR TITLE
PRX/savestates/VSH: Associate PRX with library, fix VSH browser

### LINKED ISSUE #11305: Regression: VSH Browser (#8431)
## Quick summary
VSH Browser worked before https://github.com/RPCS3/rpcs3/commit/54308920522adc7c850335f607f2fc44cd5b6797
Removing the check lets it load up properly again.

### LINKED ISSUE #13204: Savestate is not working
### Quick summary

Savestates is not working since build 0.0.26-14527. RPCS3 just crashed when booting with savestate. Last working build is 0.0.26-14526.

### Details

_No response_

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/10386907/RPCS3.zip)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
* Fixes #13204.
* Fixes #11305.

image

### CODE REVIEW

**Comment by Megamouse** [comment]
There's zero explanation or comments for the last commit

**Comment by elad335** [comment]
sys_vm commit based on:
image

Attempts to fix #11305

**Comment by Darkhost1999** [comment]
Before
image0
After
image1

**Comment by Kravickas** [comment]
Savestates regression fixed for me

**Comment by elad335** [comment]
Reverted cellGame commit.

**Comment by Megamouse** [comment]
> Reverted cellGame commit.

needs to be rebased with removal before merge

**Comment by elad335** [comment]
Can't rebase.

**Pull request merged**
