### PR TITLE
Refactor Pads & take events only from game window

### PR DESCRIPTION
**Pull request by flash-fire**
Test to make sure I didn't accidentally make input impossible. Only external difference to user is that now putting input into the rpcs3 application window won't feed into game window now.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Does pad_test.elf work? It doesn't have render window.

**Comment by flash-fire** [comment]
I'll check later. If not, I'll just bypass the filter if no valid target has been set. Easy change.

**Comment by flash-fire** [comment]
What a nuisance that gsrender is initialized but the application is still console!

**Comment by flash-fire** [comment]
Defer this until hle gcm is merged since that'll be the refactoring which changes immediately to make this code better. No point having this weird "isVisible" crap if in a few weeks, it'll be gone. Closing for now!

**Pull request closed without merging**
