### PR TITLE
Add installation for Linux

### PR DESCRIPTION
**Pull request by hcorion**
- Integrates .desktop from #2713 
- Addresses one of the problems in #2479
- Increments the progress towards an AppImage, see the issue here: #2744 

I've moved the .icon and .xpm files to a new /Data folder, based on the Dolphin emulator.
I've also updated the .xpm to the newer logo featured in the .icon.
I also created a .svg based on the new .ico, I'm no graphic artist, but I think it turned out OK.

I used the citra and dolphin emulators for inspiration.

Somebody needs to test this PR on Windows to make sure the icons still work.
**EDIT:** Don't bother viewing commit by commit, I tried to make it clean, but git just wouldn't work with me.

### CODE REVIEW

**Comment by hcorion** [comment]
Hmm, the edits I made to rpcs3_.rc didn't seem to work on Windows, Can anyone help my out?

**Comment by AniLeo** [comment]
Needs rebasing

**Comment by Nekotekina** [comment]
I'd like to avoid this "Data" folder
How we are supposed to update the version number?
Shouldn't desktop file be generated from cmake?

**Comment by hcorion** [comment]
@Nekotekina 

I added to Data folder to keep all of the non-code related assets in one place, because the root rpcs3 folder was starting to get a little messy. Dolphin emulator calls it Data, Citra emulator calls it dist, PPSSPP stores the icons in the icons folder, but I don't think it has a .desktop file for linux.

I just realized that the version number of the .desktop file is not the version of RPCS3, but the desktop spec version, I'll fix that.

It really doesn't make much sense to generate the desktop file from cmake, most source code I've seen just has a pre-made .desktop, and cmake doesn't really have a way to generate .desktop files AFAIK.

**Comment by hcorion** [comment]
RIP Pull Request, I tried my best.

**Comment by Nekotekina** [comment]
What's happened?

**Comment by hcorion** [comment]
I tried to squash the commits, and totally screwed up it up.

**Comment by AniLeo** [comment]
Here's a _shadowcopy_ of your PR: https://github.com/RPCS3/rpcs3/commit/132a7a6986161c7e7079adfa3d0d4a07cb24b27e
You can just grab those back and reopen

**Comment by hcorion** [comment]
@AniLeo Thanks! That helps a lot!
@Nekotekina  While I'm working on a new Pull Request, would you rather the .svg, .png, .desktop, .ico and be in the root rpcs3/rpcs3 folder? There is no technical reason for using the Data folder I thought it would be just cleaner.

**Pull request closed without merging**
