### PR TITLE
[WIP] TSX masterrace

### PR DESCRIPTION
**Pull request by Nekotekina**
Only processors with TSX are getting improved performance currently. If you don't have TSX, just ignore this PR for now.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Pushed new commit, it may have significant impact on performance in some cases.

**Comment by srdjan1995** [comment]
@Nekotekina In my case, overall decrease impact on performance. Started Dragon Ball Raging Blast, 10-15 FPS in menus. Using master or latest build by kd-11 (0.0.5 - 6631) I get 60 FPS in menus. I will re-test the build later with other games.

**Comment by digitaldude555** [comment]
Master
screenshot 1713
PR
screenshot 1710

**Comment by kdlz4161** [comment]
F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:912)

**Comment by srdjan1995** [comment]
Same thing here, performance are reduced a lot by these commits.

**Comment by marc0303** [comment]
With the last commit there is a significant performance increase on BLUS30011, but the game hangs within a minute or two. I assume it's a deadlock of one of the spu threads, but that's just a guess.

Here are the relevant logs:
https://pastebin.com/wPhgGMwe

**Comment by Xcedf** [comment]
Nice work here, Neko, got some free frames on this PR
here's quicktest
master

PR

master

PR

**Comment by Xcedf** [comment]
But there's a regression also
like on farseer's spuperf branch before, games like Uncharted or MotorStorm, or GoW now can randomly hang

**Comment by Zangetsu38** [comment]
this pr don't like my ryzen, i have big slow speed

**Comment by rodjun** [comment]
Ryzen doesn't have TSX right? Neko is probably aware of that, considering he told people without tsx to ignore the PR

**Comment by Zangetsu38** [comment]
yes, but this pr totaly broken perfomance on ryzen so no, i don't ignore that lol

**Comment by greggameplayer** [comment]
@Nekotekina you should had a detection if people have TSX compatible processor or not and apply this change if they have a TSX compatible processor.

**Comment by AniLeo** [comment]
@greggameplayer that doesn't make any sense, TSX path is already only enabled if present, obviously there are two paths, one for TSX and one for no-TSX

**Comment by al0xf** [comment]
Read what he wrote: **If you don't have TSX, just ignore this PR for now.**

Obviously no PR that brings Ryzen down to 3 fps will be merged, just wait for this _Work In Progress_ PR to be finished.

**Comment by RainKikyou** [comment]
Drakengard3 and Gundam EXVSFB（ stable 60fps on 6700K）no longer breaks the sound，but there is a random crash problem
https://cdn.discordapp.com/attachments/272875751773306881/431059001275449344/QQ20180404195424.png

**Comment by legend800** [comment]
I have an intel i7 6700k (supposedly it has TSX turned on) and noticed no difference in my games that can't hit full speed. Not a single frame from I what see. Though things are more unstable. 

RR7 is broken as an example. I get the following in RR7 menus which I haven't seen before and i can't proceed: 
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300800

**Comment by marc0303** [comment]
This new commit fixed the game hanging. The performance improvement on my current machine (i7 6700) are really impressive!

**Comment by Xcedf** [comment]
Became more stable it's true, but still can randomly hang

**Comment by whjhs1010203** [comment]
I think it doesn't support haswell CPU with TSX.
(microcode is 17)
It's a little slow than master.

**Comment by zwammetje** [comment]
Haswell was supposed to support TSX but it's turned off due to a faulty implementation. Check Intel ARK for your processor.

**Comment by whjhs1010203** [comment]
My CPU is i5-4570S, it's support TSX in the past.
I tried to downgrade microcode to unlock TSX.
Now, it's shows support TSX in HWinfo as well as in CPU-Z.
But log no change in rpcs3.
Thanks for your comment.

**Comment by RainKikyou** [comment]
Surprisingly! Eternal Sonata (Trusty Bell - Chopin no Yume Reprise) reaches full speed stability 30FPS.
unfortunately, it's too easy to crash

**Comment by Xcedf** [comment]
Latest code changes seems to fixed random hangs, stable as master now
and here's some more frps improvements
Master

PR


Master

PR

**Comment by Zangetsu38** [comment]
last time tested, perfomance on No more heroe improved, but few regression, No more hero crash before can play, lastr master works, and tlou and other regression freeze directly

**Comment by Rpcs3tester** [comment]
Siren blood curse BCES00294 no longer run with this PR

it's freez before start screen
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1885687/RPCS3.log.gz)

**Comment by Rpcs3tester** [comment]
Heavenly Sword BCUS98132

no longer get to stage select with this PR
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1885722/RPCS3.log.gz)

**Comment by Zangetsu38** [comment]
Datura also broken before show every things

**Comment by Kazeira** [comment]
Persona 5, Infamous, Uncharted, Red Dead Redemption and Ratchet & Clank Freeze now

**Comment by TigiHof** [comment]
I'm getting random freezes all over the place during shader compilation (Heavy Rain, Bayonetta, Alien: Isolation, Life is Strange etc). I'm adding the log for Heavy Rain (BCES00802) as an example.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1885746/RPCS3.log.gz)

I guess, currently it makes to sense to keep the last merge in the master branch. Please revert!

**Comment by NPJB00512** [comment]
Gundam EXVSFB 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1885966/RPCS3.log.gz)

**Comment by samir1231** [comment]
God of war 2 is not freezeng anymore but audio is not working. Am I the only 1 with this problem?

**Comment by Charmareian** [comment]
Hyperdimension Neptunia Mk2 now has visual artifacts constantly flickering. 

Master
untitled

PR
untitled2

**Comment by GeniusMage** [comment]
Tales of Vesperia: no longer ingame, throws a MEM access violation on the SPU or the PPU before the main menu
[Log Vesperia](https://github.com/RPCS3/rpcs3/files/1887194/Vesperia.log.gz)

Tales of Graces f, Xillia 1 & 2: major sound issues.
[Log Graces](https://github.com/RPCS3/rpcs3/files/1887196/Graces.log.gz)

**Comment by Asinin3** [comment]
I can confirm, having same issue as Zangetsu in WipEout HD (white-screen after selecting ship before reaching loading screen), Uncharted 1 (freeze during loading coin animation), and Infamous 1 (freeze after showing infamous logo). But this seems to only affect non-tsx users currently.

**Pull request merged**
