### PR TITLE
Use new shaders decompiler in OpenGL backend.

### PR DESCRIPTION
**Pull request by O1L**
Based on DH's old commits.
Some samples / games are broken, but it is in a good stage for merging in our pre-alfa version.

### CODE REVIEW

**Comment by kd-11** [comment]
@O1L Are the broken samples regressions?

**Comment by raven02** [comment]
Just compiled and tested simple games like Ardeko 01/2/3, looks like they didn;t boot .

**Comment by kd-11** [comment]
The glsl shader generation used here is a bit dated. It is based off of the old glsl compiler from a while back. It is actually lacking a lot of functionalty that has since been added (e.g vertex frequency instancing, etc) , support for integer vertex formats, etc.

**Comment by kd-11** [comment]
Also, this would undo most of the refactoring done by vlj without any obvious advantages. I thought it was to fix shader_window_origin issues, but it seems that is still a todo here. I suggest we just improve the somewhat unified decompiler in place and add functionality that would make emulation more precise to that rather than going back so far. If the decompiler here fixes any bugs, we can incorporate the changes to all existing backends that way.

**Comment by 11DH11** [comment]
@kd-11, all fixes would be merged with new decompiler. Also, all backends can use new decompiler and cache, but it's TODO. ogl renderer is test-platform for now. New decompiler generates much more readable shader, which much easier to understand what he do and find bugs.

shader_window_* registers properly handled in rsx_cache branch, but seems be broken in that pull request. Anyway, we will fix it

**Comment by kd-11** [comment]
@11DH11 Ok, but then at least incorporate all the changes and improvements that we've added since january so that we avoid too many regressions. This changeset discards alot of progress.

**Comment by 11DH11** [comment]
@kd-11, look at http://www.emunewz.net/forum/showthread.php?tid=174583&pid=231665#pid231665

Btw, affected changes related to the decompilers. Not so much changes to merge

**Comment by kd-11** [comment]
@11DH11 If its policy then I guess its ok

**Pull request closed without merging**
