### PR TITLE
[No Merge] praise miyazaki

### PR DESCRIPTION
**Pull request by kd-11**
- Disable jt in safe mode

Fixes souls games regression. Likely fixes several other regressions. For testing only as the core issue is getting investigated.

### CODE REVIEW

**Comment by Emulator-Team-2** [comment]
Fixes freeze in  Ni No Kuni.

**Comment by EmulationChannel** [comment]
@kd-11 @Emulator-Team-2 Fixed and DARK SOULS 2 ❤

**Comment by isshininu** [comment]
A-awesomeness!
Praise @kd-11

**Comment by psennermann** [comment]
NiNoKuni works again, but the first time I loaded the save file, after a minute of gameplay I got the following violet (random?) error (Vulkan):

F {rsx::thread} class std::runtime_error thrown: VirtualProtect failed (00000001e0b6b000, 0x3000, addr=0x1e0b6b000, error=0x1e7)

But this also might be unrelated to this PR, because there have been a lot of other PRs merged during the NiNoKuni "vacation"...

**Comment by theoldsport** [comment]
I was wondering if you would get impatient! Thanks for the workaround kd :)

**Comment by kd-11** [comment]
Commit https://github.com/RPCS3/rpcs3/commit/afd5af04f6e83df50c548798b65a73bc6e6f69e9 has been merged into master and incorporates this and other improvements. Closing as this is no longer needed.

**Pull request closed without merging**
