### PR TITLE
Trying to fix thread scheduler regression

### PR DESCRIPTION
**Pull request by Nekotekina**
Attempt to address #9657

I think I was careless and forgot to add special path for all ones.

### CODE REVIEW

**Comment by arabek** [comment]
image
Works as expected when run with process affinity set by system (first load column)

Fails when using "cpu scheduler" option from the gui. First run (2nd column) is okay, but if you stop and start (without exiting the emu) - the affinity mask resets to that of the system now.

**Comment by Nekotekina** [comment]
Strange... Do you by chance have logs or did you notice errors in log window saying "Failed to set thread affinity"?

**Comment by arabek** [comment]
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5873843/RPCS3.log.gz)
two subsequent runs (without exiting the emulator) (i've disabled setting the affinity from the system on this run, thus the screenshot differs re load)

**Comment by arabek** [comment]
> Strange... Do you by chance have logs or did you notice errors in log window saying "Failed to set thread affinity"?

I've noticed because of the cpu load monitor (gkrellm). Logs attached in previous comment.

**Comment by Nekotekina** [comment]
Okay, try this one please.

**Comment by arabek** [comment]
Nope, still the same. First run ok, second affinity setting ignored.

Log attached.

image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5874001/RPCS3.log.gz)

**Comment by arabek** [comment]
It fixes the first case - setting affinity by the from the system - so at least might be merged in current state as is.

I'm not sure about the second case - if the regression was introduced by the previous merge.

**Comment by Nekotekina** [comment]
So, the latest commit didn't change anything? I suspected it could be deeper problem than a simple revert.

**Comment by arabek** [comment]
> So, the latest commit didn't change anything? I suspected it could be deeper problem than a simple revert.

Yeah, it's the same before and after the last commit in this pr.

**Comment by arabek** [comment]
Should i open another bug report re consecutive runs?

**Comment by Nekotekina** [comment]
Idk, I even have a habit to always close rpcs3 to restart something. If you know how you can try to add logging to thread_ctrl::set_thread_affinity_mask and see if it gets some weird values on second run.

**Pull request merged**
