### PR TITLE
rsx: Optimizations and refactoring

### PR DESCRIPTION
**Pull request by kd-11**
This PR grew a little large, but largely consists of 4 parts:
- Code refactoring to improve readability. This is far from finished, RSXThread class is a monstrosity that needs to be gelded. This will take many more PRs to finish, so I did the basics to get them out of my way.
- Move all gcm enums to a simpler model. Rsx enums are a 1:1 translation with the PS3 values, and most to_xxxx are now inlined and consist of a basic range check. The codegen is pretty nice, most of these evaluate to like 4 instructions now. An added benefit is that we don't need to assert that the values are correct anymore, the caller will decide whether they want to assert or not.  This avoids wastefulness. The name of the wrapper is rsx::expected (stolen from std::expected, but doesn't behave the same).
- Move non-essential signal methods to simple signal lists. Instead of taking a CPU branch only to set a flag, we can just do that inline which saves on CPU resources. Using this we can, without any additional overhead, pass any kind of signals we like to the backend.
- Use the signal mechanism above to completely ellide the expensive shader load process for vulkan. This is still incomplete. With the power of EXT_dynamic_state GPU extensions, we can do much, much more, but I decided to not implement it with this PR to minimize the amount of changed code (I failed :laughing: )

Fixes https://github.com/RPCS3/rpcs3/issues/13095

### CODE REVIEW

**Comment by ArbestRi** [comment]
Sonic Generations appears to be running good on this build

**Comment by cipherxof** [comment]
Performance seemed to be about the same on MGS4.

**Comment by Scalerize** [comment]
Midnight Club: Los Angeles Gained 2 frames on my rig, which is a huge leap considering the circumstances.

**Comment by kd-11** [comment]
Last commit breaks some games, I'll investigate tomorrow.

**Comment by kd-11** [comment]
Finally fixed all the problems I could find. Hopefully no major regressions!

**Comment by Triticum0** [comment]
This build makes Folklore crash on Linux I drop the log below
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10394731/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Cannot reproduce, file an issue report with detailed repro steps

image

**Comment by caffeinekid** [comment]
Disgaea 3 worked in previous pr and freezes on startup and takes down the whole emulated system in this version.

F {RSX [0x0001ddc]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\expected.hpp:80[:13], in function front_face)

image

**Pull request merged**
