### PR TITLE
GL: fix wireframe in Catherine

### PR DESCRIPTION
**Pull request by raven02**
I don't think we need this obsolete function that do the anti-aliasing.

fix https://github.com/RPCS3/rpcs3/issues/2241

### CODE REVIEW

**Comment by Zangetsu38** [comment]
also fixed Splatterhouse
capture d ecran 2017-04-09 17 57 39

**Comment by AnonJump** [comment]
Problem still exists. GTX 560 Ti (448 cores)

**Comment by al0xf** [comment]
Fixed on Linux with a GT 555m...

**Comment by raven02** [comment]
Thanks @kd-11

**Comment by Luffykun007** [comment]
Demon's souls after the warp zone is now like this with opengl

capturar

**Comment by kd-11** [comment]
Demon's souls has lighting bug that causes darkness bugs. Reload the save to fix it.
@raven02 You were right to disable poly smooth; its not compatible with the blend mode catherine uses and I suspect the nvidia driver in rsx ignores this flag. I'm surprised its still in core opengl tbh.

**Comment by AnonJump** [comment]
Hooray! I fixed this problem using "Remove Game" in "Game List". After reinstalling the data, the stripes disappeared.

**Comment by ArtyomAN** [comment]
> Demon's souls has lighting bug that causes darkness bugs. Reload the save to fix it.
I have the same issue. When I finish the very first location from the tutorial, the game tries to load another location, and then I see black screen like on the picture above.
If I try to exit the game (for loading my character again), the emulator hangs on _every time_. :-(

**Pull request merged**
