### PR TITLE
Update of README for Linux and OSX

### PR DESCRIPTION
**Pull request by piotr-szegda**
Removed information about LLVM and fixed build command

### CODE REVIEW

**Comment by AniLeo** [comment]
I think libedit-dev can also be removed from the Ubuntu command since it was related to LLVM. 
I'll try to confirm if compiling without it works tomorrow if no one else does.

**Comment by molotiv** [comment]
I looked at a successful Travis build log online (for example: https://s3.amazonaws.com/archive.travis-ci.org/jobs/128118567/log.txt) this helped me make a build on my Mac. 

With my limited  knowledge it seems that the way the build chain explained in the readme just didn't work for me. 

The build only ran with llvm 3.6.2. The readme should leave out how to install that.

**Comment by molotiv** [comment]
*shouldn't leave that out

**Comment by tambry** [comment]
@molotiv LLVM is no longer is used in RPCS3. The warning message is slightly inaccurate, we don't really "require" it. The warning can likely be removed, though.

**Comment by Nekotekina** [comment]
There is no need to remove everything LLVM-related if you want to remove the message.

**Comment by Nekotekina** [comment]
Maybe we'll restore the recompiler "tomorrow". If seriously, it only needs to be ported to new ppu_decoder, and it's annoying.

**Comment by piotr-szegda** [comment]
@Nekotekina: I thought it will not by used anymore. If you going to use it in my opinion it's pointless remove this warning. But you should fix detection of LLVM by change find_package(LLVM CONFIG) to find_package(LLVM 3.6) but I am not sure is this will by work on other then Linux OS. But compile command is definitely wrong.

**Comment by Nekotekina** [comment]
Ah, I incorrectly commented out find_package because it was completely broken in MSYS2.

**Pull request closed without merging**
