### PR TITLE
Add Master Volume to Settings Dialog

### PR DESCRIPTION
**Pull request by Megamouse**

### CODE REVIEW

**Comment by MSuih** [comment]
You could add a warning that values over 100% can reduce sound quality. Also you could add tickmarks to at least the center position of the slider so that it'd be easier to visually identify where it is, and perhaps to 50% and 150% values as well. 

I also think it'd work better as a vertical slider that fills the screen from top to bottom, that way selecting values with mouse would be easier.

**Comment by Megamouse** [comment]
I can easily add the tickmarks. But I'm not really into the vertical slider as long as there's only a single volume slider.

**Comment by Megamouse** [comment]
Also please just post the desired Tooltip text here.

**Comment by MSuih** [comment]
"Values above 100% might reduce audio quality"? I'm not the best guy when it comes to phrasing English though.

**Comment by Megamouse** [comment]
Haha neither am I

**Comment by Megamouse** [comment]
I hope it's okay if I merge it now. Further changes can be done later on or in a future settings dialog overhaul (though there isn't any planned yet)

**Comment by xelmasx** [comment]
Diablo 3 Reaper of Souls Ultimate Evil Edition . Sound has gone!

**Pull request merged**
