### PR TITLE
Add Nekotekina skin

### PR DESCRIPTION
**Pull request by Andryshik345**
pls merge me, meow~

### CODE REVIEW

**Review by isJuhn — APPROVED** [review]

**Review by dio-gh — APPROVED** [review]

**Review by illusion0001 — APPROVED** [review]

**Review by Fabianpaw — APPROVED** [review]

**Review by Spikol02 — APPROVED** [review]
that is so nice that I cum

**Comment by RedDevilus** [comment]
I have this file in secret, but i agree sharing is caring.

**Comment by Andryshik345** [comment]
also pls download my translation(extract it to RPCS3's root folder and choose catalan language), it's very cute~
[kot translation.zip](https://github.com/RPCS3/rpcs3/files/5132307/kot.translation.zip)

**Comment by RedDevilus** [comment]
Spanish community will be confused.

**Review by RedDevilus — APPROVED** [review]

**Comment by Andryshik345** [comment]
megamouse, kot locale when

**Comment by HerrHulaHoop** [comment]
it's glorious
rpcs3-10768_2020-08-27_00-33-54
rpcs3-10779_2020-08-27_00-36-23

**Review by Mrlinkwii — APPROVED** [review]
LGTM

**Review by isshininu — APPROVED** [review]

**Comment by illusion0001** [comment]
Use integer or nearest neighbor scaling on the large neko image on the right side

**Review by xddxd — APPROVED** [review]

**Review by mavethee — APPROVED** [review]

**Review by mavethee — APPROVED** [review]

**Comment by Spikol02** [comment]
Finally I can stalk neko even in RPCS3 Itself Nya

**Comment by Spikol02** [comment]
When this gets merged neko will do another karaoke together with mave 
Putin confirmed that

**Comment by Spikol02** [comment]
When this gets 20 likes then I will start working on the progress reports on the first of september

**Review by clienthax — APPROVED** [review]

**Review by elad335 — APPROVED** [review]

**Comment by Satan86** [comment]
Update: Spikol started working on progress reports

**Pull request merged**
