### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Nekotekina**
Related issues: #972, #568 (not sure)

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@Nekotekina  What remove my change in d3d12format.cpp ?

**Comment by Nekotekina** [comment]
I didn't remove your change. I just rewrote them. Lol.

**Comment by vlj** [comment]
Why replacing unreachable by throw ? You can throw in unreachable_internal if necessary.
Throw looses the filename and line number information in the process.

**Comment by Nekotekina** [comment]
EXCEPTION macro contains file and line too, I don't think it's less informative.

**Comment by O1L** [comment]
throw's better then the "Please report this..." bla-bla-bla. If it's a very serious error - throw exceptions.

**Comment by danilaml** [comment]
@O1L @Nekotekina you missing the point. The request to report to dev is usually there to find games that use certain feature so it could be used to test it. Without this it would be easier to overlook this error (rpcs3 doesn't run some game properly? what a surprise!) and place it with others or just ignore it.

**Comment by Nekotekina** [comment]
Maybe add this message to every exception automatically? Ideally they never occur so it may be always worth reporting.

**Comment by Ekaseo** [comment]
for some reason, i cant change the controlls, it always uses the default ones

**Comment by vlj** [comment]
Since there are exception in D3D12GSRender, is it possible to destroy GSRender object if an exception is caught ?
If a command is not executed then the backend is left in an unstable state. Future operation will always throw or worst, a device removal signal can be issued by windows and invalidate several pointers.
When rpcs3 crashes this is not an issue but with this PR it looks like all exception will be reported to the TTY with the ability to resume execution. The proper way to do in such case is to automatically shutdown D3D12GSRender and potentially restart it.

**Comment by Nekotekina** [comment]
Thread stopped with an exception will not resume. Other threads may resume, but resuming was not really intended, emulation is paused in order to observe debugging state which is not immediately destroyed.

**Comment by Zangetsu38** [comment]
@danilaml Problem, you change for D3d12format not works, log indicate only line for problem, but not indicate what instruction missing, not works...
Please fix it

**Comment by danilaml** [comment]
@Nekotekina Why you merged this? You haven't explained why you removed noexcept everywhere. Even in places where it clearly should be.

**Comment by Nekotekina** [comment]
Where it "clearly should be"? There is no such place there.

**Comment by danilaml** [comment]
@Nekotekina https://github.com/Nekotekina/rpcs3/commit/aa811b6eefad2d907261c17c056b26a37bd03d29#diff-c749b2137d171010e40efb7281deb412R214
https://github.com/Nekotekina/rpcs3/commit/aa811b6eefad2d907261c17c056b26a37bd03d29#diff-c749b2137d171010e40efb7281deb412R196
https://github.com/Nekotekina/rpcs3/commit/aa811b6eefad2d907261c17c056b26a37bd03d29#diff-c749b2137d171010e40efb7281deb412R171
https://github.com/Nekotekina/rpcs3/commit/aa811b6eefad2d907261c17c056b26a37bd03d29#diff-c749b2137d171010e40efb7281deb412R224
https://github.com/Nekotekina/rpcs3/commit/aa811b6eefad2d907261c17c056b26a37bd03d29#diff-c749b2137d171010e40efb7281deb412R309
https://github.com/Nekotekina/rpcs3/commit/aa811b6eefad2d907261c17c056b26a37bd03d29#diff-c749b2137d171010e40efb7281deb412R315
and so on.

**Comment by Nekotekina** [comment]
Oh please, stop it. Read https://akrzemi1.wordpress.com/2011/06/10/using-noexcept/ - there is absolutely no reason to add noexcept to any function just because it "looks small and non-throwing".

**Comment by danilaml** [comment]
@Nekotekina so you are saying that this function might throw?
```C++
size_t get_index_type_size(u32 type)
{
	switch (type)
	{
	case CELL_GCM_DRAW_INDEX_ARRAY_TYPE_16: return 2;
	case CELL_GCM_DRAW_INDEX_ARRAY_TYPE_32: return 4;
	default: return 0;
	}
}
```

**Comment by O1L** [comment]
@Zangetsu38 always use 0x%x for logging in a hex format.


Zangetsu38 commented
And "0x" it is a usseless, no utile, it is best this "%x"

LOL. You do not understand. Stop shitting in RPCS3 code.

**Comment by Zangetsu38** [comment]
@O1L huh, what are you talking about, you're aware that the returned value is a single number?
So the "0x" placed before is useless, it all points.
My example shows good, its is pointless to have "0x4" only "4" interests us.
So yes, clearly, the "0x" before is completely unnecessary.
But let's say that I understand nothing, it just seems logical that's all great.
And if I shit in the code, it means that the code is therefore already the problem, since I have seen several times when there was not just the "0x" and that's just fine, example in cellAdec etc.

**Comment by Nekotekina** [comment]
@danilaml Let's see... Among 2^32 possible `type` values only 2 values are valid, others are probably wrong. And that mysterious zero return value doesn't solve anything, it's not even checked by the caller. I guess it fails silently. I'd just throw there, but I'm not correcting such bugs now.

**Comment by danilaml** [comment]
@Zangetsu38 %x prints number in hex format (4 is less than 16 so it looks the same). 0x is there to indicate that number is hex (so if it prints 0x10 then it's not 10 but 16).

**Comment by Zangetsu38** [comment]
@danilaml Uh ok, I understand nothing, if in both cases indicated that "10" or "0x10" I do not see where is the difference, as the "0x" will always be placed before, so how we see the difference?

**Comment by danilaml** [comment]
@Zangetsu38 http://ideone.com/D7WqWd

**Comment by O1L** [comment]
You argue like a stubborn donkey. It looks silly and not even funny.
If we see the 0x10 - we know that this is in hex format and 0x10 == 16 (in decimal format). If we see just 10, we think that this is 10. Understandably?

**Comment by Zangetsu38** [comment]
@O1L @danilaml ok but fo bit trip 
>E {rsx::thread} Exception: Invalid format (0x10)
(in file Emu\RSX\D3D12\D3D12Formats.cpp:312, in function get_color_surface_format)
Please report this to the developers.

Sorry but before "10" now "0x10" it is a change nothing 

I want to say is that the "0x" always appears before I tested, so it does not help, if "5" it shows "0x5", yet it is just "5 ", and when it is" 16 "so it reads" 0x10 "except that before that already showed" 10 ", so sorry but it didnt changed absolutely nothing.

**Comment by danilaml** [comment]
@Zangetsu38 0x is to indicate that number is in hex: https://fr.wikipedia.org/wiki/Syst%C3%A8me_hexad%C3%A9cimal#Notation

**Comment by Zangetsu38** [comment]
@danilaml No, but I understood that, but in this case it's not walking too, "0x" is absolutely still, it's useless even if it indicates "5" it is written "0x5".
So no, there is a problem in the state, it indicates nothing of it changes nothing compared to before, it just puts a "0x" before all, that's all.

**Comment by danilaml** [comment]
@Zangetsu38 the values may be bigger than 9 in which case you need 0x to resolve ambiguity.

**Comment by tambry** [comment]
Dear Mr. @Zangetsu38,

    I'd like to let you know of you being banned from the RPCS3 organization. This means that you wont be able to fork, send pull requests, open issues and comment on both issues and pull requests. The ban should come into effect in less than a couple hours.
    This decision was made after careful consideration by the core developers on RPCS3. We found your code contribution and comments often useless, disruptive or a waste of developers' time. Please remember, that this decision was ~~not~~ made lightly.
    We hope you understand the decision, and will be able to use the extra time for actually learning programming and the basic concepts of it.

Happy christmas,
RPCS3 team

**Comment by Zangetsu38** [comment]
@tambry  hu Why ? Me banned ? for Why ?...

**Comment by Zangetsu38** [comment]
@danilaml Yes, I know, I said I understood.
Ah unless it only works for number above 9 and from 10 that indicates either "0x10" to "16" or just "10" to "10".

**Comment by tambry** [comment]
@Zangetsu38 The reasons have been stated in my previous post.

**Comment by danilaml** [comment]
@Zangetsu38 there is a thing called consistency.

As you can see, most of your PRs turn into a big discussion because you clearly don't understand some fundamental concepts (plus overhead for language barrier). The team decided that'd be easier to only accept testing contributions from you and don't waste their time making you understand and fix some things. Sorry.

**Comment by Zangetsu38** [comment]
@tambry Except I do not understand, I never did anything wrong overlooked the project, I did everything to help and make project forward ...

**Comment by Zangetsu38** [comment]
@danilaml I just give my point of view, that's all.
And pardon if I do not understand everything, I really try :(

**Comment by tambry** [comment]
@Zangetsu38 We understand that you try, but unfortunately programming doesn't seem to area of expertise fit for you, right now. We have already previously warned/told you to politely to stop wasting developers' time.
While you might not be good at programming or making code contributions, I still think that you make useful contributions in the form of game testing and reporting issues with different games. I hope you will continue to make contributions in the future in by testing games and reporting the issues on forum or IRC.

**Pull request merged**
