### PR TITLE
Add Patreon link on about dialog

### PR DESCRIPTION
**Pull request by Zangetsu38**
Add Patreon link on about dialog
Change PS3 to A PlayStation 3
Change Ok to Close for close Window About RPCS3
Preview this change
capture d ecran 2017-01-31 10 29 44

### CODE REVIEW

**Comment by slx7R4GDZM** [comment]
Shouldn't the S in PlayStation be capitalized?

**Comment by Zangetsu38** [comment]
@slx7R4GDZM  Yes, thx, i have changed ^^

**Comment by raven02** [comment]
It is sort of cosmetic changes and i'll merge it .

**Comment by AniLeo** [comment]
Now Appveyor download link is broken because build failed 
https://ci.appveyor.com/project/rpcs3/rpcs3/branch/master/artifacts

**Comment by Zangetsu38** [comment]
@AniLeo Strange, perfect build before merge
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-3646

**Comment by Zangetsu38** [comment]
Is good Now ^^

**Pull request merged**
