### PR TITLE
BUILD: Refactor yaml-cpp submodule

### PR DESCRIPTION
**Pull request by p01arst0rm**
moved yaml-cpp files into separate directory.

### CODE REVIEW

**Comment by p01arst0rm** [comment]
cc @hcorion

**Comment by hcorion** [comment]
Looks fine, though I wonder if the comment and hacks mentioned are still relevant in the latest release of yaml-cpp? Might be worth rebasing Neko's commits over the latest version of yaml-cpp.

**Comment by p01arst0rm** [comment]
is it worth leaving that for another PR? instead of complicating things on this one

**Comment by hcorion** [comment]
Yeah that makes sense

**Pull request merged**
