### PR TITLE
libfs.sprx enabled

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by woody2014** [comment]
since sys_fs rewrite brutal legend Error disk can not be read

**Comment by JackONeill12** [comment]
Sonic Unleashed went from stuck in Loading screen with 0.03 FPS to 20 FPS in Loading Screen. Doesn't crash but gets stuck in an Loading screen Loop with:

U {PPU[0x1000013] Thread (LoadScheduler) [0x0291b9a8]} sys_fs TODO: sys_fs_test(arg1=0x6, arg2=0x0, arg3=*0xd0183050, arg4=0x4, arg5=*0xd0182be0, arg6=0x420) -> CELL_OK

RPCS3.log
https://drive.google.com/file/d/0Bzv00_6oh0fhNkQ4c2htZUE0QWc/view?usp=sharing

**Comment by JackONeill12** [comment]
Also, Kingdom Hearts 1.5 and Kingdom Hearts 2.5 stopped working. Now only showing black screen with FPS.

RPCS3.log
https://drive.google.com/file/d/0Bzv00_6oh0fhcFBDSGZlQXJ6LWs/view?usp=sharing

**Comment by Nekotekina** [comment]
KH must be fixed, thanks.

**Comment by JackONeill12** [comment]
Can confirm. KH is working again.

**Comment by Zangetsu38** [comment]
regression on DMC HD, log say this in loop and won't boot
>·U 0:11:48.983898 {PPU[0x1000000] Thread (main_thread) [0x0066f9a8]} sys_fs TODO: sys_fs_test(arg1=0x6, arg2=0x0, arg3=*0xd000f130, arg4=0x4, arg5=*0xd000ecc0, arg6=0x420) -> CELL_OK
·W 0:11:48.983948 {PPU[0x1000000] Thread (main_thread) [0x0066eec0]} sys_fs: 0xc0000006: 0x20, 0x10, 0x18, “/dev_bdvd/PS3_GAME/USRDIR/BUNDLES/DMC.BDP”, 0x0, 0x80010003, 0x0

**Comment by SakataGintokiYT** [comment]
*Some games showing this : 
Fotoszok.pl
**[*There is not enough avaialbe space in HDD (...) Log:](https://gist.github.com/SakataGintokiYT/7a845292f654f0039555035712e9abc5)**
**[*Error dialog-Log:](https://gist.github.com/SakataGintokiYT/42699471c9333d4b279844a811432cd0)**

*Some games doesn't start up:
**[*Log:
](https://gist.github.com/SakataGintokiYT/e5cfb5b98922c1a7d49ab4abca3cdcd2)**

**Comment by Zangetsu38** [comment]
Yes several game have problèm with libfs for install Trophy or other data

**Comment by Zangetsu38** [comment]
Error in dengeki
capture d ecran 2017-04-23 16 16 58

**Comment by Zangetsu38** [comment]
Disgaea 3 loop
>U {PPU[0x1000000] Thread (main_thread) [0x00010230]} sys_fs TODO: sys_fs_test(arg1=0x6, arg2=0x0, arg3=*0xd000f3e0, arg4=0x4, arg5=*0xd000ef70, arg6=0x420) -> CELL_OK

**Comment by JackONeill12** [comment]
Sonic Unleashed gets past the first loading screen now. Shows Sega intro then crashes in the next loading screen.

RPCS3.log:
https://drive.google.com/file/d/0Bzv00_6oh0fheGlQbjhCd2NIMTQ/view?usp=sharing

**Comment by Zangetsu38** [comment]
Disgaea 3 boot works, dmc works but only in Auto, lv2 freezed in black screen, "A.O.T." no change, "Dengeki Bunko Fighting Climax" also no change

**Comment by AniLeo** [comment]
Sonic Unleashed (Demo) is okay now
image

**Comment by Blaypeg** [comment]
Unable to start Ni no kuni BLUS30947 with this build

**Comment by AniLeo** [comment]
What error do you get?
image

NPEB90452 works here

**Comment by Blaypeg** [comment]
It loads when using 41a6185f but not when using d48723aa.

I've tried various settings for PPU/SPU but all same result
The main window opens, but title bar just says "GSFrame[OpenGL]" instead of going to frame counter. Log attached.
[kunilog.txt](https://github.com/RPCS3/rpcs3/files/952918/kunilog.txt)

**Comment by SakataGintokiYT** [comment]
@Nekotekina 

**Ratchet and Clank® Future: Tools of Destruction-Demo-{NPUA98153}**
```
E {PPU[0x1000012] Thread (fios mediathread) [0x008b6ee4]} 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED
```
**[Log: ](https://gist.github.com/SakataGintokiYT/29c7e74e54117b10605aee9bd48e638e)**


---------------------------------------------------------------------------------------------------------------
Ricochet HD-{NPEB00223}-  **Infinite loading screen**

```
E {PPU[0x100000b] Thread (Game-Data Preloader) [0x0070c198]} sys_fs: sys_fs_open(“/dev_hdd0/game/NPEB00223/USRDIR/Data/Cache/CFLs/Background.cfl”): failed to open file (flags=0, mode=0)
E {PPU[0x100000b] Thread (Game-Data Preloader) [0x0070c198]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT

```
**[Log: ](https://gist.github.com/SakataGintokiYT/b27df125e497c70811fa1c807c41a807)**

**Comment by AniLeo** [comment]
@Blaypeg That's not the full log. Full log is RPCS3.log
Don't use liblv2 for Ni no Kuni, use Automatic Library Loading.

**Comment by Blaypeg** [comment]
You're right, it loads fine with Automatic Library. 

Sound is improved from few builds previous. Thanks for help

**Comment by Zangetsu38** [comment]
A.O.T fixed
Dengeki Bunko Fighting Climax, fixed

**Comment by Nekotekina** [comment]
Any problems remaining?

**Comment by SakataGintokiYT** [comment]
**LEGO Indiana Jones: The Original Adventures**

```
E {PPU[0x1000000] Thread (main_thread) [0x009aa090]} sys_fs: sys_fs_open(“GAME.DAT”) failed: device not mounted
E {PPU[0x1000000] Thread (main_thread) [0x009aa090]} 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED
```
**[Log:](https://gist.github.com/SakataGintokiYT/d24600669a6ecfeec936a6f5abf48981)**

**Comment by SakataGintokiYT** [comment]
Can you check this ?

**Call of Juarez: Bound in Blood Demo**
```
E {PPU[0x1000000] Thread (main_thread) [0x0209bee4]} 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED
E {PPU[0x1000000] Thread (main_thread) [0x01423bb4]} sys_fs: sys_fs_opendir(“/dev_bdvd/PS3_GAME/USRDIR/CoJ2/Out/”) failed: device not mounted
E {PPU[0x1000000] Thread (main_thread) [0x01423bb4]} 'sys_fs_opendir' failed with 0x8001003a : CELL_ENOTMOUNTED
E {PPU[0x1000000] Thread (main_thread) [0x0209bee4]} 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED
E {PPU[0x1000000] Thread (main_thread) [0x014238a8]} sys_fs: sys_fs_open(“/dev_bdvd/PS3_GAME/USRDIR/CoJ2/Data0.pak”) failed: device not mounted
E {PPU[0x1000000] Thread (main_thread) [0x014238a8]} 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED
E {PPU[0x1000000] Thread (main_thread) [0x0209bee4]} 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED

```
**[Log:](https://gist.github.com/SakataGintokiYT/f59289e249a00956636aefa1f7632c76)**

**Pull request merged**
