### PR TITLE
SPU/PPU reservations: Optimizations

### PR DESCRIPTION
**Pull request by elad335**
- Implement vm::reservation_trylock, optimized locking on reservation stores with no waiting. Always fail if reservation lock bits are set.
- Make SPU accurate GET transfers on non-TSX not modify reservation lock bits.
- Add some optimization regarding to unmodified data reservations writes.
- Use optimized PPU signaling to SPU on reservation pause.
- Improve SPU LLVM MFC transfers recompilation for non-TSX.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
I do not know if it was intentional, but using your release on (already broken) Gran Turismo 6, I have got a semaphore timeout (appeared once, but not the second time).

**Comment by legend800** [comment]
Got 1-2 more fps in Motorstorm Apoc. vs. today's master. I'm up to 22fps in my "test spot" now. :)

**Comment by elad335** [comment]
I added a commit attempting to improve non-tsx performance, tester are welcome.

**Comment by LaneSh4d0w** [comment]
Build failed, cannot test release.

**Comment by elad335** [comment]
@LaneSh4d0w fixed.

**Comment by MsDarkLow** [comment]
Saw a major improvement in Yakuza Ishin, accurate getllar was enabled.
8700k@5GHz (NO-TSX)

Master: 21 to 24 fps
PR: 28 to 32 fps
<details>
<summary>Images</summary>

Master
Master

PR
PR

</details>

**Comment by elad335** [comment]
The goal here is to improve performance both on non-TSX oath **and** TSX path.
So testing both of them is important.

**Comment by LaneSh4d0w** [comment]
Seems to have fixed Gran Turismo 6

image

image

**Comment by xddxd** [comment]
Gran Turismo 6 is still not fixed here. Are you using TSX?
Screenshot_3
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4603291/RPCS3.log)

**Comment by LaneSh4d0w** [comment]
@xddxd CPU not supported for TSX.

**Comment by LaneSh4d0w** [comment]
@xddxd Works if you don't have any savedata. I suppose it's a savedata issue. (since the save data is based on the Japanese game release, the European one might not like it.)
image

**Comment by xddxd** [comment]
Can confirm, it only works if there is no savedata.

**Comment by elad335** [comment]
Added another optimization for non-TSX.

**Comment by LaneSh4d0w** [comment]
No regressions so far when testing different games. No better results too.

**Comment by elad335** [comment]
Actually wait a bit as I want to change lines.

**Comment by elad335** [comment]
Made the changes I wanted.

**Comment by AniLeo** [comment]
Needs testing in a few games to ensure they didn't regress

**Comment by elad335** [comment]
I tested them locally, I know what the changes are and what they affect.

**Comment by MsDarkLow** [comment]
Update as per request.
8700k@ 3.7GHz
Persona 5 is tested in Central Street, this is kinda RSX bottlenecked but tested anyways.
Yakuza Ishin (**NULL RENDERER**) is tested in Fushimi by the Singing bar
Portal 2 is tested with SPU Thread Auto and 2 at Test Chamber 5. With TSX Auto the game already performs nicely, but no-tsx is another story.
- With SPU Thread Auto I'll stand still at the start when you descend from the elevator 
- With SPU Thread 2 I'll be spinning around on a button with 

<table>
 <tr>
  <td><b></b></td>
  <td colspan="2"><b>TSX</b></td>
  <td colspan="2"><b>NO TSX</b></td>
 </tr>
 <tr>
  <td></td>
  <td><b>PR</b></td>
  <td><b>Master</b></td>
  <td><b>PR</b></td>
  <td><b>Master</b></td>

 </tr>
 <tr>
  <td>Yakuza Ishin (NULL)</td>
  <td>33 - 36</td>
  <td>31 - 34</td>
  <td>25 - 27</td>
  <td>18 - 20</td>
 </tr>
 <tr>
  <td>Persona 5</td>
  <td>42 - 49</td>
  <td>42 - 47</td>
  <td>39 - 44</td>
  <td>39 - 42</td>
 </tr>
 <tr>
  <td>Portal 2 (Auto)</td>
  <td>30</td>
  <td>30</td>
  <td>30</td>
  <td>19 - 22</td>
 </tr>
 <tr>
  <td>Portal 2 (2)</td>
  <td>30</td>
  <td>30</td>
  <td>28 - 30</td>
  <td>20 - 30</td>
 </tr>
</table>

**Comment by AniLeo** [comment]
Yakuza 0 Demo (OpenGL, Mesa, R9 280X)

Master: 25-29 FPS
PR: 30-34 FPS

RDR works better, didn't benchmark a single spot

**Comment by zminhquanz** [comment]
GOW 3 has improve a little bit performance , very good job developer

**Comment by legend800** [comment]
@elad335 This PR also fixed Star Wars Force Unleashed 2 loading menus. However, it only works with TSX off. Can you look into fixing the TSX path too?

**Pull request merged**
