### PR TITLE
rsx: Fix some shader decompiler bugs

### PR DESCRIPTION
**Pull request by kd-11**
- Fixes broken textureGrad and packed float assignment in some corner cases
- Also removes the .xyz restriction on textureproj in case a perspective divide is required. This should resolve shadow projection in some games, but might break other cases where w is expected to be 1.
- Catches precision overflows that causes some ingame effects to be black. Thanks to @O1L for spotting the regression in a ps3 autotest sample.

Most of these bugs detailed here: https://github.com/RPCS3/rpcs3/issues/2328

### CODE REVIEW

**Comment by raven02** [comment]
Probably this one worthwhile to checkout with shader error https://github.com/RPCS3/rpcs3/issues/2407

**Comment by MarioSonic2987** [comment]
Tested in https://github.com/RPCS3/rpcs3/commit/e189d146756fea9447dd177ae1863e16772ecf80.

Shadows are fixed in Saint Seiya: Brave Soldiers.

**Comment by SakataGintokiYT** [comment]
@kd-11 

**[e189d146]**

**Naruto: Ultimate Ninja Storm 1**

**OpenGL**
```
E {rsx::thread} RSX: Failed to compile shader: 0(81) : error C1031: swizzle mask element not present in operand "z"

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(81) : error C1031: swizzle mask element not present in operand "z"
(0) : error C2003: incompatible options for link
'
```

**[Log:](https://gist.github.com/SakataGintokiYT/89538f1497af3195a80d071be28b3791)**


Vulkan

```
E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:80: 'z' : vector field selection out of range 
ERROR: 1 compilation errors.  No code generated.


E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:461)

```
[Log:](https://gist.github.com/SakataGintokiYT/d50d4d61332be3c8be38645f1f01b57d)

**DX12**

```
E {rsx::thread} RSX: FS build failed:D:\EMU\PS3\RPCS3.V2\FragmentProgram.hlsl(155,9-26): error X3018: invalid subscript 'z'

F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)

```

**[Log:](https://gist.github.com/SakataGintokiYT/7c9e8b25e9e10df728f13e3b3502b160)**

**Comment by digitaldude555** [comment]
PixelJunk Monsters crashed when going ingame before with this error.
```
E {rsx::thread} RSX: Unimplemented SIP instruction: CAL
E {rsx::thread} RSX: Failed to compile shader: 0(85) : error C0000: syntax error, unexpected '{', expecting ',' or ';' at token "{"

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(85) : error C0000: syntax error, unexpected '{', expecting ',' or ';' at token "{"
(0) : error C9000: internal corruption, aborting
```
Now it looks playable.
screenshot 928

**Comment by JohnGodgames** [comment]
Tested with https://github.com/kd-11/rpcs3/commit/1f7572aa325d1ef5f281da73b542d0205e35cfe5

Great work btw!

**VK throws**
```
F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file k:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)
```

and **DX12** throws bad conversion
`

**OGL**
motogp 08
sbk 09
sbk 08

**Comment by AniLeo** [comment]
Naruto Ultimate Ninja Storm (Demo) is working again

**Comment by SakataGintokiYT** [comment]
@kd-11 

**[a057b2e9]**

'Naruto games'
**DX12-blurred screen / shadow on the entire ground**
https://www.youtube.com/watch?v=B1cdVqjEP8Q

**OpenGL-multiple shadow issue**
https://www.youtube.com/watch?v=-WVWVh7qNLQ

**Vulkan-multiple shadow issue**
https://www.youtube.com/watch?v=Hze3bDSGREc

**Comment by JohnGodgames** [comment]
Tested many working games and not found any regressions...

**Comment by danilaml** [comment]
@raven02 @kd-11 No change with #2407
OGL:
image
Vulkan:
```
E {rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:79: 'texture2DReconstruct' : no matching overloaded function found 
ERROR: 0:79: 'xyz' : vector field selection out of range 
ERROR: 0:79: 'assign' :  cannot convert from 'const float' to 'temp 3-component vector of float'
ERROR: 3 compilation errors.  No code generated.


E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:467)
```
(after aircraft is selected)
D3D12 still crashes after start screen with
```
F {rsx::thread} class std::range_error thrown: bad conversion
```

**Comment by kd-11** [comment]
@danilaml Need to see the FragmentProgram.spirv file from the shaderlog with vulkan. As for opengl, I'm not sure which commit caused the regression so it might need some bisecting.

**Comment by raven02** [comment]
@kd-11 , here is the FragmentProgram.spirv

**Comment by kd-11** [comment]
Thanks. I will push fixes for vulkan and the broken ingame fog before merging this. Thanks for reporting.

**Comment by digitaldude555** [comment]
screenshot 963

persona 5 is blue now.

**Comment by kd-11** [comment]
Afterburner climax should be fixed now

**Comment by danilaml** [comment]
@kd-11 Fixed fog in After Burner for OpenGL
image
Vulkan worsk too, but has some minor texture artifacts (had them before):
image
image
(In actual game it's less apparent)
D3D12 still crashes with `F {rsx::thread} class std::range_error thrown: bad conversion`

**Comment by Zangetsu38** [comment]
strange, i have this after select flyer
>F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough
(in file g:\git\rpcs3-master\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:64)

**Comment by danilaml** [comment]
@Zangetsu38 maybe the behaviour differs depending on GPU.
This is there it crashes for me on both r9 290 and intel HD4400:
image
Btw, If I enable "Debug Output" in the options - the screen stays black.

**Comment by Zangetsu38** [comment]
strange, i have retry and works good

**Comment by RainKikyou** [comment]
DT is broken
qq 20170309071229

**Comment by kd-11** [comment]
I noticed PDF is buggy with latest commit but vulkan only. Will be fixed soon.

**Comment by JohnGodgames** [comment]
https://github.com/kd-11/rpcs3/commit/ef1a7c605a28790060a1e9c65a2901dbee33177b

Soul calibur 4 (OGL) is regressed too - blue flickering and white color on clothes

soul calibur 4 1 1
soul calibur 4 1
soul calibur 4 2

**Comment by kd-11** [comment]
Miku is fixed now

**Comment by kd-11** [comment]
@JohnGodgames Retest soul calibur with latest version

**Comment by digitaldude555** [comment]
screenshot 994

Miku is now confirmed fixed.

**Comment by JohnGodgames** [comment]
https://github.com/kd-11/rpcs3/commit/3ed066ed67d22fb556b8cd4a86f7ea810ed5d6f8 the same

soul calibur 4 3

**Comment by digitaldude555** [comment]
John is the blue gone? Cause persona 5 still has the blue. @JohnGodgames

**Comment by kd-11** [comment]
The games which appear broken (blue tinted sceen) with this PR were already broken with #INF/#NAN values which is why they are overbright. If you check previous output the brightness seems to have been wrong, just that GPUs set invalid values to black. Clamping makes them seem really bright and makes them appear buggy.
Will see if an intermediate solution is applicable that will help already broken games without causing regressions.

**Comment by clienthax** [comment]
Regression, dead or alive 5 ultimate,
Seems to just stop running before it gets to the menu screen (will need the return from the edat hash check removed)

**Comment by kd-11** [comment]
@clienthax The code here just changes emitted shader code with the exception of the fix to ignore invalid textures. Do you get "texture upload requested but texture not found" error in your log?

**Comment by kd-11** [comment]
BTW is persona also blue with vulkan or only with opengl?

**Comment by kd-11** [comment]
The brightness and blue tint stuff will be fixed shortly.

**Comment by digitaldude555** [comment]
Yeah both openGL and Vulkan is blue.

**Comment by kd-11** [comment]
Please retest

**Comment by JohnGodgames** [comment]
https://github.com/kd-11/rpcs3/commit/abda2de25c31e60ecb55a8c0c37e0e1003a71096

still the same

soul4 1

**Comment by SakataGintokiYT** [comment]
@kd-11 

**Sonic Adventure 2**

```
**OpenGL**
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file C:\rpcs3\rpcs3\Emu\RSX\GL\GLRenderTargets.cpp:224)
```
**[Log:](https://gist.github.com/SakataGintokiYT/fdeb32e65541ba48c8cfa17b5b3373ab)**

E {rsx::thread} RSX: ERROR: [Driver] Code 0 : vkCreateImage: image creation failed due to invalid parameter
F {rsx::thread} class std::runtime_error thrown: Assertion failed! Result is C4650B07h

**[Log:](https://gist.github.com/SakataGintokiYT/821bcc0d1d973eeabdfd5456b42c75aa)**

**Comment by kd-11** [comment]
@JohnGodgames Is the intro still blue though?

**Comment by SakataGintokiYT** [comment]
@kd-11 
**[e11a7e1f]**

-blue flickering is still there
Fotoszok.pl

**[Log:](https://gist.github.com/SakataGintokiYT/6835a9d82ce533df14fa082778bafa38)**
**[Shaderlog:](https://mega.nz/#!YUxWBBYK!U-YCMYy-VmVbiyzvXtkK6Hxa3aybQ8uAa_JL1fiMEpo)**

**Comment by kd-11** [comment]
Trace is more useful since the shaders do not have compilation errors

**Comment by SakataGintokiYT** [comment]
@kd-11 

I got this error 

```
Fatal error
Unhandled Win32 exception 0xC0000005.
Segfault reading location 000000000b26c0b0 at 0000000076685520.
Instruction address: 0000000076685520.
Module name: 'nvoglv64.DLL'.
Module base: 0000000075990000.
RPCS3 image base: 0000000000010000.

```
**[Log:](https://gist.github.com/SakataGintokiYT/7d0f169228e0f2beb2ca2bbaa0bf54a7)**

**Comment by kd-11** [comment]
Dialed back some of the stricter restrictions. Please confirm if it reverts the overly bright highlights and blue output in some games.

**Comment by digitaldude555** [comment]
Persona 5 stopped being blue.

**Comment by JohnGodgames** [comment]
https://github.com/kd-11/rpcs3/commit/0f05063b13f7cd74d298b118f1ea14cc86733a24

fixed - no blue flickering and overbright too

soul4 2

**Comment by kd-11** [comment]
I'd advice a quick round of retests. That fix was one of the major changes in the PR, so games like deadly premonition may have returned to their original state.
Either way, I won't tackle overflows with this pull request at this moment. I'll open a separate request for that.

**Comment by LeOsmos** [comment]
jojo all star battle's characters are black with little to no color on newest but i dont know since when this was a problem

**Comment by kd-11** [comment]
@LeOsmos I think that is a pre-existing error

**Comment by JohnGodgames** [comment]
https://github.com/kd-11/rpcs3/commit/0f05063b13f7cd74d298b118f1ea14cc86733a24

still good...

dp 1

**Comment by LeOsmos** [comment]
@kd-11 if you mean on master then no

**Comment by kd-11** [comment]
@LeOsmos Which build are you using? I've pushed several commits/revisions in the last few hours

**Comment by LeOsmos** [comment]
@kd-11 These:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-4108
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-4104

**Comment by LeOsmos** [comment]
@kd-11 New problem with:
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-4110/artifacts
it doesnt reach character select in jojo all star battle, it says "not responding"

**Comment by kd-11** [comment]
Its the same code, rebased on current master. The freezing is most likely due to another bug elsewhere.

**Comment by JohnGodgames** [comment]
freezing is propably caused with  new reservations https://github.com/RPCS3/rpcs3/commit/5e3bacbd9b3256942e973bbe74758ef7a0568a6b ...not related to this PR.

**Comment by SakataGintokiYT** [comment]
@kd-11 

**[7862464]**
This fixes flickering textures in Deception IV: Blood Ties on opengl.
Can you make the same changes in VK and DX12.

Fotoszok.pl

**Comment by Luffykun007** [comment]
@KD 11 This error in Red Dead Redemption is of your knowledge
capturar
capturar1
Using: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-4112

**Comment by aakh1361** [comment]
DEAD OR ALIVE 5 Ultimate [NPEB01786] have this error shader

> F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
0(70) : error C7011: implicit cast from "float" to "vec4"
(0) : error C2003: incompatible options for link

and now fixed but game green and ...
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/836597/RPCS3.zip)

**Comment by kd-11** [comment]
Clamping re-introduced using the precision flag from the opcode. Please retest persona 5 and soul calibur IV.
Jojo should also be fixed now as I have found the bug in my RSQ implementation

**Comment by digitaldude555** [comment]
Persona 5 is now blue again.

**Comment by JohnGodgames** [comment]
https://github.com/kd-11/rpcs3/commit/381c48359557684fdb61f9c6fdf80e66f3b55de9

results:
soulc4 1
soulc4 2

**Comment by kd-11** [comment]
Disabled precision clamping for now pending further investigation.

**Comment by Zangetsu38** [comment]
Nier news rose color
capture d ecran 2017-03-13 21 52 51

**Comment by danilaml** [comment]
@kd-11
Some recent changes in this pr seem to have introduced black texture regression in Catherine:
image

**Pull request merged**
