### PR TITLE
rsx: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
**Blit Engine**
- Forcefully downloads and reuploads data from the CPU in case of unexpected overlaps
- Properly detect correct size of newly created blit targets

**Other**
- Fix flip source buffer selection
- Fix resource readback for overlapping sections (WCB)
- Fix flickering in OpenGL

Fixes https://github.com/RPCS3/rpcs3/issues/5135
Also fixes part of https://github.com/RPCS3/rpcs3/issues/4258

### CODE REVIEW

**Comment by darkdragonz12** [comment]
sin titulo
 
in this detected blue background, with the game blazblue central fiction, although this no longer passes the menu remains frozen for months.

**Comment by Parthorisian** [comment]
[BLUS30209] Beast rider - first movie is normal, [pic0](https://i.imgur.com/ldh5nGk.jpg) but just black screen [pic1](https://user-images.githubusercontent.com/35437970/45712296-9e49f100-bb94-11e8-9e26-c8862b58aa9e.png) when goes ingame. Menu also works properly

**Comment by darkdragonz12** [comment]
sin
 God of war 3 same problem blue background.

**Comment by kd-11** [comment]
Will fix the red-blue color swap soon.

**Comment by stride21** [comment]
This PR made Ratchet and Clank Future: Tools of Destruction go ingame and has fix the flicker issue in its cutscenes and main menu.
tools of destruction

**Comment by Kravickas** [comment]
Retest against latest master, cos ratchet was fixed by other pr already merged

**Comment by ruipin** [comment]
He is correct, this PR (the second commit) fixes the flashing menu in R&C ToD, as well as fixing the black screen once you go in-game. The PR that went to master only got the game to the menu.

**Comment by stride21** [comment]
> 
> 
> Retest against latest master, cos ratchet was fixed by other pr already merged
> 
> Delete comment after
still has flickering during cutscenes and black screen when ingame
master

**Comment by legend800** [comment]
Rayman Legends colors are purple now (unless you turn on WCB + Blit):
C:\Users\Wes\Desktop\2018-09-18 18_45_50-FPS_ 59.94 _ Vulkan _ 0.0.5-0fcf6fa8-rsx_volatile _ Rayman® Legends [NPEB01356].png
Note: Still flickers also from Dec 2017 regression.

**Comment by greentop** [comment]
Ubuntu 18.04 - Nvidia 396.54 
screenshot from 2018-09-18 22-22-30
screenshot from 2018-09-18 22-27-31
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2395212/RPCS3.log.gz)

**Comment by kd-11** [comment]
I'll let you know when the blue is fixed so please don't spam reports.

**Comment by elad335** [comment]
Not sure if this is a progression or regression, but this pr fixes white, green and more colored rectangles, the only ones that remain are orange. This is not random and is reproducible on every run.
image

image

**Comment by kd-11** [comment]
Blue color bug should have been fixed, time to retest.

**Comment by greentop** [comment]
TOCS2 & Hyperdimention Neptunia color issues are fixed as of c852d5c.

**Comment by elhaya** [comment]
i concur - with the last commit, gow 3 blue screen is gone (without having to use cpu blit)

**Comment by raveskirza** [comment]
B2S ingame-->Loadable

Crashes with below message
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x7e): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:100)

[RPCS3.log_Master.gz](https://github.com/RPCS3/rpcs3/files/2398737/RPCS3.log_Master.gz)
[RPCS3.log_PR.gz](https://github.com/RPCS3/rpcs3/files/2398738/RPCS3.log_PR.gz)

**Comment by kd-11** [comment]
Verification error will be analysed further and I will decide whether to patch it now or wait for the refactoring. Looks like this is still WIP for now.

**Comment by elhaya** [comment]
@kd-11 i'm experiencing slowdowns, even to a complete crawl (2fps) with some of the games i tested.
for example, risen 3 and rdr, when using opengl. i have nvidia btw, maybe it has to do with your workaround?

**Comment by kd-11** [comment]
The performance regression should be fixed now. Turns out the driver is reusing texture handles and CheckFramebuffer is not actually checking to see if the handle is the same one used when attaching. Switched to manually tracking usage and attachment refs and the problem is now gone.

**Comment by HerrHulaHoop** [comment]
Confirmed, this PR fixed regression reported in #5001 where screen flickering was visible in Terraria [BLES01938] when using OpenGL after #4973

**Comment by isshininu** [comment]
This PR fixed DeS Valley of Defilement on OpenGL, when it was sometimes too much dark,

fps_ 30 11 _ opengl _ 0 0 5-7337 _ demon s souls bles00932 18 09 2018 22_10_01

Before
fps_ 30 11 _ opengl _ 0 0 5-7337 _ demon s souls bles00932 18 09 2018 22_09_52

**Comment by rekongstor** [comment]
Fixes #4348

**Comment by ruthan** [comment]
I can confirm that Golden Axe Beast rider issue is fixed, i can load first level and see cutscene, but after i get only black screen a hear game sounds..
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2405879/RPCS3.zip)

**Comment by MarioSonic2987** [comment]
Fixes flickering graphics in Sonic Generations.

Before (changes between good and black graphics):
image

After:
image

**Comment by MarioSonic2987** [comment]
In Worms Crazy Golf, fixes 2/3 screen issue in Vulkan, but breaks color with OpenGL.

image
image

image
image

**Pull request merged**
