### PR TITLE
rsx: Depth float bringup [1 of 3]

### PR DESCRIPTION
**Pull request by kd-11**
Infrastructure bringup to support more exotic features of floating point Z buffers later on. This is basically https://github.com/RPCS3/rpcs3/pull/8741 minus the extended Z range and custom depth clipping code. Part 2 will focus on OpenGL bringup and part 3 will close out the series with the extended Z clipping support.

### CODE REVIEW

**Comment by kd-11** [comment]
Note to testers: If everything goes correctly, nothing much should change between using this PR vs master. Performance and visuals (broken or otherwise) should generally remain the same until part 3 is added.

**Comment by gamrXerus** [comment]
Black ops boots ok for me like it does on master with this pr.

**Comment by Megamouse** [comment]
image

**Comment by Josivan88** [comment]
Call of duty BO3 still have problems:
Master:
COD BO3 Master
Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5120040/RPCS3.log.gz)
PR:
COD BO3
Log
[RPCS3_2.log.gz](https://github.com/RPCS3/rpcs3/files/5120046/RPCS3_2.log.gz)

Call of duty BO now boots but have a new problem, weapons are not showing properly anymore in both cases, and it is not flickering, Maybe waiting for the new Zdepth implementation?:
PR
COD BO PR
There are some shadows artifacts not present in master too
COD BO PR A
Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5120096/RPCS3.log.gz)
RSX Capture
https://drive.google.com/file/d/1uiYOP63TF7ehkxok7QZk3ptmCmsztjYj/view?usp=sharing
Master
Shadows are fine on Master
COD BO Master
Log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5120130/RPCS3.log.gz)

**Comment by Satan86** [comment]
Gran Turismo 5 spams the log with `E {RSX [0x0913e70]} RSX: Depth/stencil textures must have format class explicitly declared`

Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5120279/RPCS3.zip)

**Comment by xddxd** [comment]
No difference between master vs PR on GTA IV.

**Comment by xddxd** [comment]
GTA V spams `E {RSX [0x0194790]} RSX: Depth/stencil textures must have format class explicitly declared` in some areas compared to master. Didn't notice visual difference though.
PR:
[gtavpr.gz](https://github.com/RPCS3/rpcs3/files/5123317/gtavpr.gz)
Master:
[gtavmaster.gz](https://github.com/RPCS3/rpcs3/files/5123318/gtavmaster.gz)

**Comment by kd-11** [comment]
Fixed error spam and shadow problem in Black Ops. I don't know if Black Ops 3 is now fixed - if it is not, attach RSX capture for it.

**Comment by Josivan88** [comment]
Unfortunately COD Black Ops is not fixed on my end, it keeps in the "press start" screen, play background music, but not respond
Screen:
BO Problem
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5126222/RPCS3.log.gz)
RSX Capture:
https://drive.google.com/file/d/19ob7dMGtuU1H8cpyQcUxSrgPh3p5ndne/view?usp=sharing
Tested 6 times, cleared caches, and nothing
Master is Ok as always

COD BO3 behaves similarly, comes until the menu and become unresponsible on "Press X"
Screen:
BO3 Problem
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5126249/RPCS3.log.gz)
RSX Capture:
https://drive.google.com/file/d/17HuJuWy1nfIYWItwYK1JGfcJnBgGLbVZ/view?usp=sharing

**Comment by Josivan88** [comment]
My mistake on the last post, remaking everything

**Comment by kd-11** [comment]
You can capture with master @Josivan88

**Comment by Josivan88** [comment]
COD BO3 Captures using Master:

Before press X button:
Before
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5130175/RPCS3.log.gz)
RSX Capture:
[BLES02166_20200826102839_capture Before.zip](https://github.com/RPCS3/rpcs3/files/5130192/BLES02166_20200826102839_capture.Before.zip)

After Press X button:
After
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5130204/RPCS3.log.gz)
RSX Capture:
[BLES02166_20200826103057_capture.zip](https://github.com/RPCS3/rpcs3/files/5130207/BLES02166_20200826103057_capture.zip)

Ingame:
Attempt 1
Ingame
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5130219/RPCS3.log.gz)
RSX Capture failed with: F {PPU[0x100000a] Thread (hang detect) [0x0059b908]} VM: Access violation writing location 0x17 (unmapped memory)

Attempt 2
Ingame 2
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5130247/RPCS3.log.gz)
RSX Capture:
https://drive.google.com/file/d/1LlLjr2iPZMzyKDq1UXp2BnhIv9UR7efp/view?usp=sharing

**Comment by kd-11** [comment]
@Josivan88 You are not using the same config for master vs the custom build. You must LLE cellVoice for the game to proceed to multiplayer menu, which you did correctly on the master version, but is obviously not done for the PR. That's why you have the error spam in the log about unimplemented stuff in cellVoice which has nothing to do with graphics.

**Comment by Shuneferus** [comment]
Hello KD-11 the game Gundam Battlefield Record UC 0081 [BLJS10050] had a regression in this pr:
The fire and smoke from the mobile suit's turbines have disappeared or failed.

rpcs3_2020_08_27_21_46_35_218
rpcs3_2020_08_27_21_46_35_918
rpcs3_2020_08_27_21_46_37_584
rpcs3_2020_08_27_21_46_39_085


[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5139372/RPCS3.log)

**Comment by Drhycodan420** [comment]
This PR also makes explosion effects in Ninja Gaiden Sigma 2 run in slow motion.  I was running it without any slowdowns before this.

**Comment by Josivan88** [comment]
please attach log and RSX capture @Drhycodan420

**Pull request merged**
