### PR TITLE
HUGE TYPO FIX (URGENT) :hcorion:

### PR DESCRIPTION
**Pull request by Talkashie**

### CODE REVIEW

**Comment by kdlz4161** [comment]
F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:912)

**Comment by kdlz4161** [comment]
esboco 20 6

**Comment by greentop** [comment]
@kdlz4161 Does this error appear on Master?

**Comment by kdlz4161** [comment]
@greentop Yes Yes opens in master yes buddy how to solve this I am installed PCS VulkanSDK-1.1.70.1-Installer.exe

**Comment by Talkashie** [comment]
All I did was edit printed text... this error was certainly not caused by my PR lol

**Comment by kdlz4161** [comment]
@AniLeo this error comes from friends times until in the same site Master RPCS3 thing

**Comment by kdlz4161** [comment]
Drive Vulkan API of my NVIDIA GTX 1050 TI 4GB updated and same thing error with current VulkanSDK-1.1.70.1-Installer.exe

**Comment by AniLeo** [comment]
Stop spamming a fucking typo PR

**Comment by kdlz4161** [comment]
@greentop Yes Yes this error is Master friend yes

**Comment by NPJB00512** [comment]
Gundam EXVSFB can't play and Audio

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1887947/RPCS3.log.gz)

**Comment by rjracer007** [comment]
what is the configuration of the emulator to run this game?

**Comment by Asinin3** [comment]
Stop spamming PR's this was a typo fix, it would not have changed how Gundam ran in any way.

@rjracer007 GitHub is not the place for support questions, use our discord #help channel https://discord.me/RPCS3 or our forums https://forums.rpcs3.net/ though discord is by far the most active.

**Pull request merged**
