### PR TITLE
Silence some obvious warnings

### PR DESCRIPTION
**Pull request by danilaml**
Makes travis logs a bit cleaner

### CODE REVIEW

**Comment by hcorion** [comment]
While you're at it, could you fix
```
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/Cell/Modules/cellPad.cpp:251:61: warning: '&' within '|' [-Wbitwise-op-parentheses]
 data->button[1] = (0x7 << 4) | std::min(data->len / 2, 15) & 0xF;
                              ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/Cell/Modules/cellPad.cpp:251:61: note: place parentheses around the '&' expression to silence this warning
 data->button[1] = (0x7 << 4) | std::min(data->len / 2, 15) & 0xF;
                                                            ^
                                (                                )
```
and
```
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp:14:13: warning: 'extern' variable has an initializer [-Wextern-initializer]
extern bool g_avoid_lwm = false;
            ^
```
and
```
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/Cell/lv2/sys_event_flag.h:90:47: warning: '&&' within '||' [-Wlogical-op-parentheses]
  if ((mode & 0xf) == SYS_EVENT_FLAG_WAIT_AND && (pattern & bitptn) != bitptn ||
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/Cell/lv2/sys_event_flag.h:90:47: note: place parentheses around the '&&' expression to silence this warning
  if ((mode & 0xf) == SYS_EVENT_FLAG_WAIT_AND && (pattern & bitptn) != bitptn ||
                                              ^
      (                                                                      )
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/Cell/lv2/sys_event_flag.h:91:43: warning: '&&' within '||' [-Wlogical-op-parentheses]
   (mode & 0xf) == SYS_EVENT_FLAG_WAIT_OR && (pattern & bitptn) == 0)
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/Cell/lv2/sys_event_flag.h:91:43: note: place parentheses around the '&&' expression to silence this warning
   (mode & 0xf) == SYS_EVENT_FLAG_WAIT_OR && (pattern & bitptn) == 0)
                                          ^
   (                                                                )
```

**Comment by danilaml** [comment]
`extern` warning is not really a proper warning. It's just a codestyle issue. And there is no way to disable it on GCC (they "forgot" to add that option and it was only recently updated on their bug tracker).

Regarding operator precedence, I haven't touched them since some of them looked like a legit bug, so I'd rather the devs that worked on that modules to look at them. For example in cellPad.cpp `std::min(data->len / 2, 15) & 0xF` doesn't make sense, since the value will always be of min will always be <= 15 (and I doubt that len could be negative, but who knows? That's why I haven't touched it).

**Comment by paulsapps** [comment]
The extern is a "proper" warning. extern means the var is declared else where, so here extern should not exist. extern and being declared here makes no sense. :joy:

**Comment by danilaml** [comment]
@paulsapps it makes explicit that this variable is used as extern elsewhere though. And this is a fully valid code. See https://stackoverflow.com/a/21585233/4114447 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=45977

**Comment by paulsapps** [comment]
I disagree, if its not static then its clear it can be used extern anywhere else. If its static then it can't be used extern anywhere else. 

This not idiomatic usage at all thats why there is a compiler warning, it looks like a mistake. Nothing can can see this "extern" declaration because its in a cpp file anyway. Its completely useless.

**Comment by danilaml** [comment]
@paulsapps developers cans see it. Personally I see it like "this variable is intended to be used as extern in other TUs") Anyway, it was introduced by @Nekotekina so I'd rather he decided whether it's useless/wrong or not.

**Comment by paulsapps** [comment]
Yeah I get you, but its not idiomatic C++, the thinking should be this:

All globals are intended to be used else where unless they are marked static or contained in an anonymous namespace.

Otherwise `int foo = 5;` appears to not be intended to be used else where no? But it can be because it isn't `static int foo = 5;`. Also the use of extern like that is not consistent with all of the other true globals in the code base.

**Pull request merged**
