### PR TITLE
[WIP] CellSysutilBgmPlaybackExtraParam and sys_rwlock_trywlock

### PR DESCRIPTION
**Pull request by scribam**
Please let me know if
- You notice audio regressions or improvements while running games which use functions `cellSysutilEnableBgmPlaybackEx`, `cellSysutilDisableBgmPlaybackEx` or `cellSysutilSetBgmPlaybackExtraParam`
- You see any changes when running games which use write lock (`sys_rwlock_trywlock`, `sys_rwlock_wlock`)

### CODE REVIEW

**Comment by scribam** [comment]
@SakataGintokiYT Try to replace "status2->playerState = CELL_SYSUTIL_BGMPLAYBACK_STATUS_STOP;" by "status2->playerState = CELL_SYSUTIL_BGMPLAYBACK_STATUS_PLAY;" and see how it goes.
But I don't think this PR would help your game to run better than it is currently.

**Comment by SakataGintokiYT** [comment]
@scribam 
No change ehh ;/

**Comment by Nekotekina** [comment]
Whaaat, it's registered as syscall 126. We would have notice log TODO.

**Comment by scribam** [comment]
Well, according to http://www.psdevwiki.com/ps3/LV2_Functions_and_Syscalls#sys_rwlock_Syscalls, it also registered as syscall 148.
I am wondering if it was registered as syscall 126 in old firmwares and then it was changed to syscall 148 on newer ones.
An other example, PSL1GHT records only syscall 148 for sys_rwlock_trywlock: https://github.com/ps3dev/PSL1GHT/blob/534e58950732c54dc6a553910b653c99ba6e9edc/ppu/include/lv2/syscalls.h

**Comment by Nekotekina** [comment]
OK. It seems they are identical. Just don't rename 148, it's problematic.

**Comment by scribam** [comment]
@Nekotekina Is my commit about `sys_rwlock_trywlock` still necessary since you merge something similar?

**Comment by Nekotekina** [comment]
No, I completed it

**Pull request closed without merging**
