### PR TITLE
vk: Better VRAM heap selection by memory properties (AMD)

### PR DESCRIPTION
**Pull request by kd-11**
AMD has a special heap type that is not present on NV. It's a small 256M section that is device_local, coherent and host_visible. The current algorithm settles on this partition for device local since we dont check the size of the heap before deciding it is the better one. This pull request ignores this partition for device local invisible storage (used primarily for textures) since we can easily exceed allocation here and run into performance issues.

The new system prefers larger device local vram blocks since we cannot access it from the host, and prefers the cached visible vram for general purpose uploads. It should work fine with future hardware from any vendor.

A similar problem with the steam client overlay has recently been fixed, improving AMD performance on commercial vulkan titles. See http://phoronix.com/scan.php?page=news_item&px=Steam-Client-Beta-VK-AMDGPU for an example

### CODE REVIEW

**Comment by kd-11** [comment]
@raven02 Could you please confirm that this does not affect NV in any negative way? I'd like to avoid introducing any unwanted issues.

**Comment by raven02** [comment]
@kd-11 , it looks good on my system

**Comment by raven02** [comment]
@kd-11 , please rebase and we can merge it .

**Comment by raven02** [comment]
@kd-11 , it is out of data with master branch . Please rebase.

**Comment by raven02** [comment]
Sorry press the wrong button

**Pull request closed without merging**
