### PR TITLE
[Render] Userclip for d12/vk/ogl

### LINKED ISSUE #2152: DX12/Vulkan : user clip planes unimplemented
Vulkan
vk

GL
gl

DX12
dx12

### PR DESCRIPTION
**Pull request by jarveson**
Implement userclipping for dx/vulkan. Changed opengl to use same api as the others. Fixes #2152,

### CODE REVIEW

**Comment by SakataGintokiYT** [comment]
**[OpenGL]**

**Ni No Kuni: Wrath of the White Witch / Demo**

```
E {rsx::thread} RSX: Failed to compile vertex shader: 0(107) : error C1020: invalid operands to "*"
0(107) : error C0000: syntax error, unexpected ']', expecting ',' or ';' at token "]"

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(107) : error C1020: invalid operands to "*"
0(107) : error C0000: syntax error, unexpected ']', expecting ',' or ';' at token "]"
(0) : error C2003: incompatible options for link
'
```
[**Log:**](https://gist.github.com/SakataGintokiYT/1ea0cc579d52528c0e4392e6aeb8106f)

**KamenRider Battlide War**

```
E {rsx::thread} RSX: Failed to compile vertex shader: 0(117) : error C1020: invalid operands to "*"
0(117) : error C0000: syntax error, unexpected ']', expecting ',' or ';' at token "]"

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(117) : error C1020: invalid operands to "*"
0(117) : error C0000: syntax error, unexpected ']', expecting ',' or ';' at token "]"
(0) : error C2003: incompatible options for link
'
```

[**Log:**](https://gist.github.com/SakataGintokiYT/fd2c747e182398bce2bcd356adec7a24)


**Naruto: Ultimate Ninja Storm**

```
E {rsx::thread} RSX: Failed to compile vertex shader: 0(212) : error C1020: invalid operands to "*"
0(212) : error C0000: syntax error, unexpected ']', expecting ',' or ';' at token "]"

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(212) : error C1020: invalid operands to "*"
0(212) : error C0000: syntax error, unexpected ']', expecting ',' or ';' at token "]"
(0) : error C2003: incompatible options for link
'
```

[**Log:**](https://gist.github.com/SakataGintokiYT/3d477c1f9ec3dccb43ea3fb8c22bf413)

**Comment by raven02** [comment]
1942 Joint Strike also broken using Vulkan backend.

**Comment by raven02** [comment]
Meanwhile , need to check out Blade Arcus from shining EX where intro seq uses clip planes

**Comment by raven02** [comment]
Shining EX using GL backend 

```
F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(93) : error C1020: invalid operands to "*"
0(93) : error C0000: syntax error, unexpected ']', expecting ',' or ';' at token "]"
(0) : error C2003: incompatible options for link
```

**Comment by jarveson** [comment]
Fixed typo with opengl, it should get rid of the shader compile errors, ill look into the other issues as well

**Comment by SakataGintokiYT** [comment]
Problem with OpenGL is already fixed.

**Comment by jarveson** [comment]
Vulkan issues should now be fixed as well

**Comment by raven02** [comment]
Both Blade Arcus from shining EX and 1942 also work okay now.

**Comment by SakataGintokiYT** [comment]
KamenRider Battlide War and Naruto: Ultimate Ninja Storm now works okay on Vulkan.

**Pull request merged**
