### PR TITLE
gl/vk: Scale line width & point size by resolution scaling

### PR DESCRIPTION
**Pull request by VelocityRa**
This is a resolution scaling accuracy fix.

Some games (ie. Sly Cooper series) use the line width primitive for outlines, wireframes or similar effects, and they look wrong (too thin) when resolution upscaling is used, since this is specified by the game in pixels, and passed to the host unmodified.
This PR scales it by the resolution factor, just like RPCS3 scales various other things for res upscaling to work in the first place.

Not sure if this breaks any games / whether it should be configurable.
PCSX2 [enables it by default](https://github.com/PCSX2/pcsx2/blob/6f7890b709d5e3f7f5b824781e493455efc92339/pcsx2/Docs/Configuration_Guide/Configuration_Guide.md#outlines-on-shapes-or-models-are-improperly-sizedaligned) (see `m_userHacks_enabled_unscale_ptln` in code). 
> **Outlines on shapes or models are improperly sized/aligned**
> Usually this is because of an upscaling hack known formerly as Unscale Point and Line. This is now enabled by default because the overwhelming majority of games work nicely with it or need it. [...]

Reviewers: @kd-11

### CODE REVIEW

**Comment by MSuih** [comment]
This is missing comparisons, so I'll add some:

<details>
 <summary>Master with 300% scaling</summary>

screenshot-2021_08_15_09_15_22

screenshot-2021_08_15_09_16_15

</details>
<details>
 <summary>This PR with 300% scaling</summary>

screenshot-2021_08_15_09_09_05

screenshot-2021_08_15_09_14_12

</details>

**Comment by MarioSonic2987** [comment]
Screenshot comparison with Sly 3. With 200 % resolution scale (1440p).

Master:
image

PR:
image

**Comment by kd-11** [comment]
I'll need update with neptunia (BLES01178) with both integral and non-integral scaling factors. I remember refusing to scale points due to that game at one point, though I have not thought about this issue in almost 4 years now. It would be good to get updated test for that. Original ticket https://github.com/RPCS3/rpcs3/issues/3740

**Comment by kd-11** [comment]
Looks like nobody tested. Can we at least then get it with a config toggle so I don't have to revert in case of regressions?

**Comment by VelocityRa** [comment]
Discord user `YuriNator557` tested this, that issue does not happen now no matter the scaling factor.

**Review by kd-11 — APPROVED** [review]
lgtm

**Comment by illusion0001** [comment]
Fixed square patterns when upscaling in frostbite titles, although MLAA needs to be patched out for it to work.
meow

**Pull request merged**
