### PR TITLE
SPU/PPU Loader: Implement linker/PS3 compiler executable files loading

### PR DESCRIPTION
**Pull request by elad335**
These are compiler-used file responsible for inserting functions or inlined SPU/PPU libs. (so called .a and .o files, .a files can be extracted using 7z and similar tools and contains many .o files)
This is important for reversing or optimizing SPU/PPU libraries with the possibility of HLE them.

### CODE REVIEW

**Comment by Nekotekina** [comment]
I'm not sure, are you trying to RE them inside rpcs3? Is there any advantage over using external tools?

**Comment by elad335** [comment]
Yes, with minor code modifications you can even step through some alongside external tools.

**Comment by nitroos-ai** [comment]
Game freezes with this message while compiling PPU.
 `F {PPU[0x1000000] Thread (main_thread) [0x003acca8]} SIG: Thread terminated due to fatal error: PPU Trap! Sometimes tweaking the setting "Stub PPU Traps" can be a workaround to this crash.
Best values depend on game code, if unsure try 1.
(in file ../rpcs3/Emu/Cell/PPUThread.cpp:1579, in function ppu_trap) (errno=17=File exists)`

Spider-Man: Shattered Dimensions
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8617938/RPCS3.log)

**Comment by elad335** [comment]
@nitroos-ai #11924

**Comment by nitroos-ai** [comment]
Fixed with #11924.

**Pull request merged**
