### PR TITLE
rsx: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Improve memory protection behavior when strict mode is off. Use full range protection without trampling shared pages instead of only checking a single page. This fixes some missing graphics in some games without requiring strict mode (id tech 5)
- Remove the broken strict mode behavior of depth range using GL
- Improve error handling, recovery and display when running vulkan (nvidia fullscreen & window resize woes)

### CODE REVIEW

**Comment by tkashkin** [comment]
@kd-11 hang seems to be fixed for both toggling fullscreen and manual resizing

**Comment by Psycho-A** [comment]
> This fixes some missing graphics in some games without requiring strict mode (id tech 5)

Still doesn't work in Silent Hill Downpour (Unreal Engine 3).
Image glitches and stucking on some camera angles, and missing/broken texts (game uses scaleform GFX for fonts rendering).

http://i4.imageban.ru/out/2017/10/10/ed1141560a73da4cb11ebec5ebb0e578.png
http://i1.imageban.ru/out/2017/10/10/fca7aa1877371a23aafded7f94461dfe.png
http://i5.imageban.ru/out/2017/10/10/97848caf168517a9749c572bbadabcd8.png

**Comment by slashiee** [comment]
LittleBigPlanet Karting text is no longer broken with strict rendering off, nice!

**Comment by kd-11** [comment]
@Psycho-A That is expected. Some things require more extensive measures to correct and strict mode will always be needed for some situations. Strict mode is not a hack or workaround, its the correct way to do rsx emulation, its just slow to do so.

**Comment by toccata10** [comment]
It removes the necessity for "strict mode" in King of fighters XIII[NPUB30837]. Nice (specially with upscaling) !

**Comment by Kravickas** [comment]
I am crashing when toogling fullscreen in Spyro, 980ti at 100% load.

**Comment by Asinin3** [comment]
While this PR fixed one issue where RPCS3 would always freeze when entering/exiting full-screen, I did have a segfault with this in the log after exiting full-screen (happened after a few hours.)

``·E 2:02:17.047421 {rsx::thread} RSX: Vulkan API call has failed with an error but will continue: Present surface is out of date (VK_ERROR_OUT_OF_DATE_KHR)
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp:1593)
·E 2:02:29.558077 {rsx::thread} RSX: Vulkan API call has failed with an error but will continue: Present surface is out of date (VK_ERROR_OUT_OF_DATE_KHR)
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp:1593)``

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1373163/RPCS3.log.gz) (logfix)

**Comment by kd-11** [comment]
Its something related to nvidia driver being wierd. I'll look into a proper way to deal with it. It shouldnt crash unless you spam resizing though.

**Comment by danilaml** [comment]
Looks like it fixed text/font rendering in most games in non-strict mode! Great!

**Comment by Psycho-A** [comment]
I can confirm that text issues gone in Silent Hill Downpour too. But still there are image glitching on some camera angles that not repeated if Strict mode On. How about natively implementing some specifications of Strict mode that doesn't harm resolution scaling? It doesn't affect performance at all anyway.

**Pull request merged**
