### PR TITLE
Final Fixes

### PR DESCRIPTION
**Pull request by Nekotekina**
I recommend to select "Load liblv2.sprx only"

### CODE REVIEW

**Comment by OverlordCW** [comment]
RDR Goty [BLES01294] doesn't start with "Load liblv2.sprx only", the game window doesn't even appear.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1270281/RPCS3.log.gz)

**Comment by Zangetsu38** [comment]
@OverlordCW not only rdr, few game not works in lv2 mode, caused byu video playing or other
in AOT exemple
>F {PPU[0x1000032] Thread (HLE Video Decoder) [0x00496b7c]} MEM: Access violation reading location 0xffff8fd4

**Comment by Ag2S2O3** [comment]
I think we can move this to "Playable"(at least "ingame") as now we can start playing this game without any extra bootstrapping.
With the help of the .sky file,we can choose the character(the characters in Swap Force or the later version can not be "Updated" successfully ) and enjoy the game.

**Comment by AniLeo** [comment]
What game? Don't ping 2 and a half year old PRs

**Pull request merged**
