### PR TITLE
PPU LLVM: Some instructions simplified

### LINKED ISSUE #1807: Linux/LLVM: build fails with `GetLastError` was not declared in this scope
This happens with LLVM enabled

```
/build/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp: In member function ‘virtual u8* MemoryManager::allocateCodeSection(uintptr_t, uint, uint, llvm::StringRef)’:
/build/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:764:109: error: ‘GetLastError’ was not declared in this scope
 (GENERAL, "LLVM: Failed to allocate code section '%s', error %u", sec_name.data(), GetLastError());
                                                                                                 ^
/build/rpcs3/rpcs3/../Utilities/Log.h:105:59: note: in definition of macro ‘LOG_FATAL’
 #define LOG_FATAL(ch, fmt, ...)   logs::ch.fatal  (fmt, ##__VA_ARGS__)
                                                           ^
/build/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp: In member function ‘virtual u8* MemoryManager::allocateDataSection(uintptr_t, uint, uint, llvm::StringRef, bool)’:
/build/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:783:109: error: ‘GetLastError’ was not declared in this scope
 (GENERAL, "LLVM: Failed to allocate data section '%s', error %u", sec_name.data(), GetLastError());
                                                                                                 ^
```

replacing the function with an empty string ```""``` fixes the compilation error, but this is just a quick and nasty workaround. maybe there is a missing include?

### PR DESCRIPTION
**Pull request by Nekotekina**
Also fixed #1807

### CODE REVIEW

**Comment by zminhquanz** [comment]
image

{PPU[0x3] Thread (main_thread)} struct vm::access_violation thrown: Access violation reading address 0x8bb1030
bug appear , when i'm new game Project Diva F , have you fix that

**Comment by raven02** [comment]
@zminhquanz , if you have issues report , please post in issues section .(I can see the build no in your screenshot is not related to this commit )

**Comment by zminhquanz** [comment]
sorry , i was deleted this

**Comment by raven02** [comment]
Thanks.

**Pull request merged**
