### PR TITLE
SPU Realms

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by scribam** [comment]
Results are good except for `spu_roundtf (FRDS)`

screenshot from 2018-07-27 20-50-42

**Comment by Xcedf** [comment]
Fixes https://github.com/RPCS3/rpcs3/issues/4937, and it seems also fixes https://github.com/RPCS3/rpcs3/issues/4478 -FS precision issue for llvm only

**Comment by stride21** [comment]
Fixes #4874 with LLVM only, looks almost on par with ASMJIT now too.

**Comment by raveskirza** [comment]
B2S graphics also fixed. however FPS is much lower than ASMJIT now.

**Comment by 13xforever** [comment]
Drakengard 3 no longer hangs on breaking boxes.

**Comment by Kravickas** [comment]
**GTA IV** 
SPU LLVM - fixed bug where character fall under the map
ASMJIT - still falling under the map

**Comment by Xcedf** [comment]
Sure it muchmore stable now, sadly it now as fasf as, or even slower than asmjit

**Comment by Lemiru** [comment]
In soulcalibur IV sound is now broken on LLVM with this PR (on master it works fine)

**Comment by Parthorisian** [comment]
Wow, Dante Inferno **[BLUS30405]** danteinferno01 also has been fixed [video](https://streamable.com/knm7p)

**Comment by slashiee** [comment]
The physics bug on the LBP games that appeared on ASMJIT seems to not appear on SPU LLVM using this PR.

**Comment by vietnam13231** [comment]
Infamous [BCUS98119] properly displays necks, elbows and knees on this PR with LLVM. Preformance is comparable, maybe even a bit better than ASMJIT.

**Comment by legend800** [comment]
@Parthorisian Geez, this PR is just magic. It fixed the Death fight?? Wonder if it fixed that one swinging puzzle near the end that required a crazy workaround to get through.

**Comment by Parthorisian** [comment]
@legend800 if we will get solid 60fps with SPU LLVM ill get rid of character control issue tied to lower framerate. In any case this is huge improvement of SPU LLVM since [pr4816 before merging and after](https://i.imgur.com/gNUbrAe.png) and latest pr4919 (almost, but it doesnt matter) - just **MEM: Access violation reading location 0x7c6a1b98**

**Comment by legend800** [comment]
@Parthorisian I don't understand what you wrote. Can you confirm the Death fight freeze is fixed with this PR?

Some testing results:
Backbreaker series: Appears more stable than SPU JIT now, almost fully playable
Captain America: No more broken characters models
Wipeout HD: washing out screen is fixed.

It really seems like everything just works now with SPU LLVM, which is just fantastic! Congrats!

Regression (potential):
On master, I get perfect audio on Ridge Racer 7 (no crackling/static) with SPU LLVM. On this PR, it sounds as staticy as ever.

**Comment by dampih** [comment]
ni1
Fix ni no kuni weird color with SPU LLVM but performance is worse than ASMJIT

**Comment by Nekotekina** [comment]
Updated: minor performance fix.

**Comment by LuismaSP89** [comment]
This PR fixes #4712 and the Guilty Gear XRD Rev2 mute problem. Awesome!

**Comment by Xcedf** [comment]
Made a few custom builds for myself with some of these accuracy changes are off, for example:
GoW 3 requires FCGT, FCMGT and FNMS to look fine, Uncharted 1 above these three also wants FS, yet Killzone 2 and Motorstorm only want accurate FM, i know it's hacky but also nice speedup

**Comment by vietnam13231** [comment]
On the newest PR build emu throws lots and lots of lines similar to this:
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0xf58c] MFC_WrTagUpdate: $3 is not a good constant
Performance is comparable to ASMJIT right now.

**Comment by legend800** [comment]
Ridge Racer 7 audio is still broken on this PR with the latest commit. 

Just doubled checked today's Master and the audio is perfect there - even with fluctuating FPS, the audio is always smooth. On this PR, it's super staticy constantly like it is with SPU Jit.

**Comment by Nekotekina** [comment]
I think xfloat accuracy will be implemented as option

**Comment by Xcedf** [comment]
An option is great, but different games want diffrent instructions to look fine
i've made few custom builds for different games for myself for maximum speed and accurate enough

**Comment by Lagahan** [comment]
This PR fixes missing graphics on WipeoutHD in SPU LLVM:
Master:
master spu llvm
PR:
pr spu llvm

**Comment by Nekotekina** [comment]
@Xcedf What is your CPU? I don't think adding an option for every instruction is a way to go...

**Comment by Xcedf** [comment]
@Nekotekina 6700k

**Comment by yahfz** [comment]
@Xcedf Can you join the RPCS3 official discord? there's no easy way to contact you other than the comment section in this PR (sorry neko, i'll delete once he replies)

**Comment by Xcedf** [comment]
@yahfz maybe later, i actually do not have much time to do my tests with rpcs3 lately

**Comment by ivicamarkovic** [comment]
This branch fix missing graphics in Tales of Xillia (missing scalps) with SPU lle.

**Comment by woj1993** [comment]
@Nekotekina  Appvoyer hasn't build new comit. Can you force it to do it? It would be helpfull in testing.

**Comment by vietnam13231** [comment]
On latest build I see less crashes while closing games, and a slight performance improvement in comparison to previous build of this PR. (2-3 fps on average in those few of my games that still didn't hit the stable FPS cap).

**Comment by Xcedf** [comment]
There's a little bit of regression for me in  https://github.com/RPCS3/rpcs3/pull/4920/commits/242fa6e2f3cd078f7a205bf13743951312e835a3
the audio may cut off randomly and it also kills furthr game processing

**Comment by Xcedf** [comment]
Yet, new version of this PR fixed some strange issue in GoW 3, in the beginning of the game after climbing mount olympus you will jump from wall, but unable to grab the edge and fall (to death of course), now this fixed and the same issue presented in Hermes chase sequence, now also fixed, startd to play this game through to see if this possible to comlete it

**Comment by Nekotekina** [comment]
@Xcedf Can you set LLVM CPU to ivybridge in config.yml and check whether this bug is fixed or not?

**Comment by Xcedf** [comment]
@Nekotekina not seems to make any difference for me

**Comment by Nekotekina** [comment]
What do you mean? You say it's fixed, I'm asking whether it's still fixed when you set CPU to ivybridge.

**Comment by Xcedf** [comment]
I meant the regression in 242fa6e, and if you're about gow3 it's really wierd, i tested ivybridge mode in Hermes chase sequence and issue happens, and it still may happen on skylake, but it woks properly from 3rd-4th time.

**Comment by vsub** [comment]
Also fixes Atelier Shallie
In master when you go near the cauldron in the ship,a falling animation starts and she stays there in the air until you move,also in some areas there are invisible walls that can be passed by jumping or sometimes her movement seems like she is about to fall.
All that is fixed with this pr

**Comment by legend800** [comment]
Regression: Using SPU LLVM on SPLATTERHOUSE [BLUS30335] triggers the same mem error that plagues the game when using PPU LLVM with SPU JIT. 

F {PPU[0x1000000] Thread (main_thread) [0x00df5054]} MEM: Access violation reading location 0x11e

The only way to avoid this error (making the game stable) is to use either PPU intepreter (slow...) or using SPU LLVM (on mainline). Note: It's still not playable because of constant SPU LLVM building spam - probably this issue: https://github.com/RPCS3/rpcs3/issues/4834
 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2280785/RPCS3.log.gz)

**Comment by LuismaSP89** [comment]
Regression in Guilty Gear XRD rev 2:

15 days ago the mute issue was solved in this PR (As I commented in this thread) but now regressed with this PR merged.

**Comment by legend800** [comment]
@Nekotekina Just as an FYI, the regressions noted above on Ridge Racer 7 (stuttering audio) and Splatterhouse (SPU LLVM stability) are not fixed with Accurate xfloat set to true or false. 

2018-08-12 08_13_11-window

**Comment by slashiee** [comment]
It seems like on master (since this PR was merged) with xfloat accuracy enabled (or else it crashes when going in-game), the physics in LBP can be worse than ASMJIT.

ASMJIT:


LLVM:


I'll probably make an issue on this later on in the month.

**Pull request merged**
