### PR TITLE
[WIP] Reservations rewritten

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by JohnGodgames** [comment]
Tekken 6 randomly hangs with this PR.

[LOG](https://mega.nz/#!SVVGCbwA!64LsT5aRC0X1ddDONEBEx0dTrV_kHh_vDD9wwdBMiy4)

**Comment by Zangetsu38** [comment]
@JohnGodgames several game have also this, but i have big speed up with this in several game, just waiting finished, actually just WIP ^^

**Comment by JohnGodgames** [comment]
Yeah I saw also speed-up, but I'm mentioning this before merging...

**Comment by Xcedf** [comment]
Made some tests with this and it's awesome PR
makes some games like Catherine or Soul Calibur IV run significantly faster, also makes Juiced 2 go menu with ingame graphics at fullspeed 30 fps, but there's some regressions:
i've got fullspeed at https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.1-3900
the later versions became slower and on the latest one tested games slow as before and Soul Calibur freezes at intros

**Comment by raven02** [comment]
Sorry , i wrongly pressed the button .

**Comment by raven02** [comment]
Got unknown formatting when tested with 1942 Striker in LLVM mode.

```
F {PPU[0x1000004] Thread (crTaskQueue) [0x00591404]} class std::runtime_error thrown: Unknown formatting: '%-.15s%s" (0x%llx), priority %ld
                   "%-.15s%s" (0x%llx), priority %ld
'
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\sys_libc_.cpp:144)
```

**Comment by AniLeo** [comment]
It's also incomplete, freezing on a few games. I remember seeing that one before though

**Comment by Zangetsu38** [comment]
@raven02 Yes, i have already signaled this error ^^, and yes, freezed few game

**Comment by Nekotekina** [comment]
Updated PR. Slightly better, but don't expect a miracle.

**Comment by raven02** [comment]
1942 striker LLVM issue fixed and DBZ burst limit is no more hang up in-game.

**Comment by danilaml** [comment]
I get about 5-6 fps boost in Katamari Forever with this (tutorial stage). From about 16-17 to 23-25. Event o 30 (fps cap) if I look at walls! Great! Especially since with LLVM recompiler it crashes instantly at the start. And Catherine is almost fullspeed too. And +10-15 fps in After Burner Climax.

**Comment by Xcedf** [comment]
Not as fast as some older versions, but still faster in some games, and no longer freezes

**Comment by Xcedf** [comment]
Not as fast as some older versions, but still faster in some games, and no longer freezes.
Thanks

**Comment by RainKikyou** [comment]
Sorry I do not know why, can not work and only get a black screen, try master build get the same result

**Comment by TechnosMarks** [comment]
has been 3 years without updates, can someone confirm the actual status of this game, i rlly want to play it

**Pull request merged**
