### PR TITLE
Fix package installation

### LINKED ISSUE #13327: [Regression] Raystorm HD [NPJB00034] - Crash during installation
### Quick summary

Emulator crashes during installation.

### Details

When trying to install the game's .pkg, the emulator crashes right at the beginning.

Last build where the game installed fine was rpcs3-v0.0.25-14511.

NOTE: v0.0.25-14516 gives some error stating that an antivirus might be blocking installation. The recent builds however straight up crash.

### Build with regression

rpcs3-v0.0.25-14516-3250c16c_win64

### Attach two log files

[RPCS3-0.0.25-14516.log.gz](https://github.com/RPCS3/rpcs3/files/10540906/RPCS3-0.0.25-14516.log.gz)
[RPCS3-0.0.25-14511.log.gz](https://github.com/RPCS3/rpcs3/files/10540907/RPCS3-0.0.25-14511.log.gz)
[RPCS3-0.0.26-14637.log](https://github.com/RPCS3/rpcs3/files/10549695/RPCS3-0.0.26-14637.log)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
- Improves logging during package installations
- Fix package installation exit condition after error occured
- Don't use u8path for filesystem path

TODO: check utf8 path

The issue is the u8path resolve of 
image
which returns an empty std::filesystem::path which in turn is an invalid argument for std::filesystem::weakly_canonical.
Maybe it should be escaped differently or ignored or whatever the ps3 may do.

image

Furthermore, the game tries to install two files with identical name but different cases without the overwrite flag (see issue #13328)

fixes #13327

### CODE REVIEW

**Comment by MSuih** [comment]
Tested this by installing a pkg to directory which has Üñıcödë in the path.

Master: Crashes entire emulator when trying to install the file.
This PR: PKG installs fine.

There seems to be debug information printed on error level that should be cleaned up:
```
E PKG: Entry 0x80000101: USRDIR/EBOOT.BIN (pad=0x0)
E PKG: Entry 0x80000101: USRDIR/RDR2.self (pad=0x0)
E PKG: Entry 0x80000101: USRDIR/EBOOT.BIN (pad=0x0)
E PKG: Entry 0x80000101: USRDIR/RDR2.self (pad=0x0)
```

**Comment by Megamouse** [comment]
Changed it to be a bit more descriptive. also changed log level to TODO:

U PKG TODO: Entry with unknown type or padding: type=0x80000101, pad=0x0, name='USRDIR/EBOOT.BIN'
! PKG: Entry: type=0x80000003, name='USRDIR/boot.ini'
...

**Comment by Rex000** [comment]
This isn't merged yet?

**Comment by 2banditos** [comment]
> Tested this by installing a pkg to directory which has Üñıcödë in the path.
> 
> Master: Crashes entire emulator when trying to install the file. This PR: PKG installs fine.
> 
> There seems to be debug information printed on error level that should be cleaned up:
> 
> ```
> E PKG: Entry 0x80000101: USRDIR/EBOOT.BIN (pad=0x0)
> E PKG: Entry 0x80000101: USRDIR/RDR2.self (pad=0x0)
> E PKG: Entry 0x80000101: USRDIR/EBOOT.BIN (pad=0x0)
> E PKG: Entry 0x80000101: USRDIR/RDR2.self (pad=0x0)
> ```

I have the same error trying to install the patch in Fight Night Champion! Any solution ?
Entry 0x80000101: USRDIR/EBOOT.BIN (pad=0x0)

**Comment by 2banditos** [comment]
> 

@Megamouse Could you help us installing the Fight Night Champion patch?

Hier ist der Link zu unserer Discord Gruppe:
https://discord.gg/RjZz7R34
Wäre spitze wenn du uns dabei unterstützen könntest!

LG 2banditos

**Pull request merged**
