### PR TITLE
Fix little problem in Gui and Update Submodule.

### PR DESCRIPTION
**Pull request by Zangetsu38**
Fixed problem for the duplicate version on the mainframe and Log.
Before
capture d ecran 2015-09-15 01 45 34
After 
capture d ecran 2015-09-15 01 48 52

And Update two submodule, ffmpeg  for VS2015 with this https://github.com/hrydgard/ppsspp-ffmpeg/commit/ebb6ef2356451ee49971735bdfd98a670e2499a9 and wxWidgets with last commit.

.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@danilaml The build "appveyor" is not important, it just allows you to compile verified that works well, and this build has a problem, it is no icon.
Compiling rpcs3 is thought to be made on Windows via Visual Studio, so clearly there is a problem if a compilation via VS gives this result.
This issue was not before, this commit caussed issue https://github.com/RPCS3/rpcs3/commit/cbe83ad8dd052d00c415d489fcf4a95466690bea

**Comment by Nekotekina** [comment]
Double version doesn't hurt as well, it's "not important". No, let's find complete solution instead.

**Comment by Zangetsu38** [comment]
@Nekotekina I have not said that it was important, just that it was not normal.
I'd also found a solution better than that: /

**Comment by Aaahh** [comment]
This actually looks perfect, don't see the problem.

**Comment by Bigpet** [comment]
alright, I'll merge the main changes in #1230 (this protected branch thing is a little silly but whatever). You can discuss the title thing among yourselves. I don't care about bikeshedding.

**Comment by Zangetsu38** [comment]
@Bigpet ok thx ^^

**Pull request closed without merging**
