### PR TITLE
Qt/windows: use Qt's high dpi scaling

### PR DESCRIPTION
**Pull request by Megamouse**
This should work as before now, even on window's high dpi settings.
The main reason for this PR was to use Qt's frontend highdpi stuff instead of using SetProcessDPIAware.
Also fixes a crash on Vulkan when resizing the window to a small height (by setting a min height on Qt side XD).

~~There is a bug still present in the gs-frame that causes a swapchain error. The max is 1 less than the calculated size on eg. pixelratios of 2~~

~~E {rsx::thread} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 993, 604, Requested = 994, 604~~

### CODE REVIEW

**Comment by Megamouse** [comment]
This is NOT ready

**Comment by Megamouse** [comment]
Removed the backend hack.

I changed the code so that APPLE uses AA_EnableHighDpiScaling and therefore devicePixelRatio as well.
I have no idea if this works in any way for MacOs.

The rounding error (width/height mismatch) still persists.

**Comment by MSuih** [comment]
The latest versions seems to fix an issue I've been having for a month where fullscreen resolution is always downsampled to 720p, even though I have windows set to 1080p and resolution scaling at 4k. I'm not 100% confident on this though as the issue seems to come and go with different builds.

**Comment by MSuih** [comment]
Disregard my previous post I guess, I compiled my own version and it's not working but the one I downloaded from appveyor is.

**Comment by Megamouse** [comment]
you are probably on a different Qt version or used different dlls

**Pull request merged**
