### PR TITLE
Update ASMJIT (new upstream API)

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Nekotekina** [comment]
Uhh what's going on 🤮

**Comment by Nekotekina** [comment]
image

**Comment by GamerZak220** [comment]
hello Nekotekina i'm so like your emulator please say for me how long make performance updates like uncharted 2-3 or the last of us

**Comment by GamerZak220** [comment]
привет Nekotekina, я так похож на ваш эмулятор, пожалуйста, скажите мне, как долго делать обновления производительности, такие как uncharted 2-3 или The last of us

**Comment by GamerZak220** [comment]
привет Nekotekina, мне так  нравится ваш эмулятор, пожалуйста, скажите мне, как долго делать обновления производительности, такие как uncharted 2-3 или последний из нас

**Comment by GamerZak220** [comment]
hello Nekotekina, I like your emulator so much, please tell me how long does it take for performance updates like uncharted 2-3 or the last of us

**Comment by GamerZak220** [comment]
Ты есть иван да или Nekotekina

**Comment by ZeeWanderer** [comment]
@GamerZak220 This is not a place for unrelated discussion. As far as i know the development policy is that they make an accurate ps3 emulator as a whole, not an accurate emulation of a specific game(s) so they don't do game targeted perf hacks. If you meant to ask how long it took to make games like uncharted playable then look in compatibility database. The date in there is date of the status change, so you just have to subtract it from the date of development start.

Your sentence makes little sense in both English and Russian from a semantic standpoint.

**Pull request merged**
