### PR TITLE
SPUThread.cpp (update stop_and_signal)

### PR DESCRIPTION
**Pull request by ikki84**
Shovel Knight: 0x003, 0x004, 0x008, 0x00c, 0x206, 0x207
Disney's Pixar UP Demo: 0x178

### CODE REVIEW

**Comment by ikki84** [comment]
Q: Where is the log?
A: check. https://github.com/ikki84/rpcs3/blob/862def779d082a23347e63fa2086c1f615d0af0d/rpcs3/Emu/Cell/SPUThread.cpp#L1044

Q: But it´s a "hack", need a proper log...
A: Check cases 0x000 and 0x001.

@Nekotekina  If it´s still needs a log in each of the cases, tell me and I will add it.
As the default case in the my previous pull request was not allowed, I listed the cases i´ve found one by one,
At least, if it´s needs another changes or it´s still weird, tell me.

**Comment by Nekotekina** [comment]
Logs don't have necessary information. There is a debugger for this purpose. Only 0x000 is special because it's zero opcode.

**Comment by Nekotekina** [comment]
I'll check shovel knight.

**Comment by Nekotekina** [comment]
That is really strange. May be a bug in some SPU instruction.

**Comment by ikki84** [comment]
@Nekotekina 
Maybe.
I don´t know whether they really exists or they are just called wrong.
Anyway I tried to save sometime until you find out what´s happening ,listing the differents cases one by one in the code.

**Comment by JohnGodgames** [comment]
```
F {SPU[0x2000005] Thread (FMOD)} class std::runtime_error thrown: Unknown STOP code: 0x98 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1322)
```

While merged this PR and run Way of the samurai 4 (Main menu)

[LOG](https://mega.nz/#!2QsnELoL!MPAwVBkWsMmJi0P106s18UggF-hJajClt6KhLgWnTgA)

**Comment by andre4688** [comment]
Error has appeared some games
E LDR: This application requires a valid RAP file for decryption!
E LDR: SELF: Can't find RAP file for NPDRM decryption!
E LDR: SELF: Failed to load SELF file metadata!
F LDR: class std::logic_error thrown: fs::file is null

crazy taxi 
hosue of dead 3 
gti club rally cote

 Nekotekina version the same

**Comment by AniLeo** [comment]
@andre4688 unrelated to this PR.

**Comment by ikki84** [comment]
@Nekotekina tested again with the latest master build. not triggering any of these cases, I think we can close it and not merge.

**Pull request closed without merging**
