### PR TITLE
Qt: improve VFS dialog a bit + misc commits

### PR DESCRIPTION
**Pull request by Megamouse**
- use normal selection instead of doubleclick
- move SaveSettings out of the tabs to reduce file access
- translate EmptyPath and title as well
- some other minor refactors to reduce lines of code

### CODE REVIEW

**Comment by flash-fire** [comment]
surprised you are touching this.  I wrote this entirely in one coding session ha

**Comment by Megamouse** [comment]
~~that's why i'm touching it~~

**Comment by Nekotekina** [comment]
Apparently, nothing good comes from replacing \ with /.
1) On Linux, \ is legal characer for filenames.
2) On Windows, network locations start from \\ and it can't be started with //. And to add more complexity to it, some further parts of the path should remain \.
3) ...

We currently do this only in a single place trying to get RPCS3 executable path. The possible damage is much less than from deploying this algorithm all around.

**Comment by Megamouse** [comment]
alright then. it isn't that important anyway.

**Pull request merged**
