### PR TITLE
Misc. Linux improvements [Linux testers wanted]

### LINKED ISSUE #4100: Linux : AppImage hangs before the UI loads
edit : Oops, wrong button.

When trying to load the latest AppImage I can see the process running in system monitor but nothing is displayed. I have been using the AppImages since they were first introduced and have not had any problems till now.

Is there any way of getting older appimages so I can do a comparison. My version checking script that runs every time I launch <stupidly> doesn't backup the older version.

### PR DESCRIPTION
**Pull request by hcorion**
Fixes #4100 

Here is an AppImage to test: https://transfer.sh/jOALk/2973644-349_linux64
I only need testing with the AppImage, only making sure the GUI shows up, preferably with different distros.

### CODE REVIEW

**Comment by hcorion** [comment]
Thanks to @yzwduck and @7oxicshadow I couldn't of done this without them.

**Comment by yzwduck** [comment]
The AppImage works with my Arch distro, it loads Arch's libfreetype.so.6 and Arch's libharfbuzz.so.0

**Comment by greentop** [comment]
**OS:** Ubuntu 16.04 
**AppImage:** 2973644-349_linux64
-RPCS3 launches, loads game (ToCS2), no errors observed.

**Comment by zekesonxx** [comment]
Tested to launch fine on an updated Arch and an updated Solus.

**Comment by 7oxicshadow** [comment]
Confirmed working for me. Fedora 27 (Fully updated).

Just as an aside, I am not sure if this solution is more of a work around. I am assuming in an ideal world that an AppImage is supposed to be self contained and as such should have no dependencies on the host system?

The fact that removing the libfreetype file means that it falls back to using the host provided version suggests that there are other libraries in the AppImage that are falling back to the host versions as well (resulting in the mismatch).

I am not sure how to prove it, I think it might require some input from the AppImage developers themselves but I think there is a dependency on a QT library that is not being bundled with the image.

**Comment by Wonuku** [comment]
OS: GNU/Debian 9.3
Other than segfaulting at an arbitrary location and printing this out in the terminal the UI loaded and the game ran well
`QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
Aborted`
This seems to happen randomly in stable as well I don't know why it is probably specific to my host

Also the loading screen seems bugged see the attachment

**Pull request merged**
