### PR TITLE
Make it build on macOS with Clang

### PR DESCRIPTION
**Pull request by rawrasaur**
This makes RPCS3 build on macOS with Clang again.

screen shot 2017-08-07 at 23 47 34

### CODE REVIEW

**Comment by rawrasaur** [comment]
The reason why it doesn't build is because it depends on a new commit in hidapi.

**Comment by hcorion** [comment]
I'm 90% sure changing std::uintptr_t to u64 is not needed.

**Comment by rawrasaur** [comment]
Unfortunately on Mac, `std::uintptr_t` is `unsigned long` and `u64` is `unsigned long long` (via `std::uint64_t)`, so implicitly converting between them like is done in JIT is impossible. I chose to replace the `uintptr_t` type with `u64` because that was the least code change.

On 64-bit Linux both are defined as `unsigned long int` so you can freely cast between them.

**Comment by AniLeo** [comment]
Are the instructions for building in MacOS accurate? I think they're outdated

**Comment by hcorion** [comment]
MacOS instructions are fine, unless @rawrasaur found some things that need installing via `brew`.

**Comment by rawrasaur** [comment]
I already had Qt and CMake via brew, so the instructions worked fine. I'll add those to the README though since they are obviously required.

**Comment by christ776** [comment]
So.. RPCS3 can be run under macOS ? Or just compiles but it's unable to run any game because of the OpenGL 4.1 limitations?

**Comment by kd-11** [comment]
Isnt uintptr_t supposed to guarantee that it can fit a pointer? There are alot more uses of uintptr for this purpose everywhere.
Also, rpcs3 needs extensions and features that are part of gl 4.3 and apple strips the drivers of this functionality for no good reason. Code glue can be used to enable mac to run but I personally dont think it's worth the effort

**Comment by kd-11** [comment]
Just to clarify, were waiting for vulkan to metal wrappers for mac

**Comment by rawrasaur** [comment]
@christ776 That is correct, with the nil renderer and interpreter I got some homebrew to run but you can't actually do anything.

@kd-11: `uintptr_t` fits a pointer just fine, it's just that C++ thinks that `unsigned long long` and `unsigned long` are different types, so when you have one in the prototype and another one in the implementation, the compiler whines.

**Comment by kd-11** [comment]
So long on macos is 64 bit? Thats messed up since they now use x86-64.

**Comment by rawrasaur** [comment]
@kd-11: Yeah, both macOS and Linux have 64-bit longs (and pretty much every other system) in 64-bit mode. Windows is the odd one out, with 32-bit longs.

**Pull request merged**
