### PR TITLE
GUI: add some visual studio filters

### PR DESCRIPTION
**Pull request by Megamouse**
Added some filters because we were scrolling like a maniac

Edit: updated

image

### CODE REVIEW

**Comment by flash-fire** [comment]
Just going to comment that if mega didn't stop me, I would've done this months ago lol

**Comment by Megamouse** [comment]
Plot twist, I wanted to get the commit to make you feel betrayed xD

**Comment by Nekotekina** [comment]
Now we a going to click like a maniac?

**Comment by Megamouse** [comment]
Exactly

**Pull request merged**
