### PR TITLE
Regressions

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by isJuhn** [comment]
Can confirm Asmjit segfault from PIC is fixed, same result as llvm now. Some games are still broke on safe asmjit/llvm.

**Comment by uaqlover** [comment]
PAIN [BCES00548] asmjit/llvm broke from PIC it close the Emulator itself

**Comment by hch12907** [comment]
@uaqlover You need to upload the logs.

**Comment by uaqlover** [comment]
@hch12907 sure here the log file 
[RPCS3 pain.zip](https://github.com/RPCS3/rpcs3/files/3181041/RPCS3.pain.zip)

**Comment by uaqlover** [comment]
PAIN [BCES00548] still intro with last commit

FPS_ 39 53 _ Vulkan _ 0 0 6-9fc1996d-Nekotekina_master _ PAIN  BCES00548  15_05_2019 10_39_58 AM

log file

[RPCS3 Regression.log.gz](https://github.com/RPCS3/rpcs3/files/3183815/RPCS3.Regression.log.gz)


0.0.6-8096

FPS_ 30 00 _ Vulkan _ 0 0 6-8096 _ PAIN  BCES00548  15_05_2019 10_41_20 AM

FPS_ 30 00 _ Vulkan _ 0 0 6-8096 _ PAIN  BCES00548  15_05_2019 10_41_23 AM

 log file

[RPCS3 0.0.6-8096.log.gz](https://github.com/RPCS3/rpcs3/files/3183802/RPCS3.0.0.6-8096.log.gz)

**Comment by SpeddieSwagetti** [comment]
Ratchet & Clank: A Crack in Time[BCES00511] boots to black screen on SPU Decoders; LLVM(Recompiler) and crashes on ASMJIT. SPU Block Size is Safe
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3184435/RPCS3.log.gz)

**Comment by isJuhn** [comment]
Ratchet & Clank fixed on asmjit/llvm safe mode with latest commits. Great job!

**Comment by uaqlover** [comment]
PAIN [BCES00548] fixed with latest commits

FPS_ 30 07 _ Vulkan _ 0 0 6-d6930e85-Nekotekina_master _ PAIN  BCES00548  15_05_2019 5_03_59 PM

**Pull request merged**
