### PR TITLE
gl/vk: Blit engine improvements [Part 1]

### PR DESCRIPTION
**Pull request by kd-11**
- Properly perform surface blits to the back/front buffers from memory. Should fix missing/flickering output in some cases
- Refactors alot of shareable code from GLRenderTargets to the common surface store for interoparability with other backends.
- Initial implementation of GPU blitting when using vulkan. This version is incomplete but functional.

This PR includes part of a much larger set of changes that will be merged into master over the next week or so. I'm choosing to split this into parts so that tracking regressions is easier and makes the process of integrating the fbo_fixes work into master.

### CODE REVIEW

**Comment by Illynir** [comment]
Freeze and crash on loading screen with Nier and Nier replicant on that PR with write color buffer ON. On master it's good. The game need Write buffer color activated for good graphics then...

Master: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1303721/RPCS3.zip)

PR:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1303723/RPCS3.zip)

**Comment by toccata10** [comment]
Compiling error on archlinux:
rpcs3/rpcs3/Emu/RSX/Common/surface_store.h:557:3: error: « surface_subresource » doesn't name a type.

**Comment by Illynir** [comment]
Black screen ingame on Kingdom Heart 1 (On compilation of Kingdom Hearts 1.5 final mix). Sound works normally but image is black and freeze. Initial menu works however.

image

On master it's good.

PR: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1303769/RPCS3.zip)

**Comment by kd-11** [comment]
When using vulkan, disable GPU texture scaling. Its unfinished in this PR.

**Comment by Illynir** [comment]
Without GPU scaling, Nier works as on Master but KH1 has always black screen. :)

**Comment by kd-11** [comment]
I think KH is fixed in later patches. Alot of hacks needed to be removed to improve accuracy so there will be some regressions.

**Comment by Asinin3** [comment]
Correct me if I'm wrong but this PR fixes the transparency issue with persona 5 on the status menu right? I'm aware that it fixed it for other people in your fork. However, for me the issue still remains.
blitengine_2017-09-15_04-40-40
GTX 1080ti + latest drivers, not using write color buffers

**Comment by MarioSonic2987** [comment]
@kd-11 
image
zxvzxv

Fixes black screen regression in Worms 2: Armageddon, Worms Crazy Golf and Worms Revolution with GPU scaling ON. With option disabled, still black screen. In WR, it has a weird shading.

**Comment by raveskirza** [comment]
Soul calibur II HD online is now full screen in Open GL. without Write color buffers and strict rendering mode. The game is black screen on Vulkan rendered however and none of the options work.
Previously it was displaying in half screen in Vulkun and Open GL using write color buffers and strict rendering mode as reported in #2464

**Comment by Ariq139** [comment]
p4au
P4AU, black screen with intro sound

**Comment by Zardas81** [comment]
@Ariq139 That game needs frame limiter and invalidate cache.

**Comment by kd-11** [comment]
I'm closing this and will just submit everything when its all ready. That will take a while, but nowadays master is expected to always work properly for end users so no beta code.

**Pull request closed without merging**
