### PR TITLE
Fix encoding in vm.cpp

### PR DESCRIPTION
**Pull request by Nekotekina**
Regression after #5178

### CODE REVIEW

**Comment by twophyro** [comment]
> Almost 2020 , and this emulator still not work properly,and we are talking of ps3 ,
> I think how much money u still need to see a decent build? When u can have a ps3 for 25 or free gift?

Rpcs3 is about making something that was thought to be impossible, NOT to replace ps3s.
The fact that any game even boots is insane.

So calm down and remember people make this for fun/passion.

**Comment by alessandro784** [comment]
Then if is for free, why they ask support us on patreon goal 4000? And u dont say me to calm down.the word is free to say , and i say what i think.

**Comment by 13xforever** [comment]
If you don't understand anything, just move along, no one is making you pay for shit, everything is free and supporting the project is optional.

Stop spamming github with unrelated spam before you're banned from project completely.

**Comment by HerrHulaHoop** [comment]
Unrelated but relevant response

neko_for_dummies

**Pull request merged**
