### PR TITLE
Better stub cellGameUpdateCheckStartAsyncEx/FinishAsyncEx, fixes PAIN

### PR DESCRIPTION
**Pull request by hcorion**
image

Thanks to Zangetsu for the tip. This moves PAIN from intro->Ingame. It's not playable imo due to some graphical issues in the vehicles.

### CODE REVIEW

**Comment by Asinin3** [comment]
I think the 3.5 fps is what makes it not playable rather than a minor graphical issue 😆

**Comment by Zangetsu38** [comment]
@Asinin3 depending scenne, look myu video, this game run most time on 30 fps for me ^^, here i have 9

**Comment by scribam** [comment]
The functions `cellGameUpdateCheckStartWithoutDialogAsync` and `cellGameUpdateCheckStartWithoutDialogAsyncEx`, also present in the file you modified, have a similar callback as argument. Have you tried to implement the same kind of behaviour like you did for `cellGameUpdateCheckStartAsyncEx` / `cellGameUpdateCheckFinishAsyncEx`?

**Comment by hcorion** [comment]
Good idea @scribam , I've done that.

**Pull request merged**
