### PR TITLE
rsx: Fixup

### PR DESCRIPTION
**Pull request by kd-11**
Do not query pure DMA sections for their format information.

Fixes https://github.com/RPCS3/rpcs3/issues/7011

### CODE REVIEW

**Comment by kd-11** [comment]
Missing one more commit for OpenGL.

**Comment by kd-11** [comment]
All issues should be resolved now.

**Comment by D87-byte** [comment]
\Emu\RSX\Common\texture_cache.h:2310

**Comment by D87-byte** [comment]
sword art online lost song

**Pull request merged**
