### PR TITLE
GL/Vulkan: return no operation when comparison is never

### PR DESCRIPTION
**Pull request by raven02**
https://github.com/RPCS3/rpcs3/issues/1989

### CODE REVIEW

**Comment by kd-11** [comment]
While the original code was correct strictly speaking, I think we can remove the comparison_func::never case since it makes no sense for alpha kill and alpha test. It is more useful for things like stencil test, where the programmer guarantees that the FAIL path will always be taken, since it usually results in actual render. Issuing a draw call with never pass just makes little sense on such old hardware.

**Comment by raven02** [comment]
Alright .Will update this PR.

**Comment by kd-11** [comment]
Just add a comment explaining why we're not discarding on never. We'll need more tests to determine correct behaviour.

**Comment by raven02** [comment]
Humm if i comment out the never case , it returns shader error as below

```
E {rsx::thread} RSX: Failed to compile shader: 0(69) : error C1048: invalid character 'l' in swizzle "aalpha_ref"
0(69) : error C7011: implicit cast from "vec2" to "bvec2"
0(69) : error C1019: scalar Boolean expression expected

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(69) : error C1048: invalid character 'l' in swizzle "aalpha_ref"
0(69) : error C7011: implicit cast from "vec2" to "bvec2"
0(69) : error C1019: scalar Boolean expression expected
(0) : error C2003: incompatible options for link
```

**Comment by kd-11** [comment]
you still have to handle the never case, just return an empty string {}. Also, i'd like to take a look at that broken shader.

**Comment by raven02** [comment]
This is the shaderlog [shaderlog.zip](https://github.com/RPCS3/rpcs3/files/493033/shaderlog.zip)

**Comment by kd-11** [comment]
Yes. I see the problem - there is no operation returned when comparison is never. That is why I suggested just 
```if (never) return {}```
or
```if (never) return ""```
Either will prevent the last part from being executed since there is no logical operation for never/always comparison

**Comment by raven02** [comment]
Thanks .I'll then merge it and add the comment for all backends in next PR.

**Pull request merged**
