### PR TITLE
Update Submodule

### PR DESCRIPTION
**Pull request by Zangetsu38**
Update Asmjit and wxWidgets submodule.
And compilation fixed with appveyor, problem solved for asmjit Unable to checkout.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Not yet.

**Comment by Zangetsu38** [comment]
@Nekotekina Why this ? wxWidgets has changed a lot, and you the same asmjit you updated too.

**Comment by SakataGintokiYT** [comment]
Still not yet  ?

**Comment by Nekotekina** [comment]
What?

**Comment by SakataGintokiYT** [comment]
Can update submodules ASMJIT  ?  

last commit 28 Aug 2015
https://github.com/asmjit/asmjit/tree/b0dad1af25fb141bf2b20cf29392194886448832

**Comment by raven02** [comment]
I think Neko is planning to port the SPU recompiler using LLVM .

**Pull request closed without merging**
