### PR TITLE
[ImgBot] Optimize images (Lossless)

### PR DESCRIPTION
**Pull request by ghostslayer989**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **36%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /bin/Icons/ui/save.png | 25.84kb | 8.84kb | 65.77% |
| /rpcs3/Icons/exit_fullscreen.png | 4.20kb | 1.65kb | 60.73% |
| /rpcs3/Icons/fullscreen.png | 3.87kb | 1.52kb | 60.64% |
| /rpcs3/Icons/pause.png | 7.35kb | 3.20kb | 56.43% |
| /bin/Icons/ui/circle.png | 4.21kb | 2.00kb | 52.52% |
| /bin/Icons/ui/triangle.png | 3.70kb | 1.92kb | 47.97% |
| /bin/Icons/ui/dpad_right.png | 3.62kb | 1.91kb | 47.25% |
| /bin/Icons/ui/square.png | 3.31kb | 1.75kb | 47.09% |
| /bin/Icons/ui/new.png | 19.49kb | 10.44kb | 46.46% |
| /bin/Icons/ui/dpad_left.png | 3.56kb | 1.91kb | 46.20% |
| /bin/Icons/ui/cross.png | 3.48kb | 1.87kb | 46.18% |
| /bin/Icons/ui/dpad.png | 3.39kb | 1.83kb | 45.94% |
| /bin/Icons/ui/left_stick.png | 3.80kb | 2.06kb | 45.73% |
| /bin/Icons/ui/dpad_up.png | 3.57kb | 1.95kb | 45.44% |
| /bin/Icons/ui/right_stick.png | 4.08kb | 2.23kb | 45.38% |
| /bin/Icons/ui/dpad_down.png | 3.53kb | 1.95kb | 44.94% |
| /rpcs3/Icons/combo_config_bordered.png | 52.88kb | 30.56kb | 42.22% |
| /rpcs3/Icons/stop.png | 4.30kb | 2.49kb | 42.13% |
| /rpcs3/Icons/controller.png | 77.83kb | 45.39kb | 41.68% |
| /rpcs3/Icons/grid.png | 9.17kb | 5.41kb | 41.06% |
| /bin/Icons/ui/L1.png | 2.76kb | 1.63kb | 40.83% |
| /rpcs3/Icons/controllers_2.png | 14.05kb | 8.42kb | 40.06% |
| /rpcs3/Icons/restart.png | 11.36kb | 6.93kb | 39.01% |
| /bin/Icons/ui/R2.png | 2.51kb | 1.54kb | 38.77% |
| /rpcs3/Icons/open.png | 11.03kb | 6.81kb | 38.28% |
| /bin/Icons/ui/select.png | 1.77kb | 1.11kb | 37.18% |
| /rpcs3/Icons/custom_config_2.png | 8.14kb | 5.14kb | 36.79% |
| /bin/Icons/ui/start.png | 2.54kb | 1.61kb | 36.68% |
| /bin/Icons/ui/R1.png | 2.64kb | 1.73kb | 34.36% |
| /bin/Icons/ui/L2.png | 2.17kb | 1.44kb | 33.72% |
| /rpcs3/Icons/list.png | 4.34kb | 2.92kb | 32.64% |
| /rpcs3/Icons/play.png | 7.84kb | 5.59kb | 28.68% |
| /rpcs3/Icons/insignia.png | 41.17kb | 30.00kb | 27.14% |
| /rpcs3/Icons/refresh.png | 13.40kb | 9.78kb | 27.00% |
| /rpcs3/Icons/configure.png | 8.89kb | 6.64kb | 25.25% |
| /rpcs3/Icons/controllers.png | 12.96kb | 9.81kb | 24.33% |
| /rpcs3/Icons/custom_config.png | 6.57kb | 5.07kb | 22.79% |
| /bin/Icons/ui/fade_top.png | 42.58kb | 35.56kb | 16.50% |
| /bin/Icons/ui/fade_bottom.png | 42.20kb | 35.56kb | 15.74% |
| | | | |
| **Total :** | **484.11kb** | **308.18kb** | **36.34%** |
</details>

---

### CODE REVIEW

**Comment by ghostslayer989** [comment]
Why not save some space? Reduce the time for download (For people with slow speeds) and make it smaller in size.

**Comment by dio-gh** [comment]
Because it's a 172.93 KiB change that ends up in a compressed file.

**Comment by ghostslayer989** [comment]
Which is also extracted for use, which is why I said the smaller file size part.

**Comment by danilaml** [comment]
If you really want to go that wrote, when compressing using [zopfli](https://github.com/google/zopfli) gives the best results (almost twice as good).

**Comment by ghostslayer989** [comment]
Is this just becoming a ad for zopfli?

**Comment by danilaml** [comment]
@ghostslayer989 as opposed to? If you feel it's important to save a few KBs on PNGs, why not save a few more? Otherwise what is the point behind the initial PR?

**Comment by ghostslayer989** [comment]
Just checked the repo and... i don't know how to use it...

**Comment by danilaml** [comment]
@ghostslayer989 just build/download binary ([link for windows exe](https://ci.appveyor.com/project/EwoutH/zopfli/build/job/q7htpf1gp2ii9gx3/artifacts)) and use like `zopflipng -m input.png output.png`. This enough for 99.9% of cases (you can pass `--help` for more info).

**Comment by Megamouse** [comment]
I really don't see the point in this. And no one will do this Everytime an image was changed

**Comment by MSuih** [comment]
One could save far more space by converting the icons to vectors instead of fiddling with compression. But that'd require changes on the code side as well.

**Comment by Hopefullyidontgetbanned** [comment]
> One could save far more space by converting the icons to vectors instead of fiddling with compression. But that'd require changes on the code side as well.

i second this, that would drastically increase icon fidelity on high res screens and save space. also means theming would have more options

**Comment by ghostslayer989** [comment]
Should I make a issue regarding Vectors?

**Comment by rhythmthief** [comment]
> Should I make a issue regarding Vectors?

It's an irrelevant non-issue. That being said, you could always contribute your own time on the conversion...

**Pull request closed without merging**
