### PR TITLE
Fix GCM callback

### LINKED ISSUE #1094: Deadlock in rsx_fp_dynamic_test2.ppu.elf
When running the rsx_fp_dynamic_test2.ppu.elf, it works for a 4 or 5 seconds (it's a dezoom effect), then the emulator halts. It waits at line 106 in Callback.cpp.
The callstack is quite short : 

rpcs3-x64.exe!CallbackManager::Init::__l2::<lambda>() Line 106	C++
rpcs3-x64.exe!thread_t::start::__l2::<lambda>() Line 1405	C++

### PR DESCRIPTION
**Pull request by raven02**
Port from rsx branch and this fixes the rsx_fp_dynamic_test2.ppu.elf . It should now render exactly like on the PS3 does.

Fixes #1094

### CODE REVIEW

**Comment by raven02** [comment]
It seems to be breaking Arkedo 02 with RSXIO memory not mapped

**Comment by vlj** [comment]
How CELL_GCM_METHOD_FLAG_JUMP  is involved with the issue ?
As far as I understand this flag is used to change RSX command buffer read pointer.

**Comment by vlj** [comment]
For what it worth using this patch on fw_stencil_reflect.ppu.elf test generates an "access violation reading 0" error, I think the issue is that we don't use correct offset here.

**Comment by vlj** [comment]
Using the offset computed in the commented out section makes fw_stencil_reflect.ppu.elf works, unfortunatly Arkedo 2 still has the RSXIO memory not mapped error.

**Pull request closed without merging**
