### PR TITLE
rsx: Improve upscaling compatibility

### PR DESCRIPTION
**Pull request by kd-11**
Adds the following fixes for derived sub-surfaces (e.g data cast from 2D to 3D or 2D to cubemap):
- Base the upscaling on the real source and not the "attr" parameter.
- In case of reconstruction, the source is much larger than the subslice in "attr"

These fixes improve upscaling compatibility without requiring large threshold values which can break visuals in some other ways. This is a companion PR to https://github.com/RPCS3/rpcs3/pull/9281. The combined results have upscaled bits that closely match what the layout at default resolution is. This will not fix all upscaling issues, you still cannot (and never will be able to) upscale the individual bytes comprising a floating point value separately.

Fixes https://github.com/RPCS3/rpcs3/issues/9318

### CODE REVIEW

**Comment by Asinin3** [comment]
Ninja Gaiden Razors Edge no longer requires changing resolution scaling threshold to fiix pink graphics caused by resolution scaling.
resolutionn_AUeSzZMEm7

**Comment by Yahfz** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5599416/RPCS3.log)
tlou now crashes in this PR.

**Comment by AphelionWasTaken** [comment]
ModNation Racers is no longer an acid trip and res scaling works properly now
image

Red Faction Armageddon is no longer green however upscaling still does not work
image

The Darkness is still the Greenness without 1024x1024 threshold
image

Can confirm that TLoU crashes before the main menu with the following error:
```
F {RSX [0x008c734]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKQueryPool.cpp:45)
```

**Comment by gamrXerus** [comment]
I can confirm that resolution scaling in Call of Duty Black Ops is now fixed with this pr. Game looks much better now. :)
screen

**Comment by MarioSonic2987** [comment]
BioShock Infinite doesn't turn green with higher resolution scale (200% in this case):
image

**Comment by zombie167** [comment]
LittleBigPlanet Karting with  resolution scale 300% ( regression fixed )


sshot-6

**Comment by zombie167** [comment]
life is strange with resolution scale 300% ( regression fixed ). Thank you very much!

**Comment by kd-11** [comment]
Crashes should be fixed now.

**Comment by Xcedf** [comment]
Fixes long standing upscaling issue in Uncharted 2 (maybe other Naugty Dog's) when increasing threshold led to broken/missing visuals
Before:
Lens flare missing with upscaling even on default 16x16 (required 1x1 before)

After:

As a result now i can use high threshold (160x160) to deal with bad bloom without risking of broken effects
Before (Statue's nose):

After:

**Comment by MsDarkLow** [comment]
(Only documented on the wiki)
Yakuza 0, Kiwi, 3, 4, 5, Dead Souls and Ishin no longer have a broken outlines and heat auras.
Yakuza 5 example of the outline bugging out.
Before:
Y5ResBrok

After:
Y5ResFix

**Comment by kazu-bilup** [comment]
I'm playing Dragon Quest Builders.
The sound stops in the middle.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5615973/RPCS3.log)

**Comment by AniLeo** [comment]
Irrelevant for this PR.

**Comment by kazu-bilup** [comment]
Why?

**Comment by ArchSonix** [comment]
@kazu-bilup This PR is, as the title says, for improving upscale compatibility.
Your problem is clearly unrelated. You need to find an appropriate issue or create a new one if there is none yet, otherwise you will not get any support.

**Comment by avindra** [comment]
My baseline FPS in RDR is higher after this PR. Also I think it _looks_ better, but I can't be sure (I am playing at 2k).

a

**Pull request merged**
