### PR TITLE
Rsx: Fix fragment decompiler

### PR DESCRIPTION
**Pull request by vlj**
This PR moves the parsing function outside of the Decompile() one which a bit more understandable.
It then adds the DIVSQ opcode to SCB which fixes a lot of glitches in SH3 HD.

### CODE REVIEW

**Comment by danilaml** [comment]
There is another thing that @DHrpcs3 almost finished that might be useful to you: https://github.com/RPCS3/rsx_program_decompiler/blob/master/rsx_program_decompiler_lib/rsx/rsx_fragment_program_decompiler.h

**Comment by vlj** [comment]
Is it reliable ? The code looks a lot better than the one currently used but it will take some time to port.

**Comment by danilaml** [comment]
@vlj @DHrpcs3 mentioned somewhere in august/september that he is going to commit final changes in a week and disappeared as usuall.

**Comment by DHrpcs3** [comment]
I'm back! :P 
@vlj I will commit my drafts to rsx_program_decompiler repository soon. Please, doesn't copy code in emucore, let it be in separate project

**Comment by vlj** [comment]
Rebased

**Comment by tambry** [comment]
@vlj Needs rebase

**Comment by vlj** [comment]
Rebased

@DHrpcs3 thanks for the info.
I guess SCT/SCB doesn't change the meaning of the instruction ?

**Comment by tambry** [comment]
@vlj Needs a rebase.

**Comment by DHrpcs3** [comment]
SCT and SCB has different instruction set

**Comment by vlj** [comment]
rebased

**Pull request merged**
