### PR TITLE
Fix hex_to_bytes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by AlbertAdair** [comment]
Nekotekina I did the game test Minecraft PlayStation 3 Edition updated to its latest version and when I create a world I get this error F {PPU [0x1000053] Thread ((4J) Server) [0x003b522c]} MEM: Access violation reading location 0x10 but Then I was trying to create a world of other ways to enter the game and I discovered that when I create a flat world with only a small mother stone if I can enter the game and runs at 60 fps and you can also enter the modes Minigame Plan the waiting rooms of the mini-game battle now, why is this error Nekotekina?

**Comment by AniLeo** [comment]
@AlbertAdair Don't hijack pull requests, this is a dev discussion platform not the forums

**Comment by AlbertAdair** [comment]
Where do I submit errors where I can post these link errors?

**Comment by AniLeo** [comment]
If you're reporting something that's specific only to a pull request then you can do it on that pull request, if it's nothing that's specific to a pull request then use the forums. 

Only use the GitHub Tracker if you know what you're doing, GitHub is a developer platform for tracking issues and submit code changes. The forums are the place designed for the end users that aren't very familiar with coding.

**Pull request merged**
