### PR TITLE
Llvm debug: Fix hang with llvm recompiler and add some debug infrastructure

### LINKED ISSUE #1342: Occasional hang in Sonic CD using llvm ppu recompiler.
Other titles might be affected too. Haven't experienced it before.
If you run Sonic CD with ppu llvm and wait for some time and play a few levels (usually 5-7 minutes is enough) it will hang, but not completely. Sound will still be playing, although very distorted, and emu will be doing, what it seems like, some sysprx mutex stuff. But the picture will stop completely.

### PR DESCRIPTION
**Pull request by vlj**
This PR should fix #1342 . It also adds an "llvm enable" option for several PPU instructions ; if disabled the recompiler will emit call to ppu interpreters functions instead of emitting llvm IR. This way it makes possible to test if a specific function translation is causing trouble.

### CODE REVIEW

**Comment by danilaml** [comment]
So it was not instruction problem but some handling of rpcs3 workflow problem?

**Comment by vlj** [comment]
fixed travis

**Comment by danilaml** [comment]
@vlj doest it fix "lle hangs" or are they still there?

**Comment by vlj** [comment]
yes it fixes them

**Comment by danilaml** [comment]
@vlj should be rebased on top of master (careful, it's been force-pushed)

**Comment by vlj** [comment]
Rebased

**Pull request merged**
