### PR TITLE
Continues the bugfixes journey of #12678

### LINKED ISSUE #12745: [Regression] 14173-14174 Guitar Hero Live/GHTV - Framerate tanks from 144 to 25 when caching files making it unplayable.
### Quick summary

Framerate tanks from 144fps to below 30fps when caching streamed assets

### Details

The game caches streamed files to dev_hdd1\caches\BLES02180_BLES02180\StreamCache so it can reload assets without redownloading them, but since 14174 the framerate seems to completely tank as you can see from the videos below.

Pretty much making it unplayable with streamed assets, 14173 was the last working version before being unplayable.

I also noticed there seems to be a bit of a delay in the RPCS3 display log when it's creating the cached files compared to older versions, like it's taking 1 second per cached file which before was almost instant.

https://user-images.githubusercontent.com/73220666/193454850-ca0ccfca-2768-4fbb-8f19-e26a9d96279a.mp4

https://user-images.githubusercontent.com/73220666/193454852-102d5bf7-cd93-4490-b1ce-e5ca3350ac30.mp4

### Build with regression

0.0.24-14174
PR https://github.com/RPCS3/rpcs3/pull/12678

### Attach two log files

[0.0.24-14174.zip](https://github.com/RPCS3/rpcs3/files/9692538/0.0.24-14174.zip)
[0.0.24-14173.zip](https://github.com/RPCS3/rpcs3/files/9692539/0.0.24-14173.zip)

### Attach capture files for visual issues

_No response_

### System configuration

GPU - Nvidia GeForce RTX 2060 Super
CPU - Intel I7-9700F 3.00GHz
Ram - 16GB

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Attempt to unbreak a thing and improve another.
Fixes #12745.
Continues the bugfixes journy of #12678.

### CODE REVIEW

**Comment by TheGuitarHeroNerd** [comment]
Tested it, sadly no changes to #12745 issue unfortunately.

**Comment by elad335** [comment]
@TheGuitarHeroNerd Retest please.

**Comment by TheGuitarHeroNerd** [comment]
image

Still no change sadly.

**Comment by TheGuitarHeroNerd** [comment]
#12745 The latest commit has fixed the issue, had no lag and was a complete straight line.

Thanks

image

**Pull request merged**
