### PR TITLE
gl: Move gl files to a separate project in VS2015

### PR DESCRIPTION
**Pull request by vlj**
Make separate solution tree a little better and strip almost all of GL deps out of emucore.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
remove 32 bit project

**Comment by vlj** [comment]
Removed x86 build

**Comment by Nekotekina** [comment]
I'd like to remove even stdafx_gui PCH instead of adding new ones.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/177e78a4-041b-4656-8eba-7bcf9dc0a455/same-precompiled-header-for-multiple-projects-in-the-same-solution?forum=msbuild
If I understand it correctly, It should be fine to share the single PCH between projects. At the same time, multiplying them may have some negative effects.

**Comment by paulsapps** [comment]
Sharing PCH'es barely worked in older VS versions, its doomed in new ones http://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/4931119-allow-precompiled-headers-to-be-shared-between-pro

**Comment by Nekotekina** [comment]
This link doesn't make any sense.

**Comment by vlj** [comment]
But sharing pch means that all projects will include d3d12/GL/... headers, or that these headers won't be precompiled at all.
There are some headers extensively using templated struct (glm) that may benefit from being in a pch

**Comment by Nekotekina** [comment]
I'd not worry about glm or dx12 headers much... Currently my PCH header for stdafx.h (Release on my branch) is 46,3 MB. DX12 obj files are about 8-9 MB and take only few seconds to compile. OpenGL files are 3-4 MB. I don't really compare obj with pch, but using different precompiled headers will definitely waste disk space.

Also recently I noticed really big PCH file (emucore.pch was about 500 MB), but I think that was some bug.

**Comment by tambry** [comment]
@vlj Needs to be rebased.

**Comment by vlj** [comment]
Rebased

**Comment by vlj** [comment]
(and removed stdafx_gl.h)

**Comment by Nekotekina** [comment]
Here configs are broken, I did it in a different way.

**Comment by vlj** [comment]
Closing, it's in another PR

**Pull request closed without merging**
