### PR TITLE
[TESTERS NEEDED] rsx: Improve atlas stitching requirements

### PR DESCRIPTION
**Pull request by kd-11**
Modifies how atlas stitching behaves when WCB/WDB is enabled. Basically, with such conditions, data will be forcefully reuploaded from CPU if it is found not to fulfill the criteria. Previously, every time the data source was from a render target and any surface had a positive match, the cache would use the incomplete data which can cause problems.

Fixes https://github.com/RPCS3/rpcs3/issues/5872

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
It fixes partially dark shadows in GTA V, but introduces some glitches in the minimap:
image

**Comment by Xcedf** [comment]
Confirm https://github.com/RPCS3/rpcs3/issues/5872 is fixed here

**Comment by kd-11** [comment]
@MarioSonic2987 Does GTAV need WCB? If it does, enable WDB as well (and all the RCB/RDB options too for good measure)

**Comment by MarioSonic2987** [comment]
@kd-11 Yes. It needs WCB to fix missing lighting outdoors. I had enabled WDB, RCB and RDB before and they allow weather effects to render (raindrops and snowflakes).

Screenshot was taken with WCB+WDB+RCB+RDB.

**Comment by kd-11** [comment]
How does it look like on master then? With the same settings.  I'm talking about the minimap here, may need RDC for comparison.

**Comment by MarioSonic2987** [comment]
The black box in the minimap is fixed, but shadows are dark again:

**Comment by stride21** [comment]
Sorry for the delay with this. Ratchet and Clank Future: A Crack in Time still has the issue with the water looking red. This happens with and without write color buffers. 
ratchet

**Pull request merged**
