### PR TITLE
GT Fixes 2

### PR DESCRIPTION
**Pull request by kd-11**
- Do not map framebuffer memory to blocks which cannot fit the clip dimensions. Clamp the dimensions in such a case to the max that can possibly fit in the space provided. This fixes "Blit request denied" spam in some GT games.
- Implement texture decoding with border texels present. This was a lot more troublesome to figure out since it seems non-linear textures have 4 border texels instead of 1 for Z order to not break the core texel block. Fixes "rainbow" colors in some GT games.

Fixes https://github.com/RPCS3/rpcs3/issues/5874

### CODE REVIEW

**Comment by MsDarkLow** [comment]
Regressions:
In Yakuza 0, the air conditioner in the background has weird green and black colors.
<details>
<summary>Yakuza 0</summary>

Master
Yakuza0Master
PR
Yakuza0PR
</details>

Y0 RDC: https://drive.google.com/open?id=1HDlG4xYPmxjbHafzV351Z6yL4tEJ_sNA

Yakuza Kiwami has overbloom or excessive lighting (idk what you call it)
<details>
<summary>Yakuza Kiwami</summary>

Master
YakuzaKiwamiMaster
PR
YakuzaKiwamiPR
</details>

Y0 Kiwi RDC: https://drive.google.com/open?id=1LD-70uCCYi_WLFNz158nHkYGEBiyx6zg

Yakuza 3 seems to have similar bugs. The smoke renders weirdly and there is some overglow
<details>
<summary>Yakuza 3</summary>

Master
Yakuza3Master
PR
Yakuza3PR
</details>

Y3 RDC: https://drive.google.com/open?id=1YyQVE7Q68wsB61ULcM7YfKdfflWu0Jtq

**Comment by arabek** [comment]
Probably unrelated to the PR, but freezes rendering when going ingame (time trial mode, daytona oval circuit). Able to stop and exit the emu without problems. Replaying erorrs with:
```
F {RSX [0x10186194]} RSX: St13runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file ../rpcs3/Emu/RSX/VK/VKHelpers.h:274)
```

RSX Capture: https://drive.google.com/file/d/1anV-Mi62fGC9Ne88xAyuXvVx4mbgMNfP/view?usp=sharing

**Comment by kd-11** [comment]
Replaying can break because of how it does memory transactions, so its not too relevant. Freezes when going ingame are not introduced by this PR and are therefore outside the scope of this task.

**Comment by kd-11** [comment]
@MsDarkLow Need more:
1. RDC from master for comparison
2. RRC capture to verify results

**Comment by Asinin3** [comment]
@kd-11 RRC from Yakuza 0, same scene. (rename extension to .7z GitHub sucks.)
[BLJM61249_20190710181558_capture.zip](https://github.com/RPCS3/rpcs3/files/3376582/BLJM61249_20190710181558_capture.zip)

RDC Soon™

**Comment by kd-11** [comment]
Fixed yakuza regression.

**Comment by arcadee1977** [comment]
This PR fixes 80% "rainbow" colors of the character in Musou Orochi 2 Ultimate [BLAS50676]
https://github.com/RPCS3/rpcs3/issues/6044

**Comment by Wizzy2018** [comment]
Omg can't wait to test it :D Thx KD-11 <3

**Comment by masaki1988** [comment]
kd hi. can you fix it https://github.com/RPCS3/rpcs3/issues/6088 ?.

**Comment by arcadee1977** [comment]
I'm sorry,I have retest Musou Orochi 2 Ultimate [BLAS50676] with 0.0.6-8358 , the "rainbow" colors of the character hasn't been fixed yet.

未标题-1

**Comment by Wizzy2018** [comment]
Colors fixed but i have this problem now.Flashing black screen
[FPS_ 26.22 _ Vulkan _ 0.0.6-8359 _ Gran Turismo®6 [BCES01893] 2019-07-11 22-29-02.zip](https://github.com/RPCS3/rpcs3/files/3383845/FPS_.26.22._.Vulkan._.0.0.6-8359._.Gran.Turismo.6.BCES01893.2019-07-11.22-29-02.zip)

**Comment by RainbowCookie32** [comment]
Can confirm the issue with GT6, seems to be fixed by enabling CPU Blit.
Saw it before merge, but didn't manage to confirm the issue in time D:

**Comment by Wizzy2018** [comment]
I tried Force CPU Blit but got only a black screen.Still no luck with GT6 it seems RPCS 3 hates my hardware XD

**Comment by Wizzy2018** [comment]
I got some errors.Here are a log file i hope it helps for bug fixing
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3389695/RPCS3.log)

**Pull request merged**
