### PR TITLE
Remap color component depends on RTT or RSX memory

### PR DESCRIPTION
**Pull request by raven02**
Target fix : https://github.com/RPCS3/rpcs3/issues/1715

### CODE REVIEW

**Comment by danilaml** [comment]
Don't forget to rebase.

**Comment by raven02** [comment]
Done .Rebased

**Comment by Nekotekina** [comment]
Needs rebase

**Comment by raven02** [comment]
@Nekotekina Should be okay to merge

**Comment by Nekotekina** [comment]
Displayed out of date for some reason...

**Comment by raven02** [comment]
@Nekotekina . Let's repull another one.

**Pull request closed without merging**
