### PR TITLE
Vulkan: fix G8B8 texture swizzle

### PR DESCRIPTION
**Pull request by raven02**
fix https://github.com/RPCS3/rpcs3/issues/2180

### CODE REVIEW

**Comment by raven02** [comment]
@kd-11 

In GL

		case CELL_GCM_TEXTURE_Y16_X16: 
			return { GL_RED, GL_GREEN, GL_RED, GL_GREEN};

		case CELL_GCM_TEXTURE_Y16_X16_FLOAT: 
			return { GL_GREEN, GL_RED, GL_GREEN, GL_RED };


In Vulkan,

	case CELL_GCM_TEXTURE_Y16_X16:
	case CELL_GCM_TEXTURE_Y16_X16_FLOAT:
		mapping = { VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G }; break;

**Comment by kd-11** [comment]
In theory, the two should be the same. I did not change the ogl one because I dont have a test case to confirm it. As I mentioned before, the ogl backend suffered from alot of confusion due to the way it was trying to upload both render target textures and regular textures as one. RTTs do not deal with swizzling properly since our internal format are technically emulated.

**Comment by raven02** [comment]
Understood . Then left it at this moment.

**Comment by raven02** [comment]
I think we may try this test again

https://github.com/RPCS3/ps3autotests/tree/master/tests/rsx/texture_formats

**Pull request merged**
