### PR TITLE
Fix CMake libpng linking

### PR DESCRIPTION
**Pull request by tambry**
Apparently libpng is linked as a shared library, due it taking priority over static library.
The easiest solution is to only build the static library.
I also turned off the building off libpng tests, so compilation times will be slightly faster.

### CODE REVIEW

**Comment by MyaniPT** [comment]
This fixes the missing libpng16 error. Just tested with the latest appVeyor build.

**Comment by danilaml** [comment]
Can confirm it. @Nekotekina ?

**Comment by danilaml** [comment]
needs rebase.

**Comment by tambry** [comment]
@Nekotekina Though you have approved it, I have added another commit to fix rpcs3-tests compiling. Re-review to make sure everything is ok, if possible.

**Pull request merged**
