### PR TITLE
rsx: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Framebuffer setup improvements
  Improves fast paths in framebuffer setup code and allows resource reuse when using opengl instead of constantly recreating new resources and binding.
- gl: Do not rely on opengl null texture; instead, provide our own black null texture to make reads from non-existent textures return (0, 0, 0, 1)
- Implement fbo flush-always when wcb is enabled. This is for games that read back the currently bound render target. Fixes some missing graphics in some games expecially when using the blit debugger (force_cpu_blit)
- vulkan API compliance fixes
- Synchronize blit engine resources with cell to avoid data loss. A typical scenario would be where an image is rendered on rsx pixel pipeline to render target A which is copied to location B using blit engine. Cell then reads back the pixels at B to do some image processing on SPU and reuploads the data from another location C. Without synchronizing reads and writes, data at B would not exist from cell's pov. Fixes some problems in some games like journey.
- vulkan: Minor memory management fixes. Avoids running out of memory during a draw call.
- fp: Explicitly gather or discard writes to output if none is defined. While the GL spec makes this work correctly, undefined output in spir-v updated the render target with blue pixels.
- texture cache: Fix component ordering on depth surfaces - all components should always read R. Fixes TOCS/TOCS2 blur
- Fix a bug in multidraw implementation and range splitting of disjoint draw calls. Fixes flickering in R&C games
- [WIP] Improved workaround for AMD vulkan driver where u16 index buffers would mistakenly break primitive restart due to fetching of the restart index T(-1), likely due to broken type identification.
- General minor optimizations all round
- Optimize texture readback performance by tracking flushable targets and performing transfers ahead of time.

### CODE REVIEW

**Comment by greentop** [comment]
**Game:** Hyperdimension Neptunia [BLUS30701]
**OS:** Ubuntu 16.04
**Video:** Nvidia 390.25
**Renderer:** Vulkan
**Audio:** PulseAudio
(kd-11/rpcs3 - rsx_volatile)

There is roughly a 10 FPS hit seen with the Vulkan renderer as an result of changes made in 546bb3f. The audio will also stutter when using the PulseAudio audio output while the FPS hit is observed.


8ed7d09d251d1d25a742d0b879adeee837a41024 - FPS drop / Audio stutter
~
f862fe4514ae8566085b0ff81a9777b3e8730748 - FPS drop / Audio stutter


378f8e539f804c0eabe6791e8876019e33833ba3 - FPS drop / Audio stutter
39ef715873ed29668003ad14d595f64224fdc046 - FPS drop / Audio stutter
~
fc0d393547e92e62cdd7649da391b40a25c46539 - FPS drop / No blurred 3d / Audio stutter
f8ac2e5e3b3c8d1a572cb2e547e3f1cc73cbf119 - FPS drop / Has blurred 3d / Audio stutter
546bb3f75612a2a01da4f5936068ba13bebdbd35 - FPS drop / Has blurred 3d / Audio stutter
9cad1eec36072b3e06e05efa84b4ff780177987c - No FPS drop / Has blurred 3d / No audio stutter
9ce45c40c22bd66e27d4b85fe04cc2534a8185a2 - No FPS drop / No audio stutter

rpcs3-v0.0.4-2018-02-06-5b5f2d4-9807_linux64 - No FPS drop / No audio stutter

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1711574/RPCS3.log.gz)

**Comment by GeniusMage** [comment]
Tales of Vesperia eats up almost the entirety of my VRAM, when in OGL, without strict rendering mode. It happens on the main menu and ingame. Doesn't affect other games, afaik.
_Master (8 fps in the main menu, the flat part is due to a Halt! error):_
capture111

_This build (1 fps in the main menu):_
capture1111

(Before the last gl fix, it was also eating RAM.)

**Comment by kd-11** [comment]
Thanks. Will fix before its ready for merge.

**Comment by raven02** [comment]
Just tried with P5 and somehow got hang up entirely when reach this 1st scene.

**Comment by MarioSonic2987** [comment]
Fixes flickering texture Ratchet & Clank Trilogy:

image
image
image

**Comment by jonwd7** [comment]
Not presuming you meant or intend to fix #4086 but if it's helpful in any way I can confirm that the distortion effect is still incorrect with this PR.  I will put my observations about the bug in that issue.   Tl;dr - I believe that there are certain invisible 3D volumes in the scene that are being written to a stencil/mask and the effect is supposed to be masked by it.

**Comment by Zangetsu38** [comment]
@MarioSonic2987 yes, i have see also yesterday ^^

**Comment by MarioSonic2987** [comment]
Fixes missing lens flare in Twilght Town.

**Before**:
image
**After**:
image

**Comment by spyropt** [comment]
God of War III black screen and out of memory error 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1712152/RPCS3.log.gz)

**Comment by Sora3100** [comment]
Tales of Xillia regressed
Threw "Thread (main_thread) [0x00878bc8]} class std::runtime_error thrown: Unregistered PPU function" when entering a boss battle
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1712426/RPCS3.log)
Same goes for Xillia 2
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1712433/RPCS3.log)

**Comment by AniLeo** [comment]
That's a bit impossible. 
Do note that this PR is behind of master, so it could be that you have objects from the latest LLVM update.

In any way, it's surely not related to the changes on this PR specifically.

**Comment by Sora3100** [comment]
I always delete the data folder when testing a new version though

**Comment by Marthgun** [comment]
what do with those ssl libs?  i dropped them into the main folder w/ .exe.  holla atcha boy

**Comment by kd-11** [comment]
@greentop @GeniusMage Please retest. While I was only able to note a 2-4fps difference, I have tried to make the performance same as before; I was not able to observe any memory leaks with vesperia either way, but if it happens, I'll try copying your steps to reproduce. I tried with gpu texture scaling both on and off and strict mode on and off -> nothing happened in menus. The slight performance loss I noticed seems to have disappeared with the last commit; it shouldn't have even been an issue in the first place.

**Comment by kd-11** [comment]
Also, note; This PR is intentionally behind master to avoid conflation of issues especially related to llvm updates and such. If testing builds from this PR, wipe llvm cache first - I'll rebase once its clear that there are no needless performance regressions from this changeset.

**Comment by L1ttl3c0w** [comment]
Journey [NPEA00288] renders graphics again (with LLVM/ASMJIT/Vulkan), but seems like tiles are rotated by 90/180/270 degrees. See attached screenshots.

image
image
image

**Comment by kd-11** [comment]
Its performance related. Attaching a debugger or forcing debug output makes the tiles render correctly

**Comment by spyropt** [comment]
P5 crashs rpcs3 after loading a save
its in the first save of the game it plays the cinematics and then crashs, deleted llvm shaders nothing worked.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1713274/RPCS3.zip)

Edit: it crashs after the cinematics because if i start a new game it crashs after the first cinematic
thats why my other saves were working ok

**Comment by greentop** [comment]
**Game:** Hyperdimension Neptunia [BLUS30701]
**OS:** Ubuntu 16.04
**Video:** Nvidia 390.25
**Renderer:** Vulkan
**Audio:** PulseAudio
(PR #4162 )

As of 1bbee51 in Vulkan, there appears to be a slight improvement in FPS (1bbee51 ~22 FPS average / 8ed7d09 ~20 FPS). The audio stutter is still present.

a7395b5884340dffc521558f8dca7030b16fea5d - FPS drop / Audio stutter
f8d34b66c7e94e72c3546cc36b38ed745a72332b - FPS drop / Audio stutter
1bbee518ada952746d55beebd4410bc534151523 - FPS drop / Audio stutter

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1713484/RPCS3.log.gz)

**Comment by kd-11** [comment]
@greentop The fps drop might be inevitable, not sure why its present. Maybe its only evident on linux; I'll check it later. The drops I was having are already fixed on windows. I'm not sure what neptunia is trying to read back from the cpu, also provide a save file for further inspection. I also have to ask, what was the framerate on your setup before?

**Comment by kd-11** [comment]
Also consider disabling gpu texture scaling option to reduce chances of sync points if performance is too slow now.

**Comment by GeniusMage** [comment]
Okay, did some more testing:
- the reason why it eats so much VRAM is actually because I have it rendered at 5K. However, as by my first comment, the VRAM usage doubled because of this PR.
- new builds didn't solve this issue (if it is an issue)

**Comment by greentop** [comment]
@kd-11 The framerate from before PR was 30 FPS in the cave area. No change in FPS and audio observed in disabling GPU Texture Scaling.

[Hyperdimension Neptunia save.zip](https://github.com/RPCS3/rpcs3/files/1713515/Hyperdimension.Neptunia.save.zip)

**Comment by greentop** [comment]
@kd-11 ToCS 1 & 2 appear to be unaffected, holding at a solid 30 FPS for both under the Vulkan renderer.

**Comment by kd-11** [comment]
Managed to hack the save file to load on BLES, hopefully its easy to work around the performance issues.

**Comment by greentop** [comment]
As of 44d9629e085836058a76432c218b60b23392895a, the FPS in Neptunia went up to roughly to an noticeable average of 25 FPS with the Vulkan renderer. The upper left corner of the game window has some kind of new flickering blurring going on. (Debug Overlay is disabled, but also happens with Debug Overlay enabled.) The audio is still continuing to stutter.

screenshot from 2018-02-10 13-28-10
44d9629e085836058a76432c218b60b23392895a

**Comment by emko** [comment]
Cars 3 - Driven to Win is showing more graphics in the start/menus and ingame

4ed0d2e2bf556a041217afe9d5bf5b8b

2d422138ecd2fa070912a5f6766a23ea

ab009ccdbfc0ecc6d89184e9607e1fd0

e3120a393e04d8fb5beaa161072d0408

**Comment by kd-11** [comment]
@greentop Retest; Cache prediction gets AMD vulkan back up to 30 fps, nvidia sits at around 27. OpenGL is also 30fps locked, but has more audio stutter. I suspect it has to do with uneven frametimes due to the balancing algorithm being not well tuned yet. Audio stutter with vulkan should be at a minimum.

**Comment by greentop** [comment]
As of 785f212, the FPS is roughly between 21 - 23 in Neptunia under the Vulkan renderer, and the audio stuttering is now gone. With the OpenGL renderer, the FPS is roughly between 19 - 21 in Neptunia, and the audio has some minor stuttering.

**Comment by raveskirza** [comment]
Beyond two souls and Soul Calibur V FPS have dropped to 2 FPS in the intros
In Master it is Beyond 2 Souls = 8 FPS and SCV=27 FPS
This PR is spamming the below line for thee 2 games, which could be the probable cause for the drastic slowdown

{rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300CC0

Logs:
[B2S_Master_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1713828/B2S_Master_RPCS3.log.gz)
[SC5_Master_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1713829/SC5_Master_RPCS3.log.gz)
[B2S_PR_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1713830/B2S_PR_RPCS3.log.gz)
[SC5_PR_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1713832/SC5_PR_RPCS3.log.gz)

**Comment by raven02** [comment]
Re-tested with P5 and no longer stuck after cinematic scene .

**Comment by Kravickas** [comment]
**Middle-Earth: Shadow of Mordor** crashing emulator as it want to load 3d graphic in menu with resolution scaling on
obrazek

**Comment by Kravickas** [comment]
am i retarded, or last commit has packet different .exe build in it

**Comment by L1ttl3c0w** [comment]
Sly Cooper: Thieves in Time (BCUS98247) is clogging with messages like this during the intro (not reproducible on master):
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300FB0

Seems to be the same issue @raveskirza reported above with Beyond Two Souls and Soul Calibur V.

Also, Under Defeat HD Collection (BLES01752) crashes during boot (not reproducible on master):
image

Logs:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1714460/RPCS3.zip)

**Comment by shadowbrony33** [comment]
@L1ttl3c0w @Kravickas Clear LLVM cache and try again. Might need to clear Shaders cache too.

**Comment by L1ttl3c0w** [comment]
The crash is fixed, thank you.

**Comment by kd-11** [comment]
@raveskirza Beyond 2 souls is less than 1 fps on master with the right settings so I'm not surprised at the poor performance. For SCV, post a screenshot with debug overlay active after a few seconds of the menus running to let the analyzer attempt to predict flush requests. I'm interested in the flush requests number.
@L1ttl3c0w Do the same for sly cooper. Debug overlay (not debug output) is in debug tab (hidden) or can be enabled from the config file for the game.

**Comment by spyropt** [comment]
SCV always had problems the only build that works at full speed in cinematics and intro is the spu_perf
on win10 it got alot worse since meltdown patch on my 3770k@4.8ghz fps went from 60fps at bandai logo to 7fps


this was tested on a x5675 win7 650ti
menu
intro
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1719348/RPCS3.log.gz)

**Comment by kd-11** [comment]
There's only one readback event. I'm not seeing how that is causing semaphore timeouts and 60 fps to 5 fps. Is opengl also that slow?

**Comment by spyropt** [comment]
opengl is even slower but its more stable and the semaphore_acquire is less frequent
the only difference from master is the semaphore_acquire this game has alot of problems even on master

disregard the 60fps to 5fps that is not related to this pr the drop with this build is just on first logos and cinematic (bandai...) from 25 to about 5fps  but it's up and down logging semaphore acquire

menu on master is about 10fps and this build about 5fps

**Comment by L1ttl3c0w** [comment]
Hey kd-11,

Here is the Sly Cooper screenshot you requested a few messages above.

image

**Comment by kd-11** [comment]
another one with 1 flush and 0 misses. I'm really not seeing the cause of a performance drop here, although readback is expensive. I would expect a 3-4 fps at most on a 30fps game not 20->1fps. I need more test cases.

**Comment by raveskirza** [comment]
In Beyond two souls with this PR with the debug overlay, it is 1-2 FPS
image

With master
image

In Master, my CPU i5-7300HQ is able to maintain the FPS between 7-8 FPS. I think Ryzen CPU's do not work very well with this game as seen in the forums from another user Ashmine who also has Ryzen.

**Comment by kd-11** [comment]
On master you need wcb and likely cpu blit enabled. Code in this PR autodetects this and enables something similar behind the scenes (note the 7 flush requests). Ryzen has no issues with any game, I fixed that. On master with those settings (wcb, cpu blit) it runs at 1fps or at least it used to.

**Comment by raveskirza** [comment]
Even with WCB and CPU bilt turned on in Master, I am getting 7-8 FPS while I use the integrated HD 630. Nvidia seems to crash with API  device lost when WCB is turned on for this game.

With this PR the slowdown in B2S seems to be adversely affected for nVidia GPU(maybe?) or is it that integrated GPU is less affected as it is closer to the CPU, and can do bilt faster?

With nVidia 1050 as GPU (1-2 FPS)
image

With Intel HD 630 (2-6 FPS)
image

**Comment by kd-11** [comment]
Pretty much. Even amd isnt as badly affected by gpu reads. The call to vkcmdcopyimagetobuffer is oddly expensive on nvidia cards. Intel will always have minimum transfer cost since everything is in system ram.

**Comment by kd-11** [comment]
Nvidia slowdown is partially due to support for D24S8 surfaces. Forcing D32S8 and emulating D24S8 with post conversion is actually alot faster which raises questions as to how this format is actually implemented in hardware.

**Comment by greentop** [comment]
With the "Use high precision Z buffer" enabled and as of b6dca09, the FPS in Neptunia with the Vulkan renderer is observed to be between 28 - 30, an increase of around 7 FPS. There is also no audio stuttering observed with that configuration. If using the OpenGL renderer, the option will greatly reduce FPS and produce audio stuttering.

screenshot from 2018-02-15 10-58-47

**Comment by jobs-git** [comment]
On D3 there is no performance hit.

@spyropt The issue on God of War III is already present even before this PR, it was already present on #4002, I just dont know where it regressed, still tracing.

**Comment by Maukyd** [comment]
captura
Earthworm Jim [HD] Still has that weird jim error

**Comment by Asinin3** [comment]
If a game "still" has an issue and it was not caused by this PR then the post belongs in it's own issue. Otherwise it just leads to confusion (what issue is caused by what change) and it's pretty much spam.

**Pull request merged**
