### PR TITLE
gui/themes: YoRHa by Ani

### PR DESCRIPTION
**Pull request by AniLeo**
~~THIS THEME REQUIRES #4227 IN ORDER TO FUNCTION PROPERLY!~~ (Already merged onto master)

I bring you my latest theme, based on YoRHa's UI from [NieR Automata](https://www.niergame.com/). If you don't know the game, I really recommend it. 

image
image

Regardless of knowing NieR or not, please give feedback and/or report bugs. Theme is mostly ready as-is though.

**TODO**: 

- [x] Font scaling
- [x] Style mouse tooltips
- [x] Lighten toolbar hovering color
- [x] Fix Trophy Manager
- [x] Fix CG Disasm
- [x] Unix path for background-image (fixed by #4227)
- [x] QHeaderView not passing transparency on Linux (Ubuntu 17.10 tested)
- [x] Cleanup identation
- [x] Fix Trophy Notification Popup

**Known issue:** Detached QFrames won't work properly as background can't be properly defined (the stylesheet has no effect when window is undocked)

Tested on resolutions up to 1080p. It's made to work with higher resolutions, but I didn't test on them.

### CODE REVIEW

**Comment by matiastulio** [comment]
You see, i almost never comment on anything. but this. THIS I WANT. Bless you and your whole family.

**Comment by sky-zer** [comment]
Forgot QSpinBox buttons:
QSpinBox::up-button {}
QSpinBox::down-button {}

**Comment by AniLeo** [comment]
Left QSpinBox styling there just because. It's not working properly for me, I'm hitting weird bug on Qt.

**Comment by AniLeo** [comment]
Some tests on different resolutions. I changed a few things, still working on it (locally).

1080p
screenshot_220

768p
screenshot_221

720p
screenshot_222

600p
screenshot_223

**Comment by AniLeo** [comment]
Pushed an update. Contains a few fixes and further style enhancements.

image

Settings dialog is looking slick :ok_hand:

**Comment by AniLeo** [comment]
Linux issues fixed, will push soonTM

image

**Comment by sauib786** [comment]
desktop screenshot 2018 02 28 - 19 40 30 28 4k

**Pull request merged**
