### PR TITLE
D3d12: Fixes

### PR DESCRIPTION
**Pull request by vlj**
Another round of fixes here.
They're aimed at Castle of Illusions Starring Mickey Mouse and at After Burner Climax, the latter being another 3d game working in rpcs3. Unfortunatly textures and some geometry are corrupted at the moment...

### CODE REVIEW

**Comment by tambry** [comment]
@vlj Needs rebase

**Comment by vlj** [comment]
rebased

**Comment by tambry** [comment]
@vlj Needs to be rebased again.

**Comment by vlj** [comment]
rebased

**Pull request merged**
