### PR TITLE
PPU LLVM: match interpreter for VEXPTEFP/VLOGEFP

### PR DESCRIPTION
**Pull request by Nekotekina**
Needs manual PPU cache clear.

### CODE REVIEW

**Comment by Xcedf** [comment]
Fixes https://github.com/RPCS3/rpcs3/issues/11553

**Comment by Darkhost1999** [comment]
I went back to the custom.exe created from rolling back https://github.com/RPCS3/rpcs3/commit/df24cff0b19eaaaebe06b6037a97dbe9120e351e after getting that fatal error 3 times from this PR build.
And progressed just fine.
[BCUS98125_INFAMOUS2_1.zip](https://github.com/RPCS3/rpcs3/files/8606632/BCUS98125_INFAMOUS2_1.zip)
If anyone wants the savedata to test go to the main mission. You should fatal error once you start attacking the enemy. Assuming you chose good (blue). Idk about evil (red).
I'm just gonna keep using the custom.exe to play the game as I have yet to encounter an issue.

**Comment by Yahfz** [comment]
This is not a regression from this PR.. This game is known to be unstable and hard to get ingame for a long time.

**Comment by Darkhost1999** [comment]
No problem I wasn't sure of the cause. I'm just informing what fixed my fatal error. And what has also fixes the sound issues is rolling back the commit mentioned previous.
This PR fixes the sound issues just I have yet to encounter an issue using the other fix where this PR has encountered an issue.

**Pull request merged**
