### PR TITLE
Compilation fix

### PR DESCRIPTION
**Pull request by elad335**

### CODE REVIEW

**Comment by Nekotekina** [comment]
Details please?

**Comment by MSuih** [comment]
```
/usr/bin/ld: rpcs3/Emu/librpcs3_emu.a(File.cpp.o): in function `fs::file::file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bs_t<fs::open_mode>)::unix_file::seek(long, fs::seek_mode)':
/home/user/rpcs3/build/../Utilities/File.cpp:1202: undefined reference to `fmt::throw_exception<char, 22ul, fs::seek_mode>::~throw_exception()'
/usr/bin/ld: rpcs3/Emu/librpcs3_emu.a(PPUThread.cpp.o): in function `ppu_cache(unsigned int)':
/home/user/rpcs3/build/../rpcs3/Emu/Cell/PPUThread.cpp:131: undefined reference to `fmt::throw_exception<char, 20ul>::~throw_exception()'
/usr/bin/ld: rpcs3/Emu/librpcs3_emu.a(SPURecompiler.cpp.o): in function `spu_recompiler_base::old_interpreter(spu_thread&, void*, unsigned char*)':
/home/user/rpcs3/build/../rpcs3/Emu/Cell/SPURecompiler.cpp:1193: undefined reference to `fmt::throw_exception<char, 20ul>::~throw_exception()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by Nekotekina** [comment]
i.e. what compiler, under what circumstances.

**Comment by al3xtjames** [comment]
> ```
> /usr/bin/ld: rpcs3/Emu/librpcs3_emu.a(File.cpp.o): in function `fs::file::file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bs_t<fs::open_mode>)::unix_file::seek(long, fs::seek_mode)':
> /home/user/rpcs3/build/../Utilities/File.cpp:1202: undefined reference to `fmt::throw_exception<char, 22ul, fs::seek_mode>::~throw_exception()'
> /usr/bin/ld: rpcs3/Emu/librpcs3_emu.a(PPUThread.cpp.o): in function `ppu_cache(unsigned int)':
> /home/user/rpcs3/build/../rpcs3/Emu/Cell/PPUThread.cpp:131: undefined reference to `fmt::throw_exception<char, 20ul>::~throw_exception()'
> /usr/bin/ld: rpcs3/Emu/librpcs3_emu.a(SPURecompiler.cpp.o): in function `spu_recompiler_base::old_interpreter(spu_thread&, void*, unsigned char*)':
> /home/user/rpcs3/build/../rpcs3/Emu/Cell/SPURecompiler.cpp:1193: undefined reference to `fmt::throw_exception<char, 20ul>::~throw_exception()'
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> ```

To add some context, this happens on Linux and macOS with `-DCMAKE_BUILD_TYPE=Debug`.

**Comment by Nekotekina** [comment]
I suspected that debug may not work with this, but there is no point in making destructor that isn't called valid. At least try a guard for debug mode + non-MSVC with removed [[noreturn]]

**Comment by elad335** [comment]
Its not UB as long as the function doesn't return at runtime, not compilation time.

**Comment by Nekotekina** [comment]
I tested it, too much warning spam. Made some discoveries in process.

**Comment by Nekotekina** [comment]
Also note that non-existing function is a form of guard against incorrect usage (or incorrect codegen). When you make it empty, you aren't sure anymore.

**Comment by elad335** [comment]
Added std::abort, should fix warnings. There's little sense in statically asserting that destructor won't be compiled by making it an empty decleration.

**Comment by Nekotekina** [comment]
I'll merge it but it's suboptimal and adds more code to compile. The trick is to make sure it does not **link** due to simple optimization pass of removing unreachable code, the fact that the destructor should be compiled is doubtless (otherwise it could be marked `= delete;` but it can't). Of course debug builds may have this optimization disabled. This was normal practice in C++03 times to provoke linkage errors on misused copy constructors.

**Pull request merged**
