### PR TITLE
TravisCI: use ccache

### PR DESCRIPTION
**Pull request by Chocobo1**
Build time cut down from 8min to 3min (a single job).

### CODE REVIEW

**Comment by paulsapps** [comment]
How does this work when the whole machine gets reset at each build?

**Comment by Chocobo1** [comment]
From TravisCI doc https://docs.travis-ci.com/user/caching:
>Travis CI fetches the cache for every build, including branches and pull requests.

In short, TravisCI store/upload the ccache's cache files everytime when a build is finished; on the next build, it restore/download the cache files and utilize it.

Due to TravisCI having infrastructure issues now, I cannot point out which line in log does this.

**Comment by danilaml** [comment]
travis build was slower than usual by about 6 mins total it seems.

**Comment by paulsapps** [comment]
I see, but won't $HOME/hombebrew_cache be specific to OSX only, and is typod? lol

**Comment by danilaml** [comment]
also, @Nekotekina disabled OSX travis build a while ago (probably because there was no working renderer for it, thanks to Apple, but I'm not sure).

**Comment by Chocobo1** [comment]
>travis build is slower than usual by about 6 mins total it seems.

The first build is slower because it has to generate the cache.
Compare these 2 build tasks: 
https://travis-ci.org/RPCS3/rpcs3/builds/203137848
https://travis-ci.org/RPCS3/rpcs3/builds/206862701 (subsequent build that has the speed up)

>I see, but won't $HOME/hombebrew_cache be specific to OSX only, and is typod? lol

Yes and no, I see there are code for osx so I added that (to be complete).

**Pull request merged**
