### PR TITLE
implement cell_ugh

### PR DESCRIPTION
**Pull request by Talkashie**
Updates some outdated tooltips to better fit the most recent version of RPCS3.
Replaces some Engrish with English.
Implements full cell_ugh compatibility.

### CODE REVIEW

**Comment by Talkashie** [comment]
kd-11, should I change the GPU texture scaling thing some more? Someone mentioned that it is enabled by default now.

**Comment by Nekotekina** [comment]
liblv2 should really be preferred now.

**Comment by Talkashie** [comment]
Okay, I have updated it.

**Comment by kd-11** [comment]
Leave the gpu scaling option as is. It still affects behaviour and explaining what it actually does would just confuse people.

**Pull request merged**
