### PR TITLE
Write vert/frag program log as .spirv (vulkan) and .glsl (OpenGL)

### PR DESCRIPTION
**Pull request by raven02**
And put it under /dev_hdd01/shader/

### CODE REVIEW

**Comment by Nekotekina** [comment]
What are you trying to achieve? And dev_hdd0 doesn't belong to config dir.

**Comment by raven02** [comment]
yep should simply write to /dev_hdd01/shader , I will take out the config dir

**Comment by danilaml** [comment]
@raven02 why to `dev_hdd` at all? You are trying to implement https://github.com/RPCS3/rpcs3/issues/1631#issuecomment-207745854, right? If so, it could be any other folder. Like `shaders` or something. dev_hdd is for ps3 stuff.

**Comment by raven02** [comment]
I will rework it in another PR

**Pull request closed without merging**
