### PR TITLE
Implement strncasecmp and strrchr

### PR DESCRIPTION
**Pull request by hcorion**
This makes MotorStorm: Apocalypse get a little farther into the loading screen.

I'm pretty sure to get this game to go further somebody will need to hack up a PS Eye/Move system that this game will believe works.

### CODE REVIEW

**Comment by Nekotekina** [comment]
_strnicmp is locale-dependent function, strncasecmp is based on simple ASCII _sys_tolower.

**Comment by hcorion** [comment]
Thanks for pointing that out @Nekotekina my knowledge of windows api's are lacking.
Would you rather me `toLower` the whole string and then just `std::strncmp`? or just use '_strnicmp_l' and set the locale?

**Comment by Zangetsu38** [comment]
@hcorion compile error in VS, need remplace "WIN32" by "_WIN32"

**Comment by hcorion** [comment]
@Nekotekina How does this implementation look?

**Comment by Nekotekina** [comment]
Oh noes, this complicates things even more...
I would prefer a straighforward implementation, because who knows what these functions do when they access "PS3 memory"...

```C++
for (u32 i = 0; i < n; i++)
{
	const int ch1 = ::tolower(str1[i]), ch2 = ::tolower(str2[i]);
	if (ch1 < ch2)
		return -1;
	if (ch1 > ch2)
		return 1;
	if (ch1 == '\0')
		break;
}
return 0;
```

**Comment by hcorion** [comment]
@Nekotekina Ok, I've got a proper implementation now.
It's based on this code here: https://stackoverflow.com/a/7299168/4268405

**Comment by Nekotekina** [comment]
This code is different

**Comment by hcorion** [comment]
Every implementation I've seen of strncasecmp works like the one I provided.
See here:
https://github.com/tianocore/edk2/blob/master/StdLib/LibC/String/strncasecmp.c
https://opensource.apple.com/source/Libc/Libc-186/string.subproj/strcasecmp.c
http://www.jbox.dk/sanos/source/lib/string.c.html

**Comment by Nekotekina** [comment]
I'm looking at liblv2.sprx dump, it's pretty certain that it returns -1, 0, or 1. Some standard requires it to be "negative" or "positive", but we know better in this case. This is also why other functions in this module may require manual reimplementation (even those already implemented).

**Comment by hcorion** [comment]
Ok, good to know

**Comment by hcorion** [comment]
Ok, this uses the previous bit of code you mentioned earlier, is this good now?

**Comment by hcorion** [comment]
I've edited it because `std::tolower` is locale dependant.

**Pull request merged**
