### PR TITLE
Slims down minidx9 to keep XAudio2_7 files only

### PR DESCRIPTION
**Pull request by AniLeo**
Removes minidx9 as a submodule
Slims down minidx9 in order to only keep the files XAudio2 (2.7) needs. The other dx9 related files weren't being used.

~~Don't merge yet as requested by Nekotekina.~~

### CODE REVIEW

**Comment by danilaml** [comment]
I think it's better to move them to `XAudio2_7` folder, instead of just `XAudio`. And commits should be squashed.

**Comment by AniLeo** [comment]
I am going to squash commits before merge, it was just to prevent changes not to appear like in the latest PR I made
(The folder is XAudio2, but I'll rename)

**Comment by AniLeo** [comment]
Squashed and rebased.
Folder renamed to XAudio2_7

**Comment by Bigpet** [comment]
Can someone on Windows 7 confirm that we can use the weird stripped down XInput "9.1.0" that ships with Windows 7? I thought we used the SDK to get full XInput 1_3 too, but I'm not sure.

**Comment by AniLeo** [comment]
I think it would be better to keep it in the main repo like a lot of other emulators like citra, psc2x, dolphin, etc do as well

**Comment by tambry** [comment]
I also think it would be better to keep submodules in the main repo, as having a submodule for submodules will only create complexity and confusion.

**Comment by Nekotekina** [comment]
Damn these submodule changes. It's a fucking hell to rebase. Don't merge this please.

**Comment by Nekotekina** [comment]
Nevermind, should be fine to merge when rebased.

**Comment by AniLeo** [comment]
Rebased

**Pull request merged**
