### PR TITLE
Implement ps3 application root flags detection

### PR DESCRIPTION
**Pull request by elad335**
Needed for VSH (has root flags), separated from games.

List of currently affected syscalls:
* `sys_ppu_thread_set_priority`.
* `sys_ppu_thread_create`.
* `sys_spu_thread_group_set_priority`.
* `sys_spu_thread_group_create`.
* `sys_ss_access_control_engine`.

### CODE REVIEW

**Comment by ruthan** [comment]
What means VSH?

**Comment by elad335** [comment]
Google "ps3 vsh".

**Comment by elad335** [comment]
Can someone test as much games for regressions? it turns out sys_ss_access_control_engine return value is used in libsysmoudle.sprx to preload some more modules.

**Comment by dio-gh** [comment]
Tested with Drakengard 3, Nier, P5, RDR and Uncharted 1, everything seems fine to me.

**Comment by 740514www** [comment]
Tales of Xillia ERROR

9295
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4040944/RPCS3.log.gz)

9294
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4040950/RPCS3.log.gz)

**Comment by elad335** [comment]
Wrong pr. This one doesnt do anything for savedata.

**Pull request merged**
