### PR TITLE
rsx/common: Remove extra "-2" in get_exact_mipmap_count non compresse…

### PR DESCRIPTION
**Pull request by vlj**
…d format.

### CODE REVIEW

**Comment by tambry** [comment]
Was this fixed targeted at any specific game?

**Comment by kd-11** [comment]
I'm more confused by its inclusion in the first place.

**Comment by vlj** [comment]
It's not targeted at a specific game. 

Basically the function returns the true mipmap count of the texture. 
RSX can accept a mipmap level of 12 for a 128x128 texture ; however you can reduce such texture only 8 times (128=2^7). In case of compressed texture the base level is a 4x4 texture ie it can be reduced only 6 times
Opengl and Vulkan texture is invalid if texture mipmap count is too high. This function is clamping texture mipmap count reported by rsx with the max possible mipmap count allowed by the texture width height and format.

**Comment by vlj** [comment]
-2 was a typo actually

**Pull request merged**
