### PR TITLE
Official ds3 driver support

### PR DESCRIPTION
**Pull request by RipleyTom**
Some people have brought to my attention that there is an official DS3 driver supported by steam that is shipped with the ps now installer.
The pad handler now works with it(scrapped the previous version so you'll have to change driver again if you used the winusb driver, sorry but it does seem to be the optimal solution for ds3 users).

### CODE REVIEW

**Comment by Dokman** [comment]
what's the name of the driver shipped with steam? :(

**Comment by 13xforever** [comment]
The driver comes with the [PS Now app for PC](https://download-psnow.playstation.com/downloads/psnow/pc/latest)

**Comment by Zangetsu38** [comment]
Yes, i have already tested this driver before, but noit have works, so i have thinked only works with psnow ^^

**Comment by Dokman** [comment]
thank you guys <3

**Comment by Dravonic** [comment]
Got the new driver installed:

image

But I keep getting these error messages:

`
E HLE: [DS3] One or more DS3 pads were detected but couldn't be interacted with directly
`
`
E HLE: [DS3] Check https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration for intructions on how to solve this issue
`

Followed the instructions on the link given (except the drivers) but pressing the PS Button doesn't seem to do anything.

**Comment by leskal** [comment]
> what's the name of the driver shipped with steam? :(

the driver from ps now, extracted from C:\Windows\System32\DriverStore\FileRepository\sixaxis.inf_amd64_ef8eb017ea26cd93
[sixaxis driver.zip](https://github.com/RPCS3/rpcs3/files/3169175/sixaxis.driver.zip)

**Pull request merged**
