### PR TITLE
pergameconfig : create directory if not exists

### PR DESCRIPTION
**Pull request by georgemoralis**
this will fix the issue when trying to configure a game before running the game for the first time

### CODE REVIEW

**Comment by raven02** [comment]
i just want to make a pull to get the config.yml from base dir as new game template so we don't know to set everything from stratch . 

It would be appreciated if you can help to include it in this pull

**Comment by georgemoralis** [comment]
will look at it

**Comment by georgemoralis** [comment]
@raven02 it should work now as you suggested. Can you test it?

**Comment by raven02** [comment]
It works good . Thanks.

**Pull request merged**
