### PR TITLE
Implement SPU page faults, Synchronization fixes

### LINKED ISSUE #5350: Gran Turismo 5 - Save file broken
Version: RPCS3 0.0.5-7496-0e0a82e5 Alpha

Game: Gran Turismo 5 [BCES00569] (Other version the game, it should be same)
Issue: Save file doesn't work when emulator gets completely frozen. I have to delete save file to make run again. (I've tried the Neko's PR "Time fixes" that doesn't solve it.)

This might be fix workaround.
image

Hardware specs: i5-4690k @ 3.5ghz, ddr3 8gb 2400mhz, GTX 1050Ti 4GB.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2589886/RPCS3.log.gz)

[RPCS3_save broken.zip](https://github.com/RPCS3/rpcs3/files/2589932/RPCS3_save.broken.zip)

### PR DESCRIPTION
**Pull request by elad335**
* Implement SPU page fault notifications
* Fixes related to page faults are described in the commit.
 
Fixes saving issues in Grand Turismo 5 and Grand Turismo 6.
Allows Gran Turismo 6 to go ingame.
Fixes #5350

### CODE REVIEW

**Comment by jenci8888** [comment]
GT5 with save
image
[RPCS3-GT5.log.gz](https://github.com/RPCS3/rpcs3/files/2873394/RPCS3-GT5.log.gz)
(this can go ingame in any tracks or cars, but some tracks spams RSX log)

GT6 with save
image
[RPCS3-GT6.log.gz](https://github.com/RPCS3/rpcs3/files/2873381/RPCS3-GT6.log.gz)
(This can't go ingame due to entire broken render or couldn't load from track or car)

**Comment by uaqlover** [comment]
could it fix https://github.com/RPCS3/rpcs3/issues/5458 ?

and nice work elad335

**Comment by Kravickas** [comment]
Elad how it can fix skyrim, is it about race conditions since i had no problem with saves ?

**Comment by elad335** [comment]
@uaqlover No, the issue there is caused by something else.
@Kravickas It could be, the race fixes is what fixed GT5 saves.

**Comment by jenci8888** [comment]
Good job, Elad! GT6 goes ingame further!
image

**Comment by ruthan** [comment]
> Elad how it can fix skyrim, is it about race conditions since i had no problem with saves ?
 With which version of emulator is Skyrim Save/Load working for you? Im testing it continually from time to time and not sucess, so far. 
  I always create new save with new emulator version, to be sure that not old saves are corrupted. Which version of Skyrim, do you have?

**Comment by Kravickas** [comment]
BLUS30778, we talked somewhere about it.

**Comment by ruthan** [comment]
> BLUS30778, we talked somewhere about it. I think in skyrim it was never broken for me.

Its standard vs. Legendary edition (Legendary is broken).

**Comment by elad335** [comment]
@ruthan @Kravickas Please move this discussion to the issue itself unless its related to the PR's effects on it.

**Comment by micaelis72** [comment]
Elad,

This PR makes Star Ocean The Last Hope [MRTC00001] to start and play the intro movie. 
Still doesn't go ingame.

Follow the logs. I hope it helps improve the PR further and turn this game ingame.

Cheers!

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2892288/RPCS3.log.gz)

**Comment by elad335** [comment]
Your log is corrupt, I cant open it.

**Comment by micaelis72** [comment]
Elad,

I'm sending the *.log directly. It's small, so not a big concern.

I hope it helps,

Cheers

[RPCS3 .log](https://github.com/RPCS3/rpcs3/files/2894116/RPCS3.log)

**Comment by elad335** [comment]
@micaelis72 I'm not seeing any page fault related messages in log, is it working on latest master? could have been fixed very recently.

**Comment by frymezim** [comment]
@elad335 
Intro was working for 2 months now, but it never get to ingame. not even related to this pr.

**Comment by micaelis72** [comment]
In my test on Linux (Fedora), master wasn't allowing go intro with Star Ocean. This PR, yes.
I'm mainly testing RPCS3 in Linux, so maybe some games works on Windows and not in Linux.

I'll look if some game that doesn't work on Linux works in Windows next time.

**Pull request merged**
