### PR TITLE
PPU: Use SEQ-CST memory barrier in reservation load

### PR DESCRIPTION
**Pull request by elad335**
Do not allow stores accessed from the same cache line to be reordered past the reservation load: it makes no sense that stores of the same cache line as the reservation load can be reordered past the reservation load instruction to the atomic operation bounderies themselfs on realhw.

### CODE REVIEW

**Review by kd-11 — COMMENTED** [review]
Lgtm if I'm understanding the intent correctly. Out of curiosity, what does a memory barrier in cell PPU code actually emit?

**Comment by elad335** [comment]
mfence instruction on gcc/ckang, lock (memiry instruction) [memory] on MSVC.

**Review by kd-11 — APPROVED** [review]
lgtm

**Comment by JasonFre** [comment]
Now there's a net talk slang I'd not seen before. Learn something new every day. Even on a github for an emulation project.

**Pull request merged**
