### PR TITLE
fix segfault in boot recent list

### PR DESCRIPTION
**Pull request by Whatcookie**
The recent game list was causing segfaults on startup of the application my computer if the directories were unreachable. When the string entry.first was printed it would either print garbage or segfault (segfaults were guaranteed if there were multiple unreachable games in the recent boot list). 

I moved the LOG_ERROR just a few lines up and the errors stopped.
I'm not sure if this bug effects non linux platforms, or if it breaks non linux platforms or what.
If there's a better way to fix this let me know, I'm a noob.

may be the same as this issue?
https://github.com/RPCS3/rpcs3/issues/3014

### CODE REVIEW

**Comment by hcorion** [comment]
Those issues you found are most likely not at all related.
This looks good to me, but it would be good to get one of the GUI devs to look over this.

**Comment by Whatcookie** [comment]
Ok, the other ones I posted don't seem to be related, but I think https://github.com/RPCS3/rpcs3/issues/3014 is

**Comment by Megamouse** [comment]
I don't know linux but moving the log error is obviously fine.
maybe someone can try on windows, but I haven't encountered it yet.
I wonder if it still happens if you use `q_string_pair entry` instead of `const q_string_pair& entry`

**Comment by mechshingolem** [comment]
Hi, where i can download this version ?

**Comment by RainbowCookie32** [comment]
It's been a part of master builds since 2017 https://rpcs3.net/download

**Pull request merged**
