### PR TITLE
Performance overlay: add average and 1% low

### PR DESCRIPTION
**Pull request by Megamouse**
image

### CODE REVIEW

**Comment by dio-gh** [comment]
Huh, not a bad idea. Average over what time? The timespan displayed by the graph? Since game launch?

**Comment by cipherxof** [comment]
> Huh, not a bad idea. Average over what time? The timespan displayed by the graph? Since game launch?

The timespan on the graph would be preferable.

**Comment by VelocityRa** [comment]
> The timespan displayed by the graph?

Yes.

@Megamouse I don't think 1% low for frametime is useful? You want to see the bad spikes, which for frametime are high.
So it should either be configurable whether it gets the min, or max, or display both.

**Comment by Megamouse** [comment]
@VelocityRa 
> @Megamouse I don't think 1% low for frametime is useful? You want to see the bad spikes, which for frametime are high. Low is just artificially bounded by vsync or whatever.
> So it should either be configurable (by a class member) whether it gets the min, or max. Or have it display both.


The code already allows for enabling/disabling mn/mx respective 1%/av.
I just don't wanna add a setting because it bloats the settings dialog.

The question is, which values do we really need for which graph?
For example, would we really miss the mn mx for the fps?

image

**Comment by Megamouse** [comment]
Added some config settings at least.

**Comment by VelocityRa** [comment]
> The code already allows for enabling/disabling mn/mx respective 1%/av.
I just don't wanna add a setting because it bloats the settings dialog.

Didn't make myself clear enough - I meant it should be adjustable from the code (via a class member that can be set to whatever makes sense ie. max for fps, min for frametime) not exposed to the UI. If it already is, cool.

**Comment by VelocityRa** [comment]
> The code already allows for enabling/disabling mn/mx respective 1%/av.

I only see `show_one_percent_low_avg` not `show_one_percent_high_avg`. Just like I said on initial review.

**Comment by Megamouse** [comment]
done

**Comment by Megamouse** [comment]
I was wondering if the 1%low should be the average of the lowest 1%. Currently I just take the hard value of the 1% datapoint.

**Comment by MSuih** [comment]
You should because that's how it is calculated when show in f.ex. PC hardware reviews and thus what people expect it to mean.

**Comment by Megamouse** [comment]
Lol. As I said, there doesn't really seem to be a science behind it. So I just came up with any of this on my own.
Should be a one-line change

**Comment by Megamouse** [comment]
done

**Pull request merged**
