### PR TITLE
Cache changes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by money123451** [comment]
since there is No description provided I asked someone in the know what the commits do the first 2 deal with #5438, the 3rd is exactly what it says and the 4th is cleanup. (at least as far as they could tell from a glance)

**Comment by Jhonny-2005** [comment]
image
With this pr I have strange error. And after it close game - rpcs3 frozen.
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/2753420/rpcs3.zip)

**Comment by Nekotekina** [comment]
@Jhonny-2005 should be fixed

**Comment by Jhonny-2005** [comment]
@Nekotekina 
Yes, looks good. First ingame for twisted metal.
image
[rpcs3_pr.zip](https://github.com/RPCS3/rpcs3/files/2753593/rpcs3_pr.zip)

**Pull request merged**
