### PR TITLE
Intel Rocket Lake 11th gen support.

### PR DESCRIPTION
**Pull request by Cereal-Killa**

### CODE REVIEW

**Review by AniLeo — CHANGES_REQUESTED** [review]
This does nothing, "rocketlake" does not exist on the version our LLVM fork is currently based on 
https://github.com/RPCS3/llvm-mirror/blob/5d8643e8eb3fcc60d8ca04b0aa61f6fd0722a0a8/lib/Support/Host.cpp#L587

Instead, rocketlake CPUs are reported as "icelake" and similar variants by checking for the existence of specific instructions

**Comment by AniLeo** [comment]
To clarify: LLVM fork needs to be rebased with LLVM 12.0.0 first for this to do something

**Comment by Cereal-Killa** [comment]
Sounds good man, thanks for clarifying.

**Comment by Nekotekina** [comment]
Is it detected as "generic" or as "icelake"?

**Comment by AniLeo** [comment]
Looking at the LLVM code, should be either "icelake", "icelake-client" or "icelake-server".
Intel has fallback for newer CPUs by detecting extensions, so it should never be generic, that only happens for new AMD additions.

**Comment by Yahfz** [comment]
Rocket Lake CPUs are detected as icelake in master.

**Comment by Nekotekina** [comment]
Merged since this may be required later.

**Pull request merged**
