### PR TITLE
rpcs3_version: Bump to 0.0.10

### PR DESCRIPTION
**Pull request by AniLeo**

### CODE REVIEW

**Comment by Hopefullyidontgetbanned** [comment]
why not bump the version to 0.1? It seems like the compatibility database would reflect that version number better imo

**Comment by AniLeo** [comment]
Not yet

**Comment by StalkerDolg** [comment]
Logicly.... 0.0.9 > 0.0.10, because 0.10 = 0.1, and 0.0.10 its 0.0.1

**Comment by AniLeo** [comment]
Then use that math logic to stick with 0.0.9 and see if it magically updates

**Comment by elad335** [comment]
theres nothing logical in your statement, versioning system is not math.

**Comment by StalkerDolg** [comment]
Why are the people here so rude

**Comment by AniLeo** [comment]
Why are you spamming a closed PR with nonsense

**Pull request merged**
