### PR TITLE
Bump linux CI to 16.04, Update clang to 8, update Qt to 5.12.3

### PR DESCRIPTION
**Pull request by hcorion**
This PR requires #5964 to be merged before we can merge, namely for the image-base fix.
This PR also requires https://github.com/RPCS3/llvm/pull/8 to be merged at the same time as this PR.

Check out this commit: https://github.com/hcorion/rpcs3-docker/commit/c308a68a49cc2a9c00a2f347c21293cc655948f5
For the changes to the Dockerfile that were done.

After today my 4-day break ends, and I will be at school for another 2 months, which means I will be unable to fix any bugs that crop-up due to this PR.

Motivations for this PR:
- Ubuntu 14.04 is no longer being supported
- The provider of the Qt PPA we use no longer supported Ubuntu 14.04
- Newer clang is newer, which means more optimizations and bug fixes!

I've only had the time to test the produced AppImage on Arch Linux, but if you use a linux computer, fire up this AppImage: https://transfer.sh/uuPqf/rpcs3.AppImage

### CODE REVIEW

**Comment by Margen67** [comment]
Will the AppVeyor ever be upgraded to Visual Studio 2019?

**Comment by Megamouse** [comment]
@hcorion  Btw Qt 5.12.4 is out and Qt 5.13 is the latest now

**Comment by hcorion** [comment]
Yes, though Beineri hasn't released a PPA for 5.12.4 or 5.13 yet
https://launchpad.net/~beineri

**Comment by Megamouse** [comment]
Ok. That's cool then

**Comment by Leopard1907** [comment]
It works. Linux Mint 19.1 , Ubuntu 18.04 based.

**Comment by hcorion** [comment]
Ok, this looks ready for merge, just remember that this PR and https://github.com/RPCS3/llvm/pull/8 need to be merged at the same time

**Comment by AniLeo** [comment]
RPCS3/llvm#8 was merged but it didn't build to release so this won't pass until it does

**Comment by Megamouse** [comment]
@hcorion  can you also add QtConcurrent to the docker?
I need it for my multithreaded lists.
(or did I miss something and that has to be done in this project?)

**Comment by johnneijzen** [comment]
i think the build failed because of Third-part APT sources were remove in Xenial image compared to Trusty image since project is using docker you may need to add docker as source like desc here written here
https://docs.travis-ci.com/user/reference/xenial#third-party-apt-repositories-removed

**Comment by Megamouse** [comment]
:sleeping:

**Pull request merged**
