### PR TITLE
gl: Fix swizzle for DIVRSQ, COS, SIN in fragment shader

### PR DESCRIPTION
**Pull request by vlj**
This fix rsx_fp_static_test2.ppu.elf and rsx_fp_static_test3.ppu.elf.

### CODE REVIEW

**Comment by raven02** [comment]
@vlj .Probably u can help to add mask for DIV , EX2 and LG2 that should fix rsx_fp_static_test5.ppu.elf

**Comment by vlj** [comment]
I added EX2 and LG2. But for some reasons masking DIV break the dynamic test 2 and doesnt fix the third dynamic test either.

**Comment by vlj** [comment]
Is this the correct output from dynamic test 2 ? 
fractal

**Comment by raven02** [comment]
Not sure but probably yes .I'll try to get somebody to run those dynamic elf on PS3 .

**Comment by raven02** [comment]
@vlj , the rsx_fp_static_test4.ppu should be fixed now .

https://github.com/vlj/rpcs3/pull/7

**Comment by Syphurith** [comment]
@vlj BTW i hope you could remove those merged/purged/useless-forever branches..
If you used `git fetch --all` to get all branches you can just `git pull --progress --all -v -p`.

**Pull request merged**
