### PR TITLE
Minor fixups

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Nekotekina** [comment]
@Lenox548 Do you mind to test P5 on this PR?

**Comment by digitaldude555** [comment]
Persona 5 freezes at intro.

**Comment by Lenox548** [comment]
All right, on my way

**Comment by Lenox548** [comment]
Well, like digitaldude555 said, the game does not even start and the emulator stops responding immediately when the game boots up

**Comment by Nekotekina** [comment]
Try again

**Comment by Lenox548** [comment]
Got it

**Comment by Lenox548** [comment]
Exactly the same results, the game freezes after loading the compiled shaders, when i exit fullscren this happens, 
screenshot
And if i exit the game the emulator stops responding

**Comment by Nekotekina** [comment]
Need another test (after appveyor compiles).
Note that there is some unrelated bug on master that can cause freeze at startup, may resolve with few attempts.

**Comment by Lenox548** [comment]
For check if in this new branch the game freeze at startup, as you suggested, i tried to start the game 10 times, in some of those tries the game freezed after loading the precompiled shaders, like before, but in the other tries, after loading the precompiled shaders, the emulator just closed himself. In the 10 tries that I did, that happened 6 times. I did the same thing in the latest master to check if the game freezes at startup, as you said, I tried to start the game 10 times again and it didn't freeze in any of the 10 times.

**Comment by Lenox548** [comment]
I've testing a little more, just for research purposes and for the first time the game didn't freezed after loading the precompiled shaders, however it did after staying 15 seconds in the first loading screen and the game was extremely laggy, but I noticed that the same thing that happened in the first branches of # 6507, started to happen again, by that i mean that the performance of the game goes back to normal if i'm not in the RPCS3 window

**Comment by Lenox548** [comment]
in RPCS3 window:
screenshot

Out RPCS3 window:
screenshot (2)

**Pull request merged**
