### PR TITLE
rsx: Texture cache fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Clipping fixes for hw-accelerated blit operations. Hardware seems to have an off-by-one addressing offset when scaling is in place; likely just a hardware quirk.
- Strict format checking in texture cache. If a resource does not strictly match what is requested, a decode must be supported for it, otherwise fall back to a full untyped cast with either a direct copy or transfer via typeless medium.
- Fix texture scanning of some formats so that GPU-side layouts match CPU-side layouts (no multibyte swaps allowed). The improved consistency fixes a few bugs.
- Implement COMPRESSED_R8G8_R8B8 and COMPRESSED_B8R8_G8R8 format decode.
- Implement RGB_655 format decode.
- Fixes a glitch in the texture cache where subresources were not properly removed upon surface changes. Still needs some optimization work that will land later.
- Improve vulkan heap status checking to ensure the renderer does not run out of memory inside the texture cache.

### CODE REVIEW

**Comment by DanteBC** [comment]
Lollipo chainsaw finally shows cutscenes correctly on that PR. You finally did it, KD!
Master:
lol1
PR:
lol2

**Comment by DanteBC** [comment]
Neverdead now dies after intro on vulkan. On master everything's fine. Log's in the attacment
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3035678/RPCS3.zip)

**Comment by toccata10** [comment]
Guitar Hero III:legends of rock [BLES00134]: on Vulkan, the "E {RSX [0x011e848]} RSX: Depth texture bound to pipeline with unexpected format 0x95" don't show up anymore.
With Ogl: I now have a crash (doesn't crash on master)
```
F {RSX [0x01ab8e4]} RSX: St13runtime_error thrown: Unexpected internal format 0x822C
(in file /home/jo/tmp/rpcs3/version2/rpcs3/rpcs3/Emu/RSX/GL/GLTexture.cpp:122)
```
Sonic all stars racing transformed [blus30839]
very broken, but it looks better on master (green lines with this Pr):
Master
FPS: 30,00 | Vulkan | 0 0 6-7932 | Sonic   All-Stars Racing Transformed™  BLUS30839 _084

PR
FPS: 30,00 | Vulkan | 0 0 6-7938-031435ac-fbo_fixes | Sonic   All-Stars Racing Transformed™  BLUS30839 _089

**Comment by kd-11** [comment]
Need renderdoc capture for those strange lines.

**Comment by MarioSonic2987** [comment]
texture_format test doesn't run due to this:
```
·F 0:00:05.653849 {RSX [0x0001b7c]} RSX: struct gsl::fail_fast thrown: GSL: Precondition failure at c:\projects\rpcs3\3rdparty\gsl\include\gsl\span: 499
```

[Log texture_format test](https://github.com/RPCS3/rpcs3/files/3038144/RPCS3.log.gz)

**Comment by toccata10** [comment]
For the green lines:
https://www.dropbox.com/s/7kya6099us6260f/SonicRacing-GreenLines-rpcs3_2019.04.03_10.28.25_frame763.zip?dl=0
The problem with guitar hero on Ogl is now solved.

**Comment by kd-11** [comment]
@MarioSonic2987 Can you retry? Its caused by bad optimization by the compiler (it runs fine when compiled with gcc). I have simplified the code somewhat, should hopefully work now.

**Comment by MarioSonic2987** [comment]
Still throws the same error:
```
·F 0:00:16.602592 {RSX [0x0001b7c]} RSX: struct gsl::fail_fast thrown: GSL: Precondition failure at c:\projects\rpcs3\3rdparty\gsl\include\gsl\span: 499
```
[Log texture_format 2](https://github.com/RPCS3/rpcs3/files/3038545/RPCS3.log.gz)

**Comment by Xcedf** [comment]
With this PR Uncharetd 2 is improved, the menu looks very clear now

But that's not all, with reverted commit fa9b4486 and SRM enabled now i have shadow mapping working, and train's windows are no longer visible through the train

**Comment by kd-11** [comment]
@Xcedf Thanks! I have actually implemented DEPTH<->RGBA format conversions so that restriction is not necessary anymore. That commit should be rightfully reverted.

**Comment by legend800** [comment]
Little improvement on Motorstorm Pacific Rift:  https://github.com/RPCS3/rpcs3/issues/5597

PR (new reflection showing):
2019-04-03 09_00_27-Sega Model 2 UI (2019_04_02) - EmuCR

Still not fully rendered correctly:


Backbreaker regression/improvement:

WCB+BLIT On:
2019-04-03 08_36_14-FPS_ 30 01 _ Vulkan _ 0 0 6-16c204ad-fbo_fixes _ BACKBREAKER VENGEANCE  NPEB0059

WCB+Blit Off:
2019-04-03 08_37_10-FPS_ 30 00 _ Vulkan _ 0 0 6-16c204ad-fbo_fixes _ BACKBREAKER VENGEANCE  NPEB0059

Previously the crowd did not render (at all), now they kinda show but are all messed up and flash constantly. Annoying for now, but progress towards correct crowd rendering.

**Comment by isshininu** [comment]
With this PR The Evil Within audio now does not interrupts and plays properly all the time (until Fatal error occured).

**Comment by kd-11** [comment]
@MarioSonic2987 Fixed gsl exception
@Xcedf I have removed the format conversion barrier, check if UC2 now works properly without reverting commits.

**Comment by Kravickas** [comment]
https://vimeo.com/328247784

**Comment by MarioSonic2987** [comment]
texture_format test now works:
image

**Comment by Xcedf** [comment]
@kd-11 confirm, it works, Thanks

**Comment by kd-11** [comment]
Updated the format conversion code a bit to take more variables into account, retest any regressions. I can confirm that some conversions (e.g ARGB8->Y16X16_FLOAT) now work properly again.

**Comment by MsDarkLow** [comment]
Not sure if its an improvement or regression in Sniper Elite v2, visuals are bad on both sides either way.
<details>
<summary>Sniper Elite v2</summary>


No WCB/Blit - Master/PR, both show the same visuals
MR None

WCB - In non-moving camera both show exactly the same visuals
MR WCB1

But when the camera moves around, the PR seems to show more visuals. (This improvement doesn't apply ingame)
Master
MR WCB2
PR
PR WCB2

WCB+Blit
Master, shows nothing but a void of black
MR WCB+Blit
PR, comparing to the no wcb/blit picture it doesn't show the left side of the screen, only the "right" is shown (it matches the whole resolution)
PR WCB+Blit
</details>
Additional info: The left side of the screen seems to not render red colors? Only Green and Blue? And on the right side idk. (This applies to both master and PR)

**Comment by kd-11** [comment]
Looks like bad AA scaling, as long as it was always broken I have no intention of looking into it at the moment. AA work will go in its own PR.

**Comment by kd-11** [comment]
@toccata10 Green lines still an issue?

**Comment by beatlep** [comment]
Uncharted 2 show this artifacts sometimes in this PR:

Snap1

**Comment by Emulator-Team-2** [comment]
@Xcedf 
Can you confirm this?

**Comment by Xcedf** [comment]
I guess it some sort of fog or depth issue or maybe both

**Comment by Emulator-Team-2** [comment]
@Xcedf 
I mean, does the master build have the same issue?

**Comment by Xcedf** [comment]
this moment on master looks like this

**Comment by toccata10** [comment]
Sega all stars racing: Green lines still an issue?
I removed all the caches (shader, ppu, spu) and I still have green lines.
FPS: 30,01 | Vulkan | 0 0 6-7942-3867400a-fbo_fixes | Sonic   All-Stars Racing Transformed™  BLUS30839 _091

**Comment by jenci8888** [comment]
I tested few racing games.

GT6 in Master
image

GT6 in this PR (Little improved reflection tachometer, but regressed skybox)
image

NFS Most Wanted in Master
image

NFS Most Wanted in this PR (regressed car reflection)
image

**Comment by Xcedf** [comment]
I noticed on latest commits fixed overbloom regression in GoW3, as for Sonic Transfromed it regressed after 71c4170f

**Comment by uaqlover** [comment]
@kd-11 with this build could fix https://github.com/RPCS3/rpcs3/issues/4938 ?

**Comment by Asinin3** [comment]
@uaqlover No, but why not test it yourself? I just did and it's still broken.

**Comment by QiQiRyan** [comment]
#5095 this build fixed this

**Comment by kd-11** [comment]
Fixed broken multibyte type textures when Z-scanning is used. Should fix green lines in sonic & all-stars game.

**Comment by toccata10** [comment]
sonic & all-stars: green lines are now fixed.

**Comment by Xcedf** [comment]
Baja Edgr of Control, commit 3867400a
before

after

**Comment by kd-11** [comment]
@Xcedf Need RDC for the broken output.

**Comment by Xcedf** [comment]
@kd-11 this is the first time i captured rdc, hope i did it right
https://mega.nz/#!yJBX2CwA!EPo-bKukPs5bEqCPuF2OmYUBVIVmmzi8Ns2SAvIfyag

**Comment by vietnam13231** [comment]
Latest commit makes Infamous crash right before entering the game world. Cleaning PPU/shaders doesn't help.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3051279/RPCS3.zip)

**Comment by kd-11** [comment]
@Xcedf Baja Should be fixed again now.

**Comment by Xcedf** [comment]
@kd-11 confirm, refixed

**Comment by kd-11** [comment]
There were some other regressions with texture decode, fixed now.

**Comment by vietnam13231** [comment]
Infamous works again.

**Comment by jenci8888** [comment]
Fixed all games with green reflection and skybox.

**Comment by legend800** [comment]
@kd-11 Any chance you can take a look at the crowd Backbreaker? Before they didn't render at all, now they do, but they're broken and flicker like mad. Too annoying to play now. :(

2019-04-07 08_58_47-Window

Renderdoc:
https://drive.google.com/file/d/1YskUr0MEJA7hb6umwktdk8LJ-iCBTKo2/view?usp=sharing

**Comment by BlueAmulet** [comment]
Twisted Metal seems to have improved a bit with this PR
Before:

After:

RenderDoc:
https://drive.google.com/file/d/1gntXRfJDy304GuKFSHXqTACMelz5s_Kc/view?usp=sharing

**Comment by uaqlover** [comment]
with last pr sound improve bit in FIFA games

**Comment by uaqlover** [comment]
NASCAR '14 [BLUS31378] has a regression with last pr

master

FPS_ 30 01 _ Vulkan _ 0 0 6-7934 _ NASCAR '14  BLUS31378  07_04_2019 11_59_28 AM

pr

FPS_ 29 98 _ Vulkan _ 0 0 6-bdc29c64-fbo_fixes _ NASCAR '14  BLUS31378  07_04_2019 11_57_53 AM

**Comment by kd-11** [comment]
I'll need some kind of trace to debug that @uaqlover. Grab either RDC or an RRC, preferrably an RSX capture here since it probably is a simple issue.

**Comment by spyropt** [comment]
uncharted 1 has exploding vertices

**Comment by kd-11** [comment]
@uaqlover Cannot reproduce broken colors with nascar 15 demo which has the exact same scene. Can you confirm this difference?

**Comment by toccata10** [comment]
For nascar 2014, you need to enable wcb.
Without wcb:
FPS: 30,00 | Vulkan | 0 0 6-7946-c3b08356-fbo_fixes | NASCAR '14  BLUS31378 _092
With wcb:
FPS: 30,00 | Vulkan | 0 0 6-7946-c3b08356-fbo_fixes | NASCAR '14  BLUS31378 _093

**Comment by isshininu** [comment]
force cpu blit + write color buffers are required
thanks you, kd-11 
<details>Снимок экрана (96)</details>

**Comment by uaqlover** [comment]
this pr fix 

NBA 2K13 [BLUS31028]

NBA 2K14 [BLUS31204]

master





pr

FPS_ 130 66 _ Vulkan _ 0 0 6-bdc29c64-fbo_fixes _ NBA 2K13  BLUS31028  08_04_2019 12_24_39 PM

FPS_ 105 74 _ Vulkan _ 0 0 6-bdc29c64-fbo_fixes _ NBA 2K14  BLUS31204  08_04_2019 12_38_03 PM

**Comment by kd-11** [comment]
@toccata10 Does it also need wcb on master? I'd be interested in a comparison if not, an rdc from before and after.

**Comment by uaqlover** [comment]
IT FIXED IT SELF WITHOUT WCB

FPS_ 30 01 _ Vulkan _ 0 0 6-bdc29c64-fbo_fixes _ NASCAR '14  BLUS31378  08_04_2019 5_45_15 PM

no idea how

**Comment by toccata10** [comment]
I confirm the same strange behaviour noted by @uaqlover: Nascar'14 was working fine on master without wcb. It is now working fine on this PR, without wcb.

**Comment by werwur** [comment]
how can I fix the "RSX: struct gsl::fail_fast thrown: GSL: Precondition failure at c:\projects\rpcs3\3rdparty\gsl\include\gsl\span: 621" bug? what I must download?

**Comment by werwur** [comment]
please help :(

**Comment by AniLeo** [comment]
Please don't spam.

**Pull request merged**
