### PR TITLE
improve cellPad [fixes Input regression]

### PR DESCRIPTION
**Pull request by Megamouse**
fixes Super Street Fighter Turbo 2 HD
similar to prior Catherine fix

also fixes a bug where devices become useless when a "prior" device is disconnected during multiplayer leading to lowered now_connect count

### CODE REVIEW

**Comment by Kravickas** [comment]
FIFA 18 - press start works now
unknown

**Comment by Luffykun007** [comment]
with this PR FIFA World Cup Brazil 2014 going into the game now.

capturar

capturar2

**Comment by spyropt** [comment]
Super Street Fighter Turbo 2 HD Tested and working again :) thanks

**Comment by bobthecooldad** [comment]
This fixes the simpsons game stuck at controller reconnect

**Comment by Asinin3** [comment]
Simpsons can go ingame on master just need to unplug controller then plug it back in.

**Comment by SakataGintokiYT** [comment]
In game with this PR 
bez tytulu

**Comment by TGEnigma** [comment]
BLUS30023 now goes ingame

**Comment by toccata10** [comment]
It fixes keyboard input on super street fighter 2, but if I change to an evdev joystick: no input at all. No input neither on my ds4 controller.
The logfile:
[RPCS3.log-cellpad.gz](https://github.com/RPCS3/rpcs3/files/1600010/RPCS3.log-cellpad.gz)

**Comment by Megamouse** [comment]
@toccata10 try again

**Comment by toccata10** [comment]
Can't build on my system
```
[ 78%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/evdev_joystick_handler.cpp.o
cc1plus: warning: /home/jo/tmp/rpcs3/megamouse/rpcs3_build/rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch : non utilisé parce que « __STDC_CONSTANT_MACROS » est défini [-Winvalid-pch]
/home/jo/tmp/rpcs3/megamouse/rpcs3/rpcs3/evdev_joystick_handler.cpp: Dans la fonction membre « evdev_joystick_handler::EvdevDevice* evdev_joystick_handler::get_device(const string&) »:
/home/jo/tmp/rpcs3/megamouse/rpcs3/rpcs3/evdev_joystick_handler.cpp:237:31: error: pas de fonction concordante pour l'appel à « evdev_joystick_handler::update_device(evdev_joystick_handler::EvdevDevice&, bool) »
  if (!update_device(dev, false))
                               ^
/home/jo/tmp/rpcs3/megamouse/rpcs3/rpcs3/evdev_joystick_handler.cpp:113:6: note: candidate: bool evdev_joystick_handler::update_device(evdev_joystick_handler::EvdevDevice&)
 bool evdev_joystick_handler::update_device(EvdevDevice& device)
      ^~~~~~~~~~~~~~~~~~~~~~
/home/jo/tmp/rpcs3/megamouse/rpcs3/rpcs3/evdev_joystick_handler.cpp:113:6: note:   le candidat attend 1 argument, 2 fourni(s)
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:7727: rpcs3/CMakeFiles/rpcs3.dir/evdev_joystick_handler.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

```

**Comment by Megamouse** [comment]
@toccata10 sorry. I forgot a line. I hope it works now

**Comment by toccata10** [comment]
It works fine now. I tested with evdev, ds4 and keyboard. So the linux part seems ok. Probably just waiting for the merge now.

**Comment by Megamouse** [comment]
as far as I can tell everything was tested now.
good thing this wasn't merged before (well actually i could've fixed all issues faster then hehe)

**Comment by LuismaSP89** [comment]
@Megamouse Syberia 2 still has no input even with this PR :S

**Comment by Megamouse** [comment]
I know. but i can't find the problem. And I don't think I caused it

**Comment by toccata10** [comment]
Syberia 2 [NPEB02016] has not input problems for me (just tested the beginning) on master. Tested with keyboard and ds4 on windows+linux.

**Comment by LuismaSP89** [comment]
@toccata10 Strange, i can´t pass the "Press start" screen, and i´m not the only one with this problem as you can see in the issue that i opened:

https://github.com/RPCS3/rpcs3/issues/3985

Mine is NPEB02016 too, and i tested with keyboard, xbox 360 and xbox one controllers.

**Comment by toccata10** [comment]
I hope this gets merged soon as it improves master for several games. The syberia 2 pb is already in master, so there's no regression here, just improvement (from what I can see).

**Comment by LuismaSP89** [comment]
@toccata10 Syberia problem is solved (https://github.com/RPCS3/rpcs3/issues/3985)

**Pull request merged**
