### PR TITLE
Add savestate buttons to home menu

### PR DESCRIPTION
**Pull request by elad335**
image

### CODE REVIEW

**Comment by Megamouse** [comment]
does this even work when the menu is open?
I'd assume the menu close event is never sent on reload

**Comment by elad335** [comment]
Of course, it just boots without closing the menu. If you want something more fancy there is that auto-pause setting on savestate startup that I forgot its name.

**Comment by Megamouse** [comment]
also, why is it between the screenshot and recording. seems kinda arbitrary

**Comment by elad335** [comment]
Define "cold state".

**Comment by Megamouse** [comment]
For example making a savestates while in the menu and then booting the savestate after closing the game or rpcs3

**Comment by elad335** [comment]
Same savestate file would behave the same each time it is booted, it does not matter what happened in the past.

**Comment by Megamouse** [comment]
How does it not matter if we never send the menu close event

**Comment by elad335** [comment]
I just tried to terminate the emulation while the menu is open and it works so is savestate reboot, if there is a bug I'm not aware of that requires a close event when terminating the emulation that's on your side.

**Comment by Megamouse** [comment]
image

**Comment by Megamouse** [comment]
you basically have to either send the menu close event after reloading the savestate, or you have to close the menu first and wait until the event is in memory or processed.

**Comment by Megamouse** [comment]
just to make this clear:
The game opens the pause screen when you open the home menu.
When you then create and boot the savestate, you can't interact with the game (press start to continue) unless you open and close the home menu again.

**Comment by elad335** [comment]
Oh, I see, odd that it sends an emulated menu event. Shouldn't it call Emu.Pause() instead? Menu events are not compatible with savestates then.

**Comment by Megamouse** [comment]
we have a setting for that:
image

**Comment by Megamouse** [comment]
It doesn't prevent the event currently though

**Comment by elad335** [comment]
Implemented!

**Comment by Megamouse** [comment]
I'll test when I have time

**Comment by elad335** [comment]
Screenshot_20230412_040947_Discord

**Comment by elad335** [comment]
The event is sent that I tested locally.

**Comment by Megamouse** [comment]
It seems to work but for some reason arkedo only lets me press start after 3 seconds, whereas it usually lets me press start immediately after closing the home menu.

**Pull request merged**
