### PR TITLE
Slay the mystical openGL bug a.k.a. "second boot crash"

### PR DESCRIPTION
**Pull request by Megamouse**
@RipleyTom managed to squash that one by himself. (hmm that commit got lost in rebase sorry)

Fixes Cg_Disasm for @Jarveson as well

minor fix: adjust toolbar size because it was too big and blurry

### CODE REVIEW

**Comment by toccata10** [comment]
Double-clic and escape key don't work anymore.

**Comment by Megamouse** [comment]
oh thx. my guts told me something is missing but I couldn't point a finger at it

**Comment by Megamouse** [comment]
@toccata10 should be fixed now. please try again when ready

**Comment by toccata10** [comment]
OK: it's fixed.

**Comment by Dokman** [comment]
this fixes god of war collection? i can't boot the game

**Comment by Megamouse** [comment]
no. this fixes a bug that prevents some people from booting any game. 
It does not improve any game

**Pull request merged**
