### PR TITLE
Update cellSaveData

### PR DESCRIPTION
**Pull request by TomiYuga**
As per [this comment](https://github.com/RPCS3/rpcs3/pull/2679#issuecomment-294020832l), fixes Persona 5's save list not updating.

### CODE REVIEW

**Comment by twdarkeh** [comment]
No effect on #2685

**Comment by TomiYuga** [comment]
It wasn't intended to have an effect on that. I'm still not quite sure what's causing that.

**Comment by Zangetsu38** [comment]
no fix resogun regression
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/923220/RPCS3.txt)

**Comment by Inviuz** [comment]
@TomiYuga #2685 is most likely caused by nullptr in this call
``` ·W 0:00:12.151361 {PPU[0x1000015] Thread (savedata_sub_thr) [0x002c3e08]} cellSaveData: cellSavaDataGetListItem(dirName=“NPUB31475-SYSTEM-”, dir=*0x0, sysFileParam=*0x0, bind=*0x0, sizeKB=*0xd00d3c50)```

Other access violation errors seem to be related with MFC, it regressed most likely in Neko sys prx changes, not in save changes

**Comment by twdarkeh** [comment]
Fixes #2685

**Comment by digitaldude555** [comment]
Persona saves overwrite now. It's working fully.

**Pull request merged**
