### PR TITLE
Try to really fix Coverity and progress on moving to container builds

### PR DESCRIPTION
**Pull request by tambry**
Coverity should be hopefully fixed. Also quite a bit of progress on moving to container builds. Only hurdle now is https://github.com/travis-ci/apt-package-whitelist/issues/417. Builds with the removal of most sudo commands have received a somewhat noticeable speedup - ~30seconds.

### CODE REVIEW

**Comment by tambry** [comment]
@Nekotekina Ready for merging?

**Comment by Nekotekina** [comment]
I don't know, but why not? Btw, use
`git pull https://github.com/tambry/rpcs3.git RealCoverityFix` command (can be copied from "command line instructions") for fast-forward merge. Merge commits for small PRs are just a trash in the history.

**Comment by Nekotekina** [comment]
@tambry Are you blind?

**Comment by tambry** [comment]
@Nekotekina ?

**Pull request merged**
