### PR TITLE
Dualshock3 Sixaxis evdev support updates

### PR DESCRIPTION
**Pull request by dreaddymck**
Minor adjustments to the library to allow support for the dualshock 3 sixaxis controller under linux. 
Verified with a Gamepadtest.pkg. 
No games are available for further testing.

### CODE REVIEW

**Comment by hcorion** [comment]
This just changes the default config values. You need to modify `config_linuxjoystick.yml` in `~/.config/rpcs3` and change these per controller.

Please close this.

**Comment by rodjun** [comment]
The evdev_joystick_handler changes are fine, they fix the broken right stick on ps3 controllers, it will require default config changes tho because it probably breaks the x360. Needs someone with an x360 controller to test

**Comment by hcorion** [comment]
Yeah, that's what I'm saying. To fix the broken right stick on ps3 controller, you need to modify the config file, not the code itself.

**Comment by toccata10** [comment]
@rodjun :You can have a look at #2885

**Comment by toccata10** [comment]
Something that would be nice: have a config_linuxjoystick.yml like this:
```
Dualshock Sixaxis:
  Start: 5
  Select: 6
  L2: 10
  R2: 11
Dragon Rise Joystick:
  Start: 6
  Select: 7
  L2: 10
  R2: 11
```
And load the correct part, depending on the device name. I'd like that (as I have a xbox controller for certain games and a custom arcade stick for others), but as I don't know yaml at all, I won't try it for now.
It seems like a useful and reasonable challenge (see #3181 for more inspiration).

**Comment by hcorion** [comment]
Yeah, that's kinda what I meant by `Add separate configs for more controllers.` in 3181

**Comment by dreaddymck** [comment]
_This just changes the default config values. You need to modify config_linuxjoystick.yml in ~/.config/rpcs3 and change these per controller._

Understood. In reality. After setting the following line to false

 cfg::_bool squirclejoysticks{this, "Squircle Joysticks", false};

the right analog worked. Maybe offer that option the the yaml. Eveything else is overidable.


I will close this out.

**Comment by hcorion** [comment]
Yep, it is offered in the .yaml

**Pull request closed without merging**
