### PR TITLE
rsx: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Compatibility workarounds for AMD cards (disables primitive restart on vulkan and emulates glMultiDrawArrays which are broken on windows driver)
- Reimplements index buffer expansion/emulation and improves use of the primitive restart flag
- Fixes clear commands for depth-only passes. This removes the need for the invalidate cache hack.

### CODE REVIEW

**Comment by Blacksama** [comment]
@kd-11 Why in the latest build do I have to disable Strict Rendering to get resolution scale to work, I am fond of leaving strict rendering on. It seemed to not cause any problem. Thanks!

**Comment by Asinin3** [comment]
@Blacksama Strict rendering mode is an accuracy setting, resolution scaling isn't accurate. KD already did some fixes which removes the need for strict rendering mode in some games about a week ago, so see if your games still need it enabled. Also this really isn't the place to ask, as this wasn't changed in this Pull Request. Discord is pretty much the best place to ask questions like this.

**Comment by Blacksama** [comment]
Understood, I don't really use discord (not even know what it is  xD), thanks for your answer.

**Comment by Asinin3** [comment]
@Blacksama Once again not the place to talk about it, but that issue is not fixed by strict rendering mode, it's fixed when using 100% scaling and since strict rendering forces 100% scaling.....

**Comment by valgusk** [comment]
This seems to have fixed crashing for Demon's Souls on both Vulkan and OpenGL on Windows, is it possible to do the same for Linux? Mesa3d still crashes on both renderers

**Comment by kd-11** [comment]
@valgusk I need the device names from radv to make it work. On windows the proprietary driver returns the correct on-box product name like "AMD RX Vega" but radv usually returns internal code names, e.g "AMD PITCAIRN" instead of "R9 200". I'll need a list of mesa device names for RX 460/470/480/550/560/570/580 as well as all Vega. Unfortunately I don't have any of these and most testers don't run linux so I don't know the names to blacklist.

**Comment by gusthe** [comment]
@kd-11 For my RX 470 my device name is listed as "AMD RADV POLARIS10" by vulkaninfo under "Device Properties and Extensions". Is this what you would use?

**Comment by valgusk** [comment]
Actually there might be something else wrong. I later hardcoded both places to mark amd card detected and Vulkan crashed shortly after booting, while OpenGL dropped the driver at the same place as before. I might have compiled wrong though, so I am not a very reliable source. 

Otherwise best I can do is probably query device for its name and paste it here, but I can only do so for my card

**Pull request merged**
