### PR TITLE
ci: auto-optimize images

### PR DESCRIPTION
**Pull request by jy95**
To deal with the tidious process to optimize images, I suggest to use a Github Actions workflow for pull requests.
Why ?

- might help to have lighter binaries
- could be [configured](https://github.com/marketplace/actions/image-actions#configuration)
- paintful to do that everytime manually

### CODE REVIEW

**Comment by AniLeo** [comment]
We very rarely include new images, I think this should be left to the designers adding any new image elements and not be done through general optimization

**Comment by jy95** [comment]
@AniLeo It might be useful for people that maintain the site https://rpcs3.net/ . (I thought the sources were there since there's no repo)

**Comment by AniLeo** [comment]
The website is not on the RPCS3 organization, it's on https://github.com/DAGINATSUKO/www-rpcs3

**Comment by sampletext32** [comment]
> @AniLeo It might be useful for people that maintain the site https://rpcs3.net/ . (I thought the sources were there since there's no repo)

For this reason you should better create a pull request to the website repo, not the emulator itself.
https://github.com/DAGINATSUKO/www-rpcs3

**Comment by AniLeo** [comment]
Closing here since it's not the correct repository

**Pull request closed without merging**
