### PR TITLE
rsx/common/d3d12/gl: Implement draw inline array support

### PR DESCRIPTION
**Pull request by vlj**
It's required for Bleach Resurection Soul.

### CODE REVIEW

**Comment by AlexAltea** [comment]
> By analyzing the blame information on this pull request, we identified [...] @AlexAltea to be potential reviewers.

Can someone please correct the blacklist for @mention-bot? I don't want to receive any notifications for this repository as I'm not a collaborator anymore.

**Comment by tambry** [comment]
@AlexAltea I have made a [commit](https://github.com/tambry/rpcs3/commit/d323f33696d5e3137da0c1db2712c089350a479f) to fix the bot. I'll probably be making a PR for that branch during this week.

**Comment by vlj** [comment]
Rebased

**Comment by vlj** [comment]
can this PR be reviewed/merged please ?

**Comment by vlj** [comment]
thanks

**Comment by DHrpcs3** [comment]
@vlj, I have added you as PR Reviewer to pullaprove. So, you can approve your commits yourself. Please, do not approve critical changes

**Pull request merged**
