### PR TITLE
Fix yaml-cpp fork commit

### LINKED ISSUE #14740: Git error in Flatpak build due to yaml-cpp having unknown remote commit
After the update of yaml-cpp included in this [commit](https://github.com/RPCS3/rpcs3/commit/ec916d1f5f30234fcef05a4d3794ba704a373c1f), the [flatpak build](https://buildbot.flathub.org/#/builders/35/builds/9138) has started to fail:
```
fatal: git upload-pack: not our ref 456c68f452da09d8ca84b375faa2b1397713eaba
fatal: remote error: upload-pack: not our ref 456c68f452da09d8ca84b375faa2b1397713eaba
fatal: Fetched in submodule path '3rdparty/yaml-cpp/yaml-cpp', but it did not contain 456c68f452da09d8ca84b375faa2b1397713eaba. Direct fetching of that commit failed.
```
I don't know all the underlying git commands executed, thus haven't been able to reproduce outside the flatpak build, however the commit pointed by the error is indeed not existing on the remote repository: https://github.com/jbeder/yaml-cpp/commit/456c68f452da09d8ca84b375faa2b1397713eaba.

If yaml-cpp 0.8.0 is supposed to be used, shouldn't the commit be https://github.com/jbeder/yaml-cpp/commit/f7320141120f720aecc4c32be25586e7da9eb978?
If not possible to contribute to the upstream package, a fork should perhaps be used (or subtree?).

Thanks in advance.

### PR DESCRIPTION
**Pull request by j8r**
Fixes #14740.
I tested on my fork, no more error. Seems to have also been noticed by @voyageur? I've seen a commit linked to the issue - can you confirm it is also fixing for you too?

### CODE REVIEW

**Comment by Megamouse** [comment]
Sorry but this is not a fix.
I just have to push it to the correct branch.

**Comment by j8r** [comment]
Push to the master branch of yaml-cpp?
Fine by me, thanks a lot!

**Comment by Megamouse** [comment]
A branch should exist now.

**Comment by voyageur** [comment]
I can confirm, git checkout is working great now with the branch

**Comment by j8r** [comment]
Me too, working now - thanks @Megamouse !

**Comment by j8r** [comment]
Hello back @Megamouse, sounds like we have a similar issue now with Soundtouch: https://github.com/RPCS3/soundtouch/commit/ced3ce8d5ecc5aef8a5156fea206a37b33774bf3 is only present in [your fork in the update branch](https://github.com/megamouse/soundtouch/commit/ced3ce8d5ecc5aef8a5156fea206a37b33774bf3), not in the [upstream repo](https://github.com/RPCS3/soundtouch).

**Comment by Megamouse** [comment]
Ah snap, I forgot to push the old commit to the other repo

**Comment by Megamouse** [comment]
should be fixed

**Comment by j8r** [comment]
Thanks a lot! Sorry to have bothered you.

**Pull request closed without merging**
