### PR TITLE
Callback: unlock mutex

### PR DESCRIPTION
**Pull request by raven02**
fix https://github.com/RPCS3/rpcs3/issues/2022

### CODE REVIEW

**Comment by raven02** [comment]
@Nekotekina , good to go?

**Comment by Nekotekina** [comment]
Now it's unlocked twice

**Comment by raven02** [comment]
I see. Thus the correct way ?

**Comment by raven02** [comment]
Humm just tested with other games and looks like it hold up and freeze.

**Comment by paulsapps** [comment]
You should have just added scoped blocks to destruct the lock earlier

**Comment by raven02** [comment]
@paulsapps .It would be nice if you can put a example here where to destruct the lock

**Comment by danilaml** [comment]
@raven02 lock should be destroyed automatically every `while` iteration or after `return`.

**Comment by raven02** [comment]
i did try to put the unlock after return however it break other games

**Comment by danilaml** [comment]
@raven02 unlock after `return`? What? Return exits the function, everything after it is ignored.

**Pull request closed without merging**
