### PR TITLE
Add sys_rsx_context_iomap workaround

### PR DESCRIPTION
**Pull request by Nekotekina**
Don't fail with CELL_EINVAL on vm::main.

### CODE REVIEW

**Comment by elad335** [comment]
The actual bug is already fixed by #5893 tho.

**Comment by Nekotekina** [comment]
I know, I'm sorry. I'm just afraid that PR may need some more polishing.

**Comment by Snakegodeater** [comment]
i still get this on MGS4 

F {PPU[0x100001e] Thread (OVERLAY_LOAD) [0x00013220]} class std::runtime_error thrown: vm::falloc() failed (addr=0x30000000, memsz=0x3afe80)
and the game just black screens . From #5893 commits i was able to get in-game . Can u check this error out ?

**Comment by dio-gh** [comment]
I'm generally interested why this PR was merged instead of @elad335's. This strikes me as a workaround, while #5893 striked me as a result of a full research. I did ask him on Discord, but couldn't make much out of his answer - kinda gave me the impression he just gave up on his PR getting merged, as it went unreviewed for so long.

So what is the actual status of this matter?

**Comment by Snakegodeater** [comment]
i thought this PR had all that changes merged from #5893 PR  but it doesn't seem that way ! :/ Anyhow whow knows ! People want to know how MGS4 will be at least bootable or go into menus .Me too My self Although i still Have My PS3 But i am getting Dull with it . LOL .Just waiting this game on RPCS3 Asap PC emulation is the best !!!

**Comment by Snakegodeater** [comment]
Never mind Eladash opened another PR about MGS4 and it should get merged soon i think .

**Pull request merged**
