### PR TITLE
VK_REMAP enum is signed.. but later case comparison is unsigned

### PR DESCRIPTION
**Pull request by bevanweiss**
another clang directed fix up... might be involved with swizzle..

### CODE REVIEW

**Comment by elad335** [comment]
Example of warnings cleanup pr: https://github.com/RPCS3/rpcs3/pull/6671, notice how a single pr does it all.

**Comment by bevanweiss** [comment]
> Example of warnings cleanup pr: #6671, notice how a single pr does it all.
I'm still new to this project, and to the build process, including clang... So I still think it's 'safer' for me to have numerous small PRs than a larger PR with numerous varied things in it.

**Comment by Megamouse** [comment]
these single line PRs that don't really do anything really just clog up our pipeline and cost developer time.
Just prepare everything until you can't find any trivial changes anymore and then open one single PR.

**Comment by MSuih** [comment]
Also, we don't have proper versioning at the moment so every merged pull request causes a update notification to appear for end users, which is more annoying the more frequently it happens. 

Don't take this the wrong way, your changes are worthwhile additions. You'll just need to combine them together a bit and not just fire a new pull request each time you find something worth changing.

**Comment by bevanweiss** [comment]
> Also, we don't have proper versioning at the moment so every merged pull request causes a update notification to appear for end users, which is more annoying the more frequently it happens.
> 
> Don't take this the wrong way, your changes are worthwhile additions. You'll just need to combine them together a bit and not just fire a new pull request each time you find something worth changing.

Is there a reason to not have a staging branch for PRs to go to after the build checks, but then only having nightly master builds?

**Comment by kd-11** [comment]
> Is there a reason to not have a staging branch for PRs to go to after the build checks, but then only having nightly master builds?

This is pointless without QA. Users will just download the unstable branch anyway if it fixes their game and if it doesn't fix any games in particular, nobody will test it. Instability will get into the nightlies and we're back where we started.

**Pull request merged**
