### PR TITLE
Fixes commit count on GIT-VERSION | RPCS3 v0.0.4

### PR DESCRIPTION
**Pull request by AniLeo**
If we're in AppVeyor and building for master:
- Fetches commit count from unshallowed upstream instead of fetching from HEAD (will always be 3 since we clone with depth of 3)

Solves #3693

### CODE REVIEW

**Comment by danilaml** [comment]
What's the point? Wouldn't be better to just not use shallow clone on AppVeyor if you want to have commit count?

**Comment by AniLeo** [comment]
I was told that using non shallowed clone would increase build time substantially.

But even not accounting for that, this approach only displays correct commit count for master builds, making it easier to distinguish master builds from non-master builds, which wouldn't happen if we always cloned from unshallowed clones.

**Comment by danilaml** [comment]
@AniLeo not build times. Just clone times. And in your PR you are doing exactly that, i.e. you fetch the whole thing anyway. The only benefit I see with approach is that PRs still use shallow clone.

**Comment by AniLeo** [comment]
But I'm just fetching the branches, not cloning them? 

I'll try finding better approach though, maybe defining depth only on pull request builds, thanks for input

**Comment by danilaml** [comment]
@AniLeo you still download all repo history. I.e. you make shallow clone unshallow. It is the same as just making full (unshallow) clone but in two steps instead of one.

**Comment by AniLeo** [comment]
Maybe I'll just remove shallowing and not include commit count on pull request builds, seems good. Thanks again

**Pull request merged**
