### PR TITLE
[Test] simd_builder ver. 2

### PR DESCRIPTION
**Pull request by Nekotekina**
Rewritten remaining intrinsic code in BufferUtils

### CODE REVIEW

**Comment by Augusto7743** [comment]
0.0.24-14148 huge slowdown, crash using all RAM and others issues #12661
https://github.com/RPCS3/rpcs3/issues/12661#issuecomment-1253428825

0.0.24-14148 Need for Speed Hot Pursuit [BLUS30566] text errors and crashing #12671
https://github.com/RPCS3/rpcs3/issues/12671#issuecomment-1253431201

**Comment by Augusto7743** [comment]
12603 breaking text ( Need for Speed Hot Pursuit [BLUS30566] ), doing wrong huge memory allocation crashing OS, slowdown in some games and cpu cores being used less of 50 %.

**Comment by Nekotekina** [comment]
For regressions spotted in this PR, test #12624 fixup

**Comment by Augusto7743** [comment]
PR 12700 fix this PR.
Not more huge slowdown, wrong memory allocation and text issues.

**Pull request merged**
