### PR TITLE
Update MVK to 1.2.4 for Vulkan SDK 1.3.250

### PR DESCRIPTION
**Pull request by shinra-electric**
[Release notes](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.4): 

- Add support for extensions:
    - VK_KHR_map_memory2
- Deprecate the obsolete and non-standard VK_MVK_moltenvk extension.
    - Add mvk_config.h, mvk_private_api.h, and mvk_deprecated_api.h, and deprecate vk_mvk_moltenvk.h.
- Support BC compression on iOS/tvOS where available (iOS/tvOS 16.4 and above and supported by the GPU).
- Support separate depth and stencil attachments during dynamic rendering.
- Fix memory leak when waiting on timeline semaphores.
- Fix race condition when updating values in VkPastPresentationTimingGOOGLE, and ensure swapchain image presented time is always populated when requested.
- Report error, but do not fail on request for timestamp query pool that is too large for MTLCounterSampleBuffer, and fall back to emulation via CPU timestamps.
- Ensure shaders that use PhysicalStorageBufferAddresses encode the use of the associated MTLBuffer.
- Disable pipeline cache compression prior to macOS 10.15 and iOS/tvOS 13.0.
- Accumulate render stages when a resource is used by multiple descriptor bindings.
- Respect the bind point supplied to vkCmdBindDescriptorSets() / vkCmdPushDescriptorSets().
- Check if shader compiled before adding it to a pipeline, to avoid Metal validation error.
- Identify each unsupported device feature flag that the app attempts to enable.
- Populate deviceUUID from MTLDevice location and peer group info, which should be unique, and constant across OS reboots.
- Populate deviceLUID from MTLDevice.registryID.
- Avoid Metal validation warning when depth component swizzled away.
- Fix depth clamp and texture swizzle feature discovery on simulator builds.
- Advertise VK_KHR_depth_stencil_resolve extension on all devices.
- For correctness, set VkPhysicalDeviceLimits::lineWidthGranularity to 1.
- Improve GitHub CI production of binary artifacts on submission and release.
- Update dependency libraries to match Vulkan SDK 1.3.250.
- Update to latest SPIRV-Cross:
    - MSL: Fix for argument buffer index compare when invalid.
    - MSL: Fix dref lod workaround on combined texture/samplers.
    - MSL: Do not override variable name with v_ identifier.
    - MSL: Use name_id consistently in argument declaration.
    - MSL: Don't hit array copy path for pointer to array.
    - MSL: Use templated array type when emitting BDA to arrays.

### CODE REVIEW

**Comment by solarmystic** [comment]
This should probably be tested a bit more by people with M1/Apple users for regressions.

The good people from ryujinx did the same but had to revert due to regressions in some games after updating MVK on their end to 1.2.3 with no apparent benefits whatsoever. 

https://github.com/Ryujinx/Ryujinx/wiki/Changelog
image

**Comment by shinra-electric** [comment]
It's slightly different, because Ryujinx were updating from 1.2.0 to 1.2.3. There were a lot of changes to MVK between those releases. 

We are updating from 1.2.3 to 1.2.4. Any errors they had (probably) don't apply here. 

But yes, people should test a bit first. The x64 CI build works fine on my M1, I haven't built on Arm yet, waiting for Homebrew to post the update (too lazy to build MVK myself).

**Comment by AniLeo** [comment]
Please check with Skate 3, which uses occlusion queries and I think it's already broken in current master with 1.2.3, might be a regression from MoltenVK as well

**Comment by shinra-electric** [comment]
No change in Skate 3. 

The regression there is supposedly caused by #12020 on June 2022 though, not anything related to updating MVK. (Could always be possible it introduced a fix with 1.2.4, but it looks like it didn't).

**Comment by kd-11** [comment]
> No change in Skate 3.
> 
> The regression there is supposedly caused by #12020 on June 2022 though, not anything related to updating MVK. (Could always be possible it introduced a fix with 1.2.4, but it looks like it didn't).

My biggest blocker has been getting a functional dev environment for x64 on M1 is pretty bad because I often need to nuke the entire build directory from time to time and macOS updates broke my old setup. I have an idea what's causing the glitch, just need some time to start a new dev env from scratch.
Or maybe I can just use cirrus CI for now.

**Pull request merged**
