### PR TITLE
Relax /dev_bdvd mounting requirements

### PR DESCRIPTION
**Pull request by Nekotekina**
Allow some PSN games with DG category to boot

### CODE REVIEW

**Comment by Nekotekina** [comment]
Nope, needs more fixes.

**Comment by Megamouse** [comment]
Looks like this fixes #3774

**Comment by sirdanielk** [comment]
Nice addition. No neeed to manually specify bdvd folder, COJ BIB is intro

**Comment by Zangetsu38** [comment]
broken Motorstorm Pacific rift boot with second commit on this PR: 
>Improve boot dir access
Add Emu.GetDir() method

log with broken
[RPCS3 broken.log.gz](https://github.com/RPCS3/rpcs3/files/1801319/RPCS3.broken.log.gz)
and log before this commit
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1801321/RPCS3.log.gz)

**Pull request merged**
