### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by hcorion** [comment]
This is...
...just...
AMAZING!
All of the problems are gone!
1942: Joint Strike Demo runs at 60fps no problems, 
Terraria 60 fps no problems.

**Comment by rcaridade145** [comment]
YAY

**Comment by ExE-Boss** [comment]
Once confirmed, you should add “Fixes #2507, fixes #2516 and fixes #2578” to the main text as per [Closing issues via commit messages](http://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by hcorion** [comment]
@ExE-Boss #2516 hasn't been fixed, the issue still occurs.

**Pull request merged**
