### PR TITLE
rsx: Fix uncaught depth-func changes

### PR DESCRIPTION
**Pull request by kd-11**
- Depth func of always or never usually disqualifies depth testing. Invalidate contested surfaces when depth func is changed.

Fixes https://github.com/RPCS3/rpcs3/issues/8668
Fixes https://github.com/RPCS3/rpcs3/issues/8619
Fixes https://github.com/RPCS3/rpcs3/issues/8740

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
KH2 regression is now fixed.
image
image

**Comment by MarioSonic2987** [comment]
One Piece: Unlimited World Red regression is fixed, similar to KH2. Fire was visible through everything.
**Before**:
image
**After**:
image

**Comment by dyno0** [comment]
Fixes #8619 also.

**Comment by MsDarkLow** [comment]
Yakuza 1&2 HD no longer has blurry scenes
Before:
OLD

After:
PR

**Comment by Josivan88** [comment]
Call of duty Black ops 2 now render something! no more acid trip. gui text still broken btw

BO 2 1

BO 2 2

**Pull request merged**
