### PR TITLE
rsx: Fixups and improvements

### PR DESCRIPTION
**Pull request by kd-11**
- Rewrite index buffer base offsets. Preserves use of u16 index buffers for consistency and reduced memory footprint.
- Partial revert of a change in fbo_fixes PR affecting async shaders.
- Fix Red-Blue color inversion when using OpenGL (old regression)
- Avoid potential deadlock in fifoctrl
- Reimplement alpha-to-coverage transparency with a better approximation technique
- Rewrite vertex attribute divisor logic
- Misc spec compliance and typo fixes

### CODE REVIEW

**Comment by uaqlover** [comment]
where i can download the branch

**Comment by digitaldude555** [comment]
Click green checkmark and and click details

**Comment by stride21** [comment]
Can confirm that The Last of Us, Battlefield: Bad Company and Uncharted 3 no longer have issues with Async Shader Compiler.

**Comment by legend800** [comment]
Tested a bunch of games and didn't see any improvements or regressions.

This regression from FBO fixes PR is still active:
https://github.com/RPCS3/rpcs3/issues/4949

Tested all of these titles (disregard the general emu notes - not related to PR - but maybe of some interest):
•	*(d)Time Crisis 4 Settings: WCB | Note: Input lag sometimes (broken)
•	*(d)Deadstorm Pirates(+install data) Settings: WCB | Note: Minor transparent textures (logged)
•	Backbreaker Vengeance(v1.0-c00)[WCB(field cache), Blit(fixes textures on VK)] 22 fps on 5-2 (need 25 min) | Settings: Scaling 100%, SPU=2 | Note: Missing crowd (Vk broken-logged, SPU LLVM broken-logged)
•	(d)Captain America(3D)[Stretch, Strict (Cap shading)] – Slow(~20 fps on curr. lvl)
•	(d)Conan – missing textures (logged) (hangs during loads 50%-logged)
•	(d)GOW3[Accurate Getllar?} ~20 fps, minor gfx issues, little unstable
•	(d)MotorStorm(2-revenge,devil)[WCB] – gfx issues
•	NFL Blitz(v1.0) – Exploding vertices(logged)| Settings: SPU=2
•	Ridge Racer 7(3D)(25-special events) – Tree flickering (logged)
•	(d)Splatterhouse(1-surv.)(eur)PPU mem crashes (PPU Inter. for areas like start of chapters-but 15 fps - logged)
•	Wipeout HD(1-Fury)(v2.51)[WCB for bloom] Little slow (~25 at start on 1st lvl, usually 60 after 1st laps, 40 on lows)
•	Force Unleashed 2 – Hangs on load
•	Split Second [WCB (fixes bg)] – ~8 fps, Bad gfx
•	Double Dragon Neon – Broken gfx (background-logged)

**Comment by altiereslima** [comment]
> onde eu posso baixar o ramo

https://ci.appveyor.com/api/buildjobs/28rjdr7jxodr872r/artifacts/xenia-d3d12.zip

**Comment by altiereslima** [comment]
> where i can download the branch
https://ci.appveyor.com/api/buildjobs/b75pdk3x8a2k5h27/artifacts/rpcs3-v0.0.5-644c4360_win64.7z

**Comment by MarioSonic2987** [comment]
Improves foliage rendering in Red Dead Redemption.

**Before**:
image
image

**After**:
image
image

**Comment by stride21** [comment]
Infamous 2 regression is now fixed with the recent commit.

**Comment by legend800** [comment]
Whoa, did some perf testing with the latest build and I gained close to +3 fps across several games. Nice work!

**Comment by legend800** [comment]
Wow, you just made NFL Blitz FULLY playable by fixing this:
https://github.com/RPCS3/rpcs3/issues/5132

2019-01-18 23_10_42-fps_ 60 00 _ vulkan _ 0 0 5-ad7f3fa2-kd-11_master _ nfl blitz npub30665

2019-01-18 23_10_27-fps_ 60 04 _ vulkan _ 0 0 5-ad7f3fa2-kd-11_master _ nfl blitz npub30665

**Comment by MarioSonic2987** [comment]
Fixes some missing models in this place (hard to see) and tree's shadows are rendered for the first time.

**Before**:
image

**After**:
image

**Comment by legend800** [comment]
Jesus, this is getting ridiculous now. You fixed the background of Double Dragon Neon finally. This PR is unreal. 

2019-01-18 23_38_11-fps_ 59 95 _ vulkan _ 0 0 5-ad7f3fa2-kd-11_master _ double dragon neon npub3076

**Comment by Xcedf** [comment]
Confirm GoWIII exploding vertices particles fixed
Before:

After:

**Comment by digitaldude555** [comment]
screenshot_1488
screenshot 1718
UI fixed!

**Comment by kd-11** [comment]
The last commit needs a ton of work, a lot more than I initially anticipated, so this has been relegated to WIP while I finish the implementation. Should be ready in a few more days.

**Comment by digitaldude555** [comment]
screenshot 1729
Displays crystals for the first time.
screenshot 1721
No more exploding vertices.

**Comment by Xcedf** [comment]
MotorStorm Pacific Rift, environment random exploding verices fixed

**Comment by Illynir** [comment]
Ni no kuni works perfectly for me, try of remove the shader cache.

**Comment by frymezim** [comment]
@Illynir 
Your right, it's weird though I always move hdd_dev0 to a newer build with a fresh directory just to make sure that I won't have shader cache issue.

**Comment by Web1017** [comment]
I am not sure if this issue is related with this PR fix implementation, though this is visible in the Master build as well. The Simpsons Game has this issue when using a specific special skill the screen texture just breaks and goes dark.

capture-error1


E {RSX [0x01a3470]} RSX: Blit request denied because the destination region does not fit!

This error is printed every time the issue occurs.

**Comment by Asinin3** [comment]
@Web1017 If the same issue exists in master then it's unrelated and shouldn't be posted in the comments of this Pull Request

**Comment by Xcedf** [comment]
It's not a regression it exists in master as well

**Comment by uaqlover** [comment]
fix NASCAR The Game: Inside Line [BLUS30932] and little bit performance

before

fps_ 3 92 _ opengl _ 0 0 5-7678 _ nascar the game_ inside line blus30932 1_21_2019 1_04_35 am

after

fps_ 29 98 _ opengl _ 0 0 5-b96edb69-kd-11_master _ nascar the game_ inside line blus30932 1_21_2019 12_59_29 am

**Comment by MarioSonic2987** [comment]
MCLA still has the improvements from this PR:
image

**Comment by stride21** [comment]
Battlefield: Bad Company and Ratchet and Clank Future: Tools of Destruction regressions are now fixed.

**Comment by legend800** [comment]
@stride21 What improvements did Motorstorm see specifically? Screenshot?

Tested new build. All positive changes remained with no regressions:  ~3+ fps, GOW effects fixed, NFL Blitz playable, DD neon bg fix

Wipeout HD regression fixed also.

**Comment by kd-11** [comment]
Cleaned up and rebased, hopefully everything is still looking good.

**Comment by MSuih** [comment]
Latest version fixes X-Men Origins: Wolverine issue I reported earlier.

**Comment by stride21** [comment]
@legend800 vehicles leave tire trials in the dirt, screenshot was posted above 4 days ago.

**Comment by stride21** [comment]
Recent commit regressed Journey 
Previously in this PR:
journey early in pr
Recent commit in this PR:
pr journey
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2784231/RPCS3.log.gz)

**Comment by Aurez** [comment]
Phantom Breaker : Extra (BLJM61098) 

Stages are black with this PR
sans titre

Master
sans titre1

**Comment by thx4ever** [comment]
I have one problem that master doesnt have in the Ghost Recon Advance Warfighter 2 around models

image

U see those yelow/white things around models, its possible to fix that? This problem don`t occurs in master

**Comment by kd-11** [comment]
@Aurez Provide an RSX replay capture.

**Comment by kd-11** [comment]
@thx4ever Provide RSX replay capture.

**Comment by thx4ever** [comment]
Done

**Comment by Aurez** [comment]
Done also :)

**Comment by kd-11** [comment]
Retest.

**Comment by Aurez** [comment]
It was quick !!
image1
Fixed: Nice job!

**Comment by thx4ever** [comment]
My problem stills there 

image

**Comment by stride21** [comment]
Journey regression is now fixed.
fixed

**Comment by thx4ever** [comment]
I tested RED DEAD REDEMPTION with this PR, and it dont get any further anymore, it stop emulator with this message: F {RSX [0x0148a24]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkoverlays.h:229), i don`t have tryed with opengl but vulkan it stops
Intel i7 7700
Nvidia Geforce GTX 1050
8GB RAM DDR4

**Comment by Xcedf** [comment]
@thx4ever flickerig polygon problem with Ghost Recon is also presented on master, and older builds, nothing to do with this PR

**Comment by Kravickas** [comment]
**GTA V** 
OGL
Master: ok
PR: black screen
new error `E {RSX [0x00452f0]} RSX: OOM Error: Ring buffer was likely being used without notify() being called`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2788577/RPCS3.log.gz)
[GTA V 5565.zip](https://github.com/RPCS3/rpcs3/files/2788584/GTA.V.5565.zip)

VK is ok

**Comment by MarioSonic2987** [comment]
Fixes color regression caused by #5146 with OpenGL in Worms Crazy Golf.

image

image

**Comment by Kravickas** [comment]
GTA V OGL fixed

**Comment by keem85** [comment]
Ahh cool. Will that fifo fix potentially fix the Diablo 3 freeze issue?

**Comment by tesla2105** [comment]
@kd-11 Is it possible to fix the double speed issue in "Tales of" games (Xillia 1&2 and Graces F)? They should run 60fps in battles and menus, and 30fps everywhere else. I'm asking this, because they play really fast on this emulator. If you can fix the double speed issue, and maybe crash issue after instaling the DLC, it would be perfect.

**Comment by arcadee1977** [comment]
GOD OF WAR 3 random freeze , display:
E {RSX [0x06fe380]} RSX: FIFO error: possible desync event x "number Unlimited increase"

**Pull request merged**
