### PR TITLE
Better evdev joystick axis scaling

### LINKED ISSUE #3179: [Linux/evdev] XBox One S Controller triggers do not work
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x45e product 0x2ea version 0x301
Input device name: "Microsoft X-Box One S pad"

Connected via USB cable.

Every button works and is correctly mapped, except for the triggers, who do absolutely nothing. Creating a config file per RPCS3 evdev tutorial and setting "Z axis triggers" to true or false makes no difference.

Evtest shows proper trigger behavior, sending events as outlined below.

Left trigger:
Event code 2 (ABS_Z)
      Value      0
      Min        0
      Max     1023

Right trigger:
Event code 5 (ABS_RZ)
      Value      0
      Min        0
      Max     1023

### PR DESCRIPTION
**Pull request by kirbyfan64**
Fixes #3179 and removes the now-unnecessary *Axis scaling* option. @HollowSoldier Try this one to see if it fixes your problems.

### CODE REVIEW

**Comment by HollowSoldier** [comment]
Scaling is fine now, but the trigger is only considered to be "pulled" if it's 100% pulled. Notice the green rectangle:

Halfway pulled:
half


Fully pulled:
full

**Comment by kirbyfan64** [comment]
@HollowSoldier Ok, it should be working now.

**Comment by HollowSoldier** [comment]
Yes, it's working perfect now, identical to xinput behavior.

**Comment by toccata10** [comment]
@kirbyfan64 : not exactly related but if you're still working on improving the evdev thing, could it be possible to add these options to the config file:
- Dpad to Left Analog
- Dpad to Right Analog
- Left Analog to Dpad
- Right Analog to Dpad
That would improve flexibility for custom sticks and even for standard sticks (ex: on chaos code which is a fighting game, you can only use the dpad. It makes quater circles or dragon punch movements very difficult). Thanks.

**Comment by kirbyfan64** [comment]
@toccata10 That's already covered in #3181.

**Comment by toccata10** [comment]
These parameters are not taken into account anymore:
Reverse left stick X axis: true
Reverse left stick Y axis: false
Maybe it's because this disappeared:
` if (revaxis[axis])
-                    {
-                        value = 256 - value;
-                    }
`
Can't be sure if it's your commit or the one from hcorion (with squircle), but I added
Squircle Joysticks: false
to my config_linuxjoystick.yml file and: no change.
I tried to download older AppImage builds, but this page https://rpcs3.net/cdn/builds/ gives me a "forbidden access". I can't see how to get older builds.

**Comment by kirbyfan64** [comment]
*Ack*, that's my fault. I'll fix it later today. Sorry!

**Pull request merged**
