### PR TITLE
Vulkan: use pkg-config instead of checking for Linux

### PR DESCRIPTION
**Pull request by myfreeweb**
Makes Vulkan optional on Linux / makes it possible on FreeBSD. When the `USE_VULKAN` flag is on, finds the Vulkan loader using pkg-config, and uses it if it's been found.

Also `libX11` is now linked on any non-Apple Unix. It was necessary on FreeBSD.

screen_2017-09-10-20 59 19

^^^ my FreeBSD desktop running Crazy Taxi, with RADV/amdgpu. ([drm-next-kmod](https://www.freshports.org/graphics/drm-next-kmod), ports patches: [Vulkan Mesa drivers](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221540) + [Vulkan loader](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222175), hopefully will be merged soon :D)

### CODE REVIEW

**Comment by hcorion** [comment]
(from Travis CI)
```
-- checking for module 'vulkan'
--   package 'vulkan' not found
```
This means that the AppImage won't have Vulkan, which we need to have. Also, build fails at
```
Linking CXX executable ../bin/rpcs3
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
/usr/bin/ld: cannot find -liconv
```
for both clang and GCC.

**Comment by myfreeweb** [comment]
Huh, weird… Oh! [The SDK did not provide a pkg-config file until 1.0.46.0](https://vulkan.lunarg.com/doc/sdk/1.0.46.0/linux/release_notes-1.0.html)!

**Comment by hcorion** [comment]
Dang, could you add an additional cmake flag to force use vulkan?

**Comment by myfreeweb** [comment]
Even better: I can make (heh) CMake find Vulkan anyway :)

**Comment by kd-11** [comment]
Also add a warning message if vulkan development package is not found. Should help avoid invalid tickets cropping up if anything goes wrong or the users forget to install/update vulkan development packages.

**Comment by myfreeweb** [comment]
Should be good now!

**Comment by kd-11** [comment]
Looks good. I'll leave it open for other testers in the meantime.

**Comment by hcorion** [comment]
Nice job! Glad to see more users on BSD!

**Comment by danilaml** [comment]
Why not use official FindVulkan module bundled with CMake (not sure which version though)?

At the very least you can just copy https://github.com/Kitware/CMake/blob/master/Modules/FindVulkan.cmake

**Comment by myfreeweb** [comment]
@danilaml it's not very good, it does not use pkg-config at all.

**Comment by hcorion** [comment]
It appears to have been added in 3.9.1, so we would need to bump the minimum cmake version number as well. And because Ubuntu 16.10 doesn't ship with that new of a cmake, they would have to install a custom version of cmake...
Just to detect vulkan, not worth it IMO.

**Pull request merged**
