### PR TITLE
BUILD: Refactor 7zlib

### PR DESCRIPTION
**Pull request by p01arst0rm**
re-worked 7z files into their own directory structure

### CODE REVIEW

**Comment by p01arst0rm** [comment]
cc @hcorion

**Comment by hcorion** [comment]
Why are all the files marked as changed? Did you change their encoding or line endings or something?

**Comment by p01arst0rm** [comment]
> Why are all the 7z files marked as changed? Did you change their encoding or line endings or something?

shouldn't have, the files were only relocated. Maybe something weird with git?

**Comment by p01arst0rm** [comment]
looks like git did something weird with line endings. fixed now :)

**Comment by Megamouse** [comment]
you probably used cut and paste instead of git mv

**Review by hcorion — APPROVED** [review]
LGTM 👍

**Pull request merged**
