### PR TITLE
Stub NpSns fix #4075 and fix regression vk/ogl G8B8

### LINKED ISSUE #4075: Mortal Kombat (Demo) - "Unimplemented"
Black screen and:
> ·F 0:05:01.279828 {PPU[0x1000000] Thread (main_thread) [0x014ad20c]} class std::runtime_error thrown: Unimplemented
> (in file Emu\Cell\Modules\sceNpSns.cpp:156)

[Mortal_Kombat_(Demo).txt](https://github.com/RPCS3/rpcs3/files/1640748/Mortal_Kombat_.Demo.txt)

### PR DESCRIPTION
**Pull request by Zangetsu38**
hle: Stub function Unimplemented in NpSns for fix https://github.com/RPCS3/rpcs3/issues/4075
Mortal kombat move to ingame now.

Fix regression with texture format G8B8, Fix Texte corrupted in Sackboy anhd maybe other.

### CODE REVIEW

**Comment by Megamouse** [comment]
shouldn't they be UNIMPLEMENTED_FUNC(sceNpSns); ?

**Comment by Zangetsu38** [comment]
I have just used same code already here

**Comment by Megamouse** [comment]
afaik the todo is more or less reserved for functions with known args.
But who knows xD

**Comment by Zangetsu38** [comment]
i have changed like you say, but finnaly it is same for code

**Comment by Zangetsu38** [comment]
Rebased, and have added fix for G8B8 regression in texture format for vk/ogl, aproved by @kd-11

**Comment by nsomniac281** [comment]
I would also like to say that Final fantasy X HD goes in game now, plays up until just after the movie where Tidus sees sin for the first time and then freezes with a 0x40 stop error

**Comment by kiraduwang** [comment]
Is it possible to have llvm 6 and the Farseer SPU build together. Wouldn't that be peak?

**Comment by AniLeo** [comment]
Don't spam PRs

**Pull request merged**
