### PR TITLE
Add callbacks for some modules

### PR DESCRIPTION
**Pull request by scribam**
Avoid games to freeze in specific cases, tested with samples and games.

Games tested:
- [X] Hatsune Miku: Project DIVA F (Studio > Photo Studio > Background Settings > XMB (TM) Photos)

### CODE REVIEW

**Comment by AniLeo** [comment]
Your commit duplicates your cellSearch PR, it's better if you remove it from this branch and leave it on the other separate PR

**Comment by scribam** [comment]
The cellSearch PR is more likely to be merge first. Once done, I will clean this PR ;)

**Comment by scribam** [comment]
cellSearch removed from the list of commits as merged
cellRec / cellVideoExport / cellVideoUpload moved to a smaller PR, to make code reviews easier

**Comment by Megamouse** [comment]
can you rebase?
I want to test a possible regression with the recent cellsurmixer commit

**Comment by scribam** [comment]
cellPhotoExport moved to a smaller PR

**Comment by Zangetsu38** [comment]
need rebase

**Comment by toccata10** [comment]
Cool for JoJo's Bizarre Adventure: All Star Battle: looks like the game will go from ingame to playable, as versus no longer freezes. It now plays quite well.

**Comment by scribam** [comment]
cellMusic moved to a smaller PR for review.

Thanks for the feedback, toccata10.

**Comment by Xcedf** [comment]
This PR makes MGS: Ground Zeroes go from Nothing to Intro
Game has some serious graphical issues and freezes randomly
was able to go ingame once

**Comment by Kravickas** [comment]
Only change in FN Champion
Master
`U {PPU[0x1000012] Thread (LoopSimulation) [0x01b61190]} cellMusicDecode TODO: cellMusicDecodeInitialize2`
PR
`U {PPU[0x1000012] Thread (LoopSimulation) [0x01b61190]} cellMusicDecode TODO: cellMusicDecodeInitialize2(mode=0x0, container=0x1, spuPriority=0x12, func=*0x16ce508, userData=*0x0, speed=0x2, bufsize=0xf0000)`

**Comment by Kravickas** [comment]
FN Champion

code above is same but new line of code after last commit
`U {PPU[0x1000018] Thread (UserMusicFramework::DecodeContr) [0x01b61e50]} cellSearch TODO: cellSearchStartListSearch(type=0x9, sortOrder=0x1, outSearchId=*0xd0151c10)`

**Comment by scribam** [comment]
cellMusicDecode moved to a smaller PR for review.

**Pull request merged**
