### PR TITLE
Rename CallAfter to CallFromMainThread

### PR DESCRIPTION
**Pull request by Megamouse**

### CODE REVIEW

**Comment by elad335** [comment]
What about AssignToMainThread ?

**Comment by Nekotekina** [comment]
SendFunctionObjectToMainThreadEventQueueWithoutWaitingForCompletionAndTrackEmulationStatePredicate

**Comment by Nekotekina** [comment]
I mean who cares. It was an idiom in wxWidgets code.

**Comment by Megamouse** [comment]
I think my choice of words conveys the intention while still keeping some resemblance to the old name

**Comment by Megamouse** [comment]
I would like to wait with this until after the exit PR.
It would mess up my current review status

**Comment by Megamouse** [comment]
K. I'll test tomorrow.

**Comment by Megamouse** [comment]
I'll merge if there are no objections

**Pull request merged**
