### PR TITLE
Fix ".rsx_image" section block, fix page flags

### LINKED ISSUE #5812: Final Fantasy XIII series cannot load to intro after #5677
Final Fantasy XIII series cannot load to intro after #5677 
it always shows the following error

E {PPU[0x1000000] Thread (main_thread) [0x014cff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
E {RSX [0x1ff0b600]} RSX: FIFO error: possible desync event x10357

rpcs3-v0.0.6-7827-e38b7aee_win64
CPU-Intel I7-2600
RAM-DDR3-1333Mhz
GPU-RX 570 4Gb
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3061620/RPCS3.log.zip)

### PR DESCRIPTION
**Pull request by elad335**
This fixes the following:
* Fixes vm::user64 base address. see https://github.com/RPCS3/rpcs3/pull/4975#issuecomment-412866301
* Fixes ".rsx_image" section page flags.

Fixes #5812, hopefully this would be the last time vm addresses are touched.
First commit ensures lv2_dir fd would be closed once at max.

### CODE REVIEW

**Comment by maximilian578** [comment]
as of 0712a04cc METAL GEAR SOLID 4 GUNS OF THE PATRIOTS [BLES00246] (PPU LLVM + Asmjit) loads but freezes with 0 fps on OpenGL and throws `F {PPU[0x100001e] Thread (OVERLAY_LOAD) [0x00011954]} class std::runtime_error thrown: vm::falloc() failed (addr=0x30000000, memsz=0x3c4960)` on Vulkan.
On interpreters it throws mentioned fatal error on both graphical backends. So #3115 is still present.

[RPCS3.log_opengl.gz](https://github.com/RPCS3/rpcs3/files/3069533/RPCS3.log_opengl.gz)
[RPCS3.log_vulkan.gz](https://github.com/RPCS3/rpcs3/files/3069534/RPCS3.log_vulkan.gz)
[RPCS3.log_interpreter_opengl.gz](https://github.com/RPCS3/rpcs3/files/3069539/RPCS3.log_interpreter_opengl.gz)
[RPCS3.log_interpreter_vulkan.gz](https://github.com/RPCS3/rpcs3/files/3069540/RPCS3.log_interpreter_vulkan.gz)

**Comment by darkdragonz12** [comment]
fix

GOD OF WAR 3 FIX :D

**Comment by Snakegodeater** [comment]
Still getting this error with the latest build ! F {PPU[0x100001e] Thread (OVERLAY_LOAD) [0x00013220]} class std::runtime_error thrown: vm::falloc() failed (addr=0x30000000, memsz=0x3afe80)

**Comment by Xcedf** [comment]
With this PR and readding
std::make_shared<block_t>(0x30000000, 0x10000000), // main extend
i've got this

Unfortunately game still goes to a blackscreen after installing
Log shows
E {PPU[0x1000023] Thread (STGDEC) [0x00031964]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000025] Thread (OVERLAY_LOAD) [0x0001180c]} 'sys_overlay_load_module_by_fd' failed with 0x80010007 : CELL_ENOEXEC, Not an ELF [1]
E {PPU[0x1000025] Thread (OVERLAY_LOAD) [0x00011954]} 'sys_overlay_load_module' failed with 0x80010007 : CELL_ENOEXEC, Invalid stream or file not found [1]
E {PPU[0x1000026] Thread (STGDEC) [0x00031964]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]

**Comment by Dravonic** [comment]
MGS4 kind of goes in menu with these changes, however it also needs [this line back](https://github.com/RPCS3/rpcs3/pull/4007#issuecomment-418549394) which was removed in [this commit](https://github.com/RPCS3/rpcs3/commit/449888b9db8349d7c008008858e0321334fcf6b3). 

It's able to complete the install process and begins to show a broken main menu, but then the screen goes black. 

Unfortunately I have no idea what I'm doing, so I can't help any further than that.

**Comment by fdemian** [comment]
This is great work, thanks!

I can confirm that adding the line that Dravonic talks about fixes MGS4. Without that line, the game crashes. 

After booting, the game attempts to copy the game into the console's HDD. Once that is 
finished I get the intro screen, press start, and then...black. 

There appears to be a few glitches, though.

loading_screen

Anyway, here's the log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3076830/RPCS3.log.gz)

**Comment by vieiraa** [comment]
I was able to get MGS4 Demo [NPUB90176] in game using OpenGL, but it only shows some very broken graphics.

Captura de tela de 2019-04-23 22-10-18

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3110163/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Full game can also render for a split second even in Vulkan, something is still very wrong with it anyways

**Pull request closed without merging**
