### PR TITLE
XAudio2.7 bug workaround

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by danilaml** [comment]
Is it really XAudio bug though? It's more like rpcs3 submits more samples than XAudio can handle at the moment. I think It was reliably reproducible in some games after pausing for a long time and then unpausing.

**Comment by Nekotekina** [comment]
@danilaml I don't recall any limitation for the number of buffers you can submit. And 2.8+ seems OK in the same situation,

**Comment by danilaml** [comment]
@Nekotekina there was a `#define` with max allowed buffers.

**Comment by Nekotekina** [comment]
It's obvious that the queue has some internal size. But it still doesn't mean I can't submit more. Of course, they may be discarded in this case. 2.7 is wrong because it crashes without even trying to recover (it should be easy to detect internally rather than explicitly checking it as I did). It could theoretically return the error code, but I don't see anything like this specified. IXAudio2SourceVoice::SubmitSourceBuffer method doesn't say much too. That's why I assume that discarding excessive buffers is right.

**Pull request merged**
