### PR TITLE
Trophy fixes

### PR DESCRIPTION
**Pull request by Farseer2**
Only trophy installed is called when the trophies are already in place.
Should improve some games, but I only noticed Handball 17

### CODE REVIEW

**Comment by legend800** [comment]
What behavior does this affect exactly, for testing?

**Comment by Farseer2** [comment]
Games that would fail because of trophies (Like NBA2k14) might work now.
Probably not access violations (Though possible), just errors about trophies

**Comment by Asinin3** [comment]
This caused Akiba's Trip to crash RPCS3 usually the game would just give a fatal error but it wouldn't crash the emulator.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2183253/RPCS3.zip)

NBA 2k15 Also does not fail on the trophy error anymore and almost goes ingame!
image
I'm pretty sure NBA 2K14 works now as well but I don't have it to check.

**Comment by Hasster1** [comment]
Are you going to merge this pr, or not?

**Comment by legend800** [comment]
Good news and bad news:

Good news is Peggle and other PopCap games can now boot the full versions! Been waiting a long time for this. Thanks!

Bad news: All the Backbreaker games are broken. https://github.com/RPCS3/rpcs3/issues/5056

**Comment by Farseer2** [comment]
I'll check it out soon, no worries

**Pull request merged**
