### PR TITLE
Adds VID/PID for Guitar Hero guitar & drum

### PR DESCRIPTION
**Pull request by RipleyTom**
Fixes a little cellPad bug and adds VID/PID for Guitar Hero guitar & drum.
It should hopefully make all Guitar Hero games work with the guitar/drum option(tested on Guitar Hero World Tour).

### CODE REVIEW

**Comment by Dokman** [comment]
@RipleyTom you will add support for Logitech g27 steering wheel for gran turismo? 😮

**Comment by uaqlover** [comment]
Nice Work 

thanks a lot @RipleyTom

**Comment by Syst3mSh0ck** [comment]
@uaqlover Not really the place for this but the Logitech G27 does support Gran Turismo 5 on the PS3 so it was worth mentioning if someone wants to reverse engineer this at some point.

Compat table: https://support.logitech.com/en_us/article/8009?product=a0qi00000069vCPAAY

Now on topic - Nice work on Guitar Hero! 👍

**Comment by AniLeo** [comment]
Looks good, in the future if someone finds IDs for other peripherals, a dropdown is probably a good idea to add on the controller settings allowing the user to change between peripherals

**Pull request merged**
