### PR TITLE
[WIP] SPU PIC support

### PR DESCRIPTION
**Pull request by Nekotekina**
Settings:
* Block size: Safe or Mega
* SPU LLVM

### CODE REVIEW

**Comment by isJuhn** [comment]
Spider-Man Shattered Dimensions [BLES00946] stops compiling spu code just after boot, rpcs3 stops responding if you mess with ui a bit. on second boot spu compilation stops on 3/100 spu programs

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3166730/RPCS3.log)
[spu.log](https://github.com/RPCS3/rpcs3/files/3166735/spu.log)

**Comment by legend800** [comment]
Nothing but fatals or freezes during SPU compile on my games.

**Comment by Kravickas** [comment]
I had good experience with  LLVM Mega in NHL 16

**Comment by isJuhn** [comment]
Spider-Man Shattered Dimensions [BLES00946] now boots and see a huge improvement in terms of spu compilation. nearly all spu programs are reused now. in master 30 seconds of gameplay used to generate 11k spu programs, with 2k unique hashes. now it's 2113 programs and 2054 unique hashes from the same playtime.

**Comment by ruipin** [comment]
RDR now generates 7k SPU programs in the same playtime it used to generate about 100k. Stutter is virtually gone when using SPU LLVM.

TLOU has regressed (might be related to the previous LLVM PR though), and no longer gets past the loading screen. UC1 also no longer manages to get to menu. If I do not use Safe, all these games I mentioned seem to crash immediately at startup.

**Comment by MsDarkLow** [comment]
Fist of the North Star: Ken's Rage - DEMO [NPEB90285]
SPU LLVM - Safe
Got a massive improvement, from basically Infinite SPU cache down to 5k.
There is a lot less stutter. 
Doing one of the "most intensive attacks" it went from an avg of 11fps to 25-30FPS! No longer stuttering whenever an action happens.

**Comment by FultonBoss** [comment]
Metal Gear Rising Revenganvce got massive improvement with SPU LLVM safe, went from 100k+ SPU cache  to 7k
Also better framerate but still suffers from FIFO desync event eventually making the game hang

**Comment by legend800** [comment]
Splatterhouse is finally playable on the SPU LLVM! No more constant cache building! Nice work. I think this PR fixes this then: https://github.com/RPCS3/rpcs3/issues/5843

2019-05-10 19_31_30-Window

Unfortunately, Splatterhouse still gets PPU mem errors after a few mins I found out, just a lot less than ASMJIT. This is being tracked separately here: https://github.com/RPCS3/rpcs3/issues/5837



[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3168541/RPCS3.log)

**Comment by MSuih** [comment]
For some reason I can only launch RDR with empty SPU cache on this PR. Attempting to launch with SPU cache will just cause the game to exit and RPCS3 will immidiately close afterwards, but if cache is cleared first then it will boot and go ingame normally.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3168561/RPCS3.log)

**Comment by arabek** [comment]
Tried out RDR and couldn reproduce it. Works from cold cache and after emulator restart with a primed cache of 3737 spu units compiled. LLVM block size Mega.

**Comment by MSuih** [comment]
Now that I tested this further I think it's tied to size of SPU cache. I managed to boot at 3k cache but then I played a bit further and on next launch the immidiate exit happened again. Tested this a couple of times and got similar results each time

Mega crashes the game for me, but that happens on master as well.

**Comment by legend800** [comment]
Updated my post above with a quick pass through some titles, noting some that are broken now on this PR. I'll continue to update it with new commit pushes.

**Comment by MarioSonic2987** [comment]
Settings used: SPU LLVM in Safe mode.

| Game  | SPU Cache Before | SPU Cache After | Screenshot reference |
| ------------- | ------------- | ------------- | ------------- |
| Grand Theft Auto IV | 15k | 6k | [Screenshot](https://user-images.githubusercontent.com/20027681/57565917-1e43f600-73c6-11e9-8834-0598a43920c9.png) |
| Grand Theft Auto V | 31.5k (loading screen and still compiling) | 8.5k (ingame) | [Screenshot](https://user-images.githubusercontent.com/20027681/57565769-ab398000-73c3-11e9-92a5-a158eece1e76.png) |
| Midnight Club: Los Angeles - Complete Edition | ~23.5k | 4.5k | [Screenshot](https://user-images.githubusercontent.com/20027681/57565974-16388600-73c7-11e9-88d7-6eac0753f286.png) |
| One Piece: Pirate Warriors | ~38k (only in title screen and still compiling) | 5.5k (It no longer stutters when you attack or move and performance goes up to ~50 FPS in cutscenes and ~60 FPS in the first level.) | [Screenshot](https://user-images.githubusercontent.com/20027681/57566184-e8087580-73c9-11e9-8e63-00bb17d7516d.png) |
| Saints Row: The Third - The Full Package | 13k-14k (still compiling) | ~6k | [Screenshot](https://user-images.githubusercontent.com/20027681/57565932-767af800-73c6-11e9-9041-13caf35820d7.png) |

This post will be updated when games are found improved by these changes.

**Comment by danc2** [comment]
no sound in twisted metal BCUS98106 with SPU LLVM

**Comment by vsub** [comment]
RPCS3 auto closes when closing the game window:
Ar NoSurge
Atelier Shallie
Atelier Escha & Loggy
Ar Tonelico Quga
Persona 5

Eternal Sonata  - the game window auto closes after loading the shaders
Tales of Xillia 1\2 - Fatal Error while using ASMJIT(maybe this is what you mean by "ASMJIT don't work") and rpcs3 auto closes when closing the game window while using LLVM(maybe all games are affected by this)

**Comment by Nekotekina** [comment]
@vsub Try new commit. ASMJIT is currently just unsupported — it needs more work.

**Comment by MSuih** [comment]
Whatever that RDR safe mode issue was, it's now fixed with latest commit and I can load the game even with existing SPU cache. Mega mode still has some issues but that's not caused by this PR.

**Comment by vsub** [comment]
@Nekotekina Yes,all problems mentioned above are fixed and Eternal Sonata spu cache seems to be WAY better.
On master if I load a save at the first town and then the first possible save location and play the tutorial,the spu cache becomes above 100k but with this pr,it is less than 2k

And also the game runs a little fasted on this pr

**Comment by Xcedf** [comment]
RDR started new game, did some random moves 7,5k On Safe never had it on safe before, but on Mega begining of the game was about 35-40k, while Mega cache from whole game is ~59k
Metal Gear Revengeance Safe - 4,4k, was 55k on Mega just in the begining
Now for the bad things Mega hows fatal error window on every game with this PR
GoW 3, TloU, Infamous are stopped working on this PR

**Comment by Xcedf** [comment]
Yet i think Mega mode regression is a part of previous Giga PR

**Comment by Parthorisian** [comment]
WET(2009) - crash on load(before going to menu) [BLUS30403](https://i.imgur.com/nrqO8Qr.png) log
[WetRPCS3.zip](https://github.com/RPCS3/rpcs3/files/3169218/WetRPCS3.zip)

**Comment by legend800** [comment]
On the latest build, closing emu window no longer crashes emu (on Master). 

Several broken games on Master with SPU LLVM work again (Ridge Racer 7, HOTD4, Razing, Xmen, etc). 

However, Wipeout and Motorstorm Apocolypse are still unstable (even with cleared cache). 

Wipeout black screen upon entergameplay:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3169228/RPCS3.log.gz)

MS Apoc freezes loading menus:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3169230/RPCS3.log.gz)

**Comment by Ghostotakoi** [comment]
This might fix j-star victory versus

**Comment by Xcedf** [comment]
With recent fix of Mega mode
did more tests
Heavy Rain:
 Safe 4.5k   Mega 1.6k
RDR:
 Safe: 7.2k  Mega 3.7k
Metal Gear Revengeance:
 Safe: 4.4k   Mega 2.2k
Far Cry 2 anoter game with countless SPU cache
 Safe: 4.2k   Mega 1.9k
Some sane numbers after all

**Comment by Xcedf** [comment]
GoW 3, Uncharted games Infamous TLoU, it seems they are broken on safe mode only and working on Mega in this PR
I successfully ran Infamous demo on mega on this PR and on master i has ~55-60k on Mega just to go ingame on this PR it's 2,2k

**Comment by Xcedf** [comment]
Found anothe regression in this PR, in GoW3 on Mega level emu crashes after "Sony presents" intro before fmv intro, tested on Master before just to make sure this isn't anoter Giga PR regression and it works fine

**Comment by legend800** [comment]
GOW3 and GOWA both just black screen during boot screens with Safe, no cache. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3169794/RPCS3.log.gz)

**Comment by raveskirza** [comment]
Beyond Two Souls (Mega):

Master:
Menu - 12k SPU cache
Intro   - 28K 

PR:
Menu - 1.6K
Intro   -  5k

**Comment by EmulationChannel** [comment]
SharedScreenshot0
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3169978/RPCS3.log)

**Comment by Xcedf** [comment]
@legend800 GOWA works on Mega, you just need to run it a few times before it get to menu for me it took 2k cache

**Comment by mavethee** [comment]
Ratchet & Clank Tools of Destruction - Black screen and emulator closes itself.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3170008/RPCS3.log)
The Last Of Us - Crashes while compiling SPU cache.
image
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3170012/RPCS3.log)

**Comment by Exmach** [comment]
Gran turismo 6 - works in Mega but hang on building cache in Safe

**Comment by Xcedf** [comment]
@mavethee you have to boot TLoU several times before it load all required cache, the game has a lots of race conditions that's why it happens

**Comment by Leafnation** [comment]
image

**Comment by mavethee** [comment]
@Xcedf I know that, just didn't mention that.

**Comment by ruipin** [comment]
> @Xcedf I know that, just didn't mention that.

Then why are you reporting something that is *not* a regression? Only "Safe" mode regressed.

**Comment by Nekotekina** [comment]
If a crash occures during SPU cache pre-compilation, please upload corresponding SPU cache dat file.

**Comment by Xcedf** [comment]
@Nekotekina gow3 mega cache, hope it'll help
[gow3mega.gz](https://github.com/RPCS3/rpcs3/files/3170212/gow3mega.gz)

@mavethee About R&C: it also works, after cutscene during blackscreen it compiles spu cache for a while ehough to thing it's stuck but it's not

**Comment by mavethee** [comment]
@Nekotina I deleted that cache ealier. Now it works fine.
@Xcedef I see. In master it loads faster, so my bad.
@ruipin I don't waste time just report what happends to me. Okay, I don't have strong CPU, but I was able to boot it. I will keep trying to boot it to get to the to that point where I'm in master.

**Comment by Lemiru** [comment]
I'm 90% sure that this is the biggest improvement in a game (deception IV) for this PR (on SPU LLVM of course)
PR:
Screen Shot 05-12-19 at 06 15 PM
SPU cache amount: 3342 (emulator closed after finishing first tutorial level
Master:
Screen Shot 05-12-19 at 06 10 PM
SPU cache amount: 125725 (emulator closed after taking screenshot)

Note: difference in visuals is not caused by PR (game on master is running so slow that I wasn't sure if it was still running so I left it for a moment and when I came back I just took this screenshot)

**Comment by resadent** [comment]
Zone of the enders 2 (Zoe HD v2): won't boot, no black screen or anything.
Persona 5: better performance, from 25-ish to 30 most of the time with dips up to 22 or so when there's lots of NPCs. Great work.

**Comment by Exmach** [comment]
@Nekotekina SPURS hack is not helped with Safe on GT6
ЗЫ: А по русски можно?

**Comment by Xcedf** [comment]
@Exmach it was not supposed to (а он и не должен был)

**Comment by raven02** [comment]
Tested with P5 using Max SPURS Threads: 3 . 1st scene 

Master : 51-52 fps
PR : 58-60 fps
PR

**Comment by Xcedf** [comment]
Completed GoW Ascension on this PR, and the whole game SPU Cache on Mega is 3308, besides 3100 of it is first 15 minutes of the gameplay, so the rest of gameplay is stutter free, before this PR game in this game i had 35k on Mega but not from whole game and 115k on Safe from whole game

**Comment by Exmach** [comment]
ASMJIT Deception 4 works good
(кеш 3к, на мастере бесконечен)

**Comment by Kravickas** [comment]
NHL 16 doesnt work with ASMJIT Safe/Mega (didnt tested giga)
it close whole emulator 1sec after it loads shader cache 

[nhl 16 asmjit safe.zip](https://github.com/RPCS3/rpcs3/files/3174991/nhl.16.asmjit.safe.zip)

**Comment by arcadee1977** [comment]
@Nekotekina Musou Orochi 2 Ultimate is full speed ! Huge speed-up! Amazing!! Thank you very much!(spu ASMJIT+MEGA)

**Comment by tabnk** [comment]
Tested Trinity: Souls of Zill O'll. 

No improvement in performance.

**Comment by legend800** [comment]
@tabnk Only report improvements/regressions from master. 

On latest build, GOW3 is still broken on safe/mega and GOWA broken with Safe. You can get it tow work with mega if you clear all cache and boot the game a few times.

**Comment by arcadee1977** [comment]
Sengoku Musou 4【BLJM61144】is full speed too!  This is a great PR!!

**Comment by jenci8888** [comment]
Other "Koei Tecmo" games are playable for this PR.
No longer constant freezing/lagging nor crashing. (while master does.)
Excellent job, Neko-chan! 👍 

image

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3176594/RPCS3.log.gz)

**Comment by resadent** [comment]
Just tested spu giga with latest build. Persona 5 performs way worse than with mega. ~15fps in places with lots of npcs. Got the log in case it helps. My pc is ivy bridge.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3178994/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
Don't bother with Giga, at least until I start working on it specifically.

**Comment by Tom-Neverwinter** [comment]
regression for WipEout® HD Fury [BCES00664] textures pop in and out. stutter. audio is even more out of sync. 8096 seemed to work fairly well.

**Comment by Muramas** [comment]
Seems like there is regression for ₱5 
[RPCS3.log - Copy.gz](https://github.com/RPCS3/rpcs3/files/3180939/RPCS3.log.-.Copy.gz)

**Comment by RainbowCookie32** [comment]
Report regressions on the tracker #5965

**Comment by alessandro784** [comment]
gow 3 start only in giga at 4 fps, before i had a good fps in safe mode

**Pull request merged**
