### PR TITLE
aarch64: Support calloc patch blocks

### PR DESCRIPTION
**Pull request by kd-11**
Closes https://github.com/RPCS3/rpcs3/issues/16014

The calloc setup inserts a call to a function at the address that has the same signature as the source address from the IR POV. The calloced block isn't injected as a regular function though, we go through a thunk so it is equivalent to an indirect branch from a flow pov. Assume we don't actually know enough about the target in that situation and do not trap on return. The callee is responsible for making sure they do not spill anything to our stack, same as indirect branches.

### CODE REVIEW

**Comment by squidbus** [comment]
I'm still seeing the same breakpoint hit with a build made from this PR's branch. Thought it might just be the `jumpf` this time but even with that changed to a `nop` it still happens.

**Comment by kd-11** [comment]
> I'm still seeing the same breakpoint hit with a build made from this PR's branch. Thought it might just be the `jumpf` this time but even with that changed to a `nop` it still happens.

You need to clean your ppu cache for the affected games.

**Comment by squidbus** [comment]
> You need to clean your ppu cache for the affected games.

Ah yep I forgot to try that, thanks I can confirm it's working now. I thought it was rebuilding it whenever I changed the patch because of the load time difference but I guess there's more to it.

**Comment by Calhbeau** [comment]
BzbBabsbahsh

**Pull request merged**
