### PR TITLE
rsx: Rewrite data texture remap expansion

### PR DESCRIPTION
**Pull request by kd-11**
While debugging Saints Row engine problems, I found that the game was expecting some channel configuration for some data format but decoding the registers by hand showed rpcs3 was "correct". However, after running some hardware tests, it would appear they do not obey the same rules as the other textures.

- 16-bit channel formats (including 8->16 compressed channels) have special 0x4|0xE encoding for only 2 channels, not 4. 0x4=word[0], 0xE=word[1]
- float textures do not take any remapping and crash if you try it. Depth float textures are the exception.

Fixes https://github.com/RPCS3/rpcs3/issues/3545

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
Fixes these graphical issues in the following games:

<details>
<summary>Saints Row: The Third - Broken lighting and missing textures in some objects</summary>

image
image
</details>
<details>
<summary>Saints Row IV - Broken lighting and missing textures in some objects</summary>

image
image
</details>

**Comment by uaqlover** [comment]
could fix https://github.com/RPCS3/rpcs3/issues/7357 ?

**Comment by Passingby1** [comment]
Saints Row 2 still has some minor texture problems. Before it was noticeable in half the body, it was darker, now it's on the face. 
Furthermore, when using Vulkan RPCS3 fast crashes to desktop after you start a game and it finishes the loading screen. 

sr2

[OpenGL log](https://github.com/RPCS3/rpcs3/files/4623393/RPCS3.log.gz)
[Vulkan log](https://github.com/RPCS3/rpcs3/files/4623398/RPCS3v.log.gz)

**Comment by Tusmi86** [comment]
From this version, Initial D Extreme Stage-[BLJM60055] runs slowly in actual driving

**Comment by illusion0001** [comment]
Open a regression report ticket https://github.com/RPCS3/rpcs3/issues/new?assignees=&labels=&template=1-regression-report.md&title=

**Comment by kd-11** [comment]
Pretty sure its not this PR but you never know. I wonder how bisecting was done, PRs are not merged in order of opening.

**Pull request merged**
