### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by raveskirza** [comment]
Soul Calibur 5 reports a trophy error with this PR

image

Log with this PR
[RPCS3-PR.log.gz](https://github.com/RPCS3/rpcs3/files/1586154/RPCS3-PR.log.gz)

Log with Master
[RPCS3-Master.log.gz](https://github.com/RPCS3/rpcs3/files/1586155/RPCS3-Master.log.gz)

**Comment by spyropt** [comment]
Just tested SoulCalibur V BLES01250 and it created trophy data
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1586164/RPCS3.log.gz)

**Comment by Xcedf** [comment]
God of War HD Collection Volume II ingame or maybe even playable now


Simpsons The Game now also progersses further but has some sort of input issue

**Comment by raveskirza** [comment]
New build is working good. SC5,,II online and tekken Tag 2  boot properly now.

**Comment by Xcedf** [comment]
https://github.com/RPCS3/rpcs3/issues/3544 seem's to be fixed now fo libnet

**Comment by MarioSonic2987** [comment]
image
Saints Row works again.

**Comment by M220** [comment]
I know that this is not the place to say this but i can't hold my self anymore...
I LOVE YOU NEKO!!!
Because Duplex games now Show right output and goes ingame without problems like access violation , Emulator get closed or getting closed after pressing a button!!!

**Comment by sirdanielk** [comment]
bejeweled also blus30868 also got working (interesting 3in1 games)

**Comment by resadent** [comment]
BLES01756 now gets past the title selection screen... though I still get a black screen after that. Before it crashed inmediately after selecting the game.
image

**Comment by gizellos** [comment]
This changes broke the app for me.

1. I cannot use ALT+TAB (I could before)
2. If I click on something on the second monitor, on the main monitor, where the emulator is opened, windows start bar will appear (It didn't do before)

**Pull request merged**
