### PR TITLE
Fix null pointer check (clang warnings)

### PR DESCRIPTION
**Pull request by JohnHolmesII**

### CODE REVIEW

**Comment by RipleyTom** [comment]
Hmm the old check didn't make sense but the new one doesn't either, I doubt it's just checking the first byte of data.

**Comment by JohnHolmesII** [comment]
I could just delete it. Maybe @Megamouse has an idea, since he spent all the time on this stuff.

**Comment by Megamouse** [comment]
well. ideally it should be checked for empty data. like empty string

**Comment by JohnHolmesII** [comment]
But what if the data is supposed to just be a block of 0s? Are you positive an empty string is an invalid arg?

**Comment by Megamouse** [comment]
The data is an online handle. so it should be a string like "Megamouse".
There's a terminating zero (probably guaranteed) in the following char after data (which is max 16 chars).

**Comment by JohnHolmesII** [comment]
So just checking if the first byte is null terminator ought to be good enough then?

**Comment by RipleyTom** [comment]
Yeah I just checked it's a string(I thought it was some unique ID hash type). So just checking first byte should be fine then, my bad.

**Comment by JohnHolmesII** [comment]
I can change the checks to explicitly compare to '\0' if that makes the code more clear.

**Pull request merged**
