### PR TITLE
RSX: missing base_index

### PR DESCRIPTION
**Pull request by raven02**
fix Regosun in-game graphic https://github.com/RPCS3/rpcs3/issues/1989

untitled

vk

### CODE REVIEW

**Comment by raven02** [comment]
@vlj / @kd-11 , looks okay ?

**Comment by raven02** [comment]
Meanhwile, do we need the base_index for copy_whole_attribute_array() as well ?

	void copy_whole_attribute_array(gsl::span<T> dst, const gsl::byte* src_ptr, u8 attribute_size, u8 dst_stride, u32 src_stride, u32 first, u32 vertex_count)
	{
		for (u32 vertex = 0; vertex < vertex_count; ++vertex)
		{
			const U* src = reinterpret_cast<const U*>(src_ptr + src_stride * (first + vertex));
			for (u32 i = 0; i < attribute_size; ++i)
			{
				dst[vertex * dst_stride / sizeof(T) + i] = src[i];
			}
		}
	}

**Comment by kd-11** [comment]
So this fixes vertex base for cmp type, but the other vertex types aren't using it.
Looking at copy_whole_attribute_array, i see no ref to the vertex base index there, so should it be restricted to cmp type?
@vlj should be able to shed more light on this since he wrote the bufferutils code.

**Comment by raven02** [comment]
Sorry , look like in-game graphic is affected by libfiber.elf as well but not by this base index change .

**Pull request closed without merging**
