### PR TITLE
vk: Restructure present mechanism

### PR DESCRIPTION
**Pull request by kd-11**
- Removes frame submission control from the application and relies on the driver to do it automatically for us. This avoids the NVIDIA fullscreen deadlock issue entirely and also improves framepacing a lot.
- Remove a lot of no-longer-necessary code from the window classes. This includes the win32 hooks and the renderer-side window management polling code. May slightly improve performance due to less overhead.
- Implements frame management when window is minimized, allowing resources to be released properly.

Fixes https://github.com/RPCS3/rpcs3/issues/5351

### CODE REVIEW

**Comment by Whatcookie** [comment]
You can remove the log message that I added the other day in VKhelpers.h at line 440 now.
Perfomance is good in amdvlk and window resizing still works.

**Comment by vsub** [comment]
Now this is really good commit,not only fixes the https://github.com/RPCS3/rpcs3/issues/5351 which was bothering a lot of people but it also fixes https://github.com/RPCS3/rpcs3/issues/6043 https://github.com/RPCS3/rpcs3/issues/5508 and https://github.com/RPCS3/rpcs3/issues/5202

**Comment by 13xforever** [comment]
<details>
 <summary>Yakuza 3 frame time pacing improvements</summary>

before
after
</details>

**Comment by MsDarkLow** [comment]
Completely fixes the microstutering in Yakuza Games.  (No more 15fps at 1% and 0.1%!)

Yakuza Kenzan:
Master
KenzanMaster
PR
KenzanPR

**Comment by blackecos** [comment]
Thanks for this, will this come to the official builds?

**Comment by dio-gh** [comment]
@blackecos It's merged, so it's already in the official build.

**Comment by blackecos** [comment]
@dio-gh 
Mhm then It doesnt work for me in the official build. 
With 0.0.6-8197.3e620f14 Alpha it works fine.
With the latest official build I still get crashes in fullscreen mode ;/

Just to be honest Im not sure thats the same thing here... I come from a link from this page:
https://github.com/RPCS3/rpcs3/issues/5351
Github confuse me all time... <.<

**Comment by dio-gh** [comment]
> With 0.0.6-8197.3e620f14 Alpha it works fine.

That's a build from before this PR was merged. This changeset is in master since `0.0.6-8204`. This PR fixed a long-standing issue of people getting crashes in fullscreen when using nvidia hardware. If you say things were working fine in that quoted build (as in, you didn't get crashes), then you're experiencing a different issue.

**Comment by blackecos** [comment]
Then should I go with the latest build -> wait for a crash and post some logs or something? x(

**Comment by 13xforever** [comment]
This issue has been confirmed to be fixed. Your issue is most likely unrelated at all. Stop spamming github please, ask in Discord if you need further help.

**Comment by dio-gh** [comment]
@blackecos I meant that what you are saying logically doesn't check out, and thus you're probably experiencing a different issue. By default, this would mean that you could open a new, separate issue, and post logs and issue description there.

However, it'd be preferable if you visited to our Discord server first, as 13x says, and clarified that it's indeed a real issue, not a settings mishap or something.

**Pull request merged**
