### PR TITLE
Overlays: Add screenshot message to queue

### PR DESCRIPTION
**Pull request by Megamouse**
image

### CODE REVIEW

**Review by RipleyTom — APPROVED** [review]

**Comment by illusion0001** [comment]
Maybe show the path too `Screenshot saved: \screenshots\filename.png`

**Comment by Megamouse** [comment]
That would mean i had to spend more time on it 😩

**Comment by Megamouse** [comment]
image

**Comment by Megamouse** [comment]
Idk

**Comment by illusion0001** [comment]
Yea, pretty much that

**Pull request merged**
