### PR TITLE
Unbreak build with Qt 5.15

### PR DESCRIPTION
**Pull request by jbeich**
Could be a Qt bug. I've only checked 5.15.0-beta2 [on FreeBSD](https://github.com/freebsd/freebsd-ports-kde/commits/qt5-5.15.0).

### CODE REVIEW

**Comment by sl1pkn07** [comment]
https://github.com/RPCS3/rpcs3/commit/9de9ec1f01ae89d8c71a42cebbd5f1d6dd32aed5

**Comment by AniLeo** [comment]
Yeah this seems like a compiler* bug, it's already included

**Comment by sl1pkn07** [comment]
i'm not sure if is a include order fault. what happen if is changed?

**Comment by jbeich** [comment]
> 9de9ec1f01ae89d8c71a42cebbd5f1d6dd32aed5

Sorry, my base revision was too old.

**Pull request closed without merging**
