### PR TITLE
D3d12: Fixes and speed improvements.

### PR DESCRIPTION
**Pull request by vlj**
This PR fixes shader miscompilation with Machinarium. It should also fix Disgaea 3 crash.
There are also some speed improvements by reducing API calls and avoiding copies.

### CODE REVIEW

**Comment by tambry** [comment]
@vlj Needs to be rebased.

**Comment by Zangetsu38** [comment]
@tambry berfore if you need push My PR for fix Compilation d3d12

**Comment by tambry** [comment]
@vlj Is @Zangetsu38's really needed before merging this one?

**Comment by Zangetsu38** [comment]
@tambry my pr fixed commpilation dx12, soo not obligatory just better :)

**Comment by vlj** [comment]
rebased

**Comment by Zangetsu38** [comment]
@tambry soo is good, vlj a fix compilation problem also.

**Pull request merged**
