### PR TITLE
sys_timer: Hotfix for stability improvements

### LINKED ISSUE #13937: [Regression] Random input freezing (#13917)
### Quick summary

The in-game inputs (besides the home button) stop working at random.

### Details

When I start a game, there is a completely random chance that my in-game inputs will freeze up and simply stop responding to what I do. They freeze, which means they don't disappear; an example of this is when I hold right, and it freezes, the game will continue to keep holding right without me doing anything. The only way to fix this is to reboot the game entirely, where it will happen again after a few minutes of play. This is a problem with the latest version, 15111.

### Build with regression

0.0.27-15111

### Attach two log files

Broken: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11634250/RPCS3.log.gz)

Fixed: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11634310/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### LINKED ISSUE #13942: [Regression] R&C Collection audio disappears
### Quick summary

This problem was seen with a discord user, when testing, I also have this, it seems to me that the build https://github.com/RPCS3/rpcs3/pull/13917 is the responsable

### Details

You play any game of the trilogy, a period of time passes and then, the audio goes away, so that later, the game freezes.

### Build with regression

0.0.27-15111

### Attach two log files

Working -> 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11641756/RPCS3.log.gz)

Broken ->
[R&C3 Missing audio and freeze.log.gz](https://github.com/RPCS3/rpcs3/files/11641764/R.C3.Missing.audio.and.freeze.log.gz)

### Attach capture files for visual issues

None

### System configuration

Windows 10 21H2
Intel Core i7-8700
15.93 GiB RAM
GPU: NVIDIA GeForce GTX 1070 Ti (535.98)

### Other details

_No response_

### LINKED ISSUE #13943: [Regression] Uncharted 3 [BCE01175] cutscene videos play at half speed in 15112 onwards
### Quick summary

Uncharted 3 has a mixture of in-engine and video cutscenes. In version 15096 video cutscenes play normally but version 15112 they play at half speed. The other Uncharted games don't seem to be affected.

The offending PR appears to be #13917

To reproduce simply start a new game and watch the opening cutscene.

### Details

Video of the issue:-

https://github.com/RPCS3/rpcs3/assets/55807111/8a66eb30-4132-4217-a504-eb492c76c38c

### Build with regression

v0.0.28-15112-33558d14

### Attach two log files

[RPCS3-15096.zip](https://github.com/RPCS3/rpcs3/files/11642668/RPCS3-15096.zip)
[RPCS3-15112.zip](https://github.com/RPCS3/rpcs3/files/11642669/RPCS3-15112.zip)

### Attach capture files for visual issues

_No response_

### System configuration

i7 12700k
16gb 3200mhz DDR 4
RTX 2060 Super 8gb

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Fixes #13937 
Fixes #13943 
Fixes #13942

### CODE REVIEW

**Comment by Ordinary205** [comment]
Gran Turismo 5 gets stuck in black screen when trying to create PPU modules.
Gran Turismo 5 gets stuck
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11643064/RPCS3.log.gz)

**Comment by elad335** [comment]
Retest now.

**Comment by elad335** [comment]
I think it may solve the audio desyncs reported on gt5 on pr.

**Comment by readywer** [comment]
Unfortunately it didn't solve the GT5 audio deync at least for me.

**Comment by readywer** [comment]
For GT5 after some tests i found out that the audio desync can be fixed by using Accurate XFloat or ASMJIT.

**Pull request merged**
