### PR TITLE
GUI: Kuroi (Dark) Theme

### PR DESCRIPTION
**Pull request by AniLeo**
Implements new custom style-sheet GUI dark theme for RPCS3.

## Screenshots
image

---

### TODO
- [x] Fixed firmware libraries styling
- [x] Fixed disabled buttons styling
- [x] Fixed controller image styling
- [x] Fixed disabled menu options styling
- [x] Fixed disabled toolbar button styling
- [x] Fixed disabled settings button styling
- [x] Fix toolbar text color
- [x] Fix game list grid text color
- [x] Fix ui buttons styling on settings
- [x] Fix about / welcome header styling
- [x] Fix toolbar default colors

---
Suggestions are welcome.

### CODE REVIEW

**Comment by Galacticlink** [comment]
Nice!

**Comment by raven02** [comment]
Very nice .The text looks like disappeared in grid mode.

untitled

**Comment by AniLeo** [comment]
Added to known issues, need fixing upstream so I can change values

**Comment by Luffykun007** [comment]
Very nice Dark Theme @Anileo.

**Comment by zminhquanz** [comment]
Very nice , it's same when i code in Visual Studio

**Comment by AniLeo** [comment]
Updated the theme, still WIP

**Comment by Megamouse** [comment]
What's wrong with the textcolor? your todo or problem with current code / style

**Comment by Megamouse** [comment]
Add this to your toolbar color section
```
QWidget#sizeSliderContainer {
	background: transparent;
}
```

**Comment by Megamouse** [comment]
The color buttons have a child label that overshadows the whole pushbutton, so you need to add this:
```
QLabel#color_button
{
	background-color: transparent;
}
```

**Comment by Megamouse** [comment]
Okay I found the easiest way to change the toolbuttons background without "hardcoding" the color.
just dimm it with alpha value.
```
QToolButton::disabled {
	background-color: rgba(0, 0, 0, 100);
}
```

**Comment by Megamouse** [comment]
only thing left to do is to change the pushbuttons margin to make color buttons look better.
And to exclude the toolbar from your background setting, because you wont see the hover and click effects like this. but that's for you to tweak.

**Comment by Megamouse** [comment]
For white dialog headers use
`QWidget#header_section {}`

**Comment by AniLeo** [comment]
For now UI toolbar colors must be set manually because I can't seem to override them for some reason

**On Settings -> Emulator -> UI Colors:** 
Main window tool bar: #323232
Main window tool icons: #bdc3c7

Updated theme

**Comment by raveskirza** [comment]
I find that the green and orange combination color for checkboxes and radio buttons selections are hard on the eyes.
The default colors for the checkbox and radio has better readability.

image

**Comment by AniLeo** [comment]
It's not orange, it's red. 

Default looks bad for me on windows 7, which is the OS I use, so I styled it differently. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by raveskirza** [comment]
There dont seem to be menu highlights in the right click menu

Without theme when you right click and hover on the Configure
image


With theme
image

**Comment by AniLeo** [comment]
I overlooked some highlights, thanks, I'll update them on next commit. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AniLeo** [comment]
Updated. Everything should be good now.

**Comment by isshininu** [comment]
I think dark theme have unusual animations in menus.

**Comment by AniLeo** [comment]
I don't understand what you mean by that

**Comment by isshininu** [comment]
I mean black theme have animated menus
standard theme doesn't have any

**Comment by AniLeo** [comment]
I updated Pad Settings coloring and replaced forums URLs for the new ones.

**Comment by Megamouse** [comment]
I think you still need to fix the toolbar button hover.

**Comment by AniLeo** [comment]
Fixed GitIgnore properly. Good to merge.

**Pull request merged**
