### PR TITLE
vk: delay texture removal when cache is clobbered

### PR DESCRIPTION
**Pull request by kd-11**
Should fix most crashes during queuePresentKHR
Fixes issues mentioned here https://github.com/RPCS3/rpcs3/issues/1942 and https://github.com/RPCS3/rpcs3/issues/1679

The texture cache was initially made to work with the original vulkan implementation which submitted work after every draw call. With that system, immediately destroying old textures was not an issue, but we now buffer all the work in a queue and submit at once, requiring that all object creation/destruction is buffered/delayed as well.

### CODE REVIEW

**Comment by kd-11** [comment]
Seems to introduce freezing in some titles. Will update.

**Comment by raven02** [comment]
@kd-11 , just wonder did 1942 Joint Strike work for you using Vulkan ?

**Comment by kd-11** [comment]
@raven02 Nope. Just black screen with fps.

**Comment by raven02** [comment]
I see. Will check out regression and open issue.

**Pull request merged**
