### PR TITLE
rsx: Misc fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Removes unused method that was being maintained for d3d12.
- Enables proper clamping for some instructions that can generate results greater than FLOAT16_MAX.
- Fix texture region copy when the texture definition is broken.
- Improve format validation for blit engine when source and destination have different aspects.

### CODE REVIEW

**Comment by Kravickas** [comment]
Fixes reported regression of Star Wars in #6971
Its back ingame 👍 obrazek

**Comment by Emulator-Team-2** [comment]
Golden Axe: Beast Rider and Iron-Man crashes on this pr with:
```
RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1178)
```
Log with Debug Output enabled:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3854501/RPCS3.log.gz)

**Comment by illusion98** [comment]
fixed regression in TR 2013 now ingame again 
previously crashes GPU driver (on 9142) with device lost

**Comment by dio-gh** [comment]
The Darkness (2007) fixed, the game now boots and goes ingame again (was regressed since #5964).

image

@Emulator-Team-2 Please retest both, should be fixed according to what kd said in staff channels.

**Comment by Emulator-Team-2** [comment]
(VK_ERROR_DEVICE_LOST) is now fixed, but these two games still crashes due to a different regression in the `texture_cache.h` unrelated to this pull request.

**Comment by Senninz8** [comment]
(VK_ERROR_DEVICE_LOST) has been fixed for Ninja Gaiden Sigma 2 with this PR.

**Comment by SpeddieSwagetti** [comment]
Regression found in Kingdom Hearts 2.5 HD Remix
Crashes before proceeding ingame. Ran fine on previous builds.

F {RSX [0x0092c8c]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2310)

Log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3872257/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/3872258/TTY.log)

**Pull request merged**
