### PR TITLE
GUI: new twanswation :3

### PR DESCRIPTION
**Pull request by dio-gh**
hewwo guys,

wast time the piwate twanswation didn't make it in, so i decided to add an cute engwish one! suwewy this wiww. ☺️ 

image

image

wove you aww <3,
xoxo

### CODE REVIEW

**Comment by Satan86** [comment]
If this is merged I quit this emulator forever.

**Review by MsDarkLow — APPROVED** [review]
This wooks pwetty amazing >w<  I... I'm in wuv with it, I want it nyow >w<

**Comment by Nenkai** [comment]
So cursed even Satan himself is leaving
I'd say this is a pretty good improvement

**Review by elad335 — APPROVED** [review]
I thiwk this shouwd be the new defauwt twanswation.

**Comment by Satan86** [comment]
elad, you too... 😿

**Comment by Nekotekina** [comment]
Uwwh...

**Comment by illusion0001** [comment]
Xo this pr is soo cute

**Review by illusion0001 — APPROVED** [review]

**Comment by GitArUs** [comment]
I found translation error in warning window. Should be WPCS3/wpcs3/mewge instead of RPCS3/rpcs3/merge.

**Comment by dio-gh** [comment]
@Megamouse pwease fix upstweam

**Comment by GitArUs** [comment]
On second thought - PR #10049 should take care of it.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by dio-gh** [comment]
Pain, peko.

**Pull request closed without merging**
