### PR TITLE
RSX: Restrict analyser loop error

### PR DESCRIPTION
**Pull request by Yahfz**
log spam from analyzer was lowering fps in R&C and maybe others (Resistance 3?). In this case there was a huge FPS boost from 23 to 66fps. This stops the output to be less/once a loop rather than every instruction. 
Games that spam this should improve. 
**RSX: vp_analyser: Possible infinite loop detected**

<details>
  <summary>Before</summary><p>

  

</p>
</details>
<details>
  <summary>After</summary><p>

  

</p>
</details>

### CODE REVIEW

**Comment by ArchSonix** [comment]
Shouldn't the var definition `bool printedError = false;` be defined right before the `while` statement?
Like right inside the walk_function but 1-2 lines before `while`?

**Comment by legend800** [comment]
Does this help even if logging (writing to file) was turned off?

**Comment by JohnHolmesII** [comment]
The variable is best put inside the lambda, since it isn't used anywhere else.

**Comment by Yahfz** [comment]
done

**Comment by lainiwaku** [comment]
resistance 3 still have log spam, do i need to activate something ? 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4397259/RPCS3.log)

**Pull request merged**
