### PR TITLE
[HOTFIX] Fix vm::check_addr calls in Thread.cpp

### LINKED ISSUE #9245: Bug: Gran Turismo 6 crash (VM: Access violation writing location)
Gran Turismo 6 crashes with a VM: Access violation writing location right around when the intro movie starts.
`{SPU[0x3000100] Thread (PDICellSpursKernel3) [0x050d8]} VM: Access violation writing location 0x43700e80 (read-only memory) [type=u256]`
`{SPU[0x2000100] Thread (PDICellSpursKernel2) [0x050d8]} VM: Access violation writing location 0x43112280 (read-only memory) [type=u256]`
`{SPU[0x4000100] Thread (PDICellSpursKernel4) [0x050d8]} VM: Access violation writing location 0x4330c680 (read-only memory) [type=u256]`

Screenshots of the kernel explorer:
Screenshot_13
Screenshot_14

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5523359/RPCS3.log.gz)

Ryzen 7 2700
RX 580 20.10.1
Windows 20H2

### PR DESCRIPTION
**Pull request by elad335**
There was no real reason to check full d_size, checking single page should be enough.

Fixes #9245 (should)

### CODE REVIEW

**Comment by xddxd** [comment]
Can confirm that #9245 is fixed

**Comment by AphelionWasTaken** [comment]
Also fixes Tales of Xillia, which was freezing with a similar error to what is seen in #9245 after PR #9239

**Comment by kotn3l** [comment]
Also fixes #9248.

**Comment by kd-11** [comment]
Merged as hotfix.

**Pull request merged**
