### PR TITLE
RSX: throw exception removal for user_command()

### PR DESCRIPTION
**Pull request by raven02**
fix https://github.com/RPCS3/rpcs3/issues/1860

### CODE REVIEW

**Comment by AniLeo** [comment]
That could still be logged as a warning instead of being totally removed for future reference (?)

**Comment by raven02** [comment]
@AniLeo .i'll do it in another pull .

**Comment by Nekotekina** [comment]
I don't think it needs a warning...

**Comment by raven02** [comment]
Alright . @Nekotekina

**Pull request merged**
