### PR TITLE
Ogl bringup 4

### PR DESCRIPTION
**Pull request by kd-11**
- Refactor OGL backend into discrete units matching GL objects
- Implement support for custom virtual formats including load/store semantics using a combination of compute shaders and renderpasses. Currently only custom upload is implemented, custom download is to be implemented in future.

With this, rendering is correct even with complex bitcast operations, though performance is pretty awful. I decided not to focus too much on optimizing that right now as the PR is already too large. The next task shall handle optimization and work mergers (some operations trigger too many jobs which can be easily batched into one)

### CODE REVIEW

**Comment by Darkhost1999** [comment]
PR
image
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8994759/RPCS3.log)
Master
image
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8994774/RPCS3.log)

**Comment by gandalfthewhite19890404** [comment]
VSH during initial setup
image
VSH after setup
image

**Comment by kd-11** [comment]
I'll be chopping up this PR into smaller bits over the coming days for incremental merging, I didn't forget about it yet.

**Comment by kd-11** [comment]
After analyzing the problems, it turned out the foundation is pretty solid and I do not need to rebuild the PR afterall.
@gandalfthewhite19890404 @Darkhost1999 You can now retest.

**Comment by Darkhost1999** [comment]
image
Color is restored to the appropriate appearance.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9097235/RPCS3.log)

image

VSH font is restored
[Uploading RPCS3.log…]()

**Pull request merged**
