### PR TITLE
Adding the icon on window GL and DX12

### PR DESCRIPTION
**Pull request by Zangetsu38**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@danilaml travis is dead ?

**Comment by danilaml** [comment]
@Zangetsu38 seems so: https://www.traviscistatus.com/

**Comment by Zangetsu38** [comment]
@danilaml that cause no problem with Linux and other?

**Comment by Zangetsu38** [comment]
Travis reality Down arf :/

**Comment by danilaml** [comment]
@Zangetsu38 travis is fixed now and rpcs3 compiles. Now just squash commits into one.

**Comment by danilaml** [comment]
@Zangetsu38 why closing it?

**Comment by Zangetsu38** [comment]
https://github.com/RPCS3/rpcs3/pull/1233

**Pull request closed without merging**
