### PR TITLE
rsx: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
Experimental code that I have been working on for almost 3 weeks now. Hopefully fixes more stuff than it breaks

- Remove an old framebuffer scaling hack (sure to cause some regressions lol)
  If the requested texture exceeds provided size, fill in for missing data with a scaling hack or stitch framebuffers if possible instead of using what exists as being 100%
- Implement framebuffer merging
  Implements framebuffer stitching to find missing data in cases where separate framebuffer regions are used as one input texture
- Optimize vertex data handling on opengl and vulkan using a large sliding window
  Avoids generating buffer views as much as possible using a 16M window extended when possible.
- Many minor performance improvements
- Nvidia hardware workaround, stop NaN values from reaching the GPU
  Feeding NaNs to nvidia GPUs can poison the framebuffer contents with undefined results (Rain)
- Fragment program decompiler improvements
  Always provide output registers even when not referenced (they still exist in hw even if unused)
  Minor fixes for component gather
- Texture cache: Force format matching for render targets and attempt bitcast if formats do not matching
  Should fix some games reuploading render targets as different formats
- Fix/support apple now that moltenvk is out
  Only compiles but does not run due to bugs. Support needed for format swizzling and GLsl.std.450.xxxx functions like unpackHalf2x16 which are still missing
- Implements basic performance counters. NOTE: The counters are inaccurate if vsync is enabled since the driver enforces the vblank wait
  Very helpful for identifying performance bottleneck
- Implement rasterization offsets
  Fixes missing graphics in some games (Turbo SS, Burgertime)
- Fix and improve transform constants management
  Fixes flickering in some games like skate3
- Partially implement transparency AA (coverage sample AA)
  Implements alpha-to-coverage transparency. Fixes foliage, hair, etc in some games
- ZCULL emulation rewritten to optimize for better performance
  Defers report updates slightly to avoid a hard stall GPU-side. Performance improvements can be huge depending on the game.
  Also fixes broken occlusion queries on nvidia cards when using OGL
  Might cause slight flicker in some games

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
Shadows are working in MCLA:
image

**Comment by mchelequim** [comment]
hi,where i download it ?

**Comment by MarioSonic2987** [comment]
@mchelequim https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-c031122d/artifacts

**Comment by toccata10** [comment]
Can't compile on ArchLinux:
```
cc1plus: warning: /home/jo/tmp/rpcs3/kd11/rpcs3_build/rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch : non utilisé parce que « __STDC_CONSTANT_MACROS » est défini [-Winvalid-pch]
In file included from /home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.h:3:0,
                 from /home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.cpp:4:
/home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/Emu/RSX/GL/GLHelpers.h:1100:3: error: la déclaration de « gl::buffer* gl::buffer_view::buffer() const » [-fpermissive]
   }
   ^
In file included from /home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.h:3:0,
                 from /home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.cpp:4:
/home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/Emu/RSX/GL/GLHelpers.h:629:8: error: change la signification de « buffer » depuis « class gl::buffer » [-fpermissive]
  class buffer
        ^~~~~~
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:5277: rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/GL/GLGSRender.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

```

**Comment by JackONeill12** [comment]
swtfu

Star Wars The Force Unleashed now shows an Image instead of a black screen before crashing the emulator.

**Comment by greentop** [comment]
4f573bf - Build error with gcc in Ubuntu 16.04 seen. The attached log file is a mostly full build output.

[4f573bf gcc build fail.log](https://github.com/RPCS3/rpcs3/files/1799472/4f573bf.gcc.build.fail.log)

**Comment by MSuih** [comment]
Read Dead Redemption doesn't go ingame with this build, it segfaults as soon as the intro cutscene starts.

>Unhandled Win32 exception 0xC0000005.
>Segfault reading location 00000008164e34f8 at 00007fff64757af7.
>Instruction address: 00007fff64757af7.
>Function address: 00007fff64757aa0 (base+0x1d7aa0).
>Module name: 'amdvlk64.dll'.
>Module base: 00007fff64580000.
>RPCS3 image base: 0000000000010000.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1799490/RPCS3.log.gz)

**Comment by M220** [comment]
Hi kd and thanks for the beautiful PR :D
Here's some regressions i'm going to report :
RDR : 
Game crashes with two method : 
# 1 : 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1799485/RPCS3.log.gz)
And # 2 : 
[RPCS3-1.log.gz](https://github.com/RPCS3/rpcs3/files/1799486/RPCS3-1.log.gz)
Also one time the game and Emulator was running but then when this error showed up, game locked but emulator was still running ( and spamming this errors right after another ) : 
E {rsx::thread} RSX: Application has failed to recover, resetting FIFO queue
E {rsx::thread} HLE: Getting the real address failed. (addr=0x45160ec0)

Persona 5 : 
Game will stop for a 2 or 3 seconds after some gameplay and then this will keep going forever ( with this error ) : 
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x403005A0

**Comment by Asinin3** [comment]
@MSuih Log is corrupt, but anyway with Vulkan Driver errors like that you need to enable debug output (change it in config.yml) and install the Vulkan SDK: https://vulkan.lunarg.com/sdk/home#windows then restart rpcs3 and get a new log with that error.

Anyone else who is experiencing Vulkan errors such as the Device_Lost error needs to use the above method otherwise the log is useless.

**Comment by MSuih** [comment]
Aw shucks, RDR doesn't crash with debug output enabled so I can't get better logs. The FPS drop caused by it seems to make the game more stable for some reason.

**Comment by MarioSonic2987** [comment]
Fixes broken "shadow" indoors in GTA V, I guess.

**Master**:
image
image

**This PR**:
image
image

**Comment by Xcedf** [comment]
A great improvement 
Resistance Demo segfault is fixed 
ingame for the first time

**Comment by Xcedf** [comment]
A regression with R&C ToD and Quest for Booty
after commit 56c51ea3 black screen and sound

**Comment by money123451** [comment]
I get a amd driver fatal crash when starting RDR with Vulkan, [here's a log](https://www.dropbox.com/s/sqa9yfzfkzjxpae/RPCS3.7z?dl=1) with validation layers asinine told me to say that and how to get a log with debug output setup.

**Comment by kd-11** [comment]
@Xcedf wcb is now required for some R&C games. This is the correct operation for these games and not a regression. How they were working before was due to a nasty hack/unimplemented function. This will be improved in future.

**Comment by Xcedf** [comment]
Ok, got it

**Comment by Nicba1010** [comment]
Resistance

Resistance 2 goes in game

**Comment by emko** [comment]
Nvidia Vulkan  Mass Effect performance increased to full speed in areas it was slow but now object flicker out and in

Before: 

https://www.youtube.com/watch?v=m1FRuB4Hk6U

Now: 

https://i.gyazo.com/4d5583744eeb139f20d1d55f26952603.mp4

https://i.gyazo.com/b96f023a488cdf43ccfcccc53ce84841.mp4

**Comment by MarioSonic2987** [comment]
Buildings become white when switching between LODs:
image

**Comment by Xcedf** [comment]
Fixed transperency on vegetation and some other objects in
WRC FIA Demo

**Comment by MSuih** [comment]
Update: On 18.3.1 drivers RDR crashes even with debug output enabled. 

RPCS3: Fatal Error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault writing location 000000006c390020 at 00007fff55e80d69.
Instruction address: 00007fff55e80d69.
Function address: 00007fff55e80d26 (base+0x250d26).<br>
Module name: 'amdvlk64.dll'.<br>
Module base: 00007fff55c30000.<br>
RPCS3 image base: 0000000000010000.<br>

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1800429/RPCS3.log.gz)

Master is unstable but goes ingame, this PR segfaults as soon as the introduction cutscene starts.

**Comment by Asinin3** [comment]
Scaling fixed in Clannad,
Before:
image

After: 
image

**Comment by Marthgun** [comment]
no changes from (recent) and current master for BLUS30903 - Tales of Graces F
didn't think I needed a log for it, just FYI for those who may test it.

**Comment by Asinin3** [comment]
Don't worry about writing X game didn't improve, if i did that I would've had to list over a hundred games. I'll delete this comment soon, lets not spam Pull Requests with irrelevant comments especially a massive PR like this one that is sure to be getting many more comments.

**Comment by resadent** [comment]
BLES01756 Zone of the enders 2 HD v2.0 now renders correctly and plays smoothly on my PC, while before it just showed a blank screen ingame. Just random crashes after cutscenes.

**Comment by kd-11** [comment]
Don't worry about UE3 games with ingame models flickering, its a timing issue with the latency I have allowed (10 instructions) which might be too high for some graphics cards. It will get tuned before merge to something that does not degrade image quality and without hurting performance too much.

**Comment by ScorchEmber256** [comment]
Nier Replicant has increased performance, but now has a periodic stutter with an error:
 E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x403004E0

**Comment by Kosyne** [comment]
@ScorchEmber256 That's always been the case since the wcb fix a while back (assuming this is windows and nvidia hardware).

**Comment by MarioSonic2987** [comment]
Skate 2 receives the same improvements as Skate 3.

**Before**: 
image

**After**:
image

**Comment by MarioSonic2987** [comment]
Fixes characters outlines in Ni no Kuni.

**Before**:


**After**:
image

**Comment by Zangetsu38** [comment]
For Ni no kuni important, like i have explain, need clean shader cache for this game, without render don't change

**Comment by kd-11** [comment]
The shader cache version will get bumped in the next PR ( I remembered after already merged )

**Comment by ap-Di0** [comment]
Getting quite a decent fps improvement (15-30%) in Demon's Souls.

**Comment by greentop** [comment]
This PR fixes the Blade mini game "second character challenge" texture corruption in ToCS2 BLUS31597.

Example bug from an much older build:
screenshot from 2017-10-24 13-11-36

This PR:
screenshot from 2018-03-14 06-48-06

**Comment by Parthorisian** [comment]
Dante Inferno
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1813387/RPCS3.log.gz)
[blus30405] now hangs often with
E {rsx::thread} RSX: Invalid RSX method 0x5ca8 (arg=0x3ca7c328)
(in file Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} RSX: FIFO contents may be corrupted. Resetting...
F {rsx::thread} class std::runtime_error thrown: [attrib buffer] Working buffer not big enough, buffer_length=402653184 allocated=2428672 requested=1896485792 guard=4194304 largest_pool=317696
(in file c:\projects\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:78)

**Comment by toccata10** [comment]
Sega rally BLES00107 is improved (try quick race mode)
Before:
selection_055
Now:
selection_053

**Pull request merged**
