### PR TITLE
cellVdec improved (requires LLE dmux)

### PR DESCRIPTION
**Pull request by Nekotekina**
Basic MPEG2 support

### CODE REVIEW

**Comment by zminhquanz** [comment]
it is can help Project Diva F to play intro

**Comment by Nekotekina** [comment]
It enables OP video and (probably) all ingame videos in Project Diva F.

**Comment by danilaml** [comment]
@Nekotekina HLE was once working though (at least for disgaea).

**Comment by raven02** [comment]
@Nekotekina . I try to enable dmux for Project Diva F , it start playing the video but stuck at the very beginning .

image

**Comment by Nezarn** [comment]
@raven02 i can confirm, also F 2nd does the same, starts the intro video and then it just stops after ~5-10 sec.

**Comment by Nekotekina** [comment]
libatxdec, libadec

**Comment by raven02** [comment]
Thanks @Nekotekina .It works okay now.

**Comment by zminhquanz** [comment]
Can God Of War 3 run this intro ?

**Comment by AniLeo** [comment]
Not sure if it matters right now but if you need a test scenario for this
I believe the game's video files are AVI and not MPEG2

**BLJM-616303 - STEINS;GATE 0**
F {PPU[0xbf] Thread (VideoDecoder[0xbe] Thread)} class fmt::exception thrown: vdecOpen::<lambda_45bb8f7c1ea34ef5aad3de7d61fd5763>::operator ()(): Unsupported time_base.num (50)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellVdec.cpp:306)

**Pull request merged**
