### PR TITLE
sys_fs: Updated some fs-related code following up #14086

### PR DESCRIPTION
**Pull request by brian218**
I implemented `fs::get_normalized_path()` and accordingly updated some sys_fs code as per the conclusion suggested by @Nekotekina and @elad335 in #14086.

### CODE REVIEW

**Comment by elad335** [comment]
You probably want Emu.GetCalbacks().resolve_path().

**Review by elad335 — APPROVED** [review]

**Comment by elad335** [comment]
Maybe just make it just a sys_fs static function for now, it's already shown that this implementation does not work for some unicode characters in some locales.

**Comment by brian218** [comment]
> Maybe just make it just a sys_fs static function for now, it's already shown that this implementation does not work for some unicode characters in some locales. We have different alternatives elsewhere like Emu.GetCallbacks().resolve_path.

I'll move it to `lv2_fs_object`.
But as for `Emu.GetCallbacks().resolve_path`, I remember I tried that too before I adopted the std::filesystem method, and it didn't seem to work for virtual paths (paths that are unrelated to the host file system).

**Comment by Nekotekina** [comment]
maybe `u8path` should be used?

**Comment by brian218** [comment]
> maybe `u8path` should be used?

It's said to have been deprecated in C++20.
Should we still prefer it?

**Review by elad335 — APPROVED** [review]

**Comment by dari1991** [comment]
MLB the show 16 faces edited after version 0.28 15157 come out with defect

**Comment by brian218** [comment]
> MLB the show 16 faces edited after version 0.28 15157 come out with defect

https://github.com/RPCS3/rpcs3/pull/14081#issuecomment-1607653637
https://github.com/RPCS3/rpcs3/pull/14088#issuecomment-1607656264
0.0.28-15157 is #13986, so DO NOT CASUALLY SPAM UNRELATED ISSUES IN UNRELATED PRs.

**Comment by dari1991** [comment]
where can i report this error?

**Pull request merged**
