### PR TITLE
OGL: disable pixel processing test before flip

### PR DESCRIPTION
**Pull request by raven02**
Target https://github.com/RPCS3/rpcs3/issues/1775

### CODE REVIEW

**Comment by kd-11** [comment]
The GL spec is very vague about what states affect the outcome of glblitframebuffer. It is clear that scissor test, pixel ownership tests and srgb are honoured but nothing is mentioned on write masks. As such, please also disable color masking just in case by setting all channels to GL_TRUE. BLEND, LOGIC_OP and CULL_FACE need not be toggled in my opinion as they are per-fragment and per-primitive operations and the fragment processing stage is skipped during a hardware blit. Depth testing and stencil test may not be needed, but a buggy driver may result in undefined results so its okay to disable them.

**Comment by raven02** [comment]
Alright . Let me revise a bit.

**Comment by Nekotekina** [comment]
I would not recommend creating branches in main rpcs3 repository. It seems travis and appveyor do double work.

**Comment by raven02** [comment]
Sure @Nekotekina .I'll create in my own repo next time.

**Comment by paulsapps** [comment]
Its quite spammy to people watching the repo too

**Comment by kd-11** [comment]
Looks good now

**Pull request merged**
