### PR TITLE
Update tooltips

### PR DESCRIPTION
**Pull request by raven02**

### CODE REVIEW

**Comment by AniLeo** [comment]
Needs to be user friendly.

**Comment by raven02** [comment]
Let me know if want a better tooltips for hook static function .

**Comment by AniLeo** [comment]
For both, no normal user will understand what's written there

**Comment by woj1993** [comment]
@AniLeo @raven02 What do you say about:
"It hooks memcpy to be native instead of emulating it. May speedup" to "It allows usage of system methods to control RAM . Probably speedup. (Actually allows to use: memcpy) If unsure leave: checked" unchecked or checked?
"Try to detect wait loops and trigger thread yield." to
"Try to detect when SPU is waiting for event and run this tread only when this event happen instead of all the time (speedup). If unsure leave: Checked". Is this correct? Again this should be checked or not?

**Comment by Megamouse** [comment]
make sure to add \n after each sentence to keep the tooltips in check

**Comment by raven02** [comment]
kd-11 just added it and will close this one.

**Pull request closed without merging**
