### PR TITLE
rsx: Implement separable MRT masks

### PR DESCRIPTION
**Pull request by kd-11**
- Allows modifying write masks individually for each RTT as is done on PS3. Discovered when investigating https://github.com/RPCS3/rpcs3/issues/4380
- Also sets up explicit memory pools for GL buffers in preparation for compute integration.
- Clean up unused OGL code.
- Hotfix for crashing capture replay.

Fixes https://github.com/RPCS3/rpcs3/issues/4380

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
Fixes weird repeated image and black holes in GTA V.

**Before**:
image

**After**:
image

**Comment by kd-11** [comment]
@incognitoh RSX capture needed.

**Comment by MarioSonic2987** [comment]
It also fixes Infamous: Festival of Blood black textures.

**Before**:
image
**After**:
image

**Comment by toccata10** [comment]
JoJo health bars: problem solved here, on linux. Thanks.

**Comment by MarioSonic2987** [comment]
There's a black part of the screen in Just Cause 2 with Vulkan. With OpenGL, it looks like master in both backends.
image
image


[RSX Capture (Vulkan PR)](https://drive.google.com/open?id=1hbVqsdcTfB8M7ZrI87AY5e0ldt3Ek6UV)

**Comment by Xcedf** [comment]
Dante's Inferno regressed on the last commit
Before:
screenshot-2019_08_27_10_35_38
After:
screenshot-2019_08_27_10_39_19
Rsx capture
https://mega.nz/#!aQZzASrI!GafxJhcOsRq418xXq8bmahWSpwhe9OjzuIalYoHsv8o

**Comment by kd-11** [comment]
Should be fixed now. There was an existing regression in surface cache that got uncovered by this PR.

**Comment by MarioSonic2987** [comment]
Just Cause 2 regression is fixed:
image

**Comment by RokkumanX** [comment]
@kd-11 

Issue https://github.com/RPCS3/rpcs3/issues/6259 is semi-fixed with this, and by semi-fixed I mean that the effects work for a limited amount of time before they becomes absent (20-30 seconds of gameplay)

You are onto something but the issue is not entirely fixed.

Huge thanks though!

**Comment by Xcedf** [comment]
Dante's Inferno fixed

**Comment by kd-11** [comment]
@incognitoh Should be fixed by https://github.com/RPCS3/rpcs3/pull/6436. I messed up the setup for a certain type of framebuffer that is rarely used.

**Comment by stachuATX7** [comment]
image

I need to admit that older version works good. 0.0.4/3

**Pull request merged**
