### PR TITLE
cellPad: check for more invalid parameters

### PR DESCRIPTION
**Pull request by Megamouse**
Could this fix some random games?

### CODE REVIEW

**Comment by psennermann** [comment]
You mean random crashes/hangs in some games?
Is there a way to test it (a build to download)?
Thanks

**Comment by psennermann** [comment]
Unfortunately following that link I cannot find anything to download...

2018-04-14 12:23 GMT+02:00 Megamouse <notifications@github.com>:

**Comment by jon-reid** [comment]
@psennermann 
It's right there under 'artifacts'

**Comment by psennermann** [comment]
NinoKuni still has random crashed, but also this PR seems faster than master 0.5.6649 (25 fps vs 23 fps)

**Comment by Rpcs3tester** [comment]
@Megamouse .. i tried it on games run nothing .. still nothing - tried it on stuck points in about 3 of games but nothing changed .. there's one problem with this build that i most reopen rpcs3 after deleting game shader that were fixed with this https://github.com/RPCS3/rpcs3/pull/4445

**Pull request merged**
