### PR TITLE
[TESTERS NEEDED] cellVdec: update methods and improve callbacks

### PR DESCRIPTION
**Pull request by Megamouse**
Try some stuff with CELL_VDEC_MSG callbacks and update deprecated ffmpeg functions.

I tried to fix Lair but for some reason I can never even get past the menu lately. So this is just for testing.

### CODE REVIEW

**Comment by elad335** [comment]
FFMPEG error != cellVdec error, it's a hack wotkarounding bugs possible in our implemenratiom of the devoder. Or reverse enginner cellVdec error checks and use them insteas.

**Comment by Megamouse** [comment]
Your comment doesn't make any sense. The entire process is a hack based on your logic. So I don't see the point of not using the proper callback when shit hits the fan

**Comment by elad335** [comment]
You are mixing unrelated things, cellVdec error callback should be executed when *cellVdec*'s related error checks fail. if FFMPEG functions return an error its entirely *the prorammer*'s fault of passing invalid arguments to it, not game's fault.

**Comment by Megamouse** [comment]
Well. It doesn't hurt to test what happens. That's why it's a draft.
Anyway, you can pass shit data to ffmpeg even if you do everything right.
For example if the encoded frame is bullshit. That has most likely nothing to do with cellVdec error checks. And the callbacks I used are not related to any cellVdec functions, but to the used decoder

**Comment by digitaldude555** [comment]
#4246

Fixes bootloop in space ace.

**Comment by lainiwaku** [comment]
Hi, i don't know if  this is related to that pr or it is a different bugs but on killzone 1  video still don't play but i know have this error in log 
(btw the path "C:\projects\rpcs3\"  is not my install path)
`E {PPU[0x100001f] Thread (HLE Video Decoder)} cellVdec: avcodec_receive_frame error(0xfffffff5): Resource temporarily unavailable
(in file C:\projects\rpcs3\rpcs3\Emu\Cell\Modules\cellVdec.cpp:293)
E {PPU[0x1000015] Thread (_libsail-control) [0x01385200]} SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [1]
E {PPU[0x1000015] Thread (_libsail-control) [0x01385200]} SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [2]
E {PPU[0x1000015] Thread (_libsail-control) [0x01385200]} SYS: 'cellVdecDecodeAu' failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [3]`

**Pull request closed without merging**
