### PR TITLE
Improve save data dialog

### PR DESCRIPTION
**Pull request by Nekotekina**
Don't display new data when unnecessary (bug fix)
Use new data icon/title if provided by the game
Minor cellSaveData cleanup

### CODE REVIEW

**Comment by Nekotekina** [comment]
screenshot from 2018-04-02 15-01-04
Something like this

**Comment by Asinin3** [comment]
Looks good, but I think the wording might need to be changed?

New Saved Data > Save Data 
OR
New Saved Data > New Save Data

Personally I think the first option is better as writing "New" twice looks a little bit odd.

**Comment by Nekotekina** [comment]
Hmm, indeed.

**Comment by Nekotekina** [comment]
screenshot from 2018-04-02 16-26-33
Update.

**Comment by Asinin3** [comment]
Looks good, maybe just change the top line to "New Save Data" instead of "New Saved Data" ?

**Comment by Megamouse** [comment]
the code says "Save"
so I assume the screenshot is outdated

**Comment by Nekotekina** [comment]
It's not a string from code.

**Pull request merged**
