### PR TITLE
rsx: Asynchronous host memory management

### PR DESCRIPTION
**Pull request by kd-11**
When requesting memory protection operations, enqueue the requests and handle them in batches. Applies to the texture cache only. A common issue is that when locking pages, we end up trampling on our own work (e.g upload texture 1, lock pages, upload texture 2, requires to unlock texture 1 then lock texture 1 and texture 2, etc). This can get really slow.
Instead, we don't actually care about the memory protection during command recording, so freely mark the slots for protection until we have gathered everything and are ready to render. Then apply the protections in bulk.
The result is a significant speedup in sensitive games though this is admittedly a rare scenario. Makes id tech 5 stop stuttering to single digit framerates.

### CODE REVIEW

**Comment by Darkhost1999** [comment]
<details>
<summary>Master VS PR</summary>
Master

image
[RPCS3.log](https://github.com/user-attachments/files/17910323/RPCS3.log)
PR
image
[RPCS3.log](https://github.com/user-attachments/files/17910335/RPCS3.log)
</details>
A significant performance increase in Need for Speed Most Wanted

**Comment by MarioSonic2987** [comment]
Water no longer shakes in Saints Row: The Third, but breaks player's character textures.
image

image

In master or disabling Asynchronous Memory Manager in this PR fixes player's characters textures, but the water will shake again.
image

**Comment by papagoghub** [comment]
In the past, when Gran Turismo 5 used 1280x720 + greater than 100% Scale when AA was enabled, the sound would be obviously stuttering when replaying below 30fps.

Recently, I accidentally discovered that using AA + 1280x1080p + greater than 100% Scale, almost all track replays within the GPU capabilities no longer have obvious sound stuttering.

However, the fps of the replay of Eiger Nordwand Short Track is not lower than 30, but there is still a bit of lag and popping sound. Using this version to test (Disable Asynchronous Memory Manager: False) can improve the problem of lag and popping sound in the replay of this level, so that all tracks
Almost no sound stuttering will occur during replay.

**Comment by kd-11** [comment]
@MarioSonic2987 Is the breakage in the screenshot? I am quite bad at finding differences in still images it's obvious or pointed out.

**Comment by A5362** [comment]
> @MarioSonic2987 Is the breakage in the screenshot? I am quite bad at finding differences in still images unless it's obvious or pointed out.

We can see a glitch on his right hand (black texture)

**Comment by Pipi86** [comment]
> @MarioSonic2987 Is the breakage in the screenshot? I am quite bad at finding differences in still images unless it's obvious or pointed out.

The poor dude in the screenshot got his eyebrows shaved and also his right palm has a pitch black spot.

**Comment by MarioSonic2987** [comment]
It's more noticeable when the camera is too close to the player. His left arm turns black.

image

Master:
image-1

**Comment by digant73** [comment]
Applied this PR on top of current rpcs3 release (today) and also on previous releases (3 days ago when this PR was opened) and in both cases I have some freezes in some games on specific sections. For example, attached the log on Resistance 3 when starting section `Ambush` on chapter `ST. Louis, MO`. When you skip the cutscene the game freezes before the gameplay start.

[RPCS3.log](https://github.com/user-attachments/files/17951765/RPCS3.log)

**Comment by kd-11** [comment]
> Applied this PR on top of current rpcs3 release (today) and also on previous releases (3 days ago when this PR was opened) and in both cases I have some freezes in some games on specific sections. For example, attached the log on Resistance 3 when starting section `Ambush` on chapter `ST. Louis, MO`. When you skip the first cutscene the game freezes before the gameplay start.
> 
> [RPCS3.log](https://github.com/user-attachments/files/17951765/RPCS3.log)

Any other games affected? I was hoping a smaller game or demo could reproduce. AAAs are hard to debug due to the fact that there is so much "noise" in the data.

**Comment by ItsLaguna** [comment]
In FIFA Street, Disable Async Memory Manager set to False breaks/doesnt show the appropiate colors for the crowd:

disable async mem man false

Setting it to True matches the current behaviour in master and the crowd is no longer looking partially blue or red/pink:

disable async mem manager true

**Comment by digant73** [comment]
> > > Applied this PR on top of current rpcs3 release (today) and also on previous releases (3 days ago when this PR was opened) and in both cases I have some freezes in some games on specific sections. For example, attached the log on Resistance 3 when starting section `Ambush` on chapter `ST. Louis, MO`. When you skip the first cutscene the game freezes before the gameplay start.
> > > [RPCS3.log](https://github.com/user-attachments/files/17951765/RPCS3.log)
> > 
> > 
> > Any other games affected? I was hoping a smaller game or demo could reproduce. AAAs are hard to debug due to the fact that there is so much "noise" in the data.
> 
> yes, the freeze was present also on other games (I have to recheck which ones (I do not remember)) but they are AAA games (I do not have small games or demos). The freeze is present also with the new param `Disable Asynchronous Memory Manager` enabled. In the week end I will try your standalone PR just to be sure I didn't miss to integrate all your changes (by double checking it seems ok)

The issue is present also on your standalone PR (downloaded and compiled). I also verified that in Resistance 3 the freeze is due to WCB enabled

**Comment by Darkhost1999** [comment]
> I also verified that in Resistance 3 the freeze is due to WCB enabled

https://github.com/RPCS3/rpcs3/issues/9133#issuecomment-1808921480

There's some running discussion of write color buffers accelerating freezes in games prone to freezing. I can't double confirm this PR as causation to the freezes because of this running discussion.
I just can't verify this PR creates any new issues.

**Comment by digant73** [comment]
> > I also verified that in Resistance 3 the freeze is due to WCB enabled
> 
> [#9133 (comment)](https://github.com/RPCS3/rpcs3/issues/9133#issuecomment-1808921480)
> 
> There's some running discussion of write color buffers accelerating freezes in games prone to freezing. I can't double confirm this PR as causation to the freezes because of this running discussion. I just can't verify this PR creates any new issues.

I do not have any freeze on current master (or previous versions) with WCB (I always had WCB enabled). The only annoying issue on some Insomniac games (R1 and R3) is the Device Lost that is present with or without WCB

**Comment by digant73** [comment]
The freeze on my side seems to be related to the flag `invalidation_cause::cause_uses_strict_data_bounds` provided at line 2493:

`invalidate_range_impl_base(cmd, tex_range, invalidation_cause::cause_is_read | invalidation_cause::cause_uses_strict_data_bounds, {}, std::forward<Args>(extras)...);`

in `texture_cache.h`

If I remove that flag the is no more freeze.

**Comment by kd-11** [comment]
> The freeze on my side seems to be related to the flag `invalidation_cause::cause_uses_strict_data_bounds` provided at line 2493:
> 
> `invalidate_range_impl_base(cmd, tex_range, invalidation_cause::cause_is_read | invalidation_cause::cause_uses_strict_data_bounds, {}, std::forward<Args>(extras)...);`
> 
> in `texture_cache.h`
> 
> If I remove that flag the is no more freeze.

Thanks for confirming. Skipping external bounds can work but requires some extra work to avoid replacement (RO vs NO flags). I've removed the change for now. Hopefully no more hangs.

**Comment by kd-11** [comment]
@ItsLaguna Retest when it builds as well. I need to make sure no regressions.

**Comment by MarioSonic2987** [comment]
With Asynchronous Memory Manager, water no longer shakes, but broken player character textures are still there:
image

Without that option, player character textures look normal, but water shakes again.
image

**Comment by ItsLaguna** [comment]
> @ItsLaguna Retest when it builds as well. I need to make sure no regressions.

Game crashes when trying to load to main menu if Disable Asynchronous Memory Manager is set to False.
`PPU[0x1000018] Thread (RenderThread) [0x0015a7ec]} VM: Access violation writing location 0x283c27 (read-only memory)`

[RPCS3.log](https://github.com/user-attachments/files/18054613/RPCS3.log)

image

If it's set to True, the game reaches the main menu and can play just fine.

**Comment by digant73** [comment]
> > @ItsLaguna Retest when it builds as well. I need to make sure no regressions.
> 
> Game crashes when trying to load to main menu if Disable Asynchronous Memory Manager is set to False. `PPU[0x1000018] Thread (RenderThread) [0x0015a7ec]} VM: Access violation writing location 0x283c27 (read-only memory)`
> 
> [RPCS3.log](https://github.com/user-attachments/files/18054613/RPCS3.log)
> 
> image
> 
> If it's set to True, the game reaches the main menu and can play just fine.

Eventually, try to clone again the project. With the git pull, the rollback on `texture_cache.h` was not present on my side while it was present clonining again the project

**Comment by ItsLaguna** [comment]
> @MarioSonic2987, @ItsLaguna Eventually, try to clone again the project. With the git pull, the rollback on `texture_cache.h` was not present on my side while it was present cloning again the project

@digant73 Just saw this but I  wasn´t cloning the project, I'm grabbing the artifacts produced from Azure. 

I've been trying to get everything set up to build it myself but I'm struggling to do it, it would be faster if someone could provide an appimage with the rolledback file. Sorry.

**Comment by digant73** [comment]
> > @MarioSonic2987, @ItsLaguna Eventually, try to clone again the project. With the git pull, the rollback on `texture_cache.h` was not present on my side while it was present cloning again the project
> 
> @digant73 Just saw this but I wasn´t cloning the project, I'm grabbing the artifacts produced from Azure.
> 
> I've been trying to get everything set up to build it myself but I'm struggling to do it, it would be faster if someone could provide an appimage with the rolledback file. Sorry.

understood. Unfortunately, I can provide the Windows version only

**Comment by ItsLaguna** [comment]
> > @digant73 Just saw this but I wasn´t cloning the project, I'm grabbing the artifacts produced from Azure.
> > I've been trying to get everything set up to build it myself but I'm struggling to do it, it would be faster if someone could provide an appimage with the rolledback file. Sorry.
> 
> understood. Unfortunately, I can provide the Windows version only

Managed to build it but it crashes after opening any game... I tried 😅
I can boot into Windows and report back if you provide it.

**Comment by kd-11** [comment]
I'll try and make time for this over the weekend to address remaining issues.

**Comment by kd-11** [comment]
Time for some retests. If visuals are glitchy still I'll just invert the option to default to the old way and have users optionally enable this for the speedboost.

**Comment by MarioSonic2987** [comment]
Water no longer shakes and player character textures look fine:

image
image

**Comment by ItsLaguna** [comment]
FIFA Street now boots fine and crowd colors aren't bugged anymore.
image

**Comment by MarioSonic2987** [comment]
Slowdowns that occur while Roxas attacks almost disappear in this PR:
image

**Comment by Linear524** [comment]
Looks like everything works fine :)

**Comment by Apopoy** [comment]
This update has issue with WWE2K14 even I on "Write color buffers" the referee is still glowing red can you fix it? Thank you

**Comment by kd-11** [comment]
Open a proper bug report and link to this PR. This discussion is completed the moment the changes are committed.

**Comment by Asinin3** [comment]
Weird how this issue was originally in 2018: https://github.com/RPCS3/rpcs3/pull/4876#issuecomment-406509121 then broke again in 2020: https://github.com/RPCS3/rpcs3/issues/7338

Then came back and was fixed again here.

**Pull request merged**
