### PR TITLE
New themes for RPCS3

### PR DESCRIPTION
**Pull request by themitosan**
I created a new theme based on Kuroi dark theme by Ani with the intention to make RPCS3 fit better in high contrast mode (Windows)

### CODE REVIEW

**Comment by Megamouse** [comment]
Please convert all of your px sizes to em.

A good rule of thumb is to just divide them by 20.
For Example:
1px -> 0.05em
or  
15px -> 0.75em

And then there is sth wrong with your Pushbuttons. Look at the pad settings dialog.

**Comment by AniLeo** [comment]
- [ ] Hyperlinks are unreadable due to weird contrast between Pure Black and Dark Blue (see: About Dialog);
- [ ] Table headers look misplaced, probably leftover from Kuroi (see: Game List header);
- [ ] Hard to distinguish disabled options vs. unselected options, selected options look like disabled options;
- [ ] Gear icons on Game List are barely visible due to being almost the same color as the background;
- [ ] Memory Viewer's background is still the same as Kuroi;
- [ ] Delete Selection button on Save Data Manager is broken;

**Comment by AniLeo** [comment]
You're still finishing ModernBlue?

**Comment by themitosan** [comment]
For now i will leave this theme like the way it is (due to my work that has taken me all my time). If it is of your interest, you can merge this PR because I unfortunately have no time to do this theme the way I want.

**Comment by Megamouse** [comment]
Could you please rebase without the blue theme then? You can add the blue theme whenever you have time later on

**Comment by themitosan** [comment]
Well, what I really wanted I realized I would have to modify some lines of code in C ++ (something that I will not dare to do because I do not know much of this language), as soon as I get home I will finish this theme.

**Comment by Megamouse** [comment]
please use .qss fileformat

**Comment by AniLeo** [comment]
Can you squash changes into two commits - one for each theme?

**Pull request merged**
