### PR TITLE
FW installer: Fix firmware downgrading/upgrading/repair

### PR DESCRIPTION
**Pull request by elad335**
Empty directory before installing firmware, this ensures accurate firmware representation.
This fixes firmware in case there are unexpected previous files in there preventing correct behaviour by the PS3 application, such as from newer or older firmware or simply put in an accident by the user.

### CODE REVIEW

**Comment by arabek** [comment]
What if files put there not by accident? Shouldn't that be an option in the install menu? Like "do a clean firmware install". You shouldn't delete anything without consent.

**Comment by elad335** [comment]
Okay I will add it when available, although it is very not recommended to put anything inside any PS3 mounted directory because it has consequences on the emulated filesystem.

**Comment by elad335** [comment]
Furthermore, the PS3 applications themself can erase these files, especially if unknown to the application.

**Comment by arabek** [comment]
I get that, and i don't necessarily disagree. Still, there might be valid cases of someone replacing a file for debugging purposes (or even just replacing a font file with some local variant) ect. I'm not saying it is proper - i'm just saying an option would be nice to have.

**Comment by Megamouse** [comment]
Just mention it in the already existing dialog.

**Comment by elad335** [comment]
Added.

**Comment by Megamouse** [comment]
Wait a second. This might actually be horrible.
What if someone has the VFS setup to some unwanted folder? It will just purge all the data inside

**Pull request closed without merging**
