### PR TITLE
Dynamic XAudio version detection

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by raven02** [comment]
How about include XAudio 2.9 as well?

`XAudio2 version 2.9 ships as part of Windows 10, XAUDIO2_9.DLL, alongside XAudio2.8 to support older applications, and does not require redistribution.`

**Comment by Nekotekina** [comment]
Why? If XAudio2.8 works fine on Win 10, I highly doubt there is any difference, 2.9 only adds some features we don't use AFAIK.

**Comment by raven02** [comment]
I see .Fair enough.

**Comment by danilaml** [comment]
Needs testing on Windows 7. Also, does it show which version of XAudio was loaded somewhere?

**Comment by Nekotekina** [comment]
On Win7 it works fine. On 8.1 too it seems.

**Comment by danilaml** [comment]
@Nekotekina would probably be nice to log which XAudio lib is loaded.

**Comment by raven02** [comment]
Windows 10 tested okay as well

**Comment by raven02** [comment]
Humm sometimes i hits 

E {Audio Thread} XAudio2Thread : AddData() failed(0x88960001)
.

One my Windows 10 , i can see the following XAudio dll under c:\windows\system32
XAudio2_7.dll 507k
XAudio2_8.dll 11k
XAudio2_9.dll 565k

**Comment by Nekotekina** [comment]
Added log message for versions. It seems XAudio2_8.dll is small and probably just uses 2.9 internally, so it doesn't make sense to load 2.9 explicitly.

**Comment by danilaml** [comment]
`S {Audio Thread} XAudio 2.8 initialized` seems to be working fine.

**Comment by Nezarn** [comment]
@Nekotekina im getting this on windows10.

> ·E {Audio Thread} XAudio2Thread : AddData() failed(0x88960001)

**Pull request merged**
