### PR TITLE
Implement BRB opcode

### PR DESCRIPTION
**Pull request by kd-11**
This was mostly done in my repo anyway, but needed some tests to narrow down the direction bit. Fortunately diablo 3 ships with an rsx-compatible cg compiler.

### CODE REVIEW

**Comment by kd-11** [comment]
WIP since I need to clean up and rebase with current master; otherwise, should be ok

**Comment by kd-11** [comment]
Need testers to confirm that vulkan and dx12 are not broken; can't test them right now.

**Comment by MarioSonic2987** [comment]
Improves One Piece: Pirate Warriors a bit.

**Comment by AniLeo** [comment]
@kd-11 Can you please rebase for one to retest One Piece: Pirate Warriors

**Comment by Zangetsu38** [comment]
One piece, Sly cooper and Saint Seiya cxrash crash in DX12

**Comment by raven02** [comment]
@AniLeo ,  i built it and merged with master here. Feel free to test it.

https://ci.appveyor.com/api/buildjobs/ons0370x8bq09mx5/artifacts/rpcs3-v0.0.1-2017-02-26-67eacc3e_win64.zip

**Comment by clienthax** [comment]
Regression: Hatsune Miku: Project DIVA F 2nd NPEB02013

http://i.imgur.com/g4PeeGp.png

http://i.imgur.com/X6hWEEA.jpg

**Comment by raven02** [comment]
It looks like crash in every games using D3D12 renderer .

**Comment by kd-11** [comment]
DX12 is fixed; at least no worse than before. Needs someone to test that it fixes any game.
Refactored vulkan and opengl a bit as well.

**Comment by raven02** [comment]
DX12 works again in other game and just like previously . For Saint Seiya , it hits this error .

```
E {rsx::thread} RSX: FS build failed:D:\rpcs3\FragmentProgram.hlsl(197,12-55): warning X3570: gradient instruction used in a loop with varying iteration, attempting to unroll the loop
D:\rpcs3\FragmentProgram.hlsl(188,3-36): error X3511: unable to unroll loop, loop does not appear to terminate in a timely manner (248 iterations) or unrolled loop is too large, use the [unroll(n)] attribute to force an exact higher number

F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)
```

**Pull request merged**
