### PR TITLE
Some small change.

### PR DESCRIPTION
**Pull request by Zangetsu38**
Update README.md for VS 2015.
Restoring include location as before on "PPULLVMRecompiler.h", no need to call twice include "ExecutionEngine.h", "MCJIT.h" the called is already.
Needless to have 2 times include "setup.h" it is already present in "wxWdigets" as "setup0.h" there is no need to put one another, but the copied like this is a very good idea.
Add Webview project on .sln, "setup.h" updated is requiring.
Removing the win32 profile in "copy_setup_h.vcxproj"  it is not necessary.
Update sln buildbot for VS 2015.

### CODE REVIEW

**Comment by Bigpet** [comment]
Do we really need this wx webview stuff? It seems to me like it would just increase compile-time for no reason, if anything we need fewer of the wx projects not more

**Comment by Zangetsu38** [comment]
@Bigpet  I know, but the last "setup.h" the request.

**Comment by Bigpet** [comment]
I don't understand what that sentence means, the setup.h is a settings file that is supposed to be modified if we want to change the settings and in our case we don't need the webview stuff so we can disable that there.

**Comment by Zangetsu38** [comment]
@Bigpet 
Hmm I see thin, I thought it would be cleaner to have only one "setup.h" which would continue to update the submodule itself.
It seemed logical, but actually hmm.

**Comment by Bigpet** [comment]
relevant things merged in https://github.com/RPCS3/rpcs3/commit/e47493e81bfb2dc4813510d050b73b254fb319be

If you want to get the PPULLVMRecompiler.h changes merged I'd open another pull-request. I didn't really want to touch it since I didn't quite understand it.

As for the wx stuff, the solution to "we already have useless project dependencies" is not "one more won't do much" but "we should remove the useless ones"

**Comment by Zangetsu38** [comment]
@Bigpet 
I understand :) thx

**Pull request closed without merging**
