### PR TITLE
Linux automated build

### PR DESCRIPTION
**Pull request by Aaahh**
Didn't test yet

### CODE REVIEW

**Comment by Aaahh** [comment]
Travis won't pull in New changes sometimes Idk y
Also sorry for the spam
If this last one doesn't work I'm done

**Comment by al0xf** [comment]
What are you trying to do? Travis already uploads builds to rpcs3.net, appimages to be more specific. They are 99 % working now, and people are looking into it. 

Moreover no one is going to merge this PR that adds some other random repo to travis.yml, that is a security risk, and also unnecessary really.

**Comment by Aaahh** [comment]
For Linux, because on the website it says it's not there
Also yeah I figured that

**Comment by Aaahh** [comment]
That's a dummy account I made

**Comment by al0xf** [comment]
That's because they are not ready for the public. But travis.yml here already does everything we need.

**Comment by Aaahh** [comment]
Well that was a fun experience then
I'm looking for stuff to do whilst I wait for my laptop to come

**Pull request closed without merging**
