### PR TITLE
Clarify working GCC versions (exclude 6.1)

### PR DESCRIPTION
**Pull request by Enverex**
GCC 6.1 cannot compile RPCS3 due to a regression within GCC itself, so note that here as it's the current version that a lot of people are likely to be using, with a link to the bug that contains further information.

### CODE REVIEW

**Comment by paulsapps** [comment]
Isn't there already a PR for this?

**Comment by Enverex** [comment]
I can see one that changes some of the commands used in the compilation process, but I'm not seeing one that changes the actual info section at the top.

**Comment by GhettoGirl** [comment]
@Enverex This other PR is mine #1847, take a look at the changes and also read the comment by @danilaml.

> personally, I think that rpcs3 is highly dev oriented right now, so only experienced users are expected to try and build it. So some super robust warning/checking is unnecessary (I think even current check is a little bit to much, but it's fine).

I agree with this so I removed the GCC 6.1 check afterwards, because this emulator is not interesting for most end-users right now, and every experienced user knows whats going on when the compiler itself dies with a segmentation fault, so this check is more or less unnecessary right know. Maybe we can add this in the future when the emulator can run a decent amount of commercial games.

**Comment by danilaml** [comment]
I think that mentioning that some versions of gcc in readme is fine. It doesn't take much space.

**Comment by GhettoGirl** [comment]
Looks pretty good actually, I wanted todo the same https://github.com/RPCS3/rpcs3/issues/1802#issuecomment-227040035
> * GCC 5.1 ~ 5.4 (6.1 doesn't work) or Clang 3.5.0+
> * GCC 5.1 ~ 5.4 or Clang 3.5.0+
> * GCC 5.1+ (not 6.1) or Clang 3.5.0+
> * GCC 5.1+ (but not 6.1) or Clang 3.5.0+

But this one is way better than my suggestions, thb.

**Comment by Enverex** [comment]
Sure, I'm happy with either way. It's just worth letting users (or devs, basically anyone trying to compile for any reason) ahead of time that it will/won't work with their compiler. No point having people try and build only to be told at compile-time that it's going to fail when they could have been told before hand.

**Comment by AniLeo** [comment]
Needs to be rebased, someone please merge this when it is so it doesn't stay on hold for too long

**Comment by Enverex** [comment]
Done.

**Comment by GhettoGirl** [comment]
Any news on this?
Also needs rebase.

**Comment by Enverex** [comment]
Do you need me to do anything here are you just waiting on someone to merge it in?

**Comment by GhettoGirl** [comment]
this should be merged imo, hopefully someone does this soon

**Comment by Nekotekina** [comment]
Thanks.

**Pull request merged**
