### PR TITLE
rsx: Deadlock avoidance of accurate RSX reservations

### PR DESCRIPTION
**Pull request by kd-11**
Fixes games randomly hard-locking when the "Accurate RSX reservations" option is enabled.

### CODE REVIEW

**Comment by Asinin3** [comment]
Performance confirmed to be the same in MGS4 for me with RSX Reservations enabled. Strangely enough, this game is quite a bit faster with it enabled (but slower with it enabled in MGO).

**Comment by Linear524** [comment]
With this PR God of War 3 finally works without freezing, but framerate is now locked to 30 in all areas where it was 60 before... TLoU is now locked to 20 fps everywhere...

**Comment by kd-11** [comment]
> With this PR God of War 3 finally works without freezing, but framerate is now locked to 30 in all areas where it was 60 before... TLoU is now locked to 20 fps everywhere...

Wrong PR. That regression is caused by the new framelimiter. See https://github.com/RPCS3/rpcs3/pull/12052

**Comment by Linear524** [comment]
Oh, sorry KD-11, you right - previous commit broke max.framerate...
Anyway - thanks for Accurate RSX reservation fix :)

**Pull request merged**
