### PR TITLE
Update gcm_enums.cpp

### PR DESCRIPTION
**Pull request by luxox8**
testing if cod3 runs with this

### CODE REVIEW

**Comment by RainbowCookie32** [comment]
You can either setup a local development environment or use a personal fork for this. Why open a PR for this here?

**Comment by illusion98** [comment]
Needs a good 🔨 on this one.

**Comment by luxox8** [comment]
> You can either setup a local development environment or use a personal fork for this. Why open a PR for this here?

ohh sh.... hahaa sorry!

**Comment by elad335** [comment]
Needs lots of hw testing...

**Pull request closed without merging**
