### PR TITLE
[Need test] vm locking refactoring

### PR DESCRIPTION
**Pull request by Nekotekina**
The idea is simple, since g_mutex and g_range_lock usually go together, simplify locking mechanics and potentially make them more efficient.

### CODE REVIEW

**Comment by AniLeo** [comment]
Tested a few games to check the stability: 
- Red Dead Redemption
- Yakuza: Dead Souls
- NieR Replicant
- vsh.self


Seems to work fine, needs performance comparison tests

**Comment by kd-11** [comment]
Quick testing shows massive performance improvements in SPU-limited games.
MGS4 52->72 fps average (+40%)
Sonic Unleashed 41 -> 46 fps (+12%)
I'm checking more titles.

**Comment by Xcedf** [comment]
SPU Test some improvements

Master:
SPU Test v1.1.2 by GalCiv
SPU Task Avalanche completed in 5239 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 1549 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4589 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 6397 ms (PS3: 4443 ms)
SPU Integer Perf completed in 1225 ms (PS3: 8666 ms)
SPU Float Perf completed in 324 ms (PS3: 2379 ms)
SPU SpinLock completed in 3605 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 8072 ms (PS3: 3853 ms)
PUTLLC Perf completed in 1500 ms (PS3: 3364 ms)
PUT Perf completed in 1564 ms (PS3: 3984 ms)
Large PUT Perf completed in 1239 ms (PS3: 4454 ms)
--Completed 11 tests in 35305 ms--

PR:
SPU Test v1.1.2 by GalCiv
SPU Task Avalanche completed in 2704 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 1293 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4405 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 7038 ms (PS3: 4443 ms)
SPU Integer Perf completed in 1223 ms (PS3: 8666 ms)
SPU Float Perf completed in 324 ms (PS3: 2379 ms)
SPU SpinLock completed in 3867 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 7629 ms (PS3: 3853 ms)
PUTLLC Perf completed in 2322 ms (PS3: 3364 ms)
PUT Perf completed in 1534 ms (PS3: 3984 ms)
Large PUT Perf completed in 1237 ms (PS3: 4454 ms)
--Completed 11 tests in 33578 ms--

**Comment by AniLeo** [comment]
+22 average FPS in Sonic Unleashed in-engine cutscene on 5900HX

**Master**
Screenshot from 2022-04-30 16-52-15

**PR**
Screenshot from 2022-04-30 16-55-21

**Comment by AniLeo** [comment]
Drakengard 3 is around 20 FPS slower on PR for some reason, tried twice on each build and got consistent results

**Master**
Screenshot from 2022-04-30 17-25-12

**PR**
Screenshot from 2022-04-30 17-28-24

**Comment by Asinin3** [comment]
5950X - Keep in mind many other CPU's will see more gains than I did, or possibly gains where I saw none depending on bottleneck.
Metal Gear Solid 4: 30fps > 60fps lock (fps capped)
Persona 5: 75 > 78 FPS (Central Street) 
Sonic Unleashed: 53 > 56 (starting spot)
Red Dead Redemption: No change (seems same on intel)
Killzone 3: No change
R&C Quest for Booty: No change
Infamous: No change

**Comment by AniLeo** [comment]
+13 average FPS in Drakengard 3 in this scene that is not RSX bottlenecked

**Master**
Screenshot from 2022-04-30 18-01-45

**PR**
Screenshot from 2022-04-30 17-58-19

**Comment by FlexBy420** [comment]
Ryzen 5 3600, 
very small gain in Uncharted 3: Drake's Deception
no gain at all in Pirates of the Caribbean: At World's End

Master
obraz_2022-04-30_191941524
image

PR
image
image

**Comment by AniLeo** [comment]
+10 average FPS (+27%) on Metal Gear Solid 4 in Red Zone on 5900HX

**Master**
Screenshot from 2022-04-30 18-53-52

**PR**
Screenshot from 2022-04-30 18-51-09

**Comment by cipherxof** [comment]
Definitely seeing a slight performance improvement here in MGS4. Unfortunately, it's still not up to par with custom builds almost entirely because of the zcull hack that those include.

**Master (relaxed zcull):**

master

master2

**PR (relaxed zcull):**

pr

pr2

**PR (zcull hack):**

custom2

custom

**Comment by Hasster1** [comment]
It's not so great for me...
i5-4210u
Both HAZE and InFamous are stuttering on this pr (Infamous with disabled video output: master - 12-13 fps, while this pr gives me 8-12, Haze is stuttering as well.)
But Serious Sam 3 actually gives me more fps than master (24-25 on master, 26-28 on this pr ) without any stuttering. 

Is it because of my craptop?

**Comment by Asinin3** [comment]
@Hasster1 You need to test games with a SPU bottleneck, infamous isn't one of them, and I doubt Haze or Serious Sam are either. test some of the games mentioned here to improve largely and see what you find.

**Comment by Hasster1** [comment]
It's not about improvement, it's about regression. Even if these games are without SPU bottleneck, they're still affected negatively on my laptop, which isn't good. I don't want to lose any amount of fps that i've got.

**Comment by Asinin3** [comment]
Are you using RPCS3's CPU Scheduler, or do you have it set to Operating System? Ani found the PR to negatively impact the RPCS3 scheduler, but faster on OS scheduler. It's likely that the RPCS3 scheduler needs to be re-written to work with this change.

**Comment by AniLeo** [comment]
Just for reference, performance regressions on specifications that are very, very low end (i.e mobile dual core) are not really blockers, that's already waaay below recommended specifications

**Comment by Hasster1** [comment]
OS scheduler. Can't change it, since i have 4 threads.

**Comment by solarmystic** [comment]
On my **12400F**, SPU Test showed over 10% improvement in completion time. 

Master:-
SPU Test v1.1.2 by GalCiv
SPU Task Avalanche completed in 6221 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2252 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 5834 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 7696 ms (PS3: 4443 ms)
SPU Integer Perf completed in 2027 ms (PS3: 8666 ms)
SPU Float Perf completed in 620 ms (PS3: 2379 ms)
SPU SpinLock completed in 4445 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 10571 ms (PS3: 3853 ms)
PUTLLC Perf completed in 3138 ms (PS3: 3364 ms)
PUT Perf completed in 1609 ms (PS3: 3984 ms)
Large PUT Perf completed in 1723 ms (PS3: 4454 ms)
**--Completed 11 tests in 46139 ms--**

PR:-
SPU Test v1.1.2 by GalCiv
SPU Task Avalanche completed in 3451 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 1822 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 5591 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 7132 ms (PS3: 4443 ms)
SPU Integer Perf completed in 1989 ms (PS3: 8666 ms)
SPU Float Perf completed in 552 ms (PS3: 2379 ms)
SPU SpinLock completed in 5067 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 9855 ms (PS3: 3853 ms)
PUTLLC Perf completed in 2716 ms (PS3: 3364 ms)
PUT Perf completed in 1621 ms (PS3: 3984 ms)
Large PUT Perf completed in 1684 ms (PS3: 4454 ms)
**--Completed 11 tests in 41482 ms--**

**Comment by Xcedf** [comment]
PR is great speedups here and there, but a GTA V got major speed regresion with it
Master:
https://youtu.be/MT-VMVOG2sA
PR:
https://youtu.be/n9NHY0B6dP8
Logs:
[Master.log.gz](https://github.com/RPCS3/rpcs3/files/8597745/Master.log.gz)
[PR.log.gz](https://github.com/RPCS3/rpcs3/files/8597746/PR.log.gz)

**Comment by Darkhost1999** [comment]
PR
Screenshot 2022-04-30 155943
[PR.log](https://github.com/RPCS3/rpcs3/files/8597823/PR.log)
Master
Screenshot 2022-04-30 160221
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8597824/RPCS3.log)

**Comment by Hasster1** [comment]
Xcedf has got an Intel CPU, and Darkhost has got an AMD CPU. Majority of the tests are also have been made on the AMD CPUs. Might there be a difference between AMD and Intel's performance in other games?

**Comment by Asinin3** [comment]
Well no, I think there is something specific to the cpu arch or settings going on. For instance a user in our Discord (9400F) went from 25fps to 6fps in Midnight Club LA.. But Yahfz gained a few FPS in the game on his 12900K. In fact Intel gained a lot more perf on Alderlake than all ryzen users did from our findings so far. The results from this PR on a 12900K are very high, some benches might be posted here later. Should stick to discord for discussion though, so this PR doesn't get spammed.

**Comment by Nekotekina** [comment]
I pushed another commit, please report how it affects performance.

**Comment by Xcedf** [comment]
GTA V regression is fixed with update

**Comment by Hasster1** [comment]
With this new PR, HAZE works much better, but it still has a little stuttering issue, the same as infamous.
Infamous on master - 12-13 fps, without any stuttering.
Infamous on this pr - the same 12-13 fps, but there are frequent frame drops to 9-10 fps, which isn't good.
And i also found out, that keeping the game out of focus removes this stuttering.

**Comment by kd-11** [comment]
Performance is still improved as before on the 5900X

**Comment by Asinin3** [comment]
Performance is back to normal in new commit for the user with a i5 9400F in Midnight Club LA as well. I re-tested some games and performance improvements are still there for me in MGS4, Persona 5 and GoW3.

**Comment by cipherxof** [comment]
There seems to be a slight improvement for me on the latest commits with MGS4.

**Comment by Augusto7743** [comment]
11904 break GOWA performance.
0.0.21-13534 was game title 25 to 30 FPS and not issues in gameplay.
Since 0.0.22-13536 11904 game title is less of 12 FPS, in gameplay less 30 % speed and freezing temporary for few seconds the graphics.

**Comment by Augusto7743** [comment]
I had replied about that PR having slowdown in
https://github.com/RPCS3/rpcs3/issues/12811

being an topic ignored erroneously because the cpu used was an AMD FX ...

Users reporting better performance ... I seeing slowdowns ... strange
Thus being in same computer for test was installed windows 10 20H1 64.
The result was that PR have much better performance with games having more frame rate running much more fast than before.
However in Ubuntu 20.04 with the Linux appimage build in some games an huge slowdown that before was 30 FPS now is less 20 FPS and others using 30 to 40 % more cpu.

That PR only does better performance for windows and for Linux slowdowns.
That's an bug in the Linux build not related with the cpu and not is being reported.

I have enabled in /etc/security/limits.conf
* hard memlock unlimited
* soft memlock unlimited

In grub boot
mitigation=off

and other configurations ... nothing fix that issue.

Please have anyone with interest in see about it ?

**Pull request merged**
