### PR TITLE
FP: Implement REFL and LRP

### PR DESCRIPTION
**Pull request by raven02**

### CODE REVIEW

**Comment by MoochMcGee** [comment]
Shouldn't you implement LRP with mix in GLSL? I assume HLSL has something similar too.

**Comment by raven02** [comment]
Yep , we can also use the GLSL built-in mix() to do LRP .Probably i can do it in another PR once i figure out how to do in HLSL.

**Comment by raven02** [comment]
Done .Rebased

**Comment by Nekotekina** [comment]
Needs rebase

**Comment by raven02** [comment]
@Nekotekina Should be okay to merge

**Pull request merged**
