### PR TITLE
[TESTERS NEEDED] RawSPU: fix race condition in RunCntl stop request

### PR DESCRIPTION
**Pull request by elad335**
Test #7522 mentioned regressions from #7304.

### CODE REVIEW

**Comment by jeremybris** [comment]
@elad335 If you haven't already, you should look into #5591.

#7304 ubiquitously effected these games. It did not fix the bug, but altered it.

**Comment by web1018** [comment]
This PR fixes Resistance: Fall of Man Out of Bounds Bug where the players start flying towards the sky and out of bounds. After testing it several times using the options of LLVM Recompiler and default settings, the bug no longer occurs. I will add these details to #7492 once this PR is completely merged and a full indication is given that this issue doesn't occur again. Great Work, Thanks

**Comment by lainiwaku** [comment]
i confirm, Resistance: Fall of Man fixed with that build

**Comment by SpeddieSwagetti** [comment]
This pull request fixes Ratchet and Clank: ToD level collision. (Insomniac Engine similar to Resistance)
Usually upon loading level ratchet would fall through the level numerous times and eventually, collision comes back. With this build, collision works 100% of the time.

**Comment by elad335** [comment]
The regression was fixed in #7542, closing as it does not match cell documentation and false reports.

**Comment by lainiwaku** [comment]
#7542 didn't fix it through

**Pull request closed without merging**
