### PR TITLE
[TESTERS NEEDED] Update VMA library

### PR DESCRIPTION
**Pull request by PawelGribov**
update VMA library to 3.1.0 dev 5677097

### CODE REVIEW

**Comment by AniLeo** [comment]
Related ticket: #13045

**Comment by kd-11** [comment]
This needs to be tested on min-spec (i.e 512MB VRAM).
It's not easy to tell what changed which is why we don't really bother upgrading this thing as we already tuned for it.
My debugging run for memory behavior is always running ACiT combat-heavy scenes with VRAM limit set to 512MB in the config (there is a debug override for this in the vulkan section)

**Comment by Augusto7743** [comment]
In config.yml in video section the VRAM allocation limit (MB): default is 65536.
For test can be used the GPU video ram size ( 1 GB = 1024000 ) value ?

**Comment by RipleyTom** [comment]
Sorry as we don't want to sift through those changes and for security reasons we'd rather limit dependency updates to staff members.

**Pull request closed without merging**
