### PR TITLE
Improve Memory Viewer

### PR DESCRIPTION
**Pull request by flash-fire**
Add label that distinguishes which offset in memory you are looking at.  Also, fix width of address text edit.

### CODE REVIEW

**Comment by Megamouse** [comment]
I've sent you a proper fix on discord

**Comment by Nekotekina** [comment]
Does it fix possible crashes?

**Comment by Megamouse** [comment]
No. This is only a minor addition of labels

**Comment by flash-fire** [comment]
This is why you should never clean up branches while you have a PR rofl.

**Pull request closed without merging**
