### PR TITLE
GUI: Rephrase trophy "eraned/not earned" to "unlocked /locked"

### PR DESCRIPTION
**Pull request by elad335**
Official trophy terminology.

### CODE REVIEW

**Comment by Megamouse** [comment]
🍿 🏆 🔒 🔓

**Comment by elad335** [comment]
I guess its not worth the hassle over a few words.

**Comment by Megamouse** [comment]
You could make a poll and ask donors.
The uppercase stuff was okay i guesa

**Comment by dio-gh** [comment]
The official trophy terminology is earned, not unlocked. I've already linked a video as proof in the other PR thread yesterday.

**Comment by elad335** [comment]
SCE_NP_TROPHY_ERROR_ALREADY_UNLOCKED, but it doesnt really matters.

**Comment by dio-gh** [comment]
That's not a user-facing string, it'd be like if the PCSX2 guys referred to the MECHACON as MEKACON, because that's how the Sony devs referred to it in the bios.

But yeah, I only bumped that other thread so that there'd be one PRs less dangling, it's genuinely low prio.

**Pull request closed without merging**
