### PR TITLE
[WIP] Add compatibility database file inside Appveyor and Travis artifacts

### PR DESCRIPTION
**Pull request by scribam**
I hope it could reduce the number of people having trouble to download the compatibility database file by providing the file directly bundled in the artifacts.

@hcorion Would you mind checking the change for Travis? I am not 100% sure about where the folder "GuiConfigs" is, before building the AppImage. I am relying on your experience 😉

### CODE REVIEW

**Comment by danilaml** [comment]
It might be worth enabling it only on master branch to decrease the load.

**Comment by AniLeo** [comment]
We need to figure out how to have users install openssl (windows) for other future functionality like pinging a check for updates API

**Comment by danilaml** [comment]
@AniLeo they can be simply asked to update it manually. But anyway, as I said in the original PR, the compat DB doesn't make much sense or serve much value with how rpcs3 is developing. There is no reason to update compat db without updating rpcs3 itself.

**Comment by twdarkeh** [comment]
@AniLeo The only real way to do that would be to just accept the inevitable ban in countries where OpenSSL is illegal and bundle it with the emulator.

**Comment by hcorion** [comment]
Like the US?

**Comment by danilaml** [comment]
This discussion is kind of off-topic to this PR. Also, as I said several times - it's not even a problem because the functionality itself is useless if not harmful. No other emulator found a need for online updating the compat DB because by-design it's tied to the emu version used.

**Comment by Megamouse** [comment]
That's not true. At the rate this is being updated and considering regressions you can't really assume the current compatibility list is tied only to the current master build. New games could get added in the time you did not update the build itself. Also many just copy over the exe and do not care about the rest. including us devs.

**Comment by danilaml** [comment]
@Megamouse 
>At the rate this is being updated and considering regressions you can't really assume the current compatibility list is tied only to the current master build. 

Don't you see a contradiction here? Since rpcs3 updates so frequently with possible regressions introduced you can't assume that DB is valid for anything other than the most recent version. If it's not - then it's a bug, simple as that. If the user uses the old version the compat info gives him nothing. 

> New games could get added in the time you did not update the build itself.

So update the build or use the website to look up. Why this should be built in the emu? It's nowhere near the point where you may want to stay on some old build for an extended period of time.
>Also many just copy over the exe and do not care about the rest. including us devs. (in particular with test builds)

So how'd you expect them to copy openSSL dlls and other stuff?  If you care enough about recent compat lists to go though the hoops with openSSL you can as well just copy one additional file from the archive. All the others can continue to not care (also, it shouldn't be an issue with appimage).

**Comment by Megamouse** [comment]
I don't see the problem. If users can't use the download feature then they get the DB through this PR.
everyone's happy. I like the feature and as it was requested by many users. And if they go through the honest process of dumping their games instead of simply pirating it they might even be capable to do one more step and get the dlls

**Comment by danilaml** [comment]
@Megamouse then they can obtain DLLs from other sources as well. The link can be added in the readme alongside VC++ Redistributable. Anyway this discussion is definitely not related to this PR and can be moved elsewhere (though I already expressed my opinion).

**Comment by AniLeo** [comment]
What about the web API abnormal scenarios:

- API return_code: -2 (Maintenance);
- API return_code: -1 (Internal error);
- Cloudflare forces 5 seconds cooldown to access the page due to high load;
- Page is inaccessible for some reason, web server issues;

Wouldn't this throw garbage into the compat_database.dat file?

**Comment by AniLeo** [comment]
Superseded by #4139 which overhauls appveyor.yml

**Comment by hcorion** [comment]
Not entirely, 4139 doesn't cover travis.

**Comment by AniLeo** [comment]
Hm, that's right, just superseded windows part then

**Comment by scribam** [comment]
Closing as #4139 is merged.
Regarding Travis, I would like to avoid adding specific code in RPCS3 to make it work correctly with AppImage. I also think Linux users have less issues when downloading the compatibility database so I don't have the intention to work on this feature anymore.
Thank you for all your feedbacks, job is done for AppVeyor 🙂

**Pull request closed without merging**
