### PR TITLE
Add caching for dependencies in appveyor.yml

### PR DESCRIPTION
**Pull request by grimd34th**
This should allow for quicker builds by not having to retrieve the files for every single build, allowing it to pull from cache instead of the google drive and dropbox.

### CODE REVIEW

**Comment by AniLeo** [comment]
Can submodules be cached until they don't check out and need updating? Build takes a while cloning them

**Comment by grimd34th** [comment]
It's possible, however unless the appveyor is a Premium or Pro account, you might run into a [size limit](https://www.appveyor.com/docs/build-cache/#cache-size-beta)

**Comment by hcorion** [comment]
I don't think this PR is good, have you tested to make sure this is actually faster? From what I've read from the Travis docs, it's actually faster to download rather than caching them, caching is supposed to only be for files that need to be compiled and can speed up the build by caching the compiled files, I would assume appveyor would be similar.

**Comment by Nekotekina** [comment]
How does it behave if downloaded files change?

**Comment by grimd34th** [comment]
I didn't know how you would prefer it to detect that, however I can change the commit to invalidate on the change of appveyor.yml, so when you update the yml with the new urls it invalidates the whole cache

**Comment by Nekotekina** [comment]
Sounds good.

**Comment by danilaml** [comment]
Yeah, adding dependency on appveyor.yml sounds like a good idea. The file should rarely change without updating our deps anyway.

**Comment by grimd34th** [comment]
Added the dependency on appveyor.yml to clear the cache

**Pull request merged**
