### PR TITLE
Support of custom configurations

### PR DESCRIPTION
**Pull request by O1L**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
@O1L Little Problem, configuration rpcs3 not save after exit, allayws rest on Interpretter 1

**Comment by O1L** [comment]
Damn! I missed one line. Add this in the SettingsDialog.cpp:
cfg->core.ppu_decoder = rbox_ppu_decoder->GetSelection();

**Comment by Zangetsu38** [comment]
@O1L ok, and for DX12 not works ?

**Comment by Zangetsu38** [comment]
ok, thx fixed here https://github.com/RPCS3/rpcs3/pull/1242

**Comment by vlj** [comment]
DX 12 does no longer work ????

**Comment by Zangetsu38** [comment]
@vlj for me yes

**Comment by DHrpcs3** [comment]
@vlj, yup, does not work. But can be easily fixed by adding one line to SettingsDialog.cpp as say @O1L

**Comment by Zangetsu38** [comment]
@O1L I could set, but the "Compile llvm" refuses to be selected.
the rpcs3.new.ini saves well but when he presents the stimulus rpcs3 "ppu interpreter".
And even without closing, if I choose llvm and I launch a game, the game turns into one interpreter.
The llvm does not work anymore: /

**Comment by Zangetsu38** [comment]
@O1L llvm fixed in my pr https://github.com/RPCS3/rpcs3/pull/1242

**Pull request merged**
