### PR TITLE
rsx: Misc fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Fix GL flushing of D24S8
- Fix FragDepth register initialization to match hardware. If shader claims to export Z, the default value if nothing is written to FragDepth is actually 0
- Fix a bug in intersection tests when incoming and outgoing surfaces have different bpp.
- Improve memory usage by freeing 'storage' blocks if they get inherited by an actual framebuffer.
- Reimplement ARGB8 textures to be presented as plain BGRA8 by byteswapping. This should make all APIs uniform since BGRA is guaranteed to be supported by every API. Also removes needs for hacks needed to get byteswapped data from Cell (blit engine, RCB).
- Fix OpenGL deadlock when using WCB and loading final framebuffer from CPU.
- Fix stale references to invalidated surfaces in texture cache.
- Fix a minor regression bug calculating valid memory range in blit engine. (https://github.com/RPCS3/rpcs3/issues/6379)

### CODE REVIEW

**Comment by SutandoTsukai181** [comment]
Didn't fix #4380 yet. bars are still missing, tried with a lot of different configs

**Comment by Xcedf** [comment]
Seem's to fixed performance regression in GoW Ascension from https://github.com/RPCS3/rpcs3/issues/5983

**Comment by MsDarkLow** [comment]
Yakuza Ishin shows incorrect colors _(people call it the shrek effect)_ and also noticed a performance drop in the main menu (from 39 to 35)
<details>
<summary>Yakuza Ishin</summary>

Master
IshinMaster
PR
IshinPR
</details>

Master RSX Capture & Renderdocc: https://drive.google.com/open?id=1pcT3h0nNu9XCrDvPaM3p7fEsOF4HaPQf

PR RSX Capture & Renderdocc: https://drive.google.com/open?id=1l46WGc8MBMavB4hdirP9xJUmX_7Rohky

**Comment by Megamouse** [comment]
gl range invalidation fixes the Blazing Angels 2 crash with OpenGl:
image

**Comment by Realmantik** [comment]
I got 
`F 0:01:01.614862 {RSX [0x013ccd4]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:383)` 
in Battle: Los Angeles using OpenGL
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3517875/RPCS3.zip)

**Comment by stride21** [comment]
This PR fixes #5918, Ratchet and Clank Future: Tools of Destruction goes ingame again with OpenGL.

**Comment by xddxd** [comment]
Fixes #6282.

**Comment by Illynir** [comment]
vesperia

This PR breaks Tales of vesperia (Demo and full game). If you want to try it yourself it's very easy, the demo only makes 230 MB, downloadable very easily.

**Comment by Kravickas** [comment]
TDU2 first time rendering gfx
It needs WCB + RCB
obrazek

**Comment by Realmantik** [comment]
> 
> 
> vesperia
> 
> This PR breaks Tales of vesperia (Demo and full game). If you want to try it yourself it's very easy, the demo only makes 230 MB, downloadable very easily.

Did you try master build? The same result on the master. Left half of the screen became wrong displayed in some other PR.

**Comment by jenci8888** [comment]
Sonic All Star Racing Transformed first time rendering GFX
It needs WCB + RCB
image

**Comment by QuaiGoner** [comment]
image
image
BO1 shows GFX for the first time!
But on another map of zombies i had a crash with this error.
Log of crash without res. scaling:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3520721/RPCS3.log.gz)

Also reasolution scaling is broken with that game and it turns GFX in green broken mess.

**Comment by Illynir** [comment]
> 
> 
> > vesperia
> > This PR breaks Tales of vesperia (Demo and full game). If you want to try it yourself it's very easy, the demo only makes 230 MB, downloadable very easily.
> 
> Did you try master build? The same result on the master. Left half of the screen became wrong displayed in some other PR. Update: The game regressed after #6357 .

My Master was not up to date with some commit missing, it seems. That's why I hadn't seen this problem on Master (I had tried, of course). It's my fault, the problem oof Tales of Vesperia comes from #6357 like you said.

**Comment by Xcedf** [comment]
Few improvemetnts here
MGS3 HD, some objects or parts were never rendered before, fixed now
Before:

After:


Uncharted 2, fog now rendered
Before:

After:

**Comment by BSoDGamingYT** [comment]
Killzone 2 now crashes when loading in-game on this PR with the below error

F {RSX [0x002e240]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\surface_store.h:359)

It is able to progress into gameplay, albeit with broken graphics on master. 

Tested on both base game and with update

**Comment by stride21** [comment]
Ratchet and Clank Future: Tools of Destruction is getting a similar error in this PR.
E {RSX [0x2123be8]} RSX: Resource was destroyed whilst holding a resource reference!
F {RSX [0x2123be8]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\surface_store.h:359)

**Comment by ju2ef1986** [comment]
MGS 2 is almost perfect now. The only thing that is broken is semi-transparent characters (only some of them).

image

image

image


This is the bug:

image

It happens even with Write Colour Buffers enabled

Video of this uploading here:

https://www.youtube.com/watch?v=0S-NoIGKxZc

**Comment by ju2ef1986** [comment]
It looks like all graphic issues in MGS 3 are now fixed. Only thing that remains is some FPS drops here and there but I don't think it's within the scope of this PR. Amazing job!

**Comment by kd-11** [comment]
I think that fixes the regressions caused by this PR itself.

**Comment by Snakegodeater** [comment]
MGS2 AND 3 Fixed .Now we wait for MGS4 :D

**Comment by ju2ef1986** [comment]
> MGS2 AND 3 Fixed .Now we wait for MGS4 :D

MGS 2 has a new bug where character models are semi-transparent. I am waiting for newest commit to compile on appveyor and will retest.

**Comment by ju2ef1986** [comment]
MGS 2 transparency of character models now fixed. Amazing work!

**Comment by web1018** [comment]
Dantes Inferno Freezes during cutscenes and while trying to move objects in this PR. Though Freezing does occur in the Master version but during fight scenes mainly. In this PR it happens different and with a different error. The outputted error is seen below the image.

Capture221
Capture21

**Comment by BSoDGamingYT** [comment]
Killzone 2 regression is fixed with the latest commits

**Comment by stride21** [comment]
Ratchet and Clank Future: Tools of Destruction is fixed.

Killzone 3 is also fixed. 

killzone fixed

**Comment by web1018** [comment]
Dantes Inferno Cutscene Freeze is fixed , but Still freezes with moving objects. 
F {RSX [0x04e7e54]} RSX: class std::runtime_error thrown: [attrib buffer] Working buffer not big enough, buffer_length=402653184 allocated=5759232 requested=3856196820 guard=4194304 largest_pool=314880


Capture112

**Comment by Snakegodeater** [comment]
On this PR i get this line around Raiden character model but only in this rooom !
Χωρίς τίτλο1

**Comment by Snakegodeater** [comment]
> MGS2
> On this PR i get this black line around Raiden character model but only in this rooom ! Haven't tested Further Or on tanker chapter yet
> 4790k+R9 380
> Χωρίς τίτλο1

Update: Tested the tanker Chapter a little and Everything seems fixed .The codec , The Laser pointer and some objects that are not rendered before. However i Get half of the FPS at some instances on both on MGS2 And 3 But i think that's on another PR

**Comment by micaelis72** [comment]
Some textures still missing on MGS2 HD

screenshot-2019_08_21_02_00_21

Specs:

GTX 1060 6Gb
64Gb Mem
i7-7700HQ
Mobile

If any logs are necessary, let me know.
This is games is this close to be perfect!

**Comment by ju2ef1986** [comment]
> Some textures still missing on MGS2 HD
> 
> screenshot-2019_08_21_02_00_21
> 
> Specs:
> Fedora 31 ( driver 430.40 )
> 
> GTX 1060 6Gb
> 64Gb Mem
> i7-7700HQ
> Mobile
> 
> If any logs are necessary, let me know.
> This is games is this close to be perfect!

I had the same issue but it's fixed now. Can you test after deleting the cache folder content?

**Comment by MarioSonic2987** [comment]
Rendering breaks in GTA IV on certain locations.
<details>
 <summary>Images</summary>

image
image
</details>

[RenderDoc VK](https://drive.google.com/open?id=1rxPCPp_mzHo_ks7HBNMuj6DQXTMWqN9w)

**Comment by dyno0** [comment]
This PR fixes the PPU memory Access violation in Resident Evil 4 while using the Vulkan renderer, without having to force CPU blit emulation.

**Comment by kd-11** [comment]
@MarioSonic2987 My pascal GPU is not compatible with maxwell-captured RDC, consider providing RSX capture instead.

**Comment by MarioSonic2987** [comment]
[RSX Captures](https://drive.google.com/open?id=1gRK6E3QWQXqqeiKTANpdN0IwpQMyv16X)

**Comment by micaelis72** [comment]
MGS2 HD still misses the laser point in the game. This is supposed to be fixed in this PR. This close to this game be fully playable...

**Comment by stride21** [comment]
This PR fixes the flickering black dots on the leaves on the main menu of Uncharted 2.

**Comment by kd-11** [comment]
Restored performance which had degraded due to CPU decoding of textures. OpenGL still uses software decode which is rather slow at the moment, will fix it later.

**Comment by ju2ef1986** [comment]
> MGS2 HD still misses the laser point in the game. This is supposed to be fixed in this PR? This game is close to be fully playable...

I can see the dot just fine. Can you delete cache folder content

Look at the left leg below
Screenshot_20190821-181725

**Comment by kd-11** [comment]
I pulled the texture optimization commits. They will be reissued in a separate PR.

**Comment by web1018** [comment]
This PR fixes Dantes Inferno Cutscene Freeze and the freezing that occurs during object interaction.  But the game still Freezes during the fights with enemies.

**Comment by ruthan** [comment]
I tried the luck with broken Conan palette its still the same.

**Pull request merged**
