### PR TITLE
Joystick support using mmsystem library on windows

### PR DESCRIPTION
**Pull request by georgemoralis**
Tested on a few joysticks it should be ok. To work you must select MMJoystick on pad selection in settings

#2266

### CODE REVIEW

**Comment by andre4688** [comment]
My test the Joystick ps3 unofficial sony my comando  life gaming series 
I saw the select Button and started misconfigured  Could  accelerate response Buttons
I do not know the original ps3 official Joystick well

**Comment by andre4688** [comment]
flash-fire   'Should be ISO, push the button to start thinking select Button And contrary

**Comment by AniLeo** [comment]
@andre4688 Can you please try expressing yourself in a more clear way? 

Also, there are a few binding issues as of yet, DS4 controllers aren't mapped correctly yet

**Comment by georgemoralis** [comment]
I made the buttons configurable. So far there isn't a gui for that but you can use the above file (place it on rpcs3 dir). If your joystick has swap buttons with the default setting you can try swap the values for the wrong buttons

[config_mmjoystick.zip](https://github.com/RPCS3/rpcs3/files/766405/config_mmjoystick.zip)

**Comment by Bryceless** [comment]
Has controller analog deadzones been implemented yet?

**Comment by Bryceless** [comment]
For anybody who has a Dualshock 4 with the official adapter that Sony released, here is a config file based on the one that georgemoralis uploaded that should work with a proper control layout.

I'm not sure if it will work with Dualshock 4 controllers via USB or Bluetooth, but if somebody is having issues, I can only make a USB version of it, due to me not having a Bluetooth adapter atm.

[config_mmjoystick DS4.zip](https://github.com/RPCS3/rpcs3/files/778182/config_mmjoystick.DS4.zip)

**Comment by Bryceless** [comment]
For anybody who wants to use a Dualshock 4 controller with RPCS3, here's a config file that will give you proper controller mapping for DS4 controllers.

This is config is designed for when using the official adapter that Sony released, and I have no clue if it works properly when connected to USB or through Bluetooth. If you find any problems, make sure to PM me, and i'll figure out any problems you may have.

[config_dualshock4.zip](https://github.com/RPCS3/rpcs3/files/778233/config_dualshock4.zip)

**Pull request merged**
