### PR TITLE
[WIP] SPU LLVM: use FMA with approx xfloat when available

### PR DESCRIPTION
**Pull request by Nekotekina**
Should improve perf and accuracy for modern processors, but will be slower on older CPUs.

### CODE REVIEW

**Comment by Cristallix** [comment]
Which CPU are you considering old ? Sandy ? Haswell ?

**Comment by Illynir** [comment]
I already told you on Discord in #testers but I'm putting it here just in case.

it doesn't work on GoW 3, RDR, etc... It behaves as if the FMA is not used at all. On uncharted 1 it "works" and you get 1/2 FPS but I think Uncharted 1 does not use the FMA.

Tested on Ryzen 2700X and Intel 8700K.

**Comment by Nekotekina** [comment]
Updated PR.

**Comment by Xcedf** [comment]
didn't noticed any performance differences yet, but as https://github.com/RPCS3/rpcs3/issues/6616 also fixes https://github.com/RPCS3/rpcs3/issues/6616

**Comment by Illynir** [comment]
GoW 3 is fixed now, +2 FPS on the menu, 53 -> 55.

**Comment by CookiePLMonster** [comment]
This breaks ingame sound in Need for Speed: Most Wanted and also numerous Most Wanted 2 prototypes. Menus and intro FMV are fine, but as soon as it jumps to gameplay, sound dies and/or is just beeps.

**Pull request merged**
