### PR TITLE
gl/vk: Bug fixes and improvements

### PR DESCRIPTION
**Pull request by kd-11**
Includes the following fixes
- Vulkan: properly upload signed normalized integer formats
- GL: emulate signed normalized integer formats (Nvidia does not support texture buffer access with some formats)
- GL: use persistent mapped buffers by default. An option is added to disable this option to allow debuggers to properly attach when tracing draw calls
- GL: do not re-update program uniform buffers when nothing has changed
- GL: do not rebind attribute buffers every draw call. They never change.
- GL: fix a regression bug with missing primitives

The performance improvements are mostly only visible at high draw call counts, greater than ~1500 calls per frame as the cost adds up quite a bit.

### CODE REVIEW

**Comment by kd-11** [comment]
I added a checkbox on the graphics settings panel to control use of legacy buffers. Let me know if alternative placement is desired. I placed it on the right since that is where the other debug options are. Maybe I can move vsync to the left to give the UI a more balanced look.

**Comment by raven02** [comment]
Or looks like this 

untitled

**Comment by kd-11** [comment]
@raven02 That's what I was asking about. Debug options are on the column to the right and RSX functionality is on the left (R/W buffers). Should we mix the two, or move Vsync to the left and the new option takes its place? I can change it to be like in your picture if thats ok.

**Comment by raven02** [comment]
I think those options are putting in random but no special meaning . Feel free to do it as the way in the picture . Thanks

**Comment by kd-11** [comment]
UI has been updated. Just check if anything seems to have regressed on opengl especially with legacy buffers disabled. It would manifest as flickering visuals where there were none, but I dont expect any ps3 game to use more than 256M of memory in one go.

**Comment by raven02** [comment]
Water effect in 1942 Joint Strike seems to be broken with this commit . However , the bullet visiblity got fixed in this commit when compared with master.

**Comment by kd-11** [comment]
Nice catch. It should be fixed now, rounding up all remaining visual glitches with 1942 joint strike.

**Comment by raven02** [comment]
Cool .Merged.

**Pull request merged**
