### PR TITLE
GUI: Adjust capitalization for CPU settings tab

### PR DESCRIPTION
**Pull request by MSuih**
Capitalised every word for the items in CPU tab to make it consistent with GPU, Debug and Audio tabs. I decided to leave Emulator tab untouched for now as it is more verbose than the other tabs but I (or someone in another PR) can alter it as well if desired.

### CODE REVIEW

**Comment by MrHulaHoop** [comment]
Truth be told, I think it would be better to change the GPU and Audio tab to match the rest. IMO using sentence case for the toggles inside the box look better than title case. 
Also, it would generally be a more appropriate use of capitalisation.

**Comment by MSuih** [comment]
That's possible as well but I feel like the options themselves should be rephased for that, they currently look off without title case. But I'm not a native English speaker and my languange only capitalizes the first word for titles, so I'm not an expert on this.

My idea is to merge these changes and keep the capitalisation rules as-is for now, and rewrite the options pane once this project enters beta stage.

**Comment by Zangetsu38** [comment]
yes, and no, in english is same, Only CAP on first word, not other, and for need need change all for have only one CAP in first word.
Other user have already open issue before for proposed change all that in the code

**Comment by MrHulaHoop** [comment]
Yeah, english follows the same rules for sentence case (capitalize only the first letter of the first word).

I don't think we need to wait till Beta release to fix something this minute. It would hardly take any time to do it properly. I also don't see why the options need to be rephrased. They still seem perfectly fine in sentence case.

**Pull request closed without merging**
