### PR TITLE
High-Resolution Game Background for loading

### PR DESCRIPTION
**Pull request by elad335**
Some games are missing PIC1.PNG (the previous default) and instead were resorting to ICON0.PNG which is a low-resolution image. Do something else entirely for image picking - pick the image path between ICON0.PNG, PIC0.PNG, PIC1.PNG, PIC2.PNG and PIC3.PNG that exists and it is the largest in disk size. (assume it is the highest resolution one)

Before:
image

After:
image

### CODE REVIEW

**Comment by Megamouse** [comment]
This completely ignores the existing logic of prefering the update path.
Also, please stop merging shit like this without any review or discussion.
This is not your personal project

**Comment by Kazeira** [comment]
I don't think it's necessary to check the file sizes, the expected resolution are PIC1=PIC3>PIC0>PIC2>ICON0.
By the way, the menus don't show the correct icons for Disc games + HDD data. On real hardware every disc game still use the files (ICON/SND0/PIC...) from the disc, the files in the hard drive are only used inside the 'Game Data Utility' folder.

So in the menu, Disc files should have priority over HDD files for Disc games.
And checking the background loading should be more like
Disc game: PIC1/PIC3(Disc) > PIC1/PIC3(HDD) > PIC0(Disc) > PIC0(HDD) > PIC2(Disc) > PIC2(HDD) > ICON0(Disc)
HDD game: PIC1/PIC3 > PIC0 > PIC2 > ICON0 (all in the HDD of course)

I also want to add that using the regional files depending of the console language selected could be great (ICON0_02.PNG... for french for example), and use the default files (ICON0.PNG...) only when missing, like a real PS3.
But yeah I know, combined with the background loading, it makes a lot of checks.

**Comment by Megamouse** [comment]
This is not the PS3 menu. This is the RPCS3 interface.
We are not trying to do a 1:1 copy of the PS3 XMB

**Comment by Megamouse** [comment]
Since the console language is not a UI setting, we don't really care for the icon localization at the moment.
It's something we'd have to integrate properly first.

**Comment by Megamouse** [comment]
We could probably add it for the background image already though.

**Comment by Kazeira** [comment]
Of course I understand, my point about the languages was just a bonus, these kinds of things are low priority since having a working emulator is always better than a fancy UI.
I only wanted to point out that:
- Checking the file sizes is overkill since we theoretically already know their resolution.
- For some games the HDD icons aren't ideal (Beyond Two Souls, Ratchet & Clank: A Crack in Time, Ratchet & Clank: All 4 One, Sonic & All-Stars Racing Transformed, The Sims 3...), so instead of checking first in the HDD and then the Disc, it would be better do the opposite.

**Comment by elad335** [comment]
Even if resolution is the same, bigger file size also indicates more detail or vibrant colors usually, so from RPCS3 perspective it is a pretty good measure for image quality that even the developers may not have thought through.

**Pull request merged**
