### PR TITLE
rsx: Fix fog behaviour

### PR DESCRIPTION
**Pull request by kd-11**
- This is likely incorrect but hw tests are still inconclusive so this is the best bet right now.

Possible fix for https://github.com/RPCS3/rpcs3/issues/5066

### CODE REVIEW

**Comment by namkazt** [comment]
Diablo 3 :ROS working again! 

Great work
dwad3212

**Comment by Rpcs3tester** [comment]
@kd-11 thanks it's fixed

**Comment by Emulator-Team-2** [comment]
Fixed regression in:
-After Burner Climax
-Dragon Ball: Xenoverse

**Comment by i2puni** [comment]
"Catherine" black texture Fixed !

**Pull request merged**
