### PR TITLE
Rsx: Fixes

### PR DESCRIPTION
**Pull request by vlj**
This PR fixes some defect of RSX/cellResc found while investigating SH3.
It fixes character rendering and flickering screen. I suspect more games can be impacted too.

### CODE REVIEW

**Comment by vlj** [comment]
Rebased

**Comment by vlj** [comment]
Normally with this PR rpcs3 is able to render SH3 HD mostly correctly (at 40-60 fps here). The geometry and the texturing are right but shadows and post process effects are still wrong.

**Comment by tambry** [comment]
@vlj Needs to be rebased.

**Comment by vlj** [comment]
Rebased

**Comment by vlj** [comment]
rebased

**Comment by vlj** [comment]
something prevents from merging ?

**Comment by B1ackDaemon** [comment]
Sleeping Nekotekina in that time, i guess :P

**Comment by tambry** [comment]
@vlj All your PRs need a rebase again

**Comment by vlj** [comment]
Rebased

**Pull request merged**
