### PR TITLE
DX12: depth buffer compare perform only if depth testing is enabled

### PR DESCRIPTION
**Pull request by raven02**
This fixes the Disgaea 3 startup error in D3D12

### CODE REVIEW

**Comment by raven02** [comment]
@kd-11 , writing to depth buffer should also only enable when depth testing is enabled, what do you think? (DX12 and Vulkan are not but GL does)

**Comment by zminhquanz** [comment]
have it fix on Disgaea 4 and The Guide Fate paradox

**Comment by kd-11** [comment]
@raven depth masking and testing are different things. It is legal to write to the depth buffer without a depth test in place.

**Comment by kd-11** [comment]
@rave02 If you look at the GL code, you can see that depth mask is set separately and depth func is only changed if depth test is enabled. However GL is a state machine; the previously set depth func remains unless depth testing is enabled and not set to nothing as your fix does.
Unless there is a driver bug, depth func should have no effect if depth test is disabled.

**Comment by raven02** [comment]
i see.Thanks @kd-11 .

**Comment by kd-11** [comment]
This seems more and more like a driver bug since DX12 has no comparison func with enum 0 which is what is set when you use this fix. It usually falls back to D3D12_COMPARISON_FUNC_LESS

**Comment by raven02** [comment]
I'll submit a bug report on Nvidia official forum.

**Comment by danilaml** [comment]
@kd-11 why do you think it's a driver bug and not an emu bug? The emu supplies dx12 with `0x0` value and as stated in mistakenly closed ( @raven02  ) issue https://github.com/RPCS3/rpcs3/issues/1672 it's a regression in 0.0.0.9

**Comment by raven02** [comment]
This is not a hack , it should be the right thing to do

**Comment by kd-11** [comment]
@danilaml this fix is setting depth test function to invalid (thus setting it to less by driver fallback). This should not be necessary since depth testing is already disabled. The depth func should not matter if no depth test is enabled and the fact that that is not the case is rather odd. Of course the only way to confirm the correct behaviour is to check it against the reference rasterizer.

**Pull request merged**
