### PR TITLE
[MSVC] Ensure disabled exceptions and FH4 for all projects.

### PR DESCRIPTION
**Pull request by ZeeWanderer**
- libcurl and wolfss project files moved to rpcs3 source control to make build system changes easier. `common_default.props` and `common_default_macros.props` included in project files.
Int and Out Dirs changed to default (for now wolfssl only):
```
<OutDir>$(SolutionDir)lib\$(Configuration)-$(Platform)\</OutDir>  
<IntDir>$(SolutionDir)tmp\$(ProjectName)-$(Configuration)-$(Platform)\</IntDir>
```
 - `common_default.props` imported in LLVM and glslang when building via MSVC
 - Exceptions and Spectre mitigations disabled in `common_default.props`. Spectre mitigation is desabled by default unless WDK is installed.

Not all projects include `rpcs3_default.props` but with this pr all MSVC projects now include `common_default.props` which disable exceptions and FH4.

- switch VC++ runtime to static (MT, MTd)

### CODE REVIEW

**Comment by Nekotekina** [comment]
Thanks, will test if it disables FH4.

**Comment by Nekotekina** [comment]
Hmm, not much luck with this. It's weird.

**Comment by Nekotekina** [comment]
Well, there is an alternative to compile with static linking of VS runtime.

**Comment by Nekotekina** [comment]
I think discord RPC is provided as a lib, but needs to be rebuilt with MT to link.

**Comment by ZeeWanderer** [comment]
Is seems i forgot to update lib include path in rpcs3 project so it used libcurl from old path that was built without disabling FH4 Faceplam

**Comment by Nekotekina** [comment]
No luck with recent build (on VS 16.5)

**Comment by Nekotekina** [comment]
With static RT, there is no more VCRUNTIME140_1 dependencies. VCRUNTIME140 is still used by Qt DLLs though, but it shouldn't be a problem for now.

**Comment by Nekotekina** [comment]
https://github.com/RPCS3/glslang/releases/download/custom-build-win/glslanglibs_mt.7z for appveyor

**Comment by Nekotekina** [comment]
LLVM build failed for some reason, retrying.

**Comment by Nekotekina** [comment]
https://github.com/RPCS3/llvm-mirror/releases/download/custom-build-win/llvmlibs_mt.7z

**Comment by Nekotekina** [comment]
Appveyor succeeded

**Pull request merged**
