### PR TITLE
Add callbacks for cellPhotoExport

### PR DESCRIPTION
**Pull request by scribam**
Reduce crashs or freezes when calling photo exporting functions.

Sample games tested:
- [X] My Aquarium (Record > Screenshots)
- [X] The IdolM@ster: Gravure For You! Vol. 1 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 2 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 3 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 4 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 5 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 6 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 7 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 8 (Let's Photo!!)
- [X] The IdolM@ster: Gravure For You! Vol. 9 (Let's Photo!!)
- [X] Wipeout HD (Photo Mode)
- [X] WRC 3 (Extras > Photo Gallery > Share)
- [X] WRC 4 FIA WORLD RALLY CHAMPIONSHIP  (Photo Mode)

### CODE REVIEW

**Comment by Kravickas** [comment]
So this shoudnt be working, just preventing crashes ?

**Comment by scribam** [comment]
Yes, it needs more work to truly be able to export photos. You can find the path of the generated images in the log by looking at the `srcHddDir` and `srcHddFile` parameters of the `cellPhotoExportFromFile` function:

```U {PPU[0x1000000] Thread (main_thread) [0x001c5b60]} cellPhotoExport TODO: cellPhotoExportFromFile(srcHddDir=“/dev_hdd1/cache/NPUB30255/”, srcHddFile=“encode_temporary.png”, param=*0xd00201e0, funcFinish=*0x3895f8, userdata=*0x2)```

But the images are often black or with garbage when you look at them (here an example from the game "My Aquarium"):

encode_temporary

~~(or maybe I haven't found the way to turn the light on before taking the screenshot)~~

**Comment by Kravickas** [comment]
I tried MXGP and there was just  like `U {PPU[0x1000000] Thread (main_thread) [0x001c5b60]} cellPhotoExport TODO: cellPhotoExport` and game just kept ''exporting'' and i was unable to do anything, but screenshot is in /dev_hdd1/cache/GAMEID
photo

**Comment by scribam** [comment]
Do you use a build with this PR included? It seems it is not the case as your log doesn't show the parameters.

**Comment by Kravickas** [comment]
I swear I had master pr merged to it... i guess not cos now its working and says its in XMB photo category

**Pull request merged**
