### PR TITLE
rsx: Fix clear color for formats with less than 32-bit width 

### PR DESCRIPTION
**Pull request by kd-11**
Fixes https://github.com/RPCS3/rpcs3/issues/9598

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
Fixes broken shadow in Midnight Club: Los Angeles at night.

**Before**:
image

**After**:
image

**Comment by palmeras** [comment]
Missing Add lod texture bias to UI added in previous build.0.0.24-14347

**Comment by Darkhost1999** [comment]
> Missing Add lod texture bias to UI added in previous build.0.0.24-14347

The commits here show that it was moved to the debug tab. It's not missing.

**Comment by palmeras** [comment]
> > Falta Agregar sesgo de textura lod a la interfaz de usuario agregado en la compilación anterior.0.0.24-14347
> 
> Las confirmaciones aquí muestran que se movió a la pestaña de depuración. No falta.

sorry, not what moved it

**Pull request merged**
