### PR TITLE
[vk] fix cubic view construction

### PR DESCRIPTION
**Pull request by kvark**
The layer count has to be divisible by 6 for cubic views.
Note: this is probably not the best fix, since it messes with the subresource range given to the helper.
Ideas are welcome!

### CODE REVIEW

**Comment by kd-11** [comment]
This is a bug from when the imageviews were being refactored. The third argument [here](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/VK/VKHelpers.h#L850) should be info.arrayLayers, not 1. This is a copypasta from what used to be a framebuffers-only method.

**Comment by kvark** [comment]
@kd-11 great observation! fixed now

**Comment by kd-11** [comment]
image

**Comment by scribam** [comment]
Is this enabled? https://help.github.com/articles/configuring-commit-rebasing-for-pull-requests/

**Comment by kvark** [comment]
@scribam they do seem to have a rebase option button, but the project disallows merging PRs that aren't up to date. I would highly recommend switching this requirement off:
screenshot from 2018-09-07 14-35-04

That would streamline review/landing process quite a bit.
In gfx-rs we use [Bors](https://app.bors.tech/) to land all the things in 99% of cases (e.g. https://github.com/gfx-rs/gfx/pull/2385). Thus, reviewer just says "bors r+" and they do all the testing on CI, rebasing and landing tasks automatically. Hooking it up is really easy, just requires admin permissions on the project.

**Comment by elad335** [comment]
https://help.github.com/articles/enabling-required-status-checks/

**Pull request merged**
