### PR TITLE
Improve GDB debug server

### PR DESCRIPTION
**Pull request by jfhs**
This PR improves GDB debug server support:
- fixes it to work with new changes to RPCS3 core
- allows interrupts to be sent from remote to pause process
- sends correct response for current thread request
- unpauses all threads when continuing
- reports correct thread after being stopped
- correctly handles restarts of the emulation

With these changes it's possible to debug PPU threads from IDA, using this plugin: https://github.com/jfhs/ida-ppc64-gdb-debugger

### CODE REVIEW

**Comment by VelocityRa** [comment]
Nice. Could you provide binaries of the plugin? Can be done with GitHub releases or just a link to it here.

**Comment by jfhs** [comment]
@VelocityRa IDA SDK is only available when you buy it, so I don't think I can distribute binaries, since they are linked with the SDK parts.

**Comment by VelocityRa** [comment]
@jfhs That would be pretty dumb of them to do, it'd mean that every plugin user would need to compile it.
There has to be an exception or whatever to their license for plugins. I've also seen other plugins being distributed, for example: http://www.idabook.com/ida-x86emu/ (unofficial despite the url)

**Comment by jfhs** [comment]
@VelocityRa well, I put it here for now then: https://www.dropbox.com/s/jpbyt2axzpydc6c/IdaPPC64GdbDebugger.p64?dl=0

**Comment by AniLeo** [comment]
Could you perhaps also handle #3524 (including required stuff in readme)

**Comment by jfhs** [comment]
@AniLeo I don't understand how #3524 is related to this. Can you elaborate?

**Comment by janisozaur** [comment]
Looks like a typo, should've been https://github.com/RPCS3/rpcs3/issues/3254 ?

**Comment by AniLeo** [comment]
Yes, it's 3254, was a typo

**Comment by elad335** [comment]
you need to rebase, you have a conflicting file

**Comment by kd-11** [comment]
A lot of codestyle problms are present, mostly braces on same line. Please fix these according to the coding style guidelines https://github.com/RPCS3/rpcs3/wiki/Coding-Style

**Pull request merged**
