### PR TITLE
Experimental TSX path update

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by ruipin** [comment]
RDR seems to be slightly faster than master, I'm getting 15-16FPS at the starting location compared to 13-14 on master.

**Comment by incognitoh** [comment]
This latest commit completely freezes P5 at intro for me. With TSX disabled, P5 works fine. Anyone else having issues with P5 with this latest commit?

**Comment by raven02** [comment]
Tested with p5 . Got 2-3 fps increment in overall.

**Comment by incognitoh** [comment]
Well I'm on Haswell with TSX enabled and P5 still freezes at intro with this PR. TSX works great on master. Guess it has something to do with Haswell TSX and changes that are being made here..

**Comment by Nekotekina** [comment]
@incognitoh Well, that was expected. Try new commit.

**Comment by Sztefanol** [comment]
Journey and Shadow of the Colossus freeze randomly before reaching title screen in this commit too. I have Haswell as well.

**Comment by incognitoh** [comment]
Yes, can confirm haswell tsx now works with the most recent commit.

**Comment by Sztefanol** [comment]
Journey and SotC still freeze but usually much further and emulator itself remains responsive.

**Comment by alessandro784** [comment]
stuttering, and loss fps any game

**Comment by Nekotekina** [comment]
@alessandro784 your CPU?

**Comment by alessandro784** [comment]
I7 9700k 5 ghz rtx 2070, 16 ddr4, 970 evo 512, w10 pro.

**Comment by psennermann** [comment]
> stuttering, and less fps any game

@alessandro784 are you sure it is caused by this PR? I ask because the stuttering I'm experiencing is due to 0.0.6-8147 and not 0.0.6-8151  (see issue #5996)

**Comment by alessandro784** [comment]
Not only this one,also previous builds, with elads builds works nice for example,or 8048 version work good too.i dont remeber all, but i see less fps now, i have all updated nothing change from 8048 build.

**Comment by incognitoh** [comment]
I may have spoken too soon. P5 works great but now I tested a number of other games and I notice several games that used to work with SPU LLVM Mega, no longer work if TSX is enabled after this PR was merged. 

For example, MotorStorm 2 worked great with SPU LLVM Mega and TSX before this PR, but now it freezes before every race if TSX is _enabled_.  But if I switch to LLVM Safe and TSX _enabled_, it works but slower since that game runs better with Mega. Also, SPU LLVM Mega and TSX _disabled_ works.

Not sure if this is due to Haswell TSX or if others are experiencing it. Hopefully some other Haswell TSX users can test and confirm or maybe @Nekotekina can take a 2nd look at it. I can post a log if necessary.

**Comment by adrianocolvero** [comment]
After this patch i can't run games with TSX enabled anymore. 
All games used to work fine, but now most of them just hang at start screen or open and freezes at first seconds of the intro.
The only one who still opening here with TSX enabled is Rock Band 2, but, the sound stop working after the main screen, without TSX  it works fine. 



My CPU is an I7 4771
Windows 10

If i can help providing logs or anything, just let me know @Nekotekina.

**Comment by RainbowCookie32** [comment]
An issue for this freezes was opened yesterday, it's #6010. If you experience this issues, post them there so everything is in one place

**Pull request merged**
