### PR TITLE
Move llvm tests to VS unit testing framework

### PR DESCRIPTION
**Pull request by vlj**
In master llvm tests are located in PPULLVMRecompilerTests.cpp and need to update a manual define to be enabled. When enabled they are run in Compiler constructor and they might interfere with the inner working of rpcs3 since they sometimes write/read to memory. In summary they are quite impracticable.

This PR solves this by moving all the testing in rpcs3-tests project introduced some commits ago.
These 555 tests are now standalone unit tests Inside VS unit testing Framework. They can be run independently or by group if needed. I think they can even be run Inside appveyor if necessary.

There are 2 drawbacks atm :
* These tests are obviously Windows specific. I don't think it will be hard to have a non Windows implementation, the Framework only uses 2 macro TEST_CLASS() and TEST_METHOD and an Assert::IsEqual function. Besides if PPULLVM works in Windows there is no reason it doesn't on linux...
* I encounter a pop up "Warning: IEEE mode not enabled" when running them which makes the tests requires manual input at the moment. In addition all the FP tests are failing too.

### CODE REVIEW

**Comment by vlj** [comment]
Simplified the dbg hook commit

**Comment by danilaml** [comment]
How does that affect LLVM recompiler?
Also, travis is not happy with changing executable map to map of void*

**Comment by vlj** [comment]
Normally it shouldn't affect LLVM recompiler, I just moved some part of the code there and there.

**Comment by danilaml** [comment]
@vlj what was the purpose of moving all these function to map (like `vm.reservation_update`)?
They are not "executables" and have different interface than others. They might as well remain separate entity.
Because of them map of executables changed to map of void ptrs and conversion from/to `void*` of function ptrs is not well defined afaik (it's either prohibited or implementation defined, but I might be wrong on this).

**Comment by vlj** [comment]
@danilaml the Call Template was already putting the function to executable_map (which was called executableMap before) :
"				m_executableMap[name] = (Executable)(void *&)function;"
When building a module we don't use the function address at all.
LLVM's ExecutionEngine is responsible for symbol resolution on the other hand, that's why we were recording the name to Executable mapping. With this PR I record all the "system" name to Executable function before creating the module. executable_map can be updated by compiler to record "dynamic" (ie other function to-be compiled) symbols.

Like you mention casting pointer to member is prohibited and that's how I discovered that there was issues with PPUThread::fast_stop. A pointer to member is not a function and ABI is not compatible. Likely we weren't emitting the PPUThread::fast_stop or we didn't execute the call otherwise it would trigger a crash since the pointer is invalid (and we didn't provide the pointer to this anyways)

**Comment by vlj** [comment]
The function interface doesn't matter btw as long as they are functions. In x86 a function is just an instruction address (pretty much like in PPC), the function call site is responsible for saving register content, pushing the arguments, calling the function, and restoring register after the function returns.

That's different for pointer to member because function can be virtual, a "call" needs to fetch the type of the object and fetch the actual function pointer.

**Comment by vlj** [comment]
Fixed build

**Comment by danilaml** [comment]
Also, I think I have a little bit lower performance with this (dice test went from 36 to 34-35) but that could be nothing.

**Comment by vlj** [comment]
Use c++ static cast now

@danilaml I commented the &PPUThread::fast_stop case because it doesn't build in VS 2015.
"cannot convert from void(__cdecl PPUThread::*)(void) to void*"
Which is conformant with the link you gave.

I have no idea why it built before. We let the template type deduction do the magic and it likely took a type (std::function ?) that could be casted properly to void*.

**Comment by vlj** [comment]
Use reinterpret cast instead of static_cast

**Comment by paulsapps** [comment]
If you use gmock/gtest then this can be multi platform test. you can use TEST_F(SuiteName,Method) { ASSERT_EQ(1,2); } for example.

Should probably updated to run these tests during CI builds else they won't detect regressions until someone manually executes them?

**Comment by Bigpet** [comment]
@paulsapps it's `TEST(SuiteName,Method)` unless you have test fixture class named `SuiteName`

**Comment by paulsapps** [comment]
@Bigpet I always mix those up, but its pretty simple to "port" to gtest anyway ;)

**Comment by danilaml** [comment]
@vlj even with reinterpret cast?

**Comment by vlj** [comment]
Use stack for optimizer pass manager

**Comment by vlj** [comment]
can it be merged ?

**Comment by danilaml** [comment]
@vlj why not wrap fast_stop in special `CPUHybridDecoderRecompiler` func that takes ppu_state just like `PollStatus`? (Does it actually ever gets called though?)

**Comment by vlj** [comment]
I didn't encountered an app that calls fast_stop from a translated block so far.

**Comment by vlj** [comment]
I wrapped fast_stop in a function call

**Comment by vlj** [comment]
Forgot reinterpret_cast

**Comment by vlj** [comment]
Mergeable ?

**Pull request merged**
