### PR TITLE
Fix mounting bdvd when elf in subdirectory

### PR DESCRIPTION
**Pull request by cornytrace**
This causes the check not to depend anymore on the location of the ELF. Causes MGS4 to boot further as previously EBOOT.BIN loads mgs\mgs4.self, which causes the check to run again, which fails and /dev_bdvd is not mounted again.

### CODE REVIEW

**Comment by clienthax** [comment]
This Might help out on zone of enders too, similar problem

**Comment by Nekotekina** [comment]
The idea doesn't look bad, however, this implementation has some flaws.

**Comment by cornytrace** [comment]
@Nekotekina Please explain, as I've really tried hard to implement this as efficient, correct and platform-independent as possible. The only thing I can see is that .find can be changed into .rfind. It runs all the same correctness checks as the old code, and checks g_cfg_vfs_dev_bdvd is a directory in addition. Maybe you want an error message if the value of g_cfg_vfs_dev_bdvd is not valid?

**Comment by Nekotekina** [comment]
For example, if PS3_GAME appears as a part of other directory name, it'll behave incorrectly. You may alternatively search for "/PS3_GAME/" after appending a '/' at the end and (win32-only) replacing '\' with '/'.

**Comment by cornytrace** [comment]
By using rfind, the PS3_GAME found by rfind is always the folder we want. If it isn't, then it is not a valid path anyways and will be caught by the check for PS3_DISC.SFB

**Comment by paulsapps** [comment]
I'm assuming its normal to still get this?

```
E {PPU[0x1000012] Thread (FSStart) [0x003c4b20]} sys_fs: sys_fs_open(“/dev_bdvd/PS3_GAME/USRDIR/mgs/movie.dat”) failed: device not mounted
E {PPU[0x1000012] Thread (FSStart) [0x003c4b20]} 'cellFsOpen' failed with 0x8001003a : CELL_ENOTMOUNTED

```

**Pull request merged**
