### PR TITLE
merge qt_camera_error_handler into qt_camera_handler

### PR DESCRIPTION
**Pull request by oltolm**
This PR merges `qt_camera_error_handler` into `qt_camera_handler`. When I tried to understand the camera code it seemed overly complicated to me, so I decided to simplify it.

### CODE REVIEW

**Comment by Megamouse** [comment]
The camera handler is not supposed to be a QObject.
That's why

**Comment by Megamouse** [comment]
Just to explain:
You're missing the Q_OBJECT macro that's needed for signals and slots.
When I implemented this feature, it didn't work with the rest of the software (or didn't even compile. I don't remember exactly).

**Comment by oltolm** [comment]
Yes, I forgot `Q_OBJECT`. I added it and fixed the compilation error. [Multiple Inheritance Requires QObject to Be First](http://doc.trolltech.com/4.5/moc.html).

**Comment by oltolm** [comment]
I also merged `qt_music_error_handler` into `qt_music_handler`.

**Pull request merged**
