### PR TITLE
Fix PPU disasm for branch opcodes with AA or LK set

### PR DESCRIPTION
**Pull request by TGEnigma**
http://www.ds.ewi.tudelft.nl/vakken/in1006/instruction-set/b.html

### CODE REVIEW

**Comment by Nekotekina** [comment]
We use `op.bt24` for target address, "strange" `ll` is seemingly left to allow emitting B instruction, because bt24 is not writable.

**Comment by TGEnigma** [comment]
I'm aware, I checked. I assumed it was there for the sake of uniformity with the spec (albeit misspelled).

**Comment by Nekotekina** [comment]
Leave them both as well as code in B emitter

**Comment by TGEnigma** [comment]
Fixed

**Comment by Nekotekina** [comment]
Ok, thanks

**Pull request merged**
