### PR TITLE
Unify .gitmodules url as relative ones.

### PR DESCRIPTION
**Pull request by Nekotekina**
Don't specify SSH or HTTPS explicitly. Can save some time if manually changing it is necessary.

### CODE REVIEW

**Comment by MSuih** [comment]
Can this affect people who have origin set to some other service than github?

**Comment by arabek** [comment]
I don't think that is correct. Upon first checkout of the rpcs3 repository the sub modules won't be populated. A recursive checkout won't be able to resolve the modules Origins at all.

**Comment by Nekotekina** [comment]
@arabek I tested it on a fresh checkout, and it fetches submodules without problem. On what basis you say this?

**Comment by arabek** [comment]
> @arabek I tested it on a fresh checkout, and it fetches submodules without problem. On what basis you say this?

indeed, i wasn't aware that git will assume that the repositories relative to will resolve to base domain.

```
Submodule '3rdparty/FAudio' (https://github.com/FNA-XNA/FAudio.git) registered for path '3rdparty/FAudio'
Submodule '3rdparty/SPIRV-Headers' (https://github.com/KhronosGroup/SPIRV-Headers.git) registered for path '3rdparty/SPIRV/SPIRV-Headers'
Submodule '3rdparty/SPIRV-Tools' (https://github.com/KhronosGroup/SPIRV-Tools.git) registered for path '3rdparty/SPIRV/SPIRV-Tools'
Submodule 'asmjit' (https://github.com/asmjit/asmjit) registered for path '3rdparty/asmjit/asmjit'
Submodule '3rdparty/cereal' (https://github.com/RPCS3/cereal.git) registered for path '3rdparty/cereal'
Submodule '3rdparty/curl' (https://github.com/curl/curl.git) registered for path '3rdparty/curl/curl'
Submodule 'rpcs3-ffmpeg' (https://github.com/RPCS3/ffmpeg-core) registered for path '3rdparty/ffmpeg'
Submodule '3rdparty/flatbuffers' (https://github.com/google/flatbuffers.git) registered for path '3rdparty/flatbuffers'
Submodule '3rdparty/glslang' (https://github.com/KhronosGroup/glslang.git) registered for path '3rdparty/glslang/glslang'
Submodule '3rdparty/hidapi' (https://github.com/RPCS3/hidapi) registered for path '3rdparty/hidapi/hidapi'
Submodule '3rdparty/libpng' (https://github.com/glennrp/libpng.git) registered for path '3rdparty/libpng/libpng'
Submodule '3rdparty/libusb' (https://github.com/libusb/libusb.git) registered for path '3rdparty/libusb/libusb'
Submodule '3rdparty/pugixml' (https://github.com/zeux/pugixml) registered for path '3rdparty/pugixml'
Submodule '3rdparty/wolfssl' (https://github.com/wolfSSL/wolfssl.git) registered for path '3rdparty/wolfssl'
Submodule '3rdparty/xxHash' (https://github.com/Cyan4973/xxHash) registered for path '3rdparty/xxHash'
Submodule '3rdparty/yaml-cpp' (https://github.com/RPCS3/yaml-cpp.git) registered for path '3rdparty/yaml-cpp'
Submodule '3rdparty/zlib' (https://github.com/madler/zlib) registered for path '3rdparty/zlib'
Submodule 'llvm' (https://github.com/RPCS3/llvm-mirror) registered for path 'llvm'
Cloning into '/Users/arab/src/rpcs3/3rdparty/FAudio'...
Cloning into '/Users/arab/src/rpcs3/3rdparty/SPIRV/SPIRV-Headers'...
Cloning into '/Users/arab/src/rpcs3/3rdparty/SPIRV/SPIRV-Tools'...
Cloning into '/Users/arab/src/rpcs3/3rdparty/asmjit/asmjit'...
Cloning into '/Users/arab/src/rpcs3/3rdparty/cereal'...
Cloning into '/Users/arab/src/rpcs3/3rdparty/curl/curl'...
```

you can ignore my comment

**Comment by Nekotekina** [comment]
@MSuih if they change origin after clone, then try to init submodules, maybe. If submodules are already init, their registered origins won't change. Looks like imaginary problem, if a problem at all.

**Review by hcorion — APPROVED** [review]
As mentioned, this would break for people on other git hosts, but it's pretty nonstandard configuration, so it seems fine to me. It makes sense with GitHub's push to move to cloning with ssh instead of https.

**Pull request merged**
