### PR TITLE
Qt: simplify GetVerboseTimeByMs logic

### PR DESCRIPTION
**Pull request by jy95**
I noticed there is many if else cases in the file rpcs3/rpcs3qt/localized.cpp.
This file generates messages when there is a update available and compute the diff time in order to print it.
[QT Linguist](https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals) suggest to write them like

```
tr("%n message(s) saved", "", n)
```

instead of

```
n == 1 ? tr("%n message saved") : tr("%n messages saved")
```

This PR is intended to fix that.

### CODE REVIEW

**Comment by Megamouse** [comment]
If it works in the Qt translator, then it should be fine. Someone needs to test

**Comment by Megamouse** [comment]
Ahh... I'm very sorry. We can't merge this at this point.

Your code practically works, but only if we provide an english translation file with -pluralonly.

I'll close this pull request now, but you are welcome to reopen this if what I said about the english translation is wrong, or once rpcs3 officially ships translation files (which probably won't be happening anytime soon).

**Comment by jy95** [comment]
Can you just let it open but put a flag for that ?

**Comment by Megamouse** [comment]
Hmm, I'd have to come up with some label, and you'd have to mark this PR as a draft.

**Comment by dio-gh** [comment]
How does this change affect languages with plural constructs that are more complicated than chucking an `s` at a word?

**Comment by Megamouse** [comment]
@dio-gh the translator provides a seperate field for each plurality for each language.
The %n and %0 can moved around as necessary. The (s) is basically just an indication for the related word. You could in theory omit it.

**Comment by jy95** [comment]
@dio-gh See the article [Plural Forms in Translations](https://doc.qt.io/archives/qq/qq19-plurals.html) ; they showcased examples with English, French and Polish

**Comment by Megamouse** [comment]
My intention was not to tell you to drop the other changes, but to append those other changes here.
:neckbeard:

**Comment by jy95** [comment]
I prefer to add them later in another separate PR (when this one will be merged) : 
here, GetVerboseTimeByMs is used by the Update Manager and the game list frame

**Comment by Megamouse** [comment]
@jy95 
Can you please rebase the code or give contributors the right to do so?
We decided to go with it after all.

**Pull request closed without merging**
