### PR TITLE
Update WxWidgets repository

### PR DESCRIPTION
**Pull request by Bigpet**
This is in preparation to make it easy to compile with VS2015.

Also there's notables changes in wxWidgets that we might find very useful,
such as being able to create OpenGL debug contexts.

The change in .gitmodules might make it necessary for people to run
"git submodule sync" after pulling these changes

### CODE REVIEW

**Comment by Syphurith** [comment]
Hi @Bigpet. Except the C++11 features, how do you feel about the VS2015? ~~VS2013 distributes many junk packages with it (i mean Azure, Ad SDK, WP SDK.. blabla with it). Well hope VS installation could be more customed than VS2013. Since it is a developer tool, not a end-user tool.~~
This pull looks good for me (except would have some time compile it again). Yep.
~~I'm getting envy about those citra-emu developing. Rpcs3 started before it.~~

**Comment by Bigpet** [comment]
@Syphurith the installation of VS2015 is still huge. I didn't really test much with VS2015 but I like that it's finally almost C99 compatible (although they did back-peddle on the standard wprintf/wsnprintf/etc. format specifiers which makes me kind of sad). But I did run across some C++ library regressions which I hope will get fixed in the final release (or at least in update 1 :smile: )

As for the development speed. Well, the codebase of rpcs3 is not quite as approachable as citras (to put it charitably). Most importantly there's no really experienced and active maintainer/developer steering the direction of rpcs3.

But there's still some active development (thanks in large part to Nekotekina ). So it could be worse.

**Comment by Syphurith** [comment]
@Bigpet To me i have hard time in reading code and understand those. Just a C programmer.
I don't know should we call for document some files to help us understand those better. Such as call relations, real reason about some calls.. also it would need someone to read some part of the code and that help himself understand the architecture. eh maybe would find some weird parts also.
It seems the project has little active developers now. Some documents are hard to find. Even B1ackDaemon have his unit but we have not much tests to run. Maybe a proposal should be made..

**Comment by Syphurith** [comment]
@Bigpet I'm so sorry post some not much related things here, but i find no other ways calling you better. Can not get to irc - all IPs are banned. There is [some links](https://gist.github.com/Syphurith/27341bb563fff5346380) i don't know if helps rpcs3 devs.
Found nucleus doc i think we may write some documents about how code arranged.. and designed.
If i am getting annoying please forgive my behavior. I know i'm some kind of talk terminator..

**Comment by Hykem** [comment]
There are efforts being taken privately to give a "new life" to RPCS3. I'm personally working around with the idea of writing a new PS3 emulator from scratch with some expert developers.
RPCS3's code base is very confusing and we took some bad decisions right at the beginning in terms of memory management and code interpretation. Unfortunately, this is something that can't simply be "patched", it requires a full and complete re-write of RPCS3's code.
At the moment, RPCS3 is more of a "playground" for reverse engineering modules, understanding the PS3 system and how applications run on them.
Also, ARMv7 emulation is currently being forked away from RPCS3 into a new Vita emulator.

**Comment by Syphurith** [comment]
@Hykem Thanks for reply. Would the new project be documented and open for participants?
"Playground" - oh well. The code base is really confusing for me at least, now.
Glad to hear that is in fact be dealt - even with a new name.

**Comment by Hykem** [comment]
@Syphurith Of course, proper documentation is a priority and as soon as the emulator reaches a stable state (in terms of proper code interpretation and memory management) it will be opened up to the public.

**Comment by shakingboy** [comment]
@Hykem Where/what is the new Vita emulator's name/location?

**Comment by Syphurith** [comment]
@shakingboy well Vita emulator? you know that Vita internals are hidden now aren't you? PSVita Dev.wiki is almost blank, so no information could be collected. rpcs3 is a PS3 emulator.
Only if you are really talented in emulator development, you can ask for its name and help. The next generation of rpcs3 must still be in development stage, not even a beta or alpha.. Or else wait.

**Comment by shakingboy** [comment]
@Syphurith All I asked was where its repository/new location will be. You don't have to interrogate me.

I don't see how I need to be talented in emulator development just to see the source code of something open-source.

**Comment by Syphurith** [comment]
@shakingboy well okey. I misunderstood. However still no Vita emulator present, cause no internal details about it. what Neko did in rpcs3 for Vita are only stubs. if not believed you can take a look at `<cloned rpcs3 repo path>rpcs3\Emu\ARMv7\`.
I can't explain the way to implement an emulator cause i can just fix some minor problems, and i don't want to do so. If interested you could google for such, there are articles about emulator implementation.
If annoyed at my words, sorry. still i don't know why you say i interrogated you, and, never mind.

**Pull request merged**
