### PR TITLE
Revert "PPU LLVM: Precompile all executable (PRX, MSELF, overlay) cod…

### PR DESCRIPTION
**Pull request by Nekotekina**
…e at startup (#9680)"

This reverts commit e3b3b0cda7fd3f1fa52fdd402686f7eef2cf4279.

Sorry for lack of testing.

### CODE REVIEW

**Comment by AniLeo** [comment]
No need to revert, it's already marked as broken on the updater

**Comment by Nekotekina** [comment]
I'm not in hurry, just in case.

**Comment by Nekotekina** [comment]
Can be closed if regression is fixed.

**Comment by AniLeo** [comment]
Tested NieR, working fine, closing

**Pull request closed without merging**
