### PR TITLE
Change return of function "sceNpMatching2Init" to CELL_OK

### LINKED ISSUE #2549: Regression: Final Fight: Double Impact - Start button does not register on arcade cabinets
It seems that you can no longer start either game on the arcade cabinets in this game, however there was a previous build where this worked. I have tested this with both keyboard and xinput input methods.

http://www.emunewz.net/forum/showthread.php?tid=163283&pid=230471#pid230471

Last known good build: https://github.com/RPCS3/rpcs3/commit/4ed91d4

rpcs3_2017-03-17_14-02-26
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/851656/RPCS3.zip)

### PR DESCRIPTION
**Pull request by scribam**
Sample games to test:
- [X] BandFuse: Rock Legends (no changes)
- [ ] Demon's Souls (check for regressions, current status is Playable)
- [X] **Disney•Pixar Brave (Loadable => Ingame)**
- [X] FAMILY GAME NIGHT 3 (no changes)
- [X] **Final Fight™: Double Impact (fix #2549)**
- [X] LittleBigPlanet (no regressions)
- [X] **Naughty Bear Gold Edition (still Intro but doesn't crash with a fatal anymore)**
- [X] **Overlord Raising Hell (Intro => Ingame with Interpreter Fast)**
- [X] Pure (no regressions)
- [X] Rotastic (no regressions)
- [X] Sackboy's Prehistoric Moves (no changes)
- [X] Sacred Citadel Demo (no regressions)
- [X] Split/Second (no regressions)
- [X] **SpongeBob SquarePants: Plankton’s Robotic Revenge (Loadable => Ingame)**
- [X] **Switchball® (Loadable => Intro)**
- [X] Tecmo Bowl Throwback (no regressions)
- [X] Virtua Tennis 2009 (no regressions)
- [ ] Wrecked: Revenge Revisited (check for regressions, current status is Ingame)

https://docs.google.com/spreadsheets/d/1CBBfrOdlQ8EPe6wdDv3hJ98CiuGZxBkDdrSAeJF5y0I/edit?usp=sharing

@Inviuz You changed the value from `CELL_OK` to `SCE_NP_MATCHING2_ERROR_TIMEDOUT` in the commit a05a7af5d50ffd0eeae981b0ef543d123e200281, do you remember which games had issues?

### CODE REVIEW

**Comment by flash-fire** [comment]
I asked this in discord a week ago (as I also  was looking at nothing/loadable games), and Jarves said this:

> Returning CELL_OK causes some games to loop on sceNp functions

**Comment by AniLeo** [comment]
I used to be an adventurer like you and tried to touch a sceNp return code.

Never again.

**Comment by Inviuz** [comment]
@scribam Demon's Souls used to loop somewhere at the beginning of 2017. Haven't tested it since

**Comment by Relsig** [comment]
Excuse me if this is completely wrong (I don't know much about the inner workings of sceNp) but is it possible these titles are using sceNpMatching2Init to check online status and maybe they're all programmed to handle the returns differently?

Perhaps SpongeBob et al don't check for timeouts? You might try returning offline and cross examine the results.

I don't own any of the above games or I would test the theory myself.

As a side note it might be handy to have a spreadsheet for the games that are known to handle sceNp functions, the functions they handle, and the effects of the returns on the game to help debug the sceNp code.

**Comment by scribam** [comment]
I currently have no idea how `sceNpMatching2Init` works. I found using `CELL_OK` helps some games to go further and as long as it does not introduce regressions, I think it is a worthy change. IIRC my tests on DECR, `CELL_OK` is returned even in offline mode.

Your idea about spreadsheet is good but, I think, very time consuming. Gathering and sharing all these information would be certainly useful for the project so it is a welcome help if anyone wants to do it.

**Comment by clienthax** [comment]
I can tell ya that timeout isn't a valid error code for that function anyway ;)

**Comment by Relsig** [comment]
compiling our current knowledge would be a PITA and most likely not worth the effort. Adding as we go would be trivial and potentially helpful, for instance this took me 4 mins ->

https://docs.google.com/spreadsheets/d/1CBBfrOdlQ8EPe6wdDv3hJ98CiuGZxBkDdrSAeJF5y0I/edit?usp=sharing

I may add validation on the functions/returns as well when i feel like digging out a list of the valid entries.

@scribam I'm assuming that the checked items that don't indicate as such are fine with either timedout or cell ok... if that's accurate let me know and I'll add the missing entries on the list.

**Comment by scribam** [comment]
Thanks! I added the link in the PR description.

Yes, you are right, using `SCE_NP_MATCHING2_ERROR_TIMEDOUT` or `CELL_OK` doesn't seem to have an impact on these games. I updated the spreadsheet.

**Comment by JohnHolmesII** [comment]
Do you still want someone to test DeS?

**Comment by Relsig** [comment]
Demons souls  isn't checked so I would work under the assumption that it hasn't been tested yet. You're more than welcome to try and run it with this build and let everyone know your results. Even if scribam hasn't updated the checklist yet having extra verification never hurts.

**Comment by JohnHolmesII** [comment]
Well demon's souls runs fine, but one thing to notice is that now it spams the log with requests for online ids and such

Â·U 0:02:39.773756 {PPU[0x1000017] Thread (NexusRevolution Main) [0x00a67f58]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0251864)
Â·U 0:02:39.773766 {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e13e64]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd0251888)
Â·U 0:02:39.773769 {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e13e74]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd02518bc)


Not really a regression, in fact thats technically a positive i guess?

**Comment by Relsig** [comment]
Absolutely! It's more than a positive, it's a feature -> those logged items are because those functions aren't implemented either at all or completely.

I believe net features are currently an afterthought and filtering them out of a log while debugging is quite trivial so I would expect those to be spamming logs into the future.

If Demon's Souls is still playable without any other significant adverse effects I would mention scribam here (@) and let him know.

**Comment by Asinin3** [comment]
Just tested DeS some more, kept warping to different areas then i got this error:

`F {PPU[0x1000032] Thread (ChrProxyThreadMan::Thread) [0x009e1e70]} class std::runtime_error thrown: Verification failed: 
(in file Emu\Cell\lv2\sys_cond.cpp:279)`

Not sure if related to this PR though, I didn't notice any other issues.

**Comment by Nekotekina** [comment]
I'll merge assuming there are no related problems found.

**Comment by KDZL** [comment]
esboco 3
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1768969/RPCS3.zip)

**Comment by AniLeo** [comment]
@KDZL Get the fuck out of here with your pirated games

**Comment by Parthorisian** [comment]
sorry it seems it too late, this report... but Demons souls is **almost** playable with this PR. 3-1 world's boss isn't more beatable in first (simpliest) way. Boss now can't obtain healing from zombie-servant. It don't works now. Boss can be killed, but than you have unique option exit through boss fog. And come in again. This reveal boss resurrection. And kill boss again, etc... This option is unavailable in normal ps3 mode. And in addition all survived in bossfight zombies don't look more upon real boss, just upon the altar (original boss location). And in addition some 4-2 world's (beam's ghost) enemies now inflicting to character much more damage than in original ps3

**Comment by JohnHolmesII** [comment]
Dude what

**Comment by Relsig** [comment]
Very strongly doubt this PR is in any way related to those issues...

I would check the forums and issue tracker to see if anyone else is reporting a similar issue. If not feel free to start a topic or open a report. Please be mindful of the guidelines for reporting issues when doing so.

**Pull request merged**
