### PR TITLE
Commit collection

### PR DESCRIPTION
**Pull request by Nekotekina**
New features, refactoring
Error logging for some syscalls (WIP)
Resurrected `vfs::mount`
Removed broken cellFsSt* implementation (try LLE)

### CODE REVIEW

**Comment by Nekotekina** [comment]
I'm afraid this may have regressions...

**Comment by raven02** [comment]
Running test against different titles

**Comment by Nezarn** [comment]
I don't know if its a regression, but now Ar Tonelico Qoga instead of having the error from #1391 log gets spammed with this after it tries accessing that file i mentioned in that issue (but with the correct path at least, so its either semi-fixed and the game goes further, or got broken further)

> ·U {PPU[0x5] Thread (main_thread) [0x00a4ccc0]} cellFs TODO: cellFsStRead(fd=3, buf=*0xd94a6a0c, size=0x10000, rsize=*0xd00fdd18)

full log: https://www.dropbox.com/s/1h9ntusx6bm0b04/artonelico.zip?dl=0

**Comment by raven02** [comment]
Tested bunch of games and so far looks okay .

**Comment by SakataGintokiYT** [comment]
Yep it works well :)

**Comment by Nekotekina** [comment]
@Nezarn Ar Tonelico requires LLE libfs.sprx since cellFsSt* implementation is broken, and I disable it in this PR.

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
Can you disable  cellFsOpendir or try fix 

{PPU[0x7] Thread (main_thread) [0x004cee28]} PPU: 'cellFsOpendir' aborted
{PPU[0x7] Thread (main_thread) [0x004cee28]} class fmt::exception thrown: Unknown Win32 error: 267.

This error appear in : 
-Dengeki Bunko: Fighting Climax
-Dengeki Bunko Fighting Climax Fighting Exhibition
- Under Night In-Birth EXE:Late

**Comment by Nekotekina** [comment]
I need logs for these

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
Log : https://gist.github.com/SakataGintokiYT/1f4cba34c7ae7f2c0f06569ddf928b7c
Log : https://gist.github.com/SakataGintokiYT/02d7f07bb88c03db128e94c0a91e688b

**Comment by Nekotekina** [comment]
@SakataGintokiYT Try, maybe it got fixed

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
[cellFsOpendir-- Fixed : ]

Now appear this error unimplemented syscall syscall 988

{PPU[0x230] Thread (savedata check thread) [0x00363efc]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
{PPU[0x230] Thread (savedata check thread) [0x004cf388]} sys_process: Process finished

Log :  https://gist.github.com/SakataGintokiYT/58fa288204631826f1ab5c1d1220eaf6

**Comment by Nekotekina** [comment]
Do you have savedata folder?

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
I don't have savedata for this game and emulator create empty folder NPJB00785-SYSTEM

**Comment by SakataGintokiYT** [comment]
@Nekotekina 
Can you look at it  :) 

##### Dragon Ball Z: Ultimate Tenkaichi
{PPU[0x7] Thread (main_thread) [0x005fc818]} struct vm::access_violation thrown: Access violation reading address 0x377
Log : https://gist.github.com/SakataGintokiYT/5d42c30612813af5335e838f706a32f7
__________________________________________________________________________________________________

##### Dragon Ball Z Budokai HD Collection
{PPU[0x7] Thread (main_thread) [0x000cd880]} PPU: 'sys_spu_thread_group_start' aborted
{PPU[0x7] Thread (main_thread) [0x000cd880]} struct vm::access_violation thrown: Access violation reading address 0x0
Log : https://gist.github.com/SakataGintokiYT/ea5fd6c509165548371348fd9db2b454
__________________________________________________________________________________________________

##### Dragon Ball: Raging Blast 2
{PPU[0x7] Thread (main_thread) [0x00543d80]} struct vm::access_violation thrown: Access violation reading address 0x4c5
Log : https://gist.github.com/SakataGintokiYT/68e2f16d065280487d1bc26737090e01
__________________________________________________________________________________________________

##### 魁!!男塾 ～日本よ、これが男である！～ [BLJS10254]
{PPU[0x7] Thread (main_thread) [0x000a65c8]} struct vm::access_violation thrown: Access violation reading address 0x68
Log : https://gist.github.com/SakataGintokiYT/b8ae23b8c28ee12adf5d6d9ec3b1566d

**Comment by Nekotekina** [comment]
OK, but not in this PR...

**Pull request merged**
