### PR TITLE
Following up on MacOS build fix.

### PR DESCRIPTION
**Pull request by devnexen**
Specialisation of llvm_value_t to allow build with LLVM this time.

### CODE REVIEW

**Comment by Nekotekina** [comment]
I think the more correct fix is, specializations for u32/u64/s32/s64 should be replaced with int, long, long long specializations (plus their unsigned counterparts). This way all basic integral types are covered regardless of platform.

**Comment by devnexen** [comment]
well that ought to work too

**Comment by Nekotekina** [comment]
long type needs to compute its bit size as `sizeof(long) * 8`

**Comment by Nekotekina** [comment]
Thanks, looks ok!

**Pull request merged**
