### PR TITLE
Fixed SEQ/SGT/STR/SSG instructions

### PR DESCRIPTION
**Pull request by raven02**
This is for rsx branch,

### CODE REVIEW

**Comment by Syphurith** [comment]
Opcode.. So RSX assembly exists.. Unfortunately i can merely find any document talking about its internals. So sorry for that. Eh is that similar to PPC code itself? Heard RSX is done by Nvidia and Sony.

**Comment by gambrio** [comment]
@Syphurith I don't think there is any actual RSX assembly. I believe the GPU just takes MMIO memory commands and implements them a certain way like DMA, fragment/pixel/vertex shading. I think the real issue with the RSX is that nobody has a clear idea about what it does on its side for every command.

**Comment by Syphurith** [comment]
@gambrio well that's not real assembly. [this](http://www.edepot.com/playstation3.html#PS3_RSX_GPU) `The RSX is a graphical processor unit (GPU) based off of the nVidia 7800GTX graphics processor, and is a G70/G71 hybrid with some modifications. The RSX has separate vertex and pixel shader pipelines.`.[Sony](https://pro.sony.com/bbsccms/ext/ZEGO/files/Cell_Computing_Whitepaper.pdf)
You are right. @raven02 Is that as [this](http://pc.watch.impress.co.jp/docs/2005/0701/kaigai_1a.gif), from [URL](http://pc.watch.impress.co.jp/docs/2005/0701/kaigai195.htm). And there was BSD driver for RSX [Source](http://www.ps3hax.net/2011/09/released-freebsd-rsx-driver/)..

**Comment by Bigpet** [comment]
@Syphurith if you want to have discussions maybe you should just use the forum, the issue tracker is not really well suited to this. Or use the IRC channel (I know you said that your IPs were banned from EFNET but there's plenty of free BNC services like irccloud out there)

**Comment by Syphurith** [comment]
@Bigpet Thanks for those. Eh if posted on forum would the discussion be dealt well? BTW i know now. If need discussion I would try quote someone to a gist or simply post on forum not issues.

**Comment by raven02** [comment]
@Syphurith , see here and should be more clear - http://en.wikipedia.org/wiki/ARB_assembly_language

**Comment by gambrio** [comment]
@raven02 Pretty sure ARB assembly is not truly one-to-one with any standardized graphics pipeline. It may be "characterized" as an "assembly language," but the RSX's commands are not standardized in any way, and they're pretty much all only specific and corresponding to the RSX's microsequencer.

**Comment by Syphurith** [comment]
Thanks as always. Please forgive my ignorance if annoyed. Eh i would stop talking about so in issue and would take a look at those code if interested much. Thus.. Hope works well..

**Pull request merged**
