### PR TITLE
vk: Properly calculate cubemap memory size

### PR DESCRIPTION
**Pull request by kd-11**
With cubemaps, each mip0 is repeated 6 times, so we need 6x the memory to get things done.

Fixes https://github.com/RPCS3/rpcs3/issues/10612

### CODE REVIEW

**Comment by RainbowCookie32** [comment]
Fixes #10612 for me 👍🏼

**Comment by segbed** [comment]
hmm, have no idea why but only after this or previous build I was able to run RDR without stacks in same places (e,g, entrains in the bar in the begining of the game), and also no artifacts in motosrtorm, no performance drops in motorstorm apocalyps.
Previous cool build was 0.0.17-12507. No any changes in PC. Just checked every build every day.
Fantastic! Thanks for your work!

**Comment by dulsan** [comment]
For some reason, when updating (for this fix) RPCS3 finds and error in updating and then deletes itself after the update is complete. This has only happened when this update.

**Comment by AniLeo** [comment]
Unrelated to the PR, OS or 3rd party program interfering

**Pull request merged**
