### PR TITLE
Update cellSubdisplay

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by raven02** [comment]
Would it be better to consolidate all these cell stub into one single PR?

**Comment by scribam** [comment]
Well, my personal opinion is it is better to keep things separated. I think it is easier to do reviews on small changes and if I do a mistake on one commit, it will not have an impact on the others which are independent. And so, it is also easier and faster to merge a PR in the master branch.
But I am not the one who does the review and the merge so maybe @Nekotekina and you @raven02 could give me some advices about how to submit a correct PR? And if I should consolidate or not these PR?

**Comment by kd-11** [comment]
Its better to consolidate PRs but keep commits separate like neko or I do. Its easier to manage.

**Comment by scribam** [comment]
Understood, I will do like that. Thanks for the reply.

**Pull request closed without merging**
