### PR TITLE
qt: fix asm instructions highlighting

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by Megamouse** [comment]
that's not what i meant and it's wrong anyway

**Comment by Megamouse** [comment]
everything after Commit a8f19fb colorizes the commata as well.
Also the change in this PR breaks stuff like:
`DP4 o[0].w, v[0], c[259];`
The 4 will be black

**Comment by Megamouse** [comment]
do you have an example of the multi line comments?

**Comment by Megamouse** [comment]
fixed in: 0b854c30e4c9036932e62c31a9d9b1ebb058173c (part of my PR)

**Comment by Megamouse** [comment]
lgtm.
should be squashed though

**Comment by scribam** [comment]
Display with "DP4 o[0].w, v[0], c[259];" and multi-line comments (right column)

screenshot from 2018-06-12 11-06-49

Squash before merge

**Comment by Megamouse** [comment]
looking at the group syntax you can even remove the -? if I am correct

**Comment by Megamouse** [comment]
scratch that
It does add a sign.

**Pull request merged**
