### PR TITLE
White space and switch to .format() strings

### PR DESCRIPTION
**Pull request by Cabalist**
This is a simple PR that just cleans up some python code.   

I noticed git-clang-format was python2 only.   I can get that working with Py3 if that is desired.

### CODE REVIEW

**Comment by Cabalist** [comment]
Actually it looks like that has already happened upstream :)

https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format

**Comment by JohnHolmesII** [comment]
I think those are old files. I don't know of anyone who uses them. I think the paths updater can be deleted, actually.

**Comment by AniLeo** [comment]
They are used on LLVM

**Comment by JohnHolmesII** [comment]
@AniLeo what part? Cause you can delete them and everything works fine.

**Comment by AniLeo** [comment]
After you've compiled once probably, but it's used as I had to mess with them a while ago in order for it to compile

**Comment by LuismaSP89** [comment]
My games works Ok with this PR, but in some cases "Guilty Gear XRD rev 2 for example" music stop playing after 1 minute (more or less) while in battle.

**Pull request merged**
