### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by allens39**
Outdated software versions...

### CODE REVIEW

**Comment by Megamouse** [comment]
these represent our minimum requirements.... so most of it is not really needed

**Comment by HenningJW** [comment]
This project is not GPLv3 like you stated in the change. Also requirements are the lowest version you need to build (in a sane way). Not the latest versions.

**Comment by AniLeo** [comment]
How to include PHP code in a C++ project?

**Comment by allens39** [comment]
@AniLeo start reading https://devzone.zend.com/1435/wrapping-c-classes-in-a-php-extension/

**Comment by HenningJW** [comment]
@allens39 you should consider appreciating the work that is done by AniLeo, instead of flaming him for a fast reaction. It is obvious that this codebase and usecase isn't as easy to get into as most others and even very solid Cpp knowledge is only the first step. What do you think would happen if such annoying and useless pull requests would need to be handled by the core developers ...

**Comment by AniLeo** [comment]
@HenningJW He wants a web dev to fix the emulator fast, I asked how to include PHP code in a C++ project then

image

image

but I only got how to make zend extensions for PHP with C++ classes

---

I can also pull more QSS themes, if you find that it fixes anything

**Pull request closed without merging**
