### PR TITLE
SPU LLVM: optimize register stores

### PR DESCRIPTION
**Pull request by Nekotekina**
Custom pass erasing unnecessary stores and sinking some of the stores out of the loop. May restore some of the recent performance loss.

### CODE REVIEW

**Comment by Asinin3** [comment]
Both me and Loweys gained 4-5 fps in RDR and the 1% lows are much better too. Well done. Hope we get some people testing this further against https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-7081b89e976ad7f931c926022bd93ddd9778347c/rpcs3-v0.0.27-14845-7081b89e_win64.7z too (build before LLVM16)

**Comment by solarmystic** [comment]
Preliminary results look good but not every game gets an increase in my usual 5 game bench.

**GOW3 - Average FPS is now within margin of error, but 1% low FPS has dropped quite a bit.** 

14845 (Last Pre-LLVM16 Master) - 130/103/70 FPS
PR - 129/89/68 FPS 

**GOWA - Has higher FPS compared to pre-llvm16 master now.** 

14845 (Last Pre-LLVM16 Master) - 64/55/50 FPS
PR - 66/59/54 FPS

**DeS - Another performance win compared to pre-llvm16 master.**

14845 (Last Pre-LLVM16 Master) - 102/84/81 FPS
PR -  106/88/65 FPS

**TLOU - No change compared to pre-llvm16 master.**

14845 (Last Pre-LLVM16 Master) - 50/46/43 FPS
PR -  50/46/43 FPS

**P5 - Minor performance regression still present compared to pre-llvm16 master, has declined further compared to current 16.01 LLVM master (14876)**

14845 (Last Pre-LLVM16 Master) - 97/71/60 FPS
14876 - 91/65/57 FPS
PR -  89/65/58 FPS

**Comment by Darkhost1999** [comment]
I don't know specifically which changes made to RPCS3 helped.
But I was using this PR when GTAV Scouting the Port actually worked to take pictures of the soldier on the boat.
I can now hopefully finish the entire storyline and plan a 100% completionist playthrough if I can.

I think Afrika recognizing pictures can be retested now as well see if issues solved.

**Comment by cipherxof** [comment]
Performance is slightly better than master but worse than 14845.

<details>
  <summary>14845</summary>

Screenshot from 2023-04-15 14-25-33
  
</details>

<details>
  <summary>14876</summary>

Screenshot from 2023-04-15 14-31-42
  
</details>

<details>
  <summary>14877</summary>

Screenshot from 2023-04-15 14-36-23
  
</details>

**Comment by Ordinary205** [comment]
I tested the PR build with 14845 and 14876 on two games.

Red Dead Redemption:
14845: (Before LLVM 16.0.0)
Test 15 (2)
Test 16 (2)

14876:
rpcs3 exe 2023 04 15 - 16 16 51 02 - frame at 1m42s (2)
rpcs3 exe 2023 04 15 - 16 16 51 02 - frame at 3m26s (2)

PR build:
rpcs3 exe 2023 04 16 - 12 56 37 02 - frame at 1m56s (2)
rpcs3 exe 2023 04 16 - 12 56 37 02 - frame at 3m0s (2)


The Last of Us:
14845: (Before LLVM 16.0.0)
rpcs3 exe 2023 04 15 - 16 32 13 04 - frame at 1m19s (2)

14876:
rpcs3 exe 2023 04 15 - 16 26 26 03 - frame at 0m59s (2)

PR build:
Test 19

**Comment by Nekotekina** [comment]
Improved the logic, please retest.

**Comment by Ordinary205** [comment]
Heres another results for 3 games on this PR build.

Red Dead Redemption:
14845: (Before LLVM 16)
Red Dead Redemption 1 (3)
Red Dead Redemption 1 (4)

PR Build:
Red Dead Redemption Test (2)
Red Dead Redemption Test 1 (2)


The Last of Us:
14845: (Before LLVM 16)
rpcs3 exe 2023 04 15 - 16 32 13 04 - frame at 1m19s (2)

PR Build:
The Last of Us (2)


God of War Ascension:
14845: (Before LLVM 16)
God of War (2)

PR Build:
God of War ascension (2)


The performance is now restored.

**Comment by solarmystic** [comment]
> Improved the logic, please retest.

@Nekotekina The latest pr commit cauises random crashes during SPU compilation now, making testing quite difficult. 

Crashlog upon attempting to boot up Persona 5.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11242419/RPCS3.log)

**Comment by Ordinary205** [comment]
I might have to retest the commit, because solarmystic was experiencing a crash.

**Comment by Nekotekina** [comment]
I think I fixed the crash, please try again.

**Comment by solarmystic** [comment]
> I think I fixed the crash, please try again.

SPU compilation crashes are fixed. Doing the usual 5 game bench compared to the previous pr commit that worked, pretty much identical or within margin of error performance in every single game.

**GOW3 - identical to the previous pr commit and pre llvm master, lower 1% FPS compared to pre-llvm16 master.**

14845 (Last Pre-LLVM16 Master) - 130/103/70 FPS
Previous PR commit that worked (b1f80256) - 129/89/68 FPS 
Current PR commit - 130/90/68 FPS

**GOWA - reduced average FPS but still within Margin of Error, ** 

14845 (Last Pre-LLVM16 Master) - 64/55/50 FPS
Previous PR commit that worked (b1f80256) - 66/59/54 FPS
Current PR commit - 65/53/49 FPS

**DeS - Identical to previous pr commit that worked, better than pre-llvm16 master.**

14845 (Last Pre-LLVM16 Master) - 102/84/81 FPS
Previous PR commit that worked (b1f80256) -  106/88/65 FPS
Current PR commit - 106/88/85 FPS

**TLOU - Within margin of error compared to previous pr commit that worked, and pre-llvm16 master.**

14845 (Last Pre-LLVM16 Master) - 50/46/43 FPS
Previous PR commit that worked (b1f80256) -  50/46/43 FPS
Current PR commit - 51/46/42 FPS

**P5 - Identical to previous pr commit that worked, minor performance regression still present compared to pre-llvm16 master, has declined further compared to current 16.01 LLVM master (14876)**

14845 (Last Pre-LLVM16 Master) - 97/71/60 FPS
14876 (current LLVM16.01 Master) - 91/65/57 FPS
Previous PR commit that worked (b1f80256) - 89/65/58 FPS
Current PR commit - 89/65/57 FPS

SS taken of all current PR results:-
[13672 PR.zip](https://github.com/RPCS3/rpcs3/files/11242667/13672.PR.zip)

**Comment by Nekotekina** [comment]
Another test, please.

**Comment by solarmystic** [comment]
> Another test, please.

**Pretty much within margin of error (MOE) or unchanged across the board, with the exception of Persona 5 which continues to decline in performance compared to previous pr and pre-llvm16 master.**

**GOW3 - Better 1% low FPS compared to previous master, within MOE for average FPS.**

14845 (Last Pre-LLVM16 Master) - 130/103/70 FPS
Previous PR commit (4342ddac) - 130/90/68 FPS
Current PR commit (5e2844f3) - 129/98/69

**GOWA - Within MOE compared to previous pr commit, with better 1% and 0.1% low FPS.**

14845 (Last Pre-LLVM16 Master) - 64/55/50 FPS
Previous PR commit (4342ddac) - 65/53/49 FPS
Current PR commit (5e2844f3)- 64/56/53 FPS

**DeS - Within MOE to previous pr commit that worked, better than pre-llvm16 master.**

14845 (Last Pre-LLVM16 Master) - 102/84/81 FPS
Previous PR commit (4342ddac) - 106/88/85 FPS
Current PR commit (5e2844f3)- 106/87/84 FPS

**TLOU - Within margin of error compared to previous pr commit that worked, and pre-llvm16 master.**

14845 (Last Pre-LLVM16 Master) - 50/46/43 FPS
Previous PR commit (4342ddac) - 51/46/42 FPS
Current PR commit (5e2844f3)- 50/45/41 FPS

**P5 - Identical to previous pr commit that worked, minor performance regression still present compared to pre-llvm16 master, has declined further compared to current 16.01 LLVM master (14876)**

14845 (Last Pre-LLVM16 Master) - 97/71/60 FPS
14876 (current LLVM16.01 Master) - 91/65/57 FPS
Previous PR commit (4342ddac) - 89/65/57 FPS
Current PR commit (5e2844f3)- 87/62/57 FPS

SS taken of all current PR results:-

[take 3.zip](https://github.com/RPCS3/rpcs3/files/11243831/take.3.zip)

**Pull request merged**
