### PR TITLE
[Experimental] SPU LLVM: More compilation threads

### PR DESCRIPTION
**Pull request by elad335**
Target: SPU Compilation performance 🚀🚀🚀
Add another compilation thread for 6+ threaded cpus, at the expense of making some SPU threads relax a bit while compiling blocks.
This PR only affects 6-11 threaded CPUs.

### CODE REVIEW

**Comment by EmulationChannel** [comment]
@elad335 I tested RED DEAD REDEMPTION 14600KF and I'm able to hit 60fps at certain times, now with this PR I'm well below 45 ah 49

**Comment by elad335** [comment]
Test in production 🚨🚨🚨

**Comment by trantien1997** [comment]
@elad335 with new version, I cannot start Prince of Persia - The Forgotten Sands (Europe) (En,Fr,De,Es,It,Nl), when I switch previous version (rpcs3-v0.0.30-16162-df4fc947_win64), the game is started smoothly.

**Comment by elad335** [comment]
Those are quite a few versions behind, be more specific

**Comment by trantien1997** [comment]
> Those are quite a few versions behind, be more specific

Maybe your recent changes have made rpcs3 unstable.

**Comment by Asinin3** [comment]
> > Those are quite a few versions behind, be more specific
> 
> Maybe your recent changes have made rpcs3 unstable.

And maybe your comment isn't useful because it doesn't rule out one build? Use https://rpcs3.net/compatibility?b and find the exact build that caused the issue. Noting that some of the previous builds have their version number crossed out because they are known to be broken, do not test with those builds.

**Comment by trantien1997** [comment]
> > > Those are quite a few versions behind, be more specific
> > 
> > 
> > Maybe your recent changes have made rpcs3 unstable.
> 
> And maybe your comment isn't useful because it doesn't rule out one build? Use https://rpcs3.net/compatibility?b and find the exact build that caused the issue. Noting that some of the previous builds have their version number crossed out because they are known to be broken, do not test with those builds.

image
it has playable status

**Comment by AniLeo** [comment]
Locking as there's no useful bug report, only noise.

**Pull request merged**
