### PR TITLE
Qt: Allow disabling the auto-updater

### PR DESCRIPTION
**Pull request by linkmauve**
It is a nice feature for users, but it gets annoying fast to have to close it all the time when developing.

### CODE REVIEW

**Comment by dio-gh** [comment]
`Config` -> `GUI` -> `UI Options` -> `Check for updates on startup`

**Comment by Ghostotakoi** [comment]
I like more disabled, what if you put some button that say check if update is available??

**Comment by dio-gh** [comment]
🤦‍♂ My previous comment points you (and the OP) to that exact option.

**Comment by JohnHolmesII** [comment]
No, it does not. I believe he was asking for a *button* that one would push when one wants to update. This way the auto update feature could be a manual feature.

As for this pr...
No. Just no.

**Comment by MSuih** [comment]
There is already a check for updates button as well.

**Comment by JohnHolmesII** [comment]
Ah yes, I see it hiding under the help menu. I think a *button*, on the main gui face, would be best. People couldn't really miss that. Well, hopefully not 🤣

**Comment by Megamouse** [comment]
Might as well ifdefs every single option in the settings. Sorry but this is really not gonna get merged.

**Comment by HerrHulaHoop** [comment]
Many desktop applications have "Check for updates" option under the last tab which is generally named _Help_. It's not something new.

**Comment by linkmauve** [comment]
I didn’t know about the setting, sorry for the noise.

**Comment by Hirato** [comment]
IMO this is still functionality that downstream Linux Distros would appreciate, as they generally want users to install and run software exclusively through their package managers and not have the program retain any functionality with which to update itself.
At least not beyond letting you know that there is a newer version available.

**Pull request closed without merging**
