### PR TITLE
Vulkan: swizzle dot product functions

### PR DESCRIPTION
**Pull request by raven02**
https://github.com/RPCS3/rpcs3/issues/1846

### CODE REVIEW

**Comment by kd-11** [comment]
@raven The swizzle is in the wrong place (vec4 is already 4 component).
A better solution here is actually remove the vec4() wrapping and swizzle the inner block to .xxxx

**Comment by raven02** [comment]
Alright .Will stripe off the vec4 .

**Comment by raven02** [comment]
@kd-11 .I will merge it if you okay .

**Comment by kd-11** [comment]
Its okay, but looking back at the original issue properly, I don't see why it should have been a problem since dot is guaranteed to always return a single float value. I'll take a closer look soon and update. This is okay to merge although you should first confirm it fixes the linked issue. If it does, we might have to file a bug report with the glslang repo.

**Comment by raven02** [comment]
I'm closing this one and will pull a new one when we find proper fix later on the real problem

**Pull request closed without merging**
