### PR TITLE
vk: Properly enable window resizing

### PR DESCRIPTION
**Pull request by kd-11**
Second attempt at window resizing. I've cleaned up the flip code a bit as well and added proper synchronization that will hopefully allow nvidia users to resize without crashing.

### CODE REVIEW

**Comment by kd-11** [comment]
Needs some testing from NV users to confirm that its working for them as well.

**Comment by Nezarn** [comment]
@kd-11 well it doesn't crash anymore, but screen isn't correct after resize
max sized
rpcs3_2016-06-16_18-15-25

random resize:

rpcs3_2016-06-16_18-16-06

log: https://gist.github.com/Nezarn/9e865a055b7ab407d4321d0eb383abf8

**Comment by SakataGintokiYT** [comment]
@kd-11 
Works :)

Log : https://gist.github.com/SakataGintokiYT/7039f074d94a6360923c58663e9f689e

**Comment by kd-11** [comment]
@Nezarn I think we'll track the scaling issue with vulkan and nvidia separately. It's the same issue as https://github.com/RPCS3/rpcs3/issues/1655

**Comment by Nezarn** [comment]
@kd-11 but its a bit different than that, since if i don't resize the window, it works fine (while in #1655 game is like that even without touching the window) or is it really the same issue?

example:1280x720
rpcs3_2016-06-16_18-28-32

**Comment by kd-11** [comment]
@Nezarn We never draw to the actual window ever. There is always scaling in place when we copy the final image to the screen and scaling always happens unless the game's internal resolution matches the window size. This means that for every game, there is a "perfect" window size where everything will be ok, but resizing will trigger the scaling. Try running commercial games at 720x480 and see what happens.

**Comment by Nezarn** [comment]
@kd-11 oh i see now, thanks for the answer :+1:

**Pull request merged**
