### PR TITLE
Gives ANSI path to curl CURLOPT_CAINFO

### PR DESCRIPTION
**Pull request by RipleyTom**
Roundabout way of getting ansi path out of utf-8 path but tested and it works.
This should fixes issues where `Problem with the SSL CA cert (path? access rights?)` error was reported.

### CODE REVIEW

**Comment by Nekotekina** [comment]
There is another problem, GetEmuDir returns some variable configured by the user. I recommend using GetModuleFileNameW(nullptr...) to get actual rpcs3.exe path and cut it.

**Comment by Megamouse** [comment]
And also put that ansi conversion into some util function

**Comment by RipleyTom** [comment]
Isn't using GetEmuDir() fine? I thought that variable was there specifically if you want to use another directory than the one where the .exe is as a "home" directory.

**Comment by Nekotekina** [comment]
It's legacy variable for VFS paths prefixes. You can change it, but certificates won't be there.

**Pull request merged**
