### PR TITLE
Add another pattern to ppu analyzer imports

### LINKED ISSUE #3942: Jump tables not found spam; emulator hanging
After starting the game, the emulator is hanging and shows nothing. After two hours of waiting, I had to stop it.
[Robert_Ludlums_The_Bourne_Conspiracy.txt](https://github.com/RPCS3/rpcs3/files/1565178/Robert_Ludlums_The_Bourne_Conspiracy.txt)

### PR DESCRIPTION
**Pull request by elad335**
Fixes The Bourne Conspiracy (from hanging the emulator more than half an hour into booting instantaneously). 
Fixes #3942.

image

### CODE REVIEW

**Comment by Xcedf** [comment]
This PR also fixes same long PPU initialization (about 2 minutes) in R&C Quest For Booty, loads instantly now

**Comment by uaqlover** [comment]
Could fix https://github.com/RPCS3/rpcs3/issues/5796 .?

**Comment by elad335** [comment]
Note for testers: ppu cache version has been bumped.

**Comment by elad335** [comment]
Can probably merge.

**Pull request merged**
