### PR TITLE
rsx: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
Implements a few minor features to improve accuracy. I'm submitting this as the whole set looks like it might grow quite a bit before its all ready and I'd like to avoid tracking a huge PR. I expect minimal number of regressions.
- Includes WIP research into getting WCB working correctly. Should now mostly work correctly on openGL and correct on vulkan where on swizzle contexts are involved
- Enables blitting from main memory to local (RSX) memory using hw acceleration. A few more titles no longer need the slow WCB path for this
- Includes a fix for nvidia memory leak when window is minimized
- Includes FP fixes to take into account data range modifiers in SRC1. Fixes negative color values getting to the tonemapping passes in some games (Dark Souls 2)

### CODE REVIEW

**Comment by Xcedf** [comment]
Here's my list of things that improved
House of the Dead Overkill
Shadow of the Collossus
Sly Cooper Thieves in time
no longer need WCB
Condemned 2
Bayonetta
Amy
UFC 2009 Undisputed 
these ones no longer need Gpu Texture scaling to render the picture
Metro Last Light improved too
before (both renders with WCB on/off)

after (vulkan)

ogl

the game is quiet unstable vulkan has 
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\users\zero\desktop\kd11\rpcs3\emu\rsx\rsx_cache.h:88)

**Comment by money123451** [comment]
on master @Xcedf that is not exactly true WCB on with opengl for me has been getting me this
2017-11-15 18_26_42-fps_ 18 26 _ opengl _ 0 0 4-6089 _ metro_ last light _ npub31219
it has and still goes ingame post #3661 
2017-11-15 18_30_06-fps_ 10 64 _ opengl _ 0 0 4-6089 _ metro_ last light _ npub31219
(on my AMD card so it might be another game that works better on amd and not nvidia? would need more testing) PPU LLVM crashes the game with this sort of screen after you hit start
2017-11-15 18_40_15-fps_ 28 69 _ opengl _ 0 0 4-6089 _ metro_ last light _ npub31219
as well on master and vulkan has had issues for a bit with crashing before getting to the main menu (might be a amd issue at with vulkan at this point).

And with this commit it causes metro last light to at best crash with any setting i try or at worse send the program into a non responsive state
2017-11-15 18_57_20-fps_ 7 00 _ opengl _ 0 0 4-8-kd-11_master _ metro_ last light _ npub31219 not
log [master](https://www.dropbox.com/s/lrafrs2w8xdruh8/RPCS3MASTMETROLL.log.gz?dl=0)
log [kd-11](https://www.dropbox.com/s/bf7512c2j32e3ud/RPCS3KD-11METROLL.log.gz?dl=0)
This became a really long post.

PS yes I know I should update the forum. Soon(TM)

**Comment by Xcedf** [comment]
never had any of this for me before this PR on my Nvidia, only black render from my first screen

**Comment by rodjun** [comment]
This PR has some changes to shader generation, have you deleted your old shaders @Xcedf ?

**Comment by MarioSonic2987** [comment]
In KH2, background in pause menu works.
image
image

In One Piece: Pirate Warriors, lighting is improved.
image
image

**Comment by Kravickas** [comment]
obrazek
First time i see render in Cars 3, master is just black screen

**Comment by Gamedev1909** [comment]
https://youtu.be/GnQe7ArfnDo lighting is fixed in fear 2 this video is a before and after. before being the master and after kd-11 build enjoy

**Comment by Gamedev1909** [comment]
If you need a more in depth look at fear 2 here is a 22 min video that shows all https://youtu.be/Fv4D37lNxWU

**Comment by digitaldude555** [comment]
Before
screenshot 2211
After
screenshot 2201
screenshot 2210
Graphics fixed.

**Comment by kamer1337** [comment]
fixed black screen in tony hawk's proving ground

**Comment by Kravickas** [comment]
Regression
MXGP: The Official Motocross Videogame

Master
bez nazvu

kd pr
bez na1zvu

**Comment by kd-11** [comment]
Please retest if regressions have been fixed.

**Comment by Gamedev1909** [comment]
regressions
FEAR 2 regressions in lighting 

tomb raider reboot regression 
re

but thats it

**Comment by Gamedev1909** [comment]
rebs3
bioshock 3 has flicker enough to cause my eyes to bleed now

**Comment by Kravickas** [comment]
MXGP : https://github.com/RPCS3/rpcs3/pull/3744#issuecomment-344943419

Not fixed

**Comment by Ekaseo** [comment]
In Dragon quest builders there are some missing effects and textures

**Comment by kd-11** [comment]
Hmm. Ok. Looks like abs precedes precision then (wrt MXGP).

**Comment by Kravickas** [comment]
Green hulk grill from Master fixed
obrazek

**Comment by kd-11** [comment]
Reordered the modifiers a bit, hopefully makes the regressions with the last commit go away. If not, try and get a renderdoc trace of before and after (using openGL renderer) for further inspection.

**Comment by isshininu** [comment]
Offtopic:

>Fixes negative color values getting to the tonemapping passes in some games (Dark Souls 2)

Is it bootable now?

**Comment by Kravickas** [comment]
Its weird lol, OGL is even worse i think..
https://youtu.be/ib2gvRNpwcU

**Comment by Gamedev1909** [comment]
bioshock 3 and fear 2 havnt changed

**Comment by Asinin3** [comment]
@Xcedf Bayonetta hasn't needed WCB since late September, for the other improvements do you mind messaging me on discord? (Asinine)

**Comment by kd-11** [comment]
@Kravickas to capture with ogl you need to enable the legacy buffers option. Its in the hidden debug tab. Vulkan traces are not properly sharable across different gpus and drivers.
As for the other stuff, this set is not the complete set from my fork, but only a part of it. Check if  it works correctly on my builds.

**Comment by Gamedev1909** [comment]
If I capture traces in ninja gaiden sigma and report it could that help fix it ?

**Comment by kd-11** [comment]
It has never worked correctly so theres no point of reference. As a general rule, maybe it helps, but its looking for a needle in a haystack. Open an issue and attch the trace for sigma and hopefully I'll get to it and its not complicated. Right now I just need for mxgp which works correctly on master.

**Comment by Gamedev1909** [comment]
Alrighty cool

**Comment by Asinin3** [comment]
This introduced a freeze for me with Eternal Sonata, whenever exiting fullscreen (not entering) the window freezes and then i have a swapchain error:
`E {rsx::thread} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 1280, 720, Requested = 2560, 1440`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1484573/RPCS3.log.gz)

Unsure if it's another Nvidia specific error.

**Comment by kd-11** [comment]
Hmm, not really surprising. The code is waiting for a window restore event and assumes swapchain was not created because the window was minimized. Maybe I should just have it wake up on any sizing command and not just restore from minimization. All that might have to wait a bit until the more serious issue (MXGP) is fixed

**Comment by Kravickas** [comment]
There it is https://drive.google.com/open?id=1Vr1bX9VU0AqByGngyncO9zLhUIL_hG2k
Hope it helps, i will be offline for 24h, so u have time for possible fix :)

**Comment by Xcedf** [comment]
@Asinin3 i talked not about wcb but about Gpu Texture Scale option, game required it ON to render some stuff, now it just work fine no matter ON/OFF

**Comment by AniLeo** [comment]
@kd-11 yes

**Comment by kd-11** [comment]
@Kravickas What does it look like now on your setup? It does not look the same as master but it certainly looks nothing like that screenshot you posted. The only change I have now is that it has the yellow filter issue not shader clipping like in the screenshot you posted.

**Comment by kd-11** [comment]
@Asinin3 Check if the latest commit fixes the hanging when exiting fullscreen

**Comment by Asinin3** [comment]
@kd-11 That fixed it.

**Pull request merged**
