### PR TITLE
[Linux] Fix fatal error dialog in AppImage

### PR DESCRIPTION
**Pull request by Nekotekina**
I'll try to figure out why fatal error dialog is broken with appimage

### CODE REVIEW

**Comment by Nekotekina** [comment]
Need to test AppImage from https://dev.azure.com/nekotekina/nekotekina/_build/results?buildId=843&view=artifacts&type=publishedArtifacts
It should display "test" error dialog.

**Comment by sampletext32** [comment]
Displays "test" On Windows 10. 
I5 10210U + Mx250.
image

**Comment by doesthisusername** [comment]
Is this what you're looking for? Downloaded LinuxBuild.GCC and ran it.
image

**Comment by Nekotekina** [comment]
Yes, thanks

**Comment by JohnHolmesII** [comment]
Push 9a1214af does not open for me, just hangs at execute. Only prints "Debugger: 0" to stdout.

**Comment by Nekotekina** [comment]
This is strange. I removed test commit though.

**Comment by JohnHolmesII** [comment]
Hmm, master has same problem. Something must have changed on my system then, ignore.

**Pull request merged**
