### PR TITLE
Porting of DH's user clip implementation in gl

### PR DESCRIPTION
**Pull request by O1L**

### CODE REVIEW

**Comment by kd-11** [comment]
Looks good, although I wish we'd avoid the raw bit selection e.g (1 << 5). Otherwise, it should be okay.
@raven02 Could you check if blade arcus from shining ex is affected by this PR? The intro sequence uses clip planes and iirc it caused problems with the broken clip planes in vulkan before.

**Comment by raven02** [comment]
Sure .Need someone restart the appveyor.

**Comment by O1L** [comment]
@raven02 also remember about this issue https://github.com/RPCS3/rpcs3/issues/2136 (I had to revert these changes for user_clip sample testing)

**Comment by raven02** [comment]
@O1L .That issue will be fixed by https://github.com/RPCS3/rpcs3/pull/2140 .

Please rebase and we can then merge this pull.

**Comment by raven02** [comment]
@O1L , do you mind sharing the user_clip.ppu.elf ?

**Comment by O1L** [comment]
@raven02 http://rgho.st/private/8vWwYMVrn/013798eaf6304ba7ae191c03fdf7f353

**Comment by raven02** [comment]
Thanks @O1L

**Comment by raven02** [comment]
Blade arcus from shining EX also looks fine.

**Pull request merged**
