### PR TITLE
RSX: Puts vertex buffer in array and in register in a variant type.

### PR DESCRIPTION
**Pull request by vlj**
This removes the logic of selecting between buffer array or register outside of backends.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Weird mapbox::util namespace, probably use std

**Comment by vlj** [comment]
I repushed using .clang-format cleaning.

**Comment by andre4688** [comment]
this broken BUGFIX in-game graphic outrun  &  Silent Hill 3 HD Colletion  for OpenGL.
please correct OpenGL games is affecting {rsx::thread} class std::out_of_range thrown: invalid string position

**Comment by vlj** [comment]
@andre4688 does it work now with gl ?

**Comment by SakataGintokiYT** [comment]
@vlj 
Fotoszok.pl
F {rsx::thread} class std::out_of_range thrown: invalid string position

**Comment by andre4688** [comment]
It is not corrected {rsx :: thread} class std :: out_of_range thrown: invalid string position
use NVIDIA 635n 
some silent Hill error games etc.
F {rsx :: thread} class std :: runtime_error thrown: OpenGL error: invalid operation
(In file C: \ rpcs3 \ rpcs3 \ Emu \ RSX \ GL \ GLG Render.cpp: 504, function GLG Render :: end).

It can also be graphics card not this well

**Comment by vlj** [comment]
Gl should be fixed.

**Comment by vlj** [comment]
By the way how do you run Outrun Arcade ? Here it crashes in PPU interpreter 2.

**Comment by SakataGintokiYT** [comment]
* PPU interpreter 2

**Comment by vlj** [comment]
Doesnt work with it. What is LLE config ?

**Comment by SakataGintokiYT** [comment]
Fotoszok.pl

**Comment by vlj** [comment]
Ok I got it working, I needed to enable /host_root/

**Comment by raven02** [comment]
@vlj , looks like still hitting invalid string in Outrun using GL backend

F {rsx::thread} class std::out_of_range thrown: invalid string position

**Comment by vlj** [comment]
replaced mapbox::util with std namespace.
Can somebody test gl backend ?

**Comment by raven02** [comment]
Just checked however still hits invalid string in GL backend

**Comment by andre4688** [comment]
Outrun Arcade fix   opengl  https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3295
try fix F {rsx::thread} class std::runtime_error thrown: Invalid RSX method 0x2c8 (arg=0x2cf0000)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:34 ScoggerHD v0.1  games etc

**Comment by vlj** [comment]
Does it work now with GL ? Here it does with Outrun

**Comment by raven02** [comment]
Vertex issue fixed for GL backend though still hit with invalid string here.

**Comment by raven02** [comment]
DX12 and Vulkan vertex issue remains.

dx12
vk

**Comment by vlj** [comment]
DX12 and Vulkan should be fixed (I could start the race).
I don't know what happens to GL though, looks like a shader error but the commit doesn't modify shader generation part.

**Comment by vlj** [comment]
Looks like GL doesn't work even before.

**Comment by SakataGintokiYT** [comment]
@vlj 
*Regression by commit #2018  
`F {rsx::thread} class std::out_of_range thrown: invalid string position `

**Comment by raven02** [comment]
Probably we can ignore GL for this time being and i'm bringing back the common decompiler for GL backend .

**Comment by vlj** [comment]
Looks like there is a spurious build failure

**Pull request merged**
