### PR TITLE
PPU: register undocumented functions in cellSysmodule

### PR DESCRIPTION
**Pull request by raven02**
fix https://github.com/RPCS3/rpcs3/issues/1971

### CODE REVIEW

**Comment by Nekotekina** [comment]
At least include B498BF77 codes in function names and don't mention "index" anywhere.

**Comment by Nekotekina** [comment]
Don't merge yet, I'll try to find some info about these functions.

**Comment by raven02** [comment]
Sure. I'll not merge until getting green signal from you.

**Comment by Nekotekina** [comment]
OK, merge it. I investigated it a bit, seems that cellSysmoduleLoadModule must return some real status of every module, it's not easy to implement. With some modifications I can avoid calling these functions at all, but this doesn't block this PR from merging.

**Comment by raven02** [comment]
Alright. Thanks @Nekotekina

**Pull request closed without merging**
