### PR TITLE
vk: Refactor some renderer objects a bit

### PR DESCRIPTION
**Pull request by kd-11**
Mostly involves moving custom types to a separate file to keep things clean. Command buffer lists are also now managed centrally in one place and auxilliary tasks are now also using a command buffer list instead of a one-time use command buffer behind a mutex. Required for some upcoming PRs which makes extensive use of the secondary command buffer list to keep GPU latency down.

### CODE REVIEW

**Comment by Darkhost1999** [comment]
I notice this PR is drafted and maybe not ready for testing.
GTA V no longer goes in game
PR: F 0:03:09.789804 {RSX [0x00b4090]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
[GTAVPR.log](https://github.com/RPCS3/rpcs3/files/8104631/GTAVPR.log)
Master is working
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8104632/RPCS3.log)

Just thought I would share

**Comment by Xcedf** [comment]
GTA V goes ingame no problem with this PR
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8105114/RPCS3.log.gz)

**Comment by Darkhost1999** [comment]
> @Darkhost1999 why's your GTAVPR.log is about Dante's Inferno?

I don't know. That's not even the game I played when I copied the log to my desktop. I copied right after the fatal error. I'll reupload

**Comment by Darkhost1999** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8105157/RPCS3.log)
And of course it's not giving me the fatal error. IDK I was just going down my games list booting into game all my games and then gtav didn't work. And I renamed the log placed it on my desktop. uploaded it here and the contents of that log does not equal anything I have done today. There should at least be 10 more games in that log

**Comment by Darkhost1999** [comment]
> @Darkhost1999 why's your GTAVPR.log is about Dante's Inferno?
image
It's not

**Comment by Darkhost1999** [comment]
As it stands how I created this issue was by booting multiple games without closing RPCS3. The game works fine when booted alone. And I wouldn't know how to exactly reproduce on master. Let's assume this issue is unrelated to this PR. But is an issue that I don't know how to replicate.

**Comment by Megamouse** [comment]
You might as well remove those unused variables I showed you the other day.

**Comment by kd-11** [comment]
> As it stands how I created this issue was by booting multiple games without closing RPCS3. The game works fine when booted alone. And I wouldn't know how to exactly reproduce on master. Let's assume this issue is unrelated to this PR. But is an issue that I don't know how to replicate.

Are you able to replicate on the PR? Like, has it happened more than once on the PR?

**Comment by Darkhost1999** [comment]
> > Has it happened more than once on the PR?

No, sorry

**Comment by kd-11** [comment]
Then I'll proceed with this implementation. If any major issues are observed I will be able to work on them individually.

**Pull request merged**
