### PR TITLE
Vulkan: Avoid extra sync

### PR DESCRIPTION
**Pull request by vlj**
This is PR #1620 reworked, hope this time it'll work better.

### CODE REVIEW

**Comment by kd-11** [comment]
Need AMD testers as I'm away from my AMD system atm. @AniLeo could you test AMD for crashes?

**Comment by AniLeo** [comment]
@kd-11 On it

**Comment by AniLeo** [comment]
I'm afraid Castle Crashers no longer boots up.

screenshot_19

```
{PPU Thread[0x1] (main_thread)[0x002248e8]} cellGcmSys TODO: cellGcmSetGraphicsHandler
{PPU Thread[0x27] (_SPU_printf_server)[0x001bdc60]} HLE: Last syscall: 130 (sys_event_queue_receive)
{PPU Thread[0x28] (VectorRenderer_0)[0x00035334]} HLE: Last syscall: 92 (sys_semaphore_wait)
{rsx::thread} Exception: Assertion failed! Result is FFFFFFFDh
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp:748, in function VKGSRender::sync_at_semaphore_release)
```
Log @ [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/191156/RPCS3.zip)

**Comment by vlj** [comment]
Does latest version works ? I forget to remove an extra vkCommandBufferEnd in sync_at_semaphore

**Comment by AniLeo** [comment]
Waiting for the AppVeyor to build

**Comment by Ekaseo** [comment]
i have kernel problems when trying to enter some games ingame and some crash randomly... same message as before

**Comment by vlj** [comment]
kernel crash seems to happen when there are validation error. For instance in Resogun.

**Comment by SakataGintokiYT** [comment]
State regression slow down on #1620 is better speed in Castle Crashers [menu 30 fps / in game 20-30 FPS ]
#1630  [menu 17 fps / in game 14-18 FPS ]

**Comment by AniLeo** [comment]
Woah. 
Castle Crashers just froze (when loading ingame, after the menus) with
```
{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: Src type 3 used, please report this to a developer.
{rsx::thread} RSX: Warning, version 420 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:79: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.


{rsx::thread} RSX: 
(...)
{rsx::thread} Exception: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:280, in function VKFragmentProgram::Compile)
RSX: Program destructor invoked!
```

It was playable (at least the first level) before. Weird.
Log @ [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/191182/RPCS3.zip)

**Comment by SakataGintokiYT** [comment]
@AniLeo 
#1615

**Comment by AniLeo** [comment]
This doesn't seem to crash the driver, and I found no regressions whatsoever.

**Comment by kd-11** [comment]
@AniLeo any difference in speed?

**Comment by AniLeo** [comment]
@kd-11 I somehow felt it was a little bit slower, but I couldn't really tell. Probably unrelated to the PR, but it was a matter of less than 5fps. I will try to run a few more tests to compare

**Comment by AniLeo** [comment]
Played until level 3, no driver crashes. 2/3 times I tried to run it it would freeze with an RSX exception at the beginning of the level and force me to stop the emulation.
Nothing relevant on the speed part.

**Pull request merged**
