### PR TITLE
XAudio2 version priority

### PR DESCRIPTION
**Pull request by Nekotekina**
#1973

### CODE REVIEW

**Comment by raven02** [comment]
Probably top-down approach . BTW, is LoadLibraryA case sensitive ?

**Comment by Nekotekina** [comment]
@raven02 I don't think so. What's happening, it can't load 2.9?

**Comment by raven02** [comment]
It cannot find 2.9 (non-windows 10 platform) , then try to load 2.7 .

**Comment by Nekotekina** [comment]
@raven02 It's intentional: 2.7 > 2.9 > 2.8

**Comment by raven02** [comment]
I see. I just tested it 5 times with PPU LLVM , it seems okay and did't trigger any AddData() failed.

**Comment by raven02** [comment]
It is interesting that "Game crash referencing XAudio2_7.dll on Windows 10." happen on PC games as well

https://steamcommunity.com/app/377160/discussions/0/496880503081108055/

**Comment by Nekotekina** [comment]
Is it good now? I used the workaround with FreeLibrary.

**Comment by raven02** [comment]
It looks okay at least not hitting AddData() failed from testing.

**Pull request merged**
