### PR TITLE
rsx: Preserve visibility of scaled blit targets [ 2 of 3]

### PR DESCRIPTION
**Pull request by kd-11**
Companion PR to https://github.com/RPCS3/rpcs3/pull/6774
This PR aims to keep images scaled via blit engine visible to the texture cache lookup routines. This allows mipmaps generated through method 2 detailed in the last PR to be properly gathered.

- Adds a fix to avoid deleting blit engine generated data inadvertently when it shares pages with a framebuffer.

- Tries to improve heurestics with the behavior of RSX if "use GPU texture scaling" is set to off. If scaling or format conversion is being done, just use the GPU. Its much faster and there is little reason to force the CPU fallback in these situations. Moving the data to the GPU side also makes it visible to the texture cache when gathering mipmap levels.

With this fix, some games like The Evil Within show correct visuals when using NVIDIA hardware. Other vendors require some shader workarounds for NVIDIA hardware compatibility which will be made available in part 3.

### CODE REVIEW

**Comment by dyno0** [comment]
The Evil Within w/o force cpu blit emulation is now almost in a playable state. Character textures and some environment textures appear broken when distant (farther they are, more broken they appear). Also there's performance instability in fast character and camera movement, while in static state like just afk-ing, it stays at stable 30fps no matter the clomplexity of the scenery.

Capture
Capture0
Capture1
Capture2


[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3744829/RPCS3.log.gz)

All in all awesome work, really appreciate and admire it.

**Comment by Josivan88** [comment]
errors with 007 games persists as cited in my comment on #6774

**Comment by kd-11** [comment]
Open a proper issue for it.

**Comment by stan0danny** [comment]
texture colors bug is people black and light is weird with Far cry 4 #6718 , my screenshot

Screenshot (15)

Screenshot (18)

**Comment by AniLeo** [comment]
Do not spam this PR with stuff that has nothing to do with it

**Comment by MarioSonic2987** [comment]
Fixes dark image in Saints Row: The Third without CPU blit.

**Before**:
image
**After**:
image

But breaks textures in many places.
image
With CPU blit, it's fine.
image

**Comment by kd-11** [comment]
The texture corruption in both games does not exist in my local experimental branches, which means something went wrong when organizing the code for submission. Relegated to WIP status for now.

**Comment by kd-11** [comment]
I believe the bugs in both games are fixed. Retest.

**Comment by MarioSonic2987** [comment]
It's fixed now.
image

**Comment by dyno0** [comment]
Fixed in The Evil Within too

Capture
Capture1

**Pull request merged**
