### PR TITLE
[TESTERS NEEDED] rsx: Filter MSAA images

### PR DESCRIPTION
**Pull request by kd-11**
Implements linear filtering of MSAA images with upscaling and upto 2x2 downscaling. I tried to keep down the number of texture reads and settled on 6 (for downscaling) as a good balance (full horizontal + half vertical) between performance and visuals.
Most games use MSAA to supersample, then downscale the result linearly to reduce aliasing when rendering below native res. This implementation is largely tuned to work with this in mind, but in theory it should work with any inputs.
Not a true replacement for a hardware filter, but it is good enough at normal viewing distance.

Fixes https://github.com/RPCS3/rpcs3/issues/11676

### CODE REVIEW

**Comment by Satan86** [comment]
GT5's MSAA at 720p is now perfect, at 1080p, not quite, but it's probably good enough. There is an issue though, some cars' headlights look completely black, and Disabling MSAA fixes it. I'm currently having internet issues and thus can't even access the rpcs3 website or Discord to download old builds, so I can't pinpoint the exact build where it broke, although my guess would be #11665. 
RSX capture of the headlight issue: https://drive.google.com/file/d/17RTSPBCAJj4TqxH9QZw_7joS03bxtS-E/view?usp=sharing

**Comment by twophyro** [comment]
Seems like it's fixed in RC: ToD

NPUA80965_screenshot_2022_04_02_11_36_27

Win10 (latest update)
6900xt (22.3.2)

**Comment by kd-11** [comment]
If it needs closer inspection then it is fine. The goal here isn't to match the hardware scaler, its to make our approach less ugly/good enough. Doing sample resolve every time an msaa image changes is terrible for performance and makes MSAA unusable. By the way, the hardware scaler isn't perfect either, it has the same small squares (aliasing sawteeth) because of a non-integer downsample. The ratio in R&C games is about 1.5-1.6:1 which is not going to give a truly smooth output no matter the technique.

**Comment by twophyro** [comment]
Well in that case #11676 is fixed, at least for my setup.

**Comment by kd-11** [comment]
Any measurable performance hit?

**Comment by twophyro** [comment]
Just tested and it appears the this PR boost performance.
Master: ~43fps
PR ~48fps
Only tested R&C: ToD

**Pull request merged**
