### PR TITLE
Make sure to use the best font

### PR DESCRIPTION
**Pull request by hcorion**
Here's some examples of the fruits of my labour:
Crappy Picture 1

Crappy picture 2

### CODE REVIEW

**Comment by B1ackDaemon** [comment]
This definitely needs to be approved
pic

**Comment by rodjun** [comment]
tlou 4k 60fps on this build

**Comment by hcorion** [comment]
Unfortunately, the consensus was not 100% unanimous, so it looks like I'll have to close it.
*sigh* Some people just can't appreciate true art.

**Comment by Megamouse** [comment]
Please reopen. I made a poll and most people liked it

**Pull request closed without merging**
