### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by danilaml** [comment]
Is it a bug in a mingw? Is there a bug report/issue for future reference?

**Comment by Nekotekina** [comment]
@danilaml I don't know, this is strange one

**Comment by Nekotekina** [comment]
Tested Bomberman Ultra with LLVM, should be fixed.

**Comment by aakh1361** [comment]
Bomberman Ultra with LLVM fix  :-)

**Pull request merged**
