### PR TITLE
cell/rsx: Bug Fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Implement frame skipping (config file option only for now)
- WIP: Batch together draw calls using the same geometry with different translation matrices
- Allow multithreaded vertex processing
- Fix some fragment shader instructions
- Implement rsx framebuffer memory persistence
- Fix vulkan layout transitions
- Properly implement FCGT and FCMGT SPU opcodes
- Minor tweaks to SPU wait loops and DMA transfers to improve stalling behaviour

 Major highlights
- Fixes persona 5 and many other games with blue output and 'overbloom'
- Fixes missing characters in Red Dead Redemption
- Fixes most of the missing graphics is Tales of Vesperia
- Fixes flickering graphics when using vulkan in some games

### CODE REVIEW

**Comment by OverlordCW** [comment]
I got this once in RDR with Vulkan:
F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough, buffer_length=268435456 allocated=266515712 requested=1048576 guard=65536 largest_pool=1048576
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:74)

**Comment by Luffykun007** [comment]
AFTER
capturar

Before
capturar1


I'm having this error now and the game is freezing.
capturar2

**Comment by AniLeo** [comment]
This PR fixes the corrupted Skybox in Naruto: Ultimate Ninja Storm.

**Comment by Xcedf** [comment]
Soul Calibur IV menu colors are fixed

**Comment by Xcedf** [comment]
Pure green filter fixed

**Comment by SakataGintokiYT** [comment]
Graphic in game is fixed now but title screen is still broken 
Fotoszok.pl

**Comment by Zangetsu38** [comment]
regression in Wipeout HD for vehicle and menu
https://cdn.discordapp.com/attachments/283643134255038465/332767909430427648/unknown.png

**Comment by twdarkeh** [comment]
Fixes the blue haze in Akiba's Trip, but character textures still broken.

**Comment by raven02** [comment]
Saint Seiya: Sanctuary Battle crashes at title screen with this pull when compared with master .

**Comment by SakataGintokiYT** [comment]
bez tytulu

**Pull request merged**
