### PR TITLE
New UI Design

### PR DESCRIPTION
**Pull request by Megamouse**
The talented @DAGINATSUKO and I created a new default design for RPCS3.
We put a lot of work into this and we hope :thisisfine:

Some of the changes made:
- Updated the hardcoded default stylesheet with @DAGINATSUKO's own stylesheet
- Switched over to QStyledItemDelegates in order to add the possibility to style table items
- Game Icons are not highlighted anymore, only the row they are in (maybe this can be made optional or styleable in the future)
- Made it easier to style the game grid by adding the object name "game_grid"
- Fixed an inaccuracy in the Icon Repaint method that caused a sub pixel painted in the wrong color
- replaced most old icons
- Removed the possibility to repaint the toolbar in the menu as it was redundant and made stylesheets more complex
- You can still colorize the game icon backgrounds if you wish as before
- Fixed the stylesheets' reload behaviour
- Updated old stylesheets (at least all dicrepancies I could find)
- Added the old style as a stylesheet "Classic (Bright)" (apart from the icons and the toolbar mostly the same as before)

image
image
image
image

### CODE REVIEW

**Comment by theoldsport** [comment]
🐬

**Comment by Megamouse** [comment]
The header situation is caused by Qt 5.11. I might add a version check later to fix that section temporarily

**Comment by Megamouse** [comment]
@greentop can you please rebuild with the latest commit and post a picture of the main window / game list ?

**Comment by greentop** [comment]
Ubuntu 16.04
Qt version 5.10.1
Screenshot as of 4ff48fe

screenshot from 2018-07-02 17-32-22

**Comment by Megamouse** [comment]
okay thx. That's what i was hoping to see 👍

**Comment by AniLeo** [comment]
Qt 5.11 for AppVeyor merged and rebase triggered for retesting

**Comment by ruthan** [comment]
IMHO old custom configuration - toothed wheel icon and its placement were better.

**Pull request merged**
