### PR TITLE
Fix vertex data

### PR DESCRIPTION
**Pull request by raven02**
This fixes the fw_dice.ppu.elf

dice_fix

### CODE REVIEW

**Comment by Syphurith** [comment]
`if (0 && ...` that must take you some time to figure out. and the `clear()`. Thanks for your effort.

**Comment by raven02** [comment]
Hopefully more can be fixed :)

**Comment by Syphurith** [comment]
@raven02 I understand that. And i would try find some logs/static analysis report (1day/2) later.

**Comment by Syphurith** [comment]
By using CppCheck it seems no severe problems after these two commits.
I don't know RSX much, and i omitted those `uninitMemberVar`,`unreadVariable`,`clarifyCalculation`.
I do know those are still code fragments and should not expect to build now.
If you please you can read the result XML file from [Here](http://pan.baidu.com/s/1jGGJxf4) with Pass `37qc`.
To read the log, you may have to create a cppcheck project file, use cppcheck gui/cli to open rpcs3 codebase as its root dir, and include at least the folder named `rpcs3` and `Utilities`to create it. Open, then stop the checking and load the result XML.
Also you can just let it finish the check to get a newer result.

BTW i would like to try build it to figure out some more warnings generated by Compiler.

**Comment by Syphurith** [comment]
@raven02 I checked the log when building this patched rsx branch.
Log contains plenty of warnings, such as `C4351` for some elements, unused property as `size`, and many convert int to float or the otherwise. En, I omitted those `data loss` when u64 to u32.. Well all seems ok for me.. but there are a few ones unsure. from `GLProcTable.h` there redirect some GL functions, and some of them use `float` type param instead of int which is used in actual program. If that is you tried to pass what from elfs it may not be a problem. Most of the corresponding code are in `GLBuffers.h`. Similiar, in `GLFragmentProgram.cpp`:259 tried to pass a `int` to `f32`.
I don't know which of those is done intentionally, so i don't use comment to mark those. If you need the log you may build it yourself to see those, and search for `rsx`. Hope these are not real troubles and your work can proceed smoothly.

**Comment by Syphurith** [comment]
Restored? Well. @raven02 BTW There may be memory leak in Graphic Related games now. See [Here](http://www.emunewz.net/forum/showthread.php?tid=168517) or just try it yourself, load a test elf such as `gs_gcm_cube.elf` and run-stop-restart it several times.

**Comment by Syphurith** [comment]
@Hykem I've seen the original `RPCS3/rsx` deleted by accident. Code and project has `<<<<` inside.
I have an easier way for you to restore it totally, and need @raven02 's help.
Today i got a bad IP and can not come to see you on IRC, so long things short.
* `raven02/rsx` was forked from `RPCS3/rsx` you can use this branch.
* Find the commit where `rsx` branch was created from raven02's repo.
* Delete current `rsx` branch again, and create branch there.
* Then let raven02 start a new pull, try to merge his `raven02/rsx` to main `RPCS3/rsx`.
* Merge those greedly.

When a commit is just after another parent, it could be merged. If a branch has the same branch start point (commit) it could be regarded as the same branch. So this trick should work.

**Pull request merged**
