### PR TITLE
gl: Strict export of diff_color and spec_color for mesa compatibility

### PR DESCRIPTION
**Pull request by kd-11**
Another fix for the mix-and-match nature of ps3 shaders causing issues with mesa's linker.
Should fix demon's souls "load profile" crash on linux+mesa

### CODE REVIEW

**Comment by SakataGintokiYT** [comment]
**Ni No Kuni: Wrath of the White Witch / Demo**
```
E {rsx::thread} RSX: Failed to compile vertex shader: 0(21) : error C1038: declaration of "front_diff_color" conflicts with previous declaration at 0(16)
0(22) : error C1038: declaration of "front_spec_color" conflicts with previous declaration at 0(17)

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(21) : error C1038: declaration of "front_diff_color" conflicts with previous declaration at 0(16)
0(22) : error C1038: declaration of "front_spec_color" conflicts with previous declaration at 0(17)
(0) : error C2003: incompatible options for link
'
```
**[Log:](https://gist.github.com/SakataGintokiYT/6a050cf4cd7c517e64388821a0bb8be2)**

**Comment by RainKikyou** [comment]
Eiyuu Densetsu - Sen no Kiseki
```
F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(16) : error C1038: declaration of "front_diff_color" conflicts with previous declaration at 0(14)
(0) : error C2003: incompatible options for link
```

**Comment by kd-11** [comment]
Relaxed the rules a little; front_diff and front_spec are no longer always defined. Please retest.

**Comment by SakataGintokiYT** [comment]
now works okay

**Comment by Behem0th** [comment]
just in case, fixed for me too

**Pull request merged**
