### PR TITLE
Qt: fix register editor and CurrentSelectionIconPath()

### PR DESCRIPTION
**Pull request by Megamouse**

### CODE REVIEW

**Comment by Nekotekina** [comment]
Why is this bunch of small unrelated changes? And not of them are necessary

**Comment by Megamouse** [comment]
why. some of the types were wrong to begin with and some other things just created annoying warnings

**Comment by Nekotekina** [comment]
Silencing truncation with static_cast usually doesn't bring correctness, especially for size. It indicates some problem which requires "expert" attention.

**Comment by Megamouse** [comment]
true. but i can't see how any of these values would ever exceed the integer limits

**Pull request merged**
