### PR TITLE
Make MSL Fast Math and software vkSemaphore optional

### LINKED ISSUE #11414: [Meta] MacOS vulkan issues
MacOS will have problems unrelated to the core application, largely due to the fact that vulkan is not natively supported on macOS. Let's track any major problems in one place to avoid creating too many tickets that may end up sitting unresolved for a long time.

Known Issues
- [x] Swizzle workarounds for old moltenvk versions cause visual bugs in titles with new moltenvk. See [#11363](https://github.com/RPCS3/rpcs3/issues/11363)
- [x] Flickering visuals in Rachet & Clank titles.
- [ ] Flickering visuals in Goldeneye 007
- [ ] Missing text in Disgaea D2
- [ ] Flickering text in GT HD

Comment with issue information and a moderator will triage and add to the TODO list above.

### PR DESCRIPTION
**Pull request by nastys**
Makes MSL Fast Math optional. Disabling it fixes various artefacts in games such as Ratchet & Clank and Yakuza Ishin on Apple GPUs. Likely fixes #11414, at least in part. __Make sure it's disabled in your custom game config after upgrading.__
EDIT: MSL Fast Math is now enabled by default, as it's much faster in some games. Only disable it for games with artefacts.
Does not fix GoldenEye 007 Reloaded nor R&C Nexus.
vkSemaphore emulation has been simplified into a single checkbox and moved from Debug to Advanced.
MoltenVK has been updated to the latest commit, which fixes an issue with push constants that prevented us from using the latest version without incurring significant bugs.
SPIRV-Cross has been downgraded to prevent ``VK_ERROR_INVALID_SHADER_NV`` in Little Big Planet, GoldenEye 007 Reloaded, and other games.
``MVK_CONFIG_RESUME_LOST_DEVICE`` is now enabled at runtime rather than compile time.

### CODE REVIEW

**Comment by rcaridade145** [comment]
@nastys  It would be nice if we could get the "wrong" shaders where fast-math is used, to try and help here https://github.com/KhronosGroup/Vulkan-Portability/issues/32

**Comment by reece394** [comment]
Goldeneye 007 Reloaded with Molten-VK 1.1.8 and this PR still exhibits flickering. Current PR version of Molten-VK produces  
`F {RSX Worker 7} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 10} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 6} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 4} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 9} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 5} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 3} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 1} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 2} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)
F {RSX Worker 8} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Invalid shader code (VK_ERROR_INVALID_SHADER_NV)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp:66[:95], in function int_compile_graphics_pipe)
(in file /private/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107[:4], in function die_with_error)`

**Comment by MSuih** [comment]
@reece394 instead of just posting one lone from log, upload the whole log file. It should be in `Library/Caches/rpcs3` in your home directory

**Comment by reece394** [comment]
> @reece394 instead of just posting one lone from log, upload the whole log file. It should be in `Library/Caches/rpcs3` in your home directory

Done

**Pull request merged**
