### PR TITLE
Trying to improve SPU LLVM experience

### PR DESCRIPTION
**Pull request by Nekotekina**
How to test: remove SPU cache and start game clear with SPU LLVM.

### CODE REVIEW

**Comment by Nerboruto** [comment]
build tested on amd apu quad core fm2 ..
worse compilation time and spu performance.
bad for me... maybe because they are not 4 real cores

**Comment by RainbowCookie32** [comment]
Beyond Two Souls' performance from boot to the menu is way better now while compiling SPU cache. From an average of 5-6fps to 15-16. I'll continue testing and updating this comment

**Comment by arcadee1977** [comment]
I tested Sonic Unleashed.  SPU llvm caching no longer stutter at first time, but FPS dropped significantly (about >5fps drops)

**Comment by MsDarkLow** [comment]
8700K
In the yakuza games there is a great improvement in terms of stuttering. The pre-rendered intro no longer has stuttering and the gameplay is now more fluid.

**Comment by fifazalata** [comment]
Tried NieR and some other games.
The performance is worse than previous builds
that's with i7 2600k

**Comment by Augusto7743** [comment]
Huge drop in performance in recent versions.

AMD FX 6300 - 4 GB - GT 640 1 GB - Windows 10 64
Default settings in RPCS3.
Using some versions before august 2019 and current version

Motorstorm Pacific Rift 15 FPS > Now 5 or 7 FPS
Hokuto no Ken Ken´s Rage 2 30 FPS > Now 5 FPS
Spider-man Shatered Dimensions > 30 FPS > Now 7 FPS

Tekken 6 between 50 at 60 FPS

**Comment by dio-gh** [comment]
> Huge drop in performance in recent versions.

Maybe I'm misunderstanding what you mean by "recent versions", but if you are not sure the performance was regressed by this PR, don't report it here. Try nailing down where the performance actually regressed for you and open a separate ticket.

**Comment by purifiedh2o** [comment]
> > Huge drop in performance in recent versions.
> 
> Maybe I'm misunderstanding what you mean by "recent versions", but if you are not sure the performance was regressed by this PR, don't report it here. Try nailing down where the performance actually regressed for you and open a separate ticket.

He used default settings, and compared older builds to this build. Try reading again.

**Comment by Leopard1907** [comment]
Purified, you should read again.

> Using some versions before august 2019 and current version

Bruh , that is long time frame. He should find the actual regression cause first.

Lemme compare random 2018 build vs now then.

**Comment by purifiedh2o** [comment]
> He should find the actual regression cause first.]

Well other users reported the same, so I think he got a point. Gonna try on my PC later.

**Comment by purifiedh2o** [comment]
> He should find the actual regression cause first.

Well other users reported the same, so I think he got a point. Long time frame, eh there is a regression that prevents some games run smoothly. Example https://github.com/RPCS3/rpcs3/issues/6536.
Btw I'm gonna try this PR on my PC later.

Update: after a quick test of Persona 5 on my laptop, I found that during normal battle, I get like 17-22 FPS (22 is when you do a melee attack) in this while older builds (even the build mentioned in that issue), I got 23-27FPS (still a laptop). That's "long time frame" for you. Yes I know 1 game is not enough, but others also reported the same so... *shrug*.

**Comment by purifiedh2o** [comment]
> He should find the actual regression cause first.

Well other users reported the same, so I think he got a point. Long time frame, eh there is a regression that prevents some games run smoothly. Example https://github.com/RPCS3/rpcs3/issues/6536.

After a quick test of Persona 5 on my laptop, I found that during normal battle, I get like 17-22 FPS (22 is when you do a melee attack) in this while older builds (even the build mentioned in that issue), I got 23-27FPS (still a laptop). That's "long time frame" for you. Yes I know 1 game is not enough, but others also reported the same so... *shrug*.

**Comment by HerrHulaHoop** [comment]
It is a long time frame. Test 0.0.7-9123 and 0.0.7-9124. If you see a performance decrease, mention it here. Otherwise, find the correct PR that decreased performance and report it there. In any case, opening a separate GitHub issue is the proper way forward. No need to post any more messages in this thread.

**Comment by proganime1200** [comment]
boost tekken 6 from 45fps to 60fps on some maps using am a8 7650k gt 730 clock at 4ghz

**Comment by Augusto7743** [comment]
The huge drop in performance in some games is recent versions. Recent versions I say more or less 10 previous versions. Versions from August-2019 run fine.
The regrssion in peformance is before of 0.0.7-9123 and 0.0.7-9124.
About
"boost tekken 6 from 45fps to 60fps on some maps using am a8 7650k gt 730 clock at 4ghz"
Is the same speed if using an FX-6300 and GT 640.
Another detail is that some games has a huge slowdown in music tempo being in some games run 60 FPS and music tempo how if is 3 FPS or running in 5 FPS and music tempo 3 FPS even not enabling low spu thread and spu loop detection.
In games running with performance regression the log window is all time creating lines about each SPU and RSX new task being an detail that not had before being also an recent detail.
Games having a huge performance regression not has all SPU code being emulated and perhaps the problem is because SPU LLVM is trying find how emulate SPU code (red lines in log window) thus using very much CPU resulting in low performance.
Have games running more fast in recent versions and results are green lines in log window.
When in log window has several red lines the game has music tempo very slow or low FPS.
I had posted here because look how being related to changes in SPU LLVM.
Using ASMJIT also has huge drop in performance.

I need to say an HUGE THANKS for changes in how is allocated Vulkan memory compiler in NVidia GPUs that is now 300 MB. Before was 1 GB.
Thanks very much :)

**Comment by jobs-git** [comment]
If you are not sure that this PR caused that regression, dont report it here, file a separate report discussing the details, identify the PR that caused it and then attach logs.

**Pull request merged**
