### PR TITLE
Trivial fixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by bobthecooldad** [comment]
Simpsons Game gone from Intro to Nothing with PR
PPU fast/LLVM:
S LDR: Boot from gamelist per doubleclick: done
U {PPU[0x1000000] Thread (main_thread) [0x00b16088]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x1000000] Thread (main_thread) [0x00c346a0]} sys_rsx TODO: sys_rsx_device_map(addr=*0xd0004830, a2=*0xd0004828, dev_id=0x8)
U {PPU[0x1000000] Thread (main_thread) [0x00c34888]} sys_rsx TODO: sys_rsx_memory_allocate(mem_handle=*0xd00047e0, mem_addr=*0xd00047e8, size=0xea00000, flags=0x80000, a5=0x300000, a6=0xf, a7=0x8)
U {PPU[0x1000000] Thread (main_thread) [0x00c34848]} sys_rsx TODO: sys_rsx_context_allocate(context_id=*0xd00047e4, lpar_dma_control=*0xd00047f0, lpar_driver_info=*0xd00047f8, lpar_reports=*0xd0004800, mem_ctx=0x0, system_mode=0x200)
U {PPU[0x1000000] Thread (main_thread) [0x00c3495c]} sys_rsx TODO: sys_rsx_context_free(context_id=0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00c34968]} sys_rsx TODO: sys_rsx_memory_free(mem_handle=0x0)
F {PPU[0x1000000] Thread (main_thread) [0x00c389b0]} MEM: Access violation reading location 0xe66000

**Comment by AniLeo** [comment]
sys_rsx? Are you on the right build?..

**Comment by bobthecooldad** [comment]
Yeah going back through the builds

**Comment by AniLeo** [comment]
Confirmed it's not caused by this PR

**Pull request merged**
