### PR TITLE
Fixups

### PR DESCRIPTION
**Pull request by kd-11**
- Remove an AMD workaround that is no longer needed with newer drivers (since 19.4.3)
- Fix texture cache search for flip source (should restore performance in some cases)
- Fix confirmed_range calculation for hw blit transfers (sw memory write barrier for flushing)
- Fix out-of-bounds transfers due to no bounds check when testing local resources for overlap.
- Fix clear failure due to null stencil mask triggering an assert.

Fixes https://github.com/RPCS3/rpcs3/issues/5869, https://github.com/RPCS3/rpcs3/issues/5854, https://github.com/RPCS3/rpcs3/issues/5824, https://github.com/RPCS3/rpcs3/issues/5898

### CODE REVIEW

**Comment by nihanthkandimalla** [comment]
Same issues persists in Ni No Kuni as before.

**Comment by Parthorisian** [comment]
For [BLUS3043] Physics interaction speed has been slowed down [master_build8035](https://streamable.com/n7wz2) (recorded results for same place- top of Latria tower, one of piles with 5-6 vases - World-3-2) [PR_build](https://streamable.com/za44t) PS Thanks for improving shader compilation speed

**Comment by kd-11** [comment]
Pretty sure that is unrelated, unless DeS started failing to find flip image in the cache which is unlikely. You have to completely replace rpcs3 (including renaming the executable to rpcs3.exe) when testing for performance regressions sometimes. Could also be because this PR is not rebased on latest master.

**Comment by kd-11** [comment]
Actually looks like something is wrong with DeS, not sure when it started though. Number of RSX readbacks has gone up considerably.

**Comment by Parthorisian** [comment]
OK, thanks for explanation, ive cleaned all available caches and tested b8021. It seems speed of physic interactions was fixed by latest master(b8033)

**Comment by uaqlover** [comment]
RPCS3 v0.0.6-f3967d72 Alpha | fbo_fixes

fixes 

FPS_ 30 09 _ OpenGL _ 0 0 6-f3967d72-fbo_fixes _ NASCAR® Unleashed  BLUS30806  29_04_2019 1_36_07 PM

still same 

FPS_ 59 99 _ Vulkan _ 0 0 6-f3967d72-fbo_fixes _ F1 Race Stars™  NPEB01124  29_04_2019 1_35_15 PM

FPS_ 23 31 _ Vulkan _ 0 0 6-f3967d72-fbo_fixes _ Motorcycle Club Demo  NPUB91024  29_04_2019 1_33_47 PM

**Pull request merged**
