### PR TITLE
My fixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by blottto** [comment]
@Nekotekina 
Now TSX works in haswell with very good improvements in performance :)

Thank you. when can tsx be activated on the degub tab in the main branch?

**Comment by Fiodorwellfme** [comment]
@blottto Could you share your build with me on the discord please ?

**Comment by blottto** [comment]
@Fiodorwellfme 
At this moment I can not upload it to discord

but here is in MF http://www.mediafire.com/file/ej0iz24s1o0h35q/Rpcs3TSX.rar/file

**Comment by Fiodorwellfme** [comment]
@Nekotekina Your build solves the problem in some games but it still freezes at the first loading screen in Persona 5

**Comment by frymezim** [comment]
I don't know which build it started to fail but whenever I play Ni no Kuni on my Intel i7 4770hq I get
```
S {rsx::thread} RSX: New program compiled successfully x5
E {PPU[0x1000000] Thread (main_thread) [0x0003554c]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [3]
```
The loading animation logo would stop from loading and the game hangs.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2070189/RPCS3.log.gz)

**Comment by Tyralyon** [comment]
@frymezim It's a confirmed regression, see https://github.com/RPCS3/rpcs3/issues/4589

**Comment by Asinin3** [comment]
_Posting on behalf of Whymsical_

I'm experiencing a new crash with SPU LLVM and Drakengard 3. SPU LLVM does work rather well on the master builds, but with this Pull Request it crashes randomly when trying to go ingame, it does seem to progress further on each subsequent launch of the game (cache related?) but on master it can go ingame every time.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2071319/RPCS3.log.gz)

**Comment by stevphie** [comment]
@Asinin3 try to put spu threads to 1 other than auto or 2 ... me also experienced the same

**Comment by whymsical** [comment]
@stevphie  I'm the individual that reported that and SPU threads were already set to 1 and I tried with auto. 
Upon first boot, it would memory access violation at the logos screen
Second boot MAV at the Title screen
Third Boot MAV after loading save game
Fourth Boot MAV after leaving my house (start of the first chapter after the opening. first time you get to save)
And you see the pattern at this point.

**Comment by whymsical** [comment]
Update to this. 

I am now getting a consistent crash. Everytime i try to open this box. It crashes
image

Unfortunately i am able to get a log from this type of crash.

**Comment by 13xforever** [comment]
To reproduce start Chapter 1: Verse 1. Part 1, break first crates on your path on the right side, after the cutscenes.
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/2073755/rpcs3.zip)

**Comment by Kravickas** [comment]
`E {PPU[0x1000000] Thread (main_thread)} SPU: [0x030d8] SPU Analyser failed, 65 vs 66`
still in NPEB01321

**Comment by incognitoh** [comment]
Haswell TSX works in some games but is still broken. For one example, with TSX enabled, Virtua Tennis 4 always locks up with "SPU: GETLLAR took too long" error, no matter what SPU setting I use. With TSX disabled with the same build, the game works perfect.

With the older Haswell TSX enabled builds from a few weeks ago, the game also worked fine without issue.

**Pull request merged**
