### PR TITLE
added try/catch and error message to lockless::push

### PR DESCRIPTION
**Pull request by p01arst0rm**
Added a try/catch block and error message to lockless::push to log possible
bad allocation due to noexcept

### CODE REVIEW

**Comment by Nekotekina** [comment]
Hmm. Did you have bad allocation in this function?

**Comment by MSuih** [comment]
We are compiling rpcs3 with -fno-exceptios or similar flags, which is why the CI builds are failing.

**Comment by p01arst0rm** [comment]
> Hmm. Did you have bad allocation in this function?

there would be no way of knowing, as any possible error wouldn't be logged; 
the program would just crash

**Comment by p01arst0rm** [comment]
> We are compiling rpcs3 with -fno-exceptios or similar flags, which is why the CI builds are failing.

Is there a rule against try-catches? i didnt see one in the style guide :/

**Comment by Nekotekina** [comment]
I think MSVC should be configured to return nullptr instead of bad alloc, this way we will get more informative error message coming from null dereference.

**Comment by Megamouse** [comment]
Another thing to mention is that we put the { on a new line.
So this (or anything similar):
```
try {
    // code goes here
} catch(...) {
    // code goes here
}
```
should look like this
```
try
{
    // code goes here
}
catch(...)
{
    // code goes here
}
```

**Comment by Nekotekina** [comment]
Not going to work anyway. There are different methods to debug it, terminate may be the best action in cause of memory leak or low system memory.

**Pull request closed without merging**
