### PR TITLE
rsx: CPU blit refactor and support RSX tiled addressing

### PR DESCRIPTION
**Pull request by kd-11**
- De-spaghettify nv3089::image_in and refactor into readable units.
- Add support for RSX tiled addressing in the CPU blit path.

Closes https://github.com/RPCS3/rpcs3/issues/6688

### CODE REVIEW

**Comment by kd-11** [comment]
Gets retro/grade back to a playable state, with the caveat that I need to use CPU blit. GPU blit is not possible right now due to an architectural problem with the emulator.

image
image

**Comment by Ordinary205** [comment]
This PR causes the regression twice on NFS The Run when enabling WCB+RCB+Tiled memory and CPU Blit Emulation.
Regression
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13762595/RPCS3.log.gz)

**Comment by legend800** [comment]
No change in Split Second from the issues noted here: https://github.com/RPCS3/rpcs3/issues/14682#issuecomment-1737749570

PR build:
2023-12-24 10_58_24-FPS_ 29 99 _ Vulkan _ 0 0 29-3be2d623 Alpha _ maint0 _ Split_Second  NPUB30450

Native res=missing effects/smoke
Higher res=effects render but large pixels everywhere

**Comment by Darkhost1999** [comment]
> Regression


How do I make my screen look like yours? Is this in the menus? In the game? Cause when trying to go ingame I get as far as pressing the first buttons and I don't see this at all.

**Comment by kd-11** [comment]
> This PR causes the regression twice on NFS The Run when enabling WCB+RCB+Tiled memory and CPU Blit Emulation. Regression [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13762595/RPCS3.log.gz)

That looks right to me w.r.t other frostbite games. CPU blit simply did not support tiled addressing, so if it was working before it means something else is broken elsewhere. Makes sense though since Rivals also had the same behavior. Some other component in the pipeline is broken and only appears when RSX tiled addressing is enabled.

**Comment by Triticum0** [comment]
@kd-11 Tested Mercury Hg Improved a lot you can now finish a level but still not perfect
Pr
NPUB30419_screenshot_2023_12_25_00_10_25
[Pr.log.gz](https://github.com/RPCS3/rpcs3/files/13763124/Pr.log.gz)

Masters
NPUB30419_screenshot_2023_12_25_00_07_19

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13763129/RPCS3.log.gz)

**Comment by Triticum0** [comment]
Chronicles of Riddick: Assault on Dark Athena crashes in the menus using Forced CPU blit so can't be tested

here the log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13763272/RPCS3.log)

**Pull request merged**
