### PR TITLE
[BUILD] Fix SDL2 version check.

### PR DESCRIPTION
**Pull request by p01arst0rm**
fixes https://github.com/RPCS3/rpcs3/issues/10597

### CODE REVIEW

**Comment by hcorion** [comment]
@Shoegzer can you test this PR, just to make sure FAudio doesn't get built and the warning shows up fine?

**Comment by Shoegzer** [comment]
@p01arst0rm Thanks for this PR.
@hcorion Tested - CMake succeeds without `-DUSE_FAUDIO=OFF` and FAudio doesn't build.  To be clear, it hasn't built for me since before #10397 was merged, I just hadn't noticed it's absence since I tend to use OpenAL (and the tooltip doesn't mention FAudio or any benefits it may have to linux users anyway).

Also, the warning does show up, though the formatting might be improved to remove spacing etc. due to the way CMake warnings are thrown.  Here's how it looks:
```
CMake Warning at 3rdparty/CMakeLists.txt:228 (message):
  -- RPCS3: FAudio requires SDL 2.0.9 or newer.


CMake Warning at 3rdparty/CMakeLists.txt:229 (message):
            since a valid SDL2 version cannot be found


CMake Warning at 3rdparty/CMakeLists.txt:230 (message):
            FAudio building will be skipped.
```
I also think this message could still confuse people with SDL2 versions that actually do meet the 2.0.9 minimum.  That's what I was trying to avoid in the language with my PR at least.

**Comment by p01arst0rm** [comment]
improved the warning message :)

**Comment by Shoegzer** [comment]
LGTM!

**Comment by p01arst0rm** [comment]
fixed the grammar :p

**Review by hcorion — APPROVED** [review]

**Pull request merged**
