### PR TITLE
 Fix experimental build warning

### PR DESCRIPTION
**Pull request by scribam**
Hotfix for #3596

### CODE REVIEW

**Comment by Nekotekina** [comment]
Wtf, appveyor build uses cmake, not vcxproj files

**Comment by scribam** [comment]
Not anymore

**Comment by Nekotekina** [comment]
Questionable move. Switching to CMake would be more universal.

**Comment by scribam** [comment]
I totally agree about the fact CMake is more universal. But we still have a Visual Studio solution in the project and no way to test it by using the previous appveyor behavior

**Comment by Joao3233** [comment]
configuracao
shadow 2
shadow
Hello good afternoon. I apologize for talking about a different matter, but here was the only place I found to talk to you. Ico and Shadow of Colossus made progress. I've been following this game, and I saw that now it seems to be emulated graphically correct. I will find out that your problems are in enlightenment. For before in September it was sort of separated in 2 screens (sorry for the explanation) that each one appeared a part of the game, one had lighting and had very bad graphics, another had not and was perfect. The point is that the problem of the game is enlightenment. The game can be played, as I killed 2 colossus, did not kill masi because it did not work where the third was, because without lighting does not give to see where they are. help, I hope that speaking of the problems will help you.

**Comment by AniLeo** [comment]
Unrelated to this pull request, use the forums @ https://forums.rpcs3.net

**Comment by P1llus** [comment]
This PR ended up messing with the compilation on Visual Studio. Confirmed by @scribam .

Would recommend on holding off upgrading until it is resolved.

**Pull request merged**
