### PR TITLE
Fixups

### PR DESCRIPTION
**Pull request by kd-11**
- Fix potential deadlock introduced by https://github.com/RPCS3/rpcs3/pull/5024
- Also fixes https://github.com/RPCS3/rpcs3/issues/5028

### CODE REVIEW

**Comment by kvark** [comment]
@kd-11 why would spinning on the fence solve your deadlock? This change looks super hacky to me, it might be just hiding the actual cause of the problem.

**Comment by kd-11** [comment]
You misunderstand, I was spinning on the wrong fence before. The function takes an optional external fence argument.

**Comment by kd-11** [comment]
Check the changes in the submit function. pending is never true if an external fence is issued.

**Comment by kvark** [comment]
Ok, the pending flag is good. But why removing the use of `vkWaitForFences`?

**Comment by MSuih** [comment]
>// NOTE: vkWaitForFences is slower than polling fence status at least on NV
My guess is that the change brings a slight performance improvement.

**Comment by kvark** [comment]
@MSuih I find this weird. Waiting on a fence should never be your performance bottleneck.

**Comment by kd-11** [comment]
It is measurably slower when called on demand. This happens due to an avoidable situation on page faults (think of PS3 as effectively unified memory, and the CPU can suddenly require something that only exists on the GPU).

**Comment by dgrace13** [comment]
Thanks @kd-11 for all you do! Any chance you could put deadstorm pirates, Razing storm and HOTD4 on the radar in the future? If not, no worries. Thx again!

**Pull request merged**
