### PR TITLE
First cuda renderer implementation

### PR DESCRIPTION
**Pull request by Megamouse**
Based on OpenGl.
Seems to be a bit faster

### CODE REVIEW

**Review by kd-11 — APPROVED** [review]
Amazing stuff

**Comment by Hasster1** [comment]
Just tested it out with a few games.
i5-4210U, GeForce 840m, 12gb ram.
Haze (BLUS30094)
While standing at the first checkpoint on the start of a game:
OpenGL - 14-15 fps
Vulkan - 17-19 (More around 18)
Cuda - 18-19 (More around 18.5)

Serious Sam 3: BFE (NPUB31165)
At the start of Summer in Cairo:
OpenGl - 14-15 fps
Cuda - 18-20 fps
Vulkan - 28-30 fps

Cuda is definitely faster than OpenGl, that's for sure, and it could even surpass Vulkan in some minor cases (Needs further testing).
I thought of testing demon's souls, but the fps counter is really broken on opengl/cuda, and InFamous is crashing on opengl (But it wasn't before (i think), so i need to find the build on which it stopped working and report the regression)
Otherwise, it's a wonderful thing.

**Review by clienthax — APPROVED** [review]

**Comment by Megamouse** [comment]
Hmm it has some issues still.

**Comment by kd-11** [comment]
Nooooo I got a huge performance bump on my AMD RX480!

**Pull request closed without merging**
