### PR TITLE
rsx: Fixups

### PR DESCRIPTION
**Pull request by kd-11**
- Invert pixel offsets when going for GPU bit. All values are relatively inverted for reverse copying. Reverse them before attempting HW-accelerated transfer.

### CODE REVIEW

**Comment by Emulator-Team-2** [comment]
This pull request regressed these games:
<details> 
<summary>Generator Rex: Agent of Providence</summary>
Vulkan:


OpenGL:


</details>

[RDC Capture-Vulkan](https://drive.google.com/file/d/1aOolQGDicbvY6gx-SbA7dF500Flk8kR0/view?usp=sharing)
[RDC Capture-OpenGL](https://drive.google.com/file/d/1FLrATBz7tEIPwSHStDJeYQ6DnPsDxjQq/view?usp=sharing)

<details> 
<summary>Genji: Days of the Blade</summary>

Vulkan:

OpenGL:


</details>

[RDC Capture-Vulkan](https://drive.google.com/file/d/1Vic_ivzo2miBWaE9q6etIaLPnUA9nxXU/view?usp=sharing)
[RDC Capture-OpenGL](https://drive.google.com/file/d/1KIvi02EN0HGP1FkbzVctT3m4ggv_8cpo/view?usp=sharing)

-----------------------------------------------------------------------------------------------------------

Monster Jam: Path of Destruction:

Vulkan:
`F {RSX [0x0018244]} RSX: class std::runtime_error thrown: Assertion failed: !region.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexturecache.h:963)`
OpenGL:
`F {RSX [0x003e69c]} RSX: class std::runtime_error thrown: Assertion failed: !cached.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:863)`
[RPCS3-Vulkan.zip](https://github.com/RPCS3/rpcs3/files/3064459/RPCS3-Vulkan.zip)
[RPCS3-OpenGL.zip](https://github.com/RPCS3/rpcs3/files/3064460/RPCS3-OpenGL.zip)

**Comment by kd-11** [comment]
@Emulator-Team-2 Retest.

**Comment by Emulator-Team-2** [comment]
@kd-11 
Latest build fixes regression in these games.
<details> 
<summary>Generator Rex: Agent of Providence</summary>

Vulkan:

OpenGL:


</details>

<details> 
<summary>Genji: Days of the Blade</summary>

Vulkan:

OpenGL:


</details>

<details> 
<summary>Monster Jam: Path of Destruction:</summary>

Vulkan:

OpenGL:


</details>

**Comment by Hinotoumei** [comment]
nbot even 5 minutes into the game and all in game text vanishes leaving you unable to even know what the heck is going on. resetting the game causes you to lose progress despite reaching multiple checkpoints..

NO issues
Works with default settings
playable??

REALLY???

**Pull request merged**
