### PR TITLE
sys_net: Add error_code

### PR DESCRIPTION
**Pull request by elad335**

### CODE REVIEW

**Comment by Nekotekina** [comment]
I don't like the idea of negating enum constant values. Can possibly overload operator- for it:
```Cpp
constexpr sys_net_error operator-(sys_net_error v)
{
  return sys_net_error{-v};
}
```

**Comment by elad335** [comment]
Done.

**Comment by D87-byte** [comment]
sword art online lost song i 5 6400  GeForce GTX 750 Ti
F {RSX [0x004fc08]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2310)

**Comment by AniLeo** [comment]
Do not false flag regressions on unrelated PRs

**Pull request merged**
