### PR TITLE
Add option for preventing display sleep

### PR DESCRIPTION
**Pull request by al3xtjames**
Implements #5777 for Windows, Linux, and macOS. Preventing the display from sleeping was already partially implemented for Windows; the pad handlers would call `SetThreadExecutionState` whenever input was received. However, this requires constant input to prevent the display from sleeping, which doesn't work for longer cutscenes/etc.

On Linux, this uses the `[Un]Inhibit` methods provided by the `org.freedesktop.ScreenSaver` D-Bus service.

### CODE REVIEW

**Comment by RainbowCookie32** [comment]
Just tested on Windows and it seems to be working as expected, display doesn't enter sleep when the game is running

**Comment by vsub** [comment]
Yes it works but can you make the option global not per game and not visible in the per game settings.

**Comment by elad335** [comment]
All settings are currently have global config and per game config by design, so not atm.

**Comment by vsub** [comment]
View Point Settings are global only
https://github.com/RPCS3/rpcs3/pull/5678

**Comment by al3xtjames** [comment]
Making this global only would make sense, but I'm not sure this belongs in viewport settings. Any recommendations/suggestions?

**Comment by vsub** [comment]
I am not sure how hiding settings works(viewport only visible in global settings),but where is is now it is the perfect place....it is a Program(Emulator) Option to prevent sleep

**Comment by al3xtjames** [comment]
Added Linux support (using D-Bus) with the latest patch.

**Comment by al3xtjames** [comment]
Just remembered that QtDBus is a thing, will redo the Linux implementation with it (instead of directly using libdbus).

**Comment by vsub** [comment]
It's nice that there is a progress on this but is there is any reason why did is still not added to master?

**Comment by dio-gh** [comment]
Agreed, any blockers for this PR?

**Comment by kd-11** [comment]
QtDBus?

**Comment by al3xtjames** [comment]
Yeah, I need to finish the QtDBus implementation for Linux (...sorry for taking so long)

**Comment by Megamouse** [comment]
Needs a rebase.
The SetThreadExecutionState was moved from the individual handlers to PadHandler.cpp

**Comment by al3xtjames** [comment]
Should be ready for merging now.

**Pull request merged**
