### PR TITLE
gui/window render: Disable read QT DPI value.

### PR DESCRIPTION
**Pull request by Zangetsu38**
- Fix issue https://github.com/RPCS3/rpcs3/issues/5455
- Fix proportion and resolution for show real and no faked/zoomed x2 if you using 200 %  windows scaloing, so can re use 2K for 2k monitor and 4K in 4K monitor.
- Fix all out of box caused by zoomed any dialog depending Windows scaling set.

Now like User have tested with other, this things is usseles and continue broken all time proportion/resolution for all inside rpcs3.

### CODE REVIEW

**Comment by Megamouse** [comment]
Nope

**Comment by ruipin** [comment]
It's not useless, AND depending on Qt version it causes a ton of issues.

**Comment by Megamouse** [comment]
And zangetsu still doesn't understand the difference between actual resolution and screen coordinates

**Comment by Megamouse** [comment]
Closing since this was discussed a billion times and it's simply not correct.
I can provide a "proper" fix later.

**Comment by Zangetsu38** [comment]
I have tested and confirmed by assinine, read dpi value is really usseless and broken all résolution for Windows scaling user, assinine have try on my computer with master set window game  2560x1440 and rpcs3 have juste said NOP you have 1080p résolution available on tour computer 🙃. 
So sorry again but i have right, And i have obligatory right, read dpi scaling  is obligatory sur and obligatory broken all on résolution ans proportion, likebuser get pas dialog out of screen.
And sorry but proper fix ? Have only one fix possible said to kd disable read dpi value.
Only one solution is that.

**Comment by Zangetsu38** [comment]
And for QT version, user get obligatory archive with last qt version dll so yesbsorry is obselet here

**Comment by Asinin3** [comment]
"confirmed by Asinine,  read dpi value is really useless and broken all resolution" You missed my point then, please don't throw me under the bus with you while I'm asleep. Yes, Qt fixed the underlying issue with its DLL's but everything we said on Discord for 5+ hours about how RPCS3 was broken before was correct. It's just that now it looks like Qt fixed the issue so the fix isn't as necessary when it comes to the GS Frame at least. There's no need to keep bringing the discussion to GitHub while we're in the middle of discussing it elsewhere. At this point the comments here should be locked.

**Comment by Zangetsu38** [comment]
I just answered Mega and rui, that all.

**Comment by Megamouse** [comment]
Try this: https://github.com/RPCS3/rpcs3/pull/6110
Use --hidpi 0

**Pull request closed without merging**
