### PR TITLE
Correct some wrong FS errors

### PR DESCRIPTION
**Pull request by JayC-03**
Detailed issue report: https://github.com/RPCS3/rpcs3/issues/3327

Fixes some games which try to access a non-existing file,
and hang caused by CELL_ENOTMOUNTED being returned wrongly.

Uncharted 2 and TLOU demos get further now.

### CODE REVIEW

**Comment by JayC-03** [comment]
Anyone testing, use second commit's build, accidentally submitted the wrong change the first time. :/

**Comment by Asinin3** [comment]
Well no changes with Infamous 1/2, Uncharted 1/2, R&C Tools of destruction and Killzone 3

**Comment by Nobbs66** [comment]
Why was this closed? The behavior should be correct here.

**Comment by AniLeo** [comment]
From Discord: it's not a proper fix

jjsat could have opened a PR himself if he found appropriate. Keep weird hacks away from PRs

**Pull request closed without merging**
