### PR TITLE
Ingame Native User Selection

### LINKED ISSUE #8472: [Feature Request] in-game user selection
## Details

A user selection dialog to select a user account for the current loaded game.

#### what part of RPCS3 would be affected by the feature:
* Gameplay

#### Why this feature is important to RPCS3.

Games like Scott Pilgrin,the LBP trilogy, and others in offline multiplayer requires the 2nd 3rd or 4th player to select a User to use so that it can load the desired characters levels, but, currently, no user dialog is shown in RPCS3, instead it loads a lvl 0 for all characters, apparently it loads a guest user account automatically.

Therefore, all players except player 1, can't save its progress along the gameplay.

#### screenshots:

in the PS3, the user selection dialog is shown as follow

image

#### logs:
tested in SCOTT PILGRIM VS. THE WORLD: THE GAME [NPUB30162]

**full log file**
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/6350912/RPCS3.log.zip)

**log overview**

If I:
1. start the game
2. go to the "story mode" -> select any difficulty
3. in the 2nd player controller, i press X then click in "Select profile"
i get the following log info:
```
U cellUserInfo TODO: cellUserInfoSelectUser_SetList(setList=*0x216b1060, funcSelect=*0x10fffc8, container=0xffffffff, userdata=*0x216b0fe0)
U cellUserInfo TODO: cellUserInfoGetList(listNum=*0x216b10b4, listBuf=*0x216b1074, currentUserId=*0x216b1050)
E cellSaveData: cellSaveDataUserAutoLoad(version=0, userId=0, dirName=“NPUB30162”, errDialog=0, setBuf=*0x25f392d8, funcStat=*0x11045f8, funcFile=*0x1104690, container=0xffffffff, userdata=*0x25f39198)
E SYS: 'sys_ppu_thread_get_priority' failed with 0x80010005 : CELL_ESRCH [3]
```

#### system configuration:
* OS:Linux (5.9.16-1-MANJARO, Xfce 4.16)
* RPCS3 Version: 0.0.15-12138-efd38fa9 Alpha

### PR DESCRIPTION
**Pull request by Megamouse**
- Implement most of cellUserInfo

fixes #8472

### CODE REVIEW

**Comment by Megamouse** [comment]
I reworked the dialog to run asynchronously, as suggested by the callbacks.

I guess it's ready for review and testing now.

**Comment by Megamouse** [comment]
Wait. I'll add some handling for Qt (I won't implement it though)

**Comment by Megamouse** [comment]
OK. It won't get any better now, unless someone has a better idea for the default avatars

**Comment by dio-gh** [comment]
Could you like show a screenshot? I don't really have a game at hand to test it

**Comment by Megamouse** [comment]
This is obviously just a placeholder icon:

image

**Comment by dio-gh** [comment]
Ah I see, looks fine. For an unset avatar you could ask dags, I'm sure she could throw something together. 

Or use this one alternatively (maybe with a slight color adjustment):
image

[It's licensed under CC BY 3.0.](https://www.iconfinder.com/icons/285645/user_icon)

**Comment by Megamouse** [comment]
Using firmware icons as default. (depending on user id)

image

**Comment by Megamouse** [comment]
Merge NO REVIEW

**Pull request merged**
