### PR TITLE
Create 7704

### PR DESCRIPTION
**Pull request by fugazyrappersoutlook**

### CODE REVIEW

**Comment by RainbowCookie32** [comment]
What's the purpose of this PR?

**Comment by legend800** [comment]
Can we close this crap and ban this guy please?

**Comment by RainbowCookie32** [comment]
> 
> 
> Can we close this crap and ban this guy please?

No need to get to the ban, seems like he doesn't understand what he's doing and ended up creating a useless pr

**Comment by legend800** [comment]
Yeah, I guess. Seemed like they were screwing around intentionally, but maybe not.

**Pull request closed without merging**
