### PR TITLE
Qt: Add Operating system category

### PR DESCRIPTION
**Pull request by Megamouse**
- Add Operating system category
- Fix some type warning

### CODE REVIEW

**Comment by digant73** [comment]
could it make also sense to allow a clean removal of the firmware as currently possible for games/games data?

**Comment by FlexBy420** [comment]
Intended, way too many users would boot it for no reason.

**Comment by MSuih** [comment]
You can have XMB shown on the list by going to View -> Game Categories and enabling Operating System. By default it's not shown.

**Comment by FayeReagan** [comment]
Thank you for answering and teaching how to make it appear on the list again FlexBy420 and MSuih

**Pull request merged**
