### PR TITLE
gl/vk/dx12: Implement forced channel remapping

### PR DESCRIPTION
**Pull request by kd-11**
Implements FORCE_ZERO and FORCE_ONE swizzles observed with some games that discard the alpha channel despite requesting for a texture format with a working alpha channel.

### CODE REVIEW

**Comment by kd-11** [comment]
Needs vulkan and Dx12 confirmation that no regressions are introduced since I don't have access to compatible hardware at the moment.

**Comment by raven02** [comment]
@kd-11 Previously found one remapping issue , it would be nice if can take a look as well .

**Comment by RainKikyou** [comment]
alpha channel still
qq 20170306201337

**Comment by kd-11** [comment]
@raven02 Retest, I've matched DRGB8 to its native sampler format (BGRA8)

**Comment by raven02** [comment]
@kd-11 , humm it become full white screen now that same as DX12 .
untitled

**Comment by kd-11** [comment]
Should be fixed now

**Comment by raven02** [comment]
Confirm issue fixed

**Comment by raven02** [comment]
Tested for regression and it looks okay for VK/DX12.

**Pull request merged**
