### PR TITLE
[Qt] TTY frame improvements

### PR DESCRIPTION
**Pull request by scribam**
- Prevent html text to be interpreted in the tty frame
- Improve performance with heavy logs leading to less data corruption

### CODE REVIEW

**Comment by AniLeo** [comment]
I think this is intentional to test http samples that return web HTML pages but I'm not sure

**Comment by Nekotekina** [comment]
Must be amazing PR, but is it safe for newlines?

**Comment by scribam** [comment]
@AniLeo you are right, I would like to be able to compare html texts printed by RPCS3 and the PS3. I could look into the TTY.log file but I find it more convenient to check the result in the TTY frame.

**Comment by scribam** [comment]
I did a sample test with `printf("Before newline\nAfter newline");` and I have the same result displayed in the TTY frame and in the TTY file:
> Before newline
> After newline

@Nekotekina Does that help answer your question?

**Comment by Nekotekina** [comment]
No, I mean you removed text.chop, which existed for a reason.

**Comment by Megamouse** [comment]
(without having tested) It should be fine since insertPlainText(text) appends text to the cursor position. Append instead adds a new paragraph.

I only fear what happens when your cursor is somewhere in the log and not at the end.

**Comment by scribam** [comment]
It is like Megamouse wrote above.

Moreover, the output in the TTY frame is still not the exact copy of the TTY.log. I can see sometimes corrupted parts in the frame. I can reproduce it in master as well so I think it is more related to the code which actually retrieves the data from the file. I haven't investigated properly this case tough.
https://github.com/RPCS3/rpcs3/blob/95c6ac699b654e9c7ad35a5c63a9113db60ba125/rpcs3/rpcs3qt/log_frame.cpp#L318-L322

**Comment by TGEnigma** [comment]
Yes, the TTY log sometimes skips lines or only copies half of them. Especially noticeable if you spam the log.

**Comment by danilaml** [comment]
@scribam is `sub` even null-terminated?

**Comment by scribam** [comment]
I pushed a fix for the text corruption in the tty frame, let me know what you think about it.

@danilaml I don't know, what will be a good test to check this ?

**Comment by danilaml** [comment]
@scribam then it's most likely isn't. You can just use `QString:fromUtf8` function directly there with a size parameter (probably `i`) without intermediate vector. You can test it with checking that`&buf[i - 1]` is always zero (if it's nit - then it is a bug).

**Comment by Nekotekina** [comment]
I don't see how switching to QFile can help. Now this is most likely wrong.

**Comment by danilaml** [comment]
Also, it doesn't look like there is a reason to keep them in unique_ptr's rather than regular fields.

**Comment by Megamouse** [comment]
what about text color

**Comment by scribam** [comment]
@Nekotekina The combination of QFile and QTextStream works perfectly so far, you can check yourself. Can you explain to me why this is wrong? Is there some edge cases I haven't thought?

@danilaml According to my understanding of memory management, I use unique_ptr to avoid memory leaks. I don't mind using `QFile*` instead of `std::unique_ptr<QFile>` but I will have to add a destructor (~log_frame()) to free this memory otherwise Valgrind probably would not be happy, isn't it?

@Megamouse It is surprising but I haven't noticed any regression regarding text color with these changes, let me know if you find an issue

**Comment by danilaml** [comment]
@scribam No. I'm saying not to use pointers at all. Also, I don't think that `m_tty_qfile->isReadable()` does what you think it does (in this case it's useless).

**Comment by Megamouse** [comment]
yes the colors are working.
you could remove all the references of tty_text in stylesheets and rpcs3_app since they won't be used then

**Comment by Nekotekina** [comment]
First, it shouldn't be line by line writing. Newline may not exist at a given moment of time.
Second, I'm not aware how exactly Qt helps to fix corruption problem. It may be as well just hiding it. My opinion is likely reading zero bytes from not yet written areas. It could be solved by extending validation algorithm to be aware of zero bytes.

**Comment by Megamouse** [comment]
performance on huge tty logs seems to have improved with this, according to the kot

**Comment by scribam** [comment]
Closing as it will be done in https://github.com/RPCS3/rpcs3/pull/4223/commits/a7023c0a7577fd31b32b27f44dc7c674eb82d294

Thanks all for your feedbacks on this :slightly_smiling_face:

**Pull request closed without merging**
