### PR TITLE
Add game category AT

### PR DESCRIPTION
**Pull request by JayC-03**
For App TV applications.
Youtube (NPUP10028) now starts..

### CODE REVIEW

**Comment by clienthax** [comment]
Should fix this then? https://github.com/RPCS3/rpcs3/issues/2926

**Comment by clienthax** [comment]
Also needs AM for certian apps, tested, works nicely

**Comment by JayC-03** [comment]
@clienthax Added!

**Comment by clienthax** [comment]
@JayC-03 and SF :D, I think that's all lol

**Comment by JayC-03** [comment]
closing this as it is outdated.
will open a new one

**Pull request closed without merging**
