### PR TITLE
[WIP] SPU ASMJIT and fast interpreter improvement

### PR DESCRIPTION
**Pull request by jjsat**
There is issue #2670 dealing with differences between fast/JIT and precise SPU interpreter. @kd-11 has added code in #2683 to deal with this.

This applies the same code from FMS, FMA and FNMS to the basic FM instruction in the fast interpreter and JIT. ~~With the change I cannot observe any more differences in behaviour compared to the precise interpreter. Of course it is difficult to say since the precise interpreter is often too slow to get very far into a game.~~ EDIT: Still differences, needs more testing.

This fixes for me with fast interpreter and JIT (I know that the first two issues did not happen with the precise interpreter):
- collision in Trine; no more falling through the world and crashing right after loading the second area
- physics in Wolfenstein (barrel exploding on level load) EDIT: There is one such physics issue even with precise interpreter.
- massive slowdown in Fat Princess demo after a few seconds of playing

### CODE REVIEW

**Comment by kd-11** [comment]
Thanks. Looks like I forgot about FM when updating the other instructions.

**Comment by Kravickas** [comment]
Fixed objects falling under map + possibly no more slow-mo at 25fps (idk if its from this)

**Comment by AniLeo** [comment]
This breaks Lord of the Rings Conquest. I have tested this at least five times.

On current master, goes Ingame with SPU Precise and SPU Recompiler
With this PR, doesn't go Ingame with SPU Recompiler - dies on MFC Thread Access Violation, but goes Ingame with SPU Precise.

**Comment by al0xf** [comment]
Dito with TLoU

**Comment by jjsat** [comment]
I cannot tell for RDR and Lord of the Rings, but TLOU dies on current master too. It was not doing that with this PR before master was merged into it.

**Comment by AniLeo** [comment]
TLOU is likely related to cellSsl commit. 

I did test Lord of the rings properly several times to make sure I wasn't going crazy.

**Comment by MarioSonic2987** [comment]
image
Fixes objects falling through the map in Skate 2.

**Comment by jjsat** [comment]
I can reproduce the crash with the LOTR demo. Tried to find out how the output from FM for precise and this PR diverges when used by the game with the fast interpreter. The only thing I see is that precise (like a real SPU) does not produce negative zero while the PR does. Shouldn't matter too much and sanitizing it doesn't help with the issue, neither does flushing denormals to 0.

The games never calls info FM with a NAN, only sometimes with INF but then the second operand is always 0 so the output is 0 too. I haven't actually compared the bit patterns of the float values, only looked at what printf puts out for now.

The fast SPU interpreter code in master produces quite a bit of NANs (-1#IND) from INF inputs, which then propagate to further calls to FM.

**Comment by woj1993** [comment]
@jjsat Why changing FM to return 0 when input is inf, 0 won't work?
For example:
if (arg[0]==inf && arg[1]==0) {return 0;} else
{fast code};

**Comment by jjsat** [comment]
Contrary to my previous comment, LOTR seems all over the place with its input values so there is not one hack that will make it work (especially without breaking the other games) or at least I haven't found it. At some point you are reimplementing the function from the precise interpreter which makes this somewhat pointless.

**Comment by woj1993** [comment]
@jjsat This branch is ready for review?

**Comment by jjsat** [comment]
In the current state it should probably not be merged. This is only a hack and unfortunately it causes regressions. If I had experienced them before doing the PR I would not have opened it.

**Comment by woj1993** [comment]
@jjsat Will you fix it properly? If so you can add WIP label. Eventually you can close this pull request if you don't want to work on this.

**Comment by Kravickas** [comment]
oh :( i was so looking for this

**Comment by jjsat** [comment]
#3526 fixes the same issues without regression.

**Pull request closed without merging**
