### PR TITLE
rsx: Stuff

### PR DESCRIPTION
**Pull request by kd-11**
Changes:

**Main**
- Introduces the base for the gpu programs analysis and management. This will be expanded in future but right now it preparses the program ucode and tracks some statistics like usable ucode start, texture units consumed, etc to minimize number of generated shaders in some poorly coded titles.
-  Properly works around two AMD driver bugs, one vulkan bug relating to primitive restart and another opengl bug caused by broken generation of gl_vertexID in some situations
- FP: Properly initialize CC registers to fix some poorly written assembly shader ucode
- VP: Implement flow control. This implements properly jumps and function calls (CAL, BRI, RET, etc). This adds proper support for subroutines.

**Other Improvements**
- Optimize transform constant management on vulkan
- Optimize program state management in rsx core

These two changes can give significant framerate boosts to some games. Combined with the program management changes and the analyser, gameplay is smoother overall with less stutter and better performance.

### CODE REVIEW

**Comment by Xcedf** [comment]
Greatly Reduces the amount of created shader cahce in games like
Far Cry 2
Lost Planet 2 Demo
Prince of Persia
previously it counted in a thousands

**Comment by kd-11** [comment]
There are other ways of handling it with better shader cache fs management. This whole thing is still very WIP though for quite some time though.

**Comment by Nicba1010** [comment]
Ok then, I think the most straightforward way would be just keeping it in different folders named by version so its easy to filter/zip up/whatever

**Comment by jobs-git** [comment]
RSX is now more stable with this pull, D3 does not need cpu blit and wcb enabled

Params
PPU llvm recompiler
SPU ASMPJIT
Vulkan

**Comment by Xcedf** [comment]
Not tested too much but here's another improvement
shadows are fixed now in
Assassin's Creed

Prince of Persia

**Comment by theoldsport** [comment]
No improvement in Condemned 2, unfortunately. It's a game that spews shaders ad infinitum. Even just staring at the same patch of ground, new shaders will continually be compiled.

**Comment by Zangetsu38** [comment]
Yes, and condemne 2 is very special, glitch on render randomly with green glitch hmm

**Comment by Xcedf** [comment]
Fixed GoW HD broken performance

**Comment by Kravickas** [comment]
WRC 4 freezing in menu behavior like @alex88510 said

**Comment by kd-11** [comment]
I think the freezing happened after rebase,  moving the end marker check should not affect games that way by itself. Maybe someone with source can bisect?  I dont have any examples that freeze.

**Comment by AniLeo** [comment]
If it's a regression from Nekotekina's work, just using Interpreter (fast) usually avoids the issue. This is the case for Catherine for example.

**Comment by sibradzic** [comment]
@kd-11 in reference to #3792, I've just built this PR branch and can confirm that RADV @ Linux is still freezing GPU & the whole the OS, 100% reproducible...

**Comment by Rpcs3tester** [comment]
Thanks @kd-11 

- i can confirm ( GOD OF WAR 2 HD ) restore it's speed run perfect .

- God of war ascension Stops running with OGL . emu Fatal crash . but it's run will with Vulkan

- Saw 2 now almost fix shadow of player & some point ingame that  prevent you from solve puzzle

saw1
saw2


- TTT2 still have issue with custom player & Fallen Garden stage * it's show character only when you pause the game

ttt2
ttt22
ttt222

**Comment by psennermann** [comment]
With this PR the game SAW has much less shader cache stuttering, while unfortunately NiNoKuni is almost 10% slower than master 0.5-6697 (Vulkan)

Win10
i5 7400
Gtx1060 3gb

**Comment by Xcedf** [comment]
Last commit brought to many games
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\sources\neko\rpcs3\emu\rsx\vk\../Common/texture_cache.h:159)
now it forces me to use Cpu Blit even in games that worked fine without it, for example Condemned 2 now wants Cpu Blit, and WCB with it to render stuff, otherwise it blackscreen
now it is slower and also render broken

**Comment by TigiHof** [comment]
Commit efd676b (rsx: Do not process malformed vertex programs) caused an ugly but interesting regression In God Of War HD (NPUA80490). After using the standard weapons (the Blades of Chaos), two fiery lines remain on screen for a while, see images.

Correct:
gow_correct

Regression;
gow_error

**Comment by EmulationChannel** [comment]
LLVM
AMSJIT
anotacao 7

**Comment by Xcedf** [comment]
@EmulationChannel unfortunately this issue is nothing to do with this PR

**Comment by EmulationChannel** [comment]
LLLLLLL

**Comment by AniLeo** [comment]
Known to be PPU Regression from previous Nekotekina PR, unrelated to this PR. Deleting false report.

**Comment by kd-11** [comment]
@TigiHof Your report is also wrong and is a ppu regression caused by llvm 6 update. I can understand the assumption that all graphics bugs must be from rsx changes but this is bot the case.

**Comment by kd-11** [comment]
The mirror stuff is experimental and not ready yet. Will cause deadlocks if used as is.

**Comment by TigiHof** [comment]
@kd-11 As a matter of fact I did not assume anything. Fact is, that in previous commits for #4505 this error does not occur and in all subsequent commits it does. So what else should I think other than the error was caused by this change?

**Comment by kd-11** [comment]
Usually for regtesting PRs the tests are made against master for this very reason. There have been many changes to master since #4505.

**Comment by raveskirza** [comment]
With the new commit b8e9338. the texts in menus of TTT2 is missing

image

Before commit and master

image

**Comment by laincat** [comment]
rpcs3_2018-05-12_10-56-06
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1997228/RPCS3.log)

**Comment by laincat** [comment]
Before
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1997236/RPCS3.log)
rpcs3_2018-05-12_11-04-55

**Comment by MSuih** [comment]
untitled
Shirts are no longer being drawn.

**Comment by PlayerWind** [comment]
Dragon Ball Z Burst Limit Black Screen

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1997351/RPCS3.log)

Rpcs3 Version  v0.0.5-94fa6b239

Screenshot:
screenshot

**Comment by MSuih** [comment]
I can confirm that the last commit fixed the invisible shirts issue.

**Comment by psennermann** [comment]
OT: for testing purpose, is there any chance that "automatic buildbot" will work again any time soon?

**Comment by alex88510** [comment]
Till https://github.com/RPCS3/rpcs3/pull/4505/commits/770787c97dd2a5096e07a388b3dff6533795a68b, project diva f 2nd still freeze once passed the main menu. (I didn't test other games)

Anyone else is facing this issue? 
I am currently preparing a build environment to manually add in the commits from this PR one at a time to the master build to see which commits is causing the issue. 
I am not so familiar with visual studio, so it will be great if anyone can help or guide.

**Comment by kd-11** [comment]
@alex88510 Should be fixed now.

**Comment by alex88510** [comment]
@kd-11 yes, fixed by commit https://github.com/RPCS3/rpcs3/pull/4505/commits/6f1c67ed3b619e2060c35b1bfd76ecb2542204a2. 

My build environment also ready now and managed to build for the first time but suddenly loss its purpose. Hahaha~
Guess I'll leave it for next time.

**Comment by Kravickas** [comment]
Perf diff ++
PR
rsx
Maestro
master

**Comment by legend800** [comment]
This PR has regressed GTI Club stability. Now there's always some kind of rsx error after launching the game. The only way past the menus to gameplay is to activate WCB (which kills gameplay speed). This was the behavior before some of your other recent rsx changes which allowed it to reach ingame with excellent speed. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1998194/RPCS3.log.gz)

**Comment by Xcedf** [comment]
Still have in Uncharted 2 before intro movie
F {SPU[0x2000002] Thread (highCellSpursKernel2) [0x022c4]} class std::runtime_error thrown: Verification failed: 
(in file c:\sources\neko\rpcs3\emu\rsx\rsx_cache.h:220)
will it be fixed, cause unlike other verifications this one can't be bypassed it just crashes with the segfault, and even if i stop the game after this error, iwill not be able to run any other it will also has segfault

**Comment by Asinin3** [comment]
@legend800 This couldn't be avoided the same thing that improved stability massively regressed performance in some games see kd-11's comment here: https://github.com/RPCS3/rpcs3/issues/4506#issuecomment-386861883

**Comment by kd-11** [comment]
I have removed memory protection changes from this PR, that is a huge task and deserves a separate tracker.

**Comment by Defiect** [comment]
Demon's Souls won't get past the opening loading icon with this build. Tried vulkan, openGL, and both recompiler and interpreted CPU modes

**Comment by kd-11** [comment]
image

**Comment by kd-11** [comment]
However it later dies / locks up with the old 9.78fps hang - That regression has nothing to do with this PR though.
```
E {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x0154cb2c]} Stat: 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x231256]
E {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x0154cb2c]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x231256]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x0154844c]} Stat: 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x115628]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x0154844c]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x115628]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x0154844c]} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x28907]
```

**Pull request merged**
