### PR TITLE
Few improvements to metainfo (aka appdata)

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by hcorion** [comment]
I'm not sure if an empty content rating applies for oars in the case of emulators.

Apps like YouTube or Stadia on iOS and Android seem to list all the details of the games/content you can play on them.
Stadia iOS Age Rating

Are you aware of how ratings work in the case of OARS with content the user decides on? Are there any examples of other software that work similar to this?

**Comment by Lctrs** [comment]
I think Youtube and Stadia's situation are different than RPCS3's one.

Youtube and Stadia provides direct access to contents that can be subject to OARS ratings, meanwhile RPCS3 is empty by default, you have to buy the games and dump them, having been already presented with the ratings associated with the game.

That being said, I really don't know. I tried to do some research on Internet but I only found this sentence on an [OARS generator website](https://hughsie.github.io/oars/generate.html) : 

> If the user is able to "enable" NSFW or "adult" content, then this should be included in the assessment even if it is turned off by default.

But I don't find that very clear.

**Comment by hcorion** [comment]
Maybe worth creating an issue at https://github.com/hughsie/oars/issues asking for clarification and advice on how to label emulators.

**Comment by hcorion** [comment]
Actually looks like oars is an abandoned project https://github.com/hughsie/oars/issues/41#issuecomment-812142468
Can we just remove it from this PR? I'd be fine with that.

**Comment by Lctrs** [comment]
@hcorion Agree. Done.

**Review by hcorion — APPROVED** [review]

**Pull request merged**
