### PR TITLE
gl/vk/rsx: Add a cross-platform overlay text; Minor perf improvements and rsx bugfixes

### PR DESCRIPTION
**Pull request by kd-11**
Adds a font-drawing mechanism that uses a plotted point list. Draw back is that font size is static, but it works well for debugging overlays. Some features are not yet complete, such as proper rendering of some special characters.
The glyphs are loaded from hex strings. This case uses the first 128 chars from the GNU unifont set (GPL), but this can be changed if needed.
Also includes minor performance improvements to the opengl code.

### CODE REVIEW

**Comment by kd-11** [comment]
@Nezarn @raven02 Please check if the overlays cause any trouble.

**Comment by Nezarn** [comment]
Doesn't cause issues for me

**Comment by kd-11** [comment]
Added a partial fix for https://github.com/RPCS3/rpcs3/issues/2145

**Comment by raven02** [comment]
It looks good .Just wonder will this new overlay apply for DX12 as well later?

**Comment by kd-11** [comment]
DX12 being windows only is using d2d text functions. It is compatible with this implementation, but not hooked up to use it at the moment.

**Comment by raven02** [comment]
i see thanks @kd-11

**Comment by kd-11** [comment]
rebased the commits into something more manageable.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/2145 should be fixed.

**Comment by AniLeo** [comment]
@raven02 probably it would be better to not squash commits in this cases. Some were unrelated to the others. Its harder to read changes imo. Let the devs choose whether they want to squash them or not.

**Comment by sirdanielk** [comment]
might be this error related to this PR, im on AMD with OGL backend
F {rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 'Vertex shader failed to compile with the following errors:
ERROR: 0:9: error(#143) Undeclared identifier: gl_DrawIDARB
ERROR: 0:9: error(#166) Integer expression required: []
ERROR: error(#273) 2 compilation errors.  No code generated

**Comment by kd-11** [comment]
@sirdanielk Yes, missing GL_ARB_shader_parameters extension will cause that.

**Comment by kd-11** [comment]
What GPU are you running? (and driver)

**Comment by sirdanielk** [comment]
Strange, i found extension on khronos site, but its not existing in any GPU ogl extensions database
. Is anyone using this extension?

**Comment by kd-11** [comment]
AMD 7000 series and up, Nvidia Fermi and up if I remember correctly. Even open source mesa has had it since 2014

**Comment by kd-11** [comment]
http://opengl.gpuinfo.org/gl_listreports.php?listreportsbyextension=GL_ARB_shader_draw_parameters
Its arb_shader_draw_parameters not shader_parameters as I mistakenly stated above.

**Comment by sirdanielk** [comment]
You are right. Im on AMD 5000. Also 6000 does not support this extension. So, it halts any game now. Any solution apart from buying new hardware? :)

**Comment by kd-11** [comment]
No need to drop 4.3 capable hardware, its all we actually need right now. That extension is not part of core even now, so I should add checks to disable the overlay from initializing unless the user checks the box in the dialog.

**Pull request merged**
