### PR TITLE
kernel-explorer/lv2: Make lv2_fs_object an abstract structure

### PR DESCRIPTION
**Pull request by elad335**
* Make lv2_fs_object an abstract structure.
* Improve kernel-explorer information for filesystem objects.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Umm... it should be more useful to devirtualize it instead. It's not the only possible way to print debug info...

**Comment by elad335** [comment]
Done + improved kernel explorer output.

**Comment by Nekotekina** [comment]
Remove virtual destructor as well

**Comment by elad335** [comment]
Done.

**Comment by Nekotekina** [comment]
Thanks

**Pull request merged**
