### PR TITLE
Fix Xaudio2 for Windows 8 and Windows 10.

### PR DESCRIPTION
**Pull request by Zangetsu38**
Use Xaudio2 2.8 for Windows 8 and Xaudio2 2.9 for Windows 10.
Fix error Xaudio2 without have Obsolete SDK Directx10 (June 10).
For Windows 7 that does not change, it applies only to Windows 8 and more.

### CODE REVIEW

**Comment by Bigpet** [comment]
Does this still work on Windows7?

**Comment by Zangetsu38** [comment]
@Bigpet for Windows 7 no change

**Comment by danilaml** [comment]
The problem with this PR is that it just decides statically on what XAudio version to use depending on the host (the ones who is building) OS. So there will be different versions of rpcs3 depending on host OS and the ones built on win 10 wouldn't run (with xaudio) on win 8, same for win 8/win 7.

Right now it just uses the lowest common denominator (win7 version of lib). And AFAIK there is no real improvement in newer libs (for us) to bother trying to organize some dynamic loading and support of different version of XAudio,

Correct me if I'm wrong.

**Comment by Zangetsu38** [comment]
@danilaml Precisely so, if I do this is that XAudio2 currently does not work on Windows 8 and 10, because of the Xaudio 2.7 is not supported.
Microsoft recommends using XAudio2 2.8 for Windows 8 and 2.9 for Windows 10 XAudio2.
They say that Windows 7 uses only version 2.7.

**Comment by danilaml** [comment]
@Zangetsu38 what do you mean XAudio 2.7 is not supported by win 8 and 10? It work fine here. There is old version of the lib present. It's the other way around - newer versions are not supported by older platforms.

**Comment by Nekotekina** [comment]
So current version uses 2.7 and it works fine on Windows 7, 8.1 and 10?

**Comment by danilaml** [comment]
@Nekotekina I'd assume so, yes.
```c++
#define _WIN32_WINNT 0x0601 // This is to be sure that correct (2.7) header is included
#include "minidx9/Include/XAudio2.h" // XAudio2 2.8 available only on Win8+, used XAudio2 2.7 from dxsdk
#undef _WIN32_WINNT
```

**Comment by O1L** [comment]
Stop it, just use XAudio 2.7. Any reason for using XAudio 2.8+ here?

**Comment by tambry** [comment]
@O1L I there is currently no need to upgrade to a newer XAudio.

I'll be closing this PR. If @Zangetsu38 wants to explain, why it's needed and how he's going to use some of the new features of it or something, then feel free to reach back to me, so I could reopen this.

**Comment by Zangetsu38** [comment]
euu Sorry ? actually Xaudio2 not works for Windows 8 and Windows 10.
I have not done all this for nothing, would stop being so limited with Windows 7, most user uses Windows 10, and complain that XAudio not work, me neither he not walk before I do that, I afford it but XAudio2 2.7 is fully compatible with version above Windows 7, it's just not meant for that.
@danilaml No supported, launch rpcs3 with xaudio on Windows 8 and 10 ans rpcs3 crash caused By Xaudio...
@tambry is Simple, it is compatible and the Xaudio unjustly walking on Windows 7, and my PR is very good, with it we can finally used Xaudio with Win8 or 10.
@Nekotekina No, indeed, this is why I do this, the Microsoft yet said very clearly, XAudio 2.7 only works on Windows 7.

**Comment by tambry** [comment]
@Zangetsu38 I'm sorry, I don't understand you.
At this point, if you want to contribute to the project, I honestly think you should learn English.

**Comment by Zangetsu38** [comment]
@tambry Yes, I know, sorry, but it is simple to understand, currently XAudio2 2.7 is limited to Windows 7 (It's official from Microsoft), I did it to solve the problem, it is done perfectly.

**Comment by tambry** [comment]
@Zangetsu38 I'm sorry, what was the problem in the first place? Currently you aren't solving it perfectly. As pointed out previously, there are problems with this approach.

**Comment by danilaml** [comment]
@Zangetsu38 It workd for me (though it sometimes crashes at start).
`'rpcs3.exe' (Win32): Loaded 'G:\Windows\System32\XAudio2_7.dll'. Symbols loaded.`
You probably missing it for some reason. Maybe you did clean windows install and lacking older win dlls. In this case try searching for them, I think they were supposed to be in dx9 sdk.

**Comment by Zangetsu38** [comment]
@tambry There is no problem with this PR precisely, depending on the OS of the person who will compile, this version will be different, it will be 2.7 with Windows 7, Windows 8 with 2.8 and finally 2.9 with Windows 10.
I do not see where is the problem seriously, it's Microsoft who say meme them to do like that.
The build your doing everything to Windows 7, I do not understand.
@danilaml I know, if you use SDK June 2010 works, but very instable, and is a normaly, this is version not compatible for 10, and my PR solve this PR, no need to the very old sdk, and Xaudio2 perfectly works

**Comment by tambry** [comment]
@Zangetsu38 @danilaml Pointed out the mistake of it linking **statically** the XAudio.dll. Maybe you should re-read his post.

**Comment by Zangetsu38** [comment]
@danilaml But I know all that I have said in the description of the Pull Request.
I do not want to just install a SDK which has already 5 years and is totally incompatible, and that is not developed for it.
Microsoft says, however good, I really do not understand or is the problem.
This rule a big PR problem that was the for a while and you refuse, hang this time Xaudio only works on Windows 7, super sense that, while everyone uses Windows 10 now.

**Comment by tambry** [comment]
@Zangetsu38 
1. Read again @danilaml's explanation, of what's wrong.
2. Not everyone uses Windows 10.
3. If you still don't understand the problem, you should learn English and take some programming lessons.

**Comment by Zangetsu38** [comment]
@tambry 
I have already taken c ++ lesson, otherwise I would have never have done that.
Only XAudio2 2.8 and 2.9 on Windows 10
@danilaml Not exist, and and I do not want to use a old dll.
capture d ecran 2015-11-16 19 01 39

**Comment by tambry** [comment]
@Zangetsu38 At this point, seems like a lot of changes and the reasoning you bring behind them is like ideological. It's like trying to explain something to a fundamentalist, who will not even address your or anyone else's points and will just ignore them.

**Comment by Zangetsu38** [comment]
@tambry I do not understand what you told me, I just said that my Pull Request merely to solve a problem which is a long time, that's all.

**Comment by tambry** [comment]
@Zangetsu38 Well, you still refuse to understand, what's the problem, and why it's not OK. @danilaml explained it quite well already.

But if you still don't understand it, here's a small explanation: XAudio is gonna be statically linked depending on the platform, which means, that there will be a different executable for Windows 7, Windows 8 and Windows 10. This will also mean, that Windows 10 build wont work on Windows 7 and 8, and Windows 8 builds wont work on Windows 7.

At this point, if you still don't understand, I don't understand, I don't know how to get it to your head.

**Comment by Zangetsu38** [comment]
@tambry If I understand it.
Except that you not understand is that this is already the case, except that it ''s for absolutely everyone.
All the current build does that only works with Windows 7, you see what a place is the problem?
My PR allows her to run XAudio with Windows 8 and Windows 10, this is what you do not understand, the current version of XAudio absolutely not walk on Windows 8.10 and if were using the DX SDK June 10 it walking yes, but it is super unstable, and it is normal, Microsoft well say.
And for information, with a build XAudio2 2.8 or 2.9 run on Windows 8 or Windows 10, Windows 10 compatible with 2.8, it's just not optimize for, but it may work, or the 2.7 is just totally inconsistent.

**Comment by tambry** [comment]
@Zangetsu38 I give up. You're trying to fix the right problem, but in the wrong way.

**Comment by Zangetsu38** [comment]
@tambry In the wrong way ?
I see why, it does precisely solves perfectly.
There is no problem to the PR, that fix the problem, that's all.
Each person who has compiled it own version, I do not see where the problem is.
since each version of Windows has used a different version of Xaudio, it's just the best solution.

**Comment by tambry** [comment]
@Zangetsu38 Yes, in the wrong way. There's a big problem and it has already been explained by also me. It fixes the problem in the wrong way. Each person doesn't compile their own version, not everyone has the knowledge for it. It's the proper solution, as has already been described.

At this point, only advice I can give, is to read the whole thread again. And focus on @danilaml [explanation](https://github.com/RPCS3/rpcs3/pull/1307#issuecomment-157021785) and [mine](https://github.com/RPCS3/rpcs3/pull/1307#issuecomment-157127818).

If you **still** don't understand, then I don't think you ever will understand, what's the problem.

**Comment by Zangetsu38** [comment]
@danilaml Yes, but this advice is not made for those with Windows 8 or 10, as I have explained, it works, but it is unstable, rpcs3 crash very often because of XAudio2 not at all makes for a supervisor 7 OS.
I understand well what you want to tell me about the different version, but this is the only way to solve the problem.

**Comment by tambry** [comment]
@Zangetsu38 Another way would be to simply remove the XAudio backend and use OpenAL instead, which doesn't crash that often, works on Linux, Windows and many more.

**Comment by Zangetsu38** [comment]
@tambry Yes, it's on, but I noticed a better quality sound via XAudio, as with OpenAL.

**Comment by vlj** [comment]
Where is Xaudio2.lib currently linked in the master ? I see neither #pragma comment(lib, "xaudio2.lib"); nor a line in rpcs3.vcproj

**Comment by Zangetsu38** [comment]
@vlj There's just not.

**Comment by vlj** [comment]
Xaudio2.lib is automatically linked with MSVC ????

**Comment by Zangetsu38** [comment]
@vlj I do not know, but with version 2.9 and 2.8 we must include the lib, otherwise link error

**Comment by vlj** [comment]
@tambry The openAL backend is also slower than the XAudio 2's one. The overhead is not that big but we're not doing any processing to the audio stream ; basically we use the API just to send an array of bytes to the audio card. If it's possible to spot a performance hit in Sonic CD I can only imagine what it can become with more demanding games...

Issues with XAudio 2 is that they slightly broke the API between 2.7 and 2.8 :
http://blogs.msdn.com/b/chuckw/archive/2012/04/02/xaudio2-and-windows-8-consumer-preview.aspx
plus some bugs were discovered but not fixed (due to backward compat) :
http://blogs.msdn.com/b/chuckw/archive/2015/10/09/known-issues-xaudio-2-7.aspx
so if we want to support XAudio 2.7 and 2.8+, we need to have 2 backends because the includes are not compatible.

**Comment by Zangetsu38** [comment]
@tambry I have a fixed my PR, I have a forget testing Build for Windows 7, now it works perfectly with the three OS, look change https://github.com/Zangetsu38/rpcs3/blob/bc2a31624dc7faf335893ed8a76f5e35b23ef1c6/rpcs3/Emu/Audio/XAudio2/XAudio2Thread.h

**Comment by danilaml** [comment]
@Zangetsu38 btw, try installing https://www.microsoft.com/en-us/download/details.aspx?id=8109 and see if it helps with xaudio

**Comment by tambry** [comment]
@danilaml If you didn't understand, it's against his ideology and it's "disgusting" for him to use old .dlls.

**Comment by walbourn** [comment]
FWIW, my approach here in [DirectX Tool Kit for Audio](https://github.com/Microsoft/DirectXTK/blob/master/Inc/Audio.h) was to use XAudio 2.7 if building for Windows 7 compat based on ``_WIN32_WINNT`` or XAudio 2.8 otherwise.

The two pros of using XAudio 2.8+ are:

1. The DLL is included in the OS by default. XAudio 2.7 or earlier requires using the legacy DirectSetup REDIST package. See [Not So Direct Setup](aka.ms/dxsetup) and [DXSETUP Update](https://blogs.msdn.microsoft.com/chuckw/2011/04/19/dxsetup-update/)

1. If you avoid using XAudio 2.7, you don't need the legacy DirectX SDK installed to build at all. Instead the Windows 8.x SDK / Windows 10 SDK includes everything you need. See [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275.aspx) and [The Zombie DirectX SDK](https://blogs.msdn.microsoft.com/chuckw/2015/03/23/the-zombie-directx-sdk/).

The con of using XAudio 2.8+ is it is not supported for Windows 7

**Comment by AniLeo** [comment]
Our Windows builds target Windows 7 and above - and we're not planning on dropping Windows 7 support. 
I don't think that approach would be good for us, as that would require us to offer two different builds, one for Windows 7, and other for Windows 8.1+.

**Pull request closed without merging**
