### PR TITLE
Deploy QT DLLs using windeployqt tool

### PR DESCRIPTION
**Pull request by henriquenj**
Replace the old mechanism that manually copy the DLLs using either CMake
or VS built-in functions. The new approach uses the windeployqt tool
provided by the QT project that automatically detect the needed DLLs and
perform the necessary copying.

This approach should be more robust if there's an upstream change on QT
project regarding DLLs usage.

I'm testing all four build configurations on VS an see if everything works. Meanwhile let's the AppVeyor do its thing.

### CODE REVIEW

**Comment by henriquenj** [comment]
Following the merge of #3419, @danilaml suggested that I used `windeployqt ` tool to better solve the problem of finding and copying the DLL files that are needed to run RPCS3. So that's what I did in the PR.

I've tested the AppVeyor build and made local clean builds in Release, Debug and Release LLVM modes. Everything seems to be working.

**Comment by Megamouse** [comment]
This adds stuff we don't actually use (yet).
Like:
Qt5Svg.dll
translations folder
stuff in imageformats
iconengines folder

**Comment by danilaml** [comment]
@Megamouse I think Qt Widgets depend on Qt SVG, but if no svg icons or images are used anywhere, it should be fine. Probably not worth it delete it explicitly, since it only weights about ~320 KBs and that way you don't need to keep track of it in case you decided to add some svg handling.

**Comment by Megamouse** [comment]
Yeah but at least translations and iconengines are not needed

**Comment by henriquenj** [comment]
I will remove the translations and the iconengines later. However if the do-not-copy list gets bigger than the do-copy list I might just leave the old approach and forget `windeployqt` for now.

**Comment by danilaml** [comment]
new approach has an advantage of working even if rpcs3 gains new qt dll dependencies while the old one would require to manually modify all the solutions and build scripts.

**Comment by Megamouse** [comment]
It's easier to remove the few restrictions later than to add new files all the time

**Comment by henriquenj** [comment]
I removed most of the new DLLs, however I didn't want to remove imageformats because I couldn't find a clear way to do it and they seems to be useful anyway (it wasn't clear from the documentation the impact of not deploying them).

I've tested the local builds and the AppVeyour, everything seems OK.

**Comment by hcorion** [comment]
Is the `QTDIR` env variable set by the [Visual Studio Qt plugin ](https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools2015)?
For those people who don't have `QTDIR` set?

**Comment by henriquenj** [comment]
Good question. I don't have the plugin installed on my machine. Can somebody please test this?

**Comment by henriquenj** [comment]
I checked `rpcs3/rpcs3.vcxproj` and there are hundreds of occurrences of `$(QTDIR)`. I'd be surprised if a system without this variable would be able to build at all.

**Comment by danilaml** [comment]
@hcorion yes, you need to set up qt location for plugin to work: http://doc.qt.io/qtvstools/qtvstools-managing-projects.html#managing-qt-versions

**Pull request merged**
