### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by Nekotekina**
This should further improve SPU ASMJIT compilation speed and performance, but probably not noticeable.

### CODE REVIEW

**Comment by QQ220** [comment]
好像真的不明显

**Comment by Nekotekina** [comment]
Pushed an experimental commit. It should work, but please test for regressions or performance degradation just in case.

**Comment by Emulator-Team-2** [comment]
[ Fist of the North Star 1-Demo NPEB90285 ]
```
F {SPU[0x2000002] Thread (CellSpursKernel2) [0x30640]} JIT: Out of memory (size=0x908, align=0x10, off=0x0)
F {SPU[0x2000002] Thread (CellSpursKernel2) [0x30640]} SPU: Failed to build a function
F {SPU[0x2000002] Thread (CellSpursKernel2) [0x30640]} class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\cell\spurecompiler.cpp:561)
```
**Log:**  [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2803714/RPCS3.log)

-----------------------------------------------------------------------------------------------------------

[ Fist of the North Star 2-Demo NPJB90575 ]
```
RPCS3: Fatal Error
Unhandled Win32 exception 0xC0000005.
Segfault writing location 0000000000000000 at 00000000007497fa.
Instruction address: 00000000007497fa.
Function address: 00000000007490f0 (base+0x7390f0).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.
```

`F {SPU[0x2000003] Thread (CellSpursKernel3) [0x359e0]} JIT: Out of memory (size=0x2e4, align=0x10, off=0x0)`

**Log:** [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2803742/RPCS3.log)

**Comment by Krusher97** [comment]
rpcs3_ 2 _2019-01-28_21-16-40
rpcs3_2019-01-28_21-19-32

Huge FPS gain in Deception 4. Its a game which compiles SPU Cache nonstop so it can only run in ASMJIT but at single digit framerate. With this PR it hits 20+FPS

**Comment by arcadee1977** [comment]
Musou Orochi 2 Ultimate(BLAS50676):

SPU ASMJIT+mega+SPU cache

ERROR LOG (random crash):

F 0:01:18.155557 {SPU[0x2000004] Thread (MainSpursCellSpursKernel4) [0x34740]} JIT: Out of memory (size=0x2620, align=0x10, off=0x0)
·F 0:01:18.155560 {SPU[0x2000004] Thread (MainSpursCellSpursKernel4) [0x34740]} SPU: Failed to build a function
·F 0:01:18.155649 {SPU[0x2000004] Thread (MainSpursCellSpursKernel4) [0x34740]} class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\cell\spurecompiler.cpp:561)

**Comment by Emulator-Team-2** [comment]
[cd58087e]
[ Fist of the North Star 1-Demo NPEB90285 ]
```
·F {SPU[0x2000003] Thread (CellSpursKernel3) [0x2f5cc]} JIT: Out of memory (size=0x970, align=0x10, off=0x0)
·F {SPU[0x2000003] Thread (CellSpursKernel3) [0x2f5cc]} SPU: Failed to build a function
·F {SPU[0x2000003] Thread (CellSpursKernel3) [0x2f5cc]} class std::runtime_error thrown: Verification failed (e=0x7f) (0000000000000000): 
(in file c:\projects\rpcs3\rpcs3\emu\cell\spurecompiler.cpp:574)
```
Log:  [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2803880/RPCS3.log)

**Comment by Nekotekina** [comment]
Thanks, I don't think I will fix out of memory error in this PR.

**Comment by Emulator-Team-2** [comment]
[ 88639ae8 ]
[ ONE PIECE: PIRATE WARRIORS ]
```
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x303b8]} JIT: Out of memory (size=0x3ac, align=0x10, off=0x0)
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x303b8]} class std::runtime_error thrown: Verification failed (e=0x7f) (0000000000000000): 
(in file c:\projects\rpcs3\rpcs3\emu\cell\spurecompiler.cpp:292)
```
Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2804545/RPCS3.log)

```
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x39f50]} JIT: Out of memory (size=0x27b8, align=0x10, off=0x0)
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x39f50]} SPU: Failed to build a function
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x39f50]} class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file c:\projects\rpcs3\rpcs3\emu\cell\spurecompiler.cpp:551)
```
Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2804554/RPCS3.log)

```
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x399a0]} JIT: Out of memory (size=0x1870, align=0x10, off=0x0)
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x399a0]} SPU: Failed to build a function
F {SPU[0x2000004] Thread (CellSpursKernel4) [0x399a0]} class std::runtime_error thrown: Verification failed (e=0x7f) (0000000000000000): 
(in file c:\projects\rpcs3\rpcs3\emu\cell\spurecompiler.cpp:568)
```
Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2804561/RPCS3.log)

**Comment by Nekotekina** [comment]
@Emulator-Team-2 How much SPU cache it creates?

**Comment by Emulator-Team-2** [comment]
`S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 515046 functions. ` O_O

**Comment by creeperjedi** [comment]
In Dynasty Warriors: Gundam 3, I am getting the same "JIT: Out of memory" error that others are reporting, though I have seen a noticeable performance increase.
Log: [Dynasty Warriors Gundam 3 Log - v0.0.5-291d55bf.log](https://github.com/RPCS3/rpcs3/files/2805095/Dynasty.Warriors.Gundam.3.Log.-.v0.0.5-291d55bf.log)

**Comment by thx4ever** [comment]
Audio Stuttering in this PR
Game: Deception 4 Blood of Ties, this not happen on master for me, i'm using XAudio2 on Windows 10 Pro

**Comment by Kravickas** [comment]
It probably create more cache to be faster ? So it consume more RAM a u are all probably using only Safe mode which compile the most spu cache and eats more RAM than Mega and Giga, tho giga is almost unusable on master with heavier spu games. Out of memory is on master too if u choose safe mode and veeery spu heavy game for example GTA V

**Comment by arcadee1977** [comment]
I test Ninja Gaiden Sigma 2 with this PR , use SPU ASMJIT, there is no faster than master , only with SPU LLVM can we get faster speed .   In addition , turn off "Hyper-Threading Technology" in BIOS and get a huge speed boost (my CPU is 8700K)

**Comment by questore** [comment]
Can you post a Build link for me to test, please?

**Comment by money123451** [comment]
> Can you post a Build link for me to test, please?

click on the show all checks button and click details link next to the little blue circle and then the artifacts tab from there download the largest file and extract it to a folder ...

**Comment by Resident007** [comment]
Graphics in The Last of Us are now pretty broken though
image
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2812729/RPCS3.log)

**Comment by enkelprifti98** [comment]
Im also getting out of memory errors with Fifa Street 4 ever since this PR was merged to the Master branch. Is this being looked on? The performance is better with the Maintenance changes, hopefully the error gets fixed soon.

**Pull request merged**
