### PR TITLE
PPU LLVM/SPU/Non-TSX: Obnoxiously responsive and obedient PPU for SPU requests

### PR DESCRIPTION
**Pull request by elad335**
Needs PPU cache removal and rebuilt to test the pr.
Not to be merged before #14404 so perf comparison would accurate to what it was earlier.
Although testers are welcome.
Imnproves Persona 5 performance a bit.
May improve #14386

### CODE REVIEW

**Comment by brian218** [comment]
Since PPU cache needs to be rebuilt after this PR, would you mind refactoring the syscalls in sys_game.cpp (by removing the underline prefix) as well as those in sys_game_.cpp (add underline prefix or suffix) by the way?

**Comment by elad335** [comment]
I mean, I don't enforce its removal. Its just so the users can access this change of code.

**Comment by elad335** [comment]
I made the pr automatically create new cache but this commit would be removed before merge.
If you want to clean new cache created with this pr remove the files conatining "removable-14408":
image

After this pr is merged you still need to rebuild cache to use the new ppu llvm code because of the reverted invalidation.

**Comment by solarmystic** [comment]
Did the usual 5 game test, wiping all prior PPU cache before hand. Persona 5 did get a modest bump of 4 FPS compared to latest master, the rest are within margin of error (+2 to -1 FPS compared to master).

image

**Comment by elad335** [comment]
Added another optimization, idk if it actually improves anything and may behave differently between different CPUs, please retest.

**Comment by Ordinary205** [comment]
Heres the performance comparison on RDR.

Master: 28.2/29.7/30.6 FPS
<details>
<summary>Screenshot</summary>

RDR FPS 2 (2)


</details>

PR: 27.4/29.3/30.2 FPS
<details>
<summary>Screenshot</summary>

RDR FPS 1 (2)


</details>

**Comment by elad335** [comment]
And if you use the build of the previous commit?

**Comment by Ordinary205** [comment]
I've haven't tested the previous commit.

**Comment by elad335** [comment]
I mean, it's available.

**Comment by Ordinary205** [comment]
Anyways, heres a performance result that was tested on the previous commit.

PR: 27.8/29.5/30.5 FPS
RDR (2)

**Comment by solarmystic** [comment]
After commit https://github.com/RPCS3/rpcs3/pull/14408/commits/493d4e40d57c29175102fbf07046a2cb475d24a8 was added, nothing really changed, but Persona 5 and TLOU gains from master diminished by 1 FPS compared to the previous commit.

image

**Comment by cipherxof** [comment]
Very minor (if any) differences in MGS4.

<details>
  <summary>First commit</summary>

  eladpr

</details>

<details>
  <summary>Commit 493d4e40d57c29175102fbf07046a2cb475d24a8</summary>

  eladpr2

</details>

<details>
  <summary>Latest Master</summary>

image

</details>

**Pull request merged**
