### PR TITLE
[Need test] Try to reduce memory usage (mainly Windows)

### PR DESCRIPTION
**Pull request by Nekotekina**
This PR attempts to utilize sparse files feature existing on modern OSs to prevent allocation of unused memory if it's not already handled by overcommit feature.

Please compare memory usage and check for performance regression on Win32 hosts.

### CODE REVIEW

**Comment by solarmystic** [comment]
Causes a memory mapping error when trying to boot Persona 5. 

zCrashwithP5

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9267765/RPCS3.log)

This does not occur in the latest master.

P514007

**Comment by solarmystic** [comment]
Still crashes with a memory mapping failed error even after https://github.com/RPCS3/rpcs3/pull/12466/commits/db0039419c5d003fe75a06cb9aacb4ab202debe9

image

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9267945/RPCS3.log)

**Comment by MSuih** [comment]
The map3 error has been appearing for some users for quite a while. It seems to be very inconsistent, seemingly caused by builds which don't have anything to do with memory mapping.

So the reported errors could be caused by the changes in this pr or they could be from that earlier regression and only get triggered from this PR

**Comment by Nekotekina** [comment]
Thanks, try again

**Comment by solarmystic** [comment]
With https://github.com/RPCS3/rpcs3/commit/aa4c77ef79b41f603644846d0283b8a066a0a1ad games boot normally again. 

image

Performance-wise, it is similar to current master, no regressions noted.

**Comment by solarmystic** [comment]
As for memory usage comparisons, in Persona 5, both PR and master show similar usage, no reduction has been noted. 

PR
P5TMEM

Master (14007)
P514007MEM

**Comment by solarmystic** [comment]
Except for the reduced peak working set for the PR build, memory usage continues to be similar after https://github.com/RPCS3/rpcs3/pull/12466/commits/48da02604a6a4292ed53e2b5cba4ef03c4902f30 

PR
P5T2MEM

Current master (14011)
P514011MEM

**Comment by Nekotekina** [comment]
@solarmystic I think I can notice lower memory usage if I monitor total memory consumption (Performance tab). Can you check it too? Process metrics may be inaccurate for RPCS3 due to heavy use of shared memory.

**Comment by solarmystic** [comment]
> @solarmystic I think I can notice lower memory usage if I monitor total memory consumption (Performance tab). Can you check it too? Process metrics may be inaccurate for RPCS3 due to heavy use of shared memory.

Ah, i see it now. Test build commits 1GB less memory compared to master. Total In use memory remains the same, however. 

This PR
P5MEMTest

Master (14014)
P5MEMMaster

**Comment by solarmystic** [comment]
One thing though, I see 3 _block_xXXXXXXX files created in rpcs3 folder now, they consume roughly 1 GB space, i suppose they're made by this PR? They get created the moment a game is launched. 
image

**Comment by Nekotekina** [comment]
Fixed various issues, please retest.

**Comment by solarmystic** [comment]
Those block files are deleted upon exit now, nice work.

Committed memory usage is reduced by around ~0.5 GB in this latest PR commit.

PR

P5MEMTest

Master (14014)

P5MEMMaster

**Pull request merged**
