### PR TITLE
Qt 5.15.2

### PR DESCRIPTION
**Pull request by Megamouse**
This is supposed to get merged when and if we are running Qt 5.15.1 on the Docker build.
The Windows build is upgraded to QT 5.15.2

### CODE REVIEW

**Comment by Ghostotakoi** [comment]
Hope this fix https://github.com/RPCS3/rpcs3/issues/8409

**Comment by arabek** [comment]
FYI Qt-5.15.1 is the only available version on Gentoo as of last week.

**Comment by Cristichi** [comment]
Good luck! I'm counting on a fix to my Qt problem

**Comment by avindra** [comment]
Should be good, the [Suse rpcs3 build](https://build.opensuse.org/package/show/Emulators/rpcs3) compiles (and runs) with 5.15.1:

a

**Comment by Ghostotakoi** [comment]
I did a fresh install of windows and update it to latest version and it work now, so it might have been a window issue because I had the windows updater disabled I was using a windows that it was near (Or already) EOL, version 1803.

**Comment by AniLeo** [comment]
CI on Linux is the current blocker
QT 5.15.2 and 5.15.1 PPAs currently fail to build: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.2-xenial

**Pull request merged**
