### PR TITLE
Overlays: Use Back instead of Cancel

### PR DESCRIPTION
**Pull request by Megamouse**
I think this is how it is on the PS3 ?

### CODE REVIEW

**Comment by dio-gh** [comment]
Yea, and the `accept` button is written as `Enter`. [Video.](https://youtu.be/y1hXKMve4tM?t=51)

**Comment by bevanweiss** [comment]
I'm pretty sure the Message Dialog used Cancel (not Back).  I can't remember if it used Enter instead of OK though.
I can check tonight (AEST).

**Comment by bevanweiss** [comment]
It does indeed use 'Back' for the Message Dialogs
And as @dio-gh mentioned, it's 'Enter' vs 'Accept'.

**Comment by kd-11** [comment]
Different strings = different dialog symmetry; might require realigning the text location to the left.

**Comment by Megamouse** [comment]
@kd-11 
This means we already have a general problem.
We now have translations, which means the labels should ideally align themselves dynamically based on font width.

**Comment by kd-11** [comment]
You're right - I just never use translations so I did not notice it, but it does need to be dynamic. You can still merge this and then we can do the dynamic alignment later in a second PR; although ideally it should be the other way around.

**Comment by Megamouse** [comment]
The worse it looks the faster it will get implemented

**Pull request merged**
