### PR TITLE
Fix typo in sys_fs_mkdir

### PR DESCRIPTION
**Pull request by elad335**
create_path doesnt check for EEXIST and ENOENT.

### CODE REVIEW

**Comment by Nekotekina** [comment]
I think it was done on purpose, need to check git blame.

**Comment by elad335** [comment]
https://github.com/elad335/rpcs3/commit/ae1e9e78dbd80b7b348d5b0230f183501a1192d1
its a typo, EEXIST check was added inside of the if instead of an outside check with fs::is_dir. this was before ENOENT check was implemented.

**Comment by darkdragonz12** [comment]
FIX ULTIMATE MARVEL VS CAPCOM 3 AND, DEVIL MY CRY 4 INSTALATION :D

**Comment by Nekotekina** [comment]
That's not what I mean, creating full path could have been on purpose.

**Pull request merged**
