### PR TITLE
VFS: fix sys_fs_opendir on root directory

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by pollo790** [comment]
what a mprovement? this build gow 3 freezwes in seconds now, what you did??

**Comment by AniLeo** [comment]
GoW3 Demo and Full Game still work, false report.

**Comment by pollo790** [comment]
Why u banned me?



Sent from my Verizon, Samsung Galaxy smartphone

-------- Messaggio originale --------
Da: Ani <notifications@github.com>
Data: 08/03/19 16:20 (GMT+01:00)
A: RPCS3/rpcs3 <rpcs3@noreply.github.com>
Cc: pollo790 <vegeta79@live.it>, Comment <comment@noreply.github.com>
Oggetto: Re: [RPCS3/rpcs3] VFS: fix sys_fs_opendir on root directory (#5704)


GoW3 Demo and Full Game still work, false report.

**Comment by AniLeo** [comment]
If you were banned, you wouldn't be commenting. Stop spamming the tracker or you will.

**Pull request merged**
