### PR TITLE
VM: FreeBSD c_madv_no_dump/dump constants support.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by jbeich** [comment]
How did you test? I get a startup crash on
https://github.com/RPCS3/rpcs3/blob/266c4209c453e3cddd027eaf9be3eee2b0f672c8/rpcs3/util/vm_native.cpp#L175
rpcs3-optim

**Comment by Nekotekina** [comment]
I'm sorry, I know nothing about BSD but this addition looked very similar to Linux. Maybe it requires some runtime feature test, or this flag should be supplied separately from other flags.

**Comment by devnexen** [comment]
ah right sorry, was able to reproduce it in fact in my git stash I popped the wrong id ... maybe setting the constant `c_madv_no_dump` as I did locally ?

**Comment by Nekotekina** [comment]
Maybe try https://github.com/RPCS3/rpcs3/pull/10139

**Pull request merged**
