### PR TITLE
cellSaveData: Slow save completion (brings iconic game save icons back)

### LINKED ISSUE #8251: Wolfenstein [BLUS30298]: Unable to read save files
An old and known bug, but obviously there never was an issue opened for this.
In Wolfenstein [BLUS30298] you can not load save files, the game simply gets stuck (see screen shot). The automatic creation of save files at checkpoints seems to work fine, since the files are present on the hard disc.

Wolfenstein

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4640731/RPCS3.log.gz)

### LINKED ISSUE #9936: Jak 2 and 3 Hangs when saving/loading
Whenever you try to save or load a file in Jak 2 and 3, the game hangs at the save/loading screen and never finishes.

### LINKED ISSUE #10569: Sly 2 and Sly 3 think saves are corrupted when manually saving
## Quick summary
Letting Sly 2 and Sly 3 autosave on their own works and produces working save files, however manually selecting the "Save Game" option makes them think that the save data is corrupted, and it'll turn off autosaving.

## Details

Letting Sly 2 and Sly 3 autosave on their own works and produces working save files, however manually selecting the "Save Game" option makes them think that the save data is corrupted, and it'll turn off autosaving.  This affects all the digital versions and disc versions (NPUA80664, NPUA80665, NPHA80175, NPHA80176, NPEA00342, NPEA00343, BCUS98246, and BCJS30061).  Note that the manual saves do work, save data is saved, but the game doesn't realize this.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6835455/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

RPCS3

#### 4. Please provide comparison with real PS3.

Real PS3 doesn't display this, it just closes the menu and the save completes.

#### 5. Please provide your system configuration:
* Windows 10 19043
* Intel Core i9-10900K
* NVIDIA RTX 2080 Super
* 466.27

#### Please include.
* Solving issue #8708 did not solve this.  It's existed since the games reached the menus for the first time.

### LINKED ISSUE #10812: OBLIVION Softlock when changing settings during gameplay.
Oblivion fails to load after changing difficulty during gameplay.
Steps to reproduce: Push pause, go to options, then gameplay, and move the difficulty icon anywhere except for the exact same spot it was on. Attempt to back all the way out of the menus and click return. The message saving... will pop up and never progress. Audio continues as normal.
(Note: As long as you stay inside the menus the game will not freeze.)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7098465/RPCS3.log.gz)

### LINKED ISSUE #12843: OBLIVION [BLUS30087] Autosave Issue
### Quick summary

·F 3:42:28.054992 {PPU[0x100e004] Thread (thr_auto_save) [0x0016c994]} VM: Access violation reading location 0x0 (unmapped memory)

### Details

When playing Oblivion, particularly in Chorrol, and leaving from any of the inns, mostly The Grey Mare, a fatal error occurs **sometimes**. But always the autosave is fine and never gets corrupted.
If you play Oblivion for any duration you can see that the autosave message almost never leaves the screen because it frequently takes measurably 5 whole seconds or more to go away; particularly in Bravil which takes the longest time.
In reality, regardless of the message, any of the auto saves are loadable the moment you gain control over your character when walking through a door. The message lingering longer than necessary and this fatal error's behavior makes me assume something is taking WAY too long to exit the thr_auto_save thread because otherwise the game wouldn't actually save or the save would become corrupt. 
To reiterate the saves never do become corrupted or fail.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9821114/RPCS3.log.gz)

### Attach capture files for visual issues

NA

### System configuration

R5 3600
GTX 1660S
WIN 11 Beta

### Other details

In summary there's 1 major issue
Autosave fatal error
and 1 minor issue
The message lingering longer than the PS3's. Even if the message has a minimum timeout, 5 whole seconds or longer isn't that minimum.

### PR DESCRIPTION
**Pull request by elad335**
The save thread completed saving too fast which led to save completion to go unnoticede because of bad game code.
I also expect that this would bring back games' animated save icons as the saving PPU finally rests for half a second (delaying half a second) letting other threads do work. 
Fixes #9936 for Jak II for me. This is timing dependant so it needs testing for others.

Fixes #9936
Fixes #10812
Fixes #10569
Fixes #12843
Fixes #8251

### CODE REVIEW

**Comment by Megamouse** [comment]
Are you sure the delay isn't expected due to the user prompt?

**Comment by elad335** [comment]
It always return OK_LAST in its only savedata callback. But it also does it for when loading the game and I would not expect PS3 to confim loading savedata when booting the game. It also has its own confirmation screen and does not use PS3 savedata UI at all, I expect there is another condition which enables this screen but this game disables it in another way.

**Comment by Megamouse** [comment]
Is it autosave/load? Just curious.
I'm fine with a delay. We do everything 100 times faster than the PS3 anyway.

**Comment by elad335** [comment]
Yes these are autosave functiions.

**Comment by kd-11** [comment]
Needs testing with DeS/Ds2. Last time we had slow save routines due to io and they became unplayable due to the autosave triggering every few seconds.

**Comment by elad335** [comment]
Yes because the PPU wasn't sleeping which made the whole emulation get stuck. Real PS3 saving is pretty slow and may take a few seconds.

**Comment by elad335** [comment]
Tested DeS, it brings its saving icon for half a second as expected and does not stutter.

**Comment by YuriNator557** [comment]
Also fixes #10569

**Comment by jjsat** [comment]
Fixes https://github.com/RPCS3/rpcs3/issues/8251 and fixes getting stuck on the option screen in Thor: God of Thunder.

**Comment by Shoegzer** [comment]
When testing this PR against #5968 I discovered RPCS3 crashes immediately on launch.  It crashes on attempts to load any title, however.  Master is okay.

pic

**Comment by elad335** [comment]
Sorry but it doesn't make much sense considering the changes in code.

**Comment by tylerjm917** [comment]
Fixes #9936 for me

**Comment by BrancuAlexandru** [comment]
This is amazing, thank you

**Comment by KabbaCallisto** [comment]
I'm sorry if this is silly but how do i actually apply this?

**Pull request merged**
