### PR TITLE
vk: Disable spirv optimizations

### PR DESCRIPTION
**Pull request by kd-11**
- Causes crashing in drivers when compiling shaders. Needs further investigation.

Fixes https://github.com/RPCS3/rpcs3/issues/8170

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Did not seem to help. With a clear shader cache, it crashes the same way as before:

image

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4603155/RPCS3.zip)

**Comment by kd-11** [comment]
Try with debug output enabled and attach log. I didn't touch normal shader compilation other than adding spirv optimizations, so I don't know what else could be causing it.

**Comment by CookiePLMonster** [comment]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4603261/RPCS3.zip)

**Comment by kd-11** [comment]
Likely just some silly nullptr deref in the code then. Unfortunately I am unable to reproduce this locally.

**Pull request closed without merging**
