### PR TITLE
apply new gui design

### PR DESCRIPTION
**Pull request by Megamouse**
I finally was able to integrate some of @DAGINATSUKO 's new designs into the GUI:

-add tooltips.json and some new icons
-add .ui files and needed cmake changes
-remove settings tab files

Layout:
-changes layouts for welcome-, about-, settings-, and pad-settings-dialog
-adds a new mainwindow toolbar with buttons, slider and searchbar
-changes main_window menu layout

main_window:
-adds some fullscreen shortcuts for mainwindow
-removes the controls from top right corner (because of toolbar)

settings_dialog:
-use tooltips from json
-add descriptions
-rewrite to use one ui file instead of all those tabs

image
image
image
image
image

btw, the gamelist toolbar is still accessible

### CODE REVIEW

**Comment by raveskirza** [comment]
Couple of Observations

1. The options in Firmware settings are not shown completely. The settings dialog may need to be expanded. My screen resolution is 1920x1080 with text scaled at 125%
image

2. Previously we could dock game list and debugger side by side. Now it is merged into tabs. Only 1 can be used at a time
Old Gui
image

New
image

Couple of questions:
Are the game categories also going to be moved to the main toolbar? Will it get the blue icons which makes it more colorful and prettier?
Will there be option to have text under icons in Main tollbar? Or would it be only through mouse hover tool tips?

**Comment by zminhquanz** [comment]
oh wow , that impressive

**Comment by toccata10** [comment]
Nice improvement. 2 things:
1. "Controller to configure" and "controller status" are grayed. So I suppose it's still not possible to have 2 players play with 1 keyboard (would be great!)
2. It doesn't scale very well on hidpi screens.
Had the same problem here:
[https://github.com/RPCS3/rpcs3/issues/2539]

A few screenshots. My Os is archlinux, with a 4k screen.
On master:
settings_251
On this PR:
configure controls_245
settings_246
settings_247
settings_248
settings_249
settings_250

**Comment by Megamouse** [comment]
please try again

@raveskirza I have no problems setting the debugger next to the list. just play around a bit more

**Comment by toccata10** [comment]
It now works perfectly. Well done ! Thanks for supporting our 4k screens (which are awesome and will become more and more common).
A few screenshots to confirm.
02-configure controls_257
02-settings_258

**Comment by Megamouse** [comment]
NICE ... hmm the controller image surely could use some resizing, but that's something for another time

**Comment by raveskirza** [comment]
@Megamouse. Yes I am able to dock side by side after playing around a bit
The settings look much better now. Still see some characters missing
image
When opening the configuration the default tab seems to be on GPU instead of CPU

**Comment by toccata10** [comment]
@raveskirza No pbs on my side. It opens on CPU and there are no missing characters.
settings_262

**Comment by Megamouse** [comment]
I get the same issues. let me play around some more 🤦‍♂️

**Comment by Megamouse** [comment]
the latest commit should at least fix the default tab for gamelist settings.
Qt designer has the nasty habit of saving the tab you last worked on as default tab.
so i made some adjustments to always load the first tab

**Comment by Megamouse** [comment]
@raveskirza @toccata10 please try again.

I am especially interested in the controller image size as well.

**Comment by raveskirza** [comment]
Looks good now
image
image

**Comment by toccata10** [comment]
Looks good for me:
settings_264
configure controls_263

**Comment by Megamouse** [comment]
since discord seems down:

@AniLeo @al0xf I have the label appearing normal:
image

**Comment by Megamouse** [comment]
@al0xf i didn't change anything. maybe your build is bobo

**Comment by al0xf** [comment]
I deleted every .yml, still no "not needed" message with OpenGL selected...

**Comment by Megamouse** [comment]
windows or what?

**Comment by al0xf** [comment]
Windows 7

**Comment by Megamouse** [comment]
deleted guisettings?

**Comment by al0xf** [comment]
Yes

**Comment by Megamouse** [comment]
does it appear when you select something else and then opengl?

**Comment by TotalCaesar659** [comment]
@Megamouse Woundn't be good to use old blue icons without these ones? They look some funereal.

**Comment by al0xf** [comment]
The very same talented designer that did rpcs3.net (DAGINATSUKO) did the icons, the new controller menu and so on. So I disagree on that.

**Comment by kacek** [comment]
Grey color looks like button is disabled. Blue icons were much better.

**Pull request merged**
