### PR TITLE
Remove optional.hpp to use C++ standard library

### PR DESCRIPTION
**Pull request by scribam**
License and copyright files will be removed from the Utilities directory too

### CODE REVIEW

**Comment by kd-11** [comment]
As optional has been integrated into c++17, why not add a `using` clause and avoid all the unnecessary edits in the source files? Would be so much cleaner than this.

**Comment by scribam** [comment]
@kd-11 What about removing completely the file `optional.hpp` and using something like this ?
```
#if __cplusplus > 201402L
    #include <optional>
    using std::optional;
#else
    #include <experimental/optional>
    using std::experimental::optional;
#endif
```
All `std::optional` would be replaced by `optional`.

**Comment by paulsapps** [comment]
An alias would be much nicer than having `std::experimental` everywhere which will need changing in a couple of years anyway.

**Comment by kd-11** [comment]
@scribam No, this is the std implementation of optional. It should be std::optional. That differentiates it from any other variant like boost:: or even rpcs3:: if it ever comes to that.  Just add `using std::experimental` if c++ < 17 and most of the code need not change.

**Comment by Nekotekina** [comment]
Won't work for me.

**Comment by scribam** [comment]
@kd-11 I tried to add `using std::experimental` but it didn't work for me. I found an other way to do it and pushed the changes into this PR. Please have a look and let me know your thoughts.

**Comment by AniLeo** [comment]
Why not at least maintain the original idea and just move it as a submodule?

**Comment by scribam** [comment]
@AniLeo I could but first, I will need to have more details from @Nekotekina about why this PR won't work for him. Otherwise, if I do the same mistake again, a new PR might end like this one.

**Comment by Nekotekina** [comment]
VS 2015 has nothing that resembles optional, and we still support it. And there is no much reason to hurry with transition to 2017.

**Comment by scribam** [comment]
Thank you for your feedback. I didn't know about the optional support in VS 2015 until AppVeyor failed, Clang or GCC didn't make any complains on my Linux computer.
No problem to keep VS 2015 instead of 2017, I don't use any of them so I mostly rely on the AppVeyor status to know if my code is valid or not for Windows.

**Pull request closed without merging**
