### PR TITLE
Rewritten RSXThread, broken DX12 Renderer and another improvements

### PR DESCRIPTION
**Pull request by DHrpcs3**
Fully rewritten RSXThraed
Fixed image scaling for OpenGL renderer
Unificated renderers frames
Added frame (with fps :P) for Null renderer

TODO: dx12 renderer broken (I will happy, if @vlj handle it :D), some (or many, dunno) homebrews degraded

### CODE REVIEW

**Comment by vlj** [comment]
I'm looking at dx12 with this branch, btw what are the broken samples ?

**Comment by tambry** [comment]
My only annoyance would be not adding glm as a submodule. It's available here on Github: https://github.com/g-truc/glm.

**Comment by DHrpcs3** [comment]
@vlj cube(doesn't render text), for example. Full list can make any, who have many free time, that not I'm :D

I think, that errors in GLRenderer, not rsx::thread

**Comment by DHrpcs3** [comment]
gcc:
> internal compiler error: Segmentation fault

i'm very happy...

**Comment by vlj** [comment]
is it possible to move "load_vertex_data" calls to backend instead of RSX ?
With D3D12 I try to preserve buffer layout as much as possible instead of concatenating attributes so the method is not used.

**Comment by Ekaseo** [comment]
most samples (cube samples for example) and some games show this error E {rsx::thread} in_weight not found.

**Comment by vlj** [comment]
Another improvement is to add a "void *allocate_vertex_buffer(size_t);" and "void *allocate_index_buffer(size_t)" + corresponding unmap methods in backend, and have RSXThread call them and fill the given pointer with vertex/index data, thus avoiding extra copies. 
Currently RSXThreads copies vertex data to a vector, and the backend copies the vertex data from RSXThreads to the gfx API. It would be better to have RSXThreads copy directly to the gfx API.
With GL it could be implemented using glBufferData(..., size, nullptr, GL_STATIC_DRAW); return glMapBuffer(...);

**Comment by DHrpcs3** [comment]
@vlj 
> is it possible to move "load_vertex_data" calls to backend instead of RSX ?
possible, but we can make cache in rsx thread instead

**Comment by vlj** [comment]
I got d3d12 to build but unfortunately it renders garbages. 
Is it possible to split some commits and submit it progressively? For instance method or member renaming can be be implemented separately.

**Comment by DHrpcs3** [comment]
> Is it possible to split some commits and submit it progressively?
http://stackoverflow.com/a/6217314

**Comment by DHrpcs3** [comment]
I would merge this request. We have made release some days ago, so lets make critical, unstable and stupid changes to emulator core!

**Comment by danilaml** [comment]
@DHrpcs3 why couldn't it be worked on more until at least sonic cd or simple tests pass? It brok almost everything, would probably make developing something very difficult for others.

**Pull request merged**
