### PR TITLE
CMake: fix linkage on Linux, missing libdl

### PR DESCRIPTION
**Pull request by magiruuvelvet**
```
/usr/sbin/ld: CMakeFiles/rpcs3.dir/__/Utilities/dynamic_library.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib/libdl.so.2: error adding symbols: DSO missing from command line
```

### CODE REVIEW

**Comment by magiruuvelvet** [comment]
Fixes #2151

**Comment by John-Gee** [comment]
Doesn't that patch get you twice -ldl in the ! use_system_ffmpeg case? Shouldn't you remove the 2nd one? (Not that it really matters though).

**Comment by magiruuvelvet** [comment]
It didn't break linkage for me. I can remove it though, not that it really matters.

**Comment by John-Gee** [comment]
Oh I don't expect it to break anything, it's just a bit weird.

**Pull request merged**
