### PR TITLE
Rsx refactor: Use variant for draw commands.

### PR DESCRIPTION
**Pull request by vlj**
This PR uses std::variant for draw command handling (ie in code setting index array and vertex buffer if necessary).
It splits the 3 cases in separate functions (one for draw array, one for draw indexed and one for draw inlined) instead of relying on several if/else sequence. It's a little more verbose but the code logic is also more apparent.

### CODE REVIEW

**Comment by Nekotekina** [comment]
I don't really understand these format tweaks, UseTab must be ForIndentation as it was already used (with discussible move to spaces in future, but not the opposite). Automatically enforcing clang-format currently doesn't make sense because the tool is broken one or another way, and correctly supports (it seems so) only its default style. I installed VS plugin and prefer to manually apply it to selected fragments of code if necessary, like for formatting enum constant lists. If it breaks something or code becomes ugly, the best approach is to avoid autoformatting at all.

**Comment by vlj** [comment]
Issue is that it's hard to define rpcs3 coding style in term of clang-format style option. It looks like clang-format doesn't support tab as well as spaces. I'm getting mixed tabs-spaces at line continuation because clang-format uses tab for indentation and then spaces (continuationIndentWidth). Using always for tab + tabWidth matching continuationIndentWidth turns the spaces into tab. Unfortunatly others space sequences may be replaced with tabs...
Otherwise clang-format works well for me with the command line ; I once used the visual studio plugin but for some reasons it ignored the settings in the .clang-format file even with the "file" style set in the options.
The hook is only active if moved in .git/hooks and without the extension ; the file in the directory doesn't activate it automatically. I added the file just for reference since all the solutions I found with google doesn't handle the non staged change properly or just abort commit if style is wrong.

**Comment by vlj** [comment]
I will remove the clang changes

**Comment by Nekotekina** [comment]
I think VS plugin silently ignores the style file when it contains errors, however I can't say for sure. Regarding spaces instead of tabs, it seems fine to not worry about these minor inconsistencies.

```
AlignAfterOpenBracket: DontAlign
```
This change seems correct.

**Comment by vlj** [comment]
Removed the tab changes in clang format.

**Comment by vlj** [comment]
By the way I found this which tell MongoDB's experience with clang format : https://engineering.mongodb.com/post/succeeding-with-clangformat-part-1-pitfalls-and-planning/

**Comment by vlj** [comment]
Can someone check if there is any regression ?

**Comment by raven02** [comment]
@vlj .Sure , will check it out.

**Comment by raven02** [comment]
Tested so far okay .

**Pull request merged**
