### PR TITLE
BUILD: Refactor glslang submodule

### PR DESCRIPTION
**Pull request by p01arst0rm**
combined glslang-build and glslang into a single
directory structure, and moved them to `3rdparty/`

### CODE REVIEW

**Comment by p01arst0rm** [comment]
cc @hcorion

**Comment by hcorion** [comment]
If we're going to move glslang it should be consistent with the other libraries in 3rdparty and be glslang/glslang, instead of having a glslang-build folder

**Comment by p01arst0rm** [comment]
sure :)

**Review by hcorion — APPROVED** [review]
LGTM 👍 from the CMake side

**Pull request merged**
