### PR TITLE
D3d12: Fixes

### PR DESCRIPTION
**Pull request by vlj**
This PR fixes some defects found by investigating SH3. Game shouldn't lack geometry.
The alpha test sample background is also correctly displayed and some Braid glitches (cloud overlapping geometry) are fixed.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Great :) Silent Hill Now is Very good, and Jet Set radio Perfect :)

**Comment by danilaml** [comment]
Latest merges to master have degraded my performance in dice elf. Also I think after d3d12 as a lib pr rpcs3 crashes on game close, but It doesn't even correctly exit and still stays as hidden process holding resources and can be killed only through cmd taskkill /f

**Comment by vlj** [comment]
Will investigate the performance regression in dice

**Comment by danilaml** [comment]
@vlj can you look at crashing as well (I get it 100% of the time in closing of dice elf)? It makes testing harder.

**Comment by danilaml** [comment]
@vlj git bisect told me that https://github.com/RPCS3/rpcs3/commit/e76abf875f60585f622c0ff6ded239625d6b8f5a
is the first bad commit

**Comment by vlj** [comment]
@Zangetsu38 you need to increase buffer texture size, looks for
	"m_textureUploadData.init(m_device.Get(), 1024 * 1024 * 512, D3D12_HEAP_TYPE_UPLOAD, D3D12_HEAP_FLAG_NONE);" and use a bigger value than 512.

**Comment by Zangetsu38** [comment]
@vlj Thx, works now with 1024

**Comment by vlj** [comment]
The crash when exiting dice seems to be older than this commit, it looks like a crash happens in wxWidget, when deleting keyboard or mouse classes.

**Comment by danilaml** [comment]
@vlj ah, sorry, I din't make it clear - this commit https://github.com/RPCS3/rpcs3/commit/e76abf875f60585f622c0ff6ded239625d6b8f5a is for performance issues.
As for crashes - it started appearing for me around the time of d312 separation/projects/dynlib conundrum. Also I usually see some dx12 destructors in the callstack. Like ~RenderTargets or something.

**Comment by danilaml** [comment]
@vlj nevermind the crashes issue, it's most likely cause by configurations PR by @O1L (since it affects oGL in the same way too).
Still it leaves the performance issues (it totally destroys my iGPU performance (60 -> 3 fps) and my dGPU takes a noticable hit (37 -> 27 fps))

**Comment by vlj** [comment]
Rebased

**Pull request merged**
