### PR TITLE
rsx: Minor Fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Code style fixes
- Fix alphakill
- Fix color swizzle ordering for new blit dst surfaces
- Tweak to rsx hang detection
- Tweaks to sampler fallback paths for vulkan https://github.com/RPCS3/rpcs3/issues/3740

### CODE REVIEW

**Comment by twdarkeh** [comment]
http://puu.sh/yKiUY.jpg Fixes the text, but now the whole screen is white now.

**Comment by kd-11** [comment]
That issue was unrelated, but should be fixed now.

**Comment by Kravickas** [comment]
do u fix regression here from previous pr in skate 3 ? 
obrazek

**Comment by Asinin3** [comment]
Why not retest it and see? I'm sure if kd-11 purposefully fixed that issue he would of commented on it. Since he hasn't then it most likely means he didn't test Skate 3. That being said the issue may have been fixed by recent changes so it's still worth retesting.

**Comment by toccata10** [comment]
Battle Fantasia recently regressed. This PR doesn't fix it.
rpcs3-v0.0.4-2017-11-14-9e0b881-8781_linux64:
fps 61 73 vulkan 0 0 4-50 battlefantasia npub30126 _056
[RPCS3.log-Battle-old.gz](https://github.com/RPCS3/rpcs3/files/1582085/RPCS3.log-Battle-old.gz)
rpcs3-v0.0.4-2017-12-16-17bfb3b-9162_linux64:
fps 59 99 vulkan 0 0 4-6226 battlefantasia npub30126 _055
[RPCS3.log-Battle-OK.gz](https://github.com/RPCS3/rpcs3/files/1582086/RPCS3.log-Battle-OK.gz)
From rpcs3-v0.0.4-2017-12-18-de5dab3-9175_linux64:
fps 61 73 vulkan 0 0 4-50 battlefantasia npub30126 _056
[RPCS3.log-Battle-Wip.gz](https://github.com/RPCS3/rpcs3/files/1582087/RPCS3.log-Battle-Wip.gz)

**Comment by Kravickas** [comment]
@Asinin3 I woudnt ask if that screenshot wast from latest commit from this PR and wanted to know if kd fix it here or just create new issue.

**Comment by Asinin3** [comment]
@Kravickas #3952 There is already an issue and we know what PR caused the problem. If you tested this PR and it's still broken then you just need to keep waiting and testing until it's fixed. The issue is unrelated to this PR.

**Comment by kd-11** [comment]
@tocatta10 please open a dedicated issue for it. Include rdc traces for before and after if you can (I think renderdoc 1.x branch has linux support, but I havent tested it lately)

**Pull request merged**
