### PR TITLE
RSX/Overlays: Add option for japanese button layout

### PR DESCRIPTION
**Pull request by Megamouse**
Switches the X and O buttons in the overlay dialogs

### CODE REVIEW

**Comment by Megamouse** [comment]
Please let me know if this is working as intended.
One open question: should the displayed buttons be switch sides as well?
Meaning: should the accept button be on the right side now instead of the left side?

**Comment by Nekotekina** [comment]
Should make more sense to name the setting as defining the assigned button.
Like "Use cross assignment button", since there is also CELL_SYSUTIL_SYSTEMPARAM_ID_ENTER_BUTTON_ASSIGN

**Comment by Megamouse** [comment]
I don't think normal users understand the meaning of this

**Comment by Nekotekina** [comment]
Switch X/O is confusing because it doesn't determine which function is default, and which is switched. In fact, neither is, they are just different "standards".

**Comment by 13xforever** [comment]
@Megamouse you shouldn't switch UI element placement, only icons

**Pull request merged**
