### PR TITLE
SPU LLVM: Detect RCHCNT busy waiting

### PR DESCRIPTION
**Pull request by elad335**
Description is yet to be added.

### CODE REVIEW

**Comment by alexloxldlol** [comment]
This build:

image


Master:

image

**Comment by dio-gh** [comment]
NFS Undercover seems to be affected, though at best I've seen an fps or two gained.

image

**Comment by elad335** [comment]
If the pattern is not "good" and "amazing" it does nothing, but thanks for reporting anyways as it detect more "good" patterns.

**Comment by xddxd** [comment]
image
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4942004/RPCS3.log)
PR causes L.A Noire to crash while building some spu module. With a fresh cache game works until it encounters the module and with a cache it crashes while building spu modules.

**Comment by nitroos-ai** [comment]
Test link is dead.

**Comment by dio-gh** [comment]
Huh, thought this was long merged. Were the test results not satisfactory?

**Pull request closed without merging**
