### PR TITLE
SPU LLVM: Fix some regressions

### PR DESCRIPTION
**Pull request by Nekotekina**
Follows #5882 and also fixes some unnecessary SPU cache writes.

Does not require removing SPU cache.

### CODE REVIEW

**Comment by Xcedf** [comment]
Journey in This PR shows
F {SPU[0x2000001] Thread (CellSpursKernel1) [0x016a8]} class std::out_of_range thrown: invalid map<K, T> key
same as KillZone 2
F {SPU[0x2000005] Thread (LowPriorityCellSpursKernel0) [0x042b0]} class std::out_of_range thrown: invalid map<K, T> key

**Comment by Kravickas** [comment]
NHL® Legacy [BLUS31540]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3134968/RPCS3.log)
```
F {SPU[0x2000003] Thread (Job Manager - Job Thread) [0x00010]} class std::runtime_error thrown: Unknown STOP code: 0x400 (Out_MBox is empty)
(in file c:\projects\rpcs3\rpcs3\emu\cell\sputhread.cpp:2694)
```

**Comment by Xcedf** [comment]
class std::out_of_range thrown: invalid map<K, T> key issues i've reported are also gone on Safe mode
but still even with safe mode Journey have with Approximate Xfloat
F {SPU[0x2000001] Thread (CellSpursKernel1) [0x09ca0]} MEM: Access violation writing location 0xffdead00
and on Accurate Xfloat
E {SPU[0x2000004] Thread (CellSpursKernel4) [0x08840]} SPU: LLVM: Verification failed at 0x8840:
Instruction does not dominate all uses!
  %3204 = phi <4 x i32> [ %3112, %2177 ], [ %12847, %9363 ]
  %3577 = bitcast <4 x i32> %3204 to <16 x i8>

F {SPU[0x2000004] Thread (CellSpursKernel4) [0x08840]} class std::runtime_error thrown: Compilation failed

**Comment by Nekotekina** [comment]
Send spu cache which causes errors please.

**Comment by raveskirza** [comment]
After #5882 Beyond Two Souls no longer passes intro using SPU LLVM. Works with ASMJIT though

[RPCS3.log_latest_master_non-bootable.gz](https://github.com/RPCS3/rpcs3/files/3135221/RPCS3.log_latest_master_non-bootable.gz)
[RPCS3.log_Working build Master.gz](https://github.com/RPCS3/rpcs3/files/3135222/RPCS3.log_Working.build.Master.gz)

**Comment by Xcedf** [comment]
Journey safe spu cache
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/3135256/spu-safe-v1-tane.zip)
btw, reverted 5b8ffc6 to run Journey and found out that sound also broken only on Mega level, safe sounds fine

**Comment by Hasster1** [comment]
With this PR, Serious Sam 3 with Mega SPU block size crahes after loading screen with error:
F {SPU[0x2000001] Thread (FMOD) [0x002d0]} MEM: Access violation writing location 0xffdead00
With the asmjit or with the safe spu block size - the good old 
F {RSX [0x04c4d34]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:964)

Here is the log

[RPCS3_mega.zip](https://github.com/RPCS3/rpcs3/files/3135853/RPCS3_mega.zip)

[RPCS3_asmjit.zip](https://github.com/RPCS3/rpcs3/files/3135856/RPCS3_asmjit.zip)

**Comment by Hasster1** [comment]
Ok, i've tested a few more games.
The results are: None of them can even be played normally with spu llvm.
every 3d game and plants vs zombies are crashing
Terraria can go ingame, but it having an old problem, where it doesn't have sound, and crashing after a minute or two.

**Comment by Xcedf** [comment]
Everything i've reported refixed, thanks

**Comment by Hasster1** [comment]
Yup, it's fixed.

**Comment by arcadee1977** [comment]
Musou Orochi 2 Ultimate is speed dropped markedly in this PR. especially in SPU mega mode.

**Comment by connorwalks** [comment]
FPS dropped dramatically for me as well in College Hoops 2K8 and NCAA Football 10. Both games were locked to 60 fps for me prior to this release, and now they struggle to reach 20 FPS. May affect other games as well, those were the only two I played earlier.

Will upload logs when I get home.

**Pull request merged**
