### PR TITLE
Split fixes

### PR DESCRIPTION
**Pull request by Nekotekina**
Should automatically try to read split files with extensions 66600, 66601 in the case the original file is not found.

### CODE REVIEW

**Comment by Dokman** [comment]
Why has been reverted the commit of base address?

**Comment by elad335** [comment]
64k pages user allocations area seems to be initialised at 0x10000000 at program loading with some data. the global base is 0x30000000. [testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/64k%20allocation%20area)

**Comment by spyropt** [comment]
Soulcalibur V regressed to nothing with this pr
tried latest master but same result
no tsx or avx cpu
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2289983/RPCS3.zip)

**Comment by incognitoh** [comment]
@Nekotekina 

Just wanted to report a regression with MLB 09 The Show (BCUS98180)
Took a while, but I narrowed it down to this PR.  The game no longer gets past intro and still does not work with any current build since this pr. The game goes ingame fine with build 0.0.5-7182 but has regressed to intro ever since 0.0.5-7186.  

I tried fresh install of both the emulator and game and different settings, TSX on/off etc.. but same result. 

the error code always is: 

F {PPU[0x1000008] Thread (Utility PPU Thread) [0x00013500]} MEM: Access violation reading location 0xe2d0a0a0

**Comment by Asinin3** [comment]
What build are you using? A regression with this PR was fixed already in 0.0.5-7288 after I reported the issue.

**Comment by elad335** [comment]
post rpcs3.log.gz

**Comment by incognitoh** [comment]
@elad335 @Asinin3 

I apologize for the late reply.. I am using the current master build 0.0.5-7337 now. But as I said, every build after 7186, this game no longer works and gets a fatal during intro while it is loading the opening menu of the game. Here is a recent log: 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2383129/RPCS3.zip)

Again, I did try a fresh install of both the emulator and game and many different settings, deleted shaders, caches, TSX on/off etc.. but same result.  I double checked the dump of the game with PS3-ISO-Rebuilder and it came back clean. The game still works (ingame) with 7186 as I tested it with that build today but it has been broken ever since this PR #4975

the  fatal error code is: 
F PPU[0x1000008] Thread (Utility PPU Thread) [0x00013d30]} MEM: Access violation reading location 0xd2d0a0a0

i7 4790k
GTX 750ti
16gb RAM
Windows 7 64 bit

**Pull request merged**
