### PR TITLE
Improve cellSearch implementation

### LINKED ISSUE #3276: Project Diva F / F 2nd edit mode loading loop
Both games are stuck in an infinite loading loop when trying to create new edit data, loading old edit data or when using the juke box inside the diva room. 
This does not happen when selecting one of the three sample edits in F 2nd as this just happens to skip the music selection screen.
Editing and playing these sample edits is fully functional.
This happens on all current releases regardless of hardware.

### PR DESCRIPTION
**Pull request by scribam**
Fix #3276 

Games using cellSearch to test:
- [X] Beat Hazard Ultra
- [X] Hatsune Miku: Project Diva F
- [X] Hatsune Miku : Project Diva F 2nd
- [X] J-Stars Victory VS +
- [X] Kung Fu Rider
- [X] Pain
- [X] Pro Evolution Soccer 2009 DEMO
- [X] Wipeout HD

### CODE REVIEW

**Comment by ikki84** [comment]
Thanks @scribam 

It also fixed https://github.com/RPCS3/rpcs3/issues/2119

j-stars

**Comment by Zangetsu38** [comment]
finnaly fixed this haha

**Comment by AniLeo** [comment]
Lol jstars is finally working haha, no more weird questions

**Comment by scribam** [comment]
Rebased + improvements for some functions.
No regressions expected for JSTARS and Project Diva.

**Comment by digitaldude555** [comment]
screenshot 724

Beat Hazard Ultra also fixed.

**Pull request merged**
