### PR TITLE
SPU: Fix Out Of Memory Error

### PR DESCRIPTION
**Pull request by Nekotekina**
How to test:
1) Get a game which has Out Of Memory error.
2) Make sure SPU ASMJIT is selected, SPU Cache is disabled.

### CODE REVIEW

**Comment by Kravickas** [comment]
ASMJIT Mega with old cache that throw OOM on master
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2980358/RPCS3.log)
obrazek

I will test safe and no cache

**Comment by digitaldude555** [comment]
Kagero Mou Hitori no Princess test, the entire emulator closes ingame...

**Comment by Kravickas** [comment]
GTA V still segfaults

**Comment by Nekotekina** [comment]
I'll take a look at some tomorrow.

**Comment by MsDarkLow** [comment]
Fist of the North Star: Ken's Rage - DEMO

On Master it crashes the emulator with the Out of Memery Error in the log
[RPCS3MasterFOTNS.zip](https://github.com/RPCS3/rpcs3/files/2980979/RPCS3MasterFOTNS.zip)

With this PR it crashes the whole emulator without popping any error
[RPCS3prFOTNS.zip](https://github.com/RPCS3/rpcs3/files/2980981/RPCS3prFOTNS.zip)

**Comment by creeperjedi** [comment]
Tested with Dynasty Warriors: Gundam 3 [BLES01301]
Where an Out Of Memory error would usually occur, the emulator now crashes with this error:
Crash
Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2980992/RPCS3.log)

**Comment by legend800** [comment]
Splatterhouse still has mem error at start of levels with PPU LLVM + ASMJit (stable with PPU Inter. and/or ASM LLVM). Apologies if this PR is not intended to fix this kind of error.

Master:
2019-03-18 18_09_47-Window
[RPCS3 master.zip](https://github.com/RPCS3/rpcs3/files/2981078/RPCS3.master.zip)

PR:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2981079/RPCS3.zip)

**Comment by arcadee1977** [comment]
I test "Musou Orochi 2 Ultimate",the test result is following:

Master [ SPU ASMJIT 、 MEGA(faster than "safe") 、“ spu cache” is disabled ] : 

https://github.com/RPCS3/rpcs3/issues/5723

This PR:

While Out Of Memory error would usually occur, crashes the whole emulator without any error logs

**Comment by arcadee1977** [comment]
> Splatterhouse still has mem error at start of levels with PPU LLVM + ASMJit (stable with PPU Inter. and/or ASM LLVM). Apologies if this PR is not intended to fix this kind of error.
> Master:
> 
> RPCS3 master.zip
> PR:
> RPCS3.zip

This issue is similar with https://github.com/RPCS3/rpcs3/issues/5712 , but this PR maybe is not fixing the problem?

**Comment by Nekotekina** [comment]
Updated my PR.

**Comment by digitaldude555** [comment]
Kagero Mou Hitori no Princess test, Still closes the entire emulator.

**Comment by MsDarkLow** [comment]
Fist of the North Star: Ken's Rage - DEMO still manages to crash the whole emulator after a while.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2989333/RPCS3.zip)

**Comment by Kravickas** [comment]
ye GTA V still segfault too, but it take a little longer 🤷‍♂️

**Comment by creeperjedi** [comment]
Dynasty Warriors: Gundam 3 no longer crashes, though performance is worse than the Interpreters (even the precise one).

Logs:
[Gundam 3.log](https://github.com/RPCS3/rpcs3/files/2990024/Gundam.3.log)
[Gundam 3.log.gz](https://github.com/RPCS3/rpcs3/files/2990026/Gundam.3.log.gz)

**Comment by Emulator-Team-2** [comment]
These games still cause to crash the whole emulator after a while.

1.[ Fist of the North Star 1-Demo NPEB90285 ] 
2.[ Fist of the North Star 2-Demo NPJB90575 ]
3.[ ONE PIECE: PIRATE WARRIORS ] 

Logs:
[RPCS3-1.zip](https://github.com/RPCS3/rpcs3/files/2990170/RPCS3-1.zip)
[RPCS3-2.zip](https://github.com/RPCS3/rpcs3/files/2990172/RPCS3-2.zip)
[RPCS3-3.zip](https://github.com/RPCS3/rpcs3/files/2990173/RPCS3-3.zip)

**Comment by arcadee1977** [comment]
<0.0.6-f89f3943>
Musou Orochi 2 Ultimate：crash the whole emulator after a while，last line of Rpcs3.log:

**W 0:01:00.357857 {SPU[0x2000003] Thread (MainSpursCellSpursKernel3) [0x38430]} JIT: Out of memory (size=0x1218, align=0x10, off=0x0)**

**Comment by arcadee1977** [comment]
<0.0.6-f89f3943>
Sengoku Musou 4 [BLJM61144]：Still crash the whole emulator after a while，last line of Rpcs3.log:
**·W 0:03:12.664086 {SPU[0x2000001] Thread (CellSpursKernel1) [0x32c98]} JIT: Out of memory (size=0x108e0, align=0x10, off=0x0)**

**Comment by Nekotekina** [comment]
Updated, crash should be fixed.

**Comment by digitaldude555** [comment]
Kagero Mou Hitori no Princess test no longer crashes.

**Comment by Emulator-Team-2** [comment]
@Nekotekina 
The crash is now fixed, but performance is still worse than with a SPU interpreter.

eg. in ONE PIECE: PIRATE WARRIORS
SPU ASMJIT spam these unexpected instruction in the log.
`-Unexpected instruction on $SP: SELB(x62)`
`-Unexpected instruction on $SP: A(x4)`
`-Unexpected instruction on $SP: ORI(x3422)`

SPU interpreter doesn't spam this.
Log:
[RPCS3-SPU ASMJIT.zip](https://github.com/RPCS3/rpcs3/files/2993457/RPCS3-SPU.ASMJIT.zip)
[RPCS3-SPU interpreter.zip](https://github.com/RPCS3/rpcs3/files/2993459/RPCS3-SPU.interpreter.zip)

**Comment by Nekotekina** [comment]
The question would be, is it slower than ASMJIT on master?

**Comment by arcadee1977** [comment]
@Nekotekina The crash is fixed! Thanks for your amazing work! But the performance(FPS) decreases when too many NPC on the screen.

**Comment by Emulator-Team-2** [comment]
@Nekotekina 
The performance of SPU ASMJIT is the same as in the Master worse than the SPU interpreter.
So this unexpected instruction doesn't cause this problem in SPU ASMJIT?

**Comment by Kravickas** [comment]
GTA V ''works'' , it freezed 2-3 times down the road +- on same spot but that could cause anything. tho still furthest i have got

**Comment by Nekotekina** [comment]
I assume SPU Debug is disabled as well? Because it can slow down things a lot.

**Comment by Emulator-Team-2** [comment]
@Nekotekina 
SPU debug is disabled.
Maybe you can try `[ Fist of the North Star 2-Demo NPJB90575 ]` to see how it works with spu amsjit.

**Comment by creeperjedi** [comment]
Yes, my tests were done SPU Debug disabled and performance is still poor

**Comment by Hopefullyidontgetbanned** [comment]
doesn't seem to fix elveon unfornately

**Pull request merged**
