### PR TITLE
sceNp/cellGame: Bugfixes

### PR DESCRIPTION
**Pull request by scribam**
- Bound by Flame (BLES01952) now goes ingame with the change in `sceNpDrmVerifyUpgradeLicense2`. I put the same change in `sceNpDrmVerifyUpgradeLicense` for consistency. Tested on DECR.
- Add CELL_GAMEUPDATE_RESULT_STATUS_* enum

### CODE REVIEW

**Comment by scribam** [comment]
Ready for review then, if valid, to go. It should be quick considering the number of changes.
Please let me know if there are any issues.

**Comment by lukantrica** [comment]
hola bueno no hablo ingles pero tengo un problema que me llevo hast aaca resulta que jugando cno el emulador pscr3 kh 2.5 me sale este problema 

F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:88)

  ¿como se arregla?  o si no que me recomiendan hacer? 
también les dejo los datos de mi pc  sist op 64 bites -8 gigas de ram - gtx 730 pentium dual core g630

**Comment by AniLeo** [comment]
Don't spam unrelated PRs, read the repository guidelines and write in English

**Comment by babosha81** [comment]
Verification failed:
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:88)
same error with top spin 4...help please..

**Comment by AniLeo** [comment]
I just said not to spam unrelated PRs. This PR doesn't touch rsx cache.

**Comment by babosha81** [comment]
Verification failed:
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:88)
same error with top spin 4..u know how to solv this problem or not ...if you know please fix it.. if u do not how knows...thanks

**Comment by AniLeo** [comment]
Spam removed. 
Don't use GitHub if you don't know what you're doing, there are forums for a reason.

**Pull request merged**
