### PR TITLE
Ignore texture upload if texture width > pitch

### PR DESCRIPTION
**Pull request by raven02**
fix https://github.com/RPCS3/rpcs3/issues/1628

### CODE REVIEW

**Comment by raven02** [comment]
@vlj / @kd-11 .Correct me if i'm wrong here.

**Comment by kd-11** [comment]
hmm. I'm unsure if the right call is to ignore completely or just clamp the size. vlj should be in a better position to offer insight here.

**Comment by raven02** [comment]
Yep , it is initially pointed out by @vlj when he checked out the Sonic CD issue .

**Comment by paulsapps** [comment]
surely the result of this issue must be another bug causing the wrong dimensions?

**Comment by raven02** [comment]
Yes i think so. Possibly the cellpngdec decode the wrong dimension .

**Pull request merged**
