### PR TITLE
input: implement raw mouse handler

### PR DESCRIPTION
**Pull request by Megamouse**
- Adds a raw mouse handler to the mouse handler selection
- The raw mouse handler can be used as replacement for the basic mouse or as ps move mouse
- As with the existing ps move mouse, the raw ps move mouse only works if the regular mouse handler is set to null
- Currently the raw mouse handler just takes all mice it can find until it reaches the max allowed number (set by the game)
- Mouse acceleration for relative movement is supported, yet not configurable at the moment

TODO:
- [x] Disable for non-windows operating systems
- [x] Configurable mouse acceleration
- [ ] Configurable mice for each index ?

implements #15158

### CODE REVIEW

**Comment by legend800** [comment]
When setting MOVE handler to Raw Mouse, the game doesn't recognize a PS Move is connected. Is that expected right now?

Move Handler = Mouse
2024-02-10 23_32_47-FPS_ 30 01 _ Vulkan _ 0 0 30-e67ebbdb Alpha _ raw_mouse _ The House Of The Dead_

Move Handler = Raw Mouse


2024-02-10 23_37_07-PS3

**Comment by legend800** [comment]
When setting MOVE handler to Raw Mouse, the game doesn't recognize a PS Move is connected. Is that expected right now?

Move Handler = Mouse
2024-02-10 23_32_47-FPS_ 30 01 _ Vulkan _ 0 0 30-e67ebbdb Alpha _ raw_mouse _ The House Of The Dead_

Move Handler = Raw Mouse


2024-02-10 23_37_07-PS3

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14231664/RPCS3.log.gz)

**Comment by Megamouse** [comment]
I forgot to initialize the raw mouse handler properly in the cellGem lib.
Should be working now I hope.

**Comment by Monky-Power** [comment]
Hello,

Sorry in advance for asking this question.
I'm trying to recover this branch to participate in the test, but I'm stuck at the following point:

I don't see the "artifact" zone anywhere
(I will test with the new fix)

Thanks in advance

image
image

**Comment by AniLeo** [comment]
We're not using Cirrus anymore for Windows and Linux builds, those instructions are outdated

**Comment by legend800** [comment]
Thanks, works now but the sys mouse cursor and in-game move cursor are way off. 

Raw mouse:


Mouse:
2024-02-11 10_00_45-FPS_ 30 00 _ Vulkan _ 0 0 30-d1487872 Alpha _ raw_mouse _ The House Of The Dead_

**Comment by Megamouse** [comment]
Added some logging. Maybe it helps to find out why it's offset.

**Comment by legend800** [comment]
New build:

2024-02-11 16_02_20-FPS_ 30 00 _ Vulkan _ 0 0 30-966a7850 Alpha _ raw_mouse _ The House Of The Dead_

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14234491/RPCS3.log.gz)

**Comment by Megamouse** [comment]
well. we're getting relative mouse movement.
Are you sure your driver sends the correct events?

**Comment by Monky-Power** [comment]
> We're not using Cirrus anymore for Windows and Linux builds, those instructions are outdated

Hello,
I'm looking for another solution to test the current build.
Add : Visual Studio 2022
Clone from repository : 
https://github.com/Megamouse/rpcs3.git
Add : Vulkan SDK

and I have 3 errors left to generate the solution.

Add  repertory inlude : ..\3rdparty\llvm\llvm\llvm\include
This did not correct the error


If you know the cause I would like a hand to finish creating the build before starting the tests (even if legend800 has already started well)
thanks in advance

image

**Comment by Megamouse** [comment]
Just download the build ....
https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzk5MjAvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip

**Comment by Monky-Power** [comment]
Hello,

I just tested : 
Game : House of The Dead 4.
Material : 1 mouse + 2 Aimtrak

- The classic mouse has the same behavior as legend800
- **Aimtrak with a raw input function are perfectly accurate and responsive** 

Thanks a lot

**Comment by Monky-Power** [comment]
Improvement 1 : 
"add additional button management"  -> use button code for the "fake" in "raw input"

Because the Aimtrak only has 3 buttons
For Sinden Lightgun this solution must already be perfect

This improvement will allow the keyboard to be used for keys used to navigate and validate, including validation of calibrations


AFTER TODO : 
_Configurable mice for each index ?_


configuration example : 
image

For using an other peripheric for the same "Controller in game"
Add boutton fonction in "Raw Mouse"

image

**Comment by Megamouse** [comment]
Merging this for now, as it works as intended ignoring the configuration part. I'll improve upon it later and maybe add linux support etc.

**Comment by Megamouse** [comment]
ah. actually I'll merge the rockband pr first, since I don't want to create conflicts again.

**Comment by legend800** [comment]
So it's fine if standard mouse is misaligned with the move cursor when using rawinput? 

I use a wiimote with dolphinbar and it's unusable. Same if I have two dolphinbars connected which is how I get multiple mice to work on raw input supported games / emulators.

**Comment by Megamouse** [comment]
The ps move is not supposed to be used with relative input.
The relative input is only there for completeness sake, since this can also be used for cellMouse.

**Comment by Megamouse** [comment]
It seems like dolphinbar specifically sets relative input for some reason.
Maybe it can be configured in their software.

**Comment by Megamouse** [comment]
btw, your screenshots are kinda useless, since they do not convey the movement. A gif would make more sense.

**Comment by legend800** [comment]
There no software\ui for it. It's just plug and play. Works perfectly in various arcade emus and PC games.

Basically here, the cursor is always misaligned by the same angle\amount. If it started aligned ON the mouse cursor from launch, it would be perfect (just like if I use just "Mouse").  I feel like if you can correct that, we should be set.

**Comment by Megamouse** [comment]
Oh. I understand. Why not say that before xD

**Comment by Megamouse** [comment]
is it always the exact same position?

**Comment by legend800** [comment]
I have to check when home in a few hours but I believe it's always off to the top left upon launch. 

Get those aligned form the start and then you should have great compatibility here.

**Comment by Monky-Power** [comment]
Thank you Megamouse.
Already very happy that the raw input could be created.

I tested several and only the check movement in House Of The Dead 4 did not work.

I'll leave the note for later when you can come back to it

Improvement 2 : 
Find the check command expected by House Of The Dead 4 to create an Input
No idea how difficult this research is.

I am available to test the behavior with AIMTRAK on future developments.

and good legend800 test with the wiimote

**Comment by Megamouse** [comment]
It's most likely some combination of two mouse buttons.

**Comment by legend800** [comment]
Works great in fullscreen, windowed it's just off but you mentioned this already -- "auto-adjustments on window resize in the next PR."

Here's a shot of my mouse and wiimote controlling separate ps moves in HOTD Overkill. Interested to see what happens in-game - can't get past cali screen atm(cellgem thing?).

2024-02-13 17_09_55-FPS_ 30 00 _ Vulkan _ 0 0 30-5c8673f6 Alpha _ raw_mouse _ The House Of The Dead_

Anyway, great to see rawinput support. Really opens up multiplayer PS Move support. Big milestone with this. Please try to keep chipping away at it. Not sure how many other input gurus are on the team so our PS Move improvements might be solely in your hands. :)

For those interested in Move games, here's the current hard-coded imput:
o	Left click: T
o	Right click: ~/Move button
o	Back: Circle
o	Left + Middle click (or 7): Start
o	Middle + Right click (or 8): Triangle
o	Middle click: X 
o	Forward: Square
o	Left + Right click (or button 6): Select

**Comment by gustavoalara** [comment]
Hi to all

I did some test:

Time Crisis Razing Storm\Time Crisis 4\Deadstorm Pirates work perfect with  two players lightguns using the new raw input feature

Dead Space Extraction\Resident Evil Darkside\Umbrella Chronicles don't appear to use the new raw input feature and all the mouses\lightguns move the player one crosshair and the second player is moved by a defined gamepad

The Shoot, the same as Dead Space but I can't pass the screen after calibration (I can't shoot over the Accept button)

Rambo The videogame, it looks like the game doesn't accept PS moves (at least in RPCS3)

**Comment by nadenislamarre** [comment]
> Merging this for now, as it works as intended ignoring the configuration part. I'll improve upon it later and maybe add linux support etc.

raw mouse handler that support multigun is evtest which is already implemented in the evdev_gun_handler.cpp
what else do you think ?

**Comment by carolis15** [comment]
> Hi to all
> 
> I did some test:
> 
> Time Crisis Razing Storm\Time Crisis 4\Deadstorm Pirates work perfect with two players lightguns using the new raw input feature
> 
> Dead Space Extraction\Resident Evil Darkside\Umbrella Chronicles don't appear to use the new raw input feature and all the mouses\lightguns move the player one crosshair and the second player is moved by a defined gamepad
> 
> The Shoot, the same as Dead Space but I can't pass the screen after calibration (I can't shoot over the Accept button)
> 
> Rambo The videogame, it looks like the game doesn't accept PS moves (at least in RPCS3)

How did you manage to get DSP, RZ and TC4 to work? The only one I managed to get working is HOTD4. Unfortunately it is unplayable without the shake function.

**Pull request merged**
