### PR TITLE
Implement simd_builder for x86

### PR DESCRIPTION
**Pull request by Nekotekina**
Trying to de-duplicate code in buffer utilities and bring more AVX2/AVX-512 optimizations in.

### CODE REVIEW

**Comment by AhayriSG** [comment]
RPCS3 12557 regression
RPCS3 12557 regression2
RPCS3 12557 regression3

**Comment by Nekotekina** [comment]
Fixed bugs, needs test.

**Comment by MSuih** [comment]
Infamous renders most of the world in black with this PR.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9437785/RPCS3.log.gz)
BCUS98119_screenshot_2022_08_27_13_43_08
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9437785/RPCS3.log.gz)

It shows in a rsx capture as well, just remove the extra .zip from end of the filename to open this split archive.
[BCUS98119_20220827134331_capture.7z.002.zip](https://github.com/RPCS3/rpcs3/files/9437794/BCUS98119_20220827134331_capture.7z.002.zip)
[BCUS98119_20220827134331_capture.7z.001.zip](https://github.com/RPCS3/rpcs3/files/9437795/BCUS98119_20220827134331_capture.7z.001.zip)

**Comment by Darkhost1999** [comment]
PR
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9437987/RPCS3.log.gz)
Master
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9437989/RPCS3.log.gz)
Because the dragon logo is missing I can't see if red screen is fixed. I doubt red graphics will get fixed in this pr but I hope connections can be found.

**Comment by Darkhost1999** [comment]
PPU interpreter still perfect
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9438041/RPCS3.log.gz)

**Comment by AhayriSG** [comment]
no need PPU Interpreter for Skyrim actually.
@Darkhost1999 https://github.com/RPCS3/rpcs3/issues/9183#issuecomment-1186621218

**Comment by Darkhost1999** [comment]
@AhayriSG Do you have any DLC installed?
Because it only happens when dlc is installed

**Comment by AhayriSG** [comment]
> Because it only happens when dlc is installed
oh ok didn't know that, my bad.

**Comment by Nekotekina** [comment]
Needs retest.

**Comment by MSuih** [comment]
The issue I reported has been solved. The previous build had some issues with missing geometry and vertex explosions in other games too but those have all been solved now. I can't find any issues to report on the games that I have access to.

**Comment by Darkhost1999** [comment]
Dragon logo has returned. Still red. But same as master

**Pull request merged**
