### PR TITLE
Qt: Speed up Log Viewer

### LINKED ISSUE #10149: The log viewer can't catch a break - literally
The log viewer completely hangs the UI thread for a good half a minute on any kind of resize, the initial render, on changing DPI, etc.., so basically, on any repaint. It's pretty unfun to use, not that I know any reason why anyone would ever want to use it to begin with.

version: any
platform: wendy's

### PR DESCRIPTION
**Pull request by Megamouse**
fixes #10149

### CODE REVIEW

**Comment by dio-gh** [comment]
Based and redpilled, works as advertised. Could you add a sideways scrollbar while at it?

**Comment by Megamouse** [comment]
There already is a horizontal scrollbar ...

image

**Comment by dio-gh** [comment]
literally where
image

**Comment by Megamouse** [comment]
Looks like your style is fucked.
It has a regular horizontal scrollbar as any other Textedit

**Comment by dio-gh** [comment]
or is it the stylesheet cucking me again?

**Comment by dio-gh** [comment]
smegged
image

ill fix it sometimes i guess, false alarm then

**Pull request merged**
