### PR TITLE
SPU LLVM: fix bug for AMD FX processors

### PR DESCRIPTION
**Pull request by Nekotekina**
Check #13736

### CODE REVIEW

**Comment by Augusto7743** [comment]
Thanks for doing an fix =)
Where is the Linux build link for PR 13738 ?
I need wait to be added in https://rpcs3.net/compatibility?b ?

**Comment by Nekotekina** [comment]
https://cirrus-ci.com/task/5949662109106176 artifacts here

**Comment by solarmystic** [comment]
Tested and compared with current 14921 master on the usual 12700KF/2080TI system. 

**GOW 3 - Identical average, better 1% FPS.**
Master (14921) - 130/89/68 FPS
This PR (96dd32d0) - 130/95/69 FPS

**GOWA - Identical average, minor gain in 0.1% FPS.**
Master (14921) - 66/56/51 FPS
This PR (96dd32d0) - 66/57/54 FPS

**The Last of Us - Identical average, minor gain in 1% and 0.1% FPS** 
Master (14921) - 51/46/41 FPS
This PR (96dd32d0) - 51/48/43 FPS

**Persona 5 - Within margin of error for average and 1% FPS, minor gain in 0.1% FPS.**
Master (14921) -  88/64/55 FPS
This PR (96dd32d0) - 89/63/58 FPS

**Demon's Souls - Within margin of error for all metrics.**
Master (14921) - 106/88/80 FPS
This PR (96dd32d0) - 106/87/81 FPS

SS with all results:-
[921 vs FX LLVM.zip](https://github.com/RPCS3/rpcs3/files/11303875/921.vs.FX.LLVM.zip)

**Comment by AniLeo** [comment]
Verified as fixed on my FX-8350

**Pull request merged**
