### PR TITLE
Add a new "Darker" theme

### PR DESCRIPTION
**Pull request by Darkhost1999**
My first PR
Totally stole from https://github.com/RPCS3/rpcs3/pull/11585 and customized.
This white text on a Grey box is the only thing I don't like from the theme using this daily since April 9th 2022.
I want the box black like all the others
unknown

Now to showoff

Screenshot 2022-04-25 113157
<details>
<summary>Show off</summary>

Screenshot 2022-04-25 113751
Screenshot 2022-04-25 113859
Screenshot 2022-04-25 113919
unknown
Screenshot 2022-04-25 113240
Screenshot 2022-04-25 113258
##### Below you can see thicc borders. Well that issue is persistent across every theme
Screenshot 2022-04-25 113310
Screenshot 2022-04-25 113701

</details>

### CODE REVIEW

**Comment by AniLeo** [comment]
I don't usually comment on design choices but what the hell is this...

image

**Comment by Darkhost1999** [comment]
> I don't usually comment on design choices but what the hell is this...

Disabled boxes

**Comment by Satan86** [comment]
I like having the option of a proper black theme, but the red bits are pretty bad. I made some changes so it's grey instead and it looks better 
unknown

**Comment by Darkhost1999** [comment]
The biggest inspiration for color choices was here

I even saw the red and I think I just plugged it into https://www.colorhexa.com/ picked like a single shade darker maybe or just put it straight into the qss.
In truth I probably hated the guarana entirely and went custom.

The idea was I wanted to draw attention to the box being disabled. That it's not too poppy but very much so present as a halt, stop, and "you can click all you want this isn't going to do anything.
I wanted consistency. So as not just the checkboxes were red when disabled but everything disabled was all consistent no variations or changes.
With grey I kinda agree it looks better but it also just holds too much consistency to the entire theme it doesn't communicate "stop" so people will ask "why doesn't this work? It looks like everything else it should work."

So all I'm seeing here is the color choice I made is fine because it's a custom theme but I should probably darken it?
And that instead of 000000 I should consider 0D0D0D / R13 G13 B13

**Comment by RedDevilus** [comment]
Ah I've used that website before. But yeah just dial it a bit back down on the luminosity.

**Comment by Darkhost1999** [comment]
It does look better.
image
FF0000 vs a80000

**Comment by Darkhost1999** [comment]
Any darker than 8f0000 loses the intent on the color red and starts looking maroon

**Comment by Darkhost1999** [comment]
It is probably 100% extremely evident that I'm learning. And this PR is just bad.
It isn't even that good a theme anyways. And I can do better. So I'm gonna do better. Trash this and rebuild.

**Pull request closed without merging**
