### PR TITLE
Fix sys_memory_free

### LINKED ISSUE #5030: Regression: Medal of Honor [BLES01067] doesn't load (#4975)
Medal of Honor [BLES01067] doesn't load and shows error window.
[Medal_of_Honor.zip](https://github.com/RPCS3/rpcs3/files/2318899/Medal_of_Honor.zip)
https://github.com/RPCS3/rpcs3/pull/4953:
medal_of_honor_ 7182
https://github.com/RPCS3/rpcs3/pull/4975:
medal_of_honor_ 7186

### PR DESCRIPTION
**Pull request by elad335**
fixes #5030

### CODE REVIEW

**Comment by Asinin3** [comment]
Confirmed, fixes DREAM C CLUB ZERO Special Edipyon! [BLJS10208]
elad_2018-09-02_2410

**Comment by joshuacode751** [comment]
Hello, with the latest build i got this new problem. previous release don't have this problem.
capture

**Comment by spyropt** [comment]
That's another regression from this pr #4871 
This regression is fixed

**Comment by Atrosincity** [comment]
This or the changes before fixed soul calibur V Us, its now fully playable, with minor shaders missing, for exemple in creation mode, when one change hair color, game, doesnt reflect changes.[
rpcs3 soulcaliburv
](url)

**Pull request merged**
