### PR TITLE
SPU: minor fixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Illynir** [comment]
No difference for me. All the "tales of" have regressed. Tales of vesperia has infinite loading with access violation. Edge of eternity/Resonance of fate regressed of Intro to Nothing also.

On i5 4670K.

**Comment by Zangetsu38** [comment]
same,, tested on game have regressed, not change, just fatal error for Sport champion have changed
F {SPU[0x2000005] Thread (MSTREAMCellSpursKernel0)} MEM: Access violation writing location 0x0

**Comment by Asinin3** [comment]
Uncharted 1, Infamous 1/2, WipEout HD, The Last of Us and all other found regressions with non-tsx CPU's seems fixed now af of newest updated commit.

**Comment by Rpcs3tester** [comment]
@Nekotekina  thanks , all previous games that hangs now works ok

siren

heavenly sword

gow 2

**Comment by NPJB00512** [comment]
Gundam EXVSFB can play to FPS 25

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1888091/RPCS3.log.gz)

**Comment by Charmareian** [comment]
Hyperdimension Neptunia Mk2 fixed with this commit with added map in the top right corner.

untitled

**Pull request merged**
