### PR TITLE
fs/linux: fix potential copy_file issue

### PR DESCRIPTION
**Pull request by Megamouse**
sendfile/sendfile64 is meant to be run in a loop, since there is no guarantee that a single call copies all the data.
The current implementation may lead to corrupt files on linux.

### CODE REVIEW

**Comment by elad335** [comment]
maybe sendfile indeed needs a loop but sendfile64 does not? I don't find any information the limitation of sendfile64.

**Comment by Nekotekina** [comment]
Maybe there is no need to use sendfile64, actually, it seems Linux-specific

**Comment by Megamouse** [comment]
you mean because of this?
"The glibc sendfile() wrapper function transparently deals with the kernel differences."

**Comment by Nekotekina** [comment]
I think so, yes

**Pull request merged**
