### PR TITLE
Alternative implementation for memory mirror support for reservations

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by elad335** [comment]
Non-tsx doesnt work with it..

**Comment by Nekotekina** [comment]
Fixed hopefully.

**Comment by Kravickas** [comment]
After pressing STOP button 
obrazek
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4003311/RPCS3.log)

**Comment by elad335** [comment]
Here's my complete list of pros and cons of #7136 comparing to this pr.

## #7136:

#### pros:
- Memory usage is very lightweight, allocates exactly the amount of reservations data needed per allocations.
    16 times as compressed as vm memory, which means a 256MB vm allocation will only allocate 16MB of reservation data.
- vm Allocations performance doesn't take a hit, uses the same amount of memory allocations as current master.
#### cons:
- Requires modifying existing code to use tags instead of addresses.
- Adds an additional tag argument for ASMJIT TSX functions which may limit (make it harder to add) additional arguments in the future.

## This pr:
#### pros:
- Does not require modifying existing code much.
- May be easier to use and more intuative to read. Only exception is non-tsx code which the opposite may be true.
#### cons:
- Memory usage is very inefficient, allocates the same amount of reservation memory as vm memory.
Which means a 256MB vm allocation needs an additional 256MB for reservation data.
- vm Allocations are more expensive, uses an additional 2 allocations as current master plus an additional deallocation.
- May introduce incompatibilities with existing reservations waiters due to the underlying pointer address being different.

**Comment by elad335** [comment]
it also has page faults notifications bug with non-tsx mentioned in #7136

**Comment by Megamouse** [comment]
REBASe

**Pull request closed without merging**
