### PR TITLE
vk/gl: Add some more blend ops for vulkan; fix immutable storage for opengl

### PR DESCRIPTION
**Pull request by kd-11**
Add min and max blend ops that were missing (Steins Gate)

### CODE REVIEW

**Comment by tambry** [comment]
It would be nice if you tried keeping more commits in one PR - would be easier to merge.

**Comment by kd-11** [comment]
@tambry I'll keep that in mind next time. I can see how it can be problematic sometimes.

**Comment by kd-11** [comment]
Added a commit to properly initialize opengl textures. Immutable textures cannot be re-declared with glTexStorage2D once they have been set the first time.

**Comment by tambry** [comment]
Needs rebase.

**Comment by kd-11** [comment]
rebased

**Comment by tambry** [comment]
Needs rebase.

**Comment by vlj** [comment]
Need rebase

**Pull request merged**
