### PR TITLE
Remove Vita emulation

### PR DESCRIPTION
**Pull request by Nekotekina**
RIP

### CODE REVIEW

**Comment by clienthax** [comment]
F

**Comment by Nekotekina** [comment]
We will have faster compilation with a lot of files removed.
There was a proposal to move them to another repository, but it can be done any time afterwards.

**Comment by petmac** [comment]
Hello,

Anyone interested in PS Vita emulation is most welcome to contribute to [Vita3K](https://github.com/Vita3K/Vita3K/). It is very early though, only some homebrew apps run.

Thanks,
Peter

**Comment by AniLeo** [comment]
Respecc

https://www.youtube.com/watch?v=owB3u1At5hw

**Comment by yoshi314** [comment]
why was it in rpcs3 in the first place?

**Comment by MSuih** [comment]
@yoshi314  I think it was because of Cross-Play, getting two different emulators to work nicely together sounds like a major headache. Also Vita and PS3 share some code on software side even though they're running on different hardware.

**Pull request merged**
