### PR TITLE
SPU LLVM: improve performance in some situations

### PR DESCRIPTION
**Pull request by Nekotekina**
For example, before (with accurate xfloat):

Screenshot from 2019-04-25 13-33-19

After:

Screenshot from 2019-04-25 13-35-25

### CODE REVIEW

**Comment by jade010** [comment]
Regression on  [BCES01893] Gran Turismo 6 using SPU LLVM

unknown

LOG:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3116750/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
Updated, you may try if the crash is gone.

**Comment by jade010** [comment]
Working fine now!

**Comment by proganime1200** [comment]
image

**Comment by proganime1200** [comment]
testing <3

**Comment by legend800** [comment]
Nice speed boost in several tested games. Need to do some more testing but some games appear to perform worse (Motorstorm Apoc. , Time Crisis 4). 

Captain America - 20>24 in slow areas
2019-04-25 08_37_49-Window

Wipeout HD - 45-50 in slow areas
2019-04-25 08_42_26-Window

Emu hangs a lot not when close game window, not sure if related.

**Comment by Asinin3** [comment]
I saw no performance gain in Persona 5, WipEout HD and Sly Cooper Thieves in Time.

**Comment by MsDarkLow** [comment]
I tested the sample you provided in 3 different spots (Zoomed in twice and Default).
i7-8700k @4.7GHz
<details>
<summary>Pictures Spot for reference</summary>

1 - Zoomed in

2 - Default

3 - Zoomed in

</details>

We get double the performance in many occasions when using accurate xfloat compared to how currently is in master.
These are the fps I got for each spot.
M: 
1 - 7.81
2 - 27.56
3 - 10.93
PR: 
1 - 15.05
2 - 45.54
3 - 20.56

However when without xfloat, I noticed a drop in fps in the 2nd spot, the other spots seem to be within margin of error.
M: 
1 - 19.16 
2 - 66.50 
3 - 28.55
PR: 
1 - 20.39 
2 - 59.68 
3 - 29.51

**Comment by proganime1200** [comment]
tried to use this on persona see minor performance boost on some places with SPU LLVM and Approximate xfloat before : 13 fps after 18fps

**Comment by kirbyguy22** [comment]
Gran Turismo 6 1.05 [BCUS98296]
i7-9700K @ 4.9GHz

- Force CPU Blit is enabled
- FPS averages were recorded in Time Trials using the Subaru BRZ GT300 in the roof camera
<table>
  <tr>
    <th>﻿</th>
    <th colspan="2">Accurate xfloat</th>
    <th colspan="2">Approx. xfloat</th>
  </tr>
  <tr>
    <td><b>Track</b></td>
    <td><b>Master</b></td>
    <td><b>PR</b></td>
    <td><b>Master</b></td>
    <td><b>PR</b></td>
  </tr>
  <tr>
    <td>Bathurst</td>
    <td>32</td>
    <td>36</td>
    <td>38</td>
    <td>37</td>
  </tr>
  <tr>
    <td>Matterhorn</td>
    <td>33</td>
    <td>36</td>
    <td>40</td>
    <td>39</td>
  </tr>
</table>

Noticeable improvement (~10%) using accurate xfloat, but no improvement at all when it is off. I will add more tracks as I test.

**Comment by arcadee1977** [comment]
Ninja gaiden sigma 2  improvement 51FPS-->58FPS (non accurate xfloat)

**Comment by psennermann** [comment]
I see almost a 10% speed gain with the game Journey (from 12,5 to 13,5 fps - non accurate xfloat)

Win10, i7 7700, gtx1060

**Comment by Aurez** [comment]
The House of the Dead 4 doesn't boot anymore with this PR

**Comment by legend800** [comment]
Confirmed. HOTD4 hangs on boot. 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3124015/RPCS3.zip)

**Comment by incognitoh** [comment]
Pretty sure this PR breaks Wangan Midnight (BLJM60028) when using SPU LLVM. Now it just freezes right before the start menu every time. Master worked fine until this PR was merged. Hopefully others can test it and confirm.

**Comment by Muramas** [comment]
I have noticed a huge stability improvement in P5 but I don't know if it is from #5895 or this. Keep up the good work

**Comment by jobs-git** [comment]
Huge performance improvement in Diablo 3. From 29fps to 38fps in Stronghold area! Other places its always 60fps!

**Pull request merged**
