### PR TITLE
Update to LLVM 16.0.1

### PR DESCRIPTION
**Pull request by Nekotekina**
Also fix AVX-512 detection bug for Zen4+.

### CODE REVIEW

**Comment by Asinin3** [comment]
Zen4 users please test performance against master. 16.0.1 brings Zen4 optimisations

**Comment by Megamouse** [comment]
Missing commit update of the submodule

**Comment by solarmystic** [comment]
Retested GOWA, GOW3 and P5 with this PR to see if it would make a difference to the minor performance regression in those games compared to the pre-LLVM16 master, unfortunately it does not.

**GOW3**

Last Master before LLVM16 (14845) - 130/103/70 FPS
PR build  - 123/101/68 FPS

**GOWA**

Last Master before LLVM16 (14845)  - 64/55/50 FPS
PR build  - 61/55/50 FPS

**P5**

Last Master before LLVM16 (14845)  - 97/71/60 FPS
PR build  - 92/65/59 FPS

Zip archive with SS of results:-
[LLVM 16.01.zip](https://github.com/RPCS3/rpcs3/files/11190961/LLVM.16.01.zip)

Tested on a stock i7 12700KF/2080Ti/W10 21H2 machine.

**Comment by Nekotekina** [comment]
@solarmystic please retest

**Comment by solarmystic** [comment]
> @solarmystic please retest

Whatever you did with that latest commit, it worked wonders.

Performance is back to pre-LLVM 16 master levels with GOWA, and almost there with GOW3. P5 is still slower, but got a performance improvement from it.

*GOW3**

Last Master before LLVM16 (14845) - 130/103/70 FPS
Current PR build  - 129/102/69 FPS

**GOWA**

Last Master before LLVM16 (14845)  - 64/55/50 FPS
PR build  - 65/57/52 FPS

**P5**

Last Master before LLVM16 (14845)  - 97/71/60 FPS
PR build  - 93/67/62 FPS

zip with SS of current PR results:- 
[v2.zip](https://github.com/RPCS3/rpcs3/files/11192410/v2.zip)

**Pull request merged**
