### PR TITLE
Update llvm tests to work with new llvm jit and tabify whole thing

### PR DESCRIPTION
**Pull request by danilaml**
Some test had to be commented out because they know cause crash/unhandled exception.
Also had to move `CustomSectionMemoryManager` into .h because it's also needed by tests (since we create `FunctionPassManager` every time now).

### CODE REVIEW

**Comment by tambry** [comment]
@danilaml Also, does Arkedo Swap now work? Since for me Arkedo Swap crashes with LLVM recompiler on master at https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Cell/PPULLVMRecompiler.cpp#L707 with an access violation.

**Comment by danilaml** [comment]
@tambry I only touched tests in this PR. And did some moving around in recompiler. It shouldn't have fixed (or broke) anything apart from tests.
But as you can see here https://github.com/danilaml/rpcs3/blob/llvm3.6-tests/rpcs3/Emu/Cell/PPULLVMRecompilerTests.cpp#L499 I already found some instructions that cause crash/don't work with new recomp. using these tests.

**Comment by tambry** [comment]
@danilaml Ok, thank you. I might just look into them and see which of them is at fault in the future.

**Comment by danilaml** [comment]
@tambry also there some tests (not whole instructions) which cause unhandled exception in rpcs3 ([e.g.](https://github.com/danilaml/rpcs3/blob/llvm3.6-tests/rpcs3/Emu/Cell/PPULLVMRecompilerTests.cpp#L915)). And it wasn't the case before I rebased it on top of latest @Nekotekina merge.

**Comment by vlj** [comment]
When this PR is merged I will rebase and submit mine, it has this commit :
https://github.com/vlj/rpcs3/commit/dfd6e73461ca8bdabdcab1fa40f76198e39082f3
which should fix some crash in Sonic CD (which happens because a module is freed while the code is being executed).

**Comment by Nekotekina** [comment]
Merged.

**Pull request closed without merging**
