### PR TITLE
Windows: Tidy up and unify to_wchar/to_utf8 functions

### PR DESCRIPTION
**Pull request by CookiePLMonster**
This PR is a rewrite of two tiny, yet frequently used Windows functions - `to_wchar` and `to_utf8`. This rewrite results in:

1) Unification of both function definitions - previously, `to_wchar` returned a `std::unique_ptr<wchar_t[]>` (!?) and `to_utf8` filled a `std::string&` parameter - now, they both take a `string_view`/`wstring_view` and return `wstring`/`string`.
2) Using `(w)string_view` instead of `(w)string` and/or plain array pointer allows for compile time string length computation wherever possible and does away with any reliance on a null terminator.
3) Previously both function would overallocate what they considered a "safe" maximum length and performed conversion. This resulted in plenty of `+1`/`-1` math and I think could even fail in an extreme edge case - I'm convinced a case where n `wchar`'s would be converted into 3n `char`'s could write one byte too much, potentially breaking string's internal structure.
Now no overallocation takes place - instead, character conversion functions are called twice - first time to determine a buffer size, second time to actually fill it. This matches the intended way of using those WinAPI character conversion functions and makes it completely bullet proof (essentially no edge cases exist).

### CODE REVIEW

**Comment by Nekotekina** [comment]
Overallocation is proven safe. There is no edge case because std::string guarantees additional char for zero past the end of string. And writing zero to that position is well-defined. I don't see the point in calling the routine twice.

**Comment by Nekotekina** [comment]
Also there is no point in using wstring insdead of wchar_t[] array, this is exceptional case where it fits its purpose just fine.

**Comment by CookiePLMonster** [comment]
> Overallocation is proven safe.

It relies on an assumption that no single wchar is expanded to a 4 byte UTF-8 char - I don't know if this is guaranteed or not, but if there is even a single character like this, that assumption breaks.


> There is no edge case because std::string guarantees additional char for zero past the end of string. And writing zero to that position is well-defined

Indeed, I cross referenced against the docs now and it's safe, but it is still somewhat pointless because it's so easily prevented.


> I don't see the point in calling the routine twice.

While I admit it feels clunky, it's an intended way of using those character conversion functions.


> Also there is no point in using wstring insdead of wchar_t[] array, this is exceptional case where it fits its purpose just fine.

It does, and so does wstring which also results in completely unified API between those two. Performance/memory usage should be equivalent, but readability improves.

**Comment by Nekotekina** [comment]
Closing as not valuable and pursuing mostly non-goals.
Although I can agree with some, like returning std::string, it can be left as is.

**Pull request closed without merging**
