### PR TITLE
qt: rewrite syntax highlighter

### PR DESCRIPTION
**Pull request by scribam**
- fix multi-line comments
- remove compilation warnings "unknown escape sequence"
- fewer lines of code (-155)

### CODE REVIEW

**Comment by Megamouse** [comment]
This broke everything

**Comment by scribam** [comment]
Please explain

**Comment by Megamouse** [comment]
Compare asm highlighting with master

**Comment by Megamouse** [comment]
Also. What was even broken in multi line comments

**Comment by Megamouse** [comment]
Just out of interest. What was the fix for the warnings

**Comment by Megamouse** [comment]
to be honest all i can see is the removal of all of the details that were necessary for this to be working as i intended. The new code is actually the code I started with when I implemented the hgihlighter

**Comment by Megamouse** [comment]
I think what broke are the capture groups

**Comment by scribam** [comment]
Try #4745 and let me know if there is still an issue

**Pull request merged**
