### PR TITLE
Add resolution for 4 k and 2k monitor

### PR DESCRIPTION
**Pull request by Zangetsu38**
Tested and perfectly works

### CODE REVIEW

**Comment by danilaml** [comment]
But does ps3 support these resolutions? I thought this was for CELL/ps3 internal resolution.

**Comment by Zangetsu38** [comment]
@danilaml No, of course not, the goal is just to make an Upscale 1080> 2k and 4k

**Comment by Bigpet** [comment]
Ok, but then why would you add it to the constants used by the ps3 client system that's being emulated? This really doesn't make any sense to me

**Comment by danilaml** [comment]
It should probably be done somewhere else. (I don't know if concept of Internal Resolution is implemented somewhere in rpcs3).

**Comment by Zangetsu38** [comment]
@Bigpet What I wanted to do is to do as the other emulator, the games thus launches in the highest supported resolution 1080 or 720 depending on the .sfo.
But the emulator displays it in a window, or even screen 4K or 2K, as selected and the screen of the user.
eg : Dolphin select Resolution full screen
capture d ecran 2015-05-29 15 52 55
other eg : pcsx2 Select résolution fenêtre 
capture d ecran 2015-05-29 15 54 19

**Comment by O1L** [comment]
Next stupid commit from Dante? Stop it, please.

**Comment by Zangetsu38** [comment]
@O1L euu, it is not stupid.
All emulator posibility for that.

**Comment by O1L** [comment]
Why do you do what you know absolutely nothing? Stop it.

**Comment by Bigpet** [comment]
@O1L yo, I deleted your comments, please stay respectful when criticizing other people. Criticism is fine, insulting is not.

**Comment by danilaml** [comment]
In other emulators there are 2 separate things : emu window resolution and internal resolution (at which rendering of the game happens). I'm not sure if rpcs3 had the first and not simply creates window same size as game tells it.

**Comment by Zangetsu38** [comment]
@danilaml I know, I have not said to want to change the resolution of the PS3, even if one can in pcsx2 and dolphin example:
capture d ecran 2015-05-29 18 23 41
capture d ecran 2015-05-29 18 24 08

**Comment by ADormant** [comment]
@Zangetsu38 This may be helpful https://www.reddit.com/r/emulation/comments/3y8d8k/how_would_internal_resolution_scaling_work_with/

**Comment by tambry** [comment]
@ADormant [There's already and issue for it](https://github.com/RPCS3/rpcs3/issues/181).
An higher internal resolution is probably still ways off.

**Pull request closed without merging**
