### PR TITLE
[msbuild] Minor refactor + VulkanSDK 1.2.135.0+ build fix

### PR DESCRIPTION
**Pull request by ZeeWanderer**
- cmake cmd line extracted to a variable in spirv and glslang msbuild projects
 - decreased VULKAN_SDK lib dir priority to avoid linking provided libs instead of rpcs3-built ones because VulkanSDK 1.2.135.0+ now comes with
```
glslang.lib
HLSL.lib
OGLCompiler.lib
OSDependent.lib
shaderc.lib
shaderc_combined.lib
shaderc_shared.lib
shaderc_util.lib
SPIRV.lib
spirv-cross-c.lib
spirv-cross-core.lib
spirv-cross-cpp.lib
spirv-cross-c-shared.lib
spirv-cross-glsl.lib
spirv-cross-hlsl.lib
spirv-cross-msl.lib
spirv-cross-reflect.lib
spirv-cross-util.lib
SPIRV-Tools.lib
SPIRV-Tools-link.lib
SPIRV-Tools-opt.lib
SPIRV-Tools-reduce.lib
SPIRV-Tools-shared.lib
SPVRemapper.lib
VkLayer_utils.lib
vulkan-1.lib
```

### CODE REVIEW

**Comment by AniLeo** [comment]
Better to update SDK version used in CI too

**Comment by ZeeWanderer** [comment]
This change just allows to build with 1.2.135.0 sdk version and should not cause problems for older versions. But sure.

**Comment by JohnHolmesII** [comment]
You would need to pr the number to here:
https://github.com/hcorion/rpcs3-docker/blob/master/xenial/Dockerfile#L47

**Comment by ZeeWanderer** [comment]
@kd-11 spiv-opt and glslang libs provided by VulkanSDK use MD runtime which is strange since vulkan-1 is statically linked to runtime. Runtime mismatch error is the reason i noticed the wrong linkage in the first place.

**Comment by kd-11** [comment]
Ok, then, I suppose current setup will do.

**Pull request merged**
