### PR TITLE
PPU LLVM improvements

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Nekotekina** [comment]
Tentative cache version bump. Implemented `fpcast` in LLVM DSL.
Rewritten instructions:
- VMHADDSHS
- VMHRADDSHS

Not recommended for testing, but if someone finds early regressions it will be helpful.

**Comment by Nekotekina** [comment]
Wrote minor optimization on LLVM side, can't push yet. 
image

**Comment by Nekotekina** [comment]
Rewritten instructions:
- VPKSHSS
- VPKSHUS
- VPKSWSS
- VPKSWUS
On AVX2 targets, they now more or less clearly turn into 4 corresponding x86 instructions. On AVX-512 some inefficient code is generated, need to investigate from LLVM side.

**Comment by Nekotekina** [comment]
The next 4 instructions for unsigned words are even more weird even though they look simple. Produced code is inconsistent mess, haven't found a good pattern yet.

**Comment by Nekotekina** [comment]
Rewritten instructions:

- VPKUHUM
- VPKUHUS
- VPKUWUM
- VPKUWUS

**Comment by Nekotekina** [comment]
Still exploring bottomless hole of PMADDWD missing optimizations.

**Comment by Nekotekina** [comment]
Rewritten instructions:
- VSUMSWS
- VSUM2SWS
- VSUM4SBS
- VSUM4SHS
- VSUM4UBS

Most vector instructions are rewritten now. Instructions mentioned as rewritten used to generate some really poor code before. Also added SAT flag optimization (only module-wide yet) which allows to skip code which was redundantly flagging saturation.

**Comment by Yahfz** [comment]
Lost about 30fps in god of war 3 with this PR. Not sure what commit caused this or if the log alone helps so let me know if you need anything else
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7612138/RPCS3.log)

**Comment by Nekotekina** [comment]
Okay, I'll merge without latest commit, it's taking too long otherwise.

**Comment by Asinin3** [comment]
2FPS improvement in Killzone 3
GoW 3 gave same FPS
2 FPS improvement in Persona 5 Central Street (Was same fps at School Hallways)
NieR seemingly lost performance, but this was at an area with ~160fps.
image
image

**Pull request merged**
