### PR TITLE
gl: Enable texture and render target caching for OpenGL

### PR DESCRIPTION
**Pull request by kd-11**
I'm proposing this as a caching implementation for OpenGL. I completely avoid reading/writing any data through the CPU by forcing the GPU itself to make backup copies of the render target results using ARB_copy_image. I've been using this for a long time and it works correctly for my small collection of games. Performance is usually 80-100% of DX12. The implementation could be merged in with other proposals if desired, but it is necessary to have OpenGL backend usable.

### CODE REVIEW

**Comment by kd-11** [comment]
If testing, please also apply https://github.com/RPCS3/rpcs3/pull/1500 to fix slowdowns and stutters due to GPU sync.

**Comment by vlj** [comment]
I suggested a similar change but apparently DHrpcs3 already have an implementation for texture and surface cache https://github.com/RPCS3/rpcs3/pull/1451

**Comment by Ekaseo** [comment]
its already been more than a month... is he even in touch with you ppl? he started so many things but most of them were left unfinished. I understand that maybe he has some personal problems, but if he knows he wont be able to continue his work for a while, he could at least send a message :frowning:

**Comment by kd-11** [comment]
@vlj I feel this implementation is different in a way as it bypasses the GPU->cpu transfers completely. This gets around the issues with pbos and glMapBuffer which destroy performance.

**Comment by kd-11** [comment]
If its not possible to directly merge this, one of the better-written solutions like vlj's or DH's could be merged and I could see if I can squeeze out more performance from it using the copy_image buffers.

**Comment by danilaml** [comment]
I can confirm that this PR gives significant boost to OpenGL. My favourite (:P) dice test went from 1-3 fps on OpenGL to 10 fps (ppu2,spu2). Still not as good as DX12 though (~27 fps and 37 fps before #1344)

**Comment by vlj** [comment]
As an interim solution I prefer to merge yours since you know it better.
My PR is using a template construct aimed at factoring code between backend but it doesn't handle texture cache (I separated texture cache and surface cache in d3d12 and only factored the later atm).

**Comment by vlj** [comment]
BTW since Vulkan is released we should start looking at factorizing some code if possible. If you can integrate the texture cache mechanism into an gfx API agnostic template (potentially coupled with surface store) it may help in the long term.

**Comment by Ekaseo** [comment]
i found many samples on github, maybe it will help http://www.emunewz.net/forum/showthread.php?tid=174274

**Comment by kd-11** [comment]
I've already started on the vulkan stuff. It's a bit tedious to work with, but I'm going to first try to build it on top of the GL one. Should have some results in about a week or so.

**Comment by kd-11** [comment]
@vlj I'll look out for similarities between the vulkan and dx12 APIs and try to refactor redundant code. I'll know more as I continue to work on it.

**Comment by vlj** [comment]
I have submitted a PR there : https://github.com/RPCS3/rpcs3/pull/1507 that adds the includes and build script from Khronos. Can make your VKGsRender project include them when it got merged ?

**Comment by kd-11** [comment]
@vlj Sure

**Comment by vlj** [comment]
I merged 1507, I added an empty project file for VKGSRender that follows the template of d3d12/GL gs renders one.

**Pull request merged**
