### PR TITLE
deprecated

### PR DESCRIPTION
**Pull request by Megamouse**
- Fixes some ugly Qt deprecation warnings by adding ugly code that supposedly is the proper way to do it.
- Removes avcodec_register_all which apparently is not needed anymore in newer ffmpeg versions (probably needs some testing).

### CODE REVIEW

**Comment by Nekotekina** [comment]
Aren't we still using old prebuilt binaries?

**Comment by Megamouse** [comment]
Define "we".
Also which binary

**Comment by Nekotekina** [comment]
Ah nvm. I build with system ffmpeg ON, it's older (and could be so for unknown number of people) and still requires avcodec_register_all unfortunately. Sorry for confusion. AppImage works fine.

**Comment by Megamouse** [comment]
It has been deprecated for 2 years. So I don't know if we should keep it

**Comment by Nekotekina** [comment]
Why not keep for now? 2 years is not such a big period to completely drop compatibility.

**Comment by Megamouse** [comment]
Alright... I'll exchange it for a comment

**Comment by Megamouse** [comment]
Wait a minute... Don't we have our own branch of ffmpeg because regular ffmpeg is incompatible?
If so, then there is no need to maintain compatibility with old system libs...

**Comment by MSuih** [comment]
We do allow users to use system ffmpeg, if the option stays then there should be some level of compatibility. But I guess we can force people to update their ffmpeg when compiling with rpcs3? Other option would be to add some kind of definition that would allow people to add that register_all if they want to, but that seems unneccessary

**Pull request merged**
