### PR TITLE
[Need testing] SPU TSX Fixups

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by legend800** [comment]
NFL Blitz has regressed further with TSX and now freezes constantly in the menus. SPU threads = 2 or Auto.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3342324/RPCS3.log.gz)

**Comment by Whatcookie** [comment]
Performance with SPU threads set to 2 seems acceptable in persona 5 again. Couldn't find any regressions.

**Comment by psennermann** [comment]
PR
image


Master
image

**Comment by Nekotekina** [comment]
Rebased, it wasn't related to this PR.

**Comment by psennermann** [comment]
Ok, now it's fine

Unfortunately issue #6119 is not fixed

**Comment by digitaldude555** [comment]
@legend800 retest nfl blitz.

**Comment by legend800** [comment]
It's better, but not fixed I'd say. 

Before the regression, SPU 2=60fps (mostly steady), SPU Auto=30-40fps

As of latest commit:
SPU Auto (10-20 fps):
2019-07-05 10_03_18-Window

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3363561/RPCS3.log.gz)

SPU 2 (40-50 fps):

[2.gz](https://github.com/RPCS3/rpcs3/files/3363568/2.gz)

**Pull request merged**
