### PR TITLE
Fix trophy regression

### LINKED ISSUE #5056: Regression: Trophies (#4871)
Backbreaker series and other titles now freeze on loading main menu (trophy related). See log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2333538/RPCS3.log.gz)

Broken by this:
https://github.com/RPCS3/rpcs3/pull/4871 

Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

### PR DESCRIPTION
**Pull request by Farseer2**
Hopefully fixes #5056 - requires testing

### CODE REVIEW

**Comment by Patkos96** [comment]
Raging Blast 2 now goes ingame again.

**Comment by Atrosincity** [comment]
Confirm it works, but since i reactivated use native interface, i have disappearing menus in soul calibur V Us
untitled

disappearing menu

**Comment by Atrosincity** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2362135/RPCS3.log.gz)

**Comment by legend800** [comment]
Another regression added (not sure if new references trigger a notification).

**Comment by isshininu** [comment]
@legend800 could you please test Peggle game with that executable and say, if it fix regression for you:
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/2690101/rpcs3.zip)

**Comment by legend800** [comment]
Sorry, no change. Still getting this upon launch:  
F {PPU[0x1000000] Thread (main_thread) [0x00446484]} MEM: Access violation reading location 0x4e9

**Pull request merged**
