### PR TITLE
gl: Reverse cull face when origin == top

### PR DESCRIPTION
**Pull request by kd-11**
Should fix broken face cull direction in games using top window origin. Tested with prince of persia: the sands of time.

### CODE REVIEW

**Comment by kd-11** [comment]
This PR needs some testing from testers with larger game libraries compatible with the emu. I don't expect any regressions, but I'm being cautious.

**Comment by raven02** [comment]
@kd-11 , please update branch then can test more accurately as i got some black screen in some games probably due to the regression with never comparison case .

**Comment by kd-11** [comment]
Rebased

**Comment by raven02** [comment]
Thanks .Will test it shortly.

**Comment by raven02** [comment]
I tested most of the titles in my inventory and looks good .

**Comment by kd-11** [comment]
should be ok to merge then

**Pull request merged**
