### PR TITLE
Create config file if it doesn't exist.

### PR DESCRIPTION
**Pull request by chaoren**

### CODE REVIEW

**Comment by danilaml** [comment]
Doesn't it already create it?

**Comment by chaoren** [comment]
There's a warning. And it craps out on Windows.

**Comment by tambry** [comment]
@chaoren Needs to be rebased.

**Comment by chaoren** [comment]
Actually, I'm not sure if this is necessary anymore. The problem was there
a few days ago, now I'm not seeing the warning on OS X anymore after
pulling. I don't have access to my Windows machine at the moment. Will
check later.

**Comment by chaoren** [comment]
screenshot

Okay, so the warning's still there on Windows, but it doesn't crap out anymore.

**Comment by chaoren** [comment]
Rebased. Okay to merge?

**Comment by Nekotekina** [comment]
Ok, just need to wait for appveyor.

**Comment by tambry** [comment]
@chaoren Needs to be rebased. Hopefully the rebase will trigger appveyor.

**Pull request merged**
