### PR TITLE
rsx: Improve surface<->texture cache communication

### PR DESCRIPTION
**Pull request by kd-11**
Currently only tracks protection setting which is important for validating orphaned slices.
While we're at it, let's also use it to speed up redundant flush operations.

Fixes https://github.com/RPCS3/rpcs3/issues/12971

### CODE REVIEW

**Comment by Darkhost1999** [comment]
F {RSX [0x0b08048]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\surface_utils.h:732[:4], in function has_flushable_data)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/10238851/RPCS3.zip)
Far Cry 3 lasted maybe 5 seconds in game

**Comment by kd-11** [comment]
@Darkhost1999 Should be fixed now. Please verify.

**Comment by Darkhost1999** [comment]
F {RSX [0x002c2ac]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\surface_utils.h:756[:4], in function has_flushable_data)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10240784/RPCS3.log)
Game froze first test so I removed Read buffers and WDB the game doesn't need and tested with accurate rsx reservation access instead of accurate gettlar.

Here is with WCB only. Bare minimum settings required to play this game.
F {RSX [0x002ba9c]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\surface_utils.h:756[:4], in function has_flushable_data)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10240808/RPCS3.log)
I have to force the task to close

**Comment by kd-11** [comment]
@Darkhost1999 You can try again now

**Comment by Darkhost1999** [comment]
Appears to be working as expected and intended. Just drove around and teleported a few places to double check different zones and regions.
Was just testing #10998 with no change observed. Thanks for the fixes.

**Comment by Darkhost1999** [comment]
As for testing WCB and frame times what better game to test than WCB's arch nemesis
Master
0 0 25-14479 _ Need for Speed Most Wanted  BLUS31010
PR
Pull_13077 _ Need for Speed Most Wanted  BLUS31010
For spectaculars focus more on the averages and 1% values. I also notice some graphical changes. All good changes

**Pull request merged**
