### PR TITLE
Alternative interpreters

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by fh1360** [comment]
hi
diablo 3 on pc online and is not cracked
please help us play on rpcs3
please please

**Comment by MoochMcGee** [comment]
@fh1360 RPCS3 doesn't play commercial games.

**Comment by MoochMcGee** [comment]
@Nekotekina Why not just improve the existing interpreters?

**Comment by danilaml** [comment]
@MoochMcGee it's different approach. The project is an early stage so it's only natural to have many different types of interpreters/recompilers and such based on different ideas to see what works best.

**Comment by MoochMcGee** [comment]
@danilaml No, that's not how it works. This is just code duplication for the sake of code duplication.

**Comment by fh1360** [comment]
Thanks for the helpPlease to the implementation and testingemulator and run ps3 games give priority on games thatare not on the computeror if you're ever not crack like god ofwar and Diablo 3 


     On Thursday, April 9, 2015 12:30 AM, MoochMcGee <notifications@github.com> wrote:
   

 @danilaml No, that's not how it works. This is just code duplication for the sake of code duplication.—

**Comment by tambry** [comment]
@fh1360 Emulators usually aren't made like that. At least RPCS3 isn't. There's no point in giving "priority" to some game. It means that other parts of the emulator will be underdeveloper and could affect the game that you gave "priority" negatively.

**Comment by fh1360** [comment]
Mypoint is that during the development and testing emulator for example, insteadof working on the WatchDogs or Wanted Corp is working on Diablo 3

**Comment by tambry** [comment]
@fh1360 You seem to completely have missed my previous point. And your poor English doesn't exactly help you. I suggest you learn something about emulation before you make very bad suggestions and ideas. And I don't even have an idea if anyone has tested Diablo 3 on RPCS3.

**Comment by MoochMcGee** [comment]
He posted the same plea on a commit, so I think he's probably just spamming.

**Comment by tambry** [comment]
@MoochMcGee Oh, hadn't noticed. Thank you for pointing it out.

**Comment by clienthax** [comment]
@fh1360 seriously, stay off the issue tracker, you are obviously too stupid to know what it is used for.

**Comment by Bigpet** [comment]
Just ignore people asking for help with piracy, there's no need for insults

**Pull request merged**
