### PR TITLE
SPU Analyser improvements ("Giga")

### PR DESCRIPTION
**Pull request by Nekotekina**
These changes are supposed to be tested with the following settings:
 * SPU LLVM
 * Giga block size

This is literally first working version from 10 min ago so don't expect much.

### CODE REVIEW

**Comment by nitrohigito** [comment]
God of War: Collection [BCES00791] now crashes when starting with a clear SPU cache.

Logfile: [gowc_RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/3145631/gowc_RPCS3.log.zip)
SPU logfile: [gowc_spu.log.zip](https://github.com/RPCS3/rpcs3/files/3145629/gowc_spu.log.zip)

**Comment by legend800** [comment]
Yeah I just get Fatal Error in all games, even with no SPU cache. Nfl Blitz is the only one I could find that could at least boot with it. 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3145736/RPCS3.log)

**Comment by Nekotekina** [comment]
Some games should work now.

**Comment by legend800** [comment]
Much better now. A few preliminary results, I'll update this more later.

- Wipeout HD: Soft locks several times trying to start a race. Log = hundreds of mbs
- Captain America: Ingame, but no perf diff (~17fps in big fights). Appears to just be constantly building SPU cache. I stayed in a small room for a few mins not moving and it kept generating.
- Splatterhouse: Soft locks before entering gameplay, I gave it several mins on the load screen, was still saying it was building SPU stuff though...

See a lot of these in games now fyi:
E {SPU[0x2000004] Thread (BR's CellSpursKernel4) [0x103f0]} SPU: Unexpected fallthrough to 0x40 (chunk=0xaa90, entry=0x103f0)

**Comment by legend800** [comment]
Still getting fatals on all games with the new build.

**Comment by Kravickas** [comment]
Is it even possible for u Neko to find out from logs why some parts of audio (music in menu) doesnt work with Giga mode ?

**Comment by Nekotekina** [comment]
From logs very unlikely. Need to bisect it live.

**Comment by digitaldude555** [comment]
Metal Slug 3 goes ingame with spu llvm giga, when you close the game rpcs3 crashes though.

**Comment by motorolah** [comment]
Ratchet & Clank: Tools of Destruction now crashes before the prologue's video, while on master it does not.

**Comment by Kravickas** [comment]
Grand Theft Auto IV [NPEB00882] segfaulting beforte showing window

Log and spu log 
[Grand Theft Auto IV [NPEB00882].zip](https://github.com/RPCS3/rpcs3/files/3148287/Grand.Theft.Auto.IV.NPEB00882.zip)

**Comment by QuaiGoner** [comment]
Red Dead Redemption Fatal Error on boot
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3148306/RPCS3.log)

**Comment by Kravickas** [comment]
Grand Theft Auto IV [NPEB00882]

still segfaulted, but even after that it opened window and tried to run and build something
Bez názvu
log, spu log[Grand Theft Auto IV [NPEB00882].zip](https://github.com/RPCS3/rpcs3/files/3149035/Grand.Theft.Auto.IV.NPEB00882.zip)

**Comment by Kravickas** [comment]
Do u want to continue ? Would be probably better if u get the game yourself or call it to ''broken'' game to fix :D

Grand Theft Auto IV [NPEB00882]

still segfault, this time no window
[Grand Theft Auto IV [NPEB00882].zip](https://github.com/RPCS3/rpcs3/files/3154096/Grand.Theft.Auto.IV.NPEB00882.zip)

**Comment by theoldsport** [comment]
A simple game that segfaults on giga is Supersonic Acrobatic Rocket-Powered Battle-Cars [NPUB30035]
image

Log-
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3155171/RPCS3.zip)

**Comment by legend800** [comment]
Everything is pretty much broken atm. I would hold off on testing until we get some fix commits to minimizing pinging everyone with effectively the same issue.

**Comment by Kravickas** [comment]
small update few builds ago u fixed sound in menu of NHLs

spu giga doesnt crash (tested with only  game) when u build some giga cache with asmjit

**Comment by Kravickas** [comment]
GTA IV
now first boot segfault, but second boot is going ingame

**Comment by arcadee1977** [comment]
Ninja gaiden sigma 2 can not ingame, PopUp "Fatal error".

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3165379/RPCS3.zip)

**Comment by MSuih** [comment]
Skate 3 freezes during intro movie and keeps spamming these 3 lines into log, even after stopping the game.
```
·E 0:01:18.520238 {SPU[0x2000003] Thread (Job Manager - Job Thread) [0x194a4]} SPU: [0x194a4] Fixed first function at 0x18aa0
·E 0:01:18.520342 {SPU[0x2000003] Thread (Job Manager - Job Thread) [0x194a4]} SPU: Function 0x192d8: [0x192d8] $LR mismatch (src=0x192d8; 0x800000e0 vs 0x0)
·E 0:01:18.520345 {SPU[0x2000003] Thread (Job Manager - Job Thread) [0x194a4]} SPU: Function 0x194a4: calls bad function (0x19340)
```
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3166483/RPCS3.log.gz)

**Comment by Nekotekina** [comment]
I moved contradicting commit in another PR, since it doesn't work in Giga mode.
I'm looking toward merging this as is, but there are probably too many regressions atm?

**Comment by Dravonic** [comment]
Every game I've tried (P5, RDR, LBP2, Demon Souls) show a fatal error popup at boot. Oddly, P5 keeps running and I'm able to go ingame if I ignore the popup but the UI freezes, only the game window seems to kinda work.

**Comment by Kravickas** [comment]
probably only regression is startup segfault

idk if this affects other options or only LLVM Giga, if only that like noone using that on master anyway

**Comment by legend800** [comment]
Don't some games work fine on giga? So now those are all broken? If breaking them is necessary for progress than I guess it's fine.

**Comment by Kravickas** [comment]
From my gamelist Master Giga works with few game and these game are rather spu easy and giga does nothing more than Mega

**Comment by AniLeo** [comment]
IMO just make sure games don't break on Safe and Mega at least, Mega and Giga are still unfinished options regardless

**Comment by MSuih** [comment]
Skate 3 doesn't work with SPU LLVM and this PR, even when safe block size is being used. After emptying cache it will show a black screen and compile some modules, then crash the emulator. Every boot after that will cause emulator to freeze after compiling only a couple of SPU modules.

**Comment by Nekotekina** [comment]
Can you send SPU cache which freezes at compilation, if I got it right?

**Comment by MSuih** [comment]
Sure. The UI froze at first SPU module.
[spu.log](https://github.com/RPCS3/rpcs3/files/3167795/spu.log)

**Comment by Nekotekina** [comment]
@MSuih Uhh, can I have .dat file?

**Comment by isJuhn** [comment]
Spider-Man Shattered Dimensions [BLES00946] same symptoms as Skate 3 in safe mode, doesn't even spawn a window before freezing

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3168034/RPCS3.log)
[spu.log](https://github.com/RPCS3/rpcs3/files/3168035/spu.log)
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/3168036/spu-safe-v1-tane.zip)

**Comment by Nekotekina** [comment]
Sadly, couldn't reproduce, but I added few checks to filter out new changes in Safe/Mega modes.

**Comment by isJuhn** [comment]
Spider-Man Shattered Dimensions [BLES00946] now boots fine

**Comment by SimoSbara** [comment]
Heavy Rain BCES00797 crashes at giga block size

**Comment by arcadee1977** [comment]
Sonic unleashed dropped 10FPS (maybe in this PR)?

**Comment by arcadee1977** [comment]
Sonic unleashed dropped 10FPS in this PR!（8063-50FPS ；8089--36FPS）
Settings: SPU LLVM+SAFE ( In 8063, SPULLVM FPS=SPU ASMJIT FPS? )


未标题-1
8089

未标题-2
8063

**Pull request merged**
