### PR TITLE
Revert "rsx: Handle cpu readback of Z-ordered memory"

### PR DESCRIPTION
**Pull request by kd-11**
Reverts RPCS3/rpcs3#8664

### CODE REVIEW

**Comment by illusion0001** [comment]
If this is for the recent demon souls regression, it's actually caused by #8652.

**Comment by elad335** [comment]
does it work with interpreter?

**Comment by illusion0001** [comment]
I'm getting someone on #netplay to test right now

**Comment by kd-11** [comment]
Ffs

**Pull request closed without merging**
