### PR TITLE
PRX improvements

### PR DESCRIPTION
**Pull request by Nekotekina**
"Load only liblv2.sprx" is now available (disable "Load required libraries"!)
Shovel Knight works correctly with music. Check other games with FMOD thread.

### CODE REVIEW

**Comment by OverlordCW** [comment]
Load only liblv2.sprx
What is this used for and when should I use it?

**Comment by Zangetsu38** [comment]
Good works :) but have problem with all game used cellfiber, log say todo and not load libfiber strange

**Comment by Zangetsu38** [comment]
Is good now thx :)

**Comment by Zangetsu38** [comment]
but with load liblv2 only i have this error with several game
Here with bleach
>F {PPU[0x1000002] Thread (_gcm_intr_thread) [0x0024bc60]} MEM: Access violation reading location 0xffff8fd8

**Comment by Luffykun007** [comment]
For me also the game does not work same error reported by @zangetsu the game neither ingame arrives now!

**Comment by Luffykun007** [comment]
Not yet working For me the game neither ingame arrives now same error reported by @zangetsu.

**Comment by ikki84** [comment]
@Luffykun007 Shovel Knight works, but as Neko said above disable "Load required libraries" (!) also check "Load only liblv2.sprx"
shovel

**Comment by Zangetsu38** [comment]
@Luffykun007 Shovel knight works

**Comment by Luffykun007** [comment]
Yes it's working now and with music the shovel knight.
capturar

**Comment by hcorion** [comment]
Fixed menu SFX in Ni No Kuni as well.

**Pull request merged**
