### PR TITLE
cellVideoOutConfigure: treat unknown aspect as AUTO

### PR DESCRIPTION
**Pull request by Megamouse**
Apparently some games just set aspect to 6 or whatever.
Let's treat unknown options as auto for now.

Since there might be another fix, I added an error message and a TODO.

### CODE REVIEW

**Review by kd-11 — APPROVED** [review]

**Comment by elad335** [comment]
Noone tested on realhw

**Comment by elad335** [comment]
I think a brief test even without trying to render graphics is to use cellVideoOutGetConfiguration afterwards to see what it returns for aspect ratio.

**Comment by Megamouse** [comment]
> I think a brief test even without trying to render graphics is to use cellVideoOutGetConfiguration afterwards in order to check what it returns for current aspect ratio.

Agreed. But i can't run the tests.
It should obviously also be run with different values than 6

**Comment by kd-11** [comment]
Let's keep this as a stop-gap solution as there are games that regressed and this restores functionality.

**Pull request merged**
