### PR TITLE
SPU: Fix page faults notifications on TSX

### PR DESCRIPTION
**Pull request by elad335**
* Release reservation lock before waiting for page fault notification.

### CODE REVIEW

**Comment by xddxd** [comment]
No change in GT6. Still freezes on intro with or without RSX reservations.

**Comment by LaneSh4d0w** [comment]
Last user indeed found the problem. Here's what I got on my side:

`·W 0:01:14.426394 {PPU[0x1000029] Thread (PDI) [0x01730278]} cellSaveData: cellSaveDataAutoLoad2(version=1, dirName=“BCJS37016-GAME6”, errDialog=0, setBuf=*0x4220e8a4, funcStat=*0x154fad0, funcFile=*0x154fae0, container=0xffffffff, userdata=*0x0)
·W 0:01:14.428121 {PPU[0x100001b] Thread (9ZWAM) [0x017368e8]} sys_io: cellMouseGetDataList(port_no=0, data=0xd00c49d0)
·! 0:01:14.429075 {PPU[0x100000f] Thread (SpursHdlr0) [0x019f9470]} SPU: Loaded SPU image: SPU-756df5d819d66f930a0c4e18c72a0e9972fa45fa (<- 0)
	[0] t=0x1, ls=0x100, size=0x790, addr=0x1a10c80
	[1] t=0x4, ls=0x0, size=0x20, addr=0x1a11424
·W 0:01:14.429683 {PPU[0x1000029] Thread (PDI) [0x01730278]} SIG: Page_fault writing location 0x611b0000 because of using unmapped memory
·W 0:01:14.429702 {PPU[0x1000029] Thread (PDI) [0x01730278]} SIG: Page_fault while in function cellSaveDataAutoLoad2`

**Comment by arabek** [comment]
Now goes past the loading screen with v1.05 and ppu/spu precise.

But starts spamming with:
```
·W 0:05:25.755045 {PPU[0x1000001] Thread (MpAnk) [0x00a797f0]} sys_memory: sys_memory_get_user_memory_size(mem_info=*0xd0014d60)
```
[ arab: ~/rpcs3 ]$ zgrep sys_memory_get_user_memory_size\(mem_info RPCS3.log.gz  | wc -l
6329

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4663400/RPCS3.log.gz)

**Comment by LaneSh4d0w** [comment]
I suppose the game is preloading all of the files it needs.

**Comment by arabek** [comment]
Dies on PPU/SPU LLVM

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4663441/RPCS3.log.gz)

**Comment by arabek** [comment]
> I suppose the game is preloading all of the files it needs, but very interesting. Do you have a savegame or not ?

No, i deleted the save to have a clean state. It goes up to/past the name input screen (haven't tested further). But it seems to be preloading stuff in the background indeed - as on the name input screen it started flickering with what seems to be a track rendering in the background thread. Wierd. It never occured before.

**Comment by arabek** [comment]
Arg. Save state indeed seems to influence the flow. If i delete game save and start with clean install of v1.05, the game starts past the loading screen even on LLVM PPU/SPU. So my previous comment is invalid. Sorry for that.

**Comment by LaneSh4d0w** [comment]
@arabek So you can confirm game is at the same state as before ?

**Comment by arabek** [comment]
Yeah, it's the same as on master. With the savegame deleted, game does not lock up. If save exists - game freezes in the loader.

**Pull request merged**
