### PR TITLE
rsx/fp: Ignore self-referencing register writes.

### PR DESCRIPTION
**Pull request by kd-11**
### Notes
- Sometimes, usually with shaders that do pack/unpack operations, there is a write-to-self operation.
  e.g `r0.xy = r0.xy` Obviously no new data was introduced into "r0" by this, so we should not mark the register as having new data.
- TODO: Investigate on realhw if self-reference is needed to "cast" the overlapping half registers to their full register counterparts. This pattern has been noted in more than one game and for the cg compiler to emit it, it must mean something.

Fixes https://github.com/RPCS3/rpcs3/issues/6303

### CODE REVIEW

**Comment by Yahfz** [comment]
image
Fixed

**Comment by legend800** [comment]
While the ground gfx are fixed (ty!!), the game is unplayable now. Constant freezes in menus, loading levels, etc. Froze on me 4/4 times and always when starting level 2 - first stage loaded fine at least once. Tried today's master and zero freezes. 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4719943/RPCS3.log.gz)

**Comment by kd-11** [comment]
Unrelated.

**Comment by jokoputera** [comment]
hi, im just curious. for PR things like this- the specific game, is it a patch only (which PS3 is not getting new games anymore), or, is it applied for all games no matter using this shaders or not?

**Comment by MSuih** [comment]
We aim to emulate the console and not to get specific games to run. If there is an issue with some game then it means that our emulation is not accurate enough. Pull requests like this one aim to make our emulator more accurate instead of adding a game-specific hack. The changes apply to games which use the same features as the one mentioned, they may or may not fix similar issues with other games.

If you are a programmer, treat individual games as unit tests for our project. If a test fails, the solution is not to add a hack which makes the test pass but rather fix the underlying issue.

**Comment by kd-11** [comment]
@jokoputera Patches for games are not committed to the emulator. They are provided by the wider community as patch.yml entries which alter the game to make it nicer on rpcs3. The programs, patched, should still work on PS3 the same way as they do with the emulator, maybe with worse performance due to hardware differences, but behavior should always be the same between real hardware and emulator as far as is reasonably possible.

**Comment by jokoputera** [comment]
Ok, thanks for @msuih and @kd-11 for thorough explanation. Nice to understand little by little... Tq

**Pull request merged**
