### PR TITLE
[TESTERS NEEDED] SPU: Reimplement SPURS limiter

### PR DESCRIPTION
**Pull request by elad335**
* Release thread semaphore upon successful SPURS Idle state setting, wait for semaphore before supposed SPURS task acquire.

### CODE REVIEW

**Comment by Augusto7743** [comment]
All good with you elad335 ? I wish all good in your life. Thanks for doing that good act.

That PR does any optimization when SPUs are extremely busy using each cpu core in 100 % ?
I see few to much speed optimization in some games.
Pro Evolution Soccer 2018 before your lastest spus optimizations code not was possible run in good performance in an cpu amd fx 6 cores running between 15 to 25 FPS. Now the game run between 35 to 46 FPS being playable !
I see moderate performance gain in Motorstorm Pacific Rift.
However has issues in few games as if SPU limiter not allow use the cpu in 100 %. Thus for any game not running 100 % need maximum spurs to above 4 or default value unlimited.

GT6 need an more recent amd zen cpu, but testing in an amd fx 6 cores if configuring the maximum spurs to less of 3 now is possible boot the game and the cpu usage drop to less of 75 % so having less performance. Need maximum spurs above of 4 to the cpu to be used 100 %. Perhaps that line information was correct to post.

**Comment by elad335** [comment]
I will think about it

**Comment by Augusto7743** [comment]
@elad335
Your recent optimizations code SPURS limiter is awesome.
Previous builds without SPURS limiter only is possible boot some games if SPURs is value unlimited or using other values happen crash.
Now is possible boot several games using SPURs with low value as 2 or 3 without crash.

I see here when testing some games three behaviors in current builds using SPURS limiter code :

- Medium to high performance optimization without crashes and using less cpu selecting SPURs to 2 or 3. Pro Evolution Soccer 2018 has high performance optimization.
- Some games run with less or same performance not using totally the cpu as was in previous builds before was added the SPURs limiter code even if SPURs value is unlimited. For some games using SPURs unlimited restore the 100 % gameplay speed and for others games the performance is below of 100 % not using totally the cpu.
- Others games nothing happen. Need for Speed Hot Pursuit is an example. Run in same performance without crashes without any optimization as if the SPURs limiter code not work.

Is as if the SPU limiter code need to be an option in the RPCS3 GUI Advanced menu to choice if enable for some games and disable for other games so avoiding errors.

**Comment by elad335** [comment]
@Augusto7743 Hi, can you provide before&afters?

**Comment by Augusto7743** [comment]
I remember the FPS performance in some games using previous build and with current build using your SPURs limiter code totally sure are more faster for some games.
Here the CPU is an amd fx 6300 6 cores and even so has performance optimization at point games unplayable are now playable being the detail important to post about it.

Pro Evolution Soccer 2018 never had an performance above 24 FPS not possible to play. Now the game run between 35 to 46 FPS being playable in my cpu.
MOTORSTORM PACIFIC RIFT NPUA70033 Demo 2 never was possible an good speed to play and was performance below of MOTORSTORM PACIFIC RIFT NPUA70022 Demo 1. Both are much slow in my cpu and never was above 12~14 FPS in previous builds. Now only for test both are between 14 to 18 FPS at point is possible play in medium speed not being exactly slow as was before.

AMD FX not run Need for Speed Hot Pursuit and GT6, but for test Need for Speed Hot Pursuit continue being the same performance 12 FPS as if the SPURs limiter code not does anything even using SPURs 2 or 3 and GT6 run more slow below 10 FPS with cpu usage never being above 75 % and before in previous builds run in 14 FPS cpu usage between 90 and 100 %.
Is good an user using current cpus having Need for Speed Hot Pursuit and GT6 post about the performance using current build.

I understand AMD FX not is really an good cpu for all games, but now run all games in good speed less NFS Hot Pursuit and GT6 both need an better cpu.
Thus being if your code does an good optimization for AMD FX I had to post about it.

You need logs ?

**Pull request merged**
