### PR TITLE
Store Vertex/Fragment program in a hashtable and do not rebuilt FP if a constant changes

### PR DESCRIPTION
**Pull request by vlj**
Instead of iterating on a vector program and comparing memory content, programs are now hashed and stocked in an unordered_map (ie a hashtable). LoadProgram() call should be faster if there are a lot of programs used.
In addition a constant change in a fragment program shouldn't trigger a program recompilation. The GLGSRender now gets constant value from an offset table and set them as uniform.

The structure is used by the upcoming D3D12GSRender.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Update your branch with the main master before.
The break that much problem.

**Comment by vlj** [comment]
Done

**Comment by raven02** [comment]
Humm seems to be bit broken when test with GCM sample

-master build
cube2

-this branch build
cube1

**Comment by vlj** [comment]
where did you find these tests?

**Comment by raven02** [comment]
This is from the PS3 SDK but we cannot share here .Probably you can test it via short waves 0.0.2 , it comes with some GCM samples.

http://www.emucr.com/2014/01/short-waves-v002.html

**Comment by vlj** [comment]
Ok I can reproduce.
By the way how do you got 41 fps ? I only get 1.15 fps here with master and my branch.

**Comment by vlj** [comment]
Oops sorry I forgot to remove a "return true" in the vertex program compare function. It should now works as intended.
Thx for the link btw

**Comment by vlj** [comment]
Another fix added for vertex fragment caching. Now it should be as fast as master for cube.ppu.elf.

**Comment by raven02** [comment]
Cool .thanks @vlj

**Comment by raven02** [comment]
@vlj , meanwhile , there is few more tests that not currently render propertly in our master branch (but okay in rsx branch now) , probably u can test it with your D3D12GSRender as well.

https://github.com/RPCS3/ps3autotests/tree/master/tests/rsx/rsx_fp_static=

**Comment by tambry** [comment]
@vlj Travis build is failing, so you should fix that.

In file included from /home/travis/build/RPCS3/rpcs3/rpcs3/Emu/RSX/GL/GLProgramBuffer.h:3:
/home/travis/build/RPCS3/rpcs3/rpcs3/Emu/RSX/GL/../Common/ProgramStateCache.h:331:3: error: 
      missing 'typename' prior to dependent type name
      'binary2FS::const_iterator'
                binary2FS::const_iterator It = m_cacheFS.find(vm::get_pt...
                ^~~~~~~~~~~~~~~~~~~~~~~~~
                typename

**Comment by Syphurith** [comment]
As told in [a reference](https://stackoverflow.com/a/613132), just add `typename` keyword before it may solve such problem.

**Comment by vlj** [comment]
I've added the typename (I think I didn't forget one) and I also reverted the id->Id rename so the change should be less invasive.

**Comment by vlj** [comment]
@raven02 I copy/pasted the GL decompiler from master for D3D12 ; I intend to factorize the decompiler between the 2 backend because HLSL and GLSL are very close. Actually supporting HLSL is just replacing vec4 by float4, and constant/input/output declaration.
It means that currently d3d12 has the same "bug" as GL, ie the static test 2 render  blue dot too big for instance.

**Comment by Syphurith** [comment]
Orz. Looked up the error in the Travis Build log, it seems X11 header broke our `Ultilities/Log.h`.
```
In file included from /home/travis/build/RPCS3/rpcs3/rpcs3/Emu/RSX/GSManager.cpp:8:
In file included from /home/travis/build/RPCS3/rpcs3/rpcs3/Emu/RSX/GL/GLGSRender.h:8:
In file included from /home/travis/build/RPCS3/rpcs3/rpcs3/Emu/RSX/GL/GLProgramBuffer.h:3:
In file included from /home/travis/build/RPCS3/rpcs3/rpcs3/Emu/RSX/GL/../Common/ProgramStateCache.h:5:
/home/travis/build/RPCS3/rpcs3/rpcs3/../Utilities/Log.h:55:3: error: expected identifier
                Success,
                ^
/usr/include/X11/X.h:350:21: note: expanded from macro 'Success'
#define Success            0    /* everything's okay */
                           ^
1 error generated.
```
Which was designed to be an enum. The `Log.h` header itself doesn't include wrong files but it seems conflict with the X11 header. Should we need a `#ifdef` or `#undef` macro somewhere (ugly)? BTW the two `Success` has different value. You can still rename those symbols in Log.h to avoid this issue.

**Comment by vlj** [comment]
Can it be fixed on master ? I think it's an include issue in master as well.

**Comment by Syphurith** [comment]
@vlj Well no much difference in the `Log.h` between rsx and master. However there is no `GSManager` but `GSFrame` which is in `Gui` Folder, and much about the other files. So currently this is issue for rsx only. Now I highly doubt the work when one want to merge rsx to master..

**Comment by raven02** [comment]
Just checked out this branch on commerical games and it fixes few graphical issues in - the guided paradox , Disgaea 3

disgaea3
paradox

**Comment by Bigpet** [comment]
Not really sure what the point of all the random "glGetError()" calls with dismissed results is.

As for renaming `Log::Success` and friends, I guess we can just make them lowercase to avoid this.

**Comment by Syphurith** [comment]
Now, I'm trying to compile a version with renamed symbols to see if all corresponding ones are renamed. After confirmed would try to rebase it and create pull there - so he can just merge those and trigger a CI build here in this pull.

**Comment by vlj** [comment]
@Bigpet I removed the call to glGetError()

**Comment by Nekotekina** [comment]
Instead of moving fucking code from fucking headers, renaming symbols. Because fucked macro everywhere.

**Pull request merged**
