### PR TITLE
cmake: Optionally disable compiling for wayland if EGL libs are not found

### PR DESCRIPTION
**Pull request by kd-11**
Also makes wayland support optional for QT_QPA_PATFORM=xcb warriors.
Closes https://github.com/RPCS3/rpcs3/issues/15938

### CODE REVIEW

**Comment by kd-11** [comment]
Turns out EGL is a component of OpenGL package.

**Comment by oltolm** [comment]
Why not use something like this?
```cmake
find_package(OpenGL REQUIRED COMPONENTS EGL)
target_link_libraries(3rdparty_opengl INTERFACE OpenGL::GL OpenGL::GLU OpenGL::GLX OpenGL::EGL)
```

**Comment by kd-11** [comment]
> Why not use something like this?
> 
> ```cmake
> find_package(OpenGL REQUIRED COMPONENTS EGL)
> target_link_libraries(3rdparty_opengl INTERFACE OpenGL::GL OpenGL::GLU OpenGL::GLX OpenGL::EGL)
> ```

That was the original plan, but I had to back off after the build failures reported in https://github.com/RPCS3/rpcs3/issues/15938. I thought a standalone FindEGL script would solve that issue but it doesn't seem to help at all.

**Comment by oltolm** [comment]
A user reported success with this patch https://github.com/oltolm/rpcs3/commit/29c8a5b1f2de187cfd4162e77a82f8865f00aeef .

**Comment by kd-11** [comment]
> A user reported success with this patch [oltolm@29c8a5b](https://github.com/oltolm/rpcs3/commit/29c8a5b1f2de187cfd4162e77a82f8865f00aeef) .

Thanks. I'll restructure and push.

**Comment by kd-11** [comment]
Will reopen as a larger PR.

**Comment by kd-11** [comment]
@oltolm Please open a PR with your commit, it looks reasonable. I've already reused this branch for other things.

**Pull request closed without merging**
