### PR TITLE
None shader preloading

### PR DESCRIPTION
**Pull request by TGEnigma**
Added a config option to disable shader preloading, useful for debugging/testing purposes.
Initially tried to make a 'null' shader cache but templates and inheritance don't like each very much so I gave up. 🐱

### CODE REVIEW

**Comment by kd-11** [comment]
Just name it "disable on-disk shader cache" and also block the store operation from working when it is enabled to keep the cache from writing to disk as well.

**Comment by kd-11** [comment]
Fair enough. Not a useful feature since you can just delete the shader cache and have no preloading but some people are really stubborn about the shader cache and believe it somehow hinders performance.

**Comment by TGEnigma** [comment]
I personally only find it useful for debugging, specifically for when I have to reboot a game constantly. Previously I just kept deleting the cache but that gets kinda annoying, and I also would like to keep my shader cache for if I want to play normally.

**Comment by scribam** [comment]
Does this option should be available from the GUI? It doesn't look like to be necessary for you @TGEnigma, am I right?

**Comment by TGEnigma** [comment]
Should it be? I don't know- I don't want noobs enabling it and then complain about how their framerate sucks.

**Comment by elad335** [comment]
put in the debug tab then

**Pull request merged**
