### PR TITLE
spu: Check exponent bits in FMA ops

### PR DESCRIPTION
**Pull request by kd-11**
This PR modifies the result of SPU FMA if exponents in a or b are at max and discards the value. This is by no means even close to accurate handling of corner cases in the SPU, but rather a fast workaround.
Discards the result of (a * b) if either a or b has extended exp bits (usually inf) without degrading performance too much.
Should fix some cases reported in https://github.com/RPCS3/rpcs3/issues/2670

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
@kd-11 With SPU fast:
image
It seems that there's missing geometry.

**Comment by MarioSonic2987** [comment]
image
With SPU fast.

**Comment by MarioSonic2987** [comment]
image

**Comment by raven02** [comment]
Very nice .TNT races in-game looks correct with SPU ASMJIT.

**Comment by hcorion** [comment]
Fixes Ni No Kuni, but on Linux I run into bug #2677 with the exploding vertices.

**Pull request merged**
