### PR TITLE
PS3UPDAT.PUP installer

### PR DESCRIPTION
**Pull request by cornytrace**
This pull request adds a menu option to the tools menu in order to automatically install the dev_flash files from a PS3UPDAT.PUP file to the emulator directory.

This also refactors SELFDecrypter into SCEDecrypter, which can handle all files with an SCE header (such as certain files in the PUP), and SELFDecrypter, which inherits from SCEDecrypter to implement SELF specific functionality.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Possible implement .mself decryption and oppened ?

**Comment by ikki84** [comment]
Just a suggestion: Could you add a progress bar while installing the firmware?

**Comment by raven02** [comment]
Looks like the installation is pretty quick ( less than a sec)  .May be not worthwhile to add progress bar . Probably a simple dialog saying  it is done should be good enough .

**Comment by cornytrace** [comment]
@raven02 Exactly. 
It already prints a success or fail message to the log, but i'll see what I can do about that dialog.

**Comment by cornytrace** [comment]
Added message boxes on success and failure.
Since it was an interesting challenge, I added a progress bar too.

**Comment by al0xf** [comment]
Seems to be working, a nice touch would be if it said something like "Installed firmware version 4.81".

**Comment by raven02** [comment]
I'll going to merge it as no further comment on this pull request .

**Comment by Nekotekina** [comment]
Why you didn't wait at all before merging?

**Comment by raven02** [comment]
@Nekotekina , alright . will leave it to you for further review next time .

**Pull request merged**
