### PR TITLE
Properly get PARAM.SFO and icons for C00 games

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
This should get PARAM.SFO for the full game instead of the trial version for C00 games if you have the RAP file to unlock full game. I've added a helper function to Emulator class and also save SFO path for the current game into a variable on boot.

### CODE REVIEW

**Comment by NicknineTheEagle** [comment]
> The command "docker pull rpcs3/rpcs3-travis-trusty:1.0" failed and exited with 1 during .

Travis failed to pull the repo for some reason.

**Comment by 13xforever** [comment]
With these changes Scott Pilgrim vs the World no longer shows in the game list

**Comment by NicknineTheEagle** [comment]
Fixed.

**Comment by Nekotekina** [comment]
You are normalizing line ends into the wrong direction. Default is Unix here.

**Comment by legend800** [comment]
Worked for all my c00 games (backbreaker vengeance, burnout crash, nba jam, pac man CE+)

**Comment by NicknineTheEagle** [comment]
Great, apparently, game_list_frame.cpp got committed with Windows line endings. Let me see if I can fix this.

**Comment by NicknineTheEagle** [comment]
Can this be merged? I think I covered everything.

**Comment by Nekotekina** [comment]
I'll check tomorrow

**Comment by Megamouse** [comment]
Why is everyone commiting these billion line changes?

**Comment by NicknineTheEagle** [comment]
People are normalizing line breaks. Some files have Windows and Unix line breaks mixed together.

**Comment by scribam** [comment]
@NicknineTheEagle Have you tried to boot an elf/self file with your PR?

**Comment by 13xforever** [comment]
works fine for me 🤔

**Comment by scribam** [comment]
It looks like Windows is fine. Unfortunately, I have this:

screenshot from 2018-12-04 22-09-48

screenshot from 2018-12-04 22-10-42

**Comment by Nekotekina** [comment]
Try the commit above, must be fixed.

**Comment by scribam** [comment]
@Nekotekina Confirmed, the issue is fixed with your commit. Thank you

**Comment by Yahikon** [comment]
>           Try the commit above, must be fixed.

what build rpcs3 need to used to see fixes for GOWIII?

**Comment by nitrohigito** [comment]
This PR broke `Harry Potter and the Order of the Phoenix [BLES00070]` as reported by @leskal in the issue ticket #5488.

**Pull request merged**
