### PR TITLE
Add more evdev buttons

### LINKED ISSUE #7760: Ps3 Controller Shanwan Clone  : Evdev button (NULLSTR) (302) is unknown.
## Quick summary
Evdev button (NULLSTR) (302) is unknown. Please add it to the button list.

## Details
When i try to map button of this controller square is mapping with DEAD and works but cross, triangle and circle (responding to evtest at 301, 302, 303) give me the error: 
Evdev button (NULLSTR) (302) is unknown. Please add it to the button list.
Searching in the code the regarding error come from:

case EV_KEY:
{
m_is_button_or_trigger = true;

// get the button value and return its code
if (button_list.find(code) == button_list.end())
{
evdev_log.error("Evdev button %s (%d) is unknown. Please add it to the button list.", libevdev_event_code_get_name(EV_KEY, code), code);
return -1;
}

value = val > 0 ? 255 : 0;
return code;
}

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4318803/RPCS3.log)

Logs attached
- your system configuration (OS, CPU, GPU, driver versions, etc)

My Config is a Intel Core i5-6500 running at 3.20ghz with 8gb ram ddr4 and geforce gtx 1050

Thanks a lot

### PR DESCRIPTION
**Pull request by Megamouse**
The current evdev button list mainly only contains named buttons (BTN_) from https://gitlab.freedesktop.org/libevdev/libevdev/-/blob/master/include/linux/input-event-codes.h

I added most of the gaps in between with hex value names for now.
For anyone wondering why there's a name map:
This was solely introduced in order to have consistency between the GUI and the config file.

might fix #7760

### CODE REVIEW

**Comment by dariocdj** [comment]
Ok thanks, now i must wait that your pull request will be merged in next release?

**Comment by Megamouse** [comment]
depends if it works.
did you try?

**Comment by dariocdj** [comment]
How i can try it? I've Never compiled at the moment, just downloaded binary. If it is necessary i try to compile, or pheraps you can give me a debian buster x64 binary?

**Comment by Megamouse** [comment]
it should already be in the latest version

**Comment by dariocdj** [comment]
YESSS IT WORKS ! Lots of thanks !

**Pull request merged**
