### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by kd-11**
- emu: Add option to manage thread placement. Makes an impact on windows when using ryzen processors, most other cpus should be unaffected. Linux does a better job on its own so the option is not recommended on linux.
- vulkan: Flush command queue on access violation event before attempting to touch texture cache in the event of access violations. This makes the device internal state consistent before texture operations. Fixes VK_ERROR_DEVICE_LOST in some cases when WCB is in use
- Fixes for native overlay. Add fallback path in dev_flash for glyphs and fix vulkan freeze if icons are non-existent.
- Fix Z clipping using selective z clamping.
- Texture cache (blit engine) fix - Remove a conditional guess that has been properly REd

https://github.com/RPCS3/rpcs3/issues/4072
https://github.com/RPCS3/rpcs3/issues/4062

### CODE REVIEW

**Comment by cheasea23** [comment]
sir kd-11, i have issue - persona 5 fps drop  -  #4079.
but #4011 is fine bro.

**Comment by Zangetsu38** [comment]
@cheasea23 you can test that https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.4-1296/artifacts ?

**Comment by cheasea23** [comment]
ok. i try bro. thanks reply. =D

**Comment by Asinin3** [comment]
Also, you can just try disabling the thread scheduler in the CPU options tab.

**Pull request merged**
