### PR TITLE
[Discussion] Remove DX12 renderer backend

### PR DESCRIPTION
**Pull request by TGEnigma**
It's been left unmaintained for a really long time, to the point of being labeled as 'DO NOT USE' in the GUI.

### CODE REVIEW

**Comment by TGEnigma** [comment]
Forgot to remove the files from the repo, I'll update in a sec

**Comment by elad335** [comment]
just need to save dx12 into a new branch before its being merged

**Comment by scribam** [comment]
We have a folder which contains the include and lib files for directx (https://github.com/RPCS3/rpcs3/tree/master/3rdparty/minidx12). Should it be removed too?

**Comment by TGEnigma** [comment]
It's used by the XAudio backend

**Comment by VelocityRa** [comment]
I thout the reason DX 12  is still there is very much intentional for those that still use it, who took the decision to remove it?

**Comment by TGEnigma** [comment]
It's up for debate as to whether it's worth keeping.

**Comment by VelocityRa** [comment]
Oh, well then it would be a good time for the people that still use it to speak up, I don't see anyone else being opposed to this.

**Comment by Zangetsu38** [comment]
eu what is that ? don't remove DirectX 12, it is just better vulkan for few game, and dev continue works on dx12 render, just look pr jarves,  Dx12 have better perfomance/debuging compared vulkan, and @vlj have take few month for implemente this, it is just very bad idea here

**Comment by Zangetsu38** [comment]
@TGEnigma Accorted by kd, juste remove dx12 on ui setting, for user can't set that, but not remove all code and other, only ui, dev continue wroks on this

**Comment by AniLeo** [comment]
I don't see any reason to remove this just yet

**Comment by jobs-git** [comment]
.Just keep, somebody might attempt to improve it. :)

**Comment by Sunderland93** [comment]
> DirectX 12, it is just better vulkan for few game

This means only that you need to improve performance of Vulkan renderer for that few games :)

**Comment by jarveson** [comment]
This has been discussed ever since the vulkan backend was created. Personally I'd vote to leave it, yes maintenance on it has been minimal, but that's also given the way the renderers are setup. Lots of changes can easily increase compatibility in all backends, with most of the speed changes being  backend specific. Dx12 normally hasnt regressed, just remained constant. So the reason to remove just because its 'unmaintained' doesn't seem enough, theres very little harm in leaving it. 

Another issue would be there is some cards that support dx12 but not vulkan. So hiding it from ui, or only showing with the debugtab enabled would be fine, but it will intially cause reports of it missing, which was why the [do not use] tag was added, but in some cases still may have better speed or compatibility with older cards compared to opengl

Also, the few graphics issues I've looked into and fixed have been with dx12 and pix debugger, which is a bit more reliable and feature filled than renderdoc (which used to be more crash happy with amd/vulkan, that seems to have gotten better though), im also more versed in directx api, so there may be some bias 😄

**Comment by Zangetsu38** [comment]
Ah yes good idea, hide on debug option is it good idea also

**Comment by FaithLV** [comment]
Are there actually any cards that support dx12 without supporting Vulkan?

If this is a vote, then I'd vote for removing it to reduce confusion.

**Comment by Zangetsu38** [comment]
@FaithLV What confusion?
And yes, there is the GTX 4XX she is only compatbile Dx12 and also other

**Comment by TGEnigma** [comment]
I'll close this for now, it seems enough people still care.

**Pull request closed without merging**
