### PR TITLE
RSX: Support texture blit and scaling using the GPU

### PR DESCRIPTION
**Pull request by kd-11**
- OGL: Implements texture blitting and scaling using the GPU to avoid texture readback whenever possible
- OGL: Use sampler objects instead of binding sampler state to texture handles
- VK/DX12: Lay foundation for GPU scaling implementation
- RSX: Minor bug fixes and improvements

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
This PR improves textures in Tekken Revolution.

**Master**:
image
**This PR**:
zxvafg

**Comment by MarioSonic2987** [comment]
Unrelated to this PR, there's overbloom in Tekken Revolution:
**RPCS3 (GL) - This PR (in master it's the same)**:
avzxvzv
**PS3**:
light ok

**Comment by danilaml** [comment]
@MarioSonic2987 does it run with d3d12? Does it have overbloom too (I've noticed that some games look brighter in oGL/Vulkan compared to D3D12)?

**Comment by MarioSonic2987** [comment]
@danilaml 
Nope. Hits this when I'm trying to get ingame (with AI fighting):
```
·F 0:01:23.352091 {rsx::thread} class std::runtime_error thrown: HRESULT = La instancia de dispositivo de GPU se ha suspendido. Use GetDeviceRemovedReason para averiguar cu⬠es la acci󮠡decuada.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12RenderTargetSets.cpp:280)
```
[Log DX12](https://drive.google.com/open?id=0B9LymxJkpT48eUNPU19JWFZHaFE)

Tested with https://github.com/RPCS3/rpcs3/commit/ac79654d1b8da4f5806dda5ac9646a8c6487a17b.

**Comment by MarioSonic2987** [comment]
With this PR, fire disappears when Seiya isn't moving and appears when he's moving, but with a depth issue (In Vulkan, occurs the depth issue, but doesn't disappears the fire.
[Video](https://www.youtube.com/watch?v=83inw7bGxwo)

**Comment by kd-11** [comment]
Overbloom, like the broken projection in shadows is a bug common to alot of games. Will be investigated separately.

**Pull request merged**
