### PR TITLE
Vulkan: slightly make some code closer to dx12 backend

### PR DESCRIPTION
**Pull request by vlj**
This PR convert some GL herited construct to one closer to dx12.

### CODE REVIEW

**Comment by kd-11** [comment]
I prefer to explicitly allocate/free vram to minimize errors during creation/assignment as it makes things easier to track down, but this is okay too. You should probably delete assignment/copy constructors for memory_block to avoid accidental reallocation of vram

**Comment by paulsapps** [comment]
If it needs to be reassigned you could make it movable like unique_ptr

**Comment by kd-11** [comment]
@paulsapps It still adds to code complexity from a coding point of view. Just look at the gl::glsl::program constructors and destructors and you'll see the workarounds. Maybe my c++ just sucks but it seems that we need alot of effort to work around the implicit ctor and dtor calls during stuff like make_pair or make_tuple or vector/deque push_back, etc. The older method didn't care about any of that as long as destroy or create wasn't called explicitly. On the other hand, the proposed method gives the impression of the object being completely managed, which is easier to read/use for some, I guess. Either way, it's okay with me.

**Comment by vlj** [comment]
Will resubmit the PR later

**Pull request closed without merging**
