### PR TITLE
SPU: Remove "Accurate PUTLLUC" setting (always accurate) + make PUTLLUC LR event accurate

### PR DESCRIPTION
**Pull request by elad335**
Reasons for removal:

- This setting is non-TSX only, creating even more accuracy diversion between TSX and non-TSX.
- PUTLLUC is cheaper and much rarer than PUTLLC, so if PUTLLC is always accurate so PUTLLUC should be as well.

Added even more accuracy than on master:
Fixed a race condition on LR event check when PUTLLUC is executed when a reservation is active.

### CODE REVIEW

**Comment by dio-gh** [comment]
What about accurate GETLLAR? Is the performance penalty still too big?

**Comment by elad335** [comment]
Yes, and that setting makes more sense to have as it affects both TSX and non-TSX equally.

**Comment by elad335** [comment]
* Fixed a race condition on LR event check when PUTLLUC is executed when a reservation is active (more accuracy than master)

**Comment by Hrodgaer** [comment]
Since the v10858 (2020-09-09) version can't load games from an ISO image.
I had to return to the previous version and v10857 version do work.

Messages that gives the emulator are:

E SYS: Failed to mount disc directory for the disc game BLES[...]
E GUI: Boot failed: reason: Invalid file or folder, path: E:/

**Comment by dio-gh** [comment]
Okay? This is not the PR that caused that though? Why are you commenting here, just because there's a comment section under each PR, it doesn't they're free real estate.

**Comment by elad335** [comment]
I've heard you the first time.

**Comment by Emulator-Team-2** [comment]
Before:


After:  #8888

**Comment by dio-gh** [comment]
Any dips where you arent in the hundreds of fps range?

**Comment by Emulator-Team-2** [comment]
@dio-gh It doesn't matter. MSI Afterburner also shows the same, the FPS is also lower in the game.

**Comment by dio-gh** [comment]
I mean it does matter, if the dip only exists with very high framerates it might very well be insignificant everywhere else. Otherwise it's like saying enabling the performance overlay is a performance drain, because it steals 1300 fps on the cube test elf...

**Comment by Emulator-Team-2** [comment]
Same result without the performance overlay.
Before:
S-1
G3-1

After: #8888
S-2
G3-2

**Comment by elad335** [comment]
@Emulator-Team-2 Test perf with #8462, if it doesnt fix it I'll do a partial revert.

**Comment by Emulator-Team-2** [comment]
@elad335 GOW3 probably back to normal but, no difference in Sonic Unleashed, FPS is still lower than before.

**Comment by elad335** [comment]
I need EXACT fps.

**Comment by Emulator-Team-2** [comment]
@elad335 
**10867 / 10870 after #8888 / Soon-Tm** : https://youtu.be/yxiGE45LqSk

**Comment by elad335** [comment]
Can someone test if this perf regression on Sonic affects TSX as well?

**Comment by jokoputera** [comment]
Any news regarding this PR?

**Comment by dio-gh** [comment]
It has been merged for nearly 7 months...

**Pull request merged**
