### PR TITLE
Grid Game Layout

### PR DESCRIPTION
**Pull request by flash-fire**
Mega and I both worked on this. This PR also simultaneously refactors game_list_frame to not use the Column stuff anymore. It's a bit easier to read now.

Grid uses a gradient in its selection. This will probably be refactored eventually onto list mode as I think it looks better.

The new mode is found under View->Game List Mode->Grid

### CODE REVIEW

**Comment by raven02** [comment]
It looks nice and would be good if last row can be shown as well when maximized.
untitled

**Comment by Luffykun007** [comment]
This really got very good!

**Comment by Megamouse** [comment]
@raven02 you can adjust the value in your GuiSettings file.Just set the marginFactor ever so slightly smaller.
for example from 0.1 to 0.09

**Comment by zminhquanz** [comment]
it's very nice , good job

**Comment by twdarkeh** [comment]
For this build to launch, you must delete GuiConfig folder; it is incompatible with current master's config.

**Comment by raven02** [comment]
Cool .Having set marginFactor=0.09 in GuiConfigs\CurrentSettings.ini , it displays good .

**Comment by Megamouse** [comment]
try the newest. it should be slightly better even without that value st to 0.09

**Comment by raven02** [comment]
Last column can show but it will have slider bar at the bottom which marginFactor = 0.09 didnt

**Comment by raven02** [comment]
It works perfectly now . Thx

**Comment by AniLeo** [comment]
This was still WIP..

**Comment by AniLeo** [comment]
@raven02 Not only you squashed commits from two different authors but you also merged a broken PR
image

I'm reverting this, please ask the author(s) before merging.

**Comment by raven02** [comment]
I tested and it worked ok . I don’t think it is necessarily to revert the entire PR . If something is not correct , it can be patched in another PR .

**Comment by AniLeo** [comment]
We had traced some bugs with it and they were still being fixed. Changing modes easily causes crashing. 
Reverted because master was broken with it and asked before doing so, please ask the authors before merging a PR.

**Pull request merged**
