### PR TITLE
PPU: restore previous NJ mode handling option

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Megamouse** [comment]
shouldn't the option be added back into the settings dialog?

btw, accurateXFloat enabled state is confused due to the two connects on static and dynamic.

**Comment by Megamouse** [comment]
btw, why is 
image
always disabled?

**Comment by Nekotekina** [comment]
Not sure, did anyone ever disable that option before?

**Comment by Megamouse** [comment]
it was your change in the last commit:
image

**Comment by Nekotekina** [comment]
I mean removed NJ option.

**Comment by Nekotekina** [comment]
Regarding Interpreter (dynamic), it's simply not implemented.

**Comment by Nekotekina** [comment]
Added back to GUI

**Comment by SlyCooperReloadCoded** [comment]
This breaks all games for me, all games fail to boot with:

"Thread terminated due to fatal error: NJ Not Implemented"

If I downgrade to the previous build and turn on Non-Java Mode Handling, everything works fine, and games that need it like Sly 2 also work fine.

**Comment by Nekotekina** [comment]
@SlyCooperReloadCoded you enabled wrong setting
Enable PPU Non-Jave Mode Fixup
Accurate Non-Java Mode Handling should be disabled.

**Comment by Megamouse** [comment]
why are you adding unimplemented stuff to the UI then?

**Comment by SlyCooperReloadCoded** [comment]
That fixed it.  Also yeah, generally not a good idea to add unimplemented stuff, but what do I know?

**Comment by Nekotekina** [comment]
It's implemented in interpreter. This one just got messed up.

**Pull request merged**
