### PR TITLE
VS build: delete QT DLLs from bin directory

### PR DESCRIPTION
**Pull request by henriquenj**
Commit 6cfb184b1ec798eb209272a404040e7a582516a7 added these files when
implementing a very large code refactoring. They seems to be unecessary
since there's a couple of VS post-build scripts that copy the files from
the user local QT installation to the bin directory every time the rpcs3
project is built. So their presence in the repository only makes cloning
it a little slower.

### CODE REVIEW

**Comment by henriquenj** [comment]
Pinging @flash-fire who originally added these files. It seems to me they were added by mistake, is that right?

**Comment by hcorion** [comment]
Cloning will still take the same amount of time now anyways, now that they're in the git history.

**Comment by henriquenj** [comment]
@hcorion Yes, any non-shallow clone will still download them. So this is mostly housekeeping.

**Comment by hcorion** [comment]
Have you verified that the AppVeyor build works with this fix? It uses cmake, and I'm not sure if the build copies the Qt dlls.

**Comment by henriquenj** [comment]
Just downloaded the zip file it generates. It does not work, the dlls are missing. I'll investigate exactly what AppVeyor is doing and see if I can find a solution.

Meanwhile please do not merge this.

**Comment by hcorion** [comment]
The Appveyor build just zips everything in the `bin` folder. You could probably add a special cmake step for installing the Qt dlls during the build.
IMO you should just leave the dlls where they're at, unless you fancy fiddling with Cmake, but I still don't think it's worth the effort.

**Comment by flash-fire** [comment]
Hcorion covered the exact reason I added them to the bin directory-- I'm too lazy to figure out how to do it in cmake. And, it saves hassle of figuring out the Qtdir when copying

**Comment by henriquenj** [comment]
I've used this last Appveyor build to boot some games and it seems everything is working. The Appveyor build indeed performs some strange steps, such as downloading libraries from someone's Google Drive, so it took me a while to get the CMake build running it locally.

I couldn't build on Debug mode using CMake on windows though, I'll take a better look tomorrow.

**Comment by Nekotekina** [comment]
These files are also required for VS solution build.

**Comment by danilaml** [comment]
The proper and more "robust" and correct way would be probably to use `windeployqt`.

**Comment by henriquenj** [comment]
Yesterday I had a look on `windeployqt` but I though it was tied to the nmake/qmake tools, so I was not sure how to use it with CMake. However I managed to use it locally from the windows CMD and it seems to do the job. It somehow found all the DLL files that were needed by just looking at the compiled rpcs3.exe.

The only thing different is that it actually copies more files than we actually needed it. So I'll keep the current CMake solution for now. But I agree that using the QT provided tools seems wiser in the long run.

**Comment by danilaml** [comment]
@henriquenj it's just an `exe`. You can query it's location from `qmake` and I think you get `qmake` location from `find_package`. I saw several CMake scripts do that. Or you can just don't include that part in the cmake and add it to the appveyor script (similar to how `linuxdeployqt` is used on travis).

**Pull request merged**
