### PR TITLE
[Need Testing] Implement TSX fallback

### PR DESCRIPTION
**Pull request by Nekotekina**
Remove Accurate PUTLLC option.
Implement fallback path for SPU transactions.

### CODE REVIEW

**Comment by Whatcookie** [comment]
Persona 5 is now crashing with `{RSX [0x00f6548]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x403005A0`
[P5TSXPRFA.log](https://github.com/RPCS3/rpcs3/files/3263508/P5TSXPRFA.log)

Ninja gaiden sigma 2 hangs the same way as master does

Ninja gaiden sigma 1 also hangs with semaphore_acquire timeout
[NGS1TSXPRFA.log](https://github.com/RPCS3/rpcs3/files/3263518/NGS1TSXPRFA.log)

**Comment by Whatcookie** [comment]
P5 and sigma crashes seem fixed, but performance in P5 is still bad without accurate GETLLAR set. 

Sigma 2 still hangs in the same manner

**Comment by legend800** [comment]
Motorstorm Apocalypse is still broken (see last comment here: https://github.com/RPCS3/rpcs3/pull/6020)

**Comment by incognitoh** [comment]
Good news. Testing 0.0.6-9320fec4,  MotorStorm 2 (and others) are now working again with TSX + LLVM SPU Mega. For me, SPU LLVM Mega was broken a few weeks ago when TSX was enabled but this PR finally fixes it.

(i7 4790k Haswell)

**Comment by Whatcookie** [comment]
(with force_abort microcode on commit 92ec6ab)
This PR in P5: 7 fps
Master in P5: 30 fps
Master/this PR with accurate GETLLAR in P5: 42 fps


While running `perf stat -T` (quick way to write 1 to the force_abort msr)
Master: 0 fps until I cancel
This PR: 0.22 fps until I cancel

The fallback is working, it wasn't in earlier commits. It doesn't really seem like its very useful though...

**Comment by Sztefanol** [comment]
Journey and SotC both work now on LLVM on Haswell.

**Comment by legend800** [comment]
Yep, Motorstorm Apoc. is working again with LLVM + TSX. Thanks for the regression fix!

**Comment by Whatcookie** [comment]
As discussed outside of github, recent commits improve performance for latest microcode, and almost all games have better performance than tsx off again. However...

Demon souls seems to have an issue on this pr with TSX enabled: 
flicker
geometry now flickers in and out in certain scenes. 
I tested 92ec6ab7c3d83061e6dda04ae4a8cae8a9b14306 as well (last commit before performance improvement) and its still occurring there. 

The flickering occurs every frame, and in a much more intense way after writing 1 to force_abort msr, so perhaps an issue with the fallback?
flicker2

**Comment by psennermann** [comment]
Any news about this PR? On master build at the moment TSX+LLVM seems to be broken with every game...

**Comment by ruipin** [comment]
Demon's Souls is a weird case, since the game has a specific race condition (game code, not RPCS3 fault) which causes the flicker. The more inconsistent the frame pacing, the more easily it triggers. I suspect frame pacing with the TSX fallback path is more inconsistent than before.

**Comment by Whatcookie** [comment]
Isn't the flickering you're thinking of the full screen effect which appears with write colour buffers enabled? This seems different from that, since I used a patch which disables the dynamic exposure (removes the need for write colour buffers).

**Comment by legend800** [comment]
Yeah, a ton of games are broken with LLVM+TSX on Master (25% in my set), and both are needed for good perf in a bunch of them. This seems more like hotfix to me and to prevent false positives in other PRs. 

Hopefully the Demon Souls thing can be sorted out as I don't see any other regressions noted and this can get merged soon.

**Comment by Nekotekina** [comment]
Updated PR, please test for regressions.

**Comment by Whatcookie** [comment]
Demon's souls flickering is fixed, even when writing 1 to force_abort msr. I'll edit this post if I find any regressions.

**Comment by Nekotekina** [comment]
Oh yeas, Preferred SPU Threads should be set to Auto with this PR.

**Comment by psennermann** [comment]
For now, after some quick testing, Ninokuni, Persona 5 and Shadow of the Damned seem to be ok

**Comment by legend800** [comment]
Seems like all known regressions are addressed and no new issues reported since the last commit a few days ago. Hopefully this fix pr can get merged soon as TSX is mostly broken on Master..

**Comment by Dime333** [comment]
So does all games work best with SPU threads set to auto now or is the speed gain from using a specific number of SPU threads in some games lost with this build?

**Comment by legend800** [comment]
Ironically, I did just found a regression with this. NFL Blitz (maybe other ea titles?) suffered a massive speed drop:

0.0.6-8266
TSX on:  20 fps
TSX off: 50 fps

0.0.6-8262
TSX on:  60 fps

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3313218/RPCS3.log.gz)

**Pull request merged**
