### PR TITLE
OGL: add specular and two side lighting enable

### PR DESCRIPTION
**Pull request by raven02**

### CODE REVIEW

**Comment by kd-11** [comment]
@raven02 GL_LIGHTING and GL_LIGHT_MODEL* are part of legacy openGL and were removed from core in GL 3.3. Try running the app with debug output and you should see a ton of complaints from the driver. They also wont have any effect since shaders bypass fixed-function lighting anyway

**Comment by kd-11** [comment]
Also, I think 2-sided lighting already works somewhat. Its the ssa variable in the shaders which ought to be multiplied by the lighting calculation to make it absolute. I dont know if its properly implemented for glsl backends though, but I remember fixing a compilation bug related to the variable.

**Comment by kd-11** [comment]
edge flag is also part of fixed-function pipe

**Comment by raven02** [comment]
Alright .I think we don't need to set it here then. I'm closing it then.

**Pull request closed without merging**
