### PR TITLE
rsx: Implement support for extended-length vertex programs

### PR DESCRIPTION
**Pull request by kd-11**
Some games are kinda pushing it with RSX register space and spilling VP data into adjacent unused register space. This has some unexpected implications such as bumping the number of instruction addressing bits from 9 to 10 to cover the extended address space. This PR adds support for the extended size data as well as the results of the RE work to find the missing instruction bits. Due to this, the structure of the programs has changed and this requires a shader cache version bump.

Fixes https://github.com/RPCS3/rpcs3/issues/8500

### CODE REVIEW

**Comment by SonofUgly** [comment]
Don't know if it's an issue with this, or was just exposed by this, but now there's some artifacts in Ratchet & Clank - Crack in Time (artifacts only happen on effects that were previously not rendered):
[Black box around some effects](https://i.imgur.com/o1VkGn9.png)
[Mr. Zurkon's laser filling up the screen](https://i.imgur.com/E7kvjcd.png)

**Comment by kd-11** [comment]
> Don't know if it's an issue with this, or was just exposed by this, but now there's some artifacts in Ratchet & Clank - Crack in Time (artifacts only happen on effects that were previously not rendered):
> [Black box around some effects](https://i.imgur.com/o1VkGn9.png)
> [Mr. Zurkon's laser filling up the screen](https://i.imgur.com/E7kvjcd.png)

You need to enable Read Color Buffers to fix that and probably Write Color Buffers too while you're at it.

**Comment by SonofUgly** [comment]
>You need to enable Read Color Buffers to fix that and probably Write Color Buffers too while you're at it.

Read Color Buffers fixes the black boxes, but nothing fixed Mr. Zurkon's laser (also noticed [the light in his eyes are squares](https://i.imgur.com/ZbTaOBg.png)).

**Comment by kd-11** [comment]
The fix is for the missing draw calls, remaining issues need to be tracked separately.

**Comment by psennermann** [comment]
Btw is there any hope that #7076 will ever get fixed?

**Pull request merged**
