### PR TITLE
Fix SPU count limit

### PR DESCRIPTION
**Pull request by elad335**
Old bug, related to spu groups count limit.
In the past it caused vm::main alloc LS failures, at current master it causes spu idm::create failures.

### CODE REVIEW

**Comment by Nekotekina** [comment]
This setting is not needed. It's much easier to hide fake SPU LS from SPU because it treats the whole vm::spu specially. The whole PR is a mess, limit could be increased with 1 line.

**Comment by Nekotekina** [comment]
Not to mention a possibility of no_access'ing them (debug tools can use sudo memory), but it's a TODO for some other time.

**Comment by elad335** [comment]
I want sys_memory_get_page_attribue and access violations to work with it, so yes, this setting is needed.

**Comment by Nekotekina** [comment]
You seem to only see what's in your stubborn head, ignoring any other's ideas (you look down on them) only because you want to do it only as you want. Not to mention your arrogant and borderline insulting attitude. Come back after you think a little more. Closing for now.

**Pull request closed without merging**
