### PR TITLE
Implement se_t<>::undo()

### PR DESCRIPTION
**Pull request by elad335**

### CODE REVIEW

**Comment by Megamouse** [comment]
rebase if still applicable

**Comment by elad335** [comment]
Done.

**Comment by Nekotekina** [comment]
I don't see much point in implementing "undo". What's the benefit over bit_cast? I know it's shorter, but doing "bad" things shouldn't be convenient.

**Comment by elad335** [comment]
It's more meaningful, using bit_cast makes you scratch your head a bit.

**Comment by Nekotekina** [comment]
Closing as not containing valuable changes.

**Pull request closed without merging**
