### PR TITLE
rsx: Surface cache fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Allow surfaces to inherit from multiple surfaces
- Fixes a possible reference leak when cloning surfaces
- Fixes data loss due to memory splitting

Reimplementation of https://github.com/RPCS3/rpcs3/pull/6205
Should fix some of the regressions in https://github.com/RPCS3/rpcs3/issues/5983

### CODE REVIEW

**Comment by lostromb** [comment]
dumb question: are there Appveyor builds for this specific branch? Or do I have to build the project from source myself if I want to test the changes?

**Comment by lostromb** [comment]
[nm, found it](https://ci.appveyor.com/project/rpcs3/rpcs3/builds/25996616)

**Comment by kirbyguy22** [comment]
Improves reflection behavior in Gran Turismo 6, but crashes in-game when starting a race with
`·F 0:01:58.672337 {RSX [0x0be2198]} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\surface_utils.h:340)`
PR:
gt6_surfcache_reflections_fix

Master (8385):
gt6_surfcache_reflections_master

Log:
[RPCS3_pr6213_GT6.log.gz](https://github.com/RPCS3/rpcs3/files/3394460/RPCS3_pr6213_GT6.log.gz)

**Comment by jenci8888** [comment]
I can confirm the same issue as Kirbyguy22, it crashes when loads 3D model in car dealer. (same error in the log as Kirbyguy22)

**Comment by lostromb** [comment]
Valkyria Chronicles [BLUS30196] depth regression is fixed by this PR. Even better, it appears that the game no longer requires Strict mode to render the "layers" of grass / water / bloom effects correctly

before
after

**Comment by jenci8888** [comment]
The GT Academy 2013 and GT6 reflection is fully fixed. (remains problem "mirror" view in the bumper camera and 2D trees aren't transparent background)
Before:
image

After:
image

However I just noticed with this little issue.
image

**RRC:** [BCES01893_20190716115746_capture.gz](https://github.com/RPCS3/rpcs3/files/3396565/BCES01893_20190716115746_capture.gz) (github sucks rename to gz)
**RDC:** https://drive.google.com/open?id=1OlxA7q6t2PWUK8WGnGfxOZKB-r4Q1XRq

**Comment by kd-11** [comment]
There are other complications with the PR, I'll ask for a retest when ready.

**Comment by kd-11** [comment]
@jenci8888 Confirm the memory corruption should be fixed now.

**Comment by kd-11** [comment]
Looks like I accidentally broke refelections again. Ugh.

**Comment by kd-11** [comment]
Fixed now. I had some debugging code still hanging around.

**Comment by lostromb** [comment]
Valkyria Chronicles still looks good. I tested a smattering of other games (Ni no Kuni, Minecraft, Trails of Cold Steel, Katamari, Mass Effect) and couldn't find any obvious regressions.

**Comment by Pontifice** [comment]
It seems this PR breaks GT5 for me.

I had attached logs from previous version (8386), this verson (8391) and the last at the moment (8410)

[RPCS3-8386.log.gz](https://github.com/RPCS3/rpcs3/files/3419005/RPCS3-8386.log.gz)
[RPCS3-8391.log.gz](https://github.com/RPCS3/rpcs3/files/3419006/RPCS3-8391.log.gz)
[RPCS3-8410.log.gz](https://github.com/RPCS3/rpcs3/files/3419007/RPCS3-8410.log.gz)

**Pull request merged**
