### PR TITLE
PPU LLVM: disable DSE pass

### PR DESCRIPTION
**Pull request by Nekotekina**
For #13648

### CODE REVIEW

**Comment by Nekotekina** [comment]
@solarmystic try again

**Comment by Nekotekina** [comment]
@solarmystic try again

**Comment by Levine91** [comment]
Not sure if I need to open individual issues for each game but the same thing seems to be happening now for "Tornado Outbreak" and "LUMINES Supernova", both of which were previously working. 
Each will hang on a black screen after creating a new PPU Cache. I've attached my log which should show both games.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11225905/RPCS3.log.gz)

**Comment by RipleyTom** [comment]
I have found that
```diff
--- a/rpcs3/Emu/Cell/SPURecompiler.cpp
+++ b/rpcs3/Emu/Cell/SPURecompiler.cpp
@@ -6422,7 +6422,7 @@ public:
                }
                case SPU_RdInMbox:
                {
-                       res.value = m_ir->CreateLoad(get_type<u32>(), spu_ptr<u32>(&spu_thread::ch_in_mbox));
+                       res.value = m_ir->CreateLoad(get_type<u32>(), spu_ptr<u32>(&spu_thread::ch_in_mbox), true);
                        res.value = m_ir->CreateLShr(res.value, 8);
                        res.value = m_ir->CreateAnd(res.value, 7);
                        break;
```
is necessary to fix sound in SoulCalibur2(in addition to https://github.com/RPCS3/rpcs3/pull/13651/commits/4188c52bb2343552fa6b182973ae0e3a4d27956b).

**Pull request merged**
