### PR TITLE
Qt: Fix debugger step shortcuts

### PR DESCRIPTION
**Pull request by Megamouse**
It seems like this got mixed up somehow.
Maybe I should change the help description instead @elad335 ?

### CODE REVIEW

**Comment by elad335** [comment]
Change the description, it should match the Visual Studio keys.

**Comment by Megamouse** [comment]
But isn't F10 step and F11 step into in VS?
I assume step into is the same as our step and their step is the same as our step over 🧐

**Comment by elad335** [comment]
Step into is the opposite of step over.

**Comment by elad335** [comment]
What I mean is thats just a typo in the help description I made.

**Comment by elad335** [comment]
https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-feature-tour?view=vs-2019#step-over-code-to-skip-functions

**Review by elad335 — COMMENTED** [review]
Maybe rename commit and remove bugfix label from pr because it may cause confusion.

**Comment by Megamouse** [comment]
ups. didn't see the last comment.
well, it's basically still a bugfix anyway

**Pull request merged**
