### PR TITLE
[Testers needed] Trophy hotfix

### PR DESCRIPTION
**Pull request by isshininu**
Attempt to fix #5096 
This PR fix trophy log spam in The Evil Within #5434 

Might fix or broken other things as well, need testing.

### CODE REVIEW

**Comment by elad335** [comment]
The pull request is wrong, INSTALLED means already installed.

**Comment by Hasster1** [comment]
Plants Vs Zombies still crashes after boot.

**Comment by legend800** [comment]
Sorry, no change. Still getting this upon launch:  
F {PPU[0x1000000] Thread (main_thread) [0x00446484]} MEM: Access violation reading location 0x4e9

**Comment by isshininu** [comment]
Need full log

**Comment by legend800** [comment]
Log attached:
[log.txt](https://github.com/RPCS3/rpcs3/files/2693479/log.txt)

**Comment by isshininu** [comment]
This is not a log, it's just window output.

**Comment by legend800** [comment]
Best I can do. Emu crashes if I try to Stop execution. It hangs, and I have to spam X on window to stop it. Log file is auto deleted.

**Comment by RainbowCookie32** [comment]
The compressed log is deleted on a crash afaik, you should still get RPCS3.log

**Comment by Hasster1** [comment]
I don't really know why legend didn't just took the rpcs3.log from rpcs3's folder, but here it is.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2702180/RPCS3.zip)

**Comment by legend800** [comment]
Sorry didn't know there was a non-compressed log as well. Now I know.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2703589/RPCS3.log)

**Comment by RipleyTom** [comment]
I think it is a good change as it is even if ideally we'd return installed when the trophy are already installed instead of reinstalling them each time this function is called.

But as it is this change will definitely improve compatibility and I doubt there is any drawback.

**Comment by Megamouse** [comment]
I'll merge this soon as it is at least a partial "hotfix".
We'll follow up with a better hotfix or better yet a real implementation later

**Pull request merged**
