### PR TITLE
gl/vk/rsx: Improve texture cache

### PR DESCRIPTION
**Pull request by kd-11**
This pull request seeks to improve the texture cache used by the graphical backends, particularly when CPU rendering is in use. There are some outstanding issues, but we can work those in later.

TODOS:
- [x] OpenGL support
- [ ] Vulkan support (Partly done)
- [ ] DX12 support (Partly pre-existing)

### CODE REVIEW

**Comment by kd-11** [comment]
A few issues I've encountered so far:
1. Seems like sometimes the game is using only part of a tile as a resource which implies that some kind of offset into the tile might be expected when rendering. I have not been able to find this parameter yet within the tile information, but its possible i'm overlooking something trivial.
2. GPU scaling of textures is non-trivial for DX12 and opengl requiring extra render-passes which causes fallback to CPU scaling which sucks.

**Comment by raven02** [comment]
Tested few games for regression and it looks okay

**Comment by kd-11** [comment]
Looks like glew.h bundled with travis does not have some 4.5 extensions. Will downgrade to GL4.3+extensions to support some older drivers.

**Comment by JohnGodgames** [comment]
Tested 3 games with https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-430

```
F {rsx::thread} class std::runtime_error thrown: Wrong vector size
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:157)
```

**Comment by kd-11** [comment]
@pcmaker Fixed now. Was a careless mistake on my part.

**Comment by SakataGintokiYT** [comment]
```
E {PPU[0x1000007] Thread (NU::Draw::RequestManager) [0x00932604]} RSX: gl::fence sync returned unknown error 0x0
F {PPU[0x1000007] Thread (NU::Draw::RequestManager) [0x00932604]} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:490)

```

**Comment by kd-11** [comment]
@SakataGintokiYT Read Color Buffers is not needed in most cases. Write Color Buffers should be enough, plus it keeps the performance from going too slow. I'll look into why the driver is failing to throw an error while returning an invalid return code of 0. This is not supposed to happen.

**Comment by kd-11** [comment]
I'm guessing the fault is not handled within the context of the rsx thread which is why the driver is bugging out. OpenGL contexts are only valid for the RSX Thread unfortunately, so more work is needed here. I'm concerned that leaving the caller on wait may cause a deadlock if the rsx_thread is also waiting elsewhere.

**Comment by kd-11** [comment]
@SakataGintokiYT Could you retest? I've added a crude mechanism to allow renderers to process internal work queues posted from other threads. It should fix this issue or at least minimize how often it happens.

**Comment by Zangetsu38** [comment]
@kd-11 Very good persona 4 works :) but little cut in two

**Comment by SakataGintokiYT** [comment]
@kd-11 
Problem is fixed

**Comment by kd-11** [comment]
@Zangetsu38 Screenshot and log for persona 4 would be helpful.

**Comment by Zangetsu38** [comment]
@kd-11 yes i know, i have add two in issue :) 
Actually test other game ^^

**Comment by danilaml** [comment]
@kd-11 I think that we can safely bump minimum openGL reqs to 4.4, since OS X is still stuck at 4.1 at it seems that apple is more likely to remove openGL support altogether in favor of their Metal(tm) API rather than supporting newer cross-platform open APIs and all GPUs that support 4.3 should support 4.4 too with the latest drivers (according to wiki).

**Comment by kd-11** [comment]
We should also check for required extensions support as well during init to help with non-compliant drivers. Also need to update glew library used to build on travis by the way since it does not have some newer extensions listed (such as ARB_direct_state_access)

**Comment by danilaml** [comment]
@kd-11 `ARB_direct_state_access` is oGL 4.5 though, is it not?

**Comment by kd-11** [comment]
GL4 uses a wierd extensions mechanism (core extensions). If old hardware implements an extension, it works the same as when it is made part of core (no EXT/ARB suffix). Even older terascale AMD supports this extension via GL 4.3. Ultimately GL versions > 4.3 are kinda irrelevant, you just check for extension support and it just works.

**Comment by kd-11** [comment]
@SakataGintokiYT @Zangetsu38 Please retest using latest commit: There has been a major change that could affect many games, including not requiring Write Buffers to be enabled for images to display.

**Comment by raven02** [comment]
Dai-3-Ji Super Robot Taisen Z Jigoku-hen  seems to be broken with background
untitled

**Comment by JohnGodgames** [comment]
With [gl: Manage RTV subviews as temporary resources](https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-437/artifacts)

Improvements:
- corrupted surface ground is now visible

**Baja: Edge of control**

[Video from master - VULKAN](https://www.youtube.com/watch?v=iCaLNCILexk) 
baja edge

[LOG](https://mega.nz/#!uJtnnSgY!broqAw1ig0zZXxf4SNYI_1mRdlYZMvO1O5zSrtLBGpk)

**Comment by andre4688** [comment]
Hello k11 can fix bug clive-barkers-jericho Demo version
   
gravando_2017_02_20_13_05_45_320 mp4_snapshot_00 31_ 2017 02 20_13 15 21
gravando_2017_02_20_13_05_45_320 mp4_snapshot_00 58_ 2017 02 20_13 15 52
gravando_2017_02_20_13_05_45_320 mp4_snapshot_02 18_ 2017 02 20_13 16 28

gravando_2017_02_20_13_05_45_320 mp4_snapshot_01 36_ 2017 02 20_13 16 09
gravando_2017_02_20_13_05_45_320 mp4_snapshot_02 00_ 2017 02 20_13 16 16

**Comment by Zangetsu38** [comment]
@kd-11 
Persona 4 : regression, not works with or without color buffer, black screen.
[P4.txt](https://github.com/RPCS3/rpcs3/files/787638/P4.txt)

Jet Set Radio : works only with With buffer color, but little regression for first loho not show and glitch.
[JetSet.txt](https://github.com/RPCS3/rpcs3/files/787677/JetSet.txt)
capture d ecran 2017-02-20 15 30 00

Eternal Sonata : same, menu black screen with or without black screen in menu
[EternalSonata.txt](https://github.com/RPCS3/rpcs3/files/787684/EternalSonata.txt)

**Comment by kd-11** [comment]
@Zangetsu38 Does Jet Set Radio work okay with DX12? I stopped writing buffers from RSX to Cell on every draw call and moved that functionality to semaphore release which is why there's black screens. Need to investigate further when to download from rsx.

**Comment by Zangetsu38** [comment]
no, balck screen with vulkan and Dx12

**Comment by raven02** [comment]
Dai-3-Ji Super Robot Taisen Z Jigoku-hen become red background with latest commit.

**Comment by kd-11** [comment]
Problem seems to be with ordering of commands within RSX thread. Looks like semaphore releases need to be deferred until after the other commands are processed.

**Comment by kd-11** [comment]
red/missing surfaces should have been fixed. Needs just a little more work on the timing and sync points and I can be done with this.

**Comment by raven02** [comment]
@kd-11 Dai-3-Ji Super Robot Taisen Z Jigoku-hen still getting blue background when tested with latest commit.

**Comment by Zangetsu38** [comment]
@kd-11 bug gfx with Dragon  quest builders, lightning strange.
capture d ecran 2017-02-20 23 46 11

**Comment by JohnGodgames** [comment]
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-443/artifacts

**Eat Lead: The Return of Matt Hazard**
```
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:208)
```

Some regression:
marvel3

**Comment by SakataGintokiYT** [comment]
```
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:587)
```

**Comment by raven02** [comment]
@kd-11 Dai-3-Ji Super Robot Taisen Z Jigoku-hen is gettting white background with the latest commit.
untitled

**Comment by MarioSonic2987** [comment]
```E {rsx::thread} RSX: Surface color buffer: Unsupported surface color format (0xd)```

Hits that in Skate 2 [NPEB90131].

**Comment by kd-11** [comment]
Are the regressions still an issue? Need to resolve them before proceeding with vulkan and dx12

**Comment by JohnGodgames** [comment]
With https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-448

**Eat Lead: The Return of Matt Hazard again ingame**

eat lead 25 2 1

eat lead 25 2 2

**Ultimate Marvel vs. Capcom 3 - regression**

[RenderDoc main menu](https://mega.nz/#!6ZV0CKxB!pSstsPsttAFeYzJuAnQHgjZd-nNstRXiDvjpIl8Xqik)
[RenderDoc main ingame](https://mega.nz/#!bB0hBbZB!eweYsCYE4Iw2cjFRNLHANNzh1TIvH_Qp268a3Wg1bs8)

**Dragon Ball Z: Burst Limit - regression**
dbz burst 1
dbz burst 2
`Can't capture frame (renderdoc crash)`

**How to Train Your Dragon - missing characters regression**
how to train 1

[RenderDoc select characters menu](https://mega.nz/#!nYsjxTxa!DfZmdDHGwD2e4Vsypr4Gpw7f7CP99hetZxD0ygFLifM)

**Comment by raven02** [comment]
Dai-3-Ji Super Robot Taisen Z Jigoku-hen is still getting white background with the latest commit.

**Comment by SakataGintokiYT** [comment]
NPUB30113
```
F {SPU[0x2000003] Thread (LLSpursCellSpursKernel3)} class std::runtime_error thrown: Verification failed: 
(in file C:\rpcs3\rpcs3\Emu\RSX\GL\GLTextureCache.cpp:57)
F {SPU[0x2000002] Thread (LLSpursCellSpursKernel2)} class std::runtime_error thrown: Verification failed: 
(in file C:\rpcs3\rpcs3\Emu\RSX\GL\GLTextureCache.cpp:57)
```

**Comment by Zangetsu38** [comment]
regression in P4, after menu press enter rpcs3 crash with this 
capture d ecran 2017-02-25 21 16 05

**Comment by kd-11** [comment]
Included some fixes and workarounds. Hope it fixes the regressions.

**Comment by raven02** [comment]
Dai-3-Ji Super Robot Taisen Z Jigoku-hen intro background renders correct again in GL backend.

**Comment by raven02** [comment]
DBZ burst limit seems to be still regressed at the the loading screen.

5b1ae072-fb5d-11e6-8ad8-53452cb365c1

**Comment by SakataGintokiYT** [comment]
Fotoszok.pl
Fotoszok.pl

**Comment by kd-11** [comment]
Looks like the remaining (blue tint) issues might be a result of the code re-organization and not the texture cache itself. Will update soon once I carry out some tests.

**Comment by kd-11** [comment]
First step at implementing deferred clear command. Should help with most regressions.

**Comment by raven02** [comment]
Yes , dragon ball burst limit is working well again in latest commit

**Comment by raven02** [comment]
1942 striker would be a good candidate to test it . In-game is quite flickering with the immediate clearing while the workaround one deferred clear less flickering .However master is no flickering .

**Comment by kd-11** [comment]
That's interesting. Is there any change if you disable/enable write color/depth buffers?
I'll have to test it out later and see why any bugs would be introduced.

Deferred clears are going to be a bit more work, since they'll need to be put into a queue and processed sequentially in case color masks/viewports/scissor regions are being changed.

**Comment by SakataGintokiYT** [comment]
@kd-11 
[8283d866]
Fotoszok.pl
Fotoszok.pl

**Comment by kd-11** [comment]
@SakataGintokiYT Any difference with the alternate build https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-463?

**Comment by raven02** [comment]
@kd-11 , just tested write color buffer or depth buffer not helping in this case . BTW , in master build , Vulkan got the similar flickering while GL and DX12 doesn;t

**Comment by SakataGintokiYT** [comment]
@kd-11 
Fotoszok.pl

**Comment by kd-11** [comment]
@SakataGintokiYT Thanks. That's what I was looking for. Will commit the buffer_sync2 version then.
In the meantime you can keep testing for regressions. I want to try and commit this tomorrow hopefully.

**Comment by danilaml** [comment]
@kd-11 don't forget to fix compilation on travis. It uses libglew-dev 1.10.0-3, IRC. So only 4.4 oGL core + extensions are supported.

**Comment by kd-11** [comment]
Yea, will have to clean up and rebase most of this before merge

**Comment by kd-11** [comment]
I'm going to merge this soon if there are no objections. OGL support is mostly there; vulkan has been prepped/refactored for the rewrite, DX12 is still pending.
Need testers to confirm that vulkan has not regressed.

**Comment by raven02** [comment]
@kd-11 , will test it out shortly

**Comment by Nekotekina** [comment]
Can we dispose of read/write buffer options already?

**Comment by kd-11** [comment]
We can keep them for now, just to allow ease of testing new changes to the cache. However, they shall be removed soon. The largest hurdle was figuring out how and when to read/write, which I have mostly worked out already.

**Comment by raven02** [comment]
Just tested with Vulkan backend , it got some issues below. Not too sure if it is my own problem.

1. 1942 striker - cannot even boot up
2. Arkedo 01 and Dragon Ball Burst Limit - hang up in-game

**Comment by kd-11** [comment]
Ok. Will test later when I have access to a vulkan-capable device.
Any other testers encountering issues?

**Comment by raven02** [comment]
For GL ,  1942 striker is flickering seriously in-game and you can check it out.

**Comment by kd-11** [comment]
It not flickering for me on AMD (tested with write color buffers on); maybe an nvidia thing? I'll have to retest on my NV laptop when I can.

**Comment by AniLeo** [comment]
@kd-11 1942 flickers on both NV and AMD without Write Color Buffers, with Write Color Buffers flickers on NV but not on AMD

**Comment by raven02** [comment]
@Anileo , did Vulakn work for you on your NV system?

**Comment by AniLeo** [comment]
On Vulkan I get a gray GSFrame on both systems, game doesn't boot.

**Comment by raven02** [comment]
Thanks . BTW ,the flickering is in-game not at the title screen .

**Comment by kd-11** [comment]
vulkan is now fixed

**Comment by kd-11** [comment]
About 1942: Joint Strike.
Its using indexed rendering, but the index values are not consistent between frames. They are still Red-only, Green-only and Blue-only, but the intensity varies alot, causing the pallete to fluctuate wildly. Probably a sync issue.

**Comment by kd-11** [comment]
Texture cache does not handle small texture invalidation properly! Will add commits to fix the basics here then follow up with a proper implementation later.

**Comment by kd-11** [comment]
On second thought, it might be better to just merge this in as is and add the improvements later otherwise this changeset will become too large.
The joint strike issue is pre-existing; it worked by luck before. I have a fix for it, but it will need testing of its own as it definately affects more games than just 1942.

**Comment by raven02** [comment]
Agreed . Vulkan is working again .

**Pull request merged**
