### PR TITLE
Use CELL_GCM_TEXTURE_CONVOLUTION_MAG for Mag 4

### PR DESCRIPTION
**Pull request by raven02**
This Mag filter is to calculate the weighted average of 2x3 or 3x3 texels that is close to the texel coordinate. The calculation expression for the weighted average is specified with Conv.

### CODE REVIEW

**Comment by raven02** [comment]
Will rebase it soon

**Comment by vlj** [comment]
the PR can be merged if it's rebased.

**Comment by raven02** [comment]
Done

**Comment by Nekotekina** [comment]
Merged https://github.com/RPCS3/rpcs3/commit/d76a3a40a94d97566d366eb8221586dc02a503bb

**Pull request closed without merging**
