### PR TITLE
Fix error message of RPCS3 directory with limited permissions

### PR DESCRIPTION
**Pull request by elad335**
See #5507. Should say "Cannot create RPCS3.log (access denied)." now.

### CODE REVIEW

**Comment by elad335** [comment]
Nvm, its weird.

**Comment by elad335** [comment]
Fixed.

**Comment by elad335** [comment]
This error is showed correctly now regardless if RPCS3.buf exists or not.

**Comment by Nekotekina** [comment]
Doesn't work on linux. Just opened two instances like it's nothing. On what basis you replaced fs::lock...

**Comment by elad335** [comment]
may be revisited in the future.

**Pull request closed without merging**
