### PR TITLE
vk: set border color default to opaque white

### PR DESCRIPTION
**Pull request by raven02**

### CODE REVIEW

**Comment by kd-11** [comment]
@raven02 Just re-open your previous pr and add a default case which returns white. This will break depth sampling for some games which is why I set it to black (it used to be default opaque white)

**Comment by Nekotekina** [comment]
cellGcmSetTextureBorder, no?

**Comment by kd-11** [comment]
Well, yes. The previous PR was better suited for that although vulkan only allows transparent black, opaque black and opaque white not rgba.

**Comment by raven02** [comment]
@kd-11 , i deleted the branch unfortunately but nevermind i'll do a new one with default case to opaque white. Previously i'm also thinking what value will be used for transparent black .For opaque white that set alpha to white ,i think it is 0 while for opaque black which set alpha to black , should be 255 (0xff). 

@Nekotekina .i think it is something similar to that cellGcmSetTextureBorder that set the border color to the sampler.

**Comment by kd-11** [comment]
@raven02 opaque white is all 1 (1, 1, 1, 1), opaque black is (0,0,0,1) (rgba, no transparency), transparent black is all 0 (0, 0, 0, 0)

**Comment by raven02** [comment]
Humm , probably we can split the u32 color into rgba and match this 3 cases .

**Comment by kd-11** [comment]
@raven02 cellGcmSetTextureBorderColor sets u32 while cellGcmSetTextureBorder sets a u8. I haven't checked whether we have access to the 32-bit values, but you can poke around. Its should be better matched for this, I agree.

**Comment by raven02** [comment]
Alright .I'll re-pull this previous one for this being and take a look the 32 bit values one later.

**Comment by raven02** [comment]
@kd-11 , btw , which game you test it before to show properly with opaque black . i would like to test it

**Comment by kd-11** [comment]
@raven02 Hitman 2 (shadows), also affects dragon ballz (shadows again)

**Comment by raven02** [comment]
Thanks. will test it out .

**Pull request closed without merging**
