### PR TITLE
Use more starts_with/ends_with.

### PR DESCRIPTION
**Pull request by Nekotekina**
Remove ends_with global func.

### CODE REVIEW

**Comment by Megamouse** [comment]
i think you forgot to actually remove ends_with

**Comment by CookiePLMonster** [comment]
Other potential candidates:

* `fs::get_virtual_device`
* `fs::set_virtual_device` (audit)

**Comment by elad335** [comment]
Also `lv2_fs_object::get_mp`.

**Comment by Nekotekina** [comment]
It's not that critical to replace substr for things like llvm::StringRef or string_view because they are cheeap.

**Pull request merged**
