### PR TITLE
Improve and fix sln solution

### PR DESCRIPTION
**Pull request by digant73**
Made some fixes, cleanup and improvements on the **SLN** solution (Windows only):
- fixed missing/broken clean action on some projects (e.g. `OpenAL`, `glslang`): the bug forced the user to manually remove the related working folders to be able to compile the code
- as it already happens with the **cmake** solutions, source folders (e.g. `3rdparty`, `rpcs3` etc.) are now decoupled from working folders (e.g. `lib`, `tmp` (`obj` and building `log` files). This avoids to mix working folders in folders typically under **git** control (e.g. all the projects under `3rdparty` folder)
- building folders and files are collected under the `<rpcs3_root>\build` folder, similarly to `<rpcs3_root>\build-msvc,`, `<rpcs3_root>\build-gcc` and `<rpcs3_root>\build-clang64` folders for the **cmake** solutions
- precompiled libs for `glslang` and `llvm` modules are now decoupled from the related source projects in `3rdparty` folder. Precompiled libs simply need to be placed under a more intuitive and logic `<rpcs3_root>\build\lib_ext\<$(Configuration)>-x64` folder. Previously, `llvm` required to be mixed on the existing `llvm` source project under `3rdparty` folder. Both the precompiled and compiled projects can now also coexist. In case both are configured, priority is given to the compiled version (linked to the **rpcs3** binary)

### CODE REVIEW

**Comment by Megamouse** [comment]
I'm sorry but no one asked for this

**Comment by Megamouse** [comment]
The only change I really welcome are the missing clean actions

**Comment by digant73** [comment]
> The only change I really welcome are the missing clean actions

It is a lot more easy than you can imagine at first sight. The majority of changes are simply to set the following paths on the projects to direct the output under `<rpcs3_root>\build folder`:
`$(SolutionDir)build\lib\$(Configuration)-$(Platform)\`
`$(SolutionDir)build\tmp\$(ProjectName)-$(Configuration)-$(Platform)\`
Currecntly there are several projects not having set any path (resolved by default as `x64\Release` or `x64\Debug` under the source project.
`llvm` project is simplified now using the installation folder for both `.h` reference and one `.lib` (1 folder for `.h` and 1 folder for `.lib`). The same for `glslang`'s `.lib` (while currently there are 5 folders defined in the `rpcs3.vcxproj` because the module was not installed).
`OpenAL`, `llvm` and `glslang` are currently bugged and very confusing (e.g. `llvm`'s `.h` files are searched on `3rdparty` folder while `llvm`'s `.lib`  were properly retrieved from the `llvm` installation folder. The installation folder contains both the `.h` and `.lib` needed for the `rpcs3` building. The same should be applied to the precompiled `llvm` libs (it is necessary only the installation folder while currently (in the downloadable zip file) there are two mixed folders, `llvm` folder (a copy of source folder `3rparty\llvm\llvm\llvm\include`) and `lvm_build` (a partial copy of the installation folder for `llvm` project)
Current changes make the solution linear as it is with cmake solutions fixing some bugs

**Comment by Megamouse** [comment]
Btw, the CI isn't working with this.
I assume it's downloading the pre build libs to the wrong dir?

**Comment by digant73** [comment]
> Btw, the CI isn't working with this. I assume it's downloading the pre build libs to the wrong dir?

Correct. The target folder for the precompiled libs `llvm` and `glslang` used in the CI is only `./build/lib_ext/Release-x64` (no impact on the related submodules on `3rdparty` folder)

**Comment by Megamouse** [comment]
I'll test this when i have time.

**Comment by Megamouse** [comment]
Needs a rebase

**Review by Megamouse — APPROVED** [review]

**Comment by Megamouse** [comment]
I couldn't merge this since there were still conflicts apparently.
So I merged something else that touches the same code anyway.
Needs another rebase with proper conflict solving.

**Comment by Megamouse** [comment]
This isn't working either. I can push the rebased commits if you like.

**Comment by digant73** [comment]
> This isn't working either. I can push the rebased commits if you like.



> This isn't working either. I can push the rebased commits if you like.
yes, no problem

**Comment by digant73** [comment]
I also saw those deprecated files and folders under 3rdparty in .gitgnore. I limited the removal only to the changed llvm module 
Also the following seems to be obsolete (libusb_cmake is not even existing)

```
# libusb
/3rdparty/libusb_cmake/config.h
/3rdparty/libusb_cmake/libusb-1.0.pc

```

**Comment by Megamouse** [comment]
Good catch.
I also added a commit to ignore opencv in the CI unless needed (Don't wanna add an extra PR just for that)

**Pull request merged**
