### PR TITLE
rsx: Do not require ZCULL buffer binding to enable ZPASS counting

### PR DESCRIPTION
**Pull request by kd-11**
- ZPASS data is still accessible in unbuffered mode.
  The only thing that buffered ZCULL enables is something closer to early-Z where large blocks of pixels can be dicarded earlier.
  It is strictly a performance optimization and not required for ZPASS to work.
- Update ZCULL stat calculations to take into account unbuffered Z

Fixes https://github.com/RPCS3/rpcs3/issues/10869
Fixes https://github.com/RPCS3/rpcs3/issues/7741

### CODE REVIEW

**Comment by Emulator-Team-2** [comment]
Fixes: https://github.com/RPCS3/rpcs3/issues/10869.

**Deadpool:**

<details> 
<summary>(Before/After Comparisons)</summary>

**Before** - (RPCS3-0.0.23-13986):


**After** - (PR):


</details>

--------------------------------------------------------------------------------------------------------------------------------------------
**Transformers: Fall of Cybertron:**

<details> 
<summary>(Before/After Comparisons)</summary>

**Before** - (RPCS3-0.0.23-13986):


**After** - (PR):


</details>

--------------------------------------------------------------------------------------------------------------------------------------------
**Shaun White Skateboarding:**

<details> 
<summary>(Before/After Comparisons)</summary>

**Before** - (RPCS3-0.0.23-13986 - OpenGL):


**After** - (PR - OpenGL):


</details>

**Comment by Emulator-Team-2** [comment]
Fixes: https://github.com/RPCS3/rpcs3/issues/7741.

**Dante's Inferno:**

<details> 
<summary>(Before/After Comparisons)</summary>

**Before** - (RPCS3-0.0.23-13986):


**After** - (PR):


</details>

**Comment by Darkhost1999** [comment]
How about Lucifer is he rendering in cutscenes?

**Comment by Jonathan44062** [comment]
Still an issue
image
Also, I tested with Read Color Buffers to fix black boxes, but is the same 
Maybe is caused by a different RSX bug

**Pull request merged**
