### PR TITLE
Update glext.h on version 31191

### PR DESCRIPTION
**Pull request by Zangetsu38**
Update glext.h on version 31191
Fix correct size icon with correct proportion

### CODE REVIEW

**Comment by Syphurith** [comment]
I don't know why that is killed. Maybe you can try re-run to see the result.

**Comment by Zangetsu38** [comment]
@Yes, I do not understand why.
How is the retry?

**Comment by Syphurith** [comment]
@Zangetsu38 I'm sorry i don't find a retry option.
I know it costs much memory when linking - don't know if this related to the problem.

**Comment by Zangetsu38** [comment]
@Syphurith I see, so you travis ignored then.

**Pull request merged**
