### PR TITLE
[WIP] gui: Initial implementation of boot error reporting

### PR DESCRIPTION
**Pull request by TGEnigma**
I will probably refactor emulator_result_code into exceptions for better errors that include eg paths but for now, but I'd like to know what you guys think of it first.

### CODE REVIEW

**Comment by TGEnigma** [comment]
Something broke, I'll fix it later

**Comment by Nekotekina** [comment]
It's always painful to see how ancient code (SELF decryptor) gets aggressively updated. What was the purpose of it anyway? Current logs aren't informative enough?

**Comment by MSuih** [comment]
If I understood this corrcetly, the purpose is to show an error dialog to the user to make it clearer that an error has occured. It's easier for an inexperienced user than yet another red line in console and allows error messages to be shown even when log is not visible (if user has hidden it or the project gets XMB-like fullscreen interface for booting games),

**Comment by TGEnigma** [comment]
Yes, the idea is to pipe internal error messages to the GUI and display them in a user friendly manner as opposed to barebones log error reporting.

**Comment by TGEnigma** [comment]
Closing for now, there doesn't seem to be a lot of interest in doing this right now.

**Pull request closed without merging**
