### PR TITLE
d3d12: Clean rtt related code

### PR DESCRIPTION
**Pull request by vlj**
This PR moves some code from D3D12GSRender.cpp to D3D12RenderTargets.cpp and do the usual cleaning there (a_b_c format, anonymous namespace...)

### CODE REVIEW

**Comment by vlj** [comment]
I added a commit that comment out the optimising behavior of the unreachable "function" and print message in the log (unfortunatly rpcs3 crashes "too fast" to catch the message on the console)

**Comment by danilaml** [comment]
@vlj have you seen my comment on now d3d12-wip branch?

**Comment by vlj** [comment]
@danilaml yes, I didn't include the faulting commit here.
I'm not really surprised to hear intel hd is performing better though, since the dice test is uploading a lot of vertex data per frame. I currently use a ram located buffer to store all the vertex data (since they are reuploaded each time) so dgpu has to pay the pcie overhead each time it has to access non cached vertex data whereas igpu can directly read the data in ram. 
I think I will add a copy operation to amortize the cost for dgpu though. On the other hand dice is a very specific test (only a couple of textures, lot of draw calls) so I don't think it will matter as much on real game (where there are more texture, and dgpu can access them faster).

**Comment by danilaml** [comment]
@vlj Ok. Any reason why disgaea3 "depth" is broken though (table in the starting scene)? It was working before. And depth test changes hinder performance (or were they just simply not optimal?)

**Comment by B1ackDaemon** [comment]
@vlj, i'm sorry for a bit offtopic here, but could you check messages on emunewz or join irc channel? :P

**Comment by vlj** [comment]
@B1ackDaemon yes, I will test soon.

Rebased

**Pull request merged**
