### PR TITLE
[WIP] Linux evdev joystick support

### PR DESCRIPTION
**Pull request by kirbyfan64**
Ref. #2678.

Some notes:

- On my controller, the right axis is the reverse of a normal controller (that's what I get for getting a refurbished PS2 controller + a cheap adapter), so here I set it to be the *opposite*. If anyone tries this, and it's reversed for you, then I'll change it.
- Again, with my controller, sometimes this simply won't work. I've had the issue for a long time, but if anyone else has the same issue, then I know it's a problem with the code. (Oddly enough, this seems to be happening more with the new Qt GUI than the old wx one? I'll wait to see what other people who try it say...)

### CODE REVIEW

**Comment by toccata10** [comment]
Tested on archlinux, with xpad kernel module. xbox 360 controller. Pressing on the buttons doesn't change anything. evtest shows my controller at
/dev/input/event19:     Microsoft X-Box 360 pad
So, for now and for me, it's not working at all.

**Comment by kirbyfan64** [comment]
@toccata10 What does your log say?

**Comment by hcorion** [comment]
Plug and play with my Xbox 360 controller on Arch Linux. 
Tested games:
Scogger HD
1942 Joint Strike Demo
It crashes on exit, here is the backtrace (compiled RelWithDebugInfo):
```
#3 0x0000000000bc6417 in evdev_joystick_handler::Close (this=<optimized out>) at /mnt/hd/Users/Zion/Documents/source/rpcs3-zion/rpcs3/evdev_joystick_handler.cpp:206
#4 0x0000000000bc623b in evdev_joystick_handler::~evdev_joystick_handler (this=0x7f44a0018480) at /mnt/hd/Users/Zion/Documents/source/rpcs3-zion/rpcs3/evdev_joystick_handler.cpp:33
#5 0x00000000009d5929 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f44a0018470) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/bits/shared_ptr_base.h:154
#6 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/bits/shared_ptr_base.h:682
#7 std::__shared_ptr<void, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/bits/shared_ptr_base.h:1121
#8 std::__shared_ptr<void, (__gnu_cxx::_Lock_policy)2>::reset (this=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/bits/shared_ptr_base.h:1233
#9 fxm::clear () at /mnt/hd/Users/Zion/Documents/source/rpcs3-zion/rpcs3/Emu/IdManager.cpp:88
#10 0x0000000000b97c53 in Emulator::Stop (this=0x2f4ed08 <Emu>) at /mnt/hd/Users/Zion/Documents/source/rpcs3-zion/rpcs3/Emu/System.cpp:679
#11 0x0000000000c027a9 in gs_frame::close (this=0xa27e930) at /mnt/hd/Users/Zion/Documents/source/rpcs3-zion/rpcs3/rpcs3qt/gs_frame.cpp:87
#12 0x00007f44f4bc2985 in QWindow::event(QEvent*) () from /usr/lib/libQt5Gui.so.5
```
The mappings seem off, and the log spams

**Comment by hcorion** [comment]
The mappings seem off (I'll have to do more testing)
And when I press the right trigger it spams
```
E : Joystick #0 sent axis event for invalid axis 5
```

**Comment by hcorion** [comment]
Also, the start button doesn't work.

**Comment by hcorion** [comment]
Also, for the D-pad, it seems like right and down are constantly pressed, perhaps make some dead zones?

**Comment by kirbyfan64** [comment]
@hcorion Well, at least this is some progress. ;)

> The mappings seem off (I'll have to do more testing)
> And when I press the right trigger it spams
> Also, the start button doesn't work.

This seems kind of odd, especially the right trigger. Could you post the full log? I might have to get my hands on a 360 controller...

**Comment by hcorion** [comment]
Alright, here is me spamming the right trigger while starting up ScoggerHD: 
https://gist.github.com/2573dd5b71b1200664bacff3d1e11a2a
Also, I believe you can emulate 360 controllers via Steam?

**Comment by hcorion** [comment]
What's the status on this @kirbyfan64 ?

**Comment by kirbyfan64** [comment]
So I think I have the XBox triggers almost working... @hcorion while I finish, can you try out [this homebrew](http://www.dashhacks.com/ps3/ps3-homebrew/ps3-game-pad-test-utitlity-by-developer-zar.html) and let me know if any other buttons aren't working?

**Comment by hcorion** [comment]
Hmm, yeah it's kinda broken.
Here is a video demonstrating the broken-ness: https://youtu.be/4kkQhGZUno4
Notably: 
- Start & Select are mapped wrong (I guess I can just re-map them though, I don't know how standard these mappings are)
- XABY are oriented wrong, though the benefit of having both X buttons do the same thing might be worth it?
- There is obviously something very wrong with the joysticks.
Log here: https://gist.github.com/anonymous/efdc79a7c206272386a21ecee6b51212

**Comment by hcorion** [comment]
Yo! Didn't realize you were into Nim @kirbyfan64 ! So cool to see another nimmer!

**Comment by MonokelPinguin** [comment]
I finally found the time to take a look at this.

I tested it with a PS3 controller connected via USB:
- The button mapping was wrong, which is to be expected, as the PS3 controller just maps the buttons linearly, so I wrote my own mapping file: [gist](https://gist.github.com/MonokelPinguin/564ab06665a810426e4053b708079e45)
- After that input was really laggy (10 Seconds for each button press), so I reduced the sleep interval and changed the button mapping form vector<vector<int>> to vector<unordered_map<int>>
- Currently the digital buttons can't be remapped, so I added that.

With those modifications the controller seemed to work really well. I also tried to remove the sleep and instead use select/poll, but they both increased latency by ~0.5 Seconds, which I felt wasn't acceptable. I pushed my changes to my [fork](https://github.com/MonokelPinguin/rpcs3/tree/evdev), if you want to have a look.

Currently integration with the controller remapping dialogue and rumble/button axes are still missing, but that can be done later. Well done!

**Comment by toccata10** [comment]
@MonokelPinguin: I tried your fork with a custom stick
DragonRise Inc.   Generic   USB  Joystick   (/dev/input/js0)
2 problems:
1) Although I created a config_linuxjoystick.yml in my .config/rpcs3 folder, the buttons are wrongly mapped (I used the kde joystick utility to detect the correct button number). For example, I have to press "select" instead of "start", and so on. So buttons are working but are not correctly mapped.
2) I can't figure how to declare the axis for the d-pad (no analog stick on my device).

Lastly, when I press (and release) a button, I've got this on the log:
E Unknown joystick #0 event 4
E Unknown joystick #0 event 4

**Comment by MonokelPinguin** [comment]
@toccata10

1. In my case the button order is exactly the same as in the joystick kcm. Does anything change if you swap button mappings after you tested the buttons? I.e map what was select to start. Also did you restart rpcs3 after creating the config and does the mapping change if you remove it?

2. You should be able to map axes with "Right stick - X axis" and so on, although I didn't fiddle with that. Although you currently can only map to the left and right stick axes, not the trigger, dpad, symbol buttons etc, that the original PS3 controller has on almost every button.

The unknown joystick event 4 is EV_MSC, which can be ignored. I get that too and we probably should remove that log message for EV_MSC. Basically some controllers emit this event additionally to the normal button events for every button press and it contains the key code of the pressed button. I still don't know, what the intended use is, but we don't need it.

**Comment by toccata10** [comment]
So, I finally realized that there's an offset:
in kde, the 1st button (the square) is reported as number 1. In the config file, it has to be reported as number 0.
This way, I was able to have my buttons work.

I then tried to have the d-pad working. Putting this in the config file results in a bad behaviour (rpcs3 becomes slow and freezes when I touch the stick).
Left stick - X axis: 0
Left stick - Y axis: 1

So, I removed this and saw that my X and Y axis for the d-pad were swapped (normal on my custom stick which is rotated by 90°). To make them correct, I tried to modify the 
evdev/rpcs3/evdev_joystick_handler.cpp
line 29 was:
enum { DPAD_AXIS_X = -1, DPAD_AXIS_Y = -2 };
I changed it to
enum { DPAD_AXIS_X = -2, DPAD_AXIS_Y = -1 };
No change.

I tried also a xbox360 controller. I was able to remap the buttons, but the axis are completely wrong.
the config_linuxjoystick.yml is:
`Start: 7
Select: 6
L1: 4
R1: 5
Triangle: 3
Circle: 1
Cross: 0
Square: 2`

**Comment by MonokelPinguin** [comment]
So I had a look at the axis remapping code:
Currently it works in a way, that you can only swap around the first 4 axes. So you have to remap all 4 axes or you will get duplicate mappings. I can't say why it froze rpcs3 in your case though. Maybe you can set the log to Notice and see if anything is obvious.

I don't know though, if you can remap your dpad to a stick in the way you imagine. A stick only has 2 axes, I'd imagine your pad has one for every dpad button?

**Comment by toccata10** [comment]
To make things clearer, this is what I have when I press my custom joystick: left, up, right, down. When pressing "left", by default, I have a "up" (because my axis are rotated). What I need, is a way to declare that my horizontal axis is "y" and my vertical axis is "x" (and probably, for greater flexibility, a way to declare that those axis could be reversed).
joystick configuration du systeme_272
joystick configuration du systeme_273
joystick configuration du systeme_274
joystick configuration du systeme_275

**Comment by MonokelPinguin** [comment]
Then your above mapping should be correct, but you also have to map the right axes to something else.

**Comment by kirbyfan64** [comment]
@hcorion The XBox controllers should be working now. @MonokelPinguin @toccata10 For your controllers, you'll now have to add this to the config file:

```yaml
Axis scaling: false
Z axis triggers: false
```

**Comment by kirbyfan64** [comment]
Hmm...so actually, the *Axis scaling* and *Z axis triggers* settings don't actually work ATM...

Also, I'm still trying to figure out the random crashes. They seem to consistently happen when I'm not using a debugger. :/

**Comment by MonokelPinguin** [comment]
@kirbyfan64 The newest code actually breaks my triggers and sticks (DS3). It maps my sticks to the triggers. But it doesn't crash. is responsive and the other buttons work fine.

**Comment by kirbyfan64** [comment]
@MonokelPinguin Like I mentioned above, you'd need to add two new config options to your file... except they don't work yet, so you can get the same effect by setting `Axis scaling` and `Z axis triggers` to `false` in `evdev_joystick.h`.

**Comment by hcorion** [comment]
Works perfectly! Thanks @kirbyfan64 ! Now to test my Steam Controller.

**Comment by hcorion** [comment]
Hmm, Steam Controller doesn't work. Seems to be using joystick API rather than evdev, so not your problem. Tested with Thrustmaster hotas, it works (button mappings are understandably wonky), however when I press a button it says `sent button event for invalid button 296`

**Comment by kirbyfan64** [comment]
@hcorion `sent button event for invalid button 296` just means that the button with the evdev id `296` isn't mapped to anything. You can see what the *normal* button ID is by scrolling up in the log to where the joystick was loaded.

**Comment by toccata10** [comment]
@kirbyfan64 : the xbox controller is working fine. Now, my custom arcade stick: no pbs with the buttons (with a remapping file). For the stick: by modifying the evdev_joystick.h (Axis scaling to false is all what is needed for me), I can use the stick, but still can't rotate it (when I press left, it goes up). I tried modifying a few values in  evdev_joystick.h, but it didn't change anything.

**Comment by kirbyfan64** [comment]
@toccata10 Try adding this to your mapping file:

```yaml
Left stick X axis: 3
Left stick Y axis: 2
```

**Comment by toccata10** [comment]
@kirbyfan64 : it improves things: I can now move my character. the only remaining pb is that (I'm testing with street fighter): when I go down, I jump and when I go up, I crouch. Left and right are OK.
So I tried
Left stick X axis: -3
Left stick Y axis: 2
to reverse the axis, but then up or down presses are not taken into account.
It looks like it's nearly there.

**Comment by kirbyfan64** [comment]
FWIW all I need to do is fix the random crashes, and I'm done.

@toccata10 You should now be able to do:

```
Reverse left stick X axis: true
```

to reverse the left stick. Negative axes were never supported.

**Comment by kirbyfan64** [comment]
FWIW I also made a [little WIP guide](https://gist.github.com/kirbyfan64/72f5d7223fcba2e24c4286aea9e4ccc1) on configuring the evdev gamepads.

**Comment by toccata10** [comment]
Works fine from my little testing: snappy response, the axes are now correct, no crashes (but maybe I didn't test long enough).
Suggestions: in the WIP guide, something like:
`evtest /dev/input/by-id/my-joystick | grep KEY`
code 288 is for button 0
code 299 is for button 1

and

Remapping axes is possible. For example, for a custom arcade stick with axes 90° rotated:
```Left stick X axis: 3
Left stick Y axis: 2
Reverse left stick X axis: true
Axis scaling: false```

Or give my config as an example: for a custom fighting stick made with a DragonRise_Inc._Generic, here'a another example configuration:
```
Start: 5
Select: 6
L2: 10
R2: 11
L1: 3
R1: 4
Triangle: 7
Circle: 2
Cross: 1
Square: 0
Axis scaling: false
Left stick X axis: 3
Left stick Y axis: 2
Reverse left stick X axis: true
```

Well done !
I was wondering if it was difficult to add the 2nd player input (with evdev) ? It's done on windows with Xinput: you can have 2 local players. That would bring the linux version to feature parity with windows, and fighting games are so much more fun with a friend !

**Comment by kirbyfan64** [comment]
I think you already can (though I haven't tested it, because I only have one controller), but you both have to be using the same controller type (because they both use the same config).

**Comment by toccata10** [comment]
Unfortunately the 2nd controller doesn't work: even if I press the X key, it's not detected.
fps 61 37 vulkan super street fighter 2 turbo hd npeb00036 _286
On another game (battle fantasia), the 2 players option is greyed: the 2nd controller is not detected.

**Comment by kirbyfan64** [comment]
@toccata10 Can you post your log file when two controllers are connected?

**Comment by toccata10** [comment]
Here it is+a screenshot showing that only 1 controller is detected.
[RPCS3-2joysticks.zip](https://github.com/RPCS3/rpcs3/files/1168392/RPCS3-2joysticks.zip)
2joysticks

**Comment by toccata10** [comment]
Here's my evtest
```
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event9:      DragonRise Inc.   Generic   USB  Joystick  
/dev/input/event20:     DragonRise Inc.   Generic   USB  Joystick  
Select the device event number [0-20]: 
```
The log file shows that only 1 joystick is detected.

**Comment by kirbyfan64** [comment]
What are the contents of `/dev/event/by-id`?

**Comment by toccata10** [comment]
doesn't exist. I suppose it's this
```
[jo@serveur rpcs3]$ ls /dev/input/by-id/
usb-DragonRise_Inc._Generic_USB_Joystick-event-joystick  usb-HUION_PenTablet-event-mouse       usb-HUION_PenTablet-mouse                       usb-Logitech_USB_Laser_Mouse-mouse
usb-DragonRise_Inc._Generic_USB_Joystick-joystick        usb-HUION_PenTablet-if01-event-mouse  usb-Logitech_HID_compliant_keyboard-event-if01
usb-HUION_PenTablet-event-if00                           usb-HUION_PenTablet-if01-mouse        usb-Logitech_HID_compliant_keyboard-event-kbd
usb-HUION_PenTablet-event-if02                           usb-HUION_PenTablet-if02-event-kbd    usb-Logitech_USB_Laser_Mouse-event-mouse
[jo@serveur rpcs3]$ 
```

**Comment by toccata10** [comment]
If I add a 3rd joystick (an xbox), only 1 is detected (on 3)
`·! 0:00:05.181535 {PPU[0x1000000] Thread (main_thread) [0x00010230]} Opened joystick #0 'Microsoft X-Box 360 pad' at /dev/input/by-id/usb-©Microsoft_Corporation_Controller_153466F-event-joystick (fd 20)`
```

[jo@serveur rpcs3]$ ls /dev/input/by-id/
usb-DragonRise_Inc._Generic_USB_Joystick-event-joystick  usb-HUION_PenTablet-if01-event-mouse            usb-Logitech_HID_compliant_keyboard-event-kbd
usb-DragonRise_Inc._Generic_USB_Joystick-joystick        usb-HUION_PenTablet-if01-mouse                  usb-Logitech_USB_Laser_Mouse-event-mouse
usb-HUION_PenTablet-event-if00                           usb-HUION_PenTablet-if02-event-kbd              usb-Logitech_USB_Laser_Mouse-mouse
usb-HUION_PenTablet-event-if02                           usb-HUION_PenTablet-mouse                       usb-©Microsoft_Corporation_Controller_153466F-event-joystick
usb-HUION_PenTablet-event-mouse                          usb-Logitech_HID_compliant_keyboard-event-if01  usb-©Microsoft_Corporation_Controller_153466F-joystick
[jo@serveur rpcs3]$ 
```

**Comment by hcorion** [comment]
Was able to fix using multiple joysticks by changing line 34 in rpcs3/evdev_joystick_handler.cpp from
```
 m_info.max_connect = std::min(max_connect, static_cast<u32>(1));
```
to
```
 m_info.max_connect = std::min(max_connect, static_cast<u32>(2));
```

**Comment by toccata10** [comment]
My tests:
with the added line 59:
1)with 2 xbox controllers: fine
[RPCS3-joy02-2xbox.zip](https://github.com/RPCS3/rpcs3/files/1172253/RPCS3-joy02-2xbox.zip)
2)with 1 xbox controller and 1 dragonrise (custom stick): fine (but the dragonrise remapping is wrong of course)
[RPCS3-xbox_and-dragonrise.zip](https://github.com/RPCS3/rpcs3/files/1172254/RPCS3-xbox_and-dragonrise.zip)
3) with 2 dragonrise: only 1 is detected (see logfile). Tried changing usb port: no change
[RPCS3-joy03-2dragonrise.zip](https://github.com/RPCS3/rpcs3/files/1172255/RPCS3-joy03-2dragonrise.zip)

**Comment by hcorion** [comment]
@toccata10 Can you change all instances of `/dev/input/by-id` to `/dev/input/by-path` and re-try with the dual dragonrise?

**Comment by kirbyfan64** [comment]
FWIW @hcorion you're right with the `by-id` and `by-path` distinction (https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/829), so I just pushed a commit to change it.

**Comment by toccata10** [comment]
It works ! With my dual dragonrise, I can finally have a local multiplayer. It just feels all right (very responsive). Congratulations everyone.

**Comment by toccata10** [comment]
Why limit ourselves to 2 players ? 4 players is just working as well. A little proof:
4players-01
4players-02

**Comment by kirbyfan64** [comment]
:fireworks:

**Comment by hcorion** [comment]
Hooray! Great job @kirbyfan64

**Comment by mirh** [comment]
Now, if somebody could lobby on the linux-input mailing list for an extension of evdev (or the joystick api?) to support all the axis of DS3.. that would be fantastic.

**Comment by MonokelPinguin** [comment]
@mirh Which axes do you think are missing? Afaik 20 axes are supported (4 Stick axes, 4 axes for Translation/Rotation and 12 for the buttons/triggers)

**Comment by aFoxNamedMorris** [comment]
Correct me if I'm wrong, bur didn't the DS3 have accelerometer axis?

**Comment by toccata10** [comment]
A bit more testing today: my custom stick works fine most of the time. The joystick is recognized as an analog input, which is often fine. Except on a few games (ex: Dragon's lair, Chaos code): these games are only accepting D-pad input.
In retroarch, they have an "Analog to Digital Type" which can have 3 values: none, left or right.
That's very convenient for custom sticks.
So, my humble request: is it possible to add a parameter in the config_linuxjoystick.yml which could be:
`Analog to Digital Type`
Or:
`Dpad=Left stick`
This would duplicate the input on both the analog and digital
Or:
`Dpad=Left stick digital only`
which would desactivate analog input and just keep the dpad inputs

**Comment by mirh** [comment]
> @mirh Which axes do you think are missing? Afaik 20 axes are supported (4 Stick axes, 4 axes for Translation/Rotation and 12 for the buttons/triggers)

The analog buttons axis have been dropped in 4.12 (because they were [spilling](https://www.spinics.net/lists/linux-input/msg51824.html) over accelerometers axis)

**Comment by kirbyfan64** [comment]
@toccata10 For the games only accepting D-pad input, can I see the log file?

**Comment by MonokelPinguin** [comment]
> The analog buttons axis have been dropped in 4.12 (because they were spilling over accelerometers axis)

Thanks for the heads up. I'm still on 4.9, so I didn't notice that, but I don't like it.

**Comment by toccata10** [comment]
@kirbyfan64 : Here it goes with Chaos Code followed by Dragon's Lair
[RPCS3-ChaosCode-Dpad-Only.zip](https://github.com/RPCS3/rpcs3/files/1183637/RPCS3-ChaosCode-Dpad-Only.zip)
[RPCS3-DragonsLair-Dpad.zip](https://github.com/RPCS3/rpcs3/files/1183649/RPCS3-DragonsLair-Dpad.zip)

**Pull request merged**
