### PR TITLE
Fix dumb games

### PR DESCRIPTION
**Pull request by isJuhn**
The disc version of Game of Thrones: A Telltale Games Series [BLES02215] is dumb and calls `cellGameContentPermit` on gamedata without calling `cellGameCreateGameData` first. We used to return the path to a non-existing gamedata folder which made the game think everything was fine and it dies. I made a [test](https://github.com/isJuhn/ps3tests/blob/master/cellGameContentPermit/expected.txt) and as expected we shouldn't set the path in such cases, just remove the `content_permission`.

Loadable -> Ingame (maybe playable?)
image
Thanks to Deminating for testing and the screenshot.

### CODE REVIEW

**Comment by Deminating** [comment]
Also fixes some of the PES games
PES 2011 loadable -> intro<details>
 <summary>PES 2011</summary>

rpcs3_2018-06-08_08-21-11
</details>



PES 2010 loadable -> ingame 
<details>
 <summary>PES 2010</summary>

rpcs3_2018-06-08_08-30-48
</details>

**Comment by legend800** [comment]
Wonder if it fixes:  
Peggle [NPUA30005] Trial version is perfect | Full game crashes at startup
https://github.com/RPCS3/rpcs3/issues/4411
The issue has got to be related to creating game/save folders and stuff.

**Comment by FibYar** [comment]
I think this PR breaks all Atelier games.
Tested in Atelier Rorona Plus, Atelier Ayesha, Atelier Escha & Logy. All of them gives an error while starting:
```
E {PPU[0x100000e] Thread (installGameDataThread) [0x00062b3c]} cellSysutil: Atelier Rorona Plus is being installed on your HDD.
The HDD access indicator will flash during installation. Please do not power off the system.
S {rsx::thread} RSX: New program compiled successfully
E {PPU[0x100000e] Thread (installGameDataThread) [0x002203cc]} cellSysutil: Installing.

E {PPU[0x100000e] Thread (installGameDataThread) [0x00e85fc8]} 'sys_fs_mkdir' failed with 0x80010014 : CELL_EEXIST, “/” [1]
E {PPU[0x100000e] Thread (installGameDataThread) [0x00e85fc8]} 'sys_fs_mkdir' failed with 0x8001003a : CELL_ENOTMOUNTED, “/Res/” [1]
E {PPU[0x1000000] Thread (main_thread) [0x0021ecfc]} cellSysutil: Installation failed.
You must delete and reinstall the game data to play this game.
```

**Comment by Nekotekina** [comment]
Should be fixed in master.

**Comment by amateur-tester** [comment]
That update killed Persona 5 Please Fix it all i have just black screen tried to clear all caches but nothing worked
untitled2

**Comment by AniLeo** [comment]
Did you read the comment above?..

**Comment by FibYar** [comment]
It works now. Thanks!

**Pull request merged**
