### PR TITLE
PPU: implement MFVSCR instruction

### PR DESCRIPTION
**Pull request by raven02**

### CODE REVIEW

**Comment by Nekotekina** [comment]
This doesn't implement anything. VSCR consists of two flags, `PPUThread::SAT` and `PPUThread::NJ`. And we need deeper investigation about its actual usage. Old interpreter already had working implementation.

**Comment by raven02** [comment]
I see. Do you mean some other instructions like VADDSBS - need to set the SAT flag ?

**Comment by Nekotekina** [comment]
Yes, they were "optimized" on purpose. If you didn't read my answer somewhere yet, this functionality must be restored in "precise" interpreter.

**Comment by raven02** [comment]
Understood.Probably out of my capability at this moment . I will leave it then .

BTW , the GUI show the PPU fast and precise , so basically they are point to the same which is the previous interpreter 2 , right ?

**Comment by Nekotekina** [comment]
Yes, sort of.

**Comment by raven02** [comment]
Thanks

**Pull request closed without merging**
