### PR TITLE
[WIP] Implement TSC calibration

### PR DESCRIPTION
**Pull request by Nekotekina**
Try to get rough TSC frequency by sampling it.
Should fix "TSC: Bad" in most cases.

Please report your results after running RPCS3 several times (10-20).

### CODE REVIEW

**Comment by HerrHulaHoop** [comment]
Shows TSC correctly now. Ran it over 10 times and only the last 2 digits would change. Rarely the third digit from the end would also change. 

RPCS3 v0.0.9-4f8c3ee2 Alpha | fixup | Firmware version: 4.85
Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz | 8 Threads | 15.94 GiB RAM | TSC: 3.597932GHz | AVX+ | FMA3

**Comment by dio-gh** [comment]
20 tests on my i7 7700HQ:

TSC: 2.807999GHz
TSC: 2.808000GHz
TSC: 2.808003GHz
TSC: 2.807999GHz
TSC: 2.808000GHz

TSC: 2.807998GHz
TSC: 2.807997GHz
TSC: 2.807997GHz
TSC: 2.808004GHz
TSC: 2.808000GHz

TSC: 2.807989GHz -- first bigger diff
TSC: 2.808005GHz
TSC: 2.807997GHz
TSC: 2.807938GHz -- chrome video playing started
TSC: 2.807992GHz

TSC: 2.808092GHz
TSC: 2.808059GHz
TSC: 2.807894GHz -- wtf?
TSC: 2.808009GHz
TSC: 2.807998GHz

**Comment by Kravickas** [comment]
10times +
range between TSC: 3.299990GHz - TSC: 3.299998GHz

Nothing fancy running

**Comment by xddxd** [comment]
ran it 20 times on a Ryzen 7 2700
1 TSC: 3.193991GHz
2 TSC: 3.193986GHz
3 TSC: 3.193974GHz
4 TSC: 3.193992GHz
5 TSC: 3.193991GHz
6 TSC: 3.193991GHz
7 TSC: 3.193990GHz
8 TSC: 3.193990GHz
9 TSC: 3.193991GHz
10 TSC: 3.193990GHz
11 TSC: 3.193991GHz
12 TSC: 3.193992GHz
13 TSC: 3.193991GHz
14 TSC: 3.193994GHz
15 TSC: 3.193989GHz
16 TSC: 3.193979GHz
17 TSC: 3.193989GHz
18 TSC: 3.193989GHz
19 TSC: 3.193990GHz
20 TSC: 3.193989GHz

**Comment by MsDarkLow** [comment]
Ran 10 times on 8700k@5GHz

RPCS3 v0.0.9-4f8c3ee2 Alpha | fixup | Firmware version: 4.84
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz | 12 Threads | 15.96 GiB RAM | AVX+ | FMA3 | TSX

TSC: 3.696000GHz
TSC: 3.696006GHz
TSC: 3.696001GHz
TSC: 3.696005GHz
TSC: 3.695997GHz
TSC: 3.696004GHz
TSC: 3.695993GHz
TSC: 3.696003GHz
TSC: 3.696004GHz
TSC: 3.696000GHz

**Comment by Nekotekina** [comment]
Back to 2 digits after dot.

**Comment by Augusto7743** [comment]
Have problems if using in Windows 10 Pro 64 1809 "bcdedit /set useplatformclock true" ?
If using bcdedit /set useplatformclock true the latency is 500 us and if using bcdedit /set useplatformclock false latency is 1000 us.
bcdedit /set useplatformclock true enable HPET ? If yes here using HPET the RPCS3 is more fast than if using "bcdedit /set useplatformclock false" ( TSC ?).
The CPU is FX-6300.

Is very much mess in internet about timers.
Timers are used to schedule threads ?

Well I will test using bcdedit /set useplatformclock false with 0.0.9-10134 and will report the result.

**Pull request merged**
