### PR TITLE
High DPI Icons

### LINKED ISSUE #5885: Qt: Circle in compatibility list
The circle indicating the compatibility of a game is quite jagged. This is particularly annoying on an HiDPI screen:

blobs

I've had a look at the code and attempted a few fixes for this, including...

...QPainter's normal Antialiasing...
antialiased

...and QPainter's "HighQualityAntialiasing":
highqualityaa

I've attempted a few other methods as well, but to my eye they all look either jagged or blurry or not like circles at all. There might well be a way to actually make the circles round, but I haven't found one.

A possible remedy for this might be changing the circle into...

...a square...
square

...or a rectangle:
blips

Personally, I prefer the last alternative as I think the geometry fits the rest of RPCS3:

rectangles

If someone more experienced than me could figure out a way to make the circle round that might be the best solution, however.

At any rate, I suggest a vote: https://www.strawpoll.me/17884582

### PR DESCRIPTION
**Pull request by Megamouse**
Improves Game Icon quality when using a higher device pixel ratio.
Improves the game compatibility circle icon quality.
fixes #5885

Please test on different monitors (especially on 4K devices) with different window and/or icon scaling.

Thank you @drysalter for the circle idea and Daginatsuko for showing me how bad the game icons actually look on her monitor.

**My results on a 4K Screen with 200% window scaling:**

List Circles:
image

Grid Circles:
image

List Icons (Smallest icon scale):
image

Grid Icons (Smallest icon scale):
image

Grid Custom config icons:
image

### CODE REVIEW

**Comment by MSuih** [comment]
Woudn't this need to be changed as well?
https://github.com/RPCS3/rpcs3/blob/a703460fc6837c4cd4799fa133955c939b5b974c/rpcs3/rpcs3qt/game_list_frame.cpp#L1049

Also, I've read somewhere that wrapping the arguments inside QRectF could improve accuracy when dealing with non-integer scale factors. We could also consider applying some antialiasing to the circles to further improve smoothness of them.

**Comment by Megamouse** [comment]
it's bugged anyway.

**Comment by drysalter** [comment]
I've tried this out. In list view both the game icons and the circles look much better. In grid view, the game icons look good, but at the larger sizes the circles look a bit jagged, perhaps due to their outline.

**Comment by Megamouse** [comment]
@drysalter I fixed the circle offset. But actually most of the offset originates in the font and not the circle itself.
And btw, I actually didn't even try to improve the circles in the game grid...
But ironically they will look a lot better with higher pixel ratios as a side effect of my game icon commit.

@MSuih I won't be using qreal for now since I have already exhausted my patience with these changes and I don't wanna test it anymore XD.
Also, the icons look a lot better in any configuration I tested and tbh I never really noticed it before Daginatsuko pointed it out.... so I guess this would be a very minor nitpick if someone notices anything at all.

**Comment by Megamouse** [comment]
I added some screenshots of my results

**Comment by drysalter** [comment]
Ah, apparently the alignment depends on the size the user sets.

I suppose the custom config icon can't be fixed by setting the pixel ratio since it's a .png?

**Comment by MSuih** [comment]
The image resource for custom config is fairly large, you'd have to stretch it quite large before you'll start seeing individual pixels. Still, having it (and the other icons) as an .svg would be neat, but that'd require redrawing.

**Comment by Megamouse** [comment]
Well... I applied the same approach for those config icons now.
But I really don't wanna make this an overhaul.
Honestly I only intended to fix the game icons on 4K screens and not the whole GUI ;)

custom config icons in the game grid: (remember, this is zoomed in)
image
image

**Comment by drysalter** [comment]
Looks much better on my end too, thanks!

**Comment by DanteBC** [comment]
Mega, can you also maybe add white outline on custom config icons? They're kinda hard to see on gray background sometimes. I can post examples if you want

**Comment by Megamouse** [comment]
no, sorry

**Pull request merged**
