### PR TITLE
rsx: add boost mode shortcut

### PR DESCRIPTION
**Pull request by Megamouse**
I've had this lying around for ages but never added it because I wanted to implement the shortcut manager first (which never happened).
So I'll just make a draft and see what happens.

### CODE REVIEW

**Comment by MSuih** [comment]
Should this also affect vblank? It's very limited if it only affect games that have unlimited fps.

**Comment by kd-11** [comment]
> Should this also affect vblank? It's very limited if it only affect games that have unlimited fps.

That would need another set of hotkeys.

**Review by kd-11 — COMMENTED** [review]
Code itself is fine, but the shortcut isn't.
Ctrl+O is a shortcut for the verb "Open" and opens a file dialog in other applications. Can we use something better?

**Comment by Megamouse** [comment]
It's 0 not O.
And yes. The shortcut is the only reason why it wasn't merged yet, because I am waiting for better suggestions

**Comment by kd-11** [comment]
Can we use function keys? Like Ctrl+F10 or something (macos can have different shortcuts)

**Pull request merged**
