### PR TITLE
vk: Implement support for VK_VALVE_attachment_feedback_loop_layout

### PR DESCRIPTION
**Pull request by kd-11**
Original discussion at https://gitlab.freedesktop.org/mesa/mesa/-/issues/4411

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Nice, I would not merge this however until the extension Iis properly available as stuff may change.

**Comment by kd-11** [comment]
This still needs testing as well and I don't have a RDNA card on hand. Seems to run fine on Polaris though.

**Comment by hakzsam** [comment]
> This still needs testing as well and I don't have a RDNA card on hand. Seems to run fine on Polaris though.

DCC for GENERAL is only enabled on RDNA1+, so Polaris/Vega are not affected..

**Comment by kd-11** [comment]
Closing for now. I'll reopen if needed down the line.

**Pull request closed without merging**
