### PR TITLE
Update to LLVM 5 (In slowcooker) (testing wanted)

### PR DESCRIPTION
**Pull request by hcorion**
**DO NOT MERGE**
LLVM 5 has finally been released!
Please test for regressions.
If you do find any regression, make sure to send log and Data folder.

If you do want to test, you will need to manually delete the previously generated LLVM objects.

We're holding off on merging this until some Linux distros have updated their llvm to 5.

---

Thanks to @Zangetsu38 for working on the AppVeyor and MSVC build.

### CODE REVIEW

**Comment by Asinin3** [comment]
I get an infinite loading screen with 3fd45e3 in persona 5.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1286389/RPCS3.log.gz)

**Comment by Zangetsu38** [comment]
@Asinin3 Yes issue for this game is Know. 
Also for both "DB: Raging blast" glitch render.
And for Beyond and lbp karting fatal error, maybe forget other

**Comment by Zardas81** [comment]
Some games now crash immediately with `F {PPU[0x1000000] Thread (main_thread) [0x00ba4cd4]} MEM: Access violation reading location 0x4`
- Ar nosurge [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1288317/RPCS3.log.gz)
- Atelier Ayesha [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1288332/RPCS3.log.gz)
- Atelier Escha [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1288341/RPCS3.log.gz)
- Atelier Shallie [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1288348/RPCS3.log.gz)

**Comment by Zangetsu38** [comment]
@Zardas81 post also folder data for this game with obj llvm

**Comment by Zardas81** [comment]
[BLUS31478.ZIP](https://github.com/RPCS3/rpcs3/files/1288451/BLUS31478.ZIP)

**Comment by hcorion** [comment]
After doing some research, it appears replacing v2+2E46B0-CA8DD8A538121CD2-cpumodel.obj with the llvm 4 object in Persona 5 (NPEB02436), fixes the loading.

**Comment by Nekotekina** [comment]
cpumodel? what the hell with this thing

**Comment by hcorion** [comment]
When I said cpumodel, I meant it generically, for example, mine says haswell, but if you're on ryzen, it says zenver1.

**Comment by lvonasek** [comment]
On Kubuntu 17.10 there are some compile problems:
Emu/Cell/PPUTranslator.h : AttributeList -> AttrBuilder
rpcs3/Emu/Cell/PPUTranslator.cpp:
-       , m_pure_attr(AttributeList::get(m_context,AttributeList::FunctionIndex, AttrBuilder().addAttribute(Attribute::NoUnwind).addAttribute(Attribute::ReadNone)))
+       , m_pure_attr(std::move(AttrBuilder().addAttribute(Attribute::NoUnwind).addAttribute(Attribute::ReadNone)))

**Comment by woj1993** [comment]
Title | Serial | Status | Additional info
-|-|-|-
Avoidance | AVOIDANCE | Works
Cascade Benath | CASCADEBE | Works
Dont Get Crushed | DGCRUSHED | Works 
Goodbye World | GDBYEWRLD | Works
Maze generator | MAZEGENRT | Works
Slime Roll | SLIMEROLL | Works
Ufo Racer | UFOR00000 | Works | (The same bug as master. You can't turn your vehicle).
Paintown | Paintown_ | **Error** | **Wait for test on master!** (class std::runtime_error thrown: Unregistered PPU function)
Naruto Ultimate Ninja Storm Demo | NPEB90080 | Works |**Wait for test on master!** (New error (deregisterEHFrames() called))

P.S. Wait. More games testing coming with edit.

**Comment by hcorion** [comment]
@woj1993 No need to re-test, I just rebased with master, none of the LLVM 5 port has changed.

**Comment by toccata10** [comment]
Arch moved to llvm5, so I had to use this PR to have a working rpcs3.
R9 fury, mesa 17.2
Seems ok (but it's hard to compare to master as I didn't test too much lately).
With Vulkan, I have to select "auto load required libraries" as "liblv2.sprx only" gives me a lot of crashes (maybe it was the case on master too).

**Comment by woj1993** [comment]
@hcorion There are errors in: Dragon Ball Raging Blast 2 Demo and Naruto Ultimate Ninja Storm Demo.
I did test before any rsx changes were made but, can you rebase it on master?

**Comment by hcorion** [comment]
Done @woj1993

**Comment by woj1993** [comment]
@hcorion My CPU is Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz. GPU: ASUS NVIDIA GT440 1GB GDDR3 OpenGL

LLVM5 | LLVM4|Links
-|-|-
obraz|obraz|LLVM4:https://www.dropbox.com/s/belcmk9khmrohgc/LLVM4%20Dragon%20Ball%20Raging%20Blast%202%20Demo.7z?dl=0 LLVM5: https://www.dropbox.com/s/dgk15pxwifyo6zv/LLVM5%20Dragon%20Ball%20Raging%20Blast%202%20Demo.7z?dl=0
New error (deregisterEHFrames() called) It doesn't change anything?| | LLVM4:https://www.dropbox.com/s/p5c6f8k7bxl77yk/LLVM4%20Naruto%20Ultimate%20Ninja%20Storm%20Demo.7z?dl=0 LLVM5:https://www.dropbox.com/s/kk4zqi6fwqmorla/LLVM5%20Naruto%20Ultimate%20Ninja%20Storm%20Demo.7z?dl=0

P.S. What are pros and cons of LLVM5?
AND
Write when I can delete these files from my dropbox. Stupid Github "You wanna add 7zip. What is that?"

**Comment by hcorion** [comment]
LLVM 5 is obviously quite broken for us, I'll close this PR for now. Hopefully will be fixed in LLVM 5.0.1.

**Comment by Zangetsu38** [comment]
i don't sur problem caused by llvm 5 directly, just llvm 5 have very changed compared llvm4, i just think need update ppu llvm in rpcs3, llvm4 have same think before, 3.9 worked but no 4.0

**Comment by Enverex** [comment]
@hcorion Is it worth at least having a bug opened for LLVM5 at the moment? Because anyone on a distro using it simply can't compile in LLVM support which essentially makes RPCS3 unusable (as it's just too slow without it). As of right now there's no open tickets specifically for LLVM5.

**Comment by hcorion** [comment]
@Enverex #3554 addresses the issue by just building using the llvm submodule (of course, this won't work with the ArchLinux AUR pkg because it's not checked out).

I feel like this is a bug in LLVM 5, but I don't have the experience/know how with LLVM to report a useful bug report to LLVM. I've asked Nekotekina to look into LLVM 5, perhaps he can figure it out.

**Pull request closed without merging**
