### PR TITLE
Fix one TSX regression

### PR DESCRIPTION
**Pull request by Nekotekina**
With this patch, RDR is able to start with default settings with TSX enabled.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Okay, I think I reclaimed most of the performance in SPU Test. I cannot test TSX-FA though.
```
SPU Test v1.1.2 by GalCiv
SPU Task Avalanche completed in 2122 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2032 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 7688 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 9836 ms (PS3: 4443 ms)
SPU Integer Perf completed in 2654 ms (PS3: 8666 ms)
SPU Float Perf completed in 786 ms (PS3: 2379 ms)
SPU SpinLock completed in 7048 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 4685 ms (PS3: 3853 ms)
PUTLLC Perf completed in 6439 ms (PS3: 3364 ms)
PUT Perf completed in 2305 ms (PS3: 3984 ms)
Large PUT Perf completed in 1531 ms (PS3: 4454 ms)
--Completed 11 tests in 47135 ms--```

**Comment by Nekotekina** [comment]
Another update makes PUTLLC Perf almost identical to PS3, on-par with non-TSX path. I suspect it only uses unmodified stores though.

**Comment by Xcedf** [comment]
Tested it with my games, works pretty well so far, no regressions, also it seems to help  a lot with stability in games like Infamous, Uncharted games and TLoU, which has same sound/script fails like RDR. I'm on 9900k, TSX unlocked.

**Comment by Xcedf** [comment]
My results:
Without PR

> SPU Test v1.1.0 by GalCiv
> SPU Task Avalanche completed in 1311 ms (PS3: 2740 ms)
> PPU/SPU Ping-Pong completed in 2082 ms (PS3: 3045 ms)
> SPU MFC 64 Bits War completed in 14490 ms (PS3: 3370 ms)
> PPU/SPU MFC 64 Bits War completed in 14975 ms (PS3: 4443 ms)
> SPU Integer Perf completed in 1897 ms (PS3: 8666 ms)
> SPU Float Perf completed in 494 ms (PS3: 2379 ms)
> SPU SpinLock completed in 5019 ms (PS3: 4409 ms)
> PUTLLUC Perf completed in 14581 ms (PS3: 3853 ms)
> PUTLLC Perf completed in 13954 ms (PS3: 3364 ms)
> PUT Perf completed in 952 ms (PS3: 3984 ms)
> Large Put Perf completed in 1291 ms (PS3: 0 ms)
> --Completed 11 tests in 71063 ms--

With PR:

> SPU Test v1.1.0 by GalCiv
> SPU Task Avalanche completed in 1399 ms (PS3: 2740 ms)
> PPU/SPU Ping-Pong completed in 1897 ms (PS3: 3045 ms)
> SPU MFC 64 Bits War completed in 3971 ms (PS3: 3370 ms)
> PPU/SPU MFC 64 Bits War completed in 4685 ms (PS3: 4443 ms)
> SPU Integer Perf completed in 1897 ms (PS3: 8666 ms)
> SPU Float Perf completed in 489 ms (PS3: 2379 ms)
> SPU SpinLock completed in 2617 ms (PS3: 4409 ms)
> PUTLLUC Perf completed in 2490 ms (PS3: 3853 ms)
> PUTLLC Perf completed in 1661 ms (PS3: 3364 ms)
> PUT Perf completed in 933 ms (PS3: 3984 ms)
> Large Put Perf completed in 1274 ms (PS3: 0 ms)
> --Completed 11 tests in 23326 ms--

**Comment by AphelionWasTaken** [comment]
I haven't noticed and regressions or performance improvements. This does seem to improve stability in Naughty Dog games with TSX enabled, as mentioned above.

Fallout 3/NV have also been a bit unstable with TSX in the past - this PR does not seem to improve stability in these games with TSX enabled, nor does it make it worse.

**Comment by coolllman** [comment]
massive 10 fps drop in uncharted 2 on non tsx i-7 11700

**Pull request merged**
