### PR TITLE
Resolve conflict for rsx branch

### PR DESCRIPTION
**Pull request by raven02**

### CODE REVIEW

**Comment by Syphurith** [comment]
@raven02 Oh well those are set now. Even it could be done much easier, using your own branch (which have the old commits) with a restarted `rsx` branch on aafd5c01811386d0fe50165a58b081d042e7cd1a in RPCS3/rpcs3. As from https://github.com/RPCS3/rpcs3/pull/1056#issuecomment-92227268. That is all okey if commit logs are not important.

**Comment by raven02** [comment]
Using my original rsx branch would be nice too but need to resolve lots of conflicts .

**Comment by Ekaseo** [comment]
The rsx branch builds now, but everything i run instantly crashes the emu. I will try to rebuild it one more time to confirm this

**Comment by Ekaseo** [comment]
ok, confirmed it that everything crashes, here is a log from psgl samples (basic cg) https://www.sendspace.com/file/5xablv

**Comment by raven02** [comment]
@Ekaseo , please have interpreter set to run . Interpreter 2 is somehow not working and crash.

**Comment by Nekotekina** [comment]
This doesn't even compile for me, and it seems terribly broken.

**Pull request merged**
