### PR TITLE
SPU: improve analyser [WIP]

### PR DESCRIPTION
**Pull request by Nekotekina**
Detailed description is under construction.

### CODE REVIEW

**Comment by Psycho-A** [comment]
May this fix #4643, #4703 or #4702?

**Comment by Nekotekina** [comment]
Potential fixes are applied to solve the problem of crashing on the first run with SPU LLVM.

**Comment by alex88510** [comment]
ToCS previously will hang on SPU LLVM. 
With this PR, it is able to load and play intro video but later crash the emulator.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2119700/RPCS3.log.gz)

**Comment by isshininu** [comment]
With this PR I can test games, if they are SPU LLVM-compatible?

**Comment by Nekotekina** [comment]
Wait until next PR update though.

**Comment by isshininu** [comment]
With this PR Silent Hill Downpour goes ingame in SPU LLVM for the first time.
No sound ingame, only in start menu.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2123574/RPCS3.log.gz)

P.S.
>F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Compilation failed

Same compilation error for Demon's Souls, though i am not sure if this game was even tested before.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2123589/RPCS3.log.gz)

**Comment by spyropt** [comment]
Persona 5 ASMJIT
F {SPU[0x2000001] Thread (gfdSpursCellSpursKernel1) [0x0b5b8]} MEM: Access violation writing location 0xffdead00
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2128647/RPCS3.log.gz)

**Comment by Hasster1** [comment]
That's a really great idea - to merge the PR with giant [Work In Progress] words.

**Comment by spyropt** [comment]
The last of us now locks before showing Naughty Dog logo
tryed with cpu blit/wcb and without on asmjit
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2128682/RPCS3.log.gz)

**Comment by AniLeo** [comment]
It's his PR, it's a great idea to merge whenever he feels like it

**Comment by Emulator-Team-2** [comment]
@spyropt 
img_20180622_203658

**Comment by spyropt** [comment]
@Emulator-Team-2  dont know why you directed that to me but ok, if its not to report regressions... i simple stop doing it.
The same applies to all the user writing in this github.
lets delete all the issues by the way since its an emulator and not some shitty game...

**Comment by AniLeo** [comment]
**Persona 5 w/ SPU ASMJIT**

image

**Comment by Nekotekina** [comment]
@spyropt Maybe you need to delete SPU cache, if you tested this PR before merge. Or need more information to reproduce.

**Comment by spyropt** [comment]
@Nekotekina did a fresh install and the same thing happens, could be because my cpu does not support avx/tsx
spu llvm works fine
The master build before this pr works

**Comment by AniLeo** [comment]
My test was done on a non-TSX CPU, but has AVX, AVX2 and XOP

**Comment by spyropt** [comment]
@AniLeo Ijust tested on a 3770k avx cpu and it works fine on asmjit
on my other cpu x5675 just goes in infinite loading
image

with F {SPU[0x2000004] Thread (gfdSpursCellSpursKernel4) [0x0b5b8]} MEM: Access violation writing location 0xffdead00

usually i do all my tests on the x5675 since its an arcade machine just for emulation

**Comment by Nekotekina** [comment]
Reproduced! AVX cpu are unaffected.

**Comment by psennermann** [comment]
I have an AVX+ cpu (i5 7400 - no TSX) and I think that this PR causes Demon's Soul (maybe other games as well?) to reliably hang/crash on my system…

Win10
Gtx 1060 3gb
i5 7400

**Pull request merged**
