### PR TITLE
Enable styling of dynamic settings

### PR DESCRIPTION
**Pull request by Megamouse**
This adds the dynamic_setting property to most widgets in the settings dialog that directly affect a dynamic config.

I can't decide on a style, so I figured I'd let you guys play with it for yourself.

You can use it in the stylesheets e.g. like this:

```
QCheckBox[dynamic_setting="true"] {
	color: red;
}
```

### CODE REVIEW

**Comment by lainiwaku** [comment]
what about bold ? 
 
Annotation 2020-04-21 061357

**Comment by lextra2** [comment]
+1 for making them bold. and maybe use green instead of red since red might confuse some people and make them think they did something wrong.

and don't use pure green. use something like `#00b200`

**Comment by Kravickas** [comment]
I dont like both. I tried some background lines, gradient 💩   etc and i dont like anything.

In my opinion, i would just ''hardcode it'' by adding some special character that is visible same on win, lisux etc..

like this _(photoshop)_
dynamic
With explanation at the default description box.

**Comment by Megamouse** [comment]
Ugh forgot about this. I'm not gonna add this if noone comes up with a nice style

**Pull request closed without merging**
