### PR TITLE
Atomic fix

### PR DESCRIPTION
**Pull request by Nekotekina**
Please test #6536

### CODE REVIEW

**Comment by Lenox548** [comment]
Do I test?

**Comment by Nekotekina** [comment]
Welp, I reverted offending commit for now. Should be ok.

**Comment by proganime1200** [comment]
graphical glitches occured on persona 5 and some lags

**Comment by AniLeo** [comment]
Very insightful report

**Comment by Lenox548** [comment]
> graphical glitches occured on persona 5 and some lags

Where? i've tried playing now that this pr has become master and the game runs well again, i'd say that now runs even better than before

**Comment by Megamouse** [comment]
Memo for the report:
This also fixed a bug (regression?) that locked up the entire emulator when closing games during HLE videos.

**Pull request merged**
