### PR TITLE
[Roadmap] Simple thread pool

### PR DESCRIPTION
**Pull request by bd339**
The aim of this PR is to implement "simple threadpool" from the roadmap. The overall approach is to avoid touching the existing code too much. What I'm looking for is comments on this particular approach and if it looks reasonable, review on the actual implementation.

First some caveats of this approach:

- **Names are not guaranteed to take effect** Code might call `thread_ctrl::start` with a named thread_ctrl, but the point of the thread pool is to not spawn a new thread on each call. So there is no guarantee that the executing thread has the desired name
- **Multiple pieces of code can own a thread and control it** Arguably that's just the semantics of `shared_ptr`, but it's worth keeping in mind that the `shared_ptr` you give to `thread_ctrl::start` can be redirected to an existing thread, and that thread could also be controlled elsewhere

Now some notes / questions:

- There is no bound on the number of threads created (as before). Should there be?
- Safe shutdown of all the threads in the pool is not yet implemented

Steps (aka what the code is (meant to be) doing):
1. add queue of threads waiting for work
1a. add a cond var to each thread to wait on work

2. update thread_ctrl::finalize
2a. don't decrement thread counter or release self reference in finalize, unless the thread is dead
2b. reset thread-local state when calling finalize on a live thread, since we'll be reusing it for a different task

3. update thread entry point
3a. introduce the concept of an empty task to signal the thread to die
3b. call initialize on thread_ctrl
3c. call invoke or go to step 3d. When invoke returns, call finalize. Add self to queue from step 1 and wait on cond var from step 1a. Pop self from queue. Go to step 3c
3d. an empty task (or an exception) signals the thread to break the loop and call finalize (kill thread)

4. make thread_ctrl::start reuse threads
4a. take a non-const shared_ptr instead of the current const
4b. check the queue for a non-busy thread
4c. if one is found, redirect the shared_ptr to the found thread. Then move the given task_stack into m_task and notify the cond var on the thread. Also reset m_signal and m_exception.
4d. if one is not found, start a new thread without redirecting the given shared_ptr

I've split the work into 4 commits to ease review, but of course they can be squashed and given proper commit messages later.

### CODE REVIEW

**Comment by bd339** [comment]
I've just started looking into this since it was brought to my attention that this causes lots of breakages. First bug I found:
scope_threads join in their destructor. But if the thread is already done with its work when that happens, join will wait on the condition variable indefinitely. This could happen before too, but then the thread would already have exited so join would finish.

**Comment by Nekotekina** [comment]
We probably don't need a thread pool at all, especially if it's nontrivial to implement. Overhead seems negligible, plus some thread pool may already exist under the hood.

**Comment by bd339** [comment]
It's not trivial to implement. There are many cases where it can behave subtly different, and it will most likely take a lot of time to test / find them all. Sounds like you can just close this. Should I instead open a PR to remove the TODOs about the thread pool and remove it from the roadmap?

**Comment by Nekotekina** [comment]
OK, I removed it from the roadmap. Sorry about this.

**Pull request closed without merging**
