### PR TITLE
Fix build for Visual Studio

### PR DESCRIPTION
**Pull request by Zangetsu38**
Fix icon and name for exe in Visual Studio for have same think build Appveyor.
Remove old rpcs3.vcxproj and rename project rpcs3qt.vcxproj in rpcs3.vcxproj 
Restored original name for rpcs3_.rc to rpcs3.rc.
Delete old wxWidgets/setup.h and FindwxWidgets.cmake no used now.

One commit separate in Two part for more easy review.
Look first commit for see why have changed, second commit only rename project.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Conflict fixed, and link updated
https://gist.github.com/Zangetsu38/72c15dda0fcd2d9ea817bf81c63a62d3

**Comment by kd-11** [comment]
Just fix the remaining conflict and we can merge

**Comment by Zangetsu38** [comment]
Yes, i have added change is good

**Comment by Nekotekina** [comment]
It's not good. config_kbpad_qt.yml should remain.

**Comment by Zangetsu38** [comment]
To do what ? I have restored the name before, that's all, it is not useful to have the name QT seen that there is only that, it is as if there was the config_QT.yml , that does not make any sense.
And I use it there is no problem, it works perfectly.
It does not have a config_kbpad.yml and a config_kbpad_QT.yml in the same folder.
It's just a forgetfulness.

**Comment by Zangetsu38** [comment]
Rebased and conflict fixed

**Comment by Luffykun007** [comment]
Someone please review this PR

**Comment by Nekotekina** [comment]
I'm not sure why it's called fix. I think old files should be renamed for now, otherwise the file history is lost.

**Comment by Zangetsu38** [comment]
@Nekotekina rename old project ?

**Comment by Nekotekina** [comment]
Yes

**Comment by Zangetsu38** [comment]
ah ok, you whant what name ? "rpcs3.old" ?

**Comment by Nekotekina** [comment]
rpcs3.old.vcxproj, it doesn't matter

**Comment by Zangetsu38** [comment]
ok good

**Comment by Zangetsu38** [comment]
Done

**Comment by Zangetsu38** [comment]
ok donne in only 2 commit. only need see change in first commit, second commit only for rename news project.

**Pull request merged**
