### PR TITLE
Add Icon on the .exe

### PR DESCRIPTION
**Pull request by Zangetsu38**
Used this Icon http://rpcs3.net/wp-content/uploads/2015/05/laaast.png 
After testing, it makes pretty good.

### CODE REVIEW

**Comment by tambry** [comment]
@Zangetsu38 Could you post a picture of how the icon looks on the .exe itself? I'd like to see it.

**Comment by Zangetsu38** [comment]
@tambry ok 
capture d ecran 2015-06-28 21 42 25

**Comment by tambry** [comment]
@Zangetsu38 Did you confirm that the icon is not affected by copyright? Also, wouldn't it be nicer to for example have an icon from the forum thread about icons (I was unable to find it right now, but with some digging you could probably find it), since the smaller text on the icon is unreadable, when shown on the actual window/taskbar/etc.

**Comment by Zangetsu38** [comment]
@tambry Fixed 
capture d ecran 2015-06-28 22 02 33
Size Correct Now ?

**Comment by tambry** [comment]
I guess it is better now.

**Comment by Zangetsu38** [comment]
And for the rest, the free people of the Cooperative is proposed a forum for better and more suitable Icon can be prettier.
I just wanted to at least make the .exe is Icon are, for the rest I invite people for this strong creates a beautiful icon, I know nothing about me ^^

**Comment by Zangetsu38** [comment]
@Tambry look this test icon
capture d ecran 2015-06-29 11 42 33

**Comment by tambry** [comment]
@Zangetsu38 I myself would preffer rpcs3B over rpcs3S. But I also like rpcs3, except I don't like that the S is on a new line behind the 3.

**Comment by Zangetsu38** [comment]
@tambry I see, so, where is your favorite? ? ^^

**Comment by Zangetsu38** [comment]
@tambry So your favorite is the rpcs3B?
This is mine too.

**Comment by tambry** [comment]
@Zangetsu38 Yes, my favourite is rpcs3B.

**Comment by Zangetsu38** [comment]
@tambry I havce a correct size S on rpcs3, it's better, but I still prefer the B, and you? ^^
capture d ecran 2015-06-29 12 14 24

**Comment by yorkiesandskittles** [comment]
I made this one a while ago, if it's any help.
rpcs3logov3

**Comment by tambry** [comment]
@Zangetsu38 I still prefer B, but @yorkiesandskittles icon is also quite nice and simpler.

**Comment by Zangetsu38** [comment]
@tambry ok, i have a news test with B2 
capture d ecran 2015-06-29 13 20 48

**Comment by tambry** [comment]
@Zangetsu38 I like the B1. Maybe you could remove "Playstation 3 emulator" text, since it is so small and isn't really needed.

**Comment by Zangetsu38** [comment]
@tambry Ok, and Now ? 
capture d ecran 2015-06-29 13 38 24

**Comment by Syphurith** [comment]
If the executable only contains one icon which is used as the primary one, the icon of executable is just same as the original icon file. If you're using `.icon` you can just show the file image, and don't need to build it at once. PS: I prefer A1.

**Comment by Zangetsu38** [comment]
@Syphurith I know, but we asked the head to see better than it had.
ok thx :) je reste sur celle la alors :)

**Comment by Bigpet** [comment]
I don't particularly like the logo and I don't think we've ever been given an answer on the copyright.

In general I'd prefer something less weirdly asymetric in shape sort of like this:

rlogo1

And if you set Color accents I'd prefer some subtle color gradients:

rlogo2

To the weird lensflare that's going on

**Comment by Zangetsu38** [comment]
@Bigpet I do not know that quite the image to the website, so I can not ask her.
I like the 2 but I prefer mine ^^.

**Comment by tambry** [comment]
@Zangetsu38 A1 is definently an improvement, good job. Though I might actually prefer @Bigpet's second icon due to the improved symmetry and color gradients.

**Comment by Blaypeg** [comment]
I prefer Bigpet's also, the icon needs to be clean and view ok at many different sizes

**Comment by Bigpet** [comment]
>I do not know that quite the image to the website, so I can not ask

I don't care which logo you chose but please ask the original creator for permission first (if you can't find the person in the forums, then maybe ask in the facebook group that they advertise on the site).

**Comment by Zangetsu38** [comment]
@Bigpet Yes, I know but even with the exe in large it is not seen
I asked, but I do not even know if we will respond.

**Comment by yorkiesandskittles** [comment]
I don't know about all of you, but I don't think we should have the 'R' flipped around like that.

**Comment by Bigpet** [comment]
It's a joke around the origins of the "r" in rpcs3 originally standing for "russian" and the russian letter Я

**Comment by Zangetsu38** [comment]
I have not had an answer, but I thought the site was official yet, so I thought it was logical to take the site icon and put it on the exe.

**Comment by Bigpet** [comment]
@Zangetsu38 I don't know who made the logo (or who runs the site for that matter) and you don't seem to know either. There's no "maybe" here, we need a yes or no.

**Comment by Zangetsu38** [comment]
@Bigpet Yes, I understand well, but I thought the person familiar with the project knew who kept the site. I think Alex knew hmm, I'll ask on the forums I think.

**Comment by Hykem** [comment]
That icon may be affected by copyright.
In terms of design, I also prefer @Bigpet's approach, which is simple and clean.

Anyway, as far as I know, the website is owned by "shadow" (from emunewz.net) and I believe it was maintained at some point by "nickblame" and "AlexAltea".

**Comment by Zangetsu38** [comment]
@Hykem Ah, thank you, I'll find out then.

**Comment by Bigpet** [comment]
@Zangetsu38 How about in the meantime you download inkscape and create either a variant with what I started: https://github.com/Bigpet/randomfiles/blob/master/rpcs3logo.svg  (font used is http://www.1001freefonts.com/orbitron.font )

or make something similar to what you wanted but in a vector format

**Comment by Zangetsu38** [comment]
@Bigpet That we can use if you want: 
capture d ecran 2015-06-30 19 32 28
If you can do it in .ico 256x256 size

**Comment by Bigpet** [comment]
@Zangetsu38 sure, https://github.com/Bigpet/randomfiles/blob/master/rpcs3_256.ico

**Comment by Zangetsu38** [comment]
@Bigpet  Thx, But there is much transparency with the letter?
Otherwise the desktop it's a white square ^^

**Comment by Bigpet** [comment]
@Zangetsu38 what? I don't understand what you are saying, it's got an 8bit alpha channel, what exactly are you talking about.

**Comment by Zangetsu38** [comment]
@Bigpet I mean the transparency of the icon, such as pcsx2 icon that shows no white, but just a vacuum, and therefore, on the desktop, it does not make white square.
Look carefully any application icon you're you understand ^^

**Comment by Bigpet** [comment]
it is already transparent, if you open it with windows photo viewer you'll see that. But I've also uploaded one *.ico that contains the lower resolutions too if that's what you wanted: https://github.com/Bigpet/randomfiles/blob/master/rpcs3_256_128_48_32_16.ico

**Comment by Zangetsu38** [comment]
@Bigpet No, it's good, it was already good I just stinks not tested, so right, it's done well thank you :) @Hykem It's good now is ready to merge :)

**Comment by Zangetsu38** [comment]
I redo the  Pull request own :)

**Comment by Syphurith** [comment]
@Zangetsu38 If icon still transparent, try replace the white/black color with one similar.

**Comment by Bigpet** [comment]
@Syphurith don't worry about it, it was fine the entire time, it's just that PNG transparency in *.ico files is displayed differently than BMP transparency in the Visual Studio preview which is probably what confused him. Also, some of the messages in this chain were edited, so the conversation makes even less sense now then it did when it happened

**Comment by Zangetsu38** [comment]
Link for New Pull Request https://github.com/RPCS3/rpcs3/pull/1130

**Comment by Syphurith** [comment]
@Bigpet Thanks for your reply. Have good day with development!

**Comment by Zangetsu38** [comment]
@Bigpet It's not you who merge the new Pull request ?

**Pull request closed without merging**
