### PR TITLE
Try to fix ugly GUIs

### LINKED ISSUE #8095: RPCS3 UI Corruption (Linux)
Hi,

I've not used RPCS3 in about a year and it turns out the UI in most recent builds is like the following...
Screenshot_2020-04-25_02-31-50

I've spent a bit of time tracking down the last build that where the UI was drawn to screen correctly which is build "rpcs3-v0.0.8-9546-76271800_linux64.AppImage" as you can see below...
Screenshot_2020-04-25_02-36-22

I'm not aware of any debug commands I can run to make RPCS3 output logging info outside of a game but, I can confirm that the AppImage does not output any error to console when executed from the command line

The desktop is just a standard X-server using openbox as the window manager. Here some info about my pc... 

Processor Information:
    CPU Brand:  Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
    Speed:  3700 Mhz
    8 logical processors
    4 physical processors

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.34-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  Openbox

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 870M/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 430.64
    Primary VRAM: 6144 MB

Here's a link to more comprehensive details about my hardware...
https://gist.github.com/Niroc/ab1f133f7e79e9e0d7932670b5f6cdc5

### PR DESCRIPTION
**Pull request by Megamouse**
probably fixes #8095

### CODE REVIEW

**Comment by AniLeo** [comment]
Wasn't there some reason why we didn't do this before? I remember something, not sure what

**Comment by Megamouse** [comment]
Probably because we actually used it before.

**Comment by Megamouse** [comment]
Let's just try it out I guess

**Comment by qurious-pixel** [comment]
Using RPCS3 0.0.11-10743-6850533b linux appimage on Lubuntu, the fix doesn't work. 
I have a script that applies the ENV variable QT_AUTO_SCREEN_SCALE_FACTOR=0.
QT_AUTO_SCALE_FACTOR does nothing.  

can the logic include both terms?

**Comment by Megamouse** [comment]
Thx. I accidentally copy pasted a wrong variable that someone else posted in the original issue.

**Pull request merged**
