### PR TITLE
Terrifying PKG installer fix

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by Nekotekina** [comment]
I mostly finished some things but it would be better to test it.

**Comment by danilaml** [comment]
Tested on Sonic - seems fine. Don't know what to specifically test (don't have psp/ps1 packages to install).

**Comment by Hykem** [comment]
I've tested it out with a few different PKGs. It's working quite well.
Just needs to be re-based and merged.

**Comment by tambry** [comment]
Also needs to be fixed for Travis.

**Pull request merged**
