### PR TITLE
Fixed per game configuration using custom yml files

### PR DESCRIPTION
**Pull request by georgemoralis**
You can now load per game configuration files which are created using game-id ( e.g NPUB30217.yml)

To create a per game configuration , right click on game and choose configure. The settings will be saved in gameid yml

When you boot a game if the specific file is found it will load settings from there

### CODE REVIEW

**Comment by Nekotekina** [comment]
Need to at least use the same config filename

**Comment by MarioSonic2987** [comment]
Will .yml archives be in a separated directory? (like in _settings_ folder).

**Comment by georgemoralis** [comment]
fixed it to be saved inside game's directory. Since i don't know how to find the position of the BOOT.BIN or EBOOT.BIN or self,elf files without running Emulator:BootGame i save it to game's dir instead

**Comment by georgemoralis** [comment]
Ok now it is saved inside game's dir with gameid.yml name. Hope it is now ok...

**Pull request closed without merging**
