### PR TITLE
rsx: Shader decompiler improvements

### PR DESCRIPTION
**Pull request by kd-11**
- Fix fp16 emulation. Simple clamping is not enough as infinity and nan need preserving and nvidia cards clamp NaN to the lower bounds which is wrong.
- Use native fp16 types if the hardware or driver supports it. In OpenGL most modern hardware will report this feature but for vulkan only Volta, Turing and Vega report this functionality. Should help lower the overhead of the fp16 emulation.
- Fix shadow compare operations on vulkan. In OpenGL, GL_ARB_shadow specifies that compare_R_to_texture clamps R to (0-1) before comparing. Vulkan behaves more like the older GL_SGIX_shadow extension and R is not necessarily clamped. This is particularly true when the depth buffer is in floating point format such as D32F_S8. Fixes broken shadows when using AMD cards or NV cards when the 'High precision Z' option is enabled.
- Fix poor attribute interpolation precision on Nvidia which causes spurious failure of floating point comparisons in fragment shaders and leads to visual noise.
- Properly enforces IEEE-754 rules for all opcodes with the exception of DIVSQ which is provably broken on realhw as well and is now done per-channel to match realhw. LG2 and RSQ seem to ignore the sign bit of the input arguments but otherwise behave in an IEEE compliant way.

Fixes:
https://github.com/RPCS3/rpcs3/issues/5830
https://github.com/RPCS3/rpcs3/issues/4174
https://github.com/RPCS3/rpcs3/issues/5343
https://github.com/RPCS3/rpcs3/issues/4799
https://github.com/RPCS3/rpcs3/issues/5567

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
One Piece: Pirate Warriors has regressed. Now shows black textures in Vulkan and throw a shader compilation error with OpenGL.

<details>
<summary>Master</summary>

image
image
</details>

<details>
<summary>This PR</summary>

PR OpenGL:
```
E {RSX [0x02192f0]} RSX: Failed to compile shader: 0(322) : error C7011: implicit cast from "int" to "float16_t"

F {RSX [0x02192f0]} RSX: class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(322) : error C7011: implicit cast from "int" to "float16_t"
(0) : error C2003: incompatible options for link
'
```

PR Vulkan:

image

</details>

[Log OPPW (OpenGL PR)](https://github.com/RPCS3/rpcs3/files/3095074/Log.OPPW.18-4-19.GL.PR.gz)

[Shaderlog OPPW (PR)](https://github.com/RPCS3/rpcs3/files/3095063/Shaderlog.OPPW.18-4-19.PR.zip)

**Comment by arcadee1977** [comment]
Thanks for your great work! All of Nvidia card's graphic issue have been fixed.

**Comment by incognitoh** [comment]
RR7 basically looks perfect now. Nice

rr7rpcs3nv

**Comment by stride21** [comment]
This PR causes black squares to appear in Battlefield: Bad Company.
 
PR: OpenGL:
bf opengl pr
PR Vulkan:
bf pr vulkan'
Master OpenGL:
bf open master
Master Vulkan:
vulkan bf master

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3095187/RPCS3.log.gz)

**Comment by jenci8888** [comment]
Progression and regression on GT5 and GT6 (I'll test more other games later)
GT5/6:
- No more flickering on car anymore, even still present rainbow.
- Vulkan (out of memory) error when load night tracks.
- More unstable ingame GT6, It can hangs ingame/intro with Vulkan error. (the error same as master)

Screenshots:
image
image

Log:
[RPCS3-GT5.gz](https://github.com/RPCS3/rpcs3/files/3096445/RPCS3-GT5.gz) (crash when loads night tracks including out of memory error as well)

**Comment by slashiee** [comment]
Regression with Sonic's model in Sonic Unleashed

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3096452/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment]
Beyond Two Souls is back to normal in this PR (seems like it broke at some point in master)

b2s-master

b2s-pr

**Comment by kd-11** [comment]
Need some kind of trace to debug any of these. RRC or RDC will do.

**Comment by slashiee** [comment]
If you think you could trace the issue with Unleashed with the RSX capture looking like this, then I can give you one.
<details>


</details>

I believe this is an RSX capture only issue. Either that or something went wrong on my end when loading the capture.

**Comment by MarioSonic2987** [comment]
[RSX Capture (OPPW VK)](https://github.com/RPCS3/rpcs3/files/3097447/NPUB30836_20190419095704_capture.zip)

**Comment by stride21** [comment]
[MotorStorm Vulkan RSX Captures](https://www.mediafire.com/file/x2cqwtcdcaf4js5/Motorstorm_Vulkan_RSX_Captures.zip/file)

[Battlefield Bad Company OpenGL RSX Captures](http://www.mediafire.com/file/vc4ool3npc3mrr5/BC_OpenGL_RSX_Captures.zip/file)

[Battlefield Bad Company Vulkan RSX Captures](https://www.mediafire.com/file/kd8u104s54cww13/BC_Vulkan_RSX_Captures.zip/file)

**Comment by kd-11** [comment]
@slashiee Don't worry about RSX capture not looking correct in replay, it usually still draws stuff properly but breaks post-processing which often relies on Cell-side intervention to look right.

**Comment by kd-11** [comment]
Retest, improved clamp16 and divsq a bit.
As for OpenGL refusing to compile some fp16-native code, it seems to be a driver bug when the driver is looking for a function override, investigating possible workarounds.

**Comment by MarioSonic2987** [comment]
One Piece: Pirate Warriors and GTA V regressions are now fixed.
image
image

But GTA IV it's the same:
image

**Comment by kd-11** [comment]
Check the OpenGL crash. For GTA4 I'll need comparison RDC to debug further. Vulkan vs master should be enough.
The differences between OpenGL and Vulkan in some cases is because OpenGL supports float16 'natively'. In reality most vulkan drivers also do support float16 but they do not advertise this feature properly. The differences appear when the native float16 implementation is more accurate than the one we emulate with the shader. A config option "disable native float16 support" exists in config.yml to force use of the shader emulation path and should also 'break' OpenGL when enabled.

**Comment by Xcedf** [comment]
Sonic Unleashed regression fixed

**Comment by MarioSonic2987** [comment]
[RDC Vulkan GTA IV Master](https://drive.google.com/open?id=18Fv6GwQUQ_tyIdfhGT0RVaZKB6oZ29Uu)
[RDC Vulkan GTA IV PR](https://drive.google.com/open?id=1OCJ6SUws_zSzLfE5TtJBFBJqLALJ6Ao0)

OPPW crash with OpenGL is now fixed, by the way.

**Comment by kd-11** [comment]
Pushed a fix for RSQ instruction that should fix GTA4. Need to verify properly with real hardware before this is merged.

**Comment by MarioSonic2987** [comment]
Now it's fixed.
image

**Comment by stride21** [comment]
Motorstorm is fixed
ms fixed

Battlefield Bad Company with Vulkan no longer shows the black squares on the ground or character models but it still has black squares where the light artifacts happen in master.
bf new pr

Battlefield Bad Company with OpenGL no longer intros 
bc opengl error
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3100167/RPCS3.log.gz)

**Comment by kd-11** [comment]
Fixed some whitespace bugs causing compilation errors.
As for battlefield black output - I feel like I fixed this before but can't remember when. The output on master is also clearly wrong so it could need more work than just restoring the result that was there before.

**Comment by kd-11** [comment]
Glowy things in bad company are a programmer's error. Every test I have run on real hw says they should be black spots there (because the programmer forgot to add a saturate modifier somewhere, literally one misssing bit). Obviously the real PS3 somehow does not generate the condition that would require this, so I'm not sure if its a real regression. Its easy to add the saturate for them but this would be a hack. Ironically this would also hide other issues that appear due to broken clamping.

**Comment by Josivan88** [comment]
Fix menu problem in Goldeneye 007 reloaded.
Master:
Master
This PR:
This PR

**Comment by kd-11** [comment]
Added a workaround for the problematic instruction. It no longer behaves like real hardware but we cannot match exactly the PS3's TMU so I think going out of spec there is fine. Basically the texture filtering does not seem to match the PS3 exactly pixel-for-pixel which is expected. Since texturing is completely fixed function (non-programmable) a workaround is the only way to get around this. I can make the hotspots dance around the screen by altering the filtering even very slightly causes the hotspots to migrate. More research on this topic will be carried out at a later date, but likely only for academic curiosity rather than improving any games (NaNs are rather useless as they are often substituted with 0 anyway).

**Comment by stride21** [comment]
Glowy things are fixed with this PR but now shooting with a weapon causes a fatal error.

Master:
BF master

PR:
BF PR fixed

PR error:
BF error
[RPCS3 log.zip](https://github.com/RPCS3/rpcs3/files/3108549/RPCS3.log.zip)

**Comment by stride21** [comment]
Battlefield Bad Company fatal error is now fixed.

**Comment by Kravickas** [comment]
Since u are working on shaders, I leave this here if u wanted to look in to that too even tho its regression from another time. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3109570/RPCS3.log.gz)
Far Cry 2 when loading ingame and generating shaders
```
·E 0:04:32.978121 {RSX [0x008ad10]} RSX: ERROR: 0:330: '' :  syntax error, unexpected EQUAL
ERROR: 1 compilation errors.  No code generated.


·E 0:04:32.978128 {RSX [0x008ad10]} RSX: 
·F 0:04:32.978395 {RSX [0x008ad10]} RSX: class std::runtime_error thrown: Failed to compile vertex shader
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:2982)
```
Let it be if its completly different issue or hard to fix.

**Comment by kd-11** [comment]
If you don't have the shaderlog then you have to submit an opengl log. Vulkan backend does not write any shader info in the log file.

**Comment by Kravickas** [comment]
OGL log [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3109867/RPCS3.log.gz)

**Comment by kd-11** [comment]
Enable 'Log shader programs' in debug settings and then after the crash (disable async shader compiler beforehand) attach shaderlog/vp_analyser.bin file.

**Comment by Kravickas** [comment]
OGL, strict enabled, async shaders disabled
[vp_analyser.zip](https://github.com/RPCS3/rpcs3/files/3112233/vp_analyser.zip)
i hope thats it

**Comment by kd-11** [comment]
Far Cry 2 crash should be fixed now.

**Comment by EwoutH** [comment]
Has someone benchmarked this PR on a Nvidia Turing (GTX 16 or RTX 20 series) or AMD Vega (Radeon Vega 56/64 or VII) yet? Those GPUs offer double the FP16 performance, would be interesting to see the gains.

**Comment by kd-11** [comment]
The version of glslang we use to emit SPIR-V may not have the optimizations built in to properly support fp16 as it is a relatively recent thing in the vulkan core spec, although the older AMD extension VK_AMD_gpu_shader_half_float seems to work correctly (there should be no difference to the emitter in theory, but you never know). A Vulkan tools update is coming soon to bring us to newer SDK versions, but it could be a few weeks before that is done.

**Comment by Kravickas** [comment]
Far Cry 2 fixed, n1 thanks

**Comment by Xcedf** [comment]
Confirm Far Cry 2 fixed

**Pull request merged**
