### PR TITLE
gl/vk: Bug fixes and improvements

### PR DESCRIPTION
**Pull request by kd-11**
This PR includes the following changes:

- Fix broken buffer size computation on opengl that regressed during refactoring
- Fix A4R4G4B4 texture remap
- Enable two sided lighting on opengl
- Force writing of output registers when a branch-to-exit is encountered (for both opengl and vulkan)
- Use proper MVP matrix

https://github.com/RPCS3/rpcs3/issues/2149 should be fixed

### CODE REVIEW

**Comment by O1L** [comment]
It breaks fragment shader generation in alphakill sample:

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(70) : error C1008: undefined variable "tex0_coord_scale"

**Comment by SakataGintokiYT** [comment]
[shaderlog alphakill](https://mega.nz/#!UIZyRKQT!HQObZphNyG0Ce_hDS7285VBgbl7S1YLVE8YPge6cR6U)

**Comment by kd-11** [comment]
Texture access outside of main code block due to the comparison function. Nice catch.

**Comment by kd-11** [comment]
Updated with proper raster comparison functions moved into the fs_main block.
Also fix for https://github.com/RPCS3/rpcs3/issues/2143 included.

Let me know if you spot any regressions.

**Comment by kd-11** [comment]
Limbo seems to have regressed :(

**Comment by raven02** [comment]
fix https://github.com/RPCS3/rpcs3/issues/1947 and https://github.com/RPCS3/rpcs3/issues/1855

**Comment by kd-11** [comment]
This PR should also finally fix limbo https://github.com/RPCS3/rpcs3/issues/1753. Playable on vulkan, ogl has regressed a bit, but I'm looking into it

**Comment by kd-11** [comment]
Fixed regression with MVP matrix.
Limbo
image

**Comment by kd-11** [comment]
Final part of this changeset: properly invert front face check when culling. Fixes face cull when origin=top as tested with prince of persia: the sands of time.

**Comment by kd-11** [comment]
I've reverted that face cull thing as it breaks some other games. I think this can be merged as is and I'll create another PR for the face cull thing

**Pull request merged**
