### PR TITLE
Low-level changes

### PR DESCRIPTION
**Pull request by Nekotekina**
First commit is nothing noticeable.

Maybe I'll push more changes with optimizations for Windows 10 and 8.1.

### CODE REVIEW

**Comment by Nekotekina** [comment]
Pushed experimental commit.

**Comment by maxgerhardt** [comment]
Quick question: When implementing `popcnt16`, why not optimize it with the `POPCNT` instruction for x86? E.g. `u8 better_popcnt16(u16 arg) { return (u8) __builtin_popcount( (u32) arg); }` compiles to just 

```asm
better_popcnt16(unsigned short):
        popcnt  ax, di
        movzx   eax, ax
        ret
```
with GCC + `-O3 -march=skylake`.

**Comment by Nekotekina** [comment]
> Quick question: When implementing `popcnt16`, why not optimize it with the `POPCNT` instruction for x86? E.g. `u8 better_popcnt16(u16 arg) { return (u8) __builtin_popcount( (u32) arg); }` compiles to just
> 
> ```assembly
> better_popcnt16(unsigned short):
>         popcnt  ax, di
>         movzx   eax, ax
>         ret
> ```
> 
> with GCC + `-O3 -march=skylake`.

We support machines which don't have this instruction

**Comment by scribam** [comment]
`std::bitset::count` (https://en.cppreference.com/w/cpp/utility/bitset/count) generates a `popcnt` instruction if the cpu supports it. Unfortunately, if it is not the case, GCC does a call to `__popcountdi2` whereas Clang seems to do a good job.

**Pull request merged**
