### PR TITLE
SPU/sys_cond/mutex/event: Implement lv2_obj::on_id_create(), Write into SPU inbound mailbox under mutex

### PR DESCRIPTION
**Pull request by elad335**
* ~~Revert a change in #8140 where the protocol was changed to PRIORITY, I will revert it for now as it is probably the cause for the regressions and I haven't hw test it.~~
* Because #7999 and #7931 made the destroy syscalls of sys_event_queue and sys_cond execute destruction code instead of the destructor, IPC support has been broken because with IPC you can have multiple copies (multiple IDs) of the same object and destroy syscall is destroying one ID at a time. The destruction code must happen on last ID destroyed, so you use an existence counter and increment it in lv2_obj::on_id_create(), decrement on destroy syscall and execute destruction code when it becomes 0.
* Fix race between sys_cond_create and sys_mutex_destroy which could lead to a conditional variable creation without any mutex attached to it! this is a nice "side effect" of the above fix because of the added last mutex existence check in lv2_cond::on_id_create() under writer IDM lock on conditional variable creation which was lacking.
* Fix minor race in sys_cond_wait which could lead to a spurious EBUSY in sys_cond_destroy.
* Write into SPU inbound mailbox under mutex, Implement EBUSY error on non-empty mailbox
 in sys_spu_thread_send_event/sys_event_flag_set_bit.

Issues to test:

- [x] #8267
- [x] #8331

### CODE REVIEW

**Comment by marcussacana** [comment]
`Dengeki Bunko: Fighting Climax [BLUS31535]`
Now the game do nothing, just freeze after open the game window
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4728454/RPCS3.log.gz)

**Comment by elad335** [comment]
Retest please.

**Comment by marcussacana** [comment]
Yeah, I'm waiting the build finish

**Comment by marcussacana** [comment]
`Dengeki Bunko: Fighting Climax [BLUS31535]`
Now the game window don't open and the game just 'stop'
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4728769/RPCS3.log.gz)

**Comment by elad335** [comment]
Needs retesting as there was a push mistake.

**Comment by marcussacana** [comment]
`Dengeki Bunko: Fighting Climax [BLUS31535]`
In game now, but still no audio after the intro video.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4728950/RPCS3.log.gz)

**Comment by elad335** [comment]
Can you upload a log before the offending pull request?

**Comment by marcussacana** [comment]
Log of build 10321 (#8137): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4729263/RPCS3.log.gz) - Audio working
Log of build 10324 (#8140): [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4729272/RPCS3.log.gz) - Audio not working

**Comment by marcussacana** [comment]
`Dengeki Bunko: Fighting Climax [BLUS31535]`
The audio worked, but stopped after some few minutes.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4729495/RPCS3.log.gz)

In the true I didn't played the game in the old version yet, then i'm not sure if is another bug or still related with this one.

**Comment by marcussacana** [comment]
`Dengeki Bunko: Fighting Climax [BLUS31535]`
Audio Still not working, but now the game 'freeze' after select a option in the main menu.
(The menu animation keep running but is like the game is doing nothing, joystick don't respond too.)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4729745/RPCS3.log.gz)

**Comment by marcussacana** [comment]
Do you already want a new test or is WIP yet?

**Comment by mshpakov** [comment]
Infinite loading screen is still here with rpcs3-v0.0.10-55708dc2_win64.7z
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4740010/RPCS3.log.gz)

**Comment by elad335** [comment]
Found the race condition! please retest.

**Comment by mshpakov** [comment]
Yo,man! This is awesome! I've successfully passed the loading screen and the game seems to work like before.

btw,  I see tremendous amount of log message updates in GUI, I certainly sure that such excessive logging use much more cpu cycles... Is this by design / in purpose  ?

`U {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d35bc8]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd02689f4) x8910
`

**Comment by marcussacana** [comment]
`Dengeki Bunko: Fighting Climax [BLUS31535]`
Audio fully working now.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4740938/RPCS3.log.gz)

Also, I'm not sure, because the old build was too, but I believe that the game is a little slower than the old version, however my computer is not very good so I dare not say that it is a problem.
In the log, the message `E {PPU[0x100026e] Thread () [0x00e8b04c]} SYS: 'sys_spu_thread_group_connect_event_all_threads' failed with 0x80010015 : CELL_EISCONN [1]` appears as well in the same time that the 'lag' happen, but this also occurred in the old build, so I don’t think it’s a problem related to this commit, I’m just commenting because I suspect the error appeared more frequently.

**Comment by mshpakov** [comment]
On my hardware Demon Soul's starts much faster if I silence the logging in settings.

> 
> 
> `Dengeki Bunko: Fighting Climax [BLUS31535]`
> Audio fully working now.
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4740938/RPCS3.log.gz)
> 
> Also, I'm not sure, because the old build was too, but I believe that the game is a little slower than the old version, however my computer is not very good so I dare not say that it is a problem.
> In the log, the message `E {PPU[0x100026e] Thread () [0x00e8b04c]} SYS: 'sys_spu_thread_group_connect_event_all_threads' failed with 0x80010015 : CELL_EISCONN [1]` appears as well in the same time that the 'lag' happen, but this also occurred in the old build, so I don’t think it’s a problem related to this commit, I’m just commenting because I suspect the error appeared more frequently.

**Comment by mshpakov** [comment]
`build rpcs3-v0.0.10-a1ae7c90_win64.7z  
game Demon's Souls - [BLUS30443] + hd font mod`

As for me this build works just fine. 
With logging silenced game starts much quicker.
[RPCS3.log.xz.zip](https://github.com/RPCS3/rpcs3/files/4768526/RPCS3.log.xz.zip)

**Comment by mshpakov** [comment]
`BLES-00906 Prince of Persia The Forgotten Sands 2010 + 1.01 patch
build rpcs3-v0.0.10-37dfa19a_win64.7z 
`
The game works just fine. I've played for 1 hour completed few chapters without any issues.
performance\sound effects are as they should  30fps/no sound glitches

**Comment by mshpakov** [comment]
```
build rpcs3-v0.0.10-6f6aae50_win64.7z 

game Demon's Souls - [BLUS30443] + hd font mod 
```
This build works just fine as previous.

**Pull request merged**
