### PR TITLE
Strict Rendering Mode (SRM) fix for Tales of Vesperia. Move old surface copy before texture upload.

### PR DESCRIPTION
**Pull request by pauls-gh**
Fixes the following issues on Tales of Vesperia which requires SRM.
- Blacked out scene after the sleeping dog now renders correctly
- Ghosting effect. The ghosting was most noticeable as a delay between the character rendering and the cell shading around the character. This appears to be gone with this change.

### CODE REVIEW

**Comment by pauls-gh** [comment]
I'm new to git/github.  There's only 1 new commit, but it says 11 commits for this pull request.  The other commits are from my previous pull request (which was merged to master) and syncing my fork to the master branch.

Is there anyway to avoid this?

**Comment by AniLeo** [comment]
git rebase --interactive HEAD~11

Then squash everything

**Comment by fifazalata** [comment]
Tested on both ogl & vk & works just fine 
Half-screen issue still remains (i know this pr is not targeted to fix it but i thought u should know maybe u can give it a look)

**Comment by AdmiralCurtiss** [comment]
I'm not sure the git command from AniLeo will have the intended effect. We want to isolate the change, not mesh it together with the rest.

I'd recommend the following. This is complicated by the fact you opened this PR using your master (avoid that in the future and just make feature branches), but okay.

`git fetch RPCS3` -- This fetches the changes from the main repository.
`git checkout RPCS3/master` -- This switches your current checked out state to the state of the main repository.
`git cherry-pick a2e641fb383e5ccef471c9c6dc0264b66b954fc9` -- This takes a single commit (the one with the fix here, a2e641fb383e5ccef471c9c6dc0264b66b954fc9) and applies it on top of the currently checked out state.
`git branch srm-fix` -- This takes the current state (main repo + fix commit) and gives it a name, so we can easily refer to it later.
`git checkout master` -- Switch back to this branch you opened the PR on.
`git reset --hard srm-fix` -- Overwrite the `master` state with the state we stored in `srm-fix`.
`git push --force` -- And push the fixed state up to Github.

**Comment by pauls-gh** [comment]
@AdmiralCurtiss - thanks for the git lesson.  :-)  I'll have to get more familiar with git.

@fifazalata - thanks for testing the fix.  Yeah, I noted the half screen issue still remains in https://github.com/RPCS3/rpcs3/issues/2707.

**Comment by AniLeo** [comment]
@AdmiralCurtiss it does, I use it all the time. It can squash everything into one commit, and the redundant changes (e.g. merging upstream's changes to fork) are not accounted for.

**Comment by Illynir** [comment]
Yes, the fix works very good. Performance on this game is always very bad even without the strict, probably SPU related though.

Good job. :)

**Comment by kd-11** [comment]
@pauls-gh Should've just done a pull rebase on upstream. Add upstream remote and just `git pull --rebase upstream master` should fix the commits.
As for the change, it as we had discussed which is ok, I'll implement the split memory access properly later.

**Comment by AniLeo** [comment]
Please don't rebase on every upstream commit, otherwise you're taking compile time from other PRs waiting merge. We can issue a rebase before merging, so don't worry.

**Comment by pauls-gh** [comment]
Sorry about all the git confusion and unnecessary compiles.  I'm slowly becoming a git expert. :-)

**git pull --rebase upstream master**
  => I had some merge conflicts with this for some reason.

So instead, this worked for me.

**git rebase -i upstream/master**
 => interactive rebase with upstream.  I chose the single commit (SRM fix) that still needs to be upstreamed.

**git push -f**
=> force push local to origin

Now my fork shows that I'm correctly one commit ahead of RPCS3/master

**Pull request merged**
