### PR TITLE
Vulkan: Add glslang and LoaderAndValidationLayers

### PR DESCRIPTION
**Pull request by vlj**
This PR adds Khronos repository for glslang and Vulkan loader and make VS 2015 build them/link against them.

It doesn't bring any Vulkan backend related code ; but I think it's better to sort out the build/include/link things as soon as possible so that everyone can work on a moreless common base for the upcoming Vulkan backend.

### CODE REVIEW

**Comment by danilaml** [comment]
https://github.com/vlj/rpcs3/commit/e0fe5eb5c5e30ce3acb529539a3a6de692fe9fbd slipped into this PR.

**Comment by vlj** [comment]
Fixed build and added cmake/python as required (like llvm Vulkan uses cmake to get build ; python is also used somewhere during build).

**Comment by danilaml** [comment]
@vlj with this PR rpcs3 doesn't build for me.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" -DBUILD_TESTS=OFF -DBUILD_DEMOS=OFF ../Vulkan-LoaderAndValidationLayers
msbuild.exe ALL_BUILD.vcxproj /t:build /p:Configuration=Release
    " exited with code 1.	Vulkan-build	G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets	37	
```

**Comment by vlj** [comment]
Do you have cmake in your PATH?

**Comment by danilaml** [comment]
@vlj I have since llvm builds just fine.

**Comment by danilaml** [comment]
@vlj it turns out that you need Python 3.3+ installed, could be mentioned in the readme (I had 2.7.10).

**Pull request merged**
