### PR TITLE
lv2: sys_timer_usleep improvements for linux

### PR DESCRIPTION
**Pull request by Whatcookie**
This is inspired by: https://github.com/RPCS3/rpcs3/pull/4716
This commit causes usleep to only sleep until one quantum before the requested time on linux. There is no change to how usleep works on windows. 

<details>
  <summary>before</summary>

```
Application started
Calculating baseline delay...(0us)
Testing usleep(0)...
    Latency = 0us
Testing usleep(1)...
    Latency = 2us
Testing usleep(10)...
    Latency = 11us
Testing usleep(50)...
    Latency = 50us
Testing usleep(100)...
    Latency = 100us
Testing usleep(200)...
    Latency = 281us
Testing usleep(300)...
    Latency = 385us
Testing usleep(400)...
    Latency = 493us
Testing usleep(500)...
    Latency = 585us
Doing the special tests...
Testing usleep(250)...
    Latency = 274us
Testing usleep(280)...
    Latency = 285us
Testing usleep(290)...
    Latency = 294us
Testing usleep(299)...
    Latency = 302us
Testing usleep(301)...
    Latency = 390us
Testing usleep(310)...
    Latency = 389us
Testing usleep(320)...
    Latency = 389us
Testing usleep(600)...
    Latency = 695us
Application finished
```

</details>

<details>
<summary>after</summary>

```
Application started
Calculating baseline delay...(0us)
Testing usleep(0)...
    Latency = 0us
Testing usleep(1)...
    Latency = 2us
Testing usleep(10)...
    Latency = 11us
Testing usleep(50)...
    Latency = 51us
Testing usleep(100)...
    Latency = 101us
Testing usleep(200)...
    Latency = 201us
Testing usleep(300)...
    Latency = 304us
Testing usleep(400)...
    Latency = 408us
Testing usleep(500)...
    Latency = 510us
Doing the special tests...
Testing usleep(250)...
    Latency = 253us
Testing usleep(280)...
    Latency = 283us
Testing usleep(290)...
    Latency = 293us
Testing usleep(299)...
    Latency = 303us
Testing usleep(301)...
    Latency = 304us
Testing usleep(310)...
    Latency = 314us
Testing usleep(320)...
    Latency = 324us
Testing usleep(600)...
    Latency = 612us
Application finished
```

</details>

This causes us to spend less time sleeping, but we're still able to sleep most of the time on linux. 

On a simple scene PPU utilization looks like this after the change:
ppuutil1

Before, on linux it would look like this: 
ppuutil2

On windows, it looks like this: 
ppuutil3

Even though its dramatically more accurate now, we are only spending a small amount of time yielding, most of the time we can sleep and not overload low thread cpus. 

Spent awhile looking through my games to see if any benefited, but none seemed to. But there were also no speed regressions, atleast on my 4C8T cpu. 

Finally, I've added a TODO message asking to confirm whether Apple and or any BSD can benefit from having the min quantum set lower. If anyone could test that then we can remove that and those operating systems can benefit as well.

### CODE REVIEW

**Comment by ruipin** [comment]
Did you test any games? Last time I played around with usleep (including seeing what happens when you skip the last quantum) a *ton* of games broke. In particular, some games (I believe Journey was one) do 1us sleeps instead of yielding, so skipping the last quantum just completely broke the game.

**Comment by Whatcookie** [comment]
@ruipin I tested all the games I have. I tested Nier a bit, and that game spams 1us sleeps as well, and it still works. 

Besides though, this won't change behavior for games requesting sleeps that small anyways, since we still don't sleep for values that small. 

I know that some games can be tolerant of terrible usleep timing (I messed around with it a lot when I was trying to find the speed difference between windows and linux in that game, and you can do literally anything (including intentionally breaking it) and the game will still play fine)

**Comment by ruipin** [comment]
Journey requests sleeps that vary in size, and can go above the minimum quantum value on linux.

The problem is some games are extremely sensitive, and so are some CPUs. 4 thread CPUs especially are very sensitive. I wouldn't merge such a change without a *lot* of testing.

**Comment by Whatcookie** [comment]
I'm not sure that this is as unstable as you think it is, we aren't "skipping" the last quantum with this commit, we're making sure that we handle it accurately. 

The windows code is inaccurate for values above 500 us, and the linux code on master is inaccurate for values above 100 us. 

You can see in the results I posted above, while 100us works fine on master, just 200us suddenly causes linux to sleep for 281us. Even such small values can be wildly inaccurate on master.

That being said, while I don't expect any negative effects other than ~2% higher cpu usage seen in the overlay, I haven't found any games that respond positively to the added accuracy. So there's certainly no rush to get this merged.

I'll test this on my computer with hypthreading disabled later and see how bad it is 4T cpus, but testing from people with other usleep sensitive games would be nice. 

If this method is really determined too expensive for 4T cpus (I doubt it), then I have another commit that I can push that I was playing around with earlier that should make usleep about 50% more accurate on linux (without spending any extra time yielding).

**Comment by ruipin** [comment]
You need to specifically test 2C4T CPUs. I remember the windows hack (where we don't spinlock for the last quantum for accuracy) was put into place *specifically* for those.

**Comment by Whatcookie** [comment]
Disabled 2 cores of my 4C8T cpu (7700K) as per ruipin's suggestion and retested all my games.

Even in situations with 100% cpu load there didn't seem to be any difference in framerate between master and this pr. I put extra testing into P5 since rui mentioned that many users on windows with 2C4T cpus complained about loss of performance in that game when usleep was first made more accurate. 

That being said, no games see any measurable improvement with 4C8T enabled either, so it'd be great if more people could test this PR.

**Comment by Whatcookie** [comment]
I've pushed a new commit that scraps the old idea entirely, but this new one is now much improved over master with no drawbacks at all.

The default minimum quantum on linux appears to be 50 microseconds on linux. Now we don't have to spin as much as before for values between 50-100 microseconds. 

There is also an accuracy improvement for values above 100 microseconds, and this is achieved without any extra spinning compared to master. 

100 microseconds is a fairly common value for games to sleep for, and those games see improved performance on my 7700K with this new commit: 

Journey demo before
journeybefore

Journey demo after
journeyafter





<details>
  <summary>master</summary>

```
Application started
Calculating baseline delay...(0us)
Testing usleep(0)...
    Latency = 0us
Testing usleep(1)...
    Latency = 2us
Testing usleep(10)...
    Latency = 11us
Testing usleep(50)...
    Latency = 50us
Testing usleep(100)...
    Latency = 100us
Testing usleep(200)...
    Latency = 281us
Testing usleep(300)...
    Latency = 385us
Testing usleep(400)...
    Latency = 493us
Testing usleep(500)...
    Latency = 585us
Doing the special tests...
Testing usleep(250)...
    Latency = 274us
Testing usleep(280)...
    Latency = 285us
Testing usleep(290)...
    Latency = 294us
Testing usleep(299)...
    Latency = 302us
Testing usleep(301)...
    Latency = 390us
Testing usleep(310)...
    Latency = 389us
Testing usleep(320)...
    Latency = 389us
Testing usleep(600)...
    Latency = 695us
Application finished
```


</details>


<details>
<summary>this pr</summary>

```
Application started
Calculating baseline delay...(0us)
Testing usleep(0)...
    Latency = 0us
Testing usleep(1)...
    Latency = 2us
Testing usleep(10)...
    Latency = 11us
Testing usleep(50)...
    Latency = 51us
Testing usleep(100)...
    Latency = 102us
Testing usleep(200)...
    Latency = 223us
Testing usleep(300)...
    Latency = 329us
Testing usleep(400)...
    Latency = 441us
Testing usleep(500)...
    Latency = 547us
Doing the special tests...
Testing usleep(250)...
    Latency = 273us
Testing usleep(280)...
    Latency = 284us
Testing usleep(290)...
    Latency = 293us
Testing usleep(299)...
    Latency = 302us
Testing usleep(301)...
    Latency = 332us
Testing usleep(310)...
    Latency = 331us
Testing usleep(320)...
    Latency = 334us
Testing usleep(600)...
    Latency = 650us
Application finished

```

</details>

I believe this is ready for review now.

**Comment by kd-11** [comment]
Wouldn't shifting the load to OS yield() cause problems for low-end CPUs? A 7700K isn't a good enough test for this imo, we had issues with this code in the past when tested on intel's 4 thread CPUs (older gen i3s and i5s) so I think we need more user testing here.
As for the code itself, its good.

**Comment by Whatcookie** [comment]
The latest commit doesn't end up yielding any more than master does, the accuracy improvements for larger values were achieved just by sleeping better. 

Two games from my testing see time spent yielding, Persona 5 has about 1-2% less PPU usage with this commit, and Journey has 8% less PPU usage.

**Comment by Whatcookie** [comment]
Did some comparisons with 2C4T enabled in bios with the new commit: 
### Journey master
journey2C4Tmaster
### Journey PR
journey2C4TPR


### Persona 5 master
P52C4Tmaster



### Persona 5 PR
P52C4TPR
### Ninja gaiden master
NGSmaster

### Ninja gaiden PR
NGSPR

For games that sleep with values between 50-100 us there is a large reduction in time spent yielding, but there is a small increase in time spent yielding for other games that I could not see when I was testing on 4C8T.

**Pull request merged**
