### PR TITLE
PPUTranslator: Ignore relative relocations

### PR DESCRIPTION
**Pull request by VelocityRa**
Fixes at least the following on LLVM recompiler:
* **Portal 2**
* **Castlevania: Harmony of Despair**
* **FIFA 12**

@Nekotekina Seems like the translator handles this just fine in emitted instructions (saw it being used for the `bc` instruction), but they weren't properly ignored.
I included all relevant relative relocations as comments and only left out relocation type 11 which we know for sure works because of aforementioned games.
I could remove the commented ones or if you think they'd work as well, uncomment them.

### CODE REVIEW

**Comment by JackONeill12** [comment]
Problem is with this PR "0:00:13.611047 PPU: Ignoring relative relocation at 0x2454f0 (11)" gets spammed in log making it over 500mb in minutes with so many lines that even Notepad++ cant open it.

**Comment by danilaml** [comment]
@JackONeill12 can't you set your log level higher?

**Comment by JackONeill12** [comment]
@danilaml The complete log gets written to the file anyway. The log level only seems to affect whats shown in the console.

**Comment by AniLeo** [comment]
Then set your log level higher on the config's log section itself not on the emulator's log console

**Comment by VelocityRa** [comment]
Not sure if I should make a new PR just for this... Is it actually a problem or does it only occur in one game?

**Comment by JackONeill12** [comment]
The log part of the config is empty. What would be the correct syntax to change the log level there?

**Comment by Nekotekina** [comment]
```
Log: {PPU: Error, sys_rsx: Fatal}
```

**Comment by JackONeill12** [comment]
Thx

**Pull request merged**
