### PR TITLE
spu: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Implement FM for interpreter fast and asmjit
- Fixes a bug in FMA/FMS/FNMS where cmpunord was used as an optimization but inadvertently broke some corner cases :p

### CODE REVIEW

**Comment by SerJons** [comment]
Now Journey works on asmjit. Also need "Write Color Buffers" and "Strict Rendering Mode" or there will be a black screen.

**Comment by woj1993** [comment]
@kd-11 What is missing in FM that it is "only" partially implemented?

**Comment by kd-11** [comment]
@woj1993 https://gist.github.com/kd-11/ed8d4b82921c29ed13417945b6597168

**Comment by kd-11** [comment]
Actually I set the wrong value for FLT_MAX. Fixing it should significantly improve accuracy.

**Comment by SNK-Afridi** [comment]
Spider man Edge of time blus 30760 shows no more black screen when i punch venom.
but crashes with pink error. Saw performance improvement as well. LLVM,ASMJIT, liblv2 only. vulkan and opengl as well and strict mode on off both.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1355504/RPCS3.log.gz)

F {SPU[0x2000004] Thread (GoliathInstCellSpursKernel4)} class std::runtime_error thrown: Branch-to-self (0x00eec)
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUASMJITRecompiler.cpp:2297)
F {MFC Thread} MEM: Access violation reading location 0x0

hmm should i post anything else?

**Comment by kd-11** [comment]
Tweaked to handle all corner cases except for INF. SPUs just process INF like a general value which breaks FM with INF. Auto-test only fails INF case for now, but I think it should be good enough.
@SNK-Afridi Does it work without crashing without this PR? What happens when the same happens on master?

**Comment by SNK-Afridi** [comment]
this is the [build](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6330) i used to give you the log in my above comment.
tested this master [build](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6317/artifacts)  from rpcs3 download and it give same error but the screen is black, used the same settings as above.
 i have been testing this paste 1 hour and found out that not attacking venom i did not get crash. but after two or three attacks again same error. 
i used SPU interpreter fast which was too slow but moved paste that stage without error. Now in next stage i took some screen shot in same location using your build and master build..
kd-11 build
desktop screenshot 2017 10 04 - 20 40 35 52
desktop screenshot 2017 10 04 - 20 41 21 48

master build.
desktop screenshot 2017 10 04 - 20 45 42 61
desktop screenshot 2017 10 04 - 20 46 25 94

it is sad to say this. but i tested a july build and it gave me same error as well :(

i forgot to mention. after using interpreter fast to move paste venom stage. i again used ASMJIT. and then i took the screen shots above. i hope i am not confusing you :(

**Pull request merged**
