### PR TITLE
Use cpu_set_t only on Linux

### LINKED ISSUE #3756: MacOS build Error
log:[macos_try.txt](https://github.com/RPCS3/rpcs3/files/1485595/macos_try.txt)

OS: MacOS High Sierra 10.13.1
XCode: Version 9.1 (9B55)
Command line tools version: 9.1
cmake version 3.9.6
LLVM version 5.0.0

Config command: `cmake ../rpcs3 -DUSE_SYSTEM_FFMPEG=ON`
Environment Variables : 
`Qt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5`
`LLVM_DIR=/usr/local/opt/llvm/bin`

### PR DESCRIPTION
**Pull request by scribam**
Fix #3756 

`cpu_set_t` is not available on MacOS

### CODE REVIEW

**Comment by Nekotekina** [comment]
It's not right. Affinity must be supported everywhere.

**Comment by rodjun** [comment]
According to a quick Google search, it might not be possible on Mac OS. "

**Comment by clienthax** [comment]
https://developer.apple.com/library/content/releasenotes/Performance/RN-AffinityAPI/#//apple_ref/doc/uid/TP40006635-CH1-DontLinkElementID_2

**Comment by scribam** [comment]
Thank you @clienthax, I did a commit which uses the Affinity API. Unfortunately, I don't have a Mac so I don't know if the code compiles fine or not. Can someone check this?

**Pull request merged**
