### PR TITLE
Added A Game Update/Installer Menu

### PR DESCRIPTION
**Pull request by Backporter**
Super Useful.

### CODE REVIEW

**Comment by AniLeo** [comment]
We have all the API data cached on our server (patchsets, packages, changelogs), it wasn't added on the emulator intentionally

**Comment by Backporter** [comment]
ah, I mean, allowing users to download game updates for dumped/installed games should be fine no?.

**Comment by AniLeo** [comment]
Not really, no other emulator does this on purpose as well

**Comment by Backporter** [comment]
ah, alright, I guess ill just create an script that will do it outside RPCS3, thought it would be a good add.

**Comment by Megamouse** [comment]
It was a good idea, but it's as AniLeo said.

**Pull request closed without merging**
