### PR TITLE
cellSaveData: Fixup funcDone result check

### LINKED ISSUE #8708: Regression: Cannot delete save data in Sly 2 [NPUA80664] (#7623)
## Quick summary
I can not delete save data correctly in v0.0.8-9755, PR #7623, and after in Sly 2 [NPUA].

## Details

| RPCS3 Version | RPCS3 Commit | Log | Description & Screenshot(s) |
| ------------- | ------------- | ------------- | ------------- |
| v0.0.8-9754 and Before  | -------------  | [RPCS3 1.log](https://github.com/RPCS3/rpcs3/files/5046033/RPCS3.1.log) | Deletes save data correctly. The save in slot 2 is gone. Capture2 |
| v0.0.8-9755 and After | [#7623](https://github.com/RPCS3/rpcs3/pull/7623) | [RPCS3 2.log](https://github.com/RPCS3/rpcs3/files/5046035/RPCS3.2.log) | **_Does not_** delete save data correctly. The save in slot 2 is still there. This message appears after trying to delete the save in slot 2 twice. Capture |

## Other Details
* If I restart the game, the save data is correctly not there, after deletion.
Capture3
* Sly 2 has another, save data bug where you can not overwrite your old saves. I think that is unrelated.

#### System Configuration:
* OS - An atari Jaguar
* CPU - A potato
* GPU - A lemon

### PR DESCRIPTION
**Pull request by elad335**
Fixes #8708, regressed after https://github.com/RPCS3/rpcs3/pull/7623.

### CODE REVIEW

**Comment by Megamouse** [comment]
Can you link the offending PR please?

**Comment by AniLeo** [comment]
#7623

**Comment by MarioSonic2987** [comment]
Sly 2 can now delete save data properly. Overwriting them still fails.

**Comment by jeremybris** [comment]
Works, thanks! :)

**Pull request merged**
