### PR TITLE
[Testers Needed] Call of Duty 3 fix #3357

### LINKED ISSUE #3357: RSX: Call of Duty 3 - Unknown blend eq 0xffff
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

While attemp to ingame it throws fatal error "Unknown blend eq 0xffff"

```
F {rsx::thread} class std::runtime_error thrown: Unknown blend eq 0xffff
(in file Emu\RSX\gcm_enums.cpp:733)
```

**[LOG](https://mega.nz/#!6NEXBTbR!X82qM4kOhbEQvEkamPtxGSEqSI6_V-0EYIxFhacx36Q)**

### PR DESCRIPTION
**Pull request by jeremybris**
Trying to fix #3357 with @Xcedf's solution

**There is probably a reason why:**

- The code is written the way it was originally written
- Xcedf did not implement the changes

**Testers are needed to see if this:**

- Fixes Call of Duty 3 by going ingame
- Causes any regressions

I am a neophyte at coding. Any feedback is appreciated. Feel free to close this, or discuss solutions.

### CODE REVIEW

**Comment by Margen67** [comment]
This is a hack/workaround, not a proper solution.

**Comment by jeremybris** [comment]
> This is a hack/workaround, not a proper solution.

Ok. I was hopeful testing this can be helpful in understanding the issue, or discussing it could lead to more information.

**Comment by jenci8888** [comment]
Fixed crash other tracks in GT5 Prologue.
image
image

**Comment by jeremybris** [comment]
> BUT, You shouldn't to merge this due to hack/workaround like said Margen67.

100% agree, do not merge please.

**Comment by web1018** [comment]
Capture14

With this PR, there is no change so far when trying to go ingame. After the cutscene, the game hangs in black screen and following error pops up

**Comment by jeremybris** [comment]
> With this PR, there is no change so far when trying to go ingame. After the cutscene, the game hangs in black screen and following error pops up

I have the same results. I had to use OpenGL. Thanks for testing web1018.

**Comment by RainbowCookie32** [comment]
Following the *really accurate* spirit of this PR, this exception should get the axe for that error to be *fixed*

**Comment by web1018** [comment]
No problem. Let me know if you need me to test again for changes. You can also reach me on discord under 'Web1017' #1746

**Comment by web1018** [comment]
> > With this PR, there is no change so far when trying to go ingame. After the cutscene, the game hangs in black screen and following error pops up
> 
> I have the same results. I had to use OpenGL. Thanks for testing web1018.

No problem. Let me know if you need me to test again for changes. You can also reach me on discord under 'Web1017'

**Comment by jeremybris** [comment]
> Following the _really accurate_ spirit of this PR, this exception should get the axe for that error to be _fixed_
> 
> Edit: forgot to add the link lol
> 
> https://github.com/RPCS3/rpcs3/blob/9ded69438f288acf6c0f2f250d737e27d8a8ce70/rpcs3/Emu/RSX/VK/VKGSRender.cpp#L190

I think you are right, I was going through the code and edited the wrong line by accident. I am going to make that change.

**Comment by AniLeo** [comment]
Pretty sure this should be closing, but assigning kd-11

**Comment by jeremybris** [comment]
> Pretty sure this should be closed, but assigning kd-11

No problem, I will close this. The discussion will still open, and the merge can still be tested by people for regressions. I am just waiting on appveyor to build the preview for testers.

**Comment by web1018** [comment]
Capture14

I can now go ingame after the cutscene. But due to high amounts of shaders being compiled, I am getting a fatal error

**Comment by elad335** [comment]
Tfw a function does not return a value.. what a meme.

**Comment by fearcraftor** [comment]
Frustrated to get that error in this game, I investigate on my own few days ago. Digging around the code, this function is used later in this file in a blend_enabled function, which let suppose that blending could be disabled.

A more graceful solution would be to disable blending if value in not in switch case ?

**Comment by elad335** [comment]
no

**Comment by elad335** [comment]
when I have time I'll fix it properly.

**Comment by VladWinner** [comment]
> when I have time I'll fix it properly.
There is no error solution yet, am I right?

**Comment by elad335** [comment]
It's fixed.

**Pull request closed without merging**
