### PR TITLE
[DRAFT] input: reset pads with some delay after cellPadInit was called

### LINKED ISSUE #6093: The Simpsons the Game [BLES00142] - Broken Controller Input
The controller inputs are not fully accepted.  it is not possible to navigate by analog stick or control pad (menus) and within gameplay is the same result. Only Input of the X or Start buttons has been accepted and trying to remove the controller and plugging it back in does not change anything. Elad mentioned before that it might have something to do with **pad thread rewrite and timing hacks/fixes**. This is the only issue I know so far thats preventing the game to be fully playable.

Tested Build :
rpcs3-v0.0.6-8254

Hardware Specs :
Nvidia GeForce GTX 960M
Intel Core i7 6700HQ
16GB of Ram
Windows 10
Xbox 360 Controller
Capture1

## Update
- Checking the Latest Master Version v0.0.10-10321-72bef8dd Alpha, The controller issue is fixed somehow. I can navigate through the menu options and in game options without any issues now. I am not sure which PR fixed this issue, but the controller Input problem no longer occurs. I have tested it using Xbox 360 controller. Unless the issue still stands, I am closing this Issue.

### PR DESCRIPTION
**Pull request by Megamouse**
This should fix the simpsons and the godfather initial input issues.
I couldn't find any other way for now.

May relate to #6093

### CODE REVIEW

**Comment by web1018** [comment]
The input issue still not fixed in the Simpsons game. I cant select any options in the Pause menu or during Main Menu of the game. 

pad1

**Comment by Megamouse** [comment]
I don't think it is related

**Comment by elad335** [comment]
The pull request's base idea is wrong.. I made a unqiue testcase which tests this idea with cellPadGetData, cellPadGetInfo, cellPadGetInfo2, cellPadClearBuf, cellPadGetCapabilityInfo.
None of which experienced this behavior after cellPadInit was called at first.

[cellPad Hack test.zip](https://github.com/RPCS3/rpcs3/files/4020147/cellPad.Hack.test.zip)

Heres the test and the results 
Dont try to compile it on your side as it would fail because of undefined references to cellPadGetInfo and cellPadGetCapabilityInfo, Although if you enable logging in rpcs3 you are able to see those calls.

**Comment by Megamouse** [comment]
I am fully aware that it doesn't happen. Remember that I already made similar these tests.
The PR is basically a draft. That's why I haven't merged it.

**Comment by web1018** [comment]
I know there hasn't been much news on this for some time, but is there any specific build you would like to be tested? I keep trying different methods and I can't get this issue to resolve by the options in the pad configuration.

**Comment by benderscruffy** [comment]
might fix #6902

**Pull request closed without merging**
