### PR TITLE
rsx: Gather most rsx commands pretty printing and state modification …

### PR DESCRIPTION
**Pull request by vlj**
…function in a single file.

rsx_decode.h implements a "rsx_decoders" template class that is specialized for most GCM command
found in rsx command buffer. 3 static members are defined : a "decode" function that turns command
value into a more meaninfull type if applicable (for instance bool for _enabled* command, surface
formats for set_surface_format command...), a "commit_rsx_state" that modifies a given rsx_state
structure when the command is parsed, and a "dump" function used in rsx_debugger for pretty printing.
Hopefully having the 3 functions in a single place for every command will act as a self documenting
list of rsx command buffer opcode.

rsx_state is also expanded into several explicit variables instead of being stored into a u32 array.
This should makes debugging easier (Visual Studio will display the exact value of these member for instance)
as well as preparing rsx_state for serialisation/deserialisation.

The vertex array and textures opcode are not concerned atm for bisecting purpose.

### CODE REVIEW

**Comment by Nekotekina** [comment]
I'm trying to understand whether it's slower than possible or not.

**Comment by vlj** [comment]
What do you mean "slower than possible" ?

**Comment by Nekotekina** [comment]
I'm not sure, if copying params can be avoided. Also it seems that rsx::thread often becomes a bottleneck, especially with PPU recompiler.

**Comment by vlj** [comment]
Unfortunatly command buffer can change states several time before emitting an actual draw command. I guess it's because of some gfx API layer but it's not uncommon to have "vertex array X : (disabled)" then "vertex array X : type = ... size = ..." or depth write disabled and then reenabled.
From rsx point of view only the last command that modifies a given parameter matters (it's a state machine afterall) so it might be hard to find a way that doesn't involve copying parameters to some location.

However I think copying parameters can be improved to some extend : currently every parameters are copied in a 16k array of u32. This array doesn't fit in L1 cache and I suspect it's not uncommon to access distant addresses :
When looking at GCM.h it appears that every command block (ie NV4097, NV3062,...) is identified by a value in the high bits ("0x6XXX" for NV3062, "0x8XXX" for NV309E, "0xCXXX" for NV3089...) while some command block don't have a lot of command so a lot of space is unused. Since NV4097 is the 3d engine (and thus the mostly used block) and NV3089 is used to update fragment constant (and thus likely the second one most used block) I guess cache miss are rather frequent.

Another inefficiency is that some parameters are copied twice, for instance transform constant (a first time from command buffer to rsx::method_registers, and a second time to the actual transform constant buffer) or transform program (same : a first time from command buffer to rsx::method_registers and then from method_registers to the transform program buffer).

**Comment by raven02** [comment]
Not too sure if it is my own issue .I cannot get this build working .

**Comment by vlj** [comment]
What is the build error message ?

**Comment by raven02** [comment]
It just simply pop up fatal error dialog and then force to close .

**Comment by vlj** [comment]
which backend ?

**Comment by raven02** [comment]
D3D12. However , it should affect all backends

**Comment by SakataGintokiYT** [comment]
@vlj 
rsx-refactor -wip works  well

**Comment by vlj** [comment]
Should be fixed, I accidently removed a rsx_registers::commit_rsx_state call thus state was never updated.

**Comment by Nekotekina** [comment]
@vlj Why the array must fit completely in L1 cache if only parts of it are actually accessed? I would think about few cache lines actually used.
However I would even store an array of be_t<u32> to avoid cost of byteswap for bool conversions. Also indirect function calls (registered methods) may have significant overhead for each RSX instruction compared to current implementation when only u32 value is copied. But I'm not profiling it, it could be that the overall amount of RSX instruction is not that big to produce noticeable overhead...

**Comment by vlj** [comment]
Actually there is already an indirect function call : for every instruction parsed, the operand is stored and then instruction opcode is tested in a rsx_method_t [] array. What I like is to combine both storage and calls to these special opcode values inside a single function table.
To be honest I'm not sure if this PR will improve performance or not. I think it won't make a difference, we may loose some perf when parsing command buffer because of indirect function call but we may gain some performance in backends code by having smaller data members to read and by sorting them by relevance. For instance there are around 20 boolean values accessed as u32 with current implementation, without array they can be grouped on a single dword. As you suggest it would require some profiling (which is likely impractical atm given that there are innefficiencies in other part of rsx emulation, like no buffer caching)

On the other hand with this PR parsing the rsx_state at debug time is much much easier since the real values are accessible to the debuger instead of encoded version. And it's easier to dump rsx_state on disk if needed.

**Comment by raven02** [comment]
@vlj . It is working okay now .

**Comment by Nekotekina** [comment]
@vlj I still think it's a mistake to use slow and obscure design just to make some values show in the debugger. If you need to peek them, the right approach would be to customize debug output, something like this: https://msdn.microsoft.com/en-us/library/jj620914.aspx

To simplify access to individual values, there is another trick:
```C++
struct rsx_state
{
private:
	std::array<u32, 0x10000 / 4> registers;

public:
	u16& testreg1 = reinterpret_cast<u16&>(registers[NV4097_SET_VIEWPORT_HORIZONTAL]);
```

Now some value can be accessed transparently. It's not also the only way to implement it.
For bit fields, there is `Utilities/BitField.h` custom bitfield class which can work even with big-endian values directly. It is also more correct to avoid using C/C++ "native" bitfields completely because they have unspecified layout.
For debugging, as I said, there should be a way to customize debug output: for BEType, for BitField and anything else.

**Comment by vlj** [comment]
I'm switching to Bitfields atm.
The issue I want to solve too is to enforce that whenever and opcode is used in code a dump() function is provided otherwise compilation break. This way command buffer dump should be more accurate and better reflect what is used or not in rpcs3.

**Comment by paulsapps** [comment]
The debugger helpers are cool but if you are not using the VS debugger they don't work. Do you plan to have some sort of real time view of the commands or just for debugger only?

**Pull request merged**
