### PR TITLE
rpcs3_version: Bump to 0.0.12

### PR DESCRIPTION
**Pull request by AniLeo**

### CODE REVIEW

**Comment by dio-gh** [comment]
Shouldn't this wait until kd finishes the feature freeze?

**Comment by AniLeo** [comment]
No, tags have been precisely bi-monthly and they're not stables, only landmarks
Plus changelogs for massive changesets are too painful to do

**Comment by dio-gh** [comment]
Alright.

**Comment by StalkerDolg** [comment]
Really guys. Why not assign version 0.1.0, and then assign 0.1.1, 0.1.2 and so on. And by the time 0.9.0 is released, several years will have passed and the emulator will be "worthy" to receive the pre-final version.
Compared to PCSX2, this emulator at the time of release 0.9.5 did not have nearly as much progress as this emulator.

**Comment by AniLeo** [comment]
No

**Pull request merged**
