### PR TITLE
rsx: Fix vertex attrib parsing

### PR DESCRIPTION
**Pull request by kd-11**
- Fixes regressions introduced by #5166 

Fixes https://github.com/RPCS3/rpcs3/issues/5168

### CODE REVIEW

**Comment by MSuih** [comment]
Found an issue with Ratchet & Clank Triology; graphics are not being rendered after selecting a game from the launcher. Audio and controls work fine but the screen stays black aside from overlays.

**Comment by kd-11** [comment]
Thanks, should be fixed now.

**Comment by Atrosincity** [comment]
This PR still crash on games boot,(both soul calibur games), last build that worked for me is 0.0.5-7376
got an old i5-3470 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2416353/RPCS3.log)

**Comment by Asinin3** [comment]
This pull request doesn't seem intended to fix that issue so it's not related and you shouldn't comment here. Open an issue for the game (if there isn't one already) and wait patiently until it's fixed (test new builds and close the issue when you notice it's been fixed).

**Comment by MSuih** [comment]
Confirming that the issue has been fixed.

**Comment by MarioSonic2987** [comment]
Fixes missing graphics regression in Red Dead Redemption.

**Before**:
image

**After**:
image

**Comment by TROguz** [comment]
Please fix FIFA 08-09-10-11. FIFA 10-11 1080p 60 fps playing but always have drop.

**Comment by ruipin** [comment]
This PR regressed TLOU and UC1


rpcs3_2018-09-25_23-21-41

Making `validate` return true "fixes" these games:

```diff --git a/rpcs3/Emu/RSX/RSXThread.h b/rpcs3/Emu/RSX/RSXThread.h
index 033e7d811..3a4cfb691 100644
--- a/rpcs3/Emu/RSX/RSXThread.h
+++ b/rpcs3/Emu/RSX/RSXThread.h
@@ -212,6 +212,7 @@ namespace rsx

                bool validate() const
                {
+                       return true;
                        switch (attribute_placement[0])
                        {
                        case attribute_buffer_placement::transient:```

**Comment by kd-11** [comment]
Regressions resolved by https://github.com/RPCS3/rpcs3/pull/5176

**Pull request merged**
