### PR TITLE
Async

### PR DESCRIPTION
**Pull request by kd-11**
- Implements asynchronous decompiling of shaders

NOTE: Includes fixes from https://github.com/RPCS3/rpcs3/pull/4869 for testing
NOTE2: When shaders are loading in there will be extreme pop-in (missing graphics that will slowly resolve). This is normal. You can disable this functionality in config.yml, set "Disable asynchronous shader compiler" to true.

- Added a simple performance fix for https://github.com/RPCS3/rpcs3/issues/4566

### CODE REVIEW

**Comment by ruipin** [comment]
I'm curious, should we expect the same issues that Dolphin saw when something similar was implemented? Just so people are aware what to expect. I'll quote their [Ubershaders article](https://dolphin-emu.org/blog/2017/07/30/ubershaders/):

> In the end, it just came down to the fact that the people who could have implemented [asynchronous shaders] along with other core developers were against it as a solution. They saw it as nothing more than a hack that would cause a lot of false positives on the issue tracker and cause bigger issues down the road. Those worries were proven somewhat valid when you realize that some games need objects to be rendered on the frame they expect it to be. In this case, the Mii heads are only rendered once to the Embedded Framebuffer. If the EFB copy is missing because of Async Shader Compilation, the Mii heads will not show up for the remainder of the game or until they're regenerated.

**Comment by vietnam13231** [comment]
In all games I tested (P5, Project Diva, Drakengard 3, NieR Replikant, Infamous), it works just as note2 says, massive pop-ups everywhere, and have not met with any problems. It lags when few first shaders are loading, after that it plays while loading more and more, and at the end works as normal. No drops or increase in performance, no dropping OOB. That's why I'm not sure if it's a needed thing at all...

**Comment by Asinin3** [comment]
Try with this PR vs Master with Asura's Wrath or Uncharted, the difference is huge. Asura's Wrath doesn't perform well on master unless you spend atleast a few hours compiling shaders. With this PR the amount of shaders that compile is significantly lower the game now performs well with a clean cache. Saying that it's not needed is just wrong.

**Comment by kd-11** [comment]
Also some games will crash if the emulator slows down to a crawl because the developers did not account for lo framerates. This largely evades this issue.

**Comment by kd-11** [comment]
@ruipin ofc they are there. Dark souls character portraits are a good example (drawn once and copied) and if you have no shaders ready they will never appear.

**Comment by TigiHof** [comment]
Did short tests on P5, Lollipop Chainsaw, Bayonetta, Demon's Souls and Ni No Kuni. On my system (i7 6700K) shader compilation stutter is practically removed. This is nothing less than spectacular, I can hardly believe it.

**Comment by slashiee** [comment]
Just tried it with Project Diva F without any shader cache, I can finally now play a song (when playing it for the first time mind you) without restarting it once or twice due to shader compilation.

**Comment by creeperjedi** [comment]
Just played a bit of Medal of Honor: Airborne and the shader stutter is almost completely gone! I can actually play a for a bit without it being a slideshow. Nothing short of amazing!

**Comment by ventuskh123** [comment]
Testing GT HD Prologue and doesn't stuck anymore changing de the camera angle

**Comment by greentop** [comment]
TOCS2 [BLUS31597] is a game for a while now that doesn't suffer from shader compiling stutter. The observation with this PR is that the map loading times are now faster (by a few short seconds) where there is no precompiled shader cache that is already present. The visual effect seen upon loading is a world map that is being rendered on the fly piece by piece for the duration of only a few very short seconds, where it is then completely rendered.  (As described in kd-11 Note2.)

**Comment by hch12907** [comment]
Will there be an option to keep the synchronous shaders after this PR? Figured that will be easier for debugging and testing, since some games may draw some objects only once.

**Comment by kd-11** [comment]
You can still use synchronous shaders. The option already exists and will be added to the GUI.

**Comment by Buzing** [comment]
This PR branch including fixes branch now freezes my client upon game load and bring to front.

Game Works flawlessly if not clicked on. but when brought onto front  screen freezes but game can still be interacted with(audio says so)
No Error seen.


Master branch: does not happen.

Just a heads up just in case as you might have an idea. It seems no one else has the issue yet.

**Comment by jobs-git** [comment]
I also experience the freeze that Buzzing described. When the screen is clicked on rpcs3 window stops responding but game is still running this happens both for disable async=true and false.

On "disable async=false", Lags due to shader compilation has been dramatically reduced! Great work!

Specs:

Win 10, Gtx 1060, Intel Avx cpu

**Comment by jobs-git** [comment]
I also experience the freeze that Buzzing described. When the screen is clicked on rpcs3 window stops responding but game is still running this happens both for disable async=true and false.

On "disable async=false", Lags due to shader compilation has been dramatically reduced! Great work!

Specs:

Win 10, Gtx 1060, Intel Avx cpu, D3 blus31437

**Comment by Patkos96** [comment]
Dragon Ball Raging Blast 2 freezes with async both Vulkan and OpenGL, but I don't think Async works with Vulkan for me, because with openGL it runs better, and it was always slower with OpenGL.
Fullscreen makes the game freeze sooner, but freezes in windows also. But performance is better even with the wrong graphics, nice imporvement.

You said Raging Blast 2 has problems with fragment shader compilation, right? Do you know approx when it will be fixed?

Here is the log. Also, if trophy popup is enabled, the game freezes every time a trophy appears. (In master there are a few times when it doesn't but usually trophy makes it freezes there too.)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2189052/RPCS3.zip)

**Comment by kd-11** [comment]
@Buzing Not able to reproduce. Are you using any monitoring tools?

**Comment by kd-11** [comment]
@Patkos96 Async is working but your CPU cannot handle the extra work `Intel(R) Core(TM) i5 CPU 760 @ 2.80GHz | 4 Threads`. Even modern i5s will freeze a little when using vulkan as compiling from ps3->glsl->spirv->driver is quite a lot of work. Add the lower CPU speed and you might be better disabling it.

**Comment by kd-11** [comment]
Freezing window bugs are caused by https://github.com/RPCS3/rpcs3/issues/4878#issuecomment-404717518 and have nothing to do with rsx code. This is why its important to test all builds not just rsx ones when checking regressions.

**Comment by spyropt** [comment]
Missing character portrait in dark souls II
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2193889/RPCS3.log.gz)

**Comment by marosis** [comment]
@kd-11 can i ask from where you know everything this about PS3 and how you know what can emulation improve? Something like this? This is really unwriteable 😄.

**Comment by Asinin3** [comment]
@marosis GitHub is **not** the place for discussion. You can ask on Discord https://discord.me/RPCS3 or our forums https://forums.rpcs3.net/

**Comment by marosis** [comment]
Yeah i understand sorry. Iam only really interrested in. I Will not do it again next time.

**Comment by Lagahan** [comment]
Huge improvement on all of my games with deleted shader caches, brings shader compilation from complete lockups to very slight slowdowns. This will make updates that invalidate shader cache much less painful!

**Comment by ju2ef1986** [comment]
Silent Hill now is almost perfect. Occasional frame drops but Shader Compilation without any cache is not causing (almost) any stutter. i7 5820, GTX 1070, 16GB DDR4, SSD. Vulkan, Strict Rendering, 1 SPU and I am getting almost solid 30fps on 1080p. 4k without strict rendering on Vulkan crashes emeulator complaining small buffer. OpenGL works fine but framerate suffers a bit on 4k. Amaznig work!

**Comment by Finoderi** [comment]
It looks like this PR made white/black flickering in Demon's Souls much less prominent than it was before. I have a Rizen 5 1600 and Radeon RX480. Audio stuttering is still there though.

**Comment by ju2ef1986** [comment]
@finoderi did you try running with single spu?

**Comment by Finoderi** [comment]
If you mean one preffered SPU thread, than yes I tried this. It reduces audio and microstuttering a little, but when PC rolls through any breakable object, the game turns to a slideshow. I found out that 4 SPU threads is optimal setting for me. On 5 and 6 threads the game hangs more often for some reason. 2 and 3 are pretty much like 1.

**Comment by gandalfthewhite19890404** [comment]
Async causes F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\GLHelpers.h:990) in every game on some GPUs. Tested with tetris(bundled with emulator) on NVIDIA 210GT (yes - its old, I know it).

**Comment by AkagiShiroe** [comment]
@gandalfthewhite19890404 clear shadercache first and make sure you use SPU ASMJIT Recompiler
(i got that issue when i have SPU LLVM Recompiler) @AniLeo .. yeah that's more awfull card than mine.. even 9600GT are breathing 8-16fps here.

**Comment by Asinin3** [comment]
This pull request fixes the outstanding issue plagueing KH 2.5 when playing as roxas. The slowdown when attacking or in attack stance has been totatlly fixed!

Before:


After: 
image

**Pull request merged**
