### PR TITLE
Precise SPU intepreter: Fix isdenormal() on Windows

### PR DESCRIPTION
**Pull request by jjsat**
On MS VC the isdenormal() function in the PSU interpreter is broken because it always returns true (value for "normal" is -1, so the bitcheck always evaluates true). I don't know what kind of compiler needs the #else path, so I just extended the #ifdef.

Observable improvements fromt this are: Wolfenstein goes ingame without destroying the physics objects and the Trine Demo has working collision/physics and plays sound (before the precise interpreter would play no sound but go ingame with broken collision and the fast interprester plays sound but crashes before going ingame).

### CODE REVIEW

**Comment by kd-11** [comment]
That block looks odd tbh, FP_CLASSxx is supposed to be used on results of fpclass(f). Maybe a legacy of older implementations/msvc workarounds?

**Comment by jjsat** [comment]
I traced the file changes back and this code originally looked like this (commit 817fec9684b92005f133f3fa9d6e221b4160d740 )

>  inline bool isdenormal(float x)
{
    const int fpc = _fpclass(x);
#ifdef __GNUG__
    return fpc == FP_SUBNORMAL;
#else
    return (fpc & (_FPCLASS_PD | _FPCLASS_ND)) != 0;
#endif
}

So you might be right...

**Comment by kd-11** [comment]
If so, the #else path is actually obsolete

**Comment by jjsat** [comment]
I removed the #ifdef and updated the pull request.

**Comment by Inviuz** [comment]
I wonder if anyone remembers why it was made this way in the first place

**Pull request merged**
