### PR TITLE
(Travis built)Travis and Coverity

### PR DESCRIPTION
**Pull request by Syphurith**
These setting are from [another project](https://github.com/devernay/cminpack/blob/master/.travis.yml). I made such a pull to see if we can make travis compile rpcs3 correctly. BTW an answer from [Stackoverflow](http://stackoverflow.com/a/26802317) suggusts not to use coverity.. Who knows if we can pass.

I can not enable coverity exactly, but at least Travis start to function - yep.

### CODE REVIEW

**Comment by Syphurith** [comment]
Yep it starts to compile! Best news for me tonight!

**Comment by Syphurith** [comment]
Now i think the coverall command would launch, which may provide some information about coverage.
Oh i did add a little command to see all the Shell Variables which may help us deal with Travis log.

**Comment by Syphurith** [comment]
@Nekotekina Take a look at the Travis log of clang.. The file `/Emu/Cell/RawSPUThread.cpp` successfully **finished Clang**, while no severe error for GCC. lol. Never thought of that would happen.

**Comment by Syphurith** [comment]
WTF? The version of GCC that Travis used for building our project is GCC 4.8.1..
#1048 @latot failed his compilation with gentoo 64 + gcc 4.8.4. And @devilmac with his OSX..

**Comment by Syphurith** [comment]
Travis can build rpcs3 now. Still some problems with Coverity and Clang.
It is said to be able to take use of coverity when enable `gcov` or `--coverage`.
Since i have no experience using these coverage tools and i don't know what exactly happened when someone succussfully used coverity. I don't think i can truely enable the coverage for our project now.
So just let it pass Travis first.. *If you have enough experience in using coverage tools, edit it*

**Comment by Syphurith** [comment]
Since the main repo's name was changed I edited the README.md to update Travis. Eh.. Coverall.io?

**Comment by Syphurith** [comment]
From [Here](http://stackoverflow.com/questions/6089140/gcov-with-cmake-using-a-separate-build-directory) and [Here](http://unlogic.co.uk/2012/08/13/cmake-and-gcov/) I got a little knowledge on how to enable coveralls.io. Since we are not using `./configure` script but cmake we may not easily set up such things as [Officially suggested](https://github.com/eddyxu/cpp-coveralls/blob/master/README.md#example-travisyml).
Well there seems to be a good module for Cmake [Here](https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake). But it has its own license..
`Set compiler flags to turn off optimization and enable coverage`. so `-g0`?

**Comment by Bigpet** [comment]
while you're at it, can you change https://github.com/RPCS3/rpcs3/blob/6627cc96669b5decfab0459f3c522851317b9554/.travis.yml#L47 and https://github.com/RPCS3/rpcs3/blob/c497de196344feef43929df28878027c2edd09d1/Utilities/git-version-gen.cmd#L16

**Comment by tambry** [comment]
@Bigpet I will try to look into Coverity stuff this weekend or next week. Might open an issue to the Coverity guys and see if they find what we're doing wrong.

**Comment by Syphurith** [comment]
@Bigpet Oh the outdated infomation. Thanks i would soon change that.

**Comment by Syphurith** [comment]
Log: Clang failed, and Travis used GCC 4.6.2 version for the build - so error.

**Pull request closed without merging**
