### PR TITLE
Savestates: More stability improvements

### PR DESCRIPTION
**Pull request by elad335**
To take advantage of this pr you have to resave and reload because it doesn't actually bump savestates version.

### CODE REVIEW

**Comment by TigiHof** [comment]
I'm still getting the same error I get in master when trying to load a savestate for the 2009 Wolfenstein (BLUS30298).

When I create a savestate and then immediately load it again without closing RPCS3 everything works fine. But when I close the program and then try to load the savestate I get the following error:

SavestateError

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9064474/RPCS3.log)

**Comment by elad335** [comment]
@TigiHof Thanks, retest.

**Comment by TigiHof** [comment]
> @TigiHof Thanks, retest.

Error is still present.

**Comment by elad335** [comment]
@TigiHof Try now.

**Comment by TigiHof** [comment]
> @TigiHof Try now.

Yes, that did it! It works now, great job!

**Pull request merged**
