### PR TITLE
Block Rosetta on macOS 14.0, 14.1, and 14.2

### PR DESCRIPTION
**Pull request by nastys**

### CODE REVIEW

**Review by kd-11 — APPROVED** [review]
lgtm. We'll know if it doesn't work if we get bug reports from such versions.

**Comment by shinra-electric** [comment]
Works as expected on 14.3.1

**Comment by immranderson** [comment]
Just as a heads-up, running on an M1 Max Macbook Pro, RPCS3 prompted me for an autoupdate and now upon attempting to launch the application, I'm running into an error that I don't have the appropriate version of Rosetta to run the app. Was this intentional? Do some caches need to be cleared out now? (Running the build before this PR got merged continues to run on my macbook just fine)

Screenshot 2024-02-25 at 2 47 47 PM

**Comment by AniLeo** [comment]
Yes, that's intentional, as stated in the PR's name.

**Comment by immranderson** [comment]
My apologies, I can see the PR title yes, but I'm just curious what the
reasoning behind this was? I didn't see any attached issues to this PR, so
I'm confused why support for newer versions of MacOS would be intentionally
broken?

**Comment by immranderson** [comment]
In general, when trying to launch a Rosetta supported app the OS will direct you to update things but it isn't happening in this case. I believe I should be on the latest version of Rosetta, so I'm assuming that the build actually relies on an earlier version? In which case, a "nice to have" would be a clearer error message describing which version of Rosetta is explicitly supported.

**Comment by AniLeo** [comment]
Whether Apple broke Rosetta on newer versions of macOS intentionally or not is not for us to judge, nor was it relevant to having the issue solved. Matter of fact is that it was broken since 14.0 and they've fixed it on 14.3.

The linked issue is #14794, but we closed it earlier as not our bug.

This PR blocks the broken versions because we're tired of people not reading the OS system requirements on our website and reporting issues that don't exist in the emulator.

**Comment by AniLeo** [comment]
> In general, when trying to launch a Rosetta supported app the OS will direct you to update things but it isn't happening in this case. I believe I should be on the latest version of Rosetta, so I'm assuming that the build actually relies on an earlier version? In which case, a "nice to have" would be a clearer error message describing which version of Rosetta is explicitly supported.

Sorry but I legitimately don't understand how an error message stating "Please update macOS to a supported version" is not clear/explicit enough that you need to check for macOS updates on your system.

**Comment by mavethee** [comment]
Why people still have troubles to keep their devices up to date 💀 Could stay on one release lower than latest if you're gonna update your stuff once in a blue moon, OS updates are for a reason.

**Comment by immranderson** [comment]
> Sorry but I legitimately don't understand how an error message stating "Please update macOS to a supported version" is not clear/explicit enough that you need to check for macOS updates on your system.

The simple fact is that the wording `a supported version` is vague -- and no where in any documentation are there explicit statements on which device configuration/versioning supports which software version. A lack of a linked issue, or no breadcrumbs left behind for users to figure things out can be frustrating too. 

I had put in a good faith effort to search through existing issues/open/closed PRs to try to ascertain what was going wrong, and it was difficult to discover what was up. 

The silver lining here is that this comment thread will be able to serve as guidance for future users who are lost.

As an aside, some folks (like myself) subscribe to the philosophy that all users are idiots (I'd know, I'm one of them!) -- however, these issues and annoyances that come up are also opportunities for improvement in usability/messaging/etc. I'll take this as an opportunity to go spelunking around the codebase and see if I can contribute some things which can help make life less stressful for everyone involved :-)

**Comment by nastys** [comment]
> The simple fact is that the wording `a supported version` is vague -- and no where in any documentation are there explicit statements on which device configuration/versioning supports which software version.

Maybe I could've worded it a bit better; however, both the Downloads and Quickstart pages do state that the supported versions are 12.6+, 13.0+, 14.3+ or later.

**Pull request merged**
