### PR TITLE
Trophy fixes

### PR DESCRIPTION
**Pull request by Farseer2**
Should fix Kung Fu Panda 2, Raging Blast 2 and probably some more...

### CODE REVIEW

**Comment by arkhamsaiyan** [comment]
although it may just be my processor because I've got an 8350 Raging Blast 2 looks absolutely beautiful either on vulkan or opengl. It froze in the beginning cutscene but pressing start really fast fixed that

**Comment by arkhamsaiyan** [comment]
OMG ON OPENGL THE BUDOKAI HD COLLECTION BOOTS

**Comment by zminhquanz** [comment]
Does it fixed trophy hangs in Odin Sphere Leifthrasir ?

**Comment by frymezim** [comment]
@Farseer2 
could you implement sceNpTrophyGetRequiredDiskSpace as this was requirement for games like star ocean 4 the last hope and other games as well.

**Pull request merged**
