### PR TITLE
Support for Namco GCon3 gun

### PR DESCRIPTION
**Pull request by bevanweiss**
Allows for calibration of gun in menu system, all buttons appear to operate.
Requires WinUSB driver under Windows (via Zadig or similar).

NOTE: Requires real Namco GCon3 gun

### CODE REVIEW

**Comment by dudesh34** [comment]
Hi,
anyway to make it work with a mouse, so we can play with wiimote/aimtrack and etc?

**Comment by bevanweiss** [comment]
Magic 8 Ball says: "Don't count on it"

The game itself has the USB 'driver' for the gun. It knows nothing about wiimotes/aimtracks.
Emulating them as equivalent USB devices will definitely be too much work for my interest.

The games do support controller fallback (I think). But I don't think we could patch into the controller fallback stuff to get much in the way of similar handling for wiimotes / aimtracks (I don't have either, so don't know how they work)

**Comment by legend800** [comment]
rpcs3 already supports mouse to emulate PS Move, which is mostly the same games as guncon is supported. It's not perfect and doesn't work for all games but it's something. Here's hoping we'll have the equivalent for guncon too at some point.

2020-08-26 19_06_55-Window

**Comment by bevanweiss** [comment]
PS Move and GunCons are VERY different here.
PS Move has an entire PS Move API.
GunCon has a device driver WITHIN the game for the GunCon, so not at all similar to PS Move, and not something on our side (emu) of the fence.

For the gun games that support the PS Move gun, the existing (and future) PS Move emulation should work. But this PR was specifically about GunCon support.
GunCon != PS Move, and I don't believe the games using the GunCon supported PS Move.

**Comment by legend800** [comment]
If this is accurate, it was just 3 games, which were also bundled together in 1 game (TC Razing Storm) and also supports PS Move. 

https://en.wikipedia.org/wiki/GunCon#GunCon_3_compatible_games

**Comment by bevanweiss** [comment]
@legend800 precisely the case.
I have a GunCon3, and I have TimeCrisis 4, so I wanted to get them working together, hence this PR.

Would be awesome if you wanted to put together a PR to support mouse/PS Move/Wiimotes/aimtrack etc for the other games :)
There is some info available on the data format sent by the GunCons so you could (perhaps) re-format Wiimotes/aimtrack data into the GunCon USB format recognised by these games... But it sounds painful to me.

**Comment by legend800** [comment]
Aimtrak's are already supported, since all they do is control the mouse, and mouse is supported as pictured above (PS move). Same for Wii remotes, but for those you need an app or Dolphin Bar to map your remote to mouse. No emu code changes needed! :)

**Comment by darkphoenixfox** [comment]
I tested with a Guncon3 and tracking works as good as in a real PS3. The game seems to be missing some of my trigger presses when trying to shoot fast, that might be related to game issues not specific to the guncon support.

**Comment by legend800** [comment]
The missing input is an rpcs3 issue that's been around since the beginning. I've found setting fps=30 fixes it for me.

**Comment by dudesh34** [comment]
Hi,
where do you change the fps in the emulator? vblank?

**Pull request merged**
