### PR TITLE
rsx: Fixes

### PR DESCRIPTION
**Pull request by kd-11**
Lots of changes
- Reimplemented the fragment shader pipeline (partially) and optimized cache access
- Implement texture data casts where possible (1D <-> 2D) 
- Implement render-to-cubemap [realtime reflections] (still incomplete, but should work most of the time)
- Fixes for texture size detection using rsx antialias modes
- Fixes for hanging when using WCB
- AMD driver bug workaround (ugh)

TODO:
- [x] Dragon Quest Builders does not show 3D anymore with vulkan
- [x] Eternal sonata LSD trip
- [x] Excessive blur in some games (looks like only nvidia is affected)

### CODE REVIEW

**Comment by Lemiru** [comment]
Differences I have found for now:
1. After Burner Climax:
Master:
screen shot 11-01-17 at 03 54 pm
This PR:
screen shot 11-04-17 at 04 46 pm
2. Eternal Sonata:
Master:
screen shot 11-04-17 at 04 27 pm
screen shot 11-04-17 at 04 28 pm
This PR:
screen shot 11-04-17 at 04 42 pm
screen shot 11-04-17 at 04 44 pm

**Comment by MarioSonic2987** [comment]
Now Grid has correct aspect ratio:

image

**Comment by digitaldude555** [comment]
screenshot 1985

Fixed half screen issue of oreimo.

**Comment by digitaldude555** [comment]
screenshot 714
Before.
screenshot 1987
After.

**Comment by Kravickas** [comment]
**NHL 15** 
On this PR spams 
`E {rsx::thread} RSX: Cannot perform scaled blit for depth/stencil images`
------------------------------
**Dirt 1**
corrected ratio, but some blur bug
obrazek
obrazek

**Comment by MarioSonic2987** [comment]
image
KH2 has correct bloom.

**Comment by Sora3100** [comment]
image
Looks like it fixes the shading on characters in Graces F
image
Doesn't fix half screen issue though or blurry skits or that you still need to delete shader cache every time

**Comment by digitaldude555** [comment]
screenshot 1824
Before.
screenshot 1990
After.
Big improvement.

**Comment by Xcedf** [comment]
Here's the report
Things that were improved
Heavy Rain Demo
Before(Master)

After(this PR)

Shadow of The Colossus
Before

After

UFC 2009 Undisputed Demo
Before

After


And things that regressed
Red Dead Redemption
white faces and shadows are gone
Before

After

Heavy Rain 
menu and some other parts of the game look overblured
Before

After

**Comment by Xcedf** [comment]
Another progress
Sonic & All Strars Racing Tranceformed Demo
now shows some render
Before

After

**Comment by Ekaseo** [comment]
Ni No Kuni missing 3D Graphics in overworld
ninokuni

**Comment by AniLeo** [comment]
@digitaldude555 You can report improvements here unless kd-11 tells you otherwise.

**Comment by digitaldude555** [comment]
Okay thanks ani.
screenshot 880
Before.
screenshot 1994
After

**Comment by Lemiru** [comment]
Quick update about Eternal sonata:
I noticed that this LSD Sonata thing is only present on Vulkan. Also it aren't always present (propably it appears only in cutscenes and tutorials)

**Comment by Asinin3** [comment]
Before character models were all black now they're fixed.
image

**Comment by Renusek** [comment]
Yakuza (Ryu ga Gotoku) Ishin/0/Kiwami are still broken 😕

**Comment by jjsat** [comment]
master:
grafik
this pr:
grafik

**Comment by digitaldude555** [comment]
screenshot 623
Before
screenshot 2021
After

Save to say all LSD graphics games improved.

**Comment by kamer1337** [comment]
Tony Hawk's Project 8 is totally broen with this pr

project8

does not display 3D correctly, menus are fine

**Comment by Zangetsu38** [comment]
Other regression in map world ingame on Ni no kuni
image

**Comment by Asinin3** [comment]
Ni No Kuni is only missing graphics in overworld with Vulkan, OpenGL is fine.
image

**Comment by liududu** [comment]
Also has blur bug in The Trail of the Cold Steel II
Before
before
After
after

**Comment by kd-11** [comment]
I cannot reproduce some of the bugs here. Its my fault for not mentionung this, but shader cache needs to be wiped before using this. I'll bump the shader cache version before this is merged to avoid such issues

**Comment by Asinin3** [comment]
Maybe everyone can edit their comment after re-testing with deleted shader cache to keep this clean.

**Comment by Sora3100** [comment]
My testing was done with the data folder being deleted beforehand, also using nvidia card, someone on discord reported yesterday that he had different results with AMD

**Comment by JackONeill12** [comment]
From Dust now has a lot of Dust covering half the picture in Vulcan.  OpenGL stayed the same.

Vulcan Master
from_dust_old_vulcan

Vulcan this PR
from_dust_new_vulcan

OpenGL Master
from_dust_old_opengl

OpenGL This PR
from_dust_new_opengl

**Comment by Psycho-A** [comment]
This seems to be fixed #3681 in Silent Hill: Downpour.

**Comment by Kojikun1** [comment]
Nier Replicant - Vulkan 
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x7e): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKTextureCache.h:57)

**Comment by Kravickas** [comment]
Intro and replays in NHL 15 regressed with ''normal'' graphic over master to this 
obrazek

OGL to this 
obrazek

**Comment by kd-11** [comment]
The depth bug is fixed now

**Comment by Zangetsu38** [comment]
DQB, and Ni no kunni fixed
image

image

**Comment by Asinin3** [comment]
Hotline Miami 2 still broken:
image

**Fixed:**
Ni No Kuni - overworld missing graphics with VK
DeS - No longer has excessive blur with this PR

**Comment by greentop** [comment]
**Ubuntu 16.04 / Nvidia 387.12 / LLVM 4 / (PR #3699 as of b391042)**

**RPCS3 GPU Additional Settings:**
Enabled - Use GPU Texture Scaling / 16xAF

**Game: ToCS2 BLUS31597**

The game textures are blurred when using the Vulkan renderer. Affected are all game textures. See screenshots below for comparison.

**Vulkan screenshot:**
screenshot from 2017-11-05 22-10-30

**OpenGL Screenshot:**
screenshot from 2017-11-05 22-14-40

**Comment by Asinin3** [comment]
I can't reproduce the ToCS blur on windows, tried enabling the same GPU settings as well.

**Comment by Marthgun** [comment]
using b391042

Tales of Graces F, BLUS30903, 
togf_strictrenderopgl2
 still getting those transparent lines (along with the other issues liike blurred skits), i can only use Strict Rendering Mode, otherwise graphix are fawked.

idk if this is a regression from Sora3100  's post above or not.  i didn't test the earlier build he/she must have used.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1444905/RPCS3.log.gz)

**Comment by Illynir** [comment]
Yes, black lines came back on Tales of graces F. There was a problem with Depth on Nvidia, corrected now.

It's probably due to that.

**Comment by Vlakipn** [comment]
Progress (ingame) on Resident Evil CV with this PR:
https://youtu.be/Od9BpbOClFw

**Comment by Sora3100** [comment]
Can confirm Graces lines are back, blue veil is also back in Vesperia, however, on OpenGL, it looks like this:
image
Also experiencing some flickering on OpenGL.

**Comment by Kravickas** [comment]
With latest commit Tony hawk P8 regression fixed
obrazek

**Comment by aakh1361** [comment]
image
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1446430/RPCS3.log.gz)

**Comment by aakh1361** [comment]
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1446469/RPCS3.log.gz)

**Comment by Asinin3** [comment]
@aakh1361 Use 1280x720

**Comment by kd-11** [comment]
Please retest alot of games and watch out for super bright games with the latest commit. That is a sign of a game being buggy and not having a vertex attribute enabled or activated but reading from it anyway. I have decided to just set a default value of 1 instead of 0 to avoid errors from multiplication and division with such values (they seem to be ignored on ps3)

**Comment by Sora3100** [comment]
Tales of Vesperia blue veil is still missing in OpenGL

**Comment by Marthgun** [comment]
No difference on Tales of Graces F from my last post, (transparent lines still present, skit blur, etc)

**Comment by Gamedev1909** [comment]
https://youtu.be/B36UWw5cT8Y looking good

**Comment by Illynir** [comment]
Regression on Ni no kuni, menu and videos are ultra white. Gameplay is normal, however.

unknown 1
unknown 2
unknown 3

**Comment by greentop** [comment]
**Ubuntu 16.04 / Nvidia 387.12 / LLVM 4 / (PR #3699 as of 627726d)**

**RPCS3 GPU Additional Settings:**
Enabled - Use GPU Texture Scaling / 16xAF

**Game: ToCS2 BLUS31597**

The blurring of game textures when using the Vulkan renderer remains present.

**Comment by Psycho-A** [comment]
Silent Hill Downpour. 
After 0.0.3-6726 log is full of this:

> E {rsx::thread} RSX: Blit request denied because the destination region does not fit! x812

Just like at #3681 instead of "Framebuffer memory occupied by regular texture"...
nVidia GTX 760 Ti video card.

**Comment by kd-11** [comment]
@greentop
That bug is different from the earlier depth blur bug (where depth of field is applied incorrectly) and seems to affect texture quality only. I am not sure why that is but since its not reproducible on windows it will be difficult to diagnose right now.

Ni no kuni "regressed" due to how a game bug is being handled. The two options we have are:
1. correct graphics in shaders that only do add/sub with invalid data and black output in shaders using mul/div
2. correct graphics in shaders using mul/div and overbright in shaders that use add and likely garbage where sub is used (less likely)
The only "true" solution is to interpret instructions like we do for CPU stuff (hint: performance hit) or generate dynamic shaders after running variable analysis in the cpu which is a huge task and will add on to the problems we already have with the shader cache so I'll leave it as is for now (with overbright menus in some games to avoid generating NaNs from division by 0)

**Comment by Kravickas** [comment]
Pre-macth intro and replays still doesnt work in NHL, but gameplay works, idk why its all rendered like gameplay if it work.

**Comment by MarioSonic2987** [comment]
image
In Saints Row: The Third, graphics have improved.

**Comment by Kojikun1** [comment]
Nier Replicant -  Vulkan - With Write Color Buffers 
Is still with this error 
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x7e): 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKTextureCache.h:57)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1450965/RPCS3.log.gz)

**Comment by Marthgun** [comment]
using e6c84fe

No difference on Tales of Graces F from my first post, (transparent lines, blurry skits, menu background half black).

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1451411/RPCS3.log.gz)

**Comment by tabnk** [comment]
Virtua Fighter 5 Color issue finally fixed :). Tks

**Comment by Gamedev1909** [comment]
Nothing changed for ninja gaiden sigma yet but the amount that is fixed is amazing way to go

**Comment by M220** [comment]
Hi
Tnx To Kd-11 Work FPS In My Games Have Increased Greatly ( + Graphics )!
And One Thing To Report :
After This Commit ( Never Happened Before This Commit , in Before , I Have Passed Through First Cutseen And Walked To The Salon ) In RDR After First Cutseen ( And When You Go Actually In game ) Game Freeze With This Error :
F {rsx:thread} class std: :runtime_error thrown:  [attrib buffer ] working buffer not big enough, buffer_length=268435456 allocated=4039168 requested=4237692448 Guard=4194304 Largest_pool=234240 ( in file c:\projects\rpcs3\rpcs3\emu\rsx\d3d12\../common/ring_buffer_helper.h:78)

And in One Other Situation , I Was Getted This Error ( Its Almost Impossible To Walk In Game After This Commit ) And This Is It : 
F {rsx:thread} class std::runtime_error Thrown Unknown Vertex Base Type 0 (in File Emu\RSX\gcm_enums.cpp:16)
( i Failed in Cathing The RPCS3 Log File Because this Time The Whole Emulator Get Unresponded And I Closed It With End Task So There was No Changelog )

Also , After Downloading ( I Think , Sorry For Not Memorizing It ) The 65xx ( Or 64xx But Higher Chance for 65xx ) RDR Say This Error Almost All Time In The Game :
E {rsx:thread} RSX: Invalid Framebuffer Setup, w=0, h=0
Log For This Error is Also In The Log File ( Because Error Is Still Exist So... ) My Number One Report Had a Connection with This Commit And My #2 Report Was For Kd-11 And Have No Connection With This Commit But It Was For #1 Report Game So I Reported It Here :)
Tnx To All Beautiful Devs of This Awesome Emulator =)

Here is The Link For RPCS3.log :
https://drive.google.com/file/d/17AvwoQEy7OUoShpQXqxVwCLBs-cv6n7u/view?usp=drivesdk

**Comment by M220** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1454011/RPCS3.log.gz)
Here is The More Easy Way To Get that ( Sorry Because i Commented With Mobile )

**Comment by AniLeo** [comment]
@M220 RDR is not a good test scenario, ignore it for now

**Comment by Aske1836** [comment]
\[T]/
Thanks for the hard work KD-11! Compatibility in about 3 of my games went from ingame to near-perfect!

**Pull request merged**
