### PR TITLE
vk: Use macros from Vulkan SDK

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by Megamouse** [comment]
This in turn sounds like a weak argument against the macro if you only use it in 5 occasions. (Ironically the small usage makes that a weak argument for the macro as well)

**Comment by scribam** [comment]
The main intent of this PR is to avoid mixing two different ways (strings and macros) to identify the extension names. Since we started to use the macros (I can easily find them by looking at "VK_.*_EXTENSION_NAME" btw) before the strings , I though it was the recommended way. I don't really mind if we use strings (although I personally prefer macros :slightly_smiling_face:) but I think we should stay consistent by doing so.

**Comment by kd-11** [comment]
I would have preferred the macros as well if they resembled the strings they map to. This would have been straightforward if khronos didn't feel the need to add the _EXTENSION_NAME suffix; makes the definitions not map directly to what is in spec. The other macros used were only for surface extensions which are different depending on the target platform, I plan on changing that as well to only have one and pre-select the proper string from vulkanapi.h. Thisisfine I guess; it bugs me but if enough people want it I can still just merge it.

**Comment by Megamouse** [comment]
redefine the macro without the _EXTENSION_NAME XD

**Comment by kd-11** [comment]
You kid but I was considering that as well. To redefine them to match the spec entries the first two parts are all caps and the rest are always no caps. Or to wrap extension strings in some struct or something that would allow to pass something resembling the extension I'm trying to load.

**Pull request merged**
