### PR TITLE
Ninja

### PR DESCRIPTION
**Pull request by janisozaur**
Ninja, the build system. Developed by people behind chrome browser it is meant to be _the fast_ build system.

### CODE REVIEW

**Comment by janisozaur** [comment]
A bit oddly, it doesn't look to speed up build of RPCS3, I'll look if this is something I can address.

**Comment by hcorion** [comment]
Probably the reason it didn't speed up the build was because of the time it takes to download Qt. I need to work on caching that download one of these days.

**Comment by janisozaur** [comment]
But the download is not happening via ninja, it is done earlier. Travis offers a breakdown of timings for each of the entries in build script (the value to the right in logs), you can see it took 666s to build here: https://travis-ci.org/RPCS3/rpcs3/jobs/312247395, but previous jobs are all over the place:
* 24s https://travis-ci.org/RPCS3/rpcs3/jobs/311881578
* 137s https://travis-ci.org/RPCS3/rpcs3/jobs/311363132
* 435s https://travis-ci.org/RPCS3/rpcs3/jobs/308118774

In one of earlier tests it only took 16s: https://travis-ci.org/janisozaur/rpcs3/jobs/312129220 that leads to a question: is ccache or some other similar thing being used? I can't find any other explanation for such wildly different times.

**Comment by janisozaur** [comment]
I think I found the answer

https://github.com/RPCS3/rpcs3/blob/d8ae94df5b83b4e85d858745ec41ac4ad925e07d/.travis.yml#L14-L15

**Comment by janisozaur** [comment]
Ping?

**Pull request merged**
