### PR TITLE
libad: Enable LLE load

### PR DESCRIPTION
**Pull request by AniLeo**
Removes libad from sys_prx ignore list.

It will only affect games that call for it, making them always progress further with the PPU Recompiler instead of dying on an Unregistered Function, as there's literally zero HLE implementation of libad.

Investigated and tested with Guitar Hero 5 [BLES00576], which now works with PPU Recompiler with this Pull Request.

**Note to testers:** Even without liblv2 loading mode, if the game calls sys_prx_load_module on libad, it will be loaded.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
i have already enable this in lv2 for Wipeout HD

**Comment by AniLeo** [comment]
Don't have Wipeout HD, found it with GH5, but it should work with all games

**Comment by Zangetsu38** [comment]
yes, no have problem

**Comment by AniLeo** [comment]
Any reason you didn't remove "libad_billboard_util.sprx" ? @Zangetsu38

**Comment by Zangetsu38** [comment]
no, i have just remove only lle user by Wipeout HD for libad, for that, i have remove 3 lle in my build

**Comment by ScorchEmber256** [comment]
Jak and Daxter still having similar issues
F {PPU[0x100000e] Thread (GOAL) [0x0001b690]} class std::runtime_error thrown: Unregistered PPU function

**Comment by AniLeo** [comment]
What game exactly?

**Comment by Zangetsu38** [comment]
not only this, rain have same think

**Comment by ScorchEmber256** [comment]
Jak and Daxter HD Collection, all three games crash, but I'm not sure which module crashes

**Comment by AniLeo** [comment]
Rain Demo crashes on boot with Recompiler and ends with Access Violation with Interpreter, no Unregistered Function. Full game only?

**Comment by Zangetsu38** [comment]
i don't know, i trhink yes, load few lle inside game and show 
>E {PPU[0x1000004] Thread (UnityMain) [0x00c13000]} PPU: Unregistered function called (LR=0x12d1034)

**Pull request merged**
