### PR TITLE
Unfixes

### PR DESCRIPTION
**Pull request by Nekotekina**

### CODE REVIEW

**Comment by hcorion** [comment]
This PR fixes the loading issue some people were having with Scott Pilgrim vs. The World: The Game (At least on Linux).

Notable output:
```
 sys_net: sys_net_bnet_socket(): unsupported family (0)
...
sys_net: sys_net_bnet_socket(): unsupported type (6)
```

**Comment by Zangetsu38** [comment]
regression for beyond two souls, now game cause rpcs3 crash
[Appveyor build RPCS3.log](https://github.com/RPCS3/rpcs3/files/1346313/RPCS3.log)

in master game works with libnet, without spam this
>·W 0:00:52.810980 {PPU[0x1000015] Thread (PSTouchService) [0x012ac4e8]} libnet: socketselect(nfds=2, readfds=*0xd00b29e0, writefds=*0x0, exceptfds=*0x0, timeout.tv_sec=0, timeout.tv_usec=5000)

**Comment by JackONeill12** [comment]
This PR fixed Portal 2 MEM Exception. Now goes a bit further and spams 
U {PPU[0x1000012] Thread (libjingle) [0x013c516c]} sys_net TODO: sys_net_bnet_select(fds=4, readfds=*0xd0226930, writefds=*0xd02269b0, exceptfds=*0x0, timeout=*0x0)

**Comment by JackONeill12** [comment]
Portal 2 is now going into the menu. But very slow because LLVM doesn't work in this game and I had to use Interpreter.

**Comment by MarioSonic2987** [comment]
Saints Row: The Third and Saints Row IV reaches title screen and freeze with this:
`E {PPU[0x1000000] Thread (main_thread) [0x03854c04]} sys_net: Unknown/illegal socket error: 10054`

[RPCS3.log.gz SRTT](https://github.com/RPCS3/rpcs3/files/1346956/RPCS3.log.gz)

**Comment by JusicP** [comment]
image
Youtube now working.

**Comment by aakh1361** [comment]
image
image
image
image
image

**Comment by AniLeo** [comment]
@aahk1361: Further posting of files download links will lead to a ban.

**Pull request merged**
