### PR TITLE
Qt: adjust resolution scale logic in settings dialog

### PR DESCRIPTION
**Pull request by Megamouse**
Changes some tooltips and words.
Updates the resolution slider based on the used tv output resolution

### CODE REVIEW

**Comment by kd-11** [comment]
Uhm, no. Use 720p for the calculation.

**Comment by lextra2** [comment]
Why not remove that option from the GUI? I've played RPCS3 for years but never have I changed the default 720p. Seems like a noobtrap.

**Comment by AniLeo** [comment]
There are some games that change assets depending on what resolution they think they're outputing to, like VNs that have separate 720p and 1080p movie folders

**Comment by Satan86** [comment]
And games like Gran Turismo 5 have significantly different Rendering from 720p to 1080p, where the latter is actually lighter on the GPU

**Comment by lextra2** [comment]
Sounds like a setting for a GameDB (pcsx2l. Any plans for that?

How many games break by changing the virtual default res vs how many games improve? Would be interesting to know.

**Comment by Megamouse** [comment]
Ugh I guess someone else can cook up a "solution" for this "problem"

**Pull request closed without merging**
