### PR TITLE
[Testers needed] Fix current Problems (alternative to PR below)

### PR DESCRIPTION
**Pull request by Megamouse**

### CODE REVIEW

**Comment by Megamouse** [comment]
this may also fix #9410

**Comment by GitArUs** [comment]
Fixes #9406, so probably also whole #9410.

**Comment by Nekotekina** [comment]
The problem is src_loc gets constructed unconditionally

**Comment by Nekotekina** [comment]
Sadly, even if std::source_location gets implemented, it may have similar problem.

**Comment by Megamouse** [comment]
While this might work, it apparently adds unwanted instructions, so we'll have to accept the verbose code for now

**Pull request closed without merging**
