### PR TITLE
Revert "Adding Git in README and some little change"

### PR DESCRIPTION
**Pull request by DHrpcs3**
Reverts RPCS3/rpcs3#1236

### CODE REVIEW

**Comment by Zangetsu38** [comment]
What this ?

**Comment by danilaml** [comment]
@DHrpcs3 our irc is @ freenode right now, in case you missed.

**Comment by Bigpet** [comment]
@DHrpcs3 should we just force push a version before the change to remove it completely? I mean it's unlikely that these files would cause catastrophic conflicts.

**Comment by Zangetsu38** [comment]
@DHrpcs3 I do not understand what I did was not much, and it was just fine.

**Comment by Bigpet** [comment]
reverted

**Comment by tambry** [comment]
@DHrpcs3 Would it be OK to tag v0.0.6, as a lot of time has passed since the last tag and many improvements have been made. Once you are OK with the tagging, I will open a PR for changing the version number in RPCS3 to v0.0.6 and will tag it.

**Pull request closed without merging**
