### PR TITLE
Support for GLSL 420

### PR DESCRIPTION
**Pull request by lvonasek**
Mesa 17.1 added support of GLSL 420 to many graphic cards and it is not necessary to requiere 430.

Removed from this pull request:
Issue #2735 makes many games not working on Linux, this pull request fixes it.

### CODE REVIEW

**Comment by flash-fire** [comment]
I'm not amazing with git but here's what I'd do.
1) cherry pick your stuff onto a new branch
2) git rebase with master upstream (if necessary)
3) force push back onto original branch. Force push onto remote.

Cheers

**Comment by lvonasek** [comment]
My git skills are really limited. I did following:
fork
commit
https://help.github.com/articles/syncing-a-fork/
commit
pull request

**Comment by kd-11** [comment]
Mesa already supports ARB_explicit_uniform_location and GLSL 450, so the downgrade isnt really necessary and conflicts with the rest o the renderer where locations are used instead of bindings. The declare bit is the only relevant change, although it is a hack. diff_color and spec_color should not be declared if the explicit back/front variants are also declared.

**Comment by lvonasek** [comment]
I am using current stable drivers, a lot of Intel video cards does not support higher OpenGL version than 4.2 (before Mesa 17.x, it supported OpenGL 3.3 only):
lubos@lubos-laptop:~$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.1.4
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.1.4
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.1.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

I understand conflicts now, I will take a look on it

**Comment by lvonasek** [comment]
There are only three bindings (and one added by me to support GLSL 420):
GLVertexProgram.cpp:    OS << "layout(std140, binding = 0) uniform ScaleOffsetBuffer\n";
GLVertexProgram.cpp:    OS << "layout(std140, binding = 1) uniform VertexConstantsBuffer\n";
GLFragmentProgram.cpp:  OS << "layout(std140, binding = 2) uniform FragmentConstantsBuffer\n";
GLVertexProgram.cpp:    OS << "layout(binding = " << location++ << ")" << "     uniform " << samplerType << " " << PI.name << "_buffer;\n";

So it should be enought to change int location = 1; to int location = 3; Or do I understand it incorrectly?

Is it really so unimportant to add more supported HW? Here you can see which GPUs need this pull request: https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Seventh_generation

**Comment by hcorion** [comment]
Basically, the issue with the submodules is that you didn't update them, since they were updated recently
`git submodule update --init`

**Comment by lvonasek** [comment]
@hcorion Is there way how to fix it when it is already commited incorrectly?

**Comment by hcorion** [comment]
You can just do the above command (`git submodule update --init`), and then add those files.
`git add 3rdparty/ffmpeg`
`git add 3rdparty/hidapi`
`git commit -m "Removed submodules"`
`git push`

**Comment by kd-11** [comment]
@Ivonasek You're getting compilation error because of glsl version? Do those GPUs not support ARB_explicit_uniform_location? You can still use locations without relying on glsl 430 explicitly.
The reason I ask is because shaders are undergoing an overhaul and I'm targeting 4.3/430. I have already run into issues with intel drivers that need workarounds.

**Comment by lvonasek** [comment]
@hcorion In did not work:
lubos@lubos-laptop:~/playstation/rpcs3$ git submodule update --init
lubos@lubos-laptop:~/playstation/rpcs3$ git add 3rdparty/ffmpeg
lubos@lubos-laptop:~/playstation/rpcs3$ git add 3rdparty/hidapi
lubos@lubos-laptop:~/playstation/rpcs3$ git commit -m "Removed submodules"
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
        modified:   3rdparty/hidapi (untracked content)

Untracked files:
        rpcs3/rpcs3_autogen/

no changes added to commit

@kd-11 yes, compile error - "unsupported GLSL version". My GPU supports ARB_explicit_uniform_location but it is not garanted that other GPUs will support it (it is in Core since OpenGL 4.3).

**Comment by kd-11** [comment]
Ok then. Leave the version downgrade in place but remove the 'declared' hack. I know there will be games that dont work but those will be fixed properly later. It hides a critical flaw with the rsx 'linker' to have it silenced that way.

**Comment by danilaml** [comment]
Isn't it easier just to wait a little bit longer for proper 4.3 support? Looking at https://mesamatrix.net/ there is only one feature that is left for full 4.3 support on Ivy Bridge: GL_ARB_stencil_texturing (needs haswell or later). Or maybe it's possible to enable GLSL 430 support without this extensions (doesn't look like we are using it).

**Comment by mrcmunir** [comment]
yeah the workaround for ivy bridge use the script

```
#! /bin/sh
# Support OpenGL 4.3 and GLSL 4.30
export MESA_GL_VERSION_OVERRIDE=4.3
export MESA_GLSL_VERSION_OVERRIDE=430
./rpcs3
```
Copy this with .sh extension under bin folder rpcs3 and working fine 

Also this workaround will help working for some others games/apps with the specific profile.

Anyway wait it Jason mesa3d intel dev recently done some work which adds some of the infrastructure but they need in order to do this but it's still quite a bit of work.

In the future they are Opengl 4.3 core profile compilant by default and fix too the problem stencil texture requeriment in Vulkan backend under Ivy bridge gen7.

**Comment by kd-11** [comment]
After thinking about it this fix is incorrect. The binding value is the evaluated value at the location which is not what is intended here. It worked before vertex rewrite because vertex streams were updated with glProgramUniformLocation and a register name used for lookup, but now the value should evaluate to some large arbitrary number greater than 20. Either way, since mesa vars can be used to enable glsl 430, I dont see the need for this anymore.

**Comment by lvonasek** [comment]
Thanks to @mrcmunir for the workaround. I agree with @kd-11 that this pull request is senseless. Maybe would be good to add some info about overriding mesa version into README.md. I am not sure if it would help to make it working on OSX (OpenGL 4.1) but anyway it is good to know that requirement for OpenGL 4.3 does not have to be so strict :)

Thanks guys for time you spend with this PR.

**Pull request closed without merging**
