### PR TITLE
SPU/PPU reservations: Optimizations of week 23 of 2020 (non-TSX)

### LINKED ISSUE #8222: Massive performance drop in various games (Shadow of the Colossus, Call of Duty 3) after PR #8175
Massive performance drop in various games (Shadow of the Colossus, Call of Duty 3) after PR #8175

Win 10 1909
i3 6100 @ 4,5 Ghz
16 Gb RAM
GTX 1063
Also the sound became from being perfect to a stuttery mess. But it's because the performance drop.
10358 (before):
Screenshot_471
10361 (after):
Screenshot_470
Even more severe case:
10358 (before):
Screenshot_483
Performance were fine, although with graphical artifacts.
And now after. It's not that it won't go ingame. But with that speed it would take forever:
Screenshot_484

### PR DESCRIPTION
**Pull request by elad335**
* Apply optimized path in vm::passive_lock() when a newly acquired passive lock has been made.
* Do not forget old reservation passive ppu lock in syscalls so it won't need to reaqcuire it later when not needed, simply signal "idle reservations" state instead.
* Refactor cpu_thread::check_state() to be more optimized towards reservation pause signaling and refactor more uses of cpu_thread::state into the ultimate atomic op.
 * Implement "SPU GETLLAR polling detection", this is currently a setting in config file and is off by default, when being set to on it partially fixes the non-tsx regression mentioned in #8222.
* Make SPU loop detection setting dynamic.

Fixes #8222.

### CODE REVIEW

**Comment by galahadhiryu** [comment]
rpcs3-v0.0.10-2e58a00b
Using "SPU GETLLAR polling detection: true" restored the performance that i used to have while playing motorstorm 2.

**Comment by legend800** [comment]
> 
> 
> rpcs3-v0.0.10-2e58a00b
> Using "SPU GETLLAR polling detection: true" restored the performance that i used to have while playing motorstorm 2.

Why do you need spu getllar for MS2? stability on non-tsx cpu?

**Comment by jobs-git** [comment]
Well done! Experienced a 1 to 7 fps increase with an average of 2 fps in BLUS31437 from not-tsx cpu. However, I encountered the following:

```F {RSX [0x0005d80]} SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting in Advanced settings.
(in file D:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:2325)```

Here is the log 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4740769/RPCS3.zip)

**Comment by galahadhiryu** [comment]
> > rpcs3-v0.0.10-2e58a00b
> > Using "SPU GETLLAR polling detection: true" restored the performance that i used to have while playing motorstorm 2.
> 
> Why do you need spu getllar for MS2? stability on non-tsx cpu?

I have a ryzen 3500x, non-tsx cpu. After PR #8175 (#8222 ? ) i lost a lot of performance and got a lot of stuttering. But with "SPU GETLLAR polling detection: true" i kind of got back the performancing that i used to have.

**Comment by jobs-git** [comment]
@galahadhiryu were do you place `  SPU GETLLAR polling detection: true`? In core or video?

**Comment by galahadhiryu** [comment]
> @galahadhiryu were do you place ` SPU GETLLAR polling detection: true`? In core or video?

In the game's custom config .yml

**Comment by elad335** [comment]
core.

**Comment by Xcedf** [comment]
https://github.com/RPCS3/rpcs3/issues/8222
Beyond Two Souls
pre https://github.com/RPCS3/rpcs3/pull/8175 build

This PR (SPU GETLLAR polling detection didn't help)


Killzone 3
pre https://github.com/RPCS3/rpcs3/pull/8175 build

This PR (SPU GETLLAR polling detection also didn't help)

**Comment by elad335** [comment]
@Xcedf what is your CPU?

**Comment by Xcedf** [comment]
@elad335 9900k

**Comment by elad335** [comment]
Latest commit should increase TSX performance.

**Comment by elad335** [comment]
Idk if it was trivial for testers or not before, but when reporting performance regressions and attaching screenshots the least you can do to help developers is to enable performance overlay...

**Comment by Xcedf** [comment]
No difference
image
image

**Comment by Xcedf** [comment]
@elad335 latest force push, problem fixed, thanks

**Pull request merged**
