### PR TITLE
Show preview videos in game list

### PR DESCRIPTION
**Pull request by Megamouse**
#### Show ICON1.PAM preview videos if available when hovering over game list and game grid icons.

animated PAM

### CODE REVIEW

**Comment by ArchSonix** [comment]
Can you include a setting to this disable this please? Not sure if everyone wants this. (I'm not a fan personally ^^)

And maybe make it start after 300ms/500ms of hover, like a tooltip?

**Comment by vsub** [comment]
What do you thing about adding an option(or update the existing one)allowing you to choose what you want to see on the shaders loading screen(nothing\image\video preview)
Will that case any problems(maybe stuttering)

**Comment by gandalfthewhite19890404** [comment]
What is about playing music along with video (sometimes it could be missing)?

**Comment by TesseracT41** [comment]
Nice rick roll :D
image

**Pull request closed without merging**
