### PR TITLE
PPU: Fix thread entry detection false positives

### LINKED ISSUE #13974: [Regression] Gran Turismo 5 (Crash at Startup)
### Quick summary

Game doesn't boot up anymore, throws two E PPU errors on startup, started with build 15141, still persistent on 15143.

### Details

image

### Build with regression

v0.0.28-15141-6d918b56

### Attach two log files

Log made on 15143, tested both 15141 and 15143 as stated previously, stated on the regression the version where it first occurred.

15143 Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/11676072/RPCS3.log)

15139 Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/11676098/RPCS3.log)

### Attach capture files for visual issues

_No response_

### System configuration

Intel Core i7 10700KF @3.8GHz
PNY GeForce RTX 3070
Corsair Vengeance 4x8GB RAM running XMP I at 3600MHz
Windows 11 Pro (Insider Channel Build 23471.1000)

### Other details

I am a bit illiterate when it comes to programming but I'd assume the issue is related to **"0.0.28-15141: PPU: Sleep after returning from thread entry function"** which was introduced with 15141.

### PR DESCRIPTION
**Pull request by elad335**
Fixes #13974

### CODE REVIEW

**Comment by coolllman** [comment]
Call of duty 3 also not boot and fixit by this pr.

**Comment by FlexBy420** [comment]
> Call of duty 3 also not boot after #13966 and fixit by this pr.

Cod 3 boots just fine on latest master for me 🤔

**Comment by elad335** [comment]
He used liblv2.sprx hle, you can say it fixes evrey game with that logic 🤣🤣

**Comment by coolllman** [comment]
Yes liblv2.sprx is checked, all work without liblv2

**Pull request merged**
