### PR TITLE
Make fs::dir::open return false on failed metadata instead of crashing

### PR DESCRIPTION
**Pull request by zekesonxx**
I have a bunch of symlinks in `$rpcs3/dev_hdd0/disc` to my network drive. If I don't have that drive mounted, I get:
```
$ ./bin/rpcs3
terminate called after throwing an instance of 'std::runtime_error'
 what():  Verification failed (e=2): dir::read
(in file /home/zekesonxx/bullshit/rpcs3/Utilities/File.cpp:1261)
[1]    14339 abort (core dumped)  ./bin/rpcs3
```
which is less than pleasant.

Now rpcs3 will fail gracefully on broken symlinks.

Q. Why doesn't this log or something when it fails to get metadata?
1. File.cpp doesn't have Log.h included, feels like a waste just for this
2. It already doesn't log if it fails to readdir
3. If `fs::dir::open` fails, and it matters, whatever is calling it will log a more useful error anyways.
4. `[8:11 PM] Megamouse: then just ignore it.`

addendum: `[8:22 PM] Megamouse: (don't quote me so neko knows possible culprits)`

### CODE REVIEW

**Comment by Nekotekina** [comment]
Thanks but needs also set set g_tls_error when returning false.

**Comment by zekesonxx** [comment]
How's that?

**Comment by Nekotekina** [comment]
Sorry, it seems the correct solution would be returning next directory instead. False indicates the end of the directory list, and the TLS error is not applicable here as well.

**Comment by zekesonxx** [comment]
Third try's the charm?

**Pull request merged**
