### PR TITLE
SPU: Improve SPURS Task limit algorithm

### LINKED ISSUE #16127: [Regression] Some Insomniac games crash to desktop after #16124
### Quick summary

After #16124 some Insomniac games crash to desktop every time it tries to display 3D, even when the SPURS thread is set to "Unlimited"

### Details

The broken games being:

- Resistance: Fall of Man
- Resistance 2
- Ratchet & Clank Future: Tools of Destruction
- Ratchet & Clank Future: Quest for Booty

### Build with regression

v0.0.33-16959-60b5adab

### Attach two log files

[RPCS3_RFOM_working.log](https://github.com/user-attachments/files/17151002/RPCS3_RFOM_working.log)
[RPCS3_RFOM_crash.log](https://github.com/user-attachments/files/17151004/RPCS3_RFOM_crash.log)

### Attach capture files for visual issues

_No response_

### System configuration

- SYS: RPCS3 v0.0.33-16959-60b5adab Alpha | master
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2024-09-26T08:13:10
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 551.86.0.0
- SYS: Firmware version: 4.88

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Test performance regressions with #16128 please.
Also fixes #16127

### CODE REVIEW

**Comment by Margen67** [comment]
penalty*

**Comment by JimScript** [comment]
Well it's an improvement over the regression, but it's still not as good as it was before, the spot I go to still stutters.

**Comment by elad335** [comment]
@JimScript  I need numbers, enable Performance Overlay and take the screenshots with it.

**Comment by JimScript** [comment]
Right, sorry, here is a more detailed sequence of images:

**Comment by elad335** [comment]
@JimScript Retest.

**Comment by elad335** [comment]
This also contains a hotfix so I merge it, but performance testing is still needed!

**Comment by shinra-electric** [comment]
Not related to performance, but Demon's Souls used to require the max spurs thread set to 3 (according to the wiki). 

Now it doesn't boot with it set to 3 (black screen), but it works fine set to unlimited. 

Other games that require this setting to be change should probably be tested and the wiki updated...

(Tested on macOS Arm)

**Pull request merged**
