### PR TITLE
Update asmjit submodule (Testers wanted!)

### PR DESCRIPTION
**Pull request by hcorion**
This took a while to get right because not all of the changes to asmjit we're documented, but I got it done.

This add roughly 1 year of changes/fixes to asmjit.

This could improve performance or make it worse. It could fix bugs or introduce bugs.

I'm still planning on doing a little cleaning up, but it should work. My game selection is rather small, so I would appreciate other people testing it out with other games, to make sure I didn't break anything.

### CODE REVIEW

**Comment by SakataGintokiYT** [comment]
I think it's better to wait for this https://github.com/jarveson/rpcs3/tree/spu-shenanigans

**Comment by hcorion** [comment]
Thanks @SakataGintokiYT for pointing out that commit.

@jarveson I see we've duplicated some work here, and I've been looking at your changes, which are very similar to mine. I noticed you start calling `InterpreterCall(op);` every once and a while, I'm wondering why that was.

Also, you've replaced the ASMJIT bug workaround, with:
```cpp
X86Gp cpu_var = compiler.gpz(X86Gp::kIdR12);
X86Gp ls_var = compiler.gpz(X86Gp::kIdR13);
```
I'm wondering how much of a difference that makes, and what the absence of setArg will do.

You also changed the qw0-2 and addr vars to 
```cpp
// win64 specific
X86Gp addr_var = compiler.zax().r32();
X86Gp qw0_var  = compiler.zcx();
X86Gp qw1_var  = compiler.zdx();
X86Gp qw2_var  = compiler.gpz(X86Gp::kIdR8);
```
I developed my code on Linux, in what way is your code win64 specific?
I'm also not sure what your doing with the FuncFrameInfo, and whether the ASMJIT error handler is worth the effort.

I would appreciate you reviewing my changes as well.

**Comment by jarveson** [comment]
Awesome work on getting asmjit updated! 
So the things you mentioned from my branch was because i was attempting to use the 'assembler' part of asmjit rather than the 'compiler' feature which is used currently, because i wanted to see if there was a difference in jit compile time, which, unfortunately, really didnt seem to make a noticeable difference during my testing, which is why the branch was left stale heh

In the assembler mode you choose and allocate registers manually, and the lines you mentioned was me just using cherry picked registers that are volatile/non-volatile/parameters on win64 calling convention. Another downside of the assembler mode is you cant use other nice features such as `XmmConst` which is why there are random `InterpreterCall(op);` littered about as i was lazy and just wanted to get a quick concept. So the code is heavily win specific, but can mostly be ignored as the 'compiler' version, which youve kept, will (should) adapt to whatever it is called on

As for your other questions, FuncFrameInfo can be ignored as its more 'assembler' specific, and the errorhandler, while nice, is only really helpful when asmjit fails to compile the code, which i dont think has ever happened so far.

Otherwise, looking at your code changes, functionaly it should be the same, barring any bugs/fixes in asmjit.

This kinda turned into a wall of text, but hope it helps, or let me know if something seems wrong/off/needs clarification

**Comment by AniLeo** [comment]
Seems to work well, finished Catherine Demo and Naruto Ultimate Ninja Storm Demo.

image

image

**Comment by woj1993** [comment]
Naruto Ultimate Ninja Storm Demo, Naruto Ultimate Ninja Storm 2 Demo, Bayonetta Demo. Everything works ok. @hcorion Good work.

P.S. Off topic. Do you have any experience in recompiler? I mean do you know why on LLVM there is mostly working game with black screen?

**Comment by davoodinator** [comment]
this breaks the fixes by nekotekina https://github.com/RPCS3/rpcs3/pull/2787 to dragon's dogma.. audio dies @ beginning of tutorial and cannot progress past first tutorial screen.

**Comment by AniLeo** [comment]
What do you mean this break the fixes if they haven't been merged

**Comment by davoodinator** [comment]
nevermind i mis understood how appveyor worked

it wasn't merging all of the pull lrequests like i thought

**Pull request merged**
