### PR TITLE
Lwmutex/Lwcond regression test (Not for merge) (Requires your help)

### PR DESCRIPTION
**Pull request by Nekotekina**
Chances are that these functions are unreliable, so I try to redirect them to very similar and more reliable functions in my opinion. *This PR shall not be merged.* Maybe I'll create similar ones or update this one later.

Try to test this PR with any broken games which freeze, throw access violation or misbehave in any way and see if they get magically fixed. *Do not report regressions*, only report "fixes" please.

Thanks in advance.

### CODE REVIEW

**Comment by raven02** [comment]
Testing it in progress

**Comment by AniLeo** [comment]
Please rebase , wanna test with the latest fix

**Comment by raven02** [comment]
I tested few titles that has issues but looks like they still have problems .

**Comment by Nekotekina** [comment]
Thanks, I hope there is nothing wrong with these syscalls after all.

**Pull request closed without merging**
