### PR TITLE
rsx: remove shader address check hack

### PR DESCRIPTION
**Pull request by elad335**
Real hardware doesnt ignore draw calls when the program address is 0. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/Fragment%20program%20address%200)

This hack was probably there as a workaround for `rsx_state::reset()` resets the program address when it shouldn't. now that the reset is fixed, this hack can be happily removed.

### CODE REVIEW

**Comment by kd-11** [comment]
Uhm, pretty sure now you will just segfault the emulator with nullptr. What does realhw draw with null fp address?

**Comment by elad335** [comment]
Nothing, it throws an exception.

**Comment by elad335** [comment]
All renderers fail with `F {rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file c:\users\elad\documents\github\rpcs3\rpcs3\emu\rsx\rsxthread.cpp:96)` as that register also holds the program's location type when such thing happens.

**Comment by kd-11** [comment]
Doesnt it make more sense to give meaningful info? `verify("Null shader program error!" HERE), shader! = 0`

**Comment by elad335** [comment]
Added a verify in set_begin_end and capture_draw_memory.

**Comment by vietnam13231** [comment]
AppVeyor failed: fatal: unable to access 'https://github.com/RPCS3/rpcs3.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
:-D

**Comment by stride21** [comment]
Battlefield: Bad Company crashes on start up and throws 
{rsx::thread} class std::runtime_error thrown: Verification failed: Null shader address!
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2377644/RPCS3.log.gz)

**Pull request merged**
