### PR TITLE
gl: Clear depth surfaces before use; Vulkan cleanup

### PR DESCRIPTION
**Pull request by kd-11**
Fixes https://github.com/RPCS3/rpcs3/issues/1954 for opengl by clearing new depth surfaces. Also cleans up some vulkan files.

~~It may be necessary to clear surfaces during prepare_ds_for_drawing as well, but I haven't seen any point in doing so yet.~~

### CODE REVIEW

**Comment by kd-11** [comment]
This game invalidates rtts and moves straight to drawing without clearing the buffers. I can fix it on all backends including DX12 by forcefully clearing depth after a buffer invalidation (prepare_render_targets), but I think a better mechanism is needed than that.

@vlj Are buffer contents considered invalid after m_rtts_dirty is set? If so, we should clear the buffers before reusing them (at least for depth buffers)

**Comment by Nezarn** [comment]
@kd-11 is it just me or this kills performance? (im getting 1/3rd speed on OGL, before i got 30 at titlescreen, now ~11)

Master: 
rpcs3_2016-07-20_22-38-48

This PR:
rpcs3_2016-07-20_22-37-24

(i can only post result from title screen since with my HD4600 i can't reach main menu with opengl)

**Comment by vlj** [comment]
Is there a command dump ?
m_rtts_dirty is set when surface format/offset/... is changed but the app can reuse the buffer afterwards

For instance a game can render solid geometry in a first pass using color + depth buffers, then render shadows in another depth buffer, then draw shadows on top of the color buffer filled in the first pass. The game reuses the color buffer data and we can't clear it (otherwise we will lost every geometry data rendered).

**Comment by kd-11** [comment]
@Nezarn What GPU are you using? It may be missing the GL_ARB_Clear_Texture extension. What level of opengl support is provided by HD 4600?

@vlj, Well, only Dx12 is affected by that specific issue since for some reason. Either dx12 is reusing old texture resources or the dx12 clear depth value during texture init is ignored, but I'll have to check. On vulkan and gl clearing new depth buffers to max depth fixes the issue.

**Comment by Nezarn** [comment]
@kd-11 I have that extension according to ogl extensions viewer.
openglex_2016-07-21_09-51-23

**Comment by kd-11** [comment]
@Nezarn It seems to be very poorly implemented on that system then. All this change does is call glClearTexSubImage after a new surface is created. I have no performance difference on AMD GCN.
I honestly think you are hitting the software fallback path, or the intel driver uses the same software method for texture clearing which is very bad. I'll modify to use opengl 3 clearbuffer although the code may get a little messier than it should

**Comment by Nezarn** [comment]
@kd-11 btw i don't know how it would change ingame performance, since theres a big performance difference in DX12 too. (between menu and ingame, in ingame sometimes i can even reach 30 (max) fps), and i think you should leave the current implementation if it works fine for every other real gpu. (and i dont think that weak iGPUs should matter in ps3 emulation :D)

**Comment by kd-11** [comment]
Well, I stumbled across complaints from people about poor performance using ARB_clear_texture. Even PCSX2 seems to have hit a similar issue and reverted back to clearbuffer*v for fbo surfaces. Apparently the speed is dependent on the type of clear being done, and depth clears are not particularly good.

**Comment by SakataGintokiYT** [comment]
GTX 960M -[Maxwell]
{rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'The fragment shader uses varying tex9, but previous shader does not write to it.
Out of resource error.
Fotoszok.pl


GTX 660 -[Kepler] 
Fotoszok.pl

**Comment by kd-11** [comment]
@Nezarn @SakataGintokiYT 
I have reworked the changeset a bit and removed refs to arb_clear_image instead going with good old glClear which should be very well optimized in drivers/hw. Please retest to see if performance is improved.

**Comment by Nezarn** [comment]
@kd-11 yep, fps is back to 30 at title screen
rpcs3_2016-07-21_20-52-15

**Comment by SakataGintokiYT** [comment]
@kd-11 
##### Title Screen - 22 FPS
##### 13 FPS  
Fotoszok.pl

**Comment by kd-11** [comment]
@Nezarn @SakataGintokiYT 
Last test. Should fix the invisible characters without performance degradation hopefully.

**Comment by Nezarn** [comment]
@kd-11 still getting 30 fps at title screen, so i guess it should be ok. (idk how does it perform at main menu with 3D model, so you need to wait fo @SakataGintokiYT for that :P)

**Comment by SakataGintokiYT** [comment]
@kd-11 
Fotoszok.pl

**Comment by kd-11** [comment]
Cleaned up for merge

**Pull request merged**
