### PR TITLE
vulkan: Fix vsync

### PR DESCRIPTION
**Pull request by kd-11**
- Tightens vsync control to not accept any modes that would allow tearing - including adaptive vsync.

The reason for this is that gcm is timed to control the virtual graphics controller instead of running uncapped and letting the display limit the framerate. This causes slight judder where the overhead of threads getting scheduled around means we might miss a present window. While the adaptive vsync does a good job allowing consistent frametimes, it does allow tearing to prevent judder. This PR forces true vsync. If you experience frame judder, disable the vsync option.

### CODE REVIEW

**Comment by Psycho-A** [comment]
Both Vulkan and OGL VSync never work for me if "Fast Sync" mode enabled in NVidia driver settings. Tearing is visible on every frame.

**Comment by Zangetsu38** [comment]
@Psycho-A yes, kd already know that, i have same think ^^

**Comment by isshininu** [comment]
I have forced vsync through Nvidia panel for all emulator ePSXe, PCSX2 and RPCS3.
Does this option still be a variant or it'll cause negative side effects now?

**Comment by kd-11** [comment]
Just use nvidia cpl if it refuses to apply. I refuse to enable straight up double buffered vsync and nvidia still tears when mailbox (triple buffered vsync) is enabled despite spec being very clear about it being tear free. It looks like on nvidia something is keeping vsync from working properly.

**Comment by Psycho-A** [comment]
@kd-11 I also noticed that emulator's VSync option works fine in windowed mode, but goes turned off when switching fullscreen. Strange things...

**Pull request merged**
