### PR TITLE
cellMsgDialogOpen: Go further using cellMsgDialogOpen2.

### PR DESCRIPTION
**Pull request by ikki84**
Notes:
Needs proper implementation (!)
The functions shows similarities but the bits in argument "type" may vary a little. 
Comparing both functions but testing in NPJA00014 I believe it could be acceptable until it be implemented properly

*Feel free to reject if it´s not allowed*

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Not good Idea, i said you, it is a works, but with you exemple here you using cellMsgDialogOpen2, so with this Log indicate use cellMsgDialogOpen2 or use really cellMsgDialogOpen, and so caused problem for know what gmae use really for debug etc.
But maybe use 
>cellSysutil.error("cellMsgDialogOpen(type=0x%x, msgString=%s, callback=*0x%x, userData=*0x%x, extParam=*0x%x)", type, msgString, callback, userData, extParam);

Or 

>LOG_ERROR(HLE, "cellMsgDialogOpen Uniplemented use cellMsgDialogOpen2", HERE);

Like this

For differentiate cellMsgDialogOpen and cellMsgDialogOpen2 used.

**Comment by ikki84** [comment]
Of course. its possible to add a log_error as you said.
@Nekotekina Do you have any suggestion?

**Comment by al0xf** [comment]
Whatever you do, there should at least be a log warning in cellMsgDialogOpen() indicating the function was called.

**Comment by Zangetsu38** [comment]
but in final, resultat exactly just same like my commit debug have a set in long time, just more clear, but with also problem for log for not indicate good called, i have return with my copy/rename caused like this.
@al0xf no, i have tested and no, juste called cellSysutil: cellMsgDialogOpen2., and probleme it there, need add log error for indicate use cellMsgDialogOpen by cellMsgDialogOpen2

**Comment by ikki84** [comment]
I will add it.

**Pull request closed without merging**
