### PR TITLE
Fix TSX freezes

### PR DESCRIPTION
**Pull request by Nekotekina**
Should fix freezes in some cases.

### CODE REVIEW

**Comment by darkdragonz12** [comment]
RDR enters the game with tsx enabled with this great work pr

**Comment by rajkosto** [comment]
MGS2/MGS3 in MGS HD collection still randomly has a chance to freeze on loading (only pulsating logo appears after a while, nothing else) even with this fix

**Comment by Nekotekina** [comment]
@rajkosto Can you check with older build? https://ci.appveyor.com/project/rpcs3/rpcs3/builds/28045640

**Comment by rajkosto** [comment]
I don't know about older build but the one you just committed (15a0ae7) just froze up

**Comment by Nekotekina** [comment]
I posted link to the old build

**Comment by rajkosto** [comment]
And I've tried to make it freeze on loading for the last hour, couldn't do it yet, so it looks like d5e23ca0 is a winner so far.

**Pull request merged**
