### PR TITLE
Fix Full screen in DX12

### PR DESCRIPTION
**Pull request by Zangetsu38**
Fix window Full Screen With Double Left Click on DX12, same before, and same OpenGL.
PR Originel https://github.com/RPCS3/rpcs3/pull/1242

### CODE REVIEW

**Comment by Zangetsu38** [comment]
hmm Travis is Dead ?

**Comment by danilaml** [comment]
Seems that it's just one time connection issue. It failed to download cmake.

**Comment by Nekotekina** [comment]
Fine, but I think double-click must be removed to prevent conflicts with further (possible) mouse usage.

**Comment by Zangetsu38** [comment]
@Nekotekina Yet I find it super convenient, and much better than the "Alt + Enter", which makes me a weird thing with me.
but I do not see how this could conflict, Windows Media Player, VLC etc, do it without problem ^^

**Comment by tambry** [comment]
@Zangetsu38 There's possibility of simulating the PlayStation Move controller using the mouse, which souns completely reasonable. As there are various buttons on the PlayStation Move controller, it would be nice/comfortable to for example click/dragging with click be responsible for the bottom button thingy and double click (and maybe dragging) to also simulate the top button.

I'm sorry if this explanation is a bit bad, since I don't exactly remember what those buttons are on the controller.

**Comment by danilaml** [comment]
@tambry could be changed in the future. The better way to do this would be to provide fullscreen mode, but oGL render doesn't support it yet, afaik.

**Comment by Zangetsu38** [comment]
@tambry hmm I see, in this case, it will just move the mouse does not emulate not, but the move pointer, like Dolphin with the wiimote.

**Comment by tambry** [comment]
@Zangetsu38 I don't understand what you mean.

**Pull request merged**
