### PR TITLE
spujitrsx

### PR DESCRIPTION
**Pull request by jobs-git**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Euuuuuuuuuu ? xD

**Comment by Megamouse** [comment]
ARF

**Comment by Luffykun007** [comment]
lol

**Comment by AniLeo** [comment]
What the hell are you doing

**Comment by elad335** [comment]
oh god lmao

**Comment by Megamouse** [comment]
looks like a reckless attempt to create neko-11 on appveyor

**Comment by jobs-git** [comment]
I was trying to test them combined, I just try on other means.

**Comment by tlm-2501** [comment]
Don't submit PRs for private use. Compile on your own machine or set up your own Appveyor instance, only send PRs for changes that are intended for potential merge with master.

**Pull request closed without merging**
