### PR TITLE
Rsx: Fix for hitman 2

### PR DESCRIPTION
**Pull request by vlj**
This PR adds support for quad strip and fog mode/parameters.
It makes Hitman 2 at least half playable. It's maybe even playable since it seems to work nicely.

### CODE REVIEW

**Comment by vlj** [comment]
The PR seems to fix the giana sister too

**Comment by elfogames** [comment]
:|

ht1
ht2
ht3

**Comment by vlj** [comment]
@elfogames can't reproduce with Intel hd Nvidia or even Microsoft Basic Renderer (the reference renderer) here

**Comment by vlj** [comment]
Fixed gl part. It should work (although lighting is missing, I don't know why).

**Comment by elfogames** [comment]
maybe its a problem with mobile cards (gt 750m)

**Comment by ikki84** [comment]
That screen problem is happening with AMD Radeon R7 200 too.

**Comment by vlj** [comment]
Do you use appveyor build?

**Comment by ikki84** [comment]
yes.

**Pull request merged**
