### PR TITLE
[UI] Grey out AA and Aniso settings under strict rendering

### PR DESCRIPTION
**Pull request by riotflowerpew**
Originally reported in issue https://github.com/RPCS3/rpcs3/issues/7768 

Fixed :

- "Automatic instead" of "Auto" for Anti-Aliasing settings for consistency 
- Grey out Anti-Aliasing and Aniso settings when selecting strict rendering mode

image

### CODE REVIEW

**Comment by riotflowerpew** [comment]
Should anti-aliasing setting be restricted ? Looking at VKRenderTargets it doesn't seem to consider the override at all.

**Comment by AniLeo** [comment]
AA On is the accurate setting, not the other way around

**Comment by elad335** [comment]
I actuall prefer 'auto' over 'automatic', less characters which may be better suited for future settings modifications.

**Comment by Nekotekina** [comment]
"Auto" should be preserved in system config. There are other means to change GUI without touching original config structures.

**Pull request merged**
